### ISSUE TITLE
import/export fit with .xml file from win to mac, fail

### ISSUE THREAD

**Issue by Sipharty** [pyfa-org/Pyfa#1000]
## Bug Report
ok so... i've exported a fit in .xml and my friend is having issues to import it in his pyfa.

my os: window
his: mac

both pyfa version are 1.27
his pyfa start loading the file and then crash
it doesn't happen with only 1 fit/file.
we tried with multiple fits/file

**Comment by Ebag333** [comment]
Can you post  the file here?  You can use https://gist.github.com/ to copy/paste the file contents.

**Comment by Sipharty** [comment]
<?xml version="1.0" ?>
<fittings>
	<fitting name="Revelation Yue">
		<description value=""/>
		<shipType value="Revelation"/>
		<hardware slot="low slot 0" type="Heat Sink II"/>
		<hardware slot="low slot 1" type="Heat Sink II"/>
		<hardware slot="low slot 2" type="Heat Sink II"/>
		<hardware slot="low slot 3" type="Reinforced Bulkheads II"/>
		<hardware slot="low slot 4" type="Reinforced Bulkheads II"/>
		<hardware slot="low slot 5" type="Reinforced Bulkheads II"/>
		<hardware slot="low slot 6" type="Reinforced Bulkheads II"/>
		<hardware slot="low slot 7" type="Damage Control II"/>
		<hardware slot="med slot 0" type="Capital Capacitor Booster II"/>
		<hardware slot="med slot 1" type="Capital Capacitor Booster II"/>
		<hardware slot="hi slot 0" type="Siege Module II"/>
		<hardware slot="hi slot 1" type="Dual Giga Pulse Laser II"/>
		<hardware slot="hi slot 2" type="Dual Giga Pulse Laser II"/>
		<hardware slot="hi slot 3" type="Dual Giga Pulse Laser II"/>
		<hardware slot="hi slot 4" type="Capital Energy Neutralizer II"/>
		<hardware slot="rig slot 0" type="Capital Energy Burst Aerator II"/>
		<hardware slot="rig slot 1" type="Capital Transverse Bulkhead I"/>
		<hardware slot="rig slot 2" type="Capital Transverse Bulkhead I"/>
		<hardware qty="12" slot="cargo" type="Navy Cap Booster 3200"/>
		<hardware qty="3" slot="cargo" type="Conflagration XL"/>
	</fitting>
</fittings>

**Comment by Sipharty** [comment]
sorry no idea how to copy/paste here lol i tried and didn't work out
can this help? https://gist.github.com/Sipharty/6e9b6b8744ebf02e2f71cd6f91ce9d5a

**Comment by Ebag333** [comment]
Works great. Let me take a look.

**Comment by Ebag333** [comment]
Imported okay for me.  Can you provide some environmental information?

- OS type and version
- Path you are trying to import from
- File name of XML

**Comment by blitzmann** [comment]
It's probably a mac issue. I never tested xml imports on osx since the import changes. I'll test them first thing when I get home tonight.

**Comment by Sipharty** [comment]
emh.. need to ask to my friend xD

**Comment by Ebag333** [comment]
No rush. Just want to make sure that we aren't running into different issues here.

There were a _LOT_ of low level changes, and @blitzmann is probably right about it being related to the imports, but more info helps. :)

**Comment by Ebag333** [comment]
Also, congrats on #1000 :D

**Comment by Sipharty** [comment]
legit! you know that something is working as intended when you reach #1000 in issues xD
well done boiz! keep it up ;)

**Comment by blitzmann** [comment]
Confirmed, happens when importing multiple files 

```
Traceback (most recent call last):
  File "C:\Users\Ryan\Sync\Git\blitzmann\Pyfa\gui\shipBrowser.py", line 941, in importStage
    shipTrait = fit.ship.traits.traitText if (fit.ship.traits is not None) else ""
AttributeError: 'Ship' object has no attribute 'traits'
```

This should be an easy fix, working on it now

**Comment by blitzmann** [comment]
Fixed. Going to release an updated release once we get a few more things squared away
