### ISSUE TITLE
graph tool disabled? 1.27 pyfa

### ISSUE THREAD

**Issue by Sipharty** [pyfa-org/Pyfa#1001]
## Bug Report
grahps tool disabled in the menus? it worked till 1.26, then i updated pyfa and now it's like this:
http://i.imgur.com/FZnhCWs.png

os: win7 

other people seems to have the same problem seeing the thread on eve forum

**Comment by Valcyriel** [comment]
I also have same problem. 1.27 graphs button is grayed. 1.26 graphs works fine. 
os: win7 64bit

**Comment by Ebag333** [comment]
Can you click `Help` then `About` and post the screenshot here?

**Comment by Sipharty** [comment]
same pyfa's info for me as well as valcyriel

**Comment by Ebag333** [comment]
Odd. That means it *DID* import.  Why are we turning it off.....?

**Comment by Ebag333** [comment]
It's not disabling it when running from source, with that particular version of matplotlib.

So it's something either in the skeleton, or the check is failing when frozen.....

**Comment by blitzmann** [comment]
@ebag333 have you confirmed the issue is in the build only and can reproduce? If so, I have an idea in a fix.

**Comment by Ebag333** [comment]
Fix submitted in #1002

If you want to monkeypatch your current build, you can do so  with the following steps.
(Make sure Pyfa isn't currently running.)

1. Open `library.zip` in 7-Zip (or another archive program that will let you edit files directly in the zip).
2. Under the folder `gui` find `graphFrame.py`
3. `Right click`, choose `edit`.
4. Replace the file contents with those found here: https://raw.githubusercontent.com/Ebag333/Pyfa/cdf392e3e522c63aea05923477319507a6a3e321/gui/graphFrame.py
5. Close the editor. Save when it prompts you to.
6. 7-Zip will prompt if you want to update the file.  Choose  yes.
7. Close 7-Zip, and relaunch Pyfa.

**Comment by Sipharty** [comment]
thanks for the attention boiz! good guys always doing god work! cheers

**Comment by blitzmann** [comment]
Pulled in the fix that ebag submitted. It reverts a change that we made to not import the required libraries until needed, but it unfortunately wasn't working properly in the builds

**Comment by mna703** [comment]
My graph option is disabled also (greyed out). Here's a screenshot: 
![pyfa](https://cloud.githubusercontent.com/assets/25934948/23177380/97c2419a-f834-11e6-9981-426808434279.jpg)

**Comment by blitzmann** [comment]
Yep, we're aware, new release should come out this week that addresses it.
