### ISSUE TITLE
fleet boosts projection not working

### ISSUE THREAD

**Issue by Yizashi** [pyfa-org/Pyfa#1004]
Hi,

i setup a Damnation fit including 3 scripted armor boosts (all of them).

When i drag that fit to my Nyx fitting it doesn't calculate the armor bonuses reliably. 
I tried turning them on and off in the projection tab of the nyx, the modules on the damnation one time solved it but the next time didn't.

I removed the damnation, draged it in again and created the fitting again but most of the times the EHP value just won't change.

The same happened with a guardian i took for testing wich also wont increase in EHP with the full armor boosts.

thanks for all the work you put in that project by the way =)

**Comment by Ebag333** [comment]
Bursts don't work off the projection tab. You have to use the command tab.

**Comment by blitzmann** [comment]
What @Ebag333 said. If there's any other questions or concerns with the way it works, please let us know here. :)

**Comment by Yizashi** [comment]
Oh, sorry i must have taken the right tab by chance the one or two times it worked then..

Sorry and again thanks for your hard work.
