### ISSUE TITLE
Hide empty ship groups hides to many groups

### ISSUE THREAD

**Issue by Sidoen** [pyfa-org/Pyfa#1005]
## Bug Report
To many ship groups are being hidden when the hide empty ships option is toggled on.

### Expected behavior:
Only ship groups without any fittings in them should disappear

### Actual behavior:
Some ship groups with fittings in them are being hidden. Although if you navigate into the ship group (before hiding empty groups) then you can see and select the ship fittings. If you have done this and then go back to the top level to hide ship groups again that specific ship group will suddenly remain visible.

### Detailed steps to reproduce:
This happened when I installed the latest version of Pyfa. I have also done a clean install (after deleting everything off of the computer other than the XML backups for my fittings).

Uninstall previous program
Delete all left over files from the previous program (with the exception of the backup XML file for fittings stored in the EVE/fittings folder)
Install/Launch the program
Import fittings from the XML backup.
Hide empty ship groups (then notice seemingly randomly missing groups)

Show all groups
Click into a group which should have been visible. (NOTE: At the subgroup window you can hide empty groups again and it will behave properly.)
Select a fitting from a group which wasn't originally visible when hiding groups.
Back out to the top level of ship groups.
Hide empty ship groups again and note that now you have that ship group visible.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
for a specific example a BS fit I'm messing around with happens to be a steady example. I've also changed the name hoping it was some weird parsing issue. I've compared the XML files directly as well and there doesn't appear to be any differences in format between this fit and other fits that behave normally.

[Rokh, Rokh]

Magnetic Field Stabilizer II
Magnetic Field Stabilizer II
Magnetic Field Stabilizer II
Capacitor Flux Coil II
Signal Amplifier II

Large Shield Booster II
Adaptive Invulnerability Field II
Shield Boost Amplifier II
Cap Recharger II
Cap Recharger II
Cap Recharger II

425mm Railgun II
425mm Railgun II
425mm Railgun II
425mm Railgun II
425mm Railgun II
425mm Railgun II
425mm Railgun II
425mm Railgun II

Large Hybrid Collision Accelerator II
Large Capacitor Control Circuit II
Large Capacitor Control Circuit II

Hornet II x5
Hornet II x1
Vespa II x1
Vespa II x1

Caldari Navy Antimatter Charge L x320

### Release or development git branch? Please note the release version or commit hash:
1.27.0 Stable - YC119.2 1.2

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 7

**Comment by blitzmann** [comment]
Thanks for the detailed bug report.

Question: does this happen only after importing fits? There is a known bug that was reported a long while ago in which the number of fits per group isn't properly updated after doing an import (you stated in reproduction steps that you imported the backup file). Can you confirm that this happens when launching pyfa with a database already full of fits?

Thanks

**Comment by Sidoen** [comment]
I have/do restart the program fairly often. The behaviour stays the same.

My comments with respect to the import are mostly to provide full steps
from when it started happening.

Sorry about that I should have added that in.

I have. Not seen any particular issue concerning fit counts, though I'm not
really looking for that so it's possible I'm just missing it.

Not in front of my pc right now otherwise I'd confirm that.

I can follow up later if you like.

**Comment by blitzmann** [comment]
I'll take a look int this soon then. Thanks for the clarifications :)

**Comment by blitzmann** [comment]
I've successfully reproduced the issue on my local database, will start looking into the cause. Hopefully we can get this fixed before the next point release in a couple days

**Comment by blitzmann** [comment]
Well that was easy. We were checking to see if number of fit for that category > 1, instead of > 0. Dumb mistake on my part lol

**Comment by Sidoen** [comment]
Well, that's an easy enough mistake to make, awesome that it was easy to
fix.
