### ISSUE TITLE
Mining Foreman Boosts not increasing yield

### ISSUE THREAD

**Issue by billypoke** [pyfa-org/Pyfa#1007]
## Bug Report

When projecting a fit with mining boosts, the relevant aspects of the ship being projected onto aren't  affected

### Expected behavior:

- Boosting fit has mining boosts with Mining Laser Field Enhancement Charges, the target ship's strip miner range increases.

- Boosting fit has mining boosts with Mining Laser Optimization Charges, the target ship's m3/s increases.

### Actual behavior:

Neither of the above occurs. Range and yield are unaffected

### Detailed steps to reproduce:

1. Use All 5 character to remove any skill conflicts
2. Create a boosting fit with mining boosts active and the charges above
3. Create a mining fit
4. Project the boosting fit onto the mining fit
5. See that the expected attributes are not affected

#### Boosting Fit

```
[Porpoise, NS Miner]

AE-K Compact Drone Damage Amplifier
Damage Control II

Drone Navigation Computer II
Drone Navigation Computer II
Adaptive Invulnerability Field II
Large Shield Extender II

Drone Link Augmentor I
Mining Foreman Burst II, Mining Laser Field Enhancement Charge
Mining Foreman Burst II, Mining Laser Optimization Charge
Auto Targeting System I

Medium Drone Mining Augmentor II
Medium Drone Mining Augmentor II
Medium Drone Mining Augmentor I


Ice Harvesting Drone II x1
Warrior II x5
```

#### Mining Fit

```
[Hulk, Max Yield]

Mining Laser Upgrade II
Mining Laser Upgrade II
Mining Laser Upgrade II

5MN Y-T8 Compact Microwarpdrive
Survey Scanner II
EM Ward Amplifier II
[Empty Med slot]

Modulated Deep Core Strip Miner II, Mercoxit Mining Crystal II
Modulated Deep Core Strip Miner II, Mercoxit Mining Crystal II

Medium Mercoxit Mining Crystal Optimization I
Medium Polycarbon Engine Housing II
```

### Release or development git branch? Please note the release version or commit hash:

Release 1.27.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10

### Other relevant information:

Screenshots

[Boosting Fit](http://imgur.com/No2kVAL)

[Mining Fit Boosting active](http://imgur.com/Z1xssxS)

[Mining Fit Boosting inactive](http://imgur.com/N1D07mE)

**Comment by blitzmann** [comment]
Mother fucker, can we have just one release in which mining boosts work correctly?

props to the bug report though, pretty thorough. Will take a look at it as I can :)

**Comment by ECHRE-Zetakya** [comment]
I can confirm that this also happens with the Orca and the Rorqual. So it's not just a Porpoise issue.

**Comment by blitzmann** [comment]
@billypoke hey, finally had a chance to sit down and actually read the issue. You're projecting the fit, which is not what you want to do. Instead, for fleet / command boosts, you want to drag it over to the Command tab. Going to close this issue assuming that is the problem - if the problem still persists after utilizing the command tab, please reopen and we'll take a look. 

:)
