### ISSUE TITLE
Startup Crash - Null reference in method new_IconFromBitmap

### ISSUE THREAD

**Issue by jlee2109** [pyfa-org/Pyfa#1014]
## Bug Report

I just installed the latest version of Pyfa (1.27.1) on Windows 7 64-bit with the exe installer.  Installation seemed to go fine (wasn't paying close attention), but I can't run the installed program.  When I run, I get the following traceback in an error window:

![image](https://cloud.githubusercontent.com/assets/6528547/23335627/e7261ef0-fb6d-11e6-909e-7c87f2e139ce.png)

The program dies at this point, never opening Pyfa.  I haven't tried anything else.

### Release or development git branch? Please note the release version or commit hash:

It's release YC119.4 - v1.27.1
https://github.com/pyfa-org/Pyfa/releases/tag/v1.27.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 7 64-bit

### Other relevant information:

Seems to be similar to the traceback described on blitzmann's comment (2nd to last) in the discussion here: http://stackissue.com/pyfa-org/Pyfa/handle-unicode-utf8-and-windows-1252-854.html

### Edit 1 

I downgraded to v1.27.0, and the issue is no longer present.  I can run pyfa without issue.  Seems to be a bug created in v1.27.1.

**Comment by blitzmann** [comment]
Can confirm, thanks for pointing this out. Working on a fix and new release pronto

**Comment by jlee2109** [comment]
Note my edit above.  Seems to be a new bug in v1.27.1.
