### ISSUE TITLE
Use unicode strings for path functions

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1017]
After discussion with @Ebag333 on Slack, we believe that using `os.path.join()` with unicode types and avoiding regular string will solve the rest of our locale issues. This issue acts as a reminder for me to do that.

**Comment by Ebag333** [comment]
What  would you think about going through and unicoding all the things?

It seems that's the common practice now.

One advantage to doing that is that if we ever implemented CCP's translations, it'd let use implement them more easily (since we'll need unicode for any strings that  interact with those).

**Comment by blitzmann** [comment]
> What would you think about going through and unicoding all the things?

I don't have an opinion on that either way. I don't know if we'll ever support translations properly, but if we do we could always address this at that time (since we'd be in the code base anyway), or start now and ensure things are correct. Values that we know are always going to be ascii should remain (pretty much anything in `eos` - attributes, groups, etc), as unicode isn't needed for those and creates a bit of overhead.

Before embarking on such a feature, I would suggest spinning up a database that uses a different language and just testing it out and seeing if everything looks more or less proper.

**Comment by blitzmann** [comment]
Closing this as it's irrelevant to current pyfa versions, due to bump to py3 - all string are now unicode, woot!
