### ISSUE TITLE
Drone stacks not correctly contributing to fittings price

### ISSUE THREAD

**Issue by bjjerry** [pyfa-org/Pyfa#1028]
Other than the first drone of a stack, drones do not currently add to the cost of a fitting. To reproduce this bug, add two drones to any fit. The first drone is counted, but the second one isn't. Will poke around some and see what I can find.

**Comment by Ebag333** [comment]
@blitzmann just made a change a month or so ago that stopped it from doing a price lookup for each drone. 

Might be related to that...

**Comment by blitzmann** [comment]
That is almost certainly the cause. I'll investigate. Should be an easy way to fix this.

Thanks for the report!

**Comment by bjjerry** [comment]
Same with cargo, first charge is counted, additional aren't.

**Comment by Ebag333** [comment]
See #1038 for possible solution.

**Comment by blitzmann** [comment]
Thanks to ebag for submitting a fix for this, as well as fixing a long-standing gripe with items not carrying their own price object. see #1115 :D

This will be released with v1.29.0
