### ISSUE TITLE
[1]    12406 segmentation fault (core dumped)  ./pyfa.py

### ISSUE THREAD

**Issue by qnub** [pyfa-org/Pyfa#1036]
## Bug Report

Crashing from time to time on different fit actions. Mostly on add/remove item to/from fit. Sometimes also on fit opening. 

### Detailed steps to reproduce:

Often add/remove item or open fit. When PyFa crashes on fit opening it can crash 2-3 times but then it opens same fit without problem. Maybe it happens when doublecliking items too fast. Not sure.

Last log string in console:

```
[1]    12406 segmentation fault (core dumped)  ./pyfa.py
```
Also sometimes i see

```
Exception in thread HTMLExport:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/media/2TB/gamez/pyfa/gui/utils/exportHtml.py", line 64, in run
    FILE.write(HTML.encode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'encode'
```
In log but program not crashed after it.

PyFa executed as: 

```./pyfa.py```

### Release or development git branch? Please note the release version or commit hash:

pyfa 1.27.2 Stable - YC119.2 1.4

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Ubuntu 16.10 x64

**Comment by blitzmann** [comment]
Do you have Automatically Export to HTML enabled in the preferences? That have been reports through the years that if you have this enabled, and then do fit actions in quick succession, a segfault happens. Try turning it off and see if that helps.

The auto export to html is less useful now with the game browser axed

**Comment by qnub** [comment]
Hm, yes, autoexport was enabled. Will check without it. Thanks!

**Comment by blitzmann** [comment]
Let me know how your testing goes so that I can close the issue :)

**Comment by qnub** [comment]
Yeah, looks stable now. Can't crash it. Thank you 👍

**Comment by blitzmann** [comment]
Sweet, glad to hear it's working :)
