### ISSUE TITLE
DEV: can't open preferences

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1039]
On OS X and Linux. OS X build here:

![image](https://cloud.githubusercontent.com/assets/3904767/23932440/5a884da2-090e-11e7-87be-dcd95cd08c9e.png)

Same error on Linux:

```
python -B pyfa.py -r -d
Traceback (most recent call last):
  File "/home/ryan/Pyfa/gui/mainFrame.py", line 444, in showPreferenceDialog
    dlg = PreferenceDialog(self)
  File "/home/ryan/Pyfa/gui/preferenceDialog.py", line 61, in __init__
    imgID = self.imageList.Add(bmp)
  File "/usr/lib/python2.7/dist-packages/wx-3.0/wx/_gdi.py", line 6735, in Add
    return _gdi_.ImageList_Add(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "(bitmap.GetWidth() >= m_width && bitmap.GetHeight() == m_height) || (m_width == 0 && m_height == 0)" failed at /home/ryan/Desktop/wxPython-src-3.0.2.0/src/generic/imaglist.cpp(66) in Add(): invalid bitmap size in wxImageList: this might work on this platform but definitely won't under Windows.

```

I'll take a look at the new images I added, make sure they're the proper size. Happens on source for Linux, build on OS X, haven't tested source on OS X yet but I expect it to be the same. Windows works fine.

As an aside, I find this funny: `...this might work on this platform but definitely won't under Windows.`

**Comment by blitzmann** [comment]
Ah, well that's easy. The gauge image is 64x64 while we define the image list to 32x32. Should be an easy fix

**Comment by Ebag333** [comment]
>`this might work on this platform but definitely won't under Windows`

Ironically works under Windows and nothing else?

**Comment by blitzmann** [comment]
> Ironically works under Windows and nothing else?

lol yep :D

**Comment by blitzmann** [comment]
fuck, I fucked my project up somehow. need to fix this again

**Comment by Ebag333** [comment]
`[Pyfa] Branch "development" was force-pushed to `1112415` by blitzmann.`

😕

**Comment by blitzmann** [comment]
Yeah, my source control is on my Sync folder, and I think it was doing something right as I committed. Removed every file. Had to revert. :/
