### ISSUE TITLE
Implant sets

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#104]
I'm adding it here for documentary here. I have no plan to implement it myself, however i think it's neat feature to have. If anyone has spare time, i will appreciate your efforts.

So, in general, idea is: you can create implant sets. Implant sets can be assigned to character and fitting. However, when implants from different sources overlap, priorities are as following:

Fit override > fit set > character override > character set (priority descending).

UI-wise i think each implant editor should have implant set specified on top of implant tab, and all inherited implants (for fit - from fit set, from character, from character set) should be shown differently - e.g. with different font color (have no ideas what good solution for this one would be). Non-inherited implants should be shown as usual.

**Comment by blitzmann** [comment]
Closing this as implant set were implemented. Should iterate on it to include "jump clones" but that should be another issue
