### ISSUE TITLE
Implant sets right click context menu no longer opening

### ISSUE THREAD

**Issue by bjjerry** [pyfa-org/Pyfa#1043]
In pyfa 1.28.0 under windows 7 I am no longer able to right click in a fit's Implants tab to load a saved implants set. If memory serves, last version did not have the Variations selection in the right click context menu when selecting an implant that has been added to a fit's Implants, so maybe this bug is related to that.

**Comment by blitzmann** [comment]
@Ebag333 possibly something with the new context menu settings or the variations thing we added?

**Comment by Ebag333** [comment]
```
[2017-03-16 06:18:51.333000] WARNING: service.settings: Failed to get setting for 'itemRemove'. Exception: 'itemRemove'
[2017-03-16 06:18:51.335000] WARNING: service.settings: Failed to get setting for 'implantSets'. Exception: 'implantSets'
```

I've noticed this popping up.

**Comment by Ebag333** [comment]
PR submitted with a fix.  Thanks @bjjerry for reporting this!
