### ISSUE TITLE
OSX - Character Creation Not Responding.

### ISSUE THREAD

**Issue by mossyblog** [pyfa-org/Pyfa#1044]
OSX Version 1.28
-
Removed a character profile to re-add it. 

When creating "new character" pyfa goes into an unresponsive state (ie appearance of a thread lock).

Now unable to add any new character outside the defaults 0 and 5.

**Comment by Ebag333** [comment]
Can you post your log file somewhere?  should be found in your home directory, named Pyfa-<date>.log.

**Comment by blitzmann** [comment]
What OS X version are you running?

**Comment by blitzmann** [comment]
I tested on my OS X 10.7 VM, and I can create a new character fine. pyfa is known to have some problems with the more recent OS X versions, so it would be helpful to know which version you have. But for now, I can't reproduce :(

Additionally, did 1.27.2 work for you?

**Comment by blitzmann** [comment]
@mossyblog any news? It would be helpful to know the OS X version you're working on. :)

**Comment by mossyblog** [comment]
It appears to have resolved itself in the 1.28 latest (ie downloadable via osx).

**Comment by blitzmann** [comment]
kk. If it happens again, simply reopen the issue. Thanks!
