### ISSUE TITLE
Matplotlib error

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1046]
https://forums.eveonline.com/default.aspx?g=posts&m=6874110#post6874110

https://puu.sh/uLgDi/44d2294e40.png

worked in 1.27.0, but not 1.27.2+ (1.27.1 wasn't a thing because I fucked up the build :3)

**Comment by Ebag333** [comment]
#1050 should fix this.

We need to hotfix this into master, because of the import issues, but there's some additional handling for exceptions that happen deep inside matplotlib.

It's not _exactly_ a fix, but at least lets us gracefully handle the failure.

**Comment by blitzmann** [comment]
Thinking it a font cache issue. I'm going to have the user clear up their ~/.matplotlib and see if that helps.

https://github.com/matplotlib/matplotlib/pull/5233

https://github.com/matplotlib/matplotlib/issues/1648/

A new build might also help - I'll try to make that a priority with this next release cycle. TravisCI may actually help with that - I want to research it a bit more.
