### ISSUE TITLE
No option to remove modules in 1.28.0

### ISSUE THREAD

**Issue by jhudson-demandbase** [pyfa-org/Pyfa#1049]
## Bug Report

Unable to remove modules from any fit in 1.28.0 on OSX

### Expected behavior:
Option to _Remove Module_ is shown 

### Actual behavior:
No option to _Remove Module_

![image](https://cloud.githubusercontent.com/assets/15617521/24009100/1e9b0b4e-0a31-11e7-9274-6e6bf524d6bb.png)

### Detailed steps to reproduce:
1. Add module to fit
2. Right-click module

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Claw, GottaGoFast]

Navy Micro Auxiliary Power Core
Navy Micro Auxiliary Power Core
Navy Micro Auxiliary Power Core
Navy Micro Auxiliary Power Core

50MN Digital Booster Microwarpdrive
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

Small Auxiliary Thrusters II
Small Ancillary Current Router II

### Release or development git branch? Please note the release version or commit hash:
v1.28.0
[3b5fc7e](https://github.com/pyfa-org/Pyfa/commit/3b5fc7e13c6e7a43931af8c4f89fb8128856b696)

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
OSX Yosemite (10.10.5)

### Other relevant information:
EVE Data: 1128147
Python: 2.7.10
wxPython: 3.0.2.0
SQLAlchemy: 1.0.9
matplotlib: 1.5.0

**Comment by Ebag333** [comment]
#1047 should address this.

Thank you very much for the incredible bug report!

**Comment by blitzmann** [comment]
Yeah, this is how a bug report should function :D

@Ebag333 you sure the PR addresses this issue as well? The PR deals with implant sets, this one is for removal. Just want to make sure, will test tonight :)

**Comment by Ebag333** [comment]
99.9% sure. As reported on the other issue we dutifully logged two errors importing settings.  So the extra logging worked to catch it, just the meat based computers failed to catch the error.

One was for implantsSets and the other for remove.  I did take care of both in that one PR.

I can submit another PR if you _really_ want me to. Pad my commit counts some more. 😉

**Comment by blitzmann** [comment]
Doh, I see it now. Sorry, was looking at the page on an old screen that has bad color representation, the green lines blend into the white

Thanks :)

**Comment by jlee2109** [comment]
This bug is also present on Windows in v1.28.0.

**Comment by blitzmann** [comment]
> This bug is also present on Windows in v1.28.0.

Yep, we're aware and it's been fixed. I updated the title to reflect that. I will try to get a new release out the door tonight :)
