### ISSUE TITLE
Item filters not resetting on new group selection

### ISSUE THREAD

**Issue by InfiniZ** [pyfa-org/Pyfa#1053]
### Expected behavior: 
When swapping between item groups in the Market Browser, the "Normal/Faction/Complex/Officer" filters at the bottom of the window should be reset to their defaults (Normal is probably best). 

### Actual behavior: 
When swapping item groups, the filter for the previous group is maintained.  

### Detailed steps to reproduce:
Screenshot 1 shows the Drone Upgrades group selected with the Faction filter.  Screenshot 2 then shows me clicking the Rigs group, and going into Armor rigs.  However, no rigs are shown as the Faction filter is still being applied to this newly selected group.

Screenshot 1 - http://imgur.com/Djsv9tp

Screenshot 2 - http://imgur.com/vqodxoi

### Fits involved in EFT format (Edit > To Clipboard > EFT):
N/A

### Release or development git branch? Please note the release version or commit hash:
Release

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
OS X 10.12.3
Ubuntu 16.04

### Other relevant information:
N/A

**Comment by invisusira** [comment]
is THAT why it does this? I've been closing and restarting pyfa for a month now because I thought it was bugged. seriously annoying.

**Comment by DarkFenX** [comment]
Preferences for this have been added in v2.9.0. One of option groups:

![image](https://user-images.githubusercontent.com/275209/66042907-71117c00-e526-11e9-9e9d-0d98dd77f4a9.png)

While default is not "Normal" but "All", i think it is acceptable.
