### ISSUE TITLE
(CREST) Can't Export Fit to Eve - unsupported type

### ISSUE THREAD

**Issue by gscottnelson** [pyfa-org/Pyfa#1060]
On multiple Mac computers, I am getting this same error message...see attached screen shot.   I get it when I get the modal window clicking "Export Fit to Eve"
![screen shot 48](https://cloud.githubusercontent.com/assets/10010885/24075428/704c4d5e-0be9-11e7-8429-8c626d3813ba.png)

**Comment by Ebag333** [comment]
I tried recreating this couldn't get any errors.

Can you post your exact EFT fit here?

Also, can you post your pyfa.log file?

**Comment by blitzmann** [comment]
So, from that error, it looks like we're trying to send a float instead of an int/long. Should be an easy case of `int(value)`, just need to know what exactly need the treatment. EFT fit would help, but I may need the database itself later.

**Comment by blitzmann** [comment]
I got it to reproduce, will be looking into it. Has to do with charges

**Comment by blitzmann** [comment]
Fix was easy, see commit. I can't think of any scenario in which we need to return anything but an int for `numCharges` so I add it there.
