### ISSUE TITLE
Council Diplomatic Shuttle not available

### ISSUE THREAD

**Issue by BartMassey** [pyfa-org/Pyfa#1061]
Pyfa does not provide the Council Diplomatic Shuttle. Yes, I know that it has zero fitting slots :-). But it would be nice to be able to look at its characteristics out-of-game when playing with stuff, and I'm guessing it would be easy to add?

**Comment by blitzmann** [comment]
I can add it easily. It's forcefully being hidden, and has the note of `CSM X celebration` next to it. What is this ship and is it available to players (I assume not)?

If anything, it would go in the custom Limited Edition ship group since it's not something players would normally be  able to get.

**Comment by BartMassey** [comment]
The Council Diplomatic Shuttle is widely available to players, as blueprints were given to everybody a while back. It goes for less than 1M ISK right now, so not too rare. <https://eve-central.com/home/quicklook.html?typeid=34496> I think the shuttle group is in fact the right place for it. (This is also where it lives in-game.) Thanks.

**Comment by Kyria** [comment]
https://community.eveonline.com/news/dev-blogs/in-celebration-of-csm-x/ for "where it comes from" :)

**Comment by BartMassey** [comment]
Thanks!

Why did you comment out the fitting test in your patch? I can't see anything in there that was related, but I am probably missing something.

**Comment by Ebag333** [comment]
>Why did you comment out the fitting test in your patch? I can't see anything in there that was related, but I am probably missing something.

Because he couldn't get that test to work.  Works locally but not on Travis-CI.  vOv
