### ISSUE TITLE
Backup solutions

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#1066]
Something that I've been thinking about lately....Git isn't a backup solution.  Yes the repo lives on many computers, but all it takes is one bad push/merge/reset/rebase/etc and you can lose a lot of history.

So, we should probably find an actual backup solution.  Shouldn't cost much/anything since we're talking about 30 megs worth of stuff.

Note to self: research backup solutions for Git.

**Comment by blitzmann** [comment]
Is it possible to fuck up the repo beyond help? Sure. If I make a new, fresh repo, make a single commit, and then force push that to pyfa-org/master, that would be a huge problem. But this isn't something that really needs to be worried about long term without the existence of a malicious user with write access. Additionally, I would assume any sort of automated backup system would be affected by any changes that fuck up the repo anyway, unless it does archived backups.

But if you're interested in looking at some sort of git mirror, sure thing. Can't hurt. :)

Also, I just (re-)enabled protection on the dev and master branch, which apparently "Disables force-pushes to this branch and prevents it from being deleted". Pretty nifty. I'm still trying to get you access btw, for some reason your name doesn't pop up in the "allow these folks to commit to branch" thing.

**Comment by Ebag333** [comment]
>But this isn't something that really needs to be worried about long term without the existence of a malicious user with write access. 

I just spent over half an hour helping someone in devfleet who had the same problem we did last night.  The user wasn't malicious, just didn't understand how hard resets and force pushes work.

You could do a lot of damage without easily being caught (intentionally or otherwise), even just by submitting a PR that gets merged in (since the merge will take in your alternative history).

>Additionally, I would assume any sort of automated backup system would be affected by any changes that fuck up the repo anyway, unless it does archived backups.

A backup solution without versioning is pretty useless. :)

A versioned backup would have been useful last night, because we could have pulled the backups from before the force push, and validate the commits before/after.

**Comment by Ebag333** [comment]
@blitmann this looks like a good solution:
backhub.co

Doesn't seem to be a charge for the service.

**Comment by blitzmann** [comment]
I've got it going on pyfa-org now. Dunno if I can share links for backups or anything, will see once it completes
