### ISSUE TITLE
Debug statements printing for linux without logging flag

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1067]
@Ebag333 you may have a quick fix for this. On current master (fd745c5f623b71be628b89e98aba682b4b180b41), running pyfa on Mint:

`python -B pyfa.py`

no `--debug` or `--logging` arguments, however, debug logs still print.

![image](https://cloud.githubusercontent.com/assets/3904767/24324780/bd618234-1162-11e7-83c6-be7bb032538d.png)

Additionally, the configforce not being there should probably be a debug, instead of a warning.

**Comment by blitzmann** [comment]
Can confirm this does not happen in Windows.

**Comment by Ebag333** [comment]
Can you use the new `pyfa.py` from #1048 and see what the info messages give for environment?

**Comment by minlexx** [comment]
May those logging messages be printed before logging was fully initialized (stdout/stderr redirected)? I guess those message are printed somwhere near initialization of database (during import eos.db or something like that)? Before the line that finally setups logging.

**Comment by Ebag333** [comment]
`with logging_setup.threadbound():` is where we initialize logging.  No logging messages can be printed until after that statement.

Hmm, gives me an idea where it might be coming from though....

**Comment by blitzmann** [comment]
This actually seems to be due to the fact that I was using Logbook < v1.0.0 (forgot to update back to 1.0.0 from testing with #1052)
