### ISSUE TITLE
Projecting Linked Guidance Disruptors yields wrong result

### ISSUE THREAD

**Issue by lunedis** [pyfa-org/Pyfa#1081]
# Submit a bug report bug report or feature request
### Expected behavior:
Missile range should show 94km * (1-0.381)^2 = 36km

### Actual behavior:
Missile range is 94km * (1-0.309)^2 = 45km

30.9% is the GD strengh without link

### Detailed steps to reproduce:

Apply Proteus Links to Crucifier.

Project Crucifier onto Caracal

### Fits involved in EFT format (Edit > To Clipboard > EFT):

```
[Crucifier, Crucifier fit]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

Guidance Disruptor II, Missile Range Disruption Script
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]
```
```
[Caracal, Caracal fit]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
Heavy Missile Launcher II, Caldari Navy Scourge Heavy Missile
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]
```
```
[Proteus, Boost]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Information Command Burst II, Electronic Hardening Charge
Information Command Burst II, Sensor Optimization Charge
Information Command Burst II, Electronic Superiority Charge
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

Medium Command Processor I
Medium Command Processor I
[Empty Rig slot]

Proteus Engineering - Augmented Capacitor Reservoir
Proteus Defensive - Warfare Processor
Proteus Offensive - Dissonic Encoding Platform
Proteus Propulsion - Gravitational Capacitor
Proteus Electronics - Dissolution Sequencer


Information Command Mindlink
```

### Release or development git branch? Please note the release version or commit hash:
1.28.1 Stable

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 7

**Comment by blitzmann** [comment]
I can confirm the issue, thanks for the detailed information! :)

it indeed does seem that the command ship boost is not affecting the Crucifier when projected (or, more likely, it's affecting the modules *after* it's being applied to the Caracal). This is going to take some time to dig into, will keep my notes here. :)

**Comment by blitzmann** [comment]
So, as I thought, the command effect is being applied to the module correctly, but only after the module is projected. Relevant code:

https://github.com/pyfa-org/Pyfa/blob/fd745c5f623b71be628b89e98aba682b4b180b41/eos/saveddata/fit.py#L750

That `for item in c:` block runs through the modules and does three things:
* Applies  module effects to the local fit
* Applies modules effects to a remote fit (if projected)
* Applied module effects to a boosted ship (if boosted).

In the case of the Crucifier, the command boosts that the Proteus emits aren't applied until `self.__runCommandBoosts(runTime)`, which is unfortunately after the projected effect is already applied to the base fit.

I have made a commit that fixes the issue by removing the projection code out of the main `for` loop, and creates a new `for` loop after the command effect code is run. I do want to take another peak at it in a few days to see if there's any fat we can trim with that code now being in it's own block (for example review the items that are chained to see if there's anything unnecessary that's currently being run for projections, such as character that I didn't bother to put brain cycles towards tonight). But for now this seems to fix the issue and works well.
