### ISSUE TITLE
Calculations

### ISSUE THREAD

**Issue by hulseinator** [pyfa-org/Pyfa#1082]
# Submit a bug report bug report or feature request

Here you can inform pyfa developers of potential bugs or suggest features / improvements to the project. Please check
to make sure that the bug hasn't been reported or feature requested before submitting. If you have general questions
about the project and want to reach out to the developers personally, please check out out our [Slack]
(https://pyfainvite.azurewebsites.net/).

---

## Bug Report:
***UPDATE***
Pyfa Calculations were perfect, I on the other hand am not. I'm just as shocked as you are. Sorry for wasting your time.

Fitting a Wreathe

### Expected behavior:
installed two Inertial Stabilizer II in pyfa and got a Align Time of 6.96s

### Actual behavior:
in game installed two inertial stabilizer II and got an Align time of 4.64s

### Detailed steps to reproduce:
Using my specific character API i selected the Wreathe Ship in Pyfa
Installed the fits below in both pyfa AND in game with different align time results.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Wreathe, Ron Jeremy]

Inertial Stabilizers II
Inertial Stabilizers II
Expanded Cargohold II
[Empty Low slot]
[Empty Low slot]

50MN Y-T8 Compact Microwarpdrive
Limited 'Anointed' EM Ward Field
Limited Thermal Dissipation Field I
Limited Adaptive Invulnerability Field I
Medium Shield Extender II

Improved Cloaking Device II
[Empty High slot]

Medium Cargohold Optimization I
Medium Cargohold Optimization I
Medium Cargohold Optimization I

### Release or development git branch? Please note the release version or commit hash:
pyfa 1.28.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win 10

### Other relevant information:
In game character Hulseinator, you may contact me in game if needed.

**Comment by Ebag333** [comment]
>in game installed two inertial stabilizer II and got an Align time of 4.64s

What are you looking at and how do you know you get an align time of that in game?

**Comment by blitzmann** [comment]
@hulseinator can you send me a copy of your database to sable.blitzmann@gmail.com? it's found in `%userprofile%\.pyfa\saveddata.db`. This will give me access to your skills so that I can properly identify the issue.

Also please double check any implants your character might have, command boosts that may be applied, etc. Basically make sure that nothing else is applying to your ingame fit that may have been overlooked in pyfa.

Also, as @Ebag333 suggests, where are you getting align time in the game? Screenshots ftw :)

**Comment by lunedis** [comment]
Also remember that align time with MWD on and with MWD off is different.

**Comment by hulseinator** [comment]
I will recheck by Turing the med off whilst in station and get back with you


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Karl Werner <notifications@github.com> Date: 3/30/17  6:39 AM  (GMT-05:00) To: pyfa-org/Pyfa <Pyfa@noreply.github.com> Cc: hulseinator <joehulse@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [pyfa-org/Pyfa] Calculations (#1082) 
Also remember that align time with MWD on and with MWD off is different.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pyfa-org/Pyfa","title":"pyfa-org/Pyfa","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/pyfa-org/Pyfa"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lunedis in #1082: Also remember that align time with MWD on and with MWD off is different."}],"action":{"name":"View Issue","url":"https://github.com/pyfa-org/Pyfa/issues/1082#issuecomment-290373218"}}}

**Comment by hulseinator** [comment]
Thank you all for your advice and I did make the adjustments in Pyfa (turning off the MWD) and it did adjust the align time to reflect more accurately the actual in game align time. I'm satisfied with the margin of error at this point but I'm sure your more interested in providing a more accurate calculation. I have attached screen shots.
![pyfa calculation](https://cloud.githubusercontent.com/assets/26777516/24521148/1bd7bbf4-1559-11e7-8910-54148b657095.png)
![calculation](https://cloud.githubusercontent.com/assets/26777516/24521156/228398ec-1559-11e7-8302-0dd28bba1b75.png)

**Comment by hulseinator** [comment]
Wait....today is my monday correcting PYFA

**Comment by hulseinator** [comment]
Okay, I was wrong. Y'all are spot on!  Keep up the great work...pouring myself another cup of coffee.

**Comment by blitzmann** [comment]
> Y'all are spot on! Keep up the great work

k... I'll assume this can be closed then :) :P
