### ISSUE TITLE
Implant effect on grid usage not always correctly updated

### ISSUE THREAD

**Issue by BartMassey** [pyfa-org/Pyfa#1090]
## Bug Report

When changing fit-specific power grid implant using the "Variations" menu, the powergrid displayed for the fit does not always update.

### Expected behavior:

Whenever a fit-specific powergrid implant is added, removed or changed, the powergrid usage displayed by Pyfa updates to match the new grid.

### Actual behavior:

Under some circumstances, increasing or reducing the powergrid implant level does not result in a change of displayed powergrid.

### Detailed steps to reproduce:

1. Take my Capital Shield Extender Dominix below (please!) and an All 5 character.

2. Use "Variations" to change the EG-606 to an EG-605. Note that the powergrid usage rises from 99.94% to 105.93%, which is clearly wrong.

3. Disable and re-enable the Shield Extender by left-clicking on the circle.

5. Note that the grid usage is now correctly displayed as 100.89%.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

```
[Dominix Navy Issue, Capital Shield BS]

Dark Blood Reactor Control Unit
Dark Blood Reactor Control Unit
Dark Blood Reactor Control Unit
Dark Blood Reactor Control Unit
Dark Blood Reactor Control Unit
Dark Blood Reactor Control Unit
Dark Blood Reactor Control Unit

Capital F-S9 Regolith Compact Shield Extender
'Basic' Capacitor Recharger
EM Ward Field II
Thermal Dissipation Field II
Adaptive Invulnerability Field II
Adaptive Invulnerability Field II

Dual 250mm Prototype Gauss Gun, Caldari Navy Antimatter Charge L
Dual 250mm Prototype Gauss Gun, Caldari Navy Antimatter Charge L
Dual 250mm Prototype Gauss Gun, Caldari Navy Antimatter Charge L
Dual 250mm Prototype Gauss Gun, Caldari Navy Antimatter Charge L
Dual 250mm Prototype Gauss Gun, Caldari Navy Antimatter Charge L
Dual 250mm Prototype Gauss Gun, Caldari Navy Antimatter Charge L

Large Ancillary Current Router II
Large Ancillary Current Router II
Large Anti-Kinetic Screen Reinforcer II


Inherent Implants 'Squire' Power Grid Management EG-606
```

### Release or development git branch? Please note the release version or commit hash:

Release version 1.28.1 Stable - YC119.3 1.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Debian testing (Stretch).

**Comment by Ebag333** [comment]
Fantastic bug report. Sounds like variations aren't always triggering a refresh. 

Might be a timing issue, the variations for implants are slow I've noticed before.

**Comment by blitzmann** [comment]
Thanks for the detailed bug report as always @BartMassey. This was a pretty simple fix - we weren't recalculating the fit correctly, seems to have been an oversight. Should be fixed with the next release. :)
