### ISSUE TITLE
Capital modules can be fit on subcapital ships

### ISSUE THREAD

**Issue by BartMassey** [pyfa-org/Pyfa#1096]
## Bug Report

Pyfa allows fitting a capital module to a subcapital ship. In-game (at least on Singularity) this is not allowed.

### Expected behavior:

Pyfa refuses to allow fitting a Capital F-S9 Regolith Compact Shield Extender to a Dominix Navy Issue.

### Actual behavior:

Pyfa allows fitting a Capital F-S9 Regolith Compact Shield Extender to a Dominix Navy Issue.

### Detailed steps to reproduce:

1. Get a Dominix Navy Issue hull.

2. Fit a Capital F-S9 Regolith Compact Shield Extender.

### Release or development git branch? Please note the release version or commit hash:

1.28.1 Stable - YC119.3 1.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Debian Testing (Squeeze)

**Comment by blitzmann** [comment]
These items don't have any attributes to restrict their use to certain ships. I think I remember this coming up at some point, and it was thought that this is actually something CCP hardcodes into the game, and isn't available via item attributes. Basically if it's a capital-sized module (defined as having a volume >4k), then they throw an error in the client stating that you can't do that.

I think we left it alone at that point as it's not something that's very detrimental to pyfa functioning correctly. However, I'll double check the issues to see if I can find any mention of this. Could you provide a screenshot of the error the client gives?

@Ebag333 could you maybe chat with Larrikin and see if you can get a firm answer on how this is handled? As stated, it's been discussed before that this is based on the volume of the module. Would be nice to know even if we choose not to implement it. :)

**Comment by BartMassey** [comment]
![capital-shield-on-subcap](https://cloud.githubusercontent.com/assets/117151/24588520/c50c8eda-177e-11e7-925a-50d3911136f6.png)

**Comment by blitzmann** [comment]
hahaha :)

Well, based on current assumptions (capital module is defined as having a volume >= 4000), we can easily restrict capital modules from being fitted onto subcap hull:

https://github.com/blitzmann/Pyfa/commit/3274130c78676a3bf1b533ebde8a95072b89a131

This prevents pyfa from even adding the module to the fit. To be able to add it, but cause some sort of warning, would be a lot more work without any real benefit methinks.

I want to dig a bit further to make sure this is indeed how things are defined before implementing it though.

**Comment by blitzmann** [comment]
> CCP Larrikin [12:34 PM] 
>@blitzmann its a hard coded thing on the server, anything over 4k m3 can't bit fit to non-capitals.

And with that, I get my answer. :D
