### ISSUE TITLE
Delete All for Damage Pattern and Target Resists

### ISSUE THREAD

**Issue by Hiwashi** [pyfa-org/Pyfa#1119]
There's an Import/Export for Damage Patterns and Target Resists but no way to delete all of them at once, making it very time consuming to remove everything if you have several patterns.

**Comment by Ebag333** [comment]
@blitzmann can pull this PR: https://github.com/Pyfa-fit/Pyfa/pull/22

**Comment by blitzmann** [comment]
Thanks @Ebag333 

Fixed it up, tested, included. @Hiwashi, should be available in the 1.29 release. :)

**Comment by blitzmann** [comment]
@Hiwashi out now with v1.29 :)
