### ISSUE TITLE
Related Skills not Included in "Change Module Skills" of Shield Boosters

### ISSUE THREAD

**Issue by zhudhjen** [pyfa-org/Pyfa#1126]
“Shield Compensation” is not currently included in "Change Module Skills" context menu of shield boosters in Pyfa. The skill reduces capacitor need of shield boosters, and it is included in "Affecting Skills" in EFT. 

Screenshot from EFT:
![image](https://cloud.githubusercontent.com/assets/3236031/25041160/b74c8310-2140-11e7-94b5-0120a5fd0652.png)

Screenshot from Pyfa:
![image](https://cloud.githubusercontent.com/assets/3236031/25041162/bd646182-2140-11e7-946c-7729bfe45aa5.png)

Pyfa version: 1.28.1 Stable - YC119.3 1.0

Edit:
Changing character to "All 5" makes that skill show up, and it seems that my character had not learned that skill. So the skill is indeed related. However, I do want to know what skills are useful for that module. Can we show the skill even if it is not already learned?

Edit 2:
Changing the character back to myself (skill not learned) and I found the skill keeps in the list, showing not learned. It seems to be a bug, but I am currently not able to reproduce it.

**Comment by blitzmann** [comment]
Thanks for the report, I'll take a look at this soon. The affecting skills code is very much hacked together, so I'm not surprised this is a thing lol

**Comment by blitzmann** [comment]
Related to #1192, gonna close this issue and track progress there. :)
