### ISSUE TITLE
Fighters maximum velocity not correct

### ISSUE THREAD

**Issue by dado023** [pyfa-org/Pyfa#1128]
This is what Pyfa shows:  ![pyfa_2017-04-17_03-58-34](https://cloud.githubusercontent.com/assets/27656063/25076618/baf96076-2322-11e7-93d5-4912703b005a.png)

and this is what in game shows: 
![exefile_2017-04-17_04-02-22](https://cloud.githubusercontent.com/assets/27656063/25076622/c53eb37e-2322-11e7-9191-e8b8013b50e7.png)

I hope this can be fixed.

Cheers

**Comment by Ebag333** [comment]
Which fighter is this? 

What's the fit of the carrier?

**Comment by dado023** [comment]
Nidhoggur + 2xDrone Navigation Computer II + 3xFighter Support Unit II

**Comment by Ebag333** [comment]
And which fighter?

Dragonfly II is closest in speed, but not the one you have selected.

**Comment by dado023** [comment]
@Ebag333 its Templar I

**Comment by blitzmann** [comment]
@dado023 What are the skill levels involved? I believe Minmatar Carrier, Drone Navigation, and Light Fighters are the ones that affect the speed for this particular setup.

Also, in the future, it would be helpful if you could post the EFT fitting of it. Just makes it easier.

With an All 5 character I'm showing 2824, which is almost equal to the value you state you get in the client. 

![image](https://cloud.githubusercontent.com/assets/3904767/25077022/2f784e3c-22f4-11e7-95f4-d638e564d29d.png)

**Comment by dado023** [comment]
@blitzmann yes, i get the same results in Pyfa, but in game speeds are higher.

**Comment by blitzmann** [comment]
> @blitzmann yes, i get the same results in Pyfa, but in game speeds are higher.

But your pyfa screen shows 2651... >_>

As for the small discrepancy in 2824 vs 2888, will take a look. I would would recommend removing all affecting modules from the fit in game and see if, from just your skills, you get a value that matches pyfa. From there, we can try to pinpoint where the calc is going off by slowly adding on additional modules.

**Comment by blitzmann** [comment]
Also (and off topic), you have very pretty screenshots. Which program is that?

**Comment by dado023** [comment]
@blitzmann i am using [https://getsharex.com/](https://getsharex.com/)

**Comment by blitzmann** [comment]
@dado023 ah, thanks!

Anyway, yeah, if you can do some research on your end by removing modules from in game and pyfa and seeing where it goes wrong, that would be great. If not, I'll log into SISI tomorrow to poke around at it and see what I can find. :)

**Comment by dado023** [comment]
k, i just striped in game 3xFighter Support Unit II and i get the same speed in pyfa as well without those modules.....so, i am assuming there is something wrong with calculation related to _Fighter Support Unit II_ modules

**Comment by blitzmann** [comment]
Thanks, that helps narrow it down. :)

Will let you know when there is a fix for it.

**Comment by dado023** [comment]
k, i just did manual calculation following these penalties:

1st mod: 100.0% effectiveness
2nd mod: 86.9%
3rd mod: 57.1%
4th mod: 28.3%
5th mod: 10.6%

**I get exact same result in my calculator as it is in Pyfa....huh.**
 It looks like game does wrong calculation, or modules are regarded as different type...wird

**Comment by blitzmann** [comment]
Yeah, not sure... I turned stacking penalties off just to see, and pyfa shows 3177 now, which is totally not correct.

Can you post the ingame and pyfa values for 1, 2, and 3 FSUs? I can then take that data to some ccp devs and try to figure out what's going on.

**Comment by blitzmann** [comment]
Also, I'm assuming that after you remove the FSUs you're also getting 2668 for the speed of the Templar I's?

**Comment by dado023** [comment]
@blitzmann with all FSUs removed, i get 2504 
![image](https://cloud.githubusercontent.com/assets/27656063/25077658/4260570a-232c-11e7-8761-ffb357e535a5.png)

**Comment by dado023** [comment]
@blitzmann oh, please dont, then CCP will fix/nerf it, so fighters will be slow :(

**Comment by dado023** [comment]
in any case, those 3 FSUs are calculated as 3 modules, not as including 2xDNC for total of 5 velocity modules, .....

Following FSU calculation penalties:

1st mod: 100.0% effectiveness
2nd mod: 86.9%
3rd mod: 57.1%

and 

Following DNC calculation penalties:
1st mod: 100.0% effectiveness
2nd mod: 86.9%

**Comment by blitzmann** [comment]
> @blitzmann with all FSUs removed, i get 2504

This is not what I get in pyfa...

Can you list your skill levels for these:

Minmatar Carrier
Drone Navigation
Light Fighters

**Comment by dado023** [comment]
Minmatar Carrier 4
Drone Navigation 4
Light Fighters 4

**Comment by blitzmann** [comment]
ah, that could explain some things. Give me a sec to plug those in

**Comment by blitzmann** [comment]
BTW, DNC required level 5 Drone Navigation... so how are you able to fit this in game?

**Comment by dado023** [comment]
oh sry, indeed, i have Drone Navigation 5

**Comment by blitzmann** [comment]
Okay... so to summarize

```
[Nidhoggur, Nidhoggur fit]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

Drone Navigation Computer II
Drone Navigation Computer II
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Fighter Support Unit II /OFFLINE
Fighter Support Unit II /OFFLINE
Fighter Support Unit II /OFFLINE
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]


Templar I x9
```

Having the the FSUs offline gets me 2504, same as you. So we're on the same page with that. :)

Can you get me the numbers from both pyfa and in game having 1 FSU online, then 2 FSU, then 3 FSU? I want to see what sort of discrepancy there is with successive modules being onlined. 

Thanks for taking the time to troubleshoot this with me :)

**Comment by dado023** [comment]
as i mentioned here https://github.com/pyfa-org/Pyfa/issues/1128#issuecomment-294397157

For FSUs just follow the penalty factors.

**Comment by blitzmann** [comment]
Ah, thanks. Sorry, misinterpreted that comment. 

However, I think I've got it:

![image](https://cloud.githubusercontent.com/assets/3904767/25078022/23f5afec-22fd-11e7-8acc-4df597ea3b55.png)

:D

I still need to play around with it to ensure this is the proper fix, but I know what's going on now. Thanks again for looking into this with me. I may have a few more questions as I progress

**Comment by dado023** [comment]
Oh well, english isn't my native language...i am trying my best :) .......looking at your screenshot, new equation seems to output correct velocity.

**Comment by blitzmann** [comment]
No problem at all man, thanks for the bug report :)
