### ISSUE TITLE
Amarr/Gallente Alpha Skills missing

### ISSUE THREAD

**Issue by MrG01** [pyfa-org/Pyfa#1131]
## Bug Report
Amarr and Gallente alpha presets, lack their respective skills marked.
This is not the case for Caldari and Minmatar.
As can be seen from the images below.

### Expected behavior:
![minmatar alpha](https://cloud.githubusercontent.com/assets/13038237/25131813/74b4fb04-2447-11e7-8144-adf41b66baae.PNG)

### Actual behavior:
![amarr alpha](https://cloud.githubusercontent.com/assets/13038237/25131765/459f26fa-2447-11e7-8c35-2dbb13d6f342.PNG)
![gallente alpha](https://cloud.githubusercontent.com/assets/13038237/25131780/4f06676c-2447-11e7-817b-6dfcaa021727.PNG)

### Detailed steps to reproduce:

1. Open Character Editor
2. Add new character
3. Select either Amarr or Gallente alpha preset
4. Check any skills

### Release or development git branch? Please note the release version or commit hash:
Release 1.28.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
None

**Comment by blitzmann** [comment]
Hmm, will have to take a look. That data is collected directly from the game files, so it's odd that it doesn't work. Thanks for the info :)

**Comment by blitzmann** [comment]
Question: does the character already have those skills trained?

The way alpha clones work in pyfa is that it sets a level cap for the already-trained character skills, based on which alpha character you choose. It doesn't apply the alpha skills to the character.

So, if I have Amarr Cruiser V, and I select Amarr alpha clone, I'll have an effective Amarr Cruiser IV. But, if I have Amarr Cruiser II and select the Amarr clone, I'll still only have level 2.

Can you verify this is what is happening in your case?

**Comment by blitzmann** [comment]
@MrG01 Can you verify the above? If you're character has those skills and the alpha clone is still showing not applied, then that could be an annoying issue. Let me know  :)

**Comment by MrG01** [comment]
Hi @blitzmann ,

Sorry for the delay.

So after some testing, i can confirm that the system does work as you have explained above. 
Whereby, it simply limits the skills to those of an alpha, but does not imprint those skills on a new blank character.

**Comment by blitzmann** [comment]
@MrG01 No worries! Thanks for the clarification. I can see why a user would want to fit for a generic alpha character. Right now, it's strictly for "oh shit my sub lapsed, what can I fly" instead of mocking up fits for unsubbed newbies. In the meantime, to emulate the functionality you're looking for, copy the All 5 Character and apply the Alpha Clone to that. That should tie you over until a more permanent solution is implemented. :)

**Comment by MrG01** [comment]
Upon typing my reply, i was thinking about that very same workaround, whereby you just copy the ALL 5 char and then limit it using presets.

Thanks for responses.

**Comment by blitzmann** [comment]
Closing this issue:

* There's another issue floating around to create a character as a "base" character, instead of doing the lvl 5 copy + alpha workaround
* Alpha skills no longer discriminate on race

Thanks!
