### ISSUE TITLE
Ancillary Remote Repairer shows incorrect HP/s when Nanite is loaded

### ISSUE THREAD

**Issue by dmsft** [pyfa-org/Pyfa#1135]
Pick any ship (e.g. Myrmidon) and fit an ancillary remote repairer into the high slot (small or medium). Without nanite paste loaded the "remote reps" section shows correct HP/s value. The moment nanite is loaded this amount is reduced by approximately factor of 3, instead of being increased.

Tested on Pyfa 1.28.1 Stable - YC119.3. 1.0

**Comment by blitzmann** [comment]
Excellent find, and thanks for the fix @Ebag333. :) 

Will get this merged in tonight

**Comment by blitzmann** [comment]
@dmsft Out with v1.29.0 :)
