### ISSUE TITLE
Capital Industrial Ship skill not being applied to Rorqual

### ISSUE THREAD

**Issue by Dominus787** [pyfa-org/Pyfa#1137]
# Capital Industrial Ship skill not being applied to Rorqual

The Capital Industrial Ship skill bonuses appear to not be applying to the Rorqual for command bursts. For instance, it appears that the skill bonus "5% bonus to Mining Foreman Burst effect strength and duration" is not being affected by the Capital Industrial Ship skill.

---

### Detailed steps to reproduce: 

1. Create fit with one Mining Foreman Burst with or without script
2. Have character set to "All 0"
3. Right click for module stats and see attribute warfareBuff#Value=1.25 (Base Value)
4. Right click module and change skill of Capital Industrial Ship from 0 to 5
5. Refresh or re-open Module Stat screen (if closed) and see the warfareBuff#Value=1.25 (still base value)

### Fits involved in EFT format (Edit > To Clipboard > EFT):

[Rorqual, Boost]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Mining Foreman Burst II
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:

pyfa release 1.28.1 Stable

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10

### Other relevant information:

Also tested using all other relevant command burst modules, including all other shield and mining bursts.

**Comment by blitzmann** [comment]
Hi there! Thanks for the report. I believe that has already been fixed in dev (possibly master), see #892

But I will double check tonight when I get home.

In the meantime you can try this build and let me know if it works for you. This is auto-generated on the master branch, which contains releases and any bugfixes in between: https://ci.appveyor.com/api/buildjobs/6ipmt7197qyyy8bm/artifacts/pyfa.zip

**Comment by blitzmann** [comment]
Ah, just realized that fix was actually included in the 1.27.* releases. So maybe this isn't fixed. Will check tonight :)

**Comment by blitzmann** [comment]
Yep, looks like it was applying to the wrong attribute (one that doesn't even exist lol). This has now been fixed. You can get an updated build here if you're interested in utilizing the fix / testing it out :)

https://ci.appveyor.com/api/buildjobs/gvtjjnrbmit3mssu/artifacts/pyfa.zip
