### ISSUE TITLE
Pyfa freezes when fitting module

### ISSUE THREAD

**Issue by lord-carlos** [pyfa-org/Pyfa#1140]
## Bug Report

When I try to fit a module, or open up an old fitting the UI just freezes. No error in the terminal.
Fitting a drone works.
I tried with a clean DB and ~.pyfa and redownloaded the git source.

Might it be because of an older Logbook version?
Logbook version >= 1.0.0 is recommended. You may have some performance issues by continuing to use an earlier version.

### Actual behavior:
Pyfa freezes.

### Detailed steps to reproduce:
rm ~.pyfa -rf
pyfa
new fitting
add module

### Release or development git branch? Please note the release version or commit hash:
Git bedd6efff2a187295696ef91c2b96c6c178052a0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Debian stable
Distributor ID: Debian
Description:    Debian GNU/Linux 8.7 (jessie)
Release:        8.7
Codename:       jessie

### Other relevant information:
python-logbook:all/jessie 0.7.0-1 uptodate

**Comment by blitzmann** [comment]
> Might it be because of an older Logbook version?

Probably. The issue with previous logbook versions is that it gobbled memory. I'm plan on making logbook 1.0 a minimum requirement instead of just a suggestion. Please upgrade logbook and let me know if the issue still persists. :)

**Comment by blitzmann** [comment]
@lord-carlos any luck?

**Comment by lord-carlos** [comment]
@blitzmann 
I installed python-logbook (0.12.3-1) from debian testing repo. https://packages.debian.org/stretch/python-logbook

I still get the warning, but it seems to work. But I only have time for a super quick test right now. Will test more later.

**Comment by blitzmann** [comment]
@lord-carlos thanks for the info. I know v0.9.1 has issues with memory, and I know v1.0 is stable. I'll try to test out tonight which is the lowest stable version that we can use and make that the requirement (there's a few versions between 0.9.1 and 1.0, such as the one you have, 0.12.3). Let me know how your extended tests go :)

**Comment by blitzmann** [comment]
kk, double checked some versions, and 0.10.0 seems to be the minimum that works well, so I've set that as a hard requirement. @lord-carlos gonna close this issue - if you need to reopen, feel free to do so. :)
