### ISSUE TITLE
Error when stripping fit

### ISSUE THREAD

**Issue by rinakondur** [pyfa-org/Pyfa#1160]
# Submit a bug report bug report or feature request

Here you can inform pyfa developers of potential bugs or suggest features / improvements to the project. Please check
to make sure that the bug hasn't been reported or feature requested before submitting. If you have general questions
about the project and want to reach out to the developers personally, please check out out our [Slack]
(https://pyfainvite.azurewebsites.net/).

---

## Bug Report
Error below with a Jackdaw upon selecting all and deleting to clear the fit.

### Expected behavior:
Clear the modules fit to current ship.

### Actual behavior:
Error appears, fit is not cleared.

### Detailed steps to reproduce:
Select all -> Delete key (keyboard) results in error below.

### Release or development git branch? Please note the release version or commit hash:
Release 1.29.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.29.1 Stable - YC119.5 1.0
pyfa root: C:\Program Files (x86)\pyfa
save path: C:\Users\user\.pyfa
fs encoding: mbcs

EXCEPTION: <eos.saveddata.mode.Mode object at 0x0E7FF850> is not in list

  File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinViews\fittingView.py", line 259, in kbEvent
    self.removeModule(self.mods[row])
  File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinViews\fittingView.py", line 354, in removeModule
    populate = sFit.removeModule(self.activeFitID, fit.modules.index(module))

**Comment by rinakondur** [comment]
Save path is correct on my end, seems GitHub likes to remove the \ before .pyfa.

**Comment by blitzmann** [comment]
Oh hey Rina! Long time no see. =)

Thanks for the report, will take a look tonight. Has select all > delete always been a thing?

**Comment by blitzmann** [comment]
Took a look at it tonight. Seems to only affect t3ds due to the Tactical Mode showing up in the list (which isn't a module, but something that's a property of the fit itself, hence the error).

It's an easy fix, but in the process of looking at it, I also noticed that a fit is recalculated for every module removed... lolwut!? I've also fixed this, but since it's a larger and lower level change, I'm going to test it a bit more before merging the fix in. :D

Thanks again for the heads up ;)

**Comment by Ebag333** [comment]
Doesn't happen in my fork.

I recall running into this stacktrace, it wasn't just T3Ds (or at least I didn't notice it on them) but was caused by something else.

**Comment by rinakondur** [comment]
Thanks guys!

**Comment by blitzmann** [comment]
@rinakondur You still doing FW things?
