### ISSUE TITLE
EXCEPTION: 'ascii' codec can't encode character u'\u047e'

### ISSUE THREAD

**Issue by cnaeus** [pyfa-org/Pyfa#1167]
## Pyfa gives an exception when i right click on the Projected frame to add a projection. This problem just started happening yesterday, have been using pyfa for a year now, and never had this issue.

Using Win 10 64, and newest version of pyfa

**Comment by Ebag333** [comment]
Do you use unicode characters in your ship names?

**Comment by Ebag333** [comment]
There's actually a bunch of times when we'd stacktrace because of this.

Fixed in my branch. 😁 
https://github.com/Pyfa-fit/Pyfa-fit/pull/88

**Comment by cnaeus** [comment]
I'm new to GitHub, Fixed in my branch means...?

**Comment by blitzmann** [comment]
> I'm new to GitHub, Fixed in my branch means...?

It a dev thing. ebag has a fix available on his repo which I've gone ahead and applied top the pyfa repo. Thanks to both of you for the report and the fix. :)

@cnaeus an automated build with the fix can be found here: https://ci.appveyor.com/api/buildjobs/nsrtecpt652taa69/artifacts/pyfa.zip let me know if you run into any other problems. Thanks!
