### ISSUE TITLE
Error loading hulk fit

### ISSUE THREAD

**Issue by slider-arnolles** [pyfa-org/Pyfa#1171]
## Bug Report
Pyfa shows error dialog loading hulk fit.

OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.29.1 Stable - YC119.5 1.0
pyfa root: C:\Program Files (x86)\pyfa
save path: C:\Users\Kenneth\.pyfa
fs encoding: mbcs

EXCEPTION: unsupported operand type(s) for +: 'float' and 'NoneType'

  File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinViews\fittingView.py", line 484, in fitChanged
    self.refresh(self.mods)
  File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinViews\fittingView.py", line 603, in refresh
    d.Display.refresh(self, stuff)
  File "C:\Program Files (x86)\pyfa\library.zip\gui\display.py", line 247, in refresh
    newText = col.getText(st)
  File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinViewColumns\misc.py", line 54, in getText
    return self.__getData(stuff)[0]
  File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinViewColumns\misc.py", line 406, in __getData
    cycleTime = getattr(stuff, 'cycleTime', stuff.getModifiedItemAttr("duration"))
  File "C:\Program Files (x86)\pyfa\library.zip\eos\saveddata\module.py", line 736, in cycleTime
    speed = (speed * numShots + effective_reload_time) / numShots

### Expected behavior:
No error dialog

### Actual behavior:
Error dialog

### Detailed steps to reproduce:
Open fit by searching in the UI and clicking the fit

### Fits involved in EFT format (Edit > To Clipboard > EFT):
Can't open fit to provide this

### Release or development git branch? Please note the release version or commit hash:
stable: pyfa version: 1.29.1 Stable - YC119.5 1.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win10

### Other relevant information:
Error first happened in hulk fit when I tried to turn off one of the mining mods, now it won't load that fit.

Log attached.
[Pyfa-2017-05-15.log.txt](https://github.com/pyfa-org/Pyfa/files/1000080/Pyfa-2017-05-15.log.txt)

**Comment by blitzmann** [comment]
@slider-arnolles can you send me your `%userprofile%/.pyfa/saveddata.db` file to sable.blitzmann@gmail.com? That will contain the fitting needed to reproduce the issue.

**Comment by blitzmann** [comment]
@slider-arnolles nevermind, you already sent it! :) Will take a look

**Comment by blitzmann** [comment]
@slider-arnolles can you send me your %userprofile%/.pyfa/saveddata.db file to sable.blitzmann@gmail.com? That will contain the fitting needed to reproduce the issue.

**Comment by blitzmann** [comment]
I was able to reproduce the error, and have a fix available on this automated build:

https://ci.appveyor.com/api/buildjobs/lf760e1v2hx2u4gq/artifacts/pyfa.zip

Could you confirm the fix?
