### ISSUE TITLE
 Error message when trying to project same ship fitting that is being worked over om the same ship

### ISSUE THREAD

**Issue by Folles** [pyfa-org/Pyfa#1177]
## Bug Report
OS version: 	Windows-7-6.1.7601-SP1
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.29.2 Stable - YC119.5 1.0
pyfa root: E:\Giochi\EVE ONLINE\PYFA
save path: C:\Users\Nimrod\.pyfa
fs encoding: mbcs

EXCEPTION: u'Ancillary Remote Armor Repairer'

  File "E:\Giochi\EVE ONLINE\PYFA\library.zip\gui\statsPane.py", line 75, in fitChanged
    view.refreshPanel(fit)
  File "E:\Giochi\EVE ONLINE\PYFA\library.zip\gui\builtinStatsViews\rechargeViewFull.py", line 109, in refreshPanel
    tank = fit.effectiveSustainableTank if self.effective else fit.sustainableTank
  File "E:\Giochi\EVE ONLINE\PYFA\library.zip\eos\saveddata\fit.py", line 1368, in effectiveSustainableTank
    eshps = self.damagePattern.calculateEffectiveTank(self, self.sustainableTank)
  File "E:\Giochi\EVE ONLINE\PYFA\library.zip\eos\saveddata\fit.py", line 1063, in sustainableTank
    self.calculateSustainableTank()
  File "E:\Giochi\EVE ONLINE\PYFA\library.zip\eos\saveddata\fit.py", line 1122, in calculateSustainableTank
    amount = mod.getModifiedItemAttr(groupAttrMap[mod.item.group.name])

### Expected behavior:
App should make the necessary calculations to account for missing cap transfered and active remote reps

### Actual behavior:
It crashes when dealing with those 2 factors

### Detailed steps to reproduce:
Fit a logi ship that has remote reppers and cap transfers. 
Project the same fitting on the fit you're working on.
Turn off the Cap Transfer, turn on the Remote Reppers. If ship is found going out of cap, app crashes.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Augoror, Auguror v.1]

1600mm Rolled Tungsten Compact Plates
Energized Adaptive Nano Membrane II
Energized Adaptive Nano Membrane II
Energized Explosive Membrane II
Energized Kinetic Membrane II

Alumel-Wired Enduring Sensor Booster
10MN Monopropellant Enduring Afterburner
Alumel-Wired Enduring Sensor Booster

Medium Solace Scoped Remote Armor Repairer
Small Ancillary Remote Armor Repairer, Nanite Repair Paste
Medium Solace Scoped Remote Armor Repairer
Centum C-Type Medium Remote Capacitor Transmitter
Medium Solace Scoped Remote Armor Repairer

Medium Trimark Armor Pump I
Medium Ancillary Current Router I
Medium Ancillary Current Router I

Light Hull Maintenance Bot I x4

Nanite Repair Paste x100
Targeting Range Script x2
Scan Resolution Script x2
ECCM Script x2

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10): 
See Bug Report

**Comment by blitzmann** [comment]
@Folles Thanks for the heads up on this error. This was fixed with d1fc2dd6e, forgot to reference this issue with it. If you want a build that includes the fix, please see here: https://ci.appveyor.com/api/buildjobs/chfievc106j16h1g/artifacts/pyfa.zip

Otherwise, a new point release will be out in the next couple of days :)
