### ISSUE TITLE
Fighter's value's are in the negatives

### ISSUE THREAD

**Issue by nikander100** [pyfa-org/Pyfa#1178]
# Submit a bug report bug report or feature request

Here you can inform pyfa developers of potential bugs or suggest features / improvements to the project. Please check
to make sure that the bug hasn't been reported or feature requested before submitting. If you have general questions
about the project and want to reach out to the developers personally, please check out out our [Slack]
(https://pyfainvite.azurewebsites.net/).

---

## Bug Report
The fighter values are in the minus they subtract money from the drone section and total section.

### Expected behavior:
put fighter in fighter bay -> value goes up by x amount of isk

### Actual behavior:
put fighter in fighter bay -> value goes down by x amount of isk

### Detailed steps to reproduce:
Drag any light/support fighter in the fighter bay from the market., the drone price will display -xM isk, total will also go down with the -xM amount of isk

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Thanatos, Thanatos Ratting Shield Buffer]

Damage Control II
Drone Damage Amplifier II
Drone Damage Amplifier II
Drone Damage Amplifier II
Omnidirectional Tracking Enhancer II
Caldari Navy Power Diagnostic System

Capital Shield Extender II
Capital Shield Extender II
Capital F-S9 Regolith Compact Shield Extender
Adaptive Invulnerability Field II
Adaptive Invulnerability Field II

Networked Sensor Array
Fighter Support Unit I
Fighter Support Unit I
Fighter Support Unit I
Fighter Support Unit I

Capital Core Defense Field Extender I
Capital Core Defense Field Extender I
Capital Processor Overclocking Unit I

Einherji I x9
Einherji I x9
Einherji I x9
Siren I x3

Liquid Ozone x300

### Release or development git branch? Please note the release version or commit hash:
Release Stable 1.29.2

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10 pro and OSX 10.12 (Sierra)

### Other relevant information:
happening for a bit longer since 1.29 (from what I can recall) Happening on my mac and windows computer.

Also tested with empty hulls and the same happens.

**Comment by blitzmann** [comment]
Thanks for noticing this! I got a fix out for it, see here: https://ci.appveyor.com/project/blitzmann/pyfa/build/artifacts

Will also be available in the 1.29.3 release whenever that comes out :)
