### ISSUE TITLE
Error dialog is not resizable, locked to top level, cuts off part of prompt.

### ISSUE THREAD

**Issue by BartMassey** [pyfa-org/Pyfa#1183]
Four error dialogs popped up when I started Pyfa 1.29.2 for the first time today. My fonts are large, and the dialog window is not resizable, so the prompt about how to deal with the errors ends with "Please". So I guess I am supposed to please do something: I'm guessing post here. Also, the dialogs are marked not hidable by other windows, which kind of makes sense, but also makes it a problem when there are four of them on a screen.

### Expected behavior:

Error dialog is resizable, not locked to top.

### Actual behavior:

Not so much.

### Detailed steps to reproduce:

Not sure. Probably: Run pyfa 1.29.2 on Debian Linux under XFCE4, and trigger an error window.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

N/A

### Release or development git branch? Please note the release version or commit hash:

1.29.2

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Debian Linux  Jesse + unstable

**Comment by blitzmann** [comment]
> so the prompt about how to deal with the errors ends with "Please"

oh lol >.<

Can you provide a screenshot of the error dialogs? Additionally, can you look in `~/.pyfa` for logs and let me know if you see any that have traceback info and post here? Would like to not only fix the dialog itself, but what causes the dialog in the first place :)

**Comment by BartMassey** [comment]
I filed a separate issue #1184 for the actual bug: you're working on it now.

Here's a screenshot:
![pyfa-error-dialog](https://cloud.githubusercontent.com/assets/117151/26276860/57e0ecde-3d35-11e7-91c6-68a913e62285.png)

**Comment by blitzmann** [comment]
My god that's hideous looking. I will look at this as soon as I can. :)

**Comment by Ebag333** [comment]
How does the rest of the app look? Mind screenshotting it?

**Comment by BartMassey** [comment]
It's fine.
![pyfa-20170521](https://cloud.githubusercontent.com/assets/117151/26282133/ca67f646-3dbf-11e7-9258-8f956ebef334.png)

**Comment by minlexx** [comment]
@BartMassey maybe you have some strange system default font settings? 😮

**Comment by blitzmann** [comment]
> It's fine.

Well... not quite. The character drop down, lists, menu, etc are all scaled up due to them using the system font sizes. I bet the preferences panels look like shit as well. Whereas the stats look fine because we explicitly set the font on these, and the tabs also look fine because the size is hardcoded when the tabs are drawn. Honestly, I never through about what happens when a user increases their system font size, and I don't think anyone has really come forward letting me know of these scaling issues. Will take a look to see what might be involved at unifying everything in a later release. But, that being said, even thought there's areas with larger font than intended, it doesn't hinder the application much, so I'll focus on the error dialog for now. :)

**Comment by Ebag333** [comment]
>I don't think anyone has really come forward letting me know of these scaling issues. 

There's been more than one mention of issues, especially with 4k or high display scaling.

**Comment by blitzmann** [comment]
>There's been more than one mention of issues, especially with 4k or high display scaling.

The only specific issue that I've known of is how pyfa looks on Retina (and similar), and that's because we aren't drawing some UI elements with the proper resolution (for example, tabs). I do imagine, though, that with the higher resolutions these days, folks are setting their font scaling up.

**Comment by BartMassey** [comment]
I have some moderate vision impairment, so large fonts are pretty important to me. I can live with the size the stats use, but I definitely have to squint at it. If my vision gets any worse I'll probably have to figure out how to increase that size to be able to use Pyfa.

**Comment by blitzmann** [comment]
> I have some moderate vision impairment, so large fonts are pretty important to me. I can live with the size the stats use, but I definitely have to squint at it. If my vision gets any worse I'll probably have to figure out how to increase that size to be able to use Pyfa.

Some parts of the stats stuff is easily changed as they key off `gui/utils/fonts.py`. I had to do this at some point because font sizes in mac are different. 

![image](https://cloud.githubusercontent.com/assets/3904767/26334903/3ad8285c-3f36-11e7-9a3c-67c004da014e.png)

There are other areas that are probably hardcoded and whatnot, or don't respect system settings. I do need to kind of go over all of them and make sure there's  a standard way of doing them for better overall appearance, it's been a while since I looked at them. I also have to keep in mind that different platforms all respond differently to font's, so... that's a thing. =/

@Ebag333 I know you looked at font size stuff at some point, find anything interesting / useful?

**Comment by Ebag333** [comment]
It's done in Pyfa.fit. 😁 

Can set font size, type, style, and weight.  Example for default type/style/weight, min/max size (6 to 12).  No reason we couldn't allow smaller/bigger, but both those are pretty extreme (as you can see).

https://puu.sh/wbQRs/31e00c57bf.png

The one thing I want to add is for some of the windows to be dynamically sized if a larger font is chosen.  Right now 12 will overflow slightly on a number of windows (though as you can see, the main window is fine).

You apparently can't change the fonts on the about window (without using a custom one), but that's not a big deal. The other one that doesn't get set properly is the New/Rename/Copy Windows, not sure why.

Other than that, they're all dynamic now.

It's spread over multiple PRs, but here's the latest one:
https://github.com/Pyfa-fit/Pyfa-fit/pull/108

**Comment by Ebag333** [comment]
The one I like most is Teletype.  It takes up too much room because the width is fixed instead of dynamic, but it looks really cool. 😁 

https://puu.sh/wbRwA/90576695ca.png

**Comment by BartMassey** [comment]
Thanks so much! I can only imagine how much work it was chasing down all the places where things had to be set up. Eagerly awaiting the final patches.

A whole bunch of free proportional typewriter fonts are [here](http://site.xavier.edu/polt/typewriters/tw-fonts.html).

**Comment by Ebag333** [comment]
Can't use third party fonts unless we want to handle each platform independently, and a ton of custom work. Not worth it.

**Comment by blitzmann** [comment]
@Ebag333 thanks for the work on this. You by chance take a look at linux or os x to see how these play out on those platforms?

I'll look into integrating it with main project next week as I'll have some time then. :D

**Comment by BartMassey** [comment]
I'm happy to try out a pre-release on Linux if you tell me what to pull.

**Comment by Ebag333** [comment]
@BartMassey 

https://github.com/Pyfa-fit/Pyfa-fit

You'll want to grab the Development branch as Master hasn't been updated to scale window size based on font yet (so it scrolls off).

You can adjust font size (and style, etc) under preferences.  The default is 9, which seems to be the wx default.  For <reasons>, there were hacks put in place to do different sizes on different platforms (mac vs everyone else), that's gone now but if someone finds the default too big/small they just just adjust it themselves. vOv

Should be pretty much done.

Next up on my list, custom background and text color.  For all the *nix nerds:D
https://puu.sh/wd8Ll/cf4aa86f7f.png

**Comment by BartMassey** [comment]
```
OS version: 	Linux-4.9.0-3-amd64-x86_64-with-debian-9.0
Python: 	2.7.13
wxPython: 	3.0.2.0
SQLAlchemy: 	1.1.6
Logbook: 	1.0.0
pyfa version: 2017.05.27 (live) - YC119.5 1.0
pyfa root: /usr/local/src/Pyfa-fit
save path: /home/bart/.pyfa
fs encoding: UTF-8

EXCEPTION: No module named EVE_Gnosis.formulas.formulas

  File "pyfa.py", line 389, in <module>
    import eos.db
  File "/usr/local/src/Pyfa-fit/eos/db/__init__.py", line 84, in <module>
    from eos.db.saveddata import (  # noqa: E402,F401
  File "/usr/local/src/Pyfa-fit/eos/db/saveddata/cargo.py", line 26, in <module>
    from eos.saveddata.fit import Fit
  File "/usr/local/src/Pyfa-fit/eos/saveddata/fit.py", line 28, in <module>
    from eos.gnosis import GnosisFormulas, GnosisSimulation
  File "/usr/local/src/Pyfa-fit/eos/gnosis.py", line 5, in <module>
    from EVE_Gnosis.formulas.formulas import Formulas
```

Looks like some stuff is missing?

**Comment by Ebag333** [comment]
Did you install the modules in requirements.txt? :)

**Comment by BartMassey** [comment]
Nope! :-)  Thought I had enough from last time I ran pyfa from source. Was wrong.

(Just how special a snowflake *is* the Gnosis, anyhow?)

Here's some pictures. The side text looks much better. Sadly, though, even at 12 point the actual fit text is smaller than it was with the old version due to my large system font. Any chance of getting a 14 point option?

The fonts seem to pick a random substitution for each face. I'll try to figure out RSN what the rules are by reading source and looking at X11 and wx stuff.

In any case, thanks much! 
![pyfa-decorative](https://user-images.githubusercontent.com/117151/26867869-d7ff17da-4b1b-11e7-958e-8054be186a1b.png)
![pyfa-small-fonts](https://user-images.githubusercontent.com/117151/26867867-d7fbc44a-4b1b-11e7-8917-546edcd70a89.png)
![pyfa-large-fonts](https://user-images.githubusercontent.com/117151/26867868-d7fd344c-4b1b-11e7-89ba-0753a28f8db9.png)

**Comment by Ebag333** [comment]
>Nope! :-) Thought I had enough from last time I ran pyfa from source. Was wrong.

You weren't wrong. There just a _few_ extra features that have been added. 

>(Just how special a snowflake is the Gnosis, anyhow?)

Well, it basically runs the cap and tank simulations. It's a from the ground up rewrite of it, with input from CCP Larrikan on mechanics. 

Given that the old sim is mostly static formulas, assumptions, and hand waving, it's surprisingly accurate. The Gnosis capsim actually plays out how cap works, so is extremely accurate to actual in game mechanics, something the old sim cannot do. 

>Here's some pictures. The side text looks much better. 

That matches the feedback I've gotten elsewhere. Seems sharper. 

>Sadly, though, even at 12 point the actual fit text is smaller than it was with the old version due to my large system font. Any chance of getting a 14 point option?

I think that this has more to do with your high resolution and DPI scaling. But, uh, yeah, I can go as high as you need. Super easy to change. 

>The fonts seem to pick a random substitution for each face. I'll try to figure out RSN what the rules are by reading source and looking at X11 and wx stuff.

It's not random, but the different fonts don't really seem to match cleanly across different platforms. On Windows, many of the fonts look the same, or are so slightly different that you really can't tell. 

These are built into wxPython, so I can't really control them, only expose the options and leave it up to you if you want to change them or not.

**Comment by Ebag333** [comment]
Okay, it's added.

https://puu.sh/wdcRi/0f113cdc79.png

You can see that for us mortal folk with mere _high_ resolution displays (1080), 16 is large enough to pretty much break everything.  (I normally run 8.)

Hopefully that gives enough of a range for your setup.  Curious to see how it looks.

One thing I may need to do is add another set of scaling for the super large sizes.  Right now it's +25% width, +10% height if you're anything over the default (9).  Might have to bump that to +50% width, +10% height if you're over 12.

Especially check areas with lots of fixed text, like the preferences panes.

**Comment by BartMassey** [comment]
I was confusing EVE_Gnosis with the in-game Gnosis, which explains my confusion :-) . It looks like a cool package.

I only have such large resolution monitors because that's the only way to get a physically large monitor I can see stuff on. I actually have one of them scaled down to match their resolutions at 100dpi.

If you want a lot of work, you can probably get the font metrics out of wx and size the windows accordingly. That way we could go as big (or small) as we wanted :-) .

Looks like the font size still only goes up to 12. I hacked in 14 point and 16 point.

BTW, seems like you have to click both Apply and OK to get the settings to update on the next run. 

Here's a screenshot with ugly colors, and a 14-point and 16-point screenshot. Except for the noted text-crowding problems (at both resolutions, although far worse at 16), 16-point is dreamy for me.

![pyfa-ugly-colors](https://user-images.githubusercontent.com/117151/26888540-2de43d62-4b60-11e7-8607-e134fe774282.png)

![pyfa-14pt](https://user-images.githubusercontent.com/117151/26888933-6231497e-4b61-11e7-9ed5-7565cb2aa0fa.png)

![pyfa-16pt](https://user-images.githubusercontent.com/117151/26888944-6aa994da-4b61-11e7-86b2-a8efd8567a83.png)

**Comment by Ebag333** [comment]
If you got the color options, you're grabbing the wrong branch, which is why you didn't have the extra font sizes.  Good to know that 16 works for you.

Can you post a screenshot of the settings pane at 16?  That's the biggest area I'm worried about, the rest of it really isn't too bad.

**Comment by BartMassey** [comment]
No, I tried both the development and color branches, neither had the new font sizes. I just tried out the color stuff while I was there.

The settings window looks fine. The too-small rectangles for the Resistances percentages are kind of a problem. Again, you probably need the font metrics here.

![pyfa-settings](https://user-images.githubusercontent.com/117151/26919773-a79e551c-4beb-11e7-9713-54e9f3d5951a.png)

**Comment by Ebag333** [comment]
Interesting. Linux handles that much cleaner than Windows.  `Weight` is off screen though.

At 16, it just doesn't handle it well.  It's usable, just not pretty.  Since not too many people will be using 16 in the first place, I'm not _too_ worried about it.

I think I fixed most of the issues.  The boxes now dynamically size. Based on using font size 16 on my Windows box, I elected to go ahead and trim quite a bit of stuff if you're using a large font size.  So for example, the ship list doesn't show how many fits for each ship type, the fit list doesn't show the timestamp (neither of these draw properly), trim down to 0 decimal places for most stats, etc.  I also resized a bunch of boxes to better fit the large font size, which should help.

https://puu.sh/weL6Q/baebbb7cf6.png

You can see some stuff still gets pushed off the screen, but it's actually completely usable on a 1080 screen, so I'm _super_ happy with it.

Plus a slew of little bug fixes along the way.

I'll be merging in the code tonight.  I just pushed to the branch, if you want to pull the color branch and play around with it.  (It does have the 16 point font in it.)

**Comment by DarkFenX** [comment]
Error window has been made resizable a few releases ago, and removed its "stay on top" property in 873a62e3f0685625e2615cb67091cae77caf37e9 (which was quite annoying, considering it stayed on top even when you switched focus to other applications).

**Comment by DarkFenX** [comment]
I am going to close this issue as initially it was about error dialog rather than font scaling / UI scaling. If those two still bother you, create new one (for larger fonts) or wait until newer wxpython versions (which will include better UI scaling for 4k displays). There's hiDPI issue, but it is windows-specific: #1225
