### ISSUE TITLE
Can't Put Rigs on Procurer

### ISSUE THREAD

**Issue by krelios** [pyfa-org/Pyfa#1195]
# Submit a bug report bug report or feature request

Here you can inform pyfa developers of potential bugs or suggest features / improvements to the project. Please check
to make sure that the bug hasn't been reported or feature requested before submitting. If you have general questions
about the project and want to reach out to the developers personally, please check out out our [Slack]
(https://pyfainvite.azurewebsites.net/).

---

## Bug Report
I cannot add any rigs to the Procurer.

### Expected behavior:
I should be able to drag a rig from the Market to an open Rig slot on the Procurer, assuming it's the right size to go on that ship.

### Actual behavior:
I drag a rig onto an open slot and nothing happens.

### Detailed steps to reproduce:
See expected/actual behavior

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Procurer, Group Mining]

Damage Control II
Warp Core Stabilizer II

Small Shield Extender I
Kinetic Deflection Field II
Tracking Disruptor I
1MN Afterburner I

Strip Miner I
Strip Miner I

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

Mining Drone II x3
Hornet II x2
Mining Drone II x2
Hornet II x3

### Release or development git branch? Please note the release version or commit hash:
1.29.2

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
If there's something I'm missing and this is user error, I apologize.

**Comment by blitzmann** [comment]
Hi there @krelios 

Double check you are adding medium sized rigs. Works for me

![image](https://cloud.githubusercontent.com/assets/3904767/26607523/e1a451cc-4564-11e7-8ad3-d2e907f8ce3c.png)

If it's still not working for you, please give an example of a rig that you're trying to add. Additionally, try to create a new fit and see if it works on that one. Let me know how that turns out and I can investigate further if need be. :)

**Comment by krelios** [comment]
Yep, it was user error. Sorry for the trouble but thanks for the help!

**Comment by blitzmann** [comment]
No worries, glad it was an easy fix! :D
