### ISSUE TITLE
Request: Quick highlight on stat changes when hovering item

### ISSUE THREAD

**Issue by Zyles** [pyfa-org/Pyfa#1201]
You know when you highlight an item in the fitting screen inside the game, before you fit it and it highlights the changes on the stats?

I want that. So I don't have to drag and drop every single item to see the changes.

**Comment by blitzmann** [comment]
Going through some old issues, I usually try to respond to all of them within a few days, and this one seems to have slipped through. Sorry!

So, while this would be an awesome feature, there are multiple problems with it. **tldr:** the current pyfa codebase / engine simply wouldn't support something like this. 

Firstly, we don't have any mechanism to show a delta for stats, or highlight something that is changing. This isn't too big of an issue, we could always develop something for the GUI (probably).

Secondly, and most importantly, is that the engine is just not equipped to do this. To know how a module affects a fit, it first needs to be added to the fit, and then the fit (and module) needs to be calculated within that context. Fitting calculations can be anywhere from 100-1000ms, depending on complexity (number of modules, projected effects, command bursts, etc), so it's not as simple as saying "just recalculate the fit every time I hover over an item" - performance would take a huge hit. We could probably get away with doing a sort of bastardized version of it, where you hover over a module it'll run that modules effects onto the fit, and nothing else. But this comes with serious drawbacks - any other item or skill that is supposed to affect that module will not be applied, so you're basically applying raw base values to the fit. Which, for most purposes, is absolutely useless.

I hate outright closing an ticket for what would be a truly awesome feature, but in this case, the amount of time, refactoring, and just plain rewriting this feature would require leaves it out of the question. 😢
