### ISSUE TITLE
Citadel Standup Webs and Painters not applied in damage graphs

### ISSUE THREAD

**Issue by justindh** [pyfa-org/Pyfa#1202]
## Bug Report
Standup Painters and Webs dont seem to have any effect in the damage graphs. 

### Expected behavior:
activating painters increase the signature radius of the target allowing standup missiles to apply damage more fully. 

### Actual behavior:
activating painters and webs have no effect to the damage graphs

### Detailed steps to reproduce:
- Load up the Fit below
- activate all modules
- open damage graph (ctrl+g)
- Set Sig Radius to 100
- Toggle Painter on and Off

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Fortizar, bugreport]

Standup Missile Guidance Enhancer I
Standup Missile Guidance Enhancer I
Standup Ballistic Control System I
Standup Ballistic Control System I

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
Standup Target Painter I

Standup Guided Bomb Launcher I, Standup Void Guided Bomb
[Empty High slot]
[Empty High slot]
Standup ASML Missile Launcher I, Standup ASML-SD Missile
[Empty High slot]
[Empty High slot]

Standup L-Set Missile Flight Processor I
[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
1.29.2 stabe - yc119.5.1.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10

### Other relevant information:
Bomb launchers also dont show up on the dps graph at all

**Comment by blitzmann** [comment]
Thanks for the info! Indeed, these were not applied correctly. haven't fixed the bomb issue (will need to take a more indepth look into that one), will open a separate issue for it. :)
