### ISSUE TITLE
after_flush() hook creating new objects

### ISSUE THREAD

**Issue by HindenPeter** [pyfa-org/Pyfa#1208]
## Bug Report
Copying a fit, then attempting to open a new fitting tab throws a multitude of errors, including "EXCEPTION: Over 100 subsequent flushes have occurred within session.commit() - is an after_flush() hook creating new objects?"

### Expected behavior:
A new blank fitting tab is opened.

### Actual behavior:
A new blank fitting tab is opened, but an error is thrown and pyfa becomes unusable.

### Detailed steps to reproduce:
1: Have an already-existing fit, possibly one created before 1.29.3.
2: Copy the fit.
3: Attempt to open a new tab.
4: Receive error.
5: Try to do literally anything else, get the same "Over 100" exception. Pyfa becomes completely unusable.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Vargur, C5?]

Capacitor Flux Coil II
Capacitor Flux Coil II
Republic Fleet Gyrostabilizer
Republic Fleet Gyrostabilizer
Republic Fleet Gyrostabilizer

Pithum C-Type Adaptive Invulnerability Field
Adaptive Invulnerability Field II
Gist X-Type X-Large Shield Booster
Pith X-Type Shield Boost Amplifier
Republic Fleet Large Cap Battery
Republic Fleet Large Cap Battery

Bastion Module I
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

Large Capacitor Control Circuit II
Large Capacitor Control Circuit II

### Release or development git branch? Please note the release version or commit hash:
1.29.3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10 x64

### Other relevant information:
This may be related to issue #1207

**Comment by blitzmann** [comment]
As this is very much related to #1207, gonna close this issue. I was able to reproduce this issue consistently while working on the other issue. Thanks for the info! :)
