### ISSUE TITLE
[Request] Add implants to EFT export when using fit-specific implants

### ISSUE THREAD

**Issue by Ligraph** [pyfa-org/Pyfa#1209]
As the title says, it would be nice to have implants included in the eft export (in the cargo I assume), when using fit-specific implants.

**Comment by blitzmann** [comment]
Hi there,

Implants are already included. CTRL+C and then choose `EFT (Implants)`. Does it not work for you?

**Comment by Ligraph** [comment]
I never noticed that...   now I feel dumb.

What are your thoughts about making it the default option, or making the export settings carry over from the last export (e.g. if you export as eft w/ implants the next export will have that selected by default)?

**Comment by blitzmann** [comment]
The problem with making it the default option is that some programs that take in EFT fittings may choke on it (hence why it's not simply part of the `EFT` option). Having a "last used" setting might be beneficial, although I feel like 9/10 it's going to be EFT (if you export in XML or DNA, etc, it's usually for a very specific reason), and having it default the next time you want to export will probably cause a lot of folks to overlook it, just as you overlooked the Implants one, and be confused when they have something like CREST format after paste. Now, having a "Remember selection" checkbox would probably solve that, so I can look into it :)

**Comment by blitzmann** [comment]
Going to close this issue as it was a non-issue. While a "remember selection" checkbox might help, I don't think it really warranted, at least for now. Am open to PR that implement this functionality though :)
