### ISSUE TITLE
"Polarized" modules

### ISSUE THREAD

**Issue by Teckor** [pyfa-org/Pyfa#1216]
### Expected behavior:
Resistance is not zero. Recharge rates are calculated as usual and not with 0% resistances.

### Actual behavior:
The resistance of the shield, armor and structure is reset when installing any "polarized" modules. Recharge rates are calculated with 0% resistances, but actually resistances are more.

### Detailed steps to reproduce:
Install any quantity of any "polarized" turrets or bays.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Daredevil, Burner Worm (best)]

Centii A-Type Small Armor Repairer
Core X-Type Armor Kinetic Hardener
Shadow Serpentis Magnetic Field Stabilizer
Shadow Serpentis Magnetic Field Stabilizer

Coreli A-Type 1MN Afterburner
Stasis Webifier II
Imperial Navy Small Capacitor Booster, Cap Booster 200

Polarized Light Neutron Blaster, Void S
Polarized Light Neutron Blaster, Void S
[Empty High slot]

Small Hybrid Burst Aerator II
[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
pyfa 1.29.3 Stable - YC119.5 1.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 8.1 for single language. Default language: English (United States). 

### Other relevant information:
"C:\Program Files (x86)\pyfa\pyfa.exe"
.Net Framework 4.0.
OpenGL 4.0.0 - Build 10.18.10.3345
DirectX 11

**Comment by Ebag333** [comment]
>The resistance of the shield, armor and structure is reset when installing any "polarized" modules. Recharge rates are calculated with 0% resistances, but actually resistances are more.

Why do you think that this is true? 

The design of polarized modules was to set resistance to 0, so unless you have evidence otherwise....

**Comment by Teckor** [comment]
I did not read the description of the module before installation. The description of the module said that the ship with this module loses its resistance to any damage. I was wrong, this is not a bug.
