### ISSUE TITLE
How to add another language to the software.！TKS！

### ISSUE THREAD

**Issue by fujiwara-takumi** [pyfa-org/Pyfa#1217]
How to add another language to the software. I am a player of EVE China server, I hope this software can support Simplified Chinese.

**Comment by Ebag333** [comment]
Not easy to do. 

We could use CCPs translations for items and some text, but most of the GUI is hard coded

**Comment by blitzmann** [comment]
Yeah, the GUI is the main beast. pyfa was never developed with translations in mind, although it's something that's been talked about on and off. It's not too difficult to have translations for the database (eve item names, for example) although it's not really supported so mileage may vary.

There was someone maintaining a Chinese version of pyfa somewhere with translations for the GUI IIRC. I don't think it's being maintained anymore, and I can't seem to find it. :(

**Comment by fujiwara-takumi** [comment]
@Ebag333 @blitzmann thanks a lot! Thank you very much for the reply. I think if the Pyfa project has a system setting, which can point to a language ini text file, which will be much simpler, ini language files can be translated by the players in each area to complete. This is also very helpful to the popularity of the Pyfa project around the world.

**Comment by blitzmann** [comment]
Closing this for #1545, which has more discussion on the topic. :)
