### ISSUE TITLE
Bug Report: Error! message at Browse EVE Fittings window

### ISSUE THREAD

**Issue by pumbah** [pyfa-org/Pyfa#1223]
### Expected behavior:
Cascade submenu

### Actual behavior:
ERROR
OS version: 	Windows-7-6.1.7601-SP1
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.29.3 Stable - YC119.5 1.0
pyfa root: C:\Program Files (x86)\pyfa
save path: C:\Users\username\.pyfa
fs encoding: mbcs

EXCEPTION: expected string or buffer

  File "C:\Program Files (x86)\pyfa\library.zip\gui\crestFittings.py", line 410, in displayFit
    fit = json.loads(self.fittingsTreeCtrl.GetPyData(selection))
  File "C:\python-2.7.10\lib\json\__init__.py", line 338, in loads
  File "C:\python-2.7.10\lib\json\decoder.py", line 366, in decode

### Detailed steps to reproduce:
1. logged on to Crest 
2. And then menu click Crest/Browse Fittings. 
3. A new window Browse EVE Fittings appear
4. Then Fetch Fits
5. Doubleclick any entries in the list of the fittings shipname text besides the cascading + generates the above error message

### Release or development git branch? Please note the release version or commit hash:
PYFA Version 1.29.3.

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
OS version: 	Windows-7-6.1.7601-SP1

**Comment by blitzmann** [comment]
Ah, sweet, thanks for the bug report. Thankfully this is an easy fix. I plan to have a point release out tonight to address some issues with old deleted fits hanging around, hope to include this as well. :)

**Comment by blitzmann** [comment]
Fixed with d319b74

**Comment by pumbah** [comment]
yw
