### ISSUE TITLE
[Request] Wormhole Effects

### ISSUE THREAD

**Issue by ShadowIntelligence** [pyfa-org/Pyfa#1229]
It would be nice if I could select a wormhole effect to be applied to the stats of the fitting.

**Comment by Ebag333** [comment]
You can. Go to the projected tab and right click.

It's not super obvious, but it's there.

**Comment by blitzmann** [comment]
Yep, already a thing. I've renamed the help text under the projected tab from "system effects" to "wormhole effects" to make it a bit more obvious - something I've been meaning to do for a long while now.
