### ISSUE TITLE
Hulk have no 3rd mining upgrade, bug?

### ISSUE THREAD

**Issue by Koxpa** [pyfa-org/Pyfa#1230]
# Submit a bug report bug report or feature request

Hi, i have an issue with Hulk hull. 
Mining Laser Upgrade I or II  does not effect if sloted in 3rd( lowest ) low slot, never 

---
### Detailed steps to reproduce:
Just fit it in, and look on Mining Yield, in example we can look on Strip Miner II with any t2 crystall  stats - Mining Amount on Hulk with 2 and 3 upgrades , and on Skiff :   
Hulk 1506 M3  - same 2 or 3 upgrades 
Skiff  1641 M3 with 3 upgrades , and 1506 M3 with 2 upgrades

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 7, pyfa 1.29.4

### Other relevant information:
Other modules seems to work, check with Co-Processor II
I cant check it in game, couse right now have no hulk near me.

![3](https://user-images.githubusercontent.com/29357734/27013454-b0413a78-4eec-11e7-881f-e702a5498faa.jpg)
![4](https://user-images.githubusercontent.com/29357734/27013455-b041bc82-4eec-11e7-8e03-e92b33d63477.jpg)
![5](https://user-images.githubusercontent.com/29357734/27013452-afc7ff96-4eec-11e7-9a4f-c157939ee011.jpg)
![1](https://user-images.githubusercontent.com/29357734/27013456-b04ab24c-4eec-11e7-9e19-c6020aa8ef45.jpg)
![2](https://user-images.githubusercontent.com/29357734/27013453-afc93334-4eec-11e7-9c58-ee1b4c78f89c.jpg)

**Comment by Ebag333** [comment]
On one of the MIning Lasers, can you right click and show `Module Stats`, then screenshot the `Affected By` tab (after expanding them all)? Your numbers don't match up with mine, and I'm trying to figure out where the difference is.

**Comment by Koxpa** [comment]
Yeah. my bad, forgot mention that i used orca all5 for bonuses , and impant mine +3% 
but it is not the matter.  

here screens without bonuses and without implants + module stats with 3 upgrades and with 2 upgrades.
![6](https://user-images.githubusercontent.com/29357734/27078751-a1040f02-503d-11e7-8c01-3b45a67aa93f.jpg)
![7](https://user-images.githubusercontent.com/29357734/27078753-a17f5e8c-503d-11e7-8182-c2b8b1aa08c2.jpg)

**Comment by Ebag333** [comment]
Well this is strange.

I can see from your screenshots that the one with 3 MLUs active does indeed have the stats for 2 MLUs.

I just tested against both Pyfa.fit (my branch) and Pyfa, neither exhibit this issue.  So it's not an (obvious) issue in the code.

Couple of things to try.

1) Does this happen with a brand new fit?
2) Can you close Pyfa, rename your saveddata.db file (found under your Users folder), and relaunch it, and see if it happens with a blank DB?

Here's what it looks like when it's working correctly:
https://puu.sh/wiVV5/04e9d32ef0.png

**Comment by Koxpa** [comment]
Ok. i tried make a brand new fit. and it works... and i cant understand what the hell happend. Anyway, thx. Solved

**Comment by Ebag333** [comment]
If you have the fit that it's happening on, I'd love to see it. 
If you can ship me your user database: ebagola@gmail.com

**Comment by Cwittofur** [comment]
I too am having this issue. I will check with brand new fit to see if that resolves my problem. If you'd like my database as well I can send that.

**Comment by DarkFenX** [comment]
No matter how i tried, works for me. Reopen if it still reproduces on latest versions.
