### ISSUE TITLE
Copying Implant Set causes error

### ISSUE THREAD

**Issue by Hethalean** [pyfa-org/Pyfa#1236]
Implant set name: Missions - Laser
Ocular Filter - Improved
Memory Augmentation - Improved
Neural Boost - Improved
Cybernetic Subprocessor  - Improved
Social Adaptation Chip - Improved
WS-610
WR-705
SS-905
LE-1005

Error:
OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.29.4 Stable - YC119.5 1.0
pyfa root: H:\Eve
save path: H:\Eve\saveddata
fs encoding: mbcs

EXCEPTION: __deepcopy__() takes exactly 1 argument (2 given)

  File "H:\Eve\library.zip\gui\builtinViews\entityEditor.py", line 121, in OnCopy
    copy = self.DoCopy(active, dlg.txtctrl.GetValue().strip())
  File "H:\Eve\library.zip\gui\setEditor.py", line 77, in DoCopy
    copy = sIS.copySet(entity)
  File "H:\Eve\library.zip\service\implantSet.py", line 84, in copySet
    newS = copy.deepcopy(implant_set)
  File "c:\python\32-bit\2.7\lib\copy.py", line 174, in deepcopy

**Comment by blitzmann** [comment]
Thanks a bunch for the error report. Was able to reproduce and fix :)
