### ISSUE TITLE
select effective dps issue

### ISSUE THREAD

**Issue by oity** [pyfa-org/Pyfa#1241]
## Bug Report

In Firepower panel
After clicking on 'toggle to mining yeld' icon and click again to went back to 'Firepower view', right click to select 'target resist' stop working, you have to close and reopen pyfa to get it back working properly.
Selecting other fits doesen't fix the issue 

pyfa 1.29.4 Stable - YC119.5 1.0
on Ubuntu 17.04

EVE Data: 	1142796
Python: 		2.7.13
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.14
matplotlib: 	 2.0.0
---

**Comment by blitzmann** [comment]
This is a known problem, and has been for a while. I think it's due to a bad binding or something. It does work, but you have to be very precise in where you spawn the context menu, and it's very very finicky. Will take a look more closely as I have time :)

**Comment by blitzmann** [comment]
This was fixed a little while ago, forgot to mark it as such :)
