### ISSUE TITLE
Wrong CovertReconfiguration subsystem bonus

### ISSUE THREAD

**Issue by Eiden2004** [pyfa-org/Pyfa#1246]
Good morning!
In new version, all CovertReconfiguration subs add 300m3 instead of 30m3.

![before sub tengu](https://user-images.githubusercontent.com/25662179/28106617-34f4bd40-66ed-11e7-9ab0-81292c0b7249.png)
![after sub tengu](https://user-images.githubusercontent.com/25662179/28106619-39206a9a-66ed-11e7-89ad-281c28b3a9e1.png)
![legion after](https://user-images.githubusercontent.com/25662179/28106627-3bf76cf0-66ed-11e7-8801-632f5b2b8d71.png)
![proteus after](https://user-images.githubusercontent.com/25662179/28106629-3e1d87e4-66ed-11e7-9690-a52a7f1cc18d.png)

**Comment by blitzmann** [comment]
I'm pretty sure this is a bug with CCPs data. I noticed a few discrepancies in the traits vs actual bonuses discrepancies when making the release, and totally forgot to file a bug report for them. Thanks for reminding me - I'll keep this issue open and active until I hear back from CCP

**Comment by blitzmann** [comment]
Actually, just took another look, seems I overlooked another attribute that was on there (or CCP added it and I missed it >.<)

My bad. An automated build with the fix can be found here:
https://ci.appveyor.com/project/blitzmann/pyfa/branch/master/artifacts

**Comment by blitzmann** [comment]
Forgot to close this after the 1.31 release >_>
