### ISSUE TITLE
Right clicking throws an exception

### ISSUE THREAD

**Issue by Ptitlaby** [pyfa-org/Pyfa#1247]
# Submit a bug report bug report or feature request

Here you can inform pyfa developers of potential bugs or suggest features / improvements to the project. Please check
to make sure that the bug hasn't been reported or feature requested before submitting. If you have general questions
about the project and want to reach out to the developers personally, please check out out our [Slack]
(https://pyfainvite.azurewebsites.net/).

---

## Bug Report

Right clicking an item throw an exception, and the "selected" item to which the right click applies stay stuck : whenever you click, it'll be the right click menu for the item right before the crash

### Expected behavior:

No exception

### Actual behavior:

Right clicking an item throw an exception, and the "selected" item to which the right click applies stay stuck : whenever you click, it'll be the right click menu for the item right before the crash

### Detailed steps to reproduce:

Open the fit
Right click on modules until you throw the exception

### Fits involved in EFT format (Edit > To Clipboard > EFT):

[Tengu, Scanning]

Experimental Hyperspatial Accelerator
Inertial Stabilizers II

Scan Rangefinding Array II
Scan Pinpointing Array II
Large Shield Extender II
Scan Acquisition Array II
[Empty Med slot]
[Empty Med slot]

Covert Ops Cloaking Device II
Shield Command Burst II, Shield Harmonizing Charge
Expanded Probe Launcher II, Sisters Core Scanner Probe
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

Medium Anti-EM Screen Reinforcer II
Medium Hyperspatial Velocity Optimizer II
Medium Hyperspatial Velocity Optimizer II

Tengu Core - Electronic Efficiency Gate
Tengu Defensive - Covert Reconfiguration
Tengu Offensive - Support Processor
Tengu Propulsion - Interdiction Nullifier

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
OS version: 

OS version: 	Windows-10.0.15063
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.30.0 Stable - YC119.7 1.0
pyfa root: D:\Games\pyfa\PackageFiles
save path: C:\Users\Laby\.pyfa
fs encoding: mbcs

EXCEPTION: C++ assertion "m_menuDepth > 0" failed at ..\..\src\msw\toplevel.cpp(1544) in wxTopLevelWindowMSW::DoSendMenuOpenCloseEvent(): No open menus?

  File "C:\python-2.7.10\lib\site-packages\wx-3.0-msw\wx\_core.py", line 16766, in <lambda>
  File "D:\Games\pyfa\PackageFiles\library.zip\gui\builtinViews\fittingView.py", line 578, in spawnMenu
    self.PopupMenu(menu)
  File "C:\python-2.7.10\lib\site-packages\wx-3.0-msw\wx\_core.py", line 11144, in PopupMenu

### Other relevant information:

Reopening a fit fix the issue temporarely

**Comment by blitzmann** [comment]
Can you confirm that you can replicate this fairly easily? And if so, how often are you seeing it? I can't seem to replicate it.

Here's where the error is being thrown in wxWidgets: https://github.com/wxWidgets/wxWidgets/blob/master/src/msw/frame.cpp#L426 Seems to be when the menu is closing... but I can't fathom why it would break for us.

**Comment by Ptitlaby** [comment]
Sorry for the delay, life got busy

I am not able to replicate the bug again after opening the same fit :(

**Comment by Ptitlaby** [comment]
Issue happened once again, on an other fit.

Exception error : 

> OS version: 	Windows-10.0.15063
> Python: 	2.7.10
> wxPython: 	3.0.2.0
> SQLAlchemy: 	1.0.5
> Logbook: 	1.0.0
> pyfa version: 1.30.0 Stable - YC119.7 1.0
> pyfa root: D:\Games\pyfa\PackageFiles
> save path: C:\Users\Laby\.pyfa
> fs encoding: mbcs
> 
> EXCEPTION: C++ assertion "m_menuDepth > 0" failed at ..\..\src\msw\toplevel.cpp(1544) in wxTopLevelWindowMSW::DoSendMenuOpenCloseEvent(): No open menus?
> 
>   File "C:\python-2.7.10\lib\site-packages\wx-3.0-msw\wx\_core.py", line 16766, in <lambda>
>   File "D:\Games\pyfa\PackageFiles\library.zip\gui\builtinViews\fittingView.py", line 578, in spawnMenu
>     self.PopupMenu(menu)
>   File "C:\python-2.7.10\lib\site-packages\wx-3.0-msw\wx\_core.py", line 11144, in PopupMenu
> 

Fit : 

> 
> [Phantasm, c3 pve Xl]
> 
> Power Diagnostic System II
> [Empty Low slot]
> [Empty Low slot]
> [Empty Low slot]
> [Empty Low slot]
> 
> Gist X-Type X-Large Shield Booster
> Pith X-Type Shield Boost Amplifier
> Adaptive Invulnerability Field II
> Gist X-Type EM Ward Field
> Thukker Large Cap Battery
> 10MN Analog Booster Afterburner
> 
> Ammatar Navy Focused Medium Pulse Laser
> Ammatar Navy Focused Medium Pulse Laser
> Ammatar Navy Focused Medium Pulse Laser
> [Empty High slot]
> 
> [Empty Rig slot]
> [Empty Rig slot]
> [Empty Rig slot]

when right clicking on the turrets

**Comment by blitzmann** [comment]
@Ptitlaby I wasn't really able to reproduce the issue before. I'm going through older issues now and checking up on them.

pyfa 2.x includes a version upgrade for wxpython, the GUI that we use. Have you had any issues like this since you upgrades to 2.x?

**Comment by blitzmann** [comment]
Going to close this issue, as it might be resolved simply by the update to wxPython with pyfa 2.x. If you run into this issue again, please open a new bug report! Thanks!
