### ISSUE TITLE
Exception: [Error 183]

### ISSUE THREAD

**Issue by Burak-Oz** [pyfa-org/Pyfa#1250]
When starting the application after first installation it gives below error.

# Submit a bug report bug report or feature request

Here you can inform pyfa developers of potential bugs or suggest features / improvements to the project. Please check
to make sure that the bug hasn't been reported or feature requested before submitting. If you have general questions
about the project and want to reach out to the developers personally, please check out out our [Slack]
(https://pyfainvite.azurewebsites.net/).

---

## Bug Report

OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.30.0 Stable - YC119.7 1.0
pyfa root: C:\Program Files (x86)\pyfa
save path: C:\Users\pc\.pyfa
fs encoding: mbcs

EXCEPTION: [Error 183] Halen varolan bir dosya oluşturulamaz: u'C:\\Users\\pc\\.pyfa'

  File "C:\python-2.7.10\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "C:\Program Files (x86)\pyfa\library.zip\pyfa__main__.py", line 204, in <module>
  File "C:\Program Files (x86)\pyfa\library.zip\config.py", line 87, in defPaths
    __createDirs(savePath)
  File "C:\Program Files (x86)\pyfa\library.zip\config.py", line 44, in __createDirs
    os.makedirs(path)
  File "c:\python\32-bit\2.7\lib\os.py", line 157, in makedirs

**Comment by blitzmann** [comment]
@Burak-Oz Google translate tells me the error says "An existing file can not be created:" which leads me to believe that this is a permissions error.

Is this the first time you've used pyfa? Do you see a folder titled `\.pyfa` in your user directroy (normally `C:\Users\UserName`)?

**Comment by Burak-Oz** [comment]
Hello,

I dont remember if i have installed pyfa before.

It was the first launch after installation this version. And after the
exception, when i tried second launch, it worked.

I suggest for first launch to check for the file before not to to get that
exception.

Kind Regards.

**Comment by blitzmann** [comment]
Thanks @Burak-Oz . I assume it's been working since? We haven't really gotten any other reports of users getting this error that I'm aware of. I'm going to be looking at the file structure soon anyway to lay the groundwork for some iterations and new features, so hopefully stuff like this should get cleared up. :)

Closing now, feel free to re-open if you still have difficulties
