### ISSUE TITLE
Pyfa Windows 1.30.0 - Tengu not displaying all slots, only Subsystems and Rigs

### ISSUE THREAD

**Issue by hrbngr1** [pyfa-org/Pyfa#1252]
# Submit a bug report bug report or feature request
## Bug Report
Not all sections being displayed for Tengu

### Expected behavior:
all high/mid/low/sub/rig slots to do a complete build

### Actual behavior:
only the changed slots (subsystems and rigs)

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Tengu, Tengu Post Changes]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

[Empty Subsystem slot]
[Empty Subsystem slot]
[Empty Subsystem slot]
[Empty Subsystem slot]

### Release or development git branch? Please note the release version or commit hash:
1.30.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 7

### Other relevant information:
![image](https://user-images.githubusercontent.com/30183034/28223189-6e27054e-6898-11e7-86bb-364c31ef6038.png)

**Comment by KawaiDesu** [comment]
That's not a bug. You should add subsystems first as they adding different amount of slots (and other attributes) to the T3 ship.

**Comment by blitzmann** [comment]
Aye. Tech 3 Cruisers slow layout is defined by the subsystem you add, so pyfa doesn't know how many of each to give you. Go ahead and add some subsystems and you should see the slots expand. :)
