### ISSUE TITLE
Low level db caching results in wrong result on query

### ISSUE THREAD

**Issue by fecgit** [pyfa-org/Pyfa#1255]
### Expected behavior:
When querying the gamedata db using functions in eos/db/gamedata/queries.py: e. g. `getItem` or `getGroup`, its expected to return the correct results even through the returned result had been cached.

### Actual behavior:
The cache mixes different kinds of objects, like Item and Group. Which results in wrong results to queries.

### Detailed steps to reproduce:
Pyfa root dir and execute test case.

minimal reduced testcase:
```python
from eos.db import getItem, getGroup

item = getItem(654)  # going to be cached
group = getGroup(654)  # returns the in this case wrongly cached object

assert item != group
```

### Release or development git branch? Please note the release version or commit hash:

> commit 0210020658baeb72d046e4e2679434f7510dadfb

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Ubuntu 16.04

**Comment by blitzmann** [comment]
Hrm... interesting. I wonder why this has never popped up before, you would think this would lead to some serious breakage in pyfa. Quick looks shows that we use `getGroup()` with a string usually, and when we don't, maybe just sheer coincidence. Thanks for reporting this, will take a further look into it

**Comment by blitzmann** [comment]
@fecgit Can you try out the `bug/#1255` branch and see if you can break the caching? This probably won't be introduced with the next release that I plan to make tomorrow (I want more time to test for such a low level change).

**Comment by blitzmann** [comment]
@fecgit would you have time to test that branch out?

**Comment by DarkFenX** [comment]
```
        print('---')
        print(eos.db.getItem(654).name)
        print(eos.db.getGroup(654).name)
```
```
---
Kryos
Advanced Heavy Assault Missile
```

Must've been fixed along the way. Closing.
