### ISSUE TITLE
80 Probes in launcher

### ISSUE THREAD

**Issue by stevehinesley** [pyfa-org/Pyfa#1256]
# Submit a bug report bug report or feature request

Here you can inform pyfa developers of potential bugs or suggest features / improvements to the project. Please check
to make sure that the bug hasn't been reported or feature requested before submitting. If you have general questions
about the project and want to reach out to the developers personally, please check out out our [Slack]
(https://pyfainvite.azurewebsites.net/).

---

### Expected behavior:
8 probes in launcher

### Actual behavior:
80 probes in launcher

### Detailed steps to reproduce:
Added Sisters Expanded Probe Launcher and chose Sisters Combat Probes. I added them first and then any probes seem to be 80. After removing all and changing to Sisters Core Probes it was 8 until I changed back to Sisters Combat Probes. Seemed to be reproducible consistently. 

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Loki, Loki]

Damage Control II
Gyrostabilizer II
Gyrostabilizer II
Gyrostabilizer II

10MN Monopropellant Enduring Afterburner
Caldari Navy Stasis Webifier
Caldari Navy Warp Scrambler
Adaptive Invulnerability Field II
Adaptive Invulnerability Field II

Covert Ops Cloaking Device II
425mm Medium 'Scout' Autocannon I, Republic Fleet EMP M
425mm Medium 'Scout' Autocannon I, Republic Fleet EMP M
425mm Medium 'Scout' Autocannon I, Republic Fleet EMP M
425mm Medium 'Scout' Autocannon I, Republic Fleet EMP M
425mm Medium 'Scout' Autocannon I, Republic Fleet EMP M
Sisters Expanded Probe Launcher, Sisters Core Scanner Probe
Medium Infectious Scoped Energy Neutralizer

Medium Anti-Kinetic Screen Reinforcer II
Medium Anti-Thermal Screen Reinforcer II
Medium Targeting System Subcontroller II

Loki Core - Immobility Drivers
Loki Defensive - Covert Reconfiguration
Loki Offensive - Projectile Scoping Array
Loki Propulsion - Intercalated Nanofibers

Hobgoblin II x5

Sisters Combat Scanner Probe x16
Sisters Core Scanner Probe x16

### Release or development git branch? Please note the release version or commit hash:
1.30.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Linux Mint 18.1

### Other relevant information:
I'm wiling to test if you are unable to reproduce and make changes.

**Comment by stevehinesley** [comment]
OK, maybe I missed something in game, but I have 16 on my Loki. If this is normal, then never mind. I have not read or been told you can have more than 8 probes loaded. If this is normal, then the first load only shows 8.

**Comment by Danfocus** [comment]
```
sqlite3 eve.db

update invtypes set capacity=0.8 where typeID=28756;
```

**Comment by blitzmann** [comment]
I don't have an active account right now so I can't test fully (using sisters), but this kind of data is directly from the game. The expanded launcher has 8m3 of space available. Thus, it can take 8 combat probes and 80 core probes.

Unless mechanics have changed and I'm unaware. But on SISI right now, pyfa reflects data in game.

Core probes and expanded launcher: 
![image](https://user-images.githubusercontent.com/3904767/30575734-d78492a6-9cd0-11e7-9931-45103a2953c9.png)

Combat probes and expanded launcher: 

![image](https://user-images.githubusercontent.com/3904767/30575794-33208174-9cd1-11e7-988f-ce9d4f1efce0.png)

Double check values in game. If you're still experiencing issues, please elaborate and re-open :)
