### ISSUE TITLE
Drugs' penalties do not apply.

### ISSUE THREAD

**Issue by Folles** [pyfa-org/Pyfa#1257]
# Submit a bug report bug report or feature request

Here you can inform pyfa developers of potential bugs or suggest features / improvements to the project. Please check
to make sure that the bug hasn't been reported or feature requested before submitting. If you have general questions
about the project and want to reach out to the developers personally, please check out out our [Slack]
(https://pyfainvite.azurewebsites.net/).

---

## Bug Report
try to use a drug, activate penalties, they don't get counted

### Expected behavior:
drugs penalties should apply when activated

### Actual behavior:
they don't

**Comment by blitzmann** [comment]
@Folles

Would you mind elaborating on which boosters you're trying to apply, which side affects you're trying to activate, etc? If it's all drugs, all side effects, please post screenshots of the booster section, EFT fit, and describe which attributes you expect should be changing but aren't. 

Thanks!

**Comment by blitzmann** [comment]
Closing due to lack of information, please feel free to create new issue if necessary with more details :)
