### ISSUE TITLE
Pyfa 1.30.0 crashed when deleting a fit with it still open in a tab.

### ISSUE THREAD

**Issue by GKFC** [pyfa-org/Pyfa#1258]
Hi,

I imported a fit from zkillboard, but didn't want it anymore.

With the fit still active in one of the tabs I deleted it in Pyfa and the entire application crashed.

I have the full Mac dump if you'd like it.

Cheers,

G.

**Comment by blitzmann** [comment]
Hi there!

Yes, this is unfortunately a well-known issue for a long while now. Every now and then I dive into why it might be, only to come up empty handed with no solutions. I have a feeling it's a low level issue with the GUI library itself, in which case there's not a lot I can do except re-write how some things are done (fit deletion is very janky to begin with). There's a few issues open already about this issue, the most prominent: #164  (other issues are linked through that one)

I'm in the middle of some refactoring, I'm going to complete that hoping that it solves it before looking any further. :) In the mean time, marking this as duplicate
