### ISSUE TITLE
Allow use of Variations menu on modules in cargo hold

### ISSUE THREAD

**Issue by pcd1193182** [pyfa-org/Pyfa#1261]
When you right-click on a module in the actual fit, you can use the Variations menu to switch between meta versions of the same module. It would be nice if you could do that in the cargo hold as well; this frequently comes up when importing a fit from my fleet's doctrine where there are refits in the cargo hold. Often these refits are designed assuming all excellent skills or no excellent skills, when in practice most people have a mix; the ability to meta up and down the modules that I can't use with just a right click would be very helpful.

It might also be nice to be able to see which of those modules are and aren't usable without having to drag them into the fit, but I'm not sure what a good UI for that would necessarily look like.

**Comment by burnsypet** [comment]
Seems like a really useful feature and have made a pull request.

**Comment by pcd1193182** [comment]
Closed, fixed!
