### ISSUE TITLE
Running Pyfa on Linux

### ISSUE THREAD

**Issue by erasmusgrant** [pyfa-org/Pyfa#1271]
Traceback (most recent call last):
  File "/home/erasmus/Downloads/pyfa/pyfa.py", line 29, in <module>
    from logbook import CRITICAL, DEBUG, ERROR, FingersCrossedHandler, INFO, Logger, NestedSetup, NullHandler, StreamHandler, TimedRotatingFileHandler, WARNING, \
ImportError: No module named logbook

I can't get this to work on my laptop(Ubuntu 17.04 Gnome3) or my desktop KDE Neon

**Comment by minlexx** [comment]
https://github.com/pyfa-org/Pyfa#dependencies
`logbook >= 1.0.0`

**Comment by petosorus** [comment]
you can also use `pip install -r requirements.txt` if you have pip installed.

**Comment by blitzmann** [comment]
Indeed, install the `logbook` package and you should be good to go. Closing as resolved :)
