### ISSUE TITLE
Granting Missing skills doesn't grant prereqs.

### ISSUE THREAD

**Issue by pcd1193182** [pyfa-org/Pyfa#1273]
## Bug Report
When using the "Grant Missing Skills" option, only toplevel skills are granted, not prerequisites. This results in some confusion when attempting to make skill plans and fits for various skill levels.

### Expected behavior:
Granting Missing Skills should grant all skills necessary to get the character in question to be able to fly the ship; the granted state should always be a valid, achievable state for a character.

### Actual behavior:
Only toplevel skills are granted.

### Detailed steps to reproduce:
1.  Create a new character with all 0s
2.  Open a Sabre fit
3.  Right click on the skill icon, Grant Missing Skills
4.  Note that the only granted skills are interdictors 1 and Minmatar Destroyer 5, which require between them spaceship command IV. graviton physics I, science V, power grid management V, propulsion jamming V, cpu management III, and Navigation II.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Sabre, temp]

[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
Release 1.31.0 stable

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
OS X 10.12.3

**Comment by burnsypet** [comment]
Looks like grantMissingSkills in characterSelection.py is not going through the list of requirements recursively, it's only adding the highest level entries in self.reqs.iteritems() to the skillsMap.

In theory it is giving you all the skills you need to operate the ship but I think this is probably an error and we should be giving all the levels for the pre-requisite skills. I'll look into fixing this.

**Comment by burnsypet** [comment]
Have created a pull request to fix this #1274 however when attempting to apply a large set of missing skills the application can lock up for quite a while so this may not be accepted.

**Comment by blitzmann** [comment]
@pcd1193182 The functionality is already an option, see Preferences > Fitting Engine > Enforce Strict Skills

![image](https://user-images.githubusercontent.com/3904767/30569524-60955f44-9ca9-11e7-8330-77428a1e9d04.png)

Every time you change a skill with this enabled, it will also recursively check the skills that depend on the changed skill. The caveat, as @burnsypet noted, is that it can be extremely slow. However, on the fly skill changes don't really happen all that often (I feel, use cases obviously vary). But, once the skill has loaded its pre-reqs (which is what takes most of the time), this functionality can be pretty quick.

@pcd1193182 please check to make sure this works for you. I will be closing this issue unless something else regarding this pops up :)
