### ISSUE TITLE
Information Command Burst Targeting Range bonus calculation error

### ISSUE THREAD

**Issue by 6reedy** [pyfa-org/Pyfa#1275]
## Bug Report
Targeting Range command bonus from Information Command Burst II + Sensor Optimization charge applied to a fit with Sensor Booster II + Targeting Range script results it Targeting Range in pyfa being higher than actual value in EvE. It seems that stacking penalty is not applied to targeting range command bonus.
Scan Resolution bonus calculation works fine.

### Expected behavior / Actual behavior:
Assembling 2 ships for test, Raven with 2x Sensor Booster II and Bifrost with Information Command Burst module, i.e. we have 3 modules which affect Targeting range of the Raven. When trying various combinations we get the following.

Effects on | EvE | pyfa
------------ | ------------- | -------------
Base | 93.75 | 93.8
1x SeBo | 150.00 | 150.0
2x SeBo | 228.22 | 228.2
Base + links | 125.39 | 125.4
links + 1x SeBo | **194.00** | **200.6**
links + 2x SeBo | **272.17** | **300.0**

As you can see we get no difference when only local modules are applied, but when both links and local SeBo are on we get higher values than actual (two bottom rows).

### Detailed steps to reproduce:
1. Create Raven fit with 2 Sensor Booster II modules (listed below), load Targeting Range scripts.
2. Create bifrost fit with an Information Command Burst II module (listed below), load Sensor Optimization charge.
3. Set bifrost fit as a fleet booster for raven fit in Command tab
4. When both local Sensor Booster II modules and Information Burst effects are applied Targeting Range value in pyfa will be higher that the one your get in EvE client.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Bifrost, roam 3 links t2]

Nanofiber Internal Structure II
Nanofiber Internal Structure II
Overdrive Injector System II

Micro Jump Field Generator
5MN Quad LiF Restrained Microwarpdrive
Warp Disruptor II
Republic Fleet Medium Shield Extender
Ta3 Compact Ship Scanner

Information Command Burst II, Sensor Optimization Charge
Skirmish Command Burst II, Interdiction Maneuvers Charge
Skirmish Command Burst II, Rapid Deployment Charge
Core Probe Launcher I /OFFLINE
[Empty High slot]
[Empty High slot]

Small Command Processor I
Small Command Processor I

Nanite Repair Paste x49
Sisters Core Scanner Probe x8
Sensor Optimization Charge x300
Interdiction Maneuvers Charge x300
Rapid Deployment Charge x300

[Raven, snipe]

Ballistic Control System II
Ballistic Control System II
Ballistic Control System II
Ballistic Control System II
Damage Control II

500MN Cold-Gas Enduring Microwarpdrive
Large Micro Jump Drive
Missile Guidance Computer II, Missile Range Script
Missile Guidance Computer II, Missile Range Script
Adaptive Invulnerability Field II
Sensor Booster II, Targeting Range Script
Sensor Booster II, Targeting Range Script

Heavy Energy Neutralizer II
Cruise Missile Launcher II, Mjolnir Fury Cruise Missile
Cruise Missile Launcher II, Mjolnir Fury Cruise Missile
Cruise Missile Launcher II, Mjolnir Fury Cruise Missile
Cruise Missile Launcher II, Mjolnir Fury Cruise Missile
Cruise Missile Launcher II, Mjolnir Fury Cruise Missile
Cruise Missile Launcher II, Mjolnir Fury Cruise Missile

Large Anti-EM Screen Reinforcer II
Large Rocket Fuel Cache Partition I
Large Hydraulic Bay Thrusters I

Acolyte II x5
Light Shield Maintenance Bot II x5

### Release or development git branch? Please note the release version or commit hash:
pyfa 1.31.0 Stable

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 7 Professional

### Other relevant information:
I have tested this with 2 different ships as a booster (bifrost and Tengu) both in k-space and Class 2 Magnetar, and I get the same results.

**Comment by blitzmann** [comment]
This is an excellent bug report, very detailed and well-formatted! Thanks so much. I've reproduced the values that you are getting in pyfa (trusting that the eve values are correct since I don't have a way of testing that unfortunately). Indeed, stacking penalties were not applied. Applying them leads to the exact same values as EVE. 

I'll be making a release tonight with the included fix, stay tuned!

**Comment by blitzmann** [comment]
Was fixed with #1299

**Comment by 6reedy** [comment]
Well done fixing it. You provide the formatting stub, all I did is just fill it up accurately, step by step. Took me some time but it's a time well invested.
Keep up the good job with making pyfa better.
0/
