### ISSUE TITLE
Legion Covert Reconfiguration no scanning bonus

### ISSUE THREAD

**Issue by Rammix** [pyfa-org/Pyfa#1276]
### Expected behavior:
"Legion defensive - Covert Reconfiguration" subsystem should give scanning strength bonus.
### Actual behavior:
It doesn't.

### Detailed steps to reproduce:
Fit a probe launcher, fit the cov. reconf. subsystem, see the scanning stats, change the subsystem, recheck the scanning stats.

### Release or development git branch? Please note the release version or commit hash:
YC119.8 - v1.31.0 Release

**Comment by blitzmann** [comment]
Thanks for the bug report! Looks like I missed an effect when they rebalanced t3 cruisers :)
