### ISSUE TITLE
Align time is wrong

### ISSUE THREAD

**Issue by robmburke** [pyfa-org/Pyfa#1279]
# Submit a bug report bug report or feature request

Here you can inform pyfa developers of potential bugs or suggest features / improvements to the project. Please check
to make sure that the bug hasn't been reported or feature requested before submitting. If you have general questions
about the project and want to reach out to the developers personally, please check out out our [Slack]
(https://pyfainvite.azurewebsites.net/).

---

### Expected behavior:
Eve Online reports align time as 3.9 seconds.

### Actual behavior:
Pyfa reports 5.35 seconds.
![image](https://user-images.githubusercontent.com/11561820/30277868-1199cd6c-96d7-11e7-9e01-4e106843a9a7.png)

### Detailed steps to reproduce:
Use the provided fit

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Flycatcher, Bubble Pop Jr]

Ballistic Control System II

5MN Y-T8 Compact Microwarpdrive
X5 Enduring Stasis Webifier
X5 Enduring Stasis Webifier
Sensor Booster II, Scan Resolution Script
Caldari Navy Medium Shield Extender

Rocket Launcher II
Rocket Launcher II
Rocket Launcher II
Rocket Launcher II
Rocket Launcher II
Rocket Launcher II
Rocket Launcher II
Interdiction Sphere Launcher I, Warp Disrupt Probe

Small Polycarbon Engine Housing II
Small Polycarbon Engine Housing II

Warp Disrupt Probe x50
Scourge Rage Rocket x700
Nanite Repair Paste x200
Surgical Warp Disrupt Probe x20

### Release or development git branch? Please note the release version or commit hash:
1.31.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by BoraVyvorant** [comment]
Try turning off the afterburner in Pyfa and see if you get the same answer as in-game.

The in-game simulator assumes prop mod off for purposes of determining align time, I think. Pyfa lets you model both states.

**Comment by robmburke** [comment]
Ahh, yes. Had the MWD on. Did not realize that was a feature. Thanks.
