### ISSUE TITLE
Booster penalties not being applied. Error message attached.

### ISSUE THREAD

**Issue by oovarvu** [pyfa-org/Pyfa#1280]
# Submit a bug report bug report or feature request

Here you can inform pyfa developers of potential bugs or suggest features / improvements to the project. Please check
to make sure that the bug hasn't been reported or feature requested before submitting. If you have general questions
about the project and want to reach out to the developers personally, please check out out our [Slack]
(https://pyfainvite.azurewebsites.net/).

---

## Bug Report
Booster Penalties Not Registering

### Expected behavior:
Penalties to register

### Actual behavior:
not registrating

### Detailed steps to reproduce:
apply booster to fit, attempt to activate penalty

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Hound, BB Wolfpack T2]

Co-Processor II
Ballistic Control System II
Ballistic Control System II

Missile Guidance Computer II, Missile Range Script
1MN Y-S8 Compact Afterburner
Missile Guidance Computer II, Missile Range Script

Prototype 'Arbalest' Torpedo Launcher, Caldari Navy Nova Torpedo
Prototype 'Arbalest' Torpedo Launcher, Caldari Navy Nova Torpedo
Prototype 'Arbalest' Torpedo Launcher, Caldari Navy Nova Torpedo
Bomb Launcher I
Covert Ops Cloaking Device II

Small Warhead Calefaction Catalyst I
Small Polycarbon Engine Housing II

### Release or development git branch? Please note the release version or commit hash:
pyfa version 1.31.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
win 7 sp1

### Other relevant information:
This was the error message i get:

wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.31.0 Stable    - YC119.8 1.0
pyfa root: C:\Program Files (x86)\pyfa
save path: C:\Users\1st\.pyfa
fs encoding: mbcs

EXCEPTION: unsupported operand type(s) for /: 'str' and 'float'

  File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinContextMenus\boosterSideEffects.py", line 60, in handleMode
    sFit.toggleBoosterSideEffect(fitID, effect)
  File "C:\Program Files (x86)\pyfa\library.zip\service\fit.py", line 999, in toggleBoosterSideEffect
    self.recalc(fit)
  File "C:\Program Files (x86)\pyfa\library.zip\service\fit.py", line 1209, in recalc
    fit.calculateModifiedAttributes()
  File "C:\Program Files (x86)\pyfa\library.zip\eos\saveddata\fit.py", line 790, in calculateModifiedAttributes
    item.calculateModifiedAttributes(self, runTime, False)
  File "C:\Program Files (x86)\pyfa\library.zip\eos\saveddata\booster.py", line 124, in calculateModifiedAttributes
    effect.handler(fit, self, ("booster",))
  File "C:\Program Files (x86)\pyfa\library.zip\eos\effects\boostermissilevelocitypenalty.py", line 17, in handler
    "maxVelocity", attr)
  File "C:\Program Files (x86)\pyfa\library.zip\eos\effectHandlerHelpers.py", line 94, in filteredChargeBoost
    element.boostChargeAttr(*args, **kwargs)
  File "C:\Program Files (x86)\pyfa\library.zip\eos\effectHandlerHelpers.py", line 273, in boostChargeAttr
    self.chargeModifiedAttributes.boost(*args, **kwargs)
  File "C:\Program Files (x86)\pyfa\library.zip\eos\modifiedAttributeDict.py", line 385, in boost
    self.multiply(attributeName, 1 + boostFactor / 100.0, resist=(True if resist else False), *args, **kwargs)

**Comment by burnsypet** [comment]
Was able to reproduce this. It appears to only occur when attempting to apply a missile velocity side effect penalty which is a possibility on Crash and X-Instinct boosters.

**Comment by oovarvu** [comment]
I have also noticed that some of the standard boosters don't even offer the option of applying penalties.

thanks for looking at this so quickly.

**Comment by burnsypet** [comment]
@oovarvu I have applied a fix for this, which will be available whenever the next build is released. Could you please raise another ticket and let me know which boosters you have seen don't have a side effect context menu? I've tried these:

![image](https://user-images.githubusercontent.com/6990224/30455673-ab791c12-9998-11e7-9ade-b8892f005b73.png)

The only strange thing I saw with these is that Standard Cerebral Accelerator has a side effects context menu when it doesn't actually have any side effects.

**Comment by oovarvu** [comment]
My apologies, the side effect context menus are there but i have found they disappear for me after i get an error message. So sequence is:
1/ add booster 
2/ attempt to apply penalty for missile or turret 
3/ get error message 
4/ apply another booster
5/ attempt to apply penalty
6/ no context menu. 
At this point i have to restart pyfa to get the context menus back. The main issues with the penalties do seem to revolve around missile and turret penalties, i can apply up to 3 boosters and provided i avoid any missile/turret penalties they register just fine.

**Comment by burnsypet** [comment]
I've not noticed any turret ones causing an error, just the missile velocity. What seems to happen is after you trigger the error once then you won't be able to apply any other ones and the context menu won't spawn. Once my fix goes in it will hopefully make it so that you won't even get the error in the first place.

**Comment by oovarvu** [comment]
Thanks for getting it fixed, looking forward to the next update.

**Comment by blitzmann** [comment]
@burnsypet excellent work, thanks for the quick fix! Merged, will be releasing a new version in the coming days, depending on how quickly I get through the new issues :)
