### ISSUE TITLE
Importing Overrides fails with argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by fuzzysteve** [pyfa-org/Pyfa#1283]
### Expected behavior:
Overrides can be exported from one copy of pyfa and imported into a different one.

### Actual behavior:
When importing a set of overrides (lifeblood changes) an error is thrown.

[2017-09-17 15:53:13.516000] CRITICAL: __main__: Exception in main thread: argument of type 'NoneType' is not iterable
[2017-09-17 15:53:13.516000] CRITICAL: __main__:   File "C:\Program Files (x86)\pyfa\library.zip\gui\propertyEditor.py", line 111, in OnImport
[2017-09-17 15:53:13.516000] CRITICAL: __main__:     item.setOverride(attr, float(value))
[2017-09-17 15:53:13.516000] CRITICAL: __main__:   File "C:\Program Files (x86)\pyfa\library.zip\eos\gamedata.py", line 280, in setOverride
[2017-09-17 15:53:13.516000] CRITICAL: __main__:     if attr.name in self.__overrides:

### Detailed steps to reproduce:

With a fresh pyfa install (.pyfa folder wiped out) and an overrides file https://gist.github.com/fuzzysteve/31aa58aa7349dca24f0c8f8167535c60 

open pyfa
Window-> attribute editor
File -> import 
select the import file and import it
the error above is thrown. no attributes are imported.

### Release or development git branch? Please note the release version or commit hash:

pyfa version: 1.31.0 Stable    - YC119.8 1.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:

OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.31.0 Stable    - YC119.8 1.0
pyfa root: C:\Program Files (x86)\pyfa
save path: C:\Users\Steve\.pyfa
fs encoding: mbcs

EXCEPTION: argument of type 'NoneType' is not iterable

  File "C:\Program Files (x86)\pyfa\library.zip\gui\propertyEditor.py", line 111, in OnImport
    item.setOverride(attr, float(value))
  File "C:\Program Files (x86)\pyfa\library.zip\eos\gamedata.py", line 280, in setOverride
    if attr.name in self.__overrides:

**Comment by fuzzysteve** [comment]
When working with a fresh set of settings, any import fails. 

If you make a manual edit to a ship, then remove the override, you can import others for that ship. Just so long as you don't wipe out the .pyfa directory

**Comment by burnsypet** [comment]
Looks like there isn't any defensive coding in setOverride() to handle the case where the overrides list is none, presumably if you've changed the ship locally already the overrides list is already saved (?). If you want to build it yourself, this appears to be a quick workaround and allows me to run your overrides file:

https://gist.github.com/burnsypet/e106afc44cdd13f157178e557343df1f

Amendment starts on line 278 in ./eos/gamedata.py, there's probably a better solution and I'll look at it more tomorrow.

**Comment by blitzmann** [comment]
Hey guys, going through list of new issues in prep for upcoming patch
release. Will take a look at this - doesn't seem to be too complicated.
@Alex, will take a look at your fix more in-depth, but if you get to a
solution before I do, feel free to submit PR :)

- Blitzmann

**Comment by blitzmann** [comment]
>@fuzzysteve Looks like there isn't any defensive coding in setOverride() to handle the case where the overrides list is none, presumably if you've changed the ship locally already the overrides list is already saved (?). If you want to build it yourself, this appears to be a quick workaround and allows me to run your overrides file:

Close. You're correct in that overrides just aren't loaded yet.  However, a proper fix would be to just call `self.overrides` int `setOverrides()`.  The `overrides` property checks to see if it's been loaded first and, if not, loads it.

```
    def setOverride(self, attr, value):
        from eos.saveddata.override import Override
        if attr.name in self.overrides:
            override = self.overrides.get(attr.name)
            override.value = value
        else:
            override = Override(self, attr, value)
            self.overrides[attr.name] = override
        eos.db.save(override)
```

Will apply fix to master in a few minutes after a bit more testing and evaluation. Thanks to both of you :)
