### ISSUE TITLE
Grant Missing Skills (when strict skill levels is on) misses a few

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1289]
While looking into #1273, I noticed that, while not exactly the same issue, there is some sort of issue revolving around the grant missing skills option.

Copy all 0 character and apply to this fit:

```
[Sabre, Sabre]

Damage Control II
Nanofiber Internal Structure II

Medium Azeotropic Restrained Shield Extender
5MN Y-T8 Compact Microwarpdrive
Initiated Compact Warp Scrambler
Medium Shield Extender II

Prototype Cloaking Device I
125mm Gatling AutoCannon II
125mm Gatling AutoCannon II
125mm Gatling AutoCannon II
125mm Gatling AutoCannon II
125mm Gatling AutoCannon II
125mm Gatling AutoCannon II
Interdiction Sphere Launcher I, Warp Disrupt Probe

Small Hyperspatial Velocity Optimizer II
Small Hyperspatial Velocity Optimizer II


Warp Disrupt Probe x46
```

This is the skill list: 

![image](https://user-images.githubusercontent.com/3904767/30623710-4d89ec56-9d87-11e7-8bd6-7c40d9f6c54a.png)

Grant missing skills, these skills are still needed:

![image](https://user-images.githubusercontent.com/3904767/30623719-6346e0d0-9d87-11e7-8b2e-8acc2cf4b194.png)

This is all assuming strict skills are enabled

**Comment by burnsypet** [comment]
I added some traces to characterSelection.py and it looks like grantMissingSkills is not considering skills deeper in the tree, eg. 11579 "Cloaking" is considered however it's requirement 3426 "CPU Management" is not.

_buildSkillsTooltipCondensed seems to traverse all the skill requirements, and I have made an amendment on a local version to re-use the skillsMap generated by this to populate the skillsMap used by grantMissingSkills. Will hopefully have something ready to submit tomorrow.
