### ISSUE TITLE
Error in various capacitor calculations for a specific Bhaalghorn fit

### ISSUE THREAD

**Issue by fspigel** [pyfa-org/Pyfa#1304]
### Expected behavior:
When I turn a large cap battery or one of the Nosferatus on, the stability percentage should increase

### Actual behavior:
Turning either of these on decreases stability

### Detailed steps to reproduce:
For the cap battery error: 

Skills: All V
Implants/Boosters: None
Projected fits/bursts: None

1. Turn off one neutralizer, all other modules should be active and not heated.
2. Turn off the large cap battery. 

The cap stability goes from 34m 32s to 62.2% stable, instead of dropping. 

For the nosferatu error:

Skills: All V
Implants/Boosters: None
Projected fits/bursts: Guardian

1. Add included Guardian fit to projections, with both cap transfers running, not heated. 
2. Deactivate one neutralizer and one nosferatu. All other modules should be active, not heated.
3. Turn a second neutralizer off. 

The cap stability goes from 93.9% to 94.1%, instead of dropping. 

### Fits involved in EFT format (Edit > To Clipboard > EFT):
```
[Bhaalgorn, Max Resist]

Damage Control II
Corelum C-Type Energized Adaptive Nano Membrane
Corelum C-Type Energized Adaptive Nano Membrane
Reactive Armor Hardener
Corpus A-Type Armor Thermal Hardener
Corpus A-Type Armor EM Hardener
Corpus A-Type Armor Explosive Hardener

Shadow Serpentis 500MN Microwarpdrive
Dark Blood Stasis Webifier
Dark Blood Stasis Webifier
100MN Afterburner II
Republic Fleet Large Cap Battery

Corpus X-Type Heavy Energy Neutralizer
Corpus X-Type Heavy Energy Neutralizer
Corpus X-Type Heavy Energy Neutralizer
Corpus X-Type Heavy Energy Neutralizer
Corpus X-Type Heavy Energy Nosferatu
Corpus X-Type Heavy Energy Nosferatu
Corpus X-Type Heavy Energy Nosferatu

Large Anti-Thermal Pump II
Large Anti-Kinetic Pump II
Large Trimark Armor Pump II
```
```
[Guardian, Fleet (Armor) LogiCruiser V *DOCTOR*]

Core X-Type Armor Kinetic Hardener
Coreli A-Type Adaptive Nano Plating
Core X-Type Armor Thermal Hardener
Core X-Type Armor EM Hardener
Federation Navy 1600mm Steel Plates

Sensor Booster II
10MN Afterburner II

Large Remote Armor Repairer II
Large Remote Armor Repairer II
Large Coaxial Compact Remote Armor Repairer
Large Coaxial Compact Remote Armor Repairer
Large 'Regard' Remote Capacitor Transmitter
Large 'Regard' Remote Capacitor Transmitter

Medium Ancillary Current Router II
Medium Ancillary Current Router II


Warrior II x5

Targeting Range Script x1
Scan Resolution Script x1
ECCM Script x1
```

### Release or development git branch? Please note the release version or commit hash:
pyfa 1.32.0 Stable - YC119.9 1.3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
I tried to reproduce this in the in-game simulator, but didn't observe any such behavior, although my skills in game are a far cry from all V.

I love you for making Pyfa <3

**Comment by blitzmann** [comment]
Hi there,

Haven't looked specifically, but there is a known issue I believe with nos/neut paired with cap batteries. On mobile atm so can't verify / check, will keep you posted :)

**Comment by blitzmann** [comment]
See PR #1367 for fix
