### ISSUE TITLE
Shadow Serpentis Heavy Statis Grappler

### ISSUE THREAD

**Issue by SubjectXXX** [pyfa-org/Pyfa#1305]
## Bug Report
This fit below shows different values in cap management in comparison to in-game simulation.
Values are synced if NOSes and grappler are offline.

I was looking at the grapplers ingame (while undocked) info and it says 4GJ cap each 2 seconds. When I look in pyfa, there is a skill applied to it, lowering it to 3GJ per 2seconds.

I have also went out and test it with triggering module while full cap and it indeed takes 4GJ out of cap pool.

### Expected behavior:
It seems that ingame skill Propulsion Jamming is not applied.

### Actual behavior:
It applies skill Propulsion Jamming.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
    [Kronos, fff]
    Magnetic Field Stabilizer II
    Imperial Navy 1600mm Steel Plates
    Corpus X-Type Large Armor Repairer
    Imperial Navy Energized Adaptive Nano Membrane
    Centus X-Type Armor Explosive Hardener
    Imperial Navy Energized Adaptive Nano Membrane
    Damage Control II

    Shadow Serpentis Heavy Stasis Grappler
    True Sansha Warp Scrambler
    Republic Fleet Large Cap Battery
    Republic Fleet Large Cap Battery

    Bastion Module I
    Corpus X-Type Heavy Energy Neutralizer
    Neutron Blaster Cannon II
    Neutron Blaster Cannon II
    Neutron Blaster Cannon II
    Neutron Blaster Cannon II
    Corpus X-Type Heavy Energy Nosferatu
    Dark Blood Medium Energy Nosferatu

    Large Auxiliary Nano Pump II
    Large Auxiliary Nano Pump II

### Release or development git branch? Please note the release version or commit hash:
Latest

**Comment by blitzmann** [comment]
You are correct, prop jamming skill was being applied when it shouldn't have been (verified by raw eve data  as well)

This doesn't warrant a new release, but if you're interested in an updated build, please get it here: https://ci.appveyor.com/project/blitzmann/pyfa/build/artifacts

Thanks!
