### ISSUE TITLE
Civilian Analyzers not in Pyfa

### ISSUE THREAD

**Issue by BartMassey** [pyfa-org/Pyfa#1308]
Not even sure if this should be a thing, but the Civilian Relic Analyzer and Civilian Data Analyzer are not in Pyfa right now. Don't ask.

**Comment by blitzmann** [comment]
Civilian modules come up from time to time. I don't really get the point of including them, but since folks regularly ask for this and that to be included, I've gone ahead and just published everything that starts with "Civilian" lol

Currently on the sisi branch. cheers!

**Comment by BartMassey** [comment]
I actually needed these for a fit, believe it or not. Thanks much!
