### ISSUE TITLE
Running very slow

### ISSUE THREAD

**Issue by graphics12** [pyfa-org/Pyfa#1309]
Just installed version 1.32.0 and it is terribly slow.

More than a one minute to open the program initially, for reference Excel 2007 opens in less than 5 seconds.

Screen refresh when I open a fit or make a change takes more than a minute to complete.

Not sure where to look or what to try.  Cleared internet caches, ran the windows tool to clean up the hard drive, ran defrag, scanned for virus or malware, even ran a tool to check the Windows INI files none of that made any difference.

Ideas, theories, help please.

Running Windows 10 Home version 1703.
Intel I-5 3570 processor running at 3.4 GHz.
8 GB memory.

**Comment by blitzmann** [comment]
Hey there,

I run pretty much the exact same specs on my desktop and don't have these issues =/. Did this start happening only with 1.32 or was it an issue with previous versions?

Nothing major changed between releases 31 and 32, especially changes that could reduce startup times. pyfa itself isn't very performant (for various reasons - built on an interpreted language, the calc engine is old and pretty inefficient, etc), but it shouldn't take that long to load. Once a fit loads, is working with the fit relatively fast (ie, is it just initial loading of the data that is slow?)

Could you post your log files here, they can be found in `%userprofile%\.pyfa` and have a .log extension. it might have certain metrics to figure out what is taking a while. Additionally, are you running on a SSD or spinning hard disk?

Thanks :)

**Comment by graphics12** [comment]
Apologies for the delay in responding, family emergency.

Yes the slow screen redraw just started with 1.32 that was what lead me to check all the other things listed first.

**Comment by blitzmann** [comment]
@graphics12 sorry, this fell off my radar.

I'm at a loss as to what is causing it, other than running from a spinning hard disk (which really shouldn't be an issue, especially if 1.31 didn't show symptoms and if it's slow all the time, except when loading data). 1.33 is out now if you want to try it and see if you notice any improvement. Additionally, if you could download and run the 1.31zip again to confirm that is still  is more performant than 1.32 / 1.33.

**Comment by graphics12** [comment]
Thank you for the time and ideas.
I will update to the latest version in the next few days and see what happens.

To all who may read this, I was remiss in noting on my initial post that I did then and still do consider this to be a problem with my computer / software and not a problem with PYFA.

**Comment by Ebag333** [comment]
While it's a few versions back, you could try Pyfa.fit and see if it is better.

There are a number of performance enhancements in it, and that would at least give a interesting data point. 

Keep in mind that it's a fork of Pyfa, and not supported by Blitzmann.

**Comment by blitzmann** [comment]
@graphics12 if you haven't tried yet, give the latest 2.x version a run. There have been some reports of slow start up times in relation to 1.x, but other users have reported faster... so IDFK 😆. With respect to this issue, though, gonna close it due to lack of activity , being older, and it revolving around 1.x which is no longer being developed - don't want to further diagnose an old version if you're not experiencing the issue in 2.x. 

If you are still having slow start up issues with 2.x, please report in #1605 with logs if you can get them. Thanks! 😄
