### ISSUE TITLE
T2 XL Torp/Cruise variants not displaying explosion radius and explosion velocity

### ISSUE THREAD

**Issue by jacobmatthewjansen** [pyfa-org/Pyfa#1325]
### Expected behavior:
Explosion radius and explosion velocity displays in column on fitting window when Precision/Fury/Rage/Javelin ammo variants are loaded into XL Cruise Missile/Torpedo Launcher II's

### Actual behavior:
The area in the fitting window that usually displays this info is blank

### Detailed steps to reproduce:
Load T2 Ammo into a T2 XL launcher on a Phoenix

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Phoenix, Blap]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

XL Cruise Missile Launcher II, Scourge Precision XL Cruise Missile
XL Torpedo Launcher II, Nova Rage XL Torpedo
XL Torpedo Launcher II, Guristas Nova XL Torpedo
Siege Module II
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
https://i.imgur.com/VCmZHUV.png

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
https://i.imgur.com/aJfdFTh.png

**Comment by blitzmann** [comment]
Thanks for this, looks like we weren't handling Advanced groups for XL stuff. Fixed with efea46006aa282b083b78b9a3abdaa817506724a
