### ISSUE TITLE
Market updates invalidate prices

### ISSUE THREAD

**Issue by BartMassey** [pyfa-org/Pyfa#1334]
## Bug Report

When market data is retrieved (from eve-marketdata.com, currently) and no Jita sell orders are active for an item, the cached price for that item is deleted.

### Expected behavior:

Cached prices are retained until a new price becomes available. Ideally, if there are no Jita sell orders, the tool would look globally. (The eve-marketdata API allows this).

### Actual behavior:

See above.

### Detailed steps to reproduce:

Pick a thing for which you have a cached price. Fit it to a ship. Wait for the market to not have any sell orders. Watch the price disappear on the next cache update.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

Was fitting a Federation Navy Medium Armor Repairer.

### Release or development git branch? Please note the release version or commit hash:

1.33.1 Stable

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Debian Linux Stretch

**Comment by blitzmann** [comment]
Fixed in dev branch :)

**Comment by BartMassey** [comment]
Thank you!

**Comment by blitzmann** [comment]
Oh, it seems I never saved my comment on why this was happening. Basically eve-marketdata returns 0 when it doesn't have a price. To counter this, I check to see if it's 0 (market orders should never be 0), and if it is, just use the cache price. Also did a bit of tweaking with the logic.

Hope it helps! :)

**Comment by BartMassey** [comment]
I read the patch. Really appreciate it!
