### ISSUE TITLE
Crash Booster not showing shield booster side affect

### ISSUE THREAD

**Issue by Ligraph** [pyfa-org/Pyfa#1335]
The Crash boosters aren't showing the shield booster side affect in the right click menu.
![image](https://user-images.githubusercontent.com/17717986/32694668-d0ddf4b6-c6fa-11e7-90fc-3b519b6906b2.png)
![image](https://user-images.githubusercontent.com/17717986/32694669-e28fdcc4-c6fa-11e7-970c-59eeeb16343d.png)

**Comment by blitzmann** [comment]
@Ligraph sorry, this fell off my radar! I've got it fixed, along with another bug that would display the menu even if there weren't any side effects for the booster (eg: synth)

#1341

You can get the bug fix build here: https://ci.appveyor.com/project/blitzmann/pyfa/build/artifacts
