### ISSUE TITLE
Add New Alpha Skill Limiter for December Alpha Expansion

### ISSUE THREAD

**Issue by alexanderdarino** [pyfa-org/Pyfa#1338]
Pyfa currently has built-in skill caps for the four racial alpha clones. Coming this December, all four racial alpha clones will be consolidated into a single greatly expanded omniracial clone. Alphas will be able to fly any race's ships, and be able to fly up to T1 BSes, among some other expansions to current capabilities. To aid with fitting in anticipation of this massive release, a "Max Alpha December 2017" skill limiter preset should be added alongside the existing soon-to-be-legacy presets for the four racial Alphas profiles (shown below)

![image](https://user-images.githubusercontent.com/671964/33138001-6d5f56c0-cf77-11e7-93c4-4b359e2ee837.png)

More information:
https://community.eveonline.com/news/dev-blogs/clone-states-the-next-steps/ <<< contains skill levels
https://community.eveonline.com/news/dev-blogs/new-alpha-training-option/

**Comment by blitzmann** [comment]
Yep, I've briefly read up on the new features. Not exactly sure how it's going to work out right now - I'm hoping this stuff is exposed on SISI soonish (haven't checked recently).

As for having a release that has the new mechanics "alongside" the current mechanics, that's not really necessary. Once I get to work on this, hopefully during this long weekend, the changes should be built automatically on appveyor. I'll post something here when I've got some work on this completed :)

Thanks!

**Comment by blitzmann** [comment]
So taking a brief look at the data, it seems CCP is using the same mechanics under the hood - there is still a "clone" for each race, however they are now all identical. It may be easy enough to simply check to make sure they are all the same when I generate the database for pyfa, and then restrict the alpha list to a single clone. I think that would have minimal impact, as well as allow us to branch back into a per-race situation in case CCP reverts it's decision on having all races be the same. :)

**Comment by blitzmann** [comment]
Was actually easier than expected:

https://ci.appveyor.com/project/blitzmann/pyfa/build/development-337/artifacts

WARNING: If you run this test build, it will overwrite you're current alpha characters to alpha clone ID 1. If you decide to go back to the stable release, that would mean all your alpha characters are now Alpha Caldari (IIRC), regardless what they were before. Just a heads up :)
