### ISSUE TITLE
Error on importing Victor (AT15 ship)

### ISSUE THREAD

**Issue by iLLeLogical** [pyfa-org/Pyfa#1345]
# Submit a bug report bug report or feature request

Here you can inform pyfa developers of potential bugs or suggest features / improvements to the project. Please check
to make sure that the bug hasn't been reported or feature requested before submitting. If you have general questions
about the project and want to reach out to the developers personally, please check out out our [Slack]
(https://pyfainvite.azurewebsites.net/).

---

## Bug Report
OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.33.2 Stable - Lifeblood 1.7
pyfa root: C:\Program Files (x86)\pyfa
save path: C:\Users\iLLeLogicaL\.pyfa
fs encoding: mbcs

EXCEPTION: unsupported operand type(s) for -: 'int' and 'NoneType'

  File "C:\Program Files (x86)\pyfa\library.zip\gui\statsPane.py", line 75, in fitChanged
    view.refreshPanel(fit)
  File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinStatsViews\resistancesViewFull.py", line 183, in refreshPanel
    resonance = (1 - fit.ship.getModifiedItemAttr(resonance)) * 100

### Expected behavior:

Succesful import of Victor Fit (from ZKB)

### Actual behavior:
Blank fit window that generates error every time clicked on

### Detailed steps to reproduce:
Import Victor fit from clipboard 

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Victor, kingtuttut Badasaz's Victor]
Hakim's Modified Tracking Enhancer
Republic Fleet Nanofiber Structure
Republic Fleet Nanofiber Structure
Syndicate Damage Control
Tobias' Modified Tracking Enhancer

Corelum A-Type 50MN Microwarpdrive
Thukker Large Shield Extender
True Sansha Stasis Webifier
True Sansha Warp Disruptor
X-Large Ancillary Shield Booster

'Smokescreen' Covert Ops Cloaking Device II
Medium 'Ditch' Energy Neutralizer
Heavy Neutron Blaster II,Null M
Heavy Neutron Blaster II,Null M
Heavy Neutron Blaster II,Null M

Medium Ancillary Current Router II
Medium Anti-EM Screen Reinforcer II

Valkyrie II x2
Valkyrie II x2
Hornet EC-300 x3
Hornet EC-300 x1

**Comment by blitzmann** [comment]
Duplicate #1323

I have a branch that already has these ships, but I'm a bit behind on the december release from Tuesday - just upgrade my battlestation, so I'm still in the process of installing my dev tools and getting everything up to snuff. Should have the 1.34 release out this weekend sometime, keep and eye out for it :)

**Comment by blitzmann** [comment]
btw, if you're interested in running a dev build with the at ships, see https://ci.appveyor.com/project/blitzmann/pyfa/build/development-337/artifacts

It's an old commit and there may have been tweaks to the data between that build and when they went live tuesday, but should be there for the most part
