### ISSUE TITLE
Loggerhead Maintenance Bot Bonuses not Applying

### ISSUE THREAD

**Issue by DinKartay** [pyfa-org/Pyfa#1348]
The shield/armor/structure transfer amounts for any of the logistics drones on the Loggerhead fit is not affected by the 1000% transfer amount bonus.

With perfect skills, the heavy shield/armor t2 should transfer 198 per cycle each after the bonus, for example. However, they only transfer 18 each on a simulated pyfa fit.

When tested as a simulation in the EvE fitting window, the bonuses appear to apply normally.

# Versions:
Latest release v1.34.0 Stable
Windows 10
Eve Data 1219896
Python 2.7.10
wxPython 3.0.2.0
SQLAlchemy 1.0.5
matplotlib 1.4.3

**Comment by blitzmann** [comment]
Thanks for the report, will take a look at it tonight :)

**Comment by blitzmann** [comment]
Fix merged into master :) thanks for the report, and sorry about the long response! Holidays @_@
