### ISSUE TITLE
Feature Request: DPS vs Speed graph

### ISSUE THREAD

**Issue by BaconCatBug** [pyfa-org/Pyfa#1351]
Edit: User error, setting the speed to be a range (e.g. 0-500) sets the lower axis to speed.

**Comment by blitzmann** [comment]
> User error, setting the speed to be a range (e.g. 0-500) sets the lower axis to speed.

I'll be totally honest with you, I didn't know this was a thing. I'll have to double check it to make sure it works as required. It's not intuitive either, so I'll take a look at trying to figure out a way to make this more apparent (or have two graphs that are specific for each)

(I also added back the original feature request for documentation :) )

**Comment by BaconCatBug** [comment]
Sorry about that! From what I see it seems to be accurate (in that the fury
vs cruise graphs looks correct with increasing speed) but I appreciate the
effort you take in making this program better than ever!

**Comment by DarkFenX** [comment]
Implemented in current master
