### ISSUE TITLE
Projecting a Command Burst Doesn't Work

### ISSUE THREAD

**Issue by HindenPeter** [pyfa-org/Pyfa#1352]
### Expected behavior:
Projecting any Command Burst effect onto any other ship should apply the relevant bonuses.

### Actual behavior:
The bonuses are not applied. Bursts also seem to apply a bug to MWDs that shows them as turned off but online, always active (according to the Targeting & Misc section) despite graphically appearing inactive. The MWD cannot be toggled until the projected Command Burst is disabled, whether by toggling the check mark or simply removing the projected fit. Some effects seem to apply by virtue of, for instance, EHP/s increasing on active armor reps when a resistance burst is applied, but not displaying in any other way (doesn't show resistance increase for example).

### Detailed steps to reproduce:
1: Open any (or create a new) fit which has a Command Burst module of any description installed.
2: Open any (or create a new) fit for any ship.
3: Project the ship with the Command Burst onto the other ship.
4: Notice that nothing happens.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

[Stork, Check]

[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Shield Command Burst I, Shield Harmonizing Charge
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]

----

[Scimitar, Skimmi]

Damage Control II
Nanofiber Internal Structure II
Nanofiber Internal Structure II
Nanofiber Internal Structure II

X-Large Ancillary Shield Booster, Navy Cap Booster 400
10MN Afterburner II
Adaptive Invulnerability Field II
Shield Boost Amplifier II
Medium Electrochemical Capacitor Booster I, Navy Cap Booster 800

Pithum C-Type Medium Remote Shield Booster
Pithum C-Type Medium Remote Shield Booster
Pithum C-Type Medium Remote Shield Booster
Pithum C-Type Medium Remote Shield Booster

Medium Ancillary Current Router I
Medium Anti-Kinetic Screen Reinforcer II

Nanite Repair Paste x500
Navy Cap Booster 400 x9
Navy Cap Booster 800 x13

----

[Sleipnir, Passive]

Shield Power Relay II
Shield Power Relay II
Damage Control II
Gyrostabilizer II
Gyrostabilizer II

Republic Fleet Large Shield Extender
Adaptive Invulnerability Field II
Caldari Navy Warp Scrambler
Republic Fleet Large Shield Extender
50MN Cold-Gas Enduring Microwarpdrive

425mm AutoCannon II, Republic Fleet EMP M
425mm AutoCannon II, Republic Fleet EMP M
425mm AutoCannon II, Republic Fleet EMP M
Shield Command Burst II, Shield Extension Charge
Shield Command Burst II, Shield Harmonizing Charge
425mm AutoCannon II, Republic Fleet EMP M
425mm AutoCannon II, Republic Fleet EMP M

Medium Core Defense Field Purger II
Medium Core Defense Field Purger II

Hobgoblin II x5

Republic Fleet Phased Plasma M x800
Active Shielding Charge x300
Shield Harmonizing Charge x300

### Release or development git branch? Please note the release version or commit hash:
Release, v1.34.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10 Home x64

**Comment by jacobmatthewjansen** [comment]
Are you projecting or "Add Command Booster" ?

Using the "Add Command Booster", links are working just fine for me

**Comment by blitzmann** [comment]
Wow, I must have missed this post originally. Yeah, it seems that you are projecting rather than using the command interface. The two are similar, but distinctly different. I can confirm, at least through my quick testing, that this is working as intended. Please reopen if you are still having difficulty or have more information to provide :)
