### ISSUE TITLE
[BUG] Deleting fit from history, the entry remains and deleting twice causes exception.

### ISSUE THREAD

**Issue by antihax** [pyfa-org/Pyfa#1355]
If you delete a fit from the history window, it remains in the window and deleting twice produces a cryptic exception message.

### Expected behavior:
Fitting deleted and removed from list.

### Actual behavior:
Fitting remains, deleting twice causes:
```
OS version: 	Windows-8-6.2
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.34.0 Stable -  Arms Race 1.3
pyfa root: e:\Program Files (x86)\pyfa
save path: C:\Users\user\.pyfa
fs encoding: mbcs

EXCEPTION: 'NoneType' object has no attribute 'name'

  File "e:\Program Files (x86)\pyfa\library.zip\gui\builtinViews\fittingView.py", line 289, in fitRemoved
    sFit.refreshFit(self.getActiveFit())
  File "e:\Program Files (x86)\pyfa\library.zip\service\fit.py", line 1203, in refreshFit
    self.recalc(fit)
  File "e:\Program Files (x86)\pyfa\library.zip\service\fit.py", line 1207, in recalc
    pyfalog.info(u"=" * 10 + u"recalc: {0}" + u"=" * 10, fit.name)
```

### Detailed steps to reproduce:
Attempt to delete a fit twice from history window.

**Comment by blitzmann** [comment]
Hmm, nice catch. Should have this fixed with the next release, everything is a bit slow right now due to the holidays :)

**Comment by blitzmann** [comment]
See here for an updated build with the fix:

https://ci.appveyor.com/project/blitzmann/pyfa/build/bug/1355-375/artifacts

Otherwise it'll be included with the next release :D

Thanks for reporting the bug!
