### ISSUE TITLE
Nos +cap amount is reduced by fit cap batteries

### ISSUE THREAD

**Issue by alelazar** [pyfa-org/Pyfa#1360]
## Bug Report
Nos +cap amount is reduced by fit cap batteries

### Expected behavior:
Nos amount should not be impacted by fitting a cap battery. Nos amount is only impacted by a cap battery on the fit of the ship being targeted. 

### Actual behavior:
Having a cap battery fit reduces the amount a nos gives you. It does not impact the drain amount stated, just the gain amount. 

### Detailed steps to reproduce:
See above. 

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Bhaalgorn, nos test]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

Republic Fleet Large Cap Battery
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Corpus X-Type Heavy Energy Nosferatu
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
Pyfa 1.34.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 7, OSX 10.12.6

**Comment by blitzmann** [comment]
Possible duplicate #1144, #1304

Last time I took a look at it, it wasn't an easy fix (IIRC). I'll have to take a look at it again to refresh my memory. Can you give me exactly the values that you get vs what you are expecting? The more data, the better :)

**Comment by alelazar** [comment]
The nos +cap amount (but not the -cap to target) is reduced by exactly the % stated by the cap battery. 

I would guess that wherever is doing the nos calculations is accidentally pulling the cap battery field even though that field is for nos targeting you, not your own nos.

**Comment by burnsypet** [comment]
In eos/effects/energynosferatufalloff.py the capacitor need calculation was using the amount that had already been modified by the energy warfare resistance. I believe I introduced this defect when working on #1322  😨 

Fix is to only apply the resistance modifier when dealing with a projected module. Will submit a pull request soon to resolve.

**Comment by blitzmann** [comment]
> I believe I introduced this defect when working on #1322 😨

I'm not sure about that,. There have been reports from before your fix was merged in about the cap battery / nos combo being funky. I'm going to spend some time tomorrow looking deeper into it (the fix may very well exacerbate the issue, so will double check that as well =D)
