### ISSUE TITLE
Request for new SISI build with assault frigate changes

### ISSUE THREAD

**Issue by burnsypet** [pyfa-org/Pyfa#1363]
_blitzmann edit: See https://github.com/pyfa-org/Pyfa/issues/1363#issuecomment-362151930 for a link to current sisi branch build_

---

Some of my corp mates have asked for there to be a Pyfa version that contains the assault frigate changes which are now on the SISI test server so that we can do some theory crafting.

I have almost finished making the required effects files and have amended the database to reflect the updates, the only one left to do is the Jaguar as it has been completely changed. @blitzmann if I send you the changes that I've made would you be able to publish a new test server build on the releases page for people to use?

**Comment by blitzmann** [comment]
Yep, I heard that SISI had new changes. I've been extremely busy IRL for the past two weeks as we are moving into a new place (yay!), but if you have some changes feel free to submit a PR *against the singularity branch* and I can review / tweak as needed. :)

**Comment by burnsypet** [comment]
Unfortunately it's just down on EVE-Updates as "Winter 2018". The current version seems fairly WIP... some descriptions and tool tips are missing etc... and there hasn't been a devblog yet so I would hazard a guess at a release in March.

**Comment by blitzmann** [comment]
Hmm, instead of a pre-release then, I would probably recommend just keeping sisi branch up to date as needed and have the builds automatically generated on appveyor, which we can then link to in this issue so people know where to look for it. This will allow us to have a sort of rolling release instead of having to literally doe a pre-release every week or so when things change.

**Comment by burnsypet** [comment]
I've completed all the changes but have been fighting git for the last few hours trying to get everything into the repository. Will send a pull request once I've figured it out.

**Comment by blitzmann** [comment]
:( That sucks, sorry for the trouble. No worries, I'll also look into it this weekend if I have some time. :)

**Comment by blitzmann** [comment]
https://ci.appveyor.com/project/blitzmann/pyfa/branch/singularity/artifacts

This is what I currently have. I don't think the new assault DCUs are fully implemented as I believe they are missing attributes / effect data, however I didn't take a long look. Will try to keep this updated moving forward, new singularity builds should always be available from that link.

**Comment by blitzmann** [comment]
Just added the assault damage control effect, see link above for a new build :)

**Comment by burnsypet** [comment]
Closed as we now have a release, cheers.
