### ISSUE TITLE
Copying a carrier fit breaks fighter damage

### ISSUE THREAD

**Issue by fspigel** [pyfa-org/Pyfa#1371]
## Bug Report

Copying and pasting any carrier or super-carrier fit will stop the client from calculating any fighter damage, even when completely new fighters are added

### Expected behavior:

Fighter damage should be calculated normally (remain the same immediately after copying, then update as fighters are added, removed or changed)

### Actual behavior:

Fighter (drone) damage drops to 0 in the new fit, and fails to update to any new value according to changes such as adding new fighters or removing current ones. Re-opening the fit or client doesn't fix the issue. 

### Detailed steps to reproduce:

1.) In Pyfa, create any fitting capable of launching fighters (so far I've had 100% repro with Nidhoggur, Thanatos, Hel and Aeon)
2.) Copy the fitting using the green copy button next to the fitting name in the left-hand menu

Alternatively:
1.) Create any fitting capable of launching fighters, in pyfa or otherwise
2.) Copy the fit to clipboard
3.) In pyfa, use ctrl-v, or go to Edit->From Clipboard, to load the fit into pyfa

### Fits involved in EFT format (Edit > To Clipboard > EFT):

```
[Aeon, Aeon fit]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]


Templar I x9
Templar I x9
```

```
[Aeon, Aeon fit copy]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]


Templar I x9
Templar I x9
```

### Release or development git branch? Please note the release version or commit hash:

pyfa 1.34.0 Stable - Arms Race 1.3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10

**Comment by blitzmann** [comment]
Hey there,

The reason this is happening is because the new fit does not have any Fighter abilities activated.

![image](https://user-images.githubusercontent.com/3904767/35816035-def70bb8-0a67-11e8-80c6-f71ff30c57f8.png)

And the reason for *that* is because the EFT format does not support which abilities are on / off (no format currently supports this, as it's really a pyfa-specific implementation). I could possibly add support with custom flags, but I'm not sure how other apps that use eft format will handle it. Will take a look into it

**Comment by fspigel** [comment]
Woops, that explains it. As you can see I don't normally simulate carriers. Sorry for wasting your time and please keep up the great work.
