### ISSUE TITLE
Fighter MWD max velocity is too high

### ISSUE THREAD

**Issue by wilki24** [pyfa-org/Pyfa#1372]
## Bug Report
The displayed fighter max velocity while MWD is on, is higher than what is observed in game.

### Expected behavior:
Based on observations in game, with the Nidhoggur fit below, Pfya should show fighter's max MWD velocity as:
17784 m/s MWD
This is what is shown in game on the fighter info while in space. It also matches the top speed observed in the overview when they're going in a straight line.

### Actual behavior:
Pyfa shows the fighter's max speed as:
19772 m/s MWD 

### Detailed steps to reproduce:
Open Pyfa
Use All 5 Character
Import Nidhogger fit from below
Click on the Fighters tab
Right click the Templar II entry->Abilities->Microwarpdrive
Right click the Templar II entry->Fighter Stats
Observe the Current Value Maximum Velocity is shown as 19772 , rather than the correct value 17784 

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Nidhoggur, Nidhoggur]
Prototype Hyperspatial Accelerator
Prototype Hyperspatial Accelerator
Imperial Navy Drone Damage Amplifier
Imperial Navy Drone Damage Amplifier
Imperial Navy Drone Damage Amplifier

Capital Shield Booster I
Omnidirectional Tracking Link II
Omnidirectional Tracking Link II
Omnidirectional Tracking Link II
Drone Navigation Computer II
Sentient Drone Navigation Computer

Networked Sensor Array
Fighter Support Unit II
Fighter Support Unit II
Fighter Support Unit II
Fighter Support Unit I

Capital Hyperspatial Velocity Optimizer II
Capital Hyperspatial Velocity Optimizer II
Capital Hyperspatial Velocity Optimizer II

Optimal Range Script x3
Templar II x19

### Release or development git branch? Please note the release version or commit hash:
Release 1.34.0 Arms Race 1.3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
This seems to be the case with other carriers and fighter combinations, as well.

**Comment by blitzmann** [comment]
Hmm, might be a stacking penalty not being applied correctly. Will double check, thanks!

**Comment by blitzmann** [comment]
That is indeed the issue. Please see https://ci.appveyor.com/project/blitzmann/pyfa/build/bug/1372-370/artifacts for an updated build that includes this fix in case you need it immediately :)
