### ISSUE TITLE
Double agility bonus applied to revenant

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1375]
Current singularity branch. Agility attribute on revenant, all V skills:

Pyfa: 0.0132890625
Expected: 0.01771875

Base: 0.035
Spaceship command: x0.9
Evasive maneuvering: x0.75
Advanced spaceship command: x0.75
0.035×0.75×0.75×0.9 = 0.01771875

Did not check actual ingame value as i do not possess any supercaps

**Comment by lunedis** [comment]
Skill "Capital Ships" gives 25% agility bonus.

https://i.imgur.com/258zXcm.png

**Comment by DarkFenX** [comment]
My bad. Got to double-check numbers next time.
