### ISSUE TITLE
Damage bonus is applied twice for revenant fighters

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1376]
Current singularity branch. fighterAbilityAttackMissileDamageMultiplier attribute on Templar II of revenant, all V skills:

Pyfa: 2.9296875
Expected: 2.34375

Base: 1
Amarr carrier: x1.25
Caldari carrier: x1.25
Fighters: x1.5
1×1.25×1.25×1.5 = 2.34375

Did not check actual ingame value as i do not possess any supercaps

**Comment by lunedis** [comment]
The skill Fighters actually only gives 25% damage bonus. You are forgetting the skill "Drone Interfacing" which gives 50%.

Fighters: 1.25
Drone Interfacing: 1.5
Carrier Bonus Hel: 1.5
Carrier Bonus Revenant: 1.25 each

Hel:
1.25*1.5*1.5 = 2.81125, exactly like in pyfa
Revenant: 
1.25*1.25*1.5*1.25 =2.9296875 like in pyfa

**Comment by DarkFenX** [comment]
Thanks you and sorry for false alert.
