### ISSUE TITLE
Wrong attributes of Cataclysmic Variable Effect

### ISSUE THREAD

**Issue by akmef** [pyfa-org/Pyfa#138]
In description (only desc, not effect itself) of all 6 classes Cataclysmic Variable values of 'Shield repair multiplier' and 'Shield transfer amount multiplier' are contrary.
![image](https://cloud.githubusercontent.com/assets/7958902/3360033/4d11693c-faee-11e3-8bf2-f64a3e64a51c.png)

**Comment by blitzmann** [comment]
Looking through my old eve bug reports. Turns out this was fixed on CCPs side. Yay!
