### ISSUE TITLE
Can't add drones to drone bays

### ISSUE THREAD

**Issue by paulcdejean** [pyfa-org/Pyfa#1383]
pyfa v2.0.0b1

Pretty blatant regression.

**Comment by Velonad** [comment]
Can confirm this error, also running v2.0.0b1 beta update in Windows 10.

If it does matter I'm running it from a dropbox folder.

**Comment by Lucifirius** [comment]
Third confirmation

**Comment by rdymade** [comment]
Also not working on Linux

Distro: Arch Linux

**Comment by paulcdejean** [comment]
Dupes:

https://github.com/pyfa-org/Pyfa/issues/1393

https://github.com/pyfa-org/Pyfa/issues/1388

**Comment by blitzmann** [comment]
Thanks for the report all. Will take a look into this ASAP. This is why we have beta releases \o/
