### ISSUE TITLE
Can't fit fighters to the citadel.

### ISSUE THREAD

**Issue by BloodKhanid** [pyfa-org/Pyfa#1386]
It does not allow to fit fighters into the Fortizar, as well as doesn't show the available fighter tubes for it.
pyfa v2.0.0b1 on Win10 Ent

**Comment by blitzmann** [comment]
Thanks for the report! This is also happening on the stable 1.x branch. I apparently missed the memo on a lot of the citadel changes, looking through them all now. :)

**Comment by blitzmann** [comment]
https://ci.appveyor.com/project/blitzmann/pyfa/build/bug/citadels-397/artifacts

Can you try this build and see if you can poke any holes in it?
