### ISSUE TITLE
Ishkur drone bay

### ISSUE THREAD

**Issue by oovarvu** [pyfa-org/Pyfa#1388]
### Fits involved in EFT format (Edit > To Clipboard > EFT):[Ishkur, Ishkur fit]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]

Acolyte II x1

**Comment by oovarvu** [comment]
my bad, i see this has already been reported.

**Comment by blitzmann** [comment]
No worries, thanks for the report! 

Closing, duplicate #1383
