### ISSUE TITLE
Attempting to create new citadel fitting in debug mode causes crash

### ISSUE THREAD

**Issue by burnsypet** [pyfa-org/Pyfa#1389]
Attempting to create a new fitting for a citadel whilst in debug mode (Windows with -d option set) appears to cause Pyfa to crash. Relevant part in the logs appears to be:

```
[2018-02-15 11:25:48.589000] ERROR: eos.saveddata.ship: Passed item 'Fortizar' (category: Structure) is not under Ship category
[2018-02-15 11:25:48.589000] CRITICAL: __main__: Traceback (most recent call last):
...
[2018-02-15 11:25:48.663000] CRITICAL: __main__: Exception in main thread: maximum recursion depth exceeded while calling a Python object
...
[2018-02-15 11:25:48.678000] WARNING: __main__: Exception in main thread: maximum recursion depth exceeded while calling a Python object
[2018-02-15 11:25:48.678000] CRITICAL: __main__:   File "C:\dev\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 333, in OnLeftUp
...
[2018-02-15 11:25:48.694000] CRITICAL: __main__: Traceback (most recent call last):
```

Does not appear to be an issue when running without debug mode, although this is going to cause a nightmare when trying to troubleshoot problems with citadel fittings like #1387. Will investigate what the issue is this afternoon. I seem to get a similar error when trying to offline a module in debug mode too.

**Comment by burnsypet** [comment]
This failure seems to be caused when executing pyfalog.error in validate() method of ship.py.

Experimenting a bit I added a pyfalog.error output into statsPane.py and it appears that whenever we attempt to call pyfalog,error in debug mode it results in the same crash. I don't think this is intended behaviour.

**Comment by blitzmann** [comment]
I'm not able to reproduce this. Is this with the bundled .exe or running from source?

**Comment by burnsypet** [comment]
Originally noticed it when I did a windows build from source but also appears to happen with the downloaded windows installer. Happens on my windows 7 and windows 10 machines.

**Comment by blitzmann** [comment]
The error itself notes a max recursion error. I wouldn't know why they would be a thing in the ship browser. Can you reproduce it very consistently, and if so, please provide detailed step by step instructions.

Also, is this on 1.35 or 2.0b1? I only tested 1.35

**Comment by burnsypet** [comment]
@blitzmann The critical error does not occur when running 2.x on my Mac. When I get home I will try it on my Windows 7 laptop to see if it happens on there still.

**Comment by blitzmann** [comment]
Thanks @burnsypet!

If it seems to be resolved, or at least not able to be reproduced, go ahead and close this issue. 😄

**Comment by burnsypet** [comment]
Doesn't happen on Windows 7 anymore either so I think this can just be closed.

**Comment by blitzmann** [comment]
Thanks!
