### ISSUE TITLE
Version not being reported correctly in the main window.

### ISSUE THREAD

**Issue by aydjay** [pyfa-org/Pyfa#1390]
Uninstalled pyfa 1.33

Downloaded 2.0.0b1

Extracted zip to a folder. Pressed go button.

Version not being reported correctly in the main window.

![image](https://user-images.githubusercontent.com/9460838/36255320-6fec035e-1246-11e8-9233-a06c80763742.png)

**Comment by blitzmann** [comment]
Ah, yeah. The new pyfa uses a special version file for the about box, while the main window uses what's in config.py. Thanks for the heads up!

**Comment by blitzmann** [comment]
Should be fixed with 82e3db1ffbdef569c5e08a54a219780fa0779795. Still trying to work a final solve for version things, but this solution should work well for now.
