### ISSUE TITLE
v2.0b mac os character window open fail

### ISSUE THREAD

**Issue by bershadskiy** [pyfa-org/Pyfa#1392]
## Bug Report

OS version: Darwin-17.4.0-x86_64-i386-64bit
Python version: 3.6.3 (default, Oct 22 2017, 22:24:50) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.1

####################

wx._core.wxAssertionError: C++ assertion "Assert failure" failed at /Users/robind/projects/buildbots/macosx-vm6/dist-osx-py36/Phoenix/ext/wxWidgets/src/osx/imaglist.cpp(152) in GetIcon(): cannot convert from bitmap to icon

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.MouseEvent'> returned a result with an error set

### Detailed steps to reproduce:
1) Launch app
2) press cmd+E to open characters

**Comment by blitzmann** [comment]
Thanks for the report! OS X is the platform that needs the most testing I feel, and this is great feedback. Will try to hunt this bug down and get a fix our soon :)

**Comment by fswasey** [comment]
Having same issue on Mac OS 10.12.6 (Sierra)

**Comment by blitzmann** [comment]
Fixed with 05f08970c95c9078fe2abc1ccbfb83394a703c43, will try to get another build together soon
