### ISSUE TITLE
[v2.0b] Not able to add drones to ship's drone bay

### ISSUE THREAD

**Issue by PainPlane** [pyfa-org/Pyfa#1393]
## Bug Report

Double clicking or drug'n'dropping the drone to the ship's drone bay takes no effect. 

### Expected behavior:

Drones are added to the drone bay and additional dps is added to the ship's "firepower".

### Actual behavior:

The main fit window refreshes then nothing happens.

### Detailed steps to reproduce:

1) Create fit for any ship.

2) Try to add the drones.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

Bug occurs for any fit.

### Release or development git branch? Please note the release version or commit hash:

Version: v2.0b (py3 branch)
Commit hash: da0f89ef91dba485775d2c53755e2b4078040b6c

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 7

### Other relevant information:

Importing the fitting with drones already in it works as intended.

**Comment by blitzmann** [comment]
Thanks for the report! Duplicate #1383, closing.
