### ISSUE TITLE
"Ship Stats" for Jaguar shows Wolf stats

### ISSUE THREAD

**Issue by stevehinesley** [pyfa-org/Pyfa#1395]
## Bug Report
"Ship Stats" for Jaguar shows Wolf stats

### Expected behavior:
Jaguar should have light missile and rocket bonuses

### Actual behavior:
shows Wolf stats

### Release or development git branch? Please note the release version or commit hash:
1.34.0 Release

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
more /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.3
DISTRIB_CODENAME=sylvia
DISTRIB_DESCRIPTION="Linux Mint 18.3 Sylvia"

**Comment by blitzmann** [comment]
> 1.34.0 Release

Maybe this was a typo, but the latest release cycle is v1.35.x. Additionally, I don't see the same issue. With 1.35, these are the description for the ships:
![image](https://user-images.githubusercontent.com/3904767/36295249-46afabf8-12b4-11e8-9b85-8e95ab8738a8.png)

**Comment by blitzmann** [comment]
Could you provide a bit more detail, maybe a couple screen shots?

**Comment by stevehinesley** [comment]
![jaguar](https://user-images.githubusercontent.com/20214126/36327530-b1576716-1313-11e8-99f4-b1cf2b8119d5.png)
![wolf](https://user-images.githubusercontent.com/20214126/36327537-b95c4292-1313-11e8-8ad4-f6d757770e55.png)
![jaguar2](https://user-images.githubusercontent.com/20214126/36327662-16687cda-1314-11e8-97f5-ed6c2d0bfe64.png)
![wolf2](https://user-images.githubusercontent.com/20214126/36327666-19b3b814-1314-11e8-811f-912066546b2e.png)

**Comment by stevehinesley** [comment]
I'm going to update and see if this is still the case.

**Comment by stevehinesley** [comment]
After updating to 1.35 it is now showing the correct info.
