### ISSUE TITLE
[Feature] Add drag and drop case

### ISSUE THREAD

**Issue by Seavert** [pyfa-org/Pyfa#1397]
It would be very convenient to make possible d&d of fitted module to Projected tab.
Original slot: no actions.
Projected tab: same as dragging exact type from market list.

**Comment by Seavert** [comment]
I know. It is good, but doesnt allow detailed examination of combat states.

**Comment by blitzmann** [comment]
Can you please elaborate a bit more, be as descriptive as possible. I'm not sure what you are suggesting :)

**Comment by Seavert** [comment]
I'll try. Provide capability to drag single fitted module into Projected tab.
Pyfa should check module type and either add it to Projected, or do nothing.

**Comment by blitzmann** [comment]
I feel like there's still a language / terminology barrier here, so please bear with me. :)

You are requesting to be able to do this:
![image](https://user-images.githubusercontent.com/3904767/36635555-20ba1438-1985-11e8-890c-e0f79a12d4ed.png)

From the fitting window, be able to drag a module to the projected pane. This would avoid having to search for that same module in the market browser and apply it from there, and would basically have the same effect as dragging it from the market?

This would certainly be possible. :)

**Comment by blitzmann** [comment]
Thanks for the clarification @Seavert!

https://ci.appveyor.com/project/blitzmann/pyfa/build/master-487/artifacts

Check out this build, I believe this is what you're looking for. Please note: dragging a skill from fitting window to projected panel will not carry over any bonuses (so, for example, a boosted web will not project as booster, it will basically act the exact same way as dragging it form the market).

Hope that helps! :)

**Comment by Seavert** [comment]
Its working. My thanks!

**Comment by blitzmann** [comment]
No problem! Glad you can get some use out of it :)
