### ISSUE TITLE
Select Amount window is too short

### ISSUE THREAD

**Issue by gec100** [pyfa-org/Pyfa#1399]
## Bug Report
Select Amount Window for changing Cargo amount is too short 

### Expected behavior:
-

### Actual behavior:
-

### Detailed steps to reproduce:
-rightclick to item (charge in my case) -> Change charge quantity 

### Fits involved in EFT format (Edit > To Clipboard > EFT):
-

### Release or development git branch? Please note the release version or commit hash:
2.0.0.b1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win10

**Comment by blitzmann** [comment]
Thanks for the report! Will take a look at this soon and try to get it looking better.

**Comment by gec100** [comment]
it is not just a design issue. half of the input window is missing.

**Comment by blitzmann** [comment]
> it is not just a design issue. half of the input window is missing.

Oh, I'm aware, didn't mean it's strictly a design issue, but rather it deals with how the UI is laid out with that window. :)

**Comment by blitzmann** [comment]
Fixed! Will hopefully make another pre-release this weekend if I can shore up a few more of the discovered bugs :)
