### ISSUE TITLE
Error on initial run after install

### ISSUE THREAD

**Issue by Archie8300** [pyfa-org/Pyfa#1402]
## Bug Report
OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.11.0 Stable - Mosaic 1.0
pyfa root: Unknown
save path: Unknown
fs encoding: mbcs

EXCEPTION: defPaths() takes no arguments (1 given)

  File "C:\python-2.7.10\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "C:\Users\Billy\.pyfa\pyfa\library.zip\pyfa__main__.py", line 204, in <module>

### Expected behavior:
install .exe, run wizard, run program.

### Actual behavior:
install .exe, run wizard, run program error.

### Release or development git branch? Please note the release version or commit hash:
Release 1.35.1

### Other relevant information:
moved previous data from old hardrive, maybe it's not in a good state and i couldnt find out how to load my old fits so i tried a new install.

**Comment by Archie8300** [comment]
Nevermind, for some reason i had it nested. Still having the fit issue but that just something i need to figure out.

**Comment by blitzmann** [comment]
Hey there! What do you mean you had it nested?

It should be pretty easy to migrate data from an old install. Find your saveddata.db file (should be under `C:\Users\[username]\.pyfa`) under the old harddrive and move it to the new hard drive, same place.

**Comment by Archie8300** [comment]
Had it C:\Users\Billy\.pyfa\pyfa, reinstalled to User and that one worked. This error was on the new drive, i only mentioned the old drive as that may have affected the file structure. I really need to check for a quick guide to see what is important when migrating, i didnt have the cleanest setup as i was lazy with the .exe installs
