### ISSUE TITLE
Evaluate need for code forcing publishing / market group / etc in the market service

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1407]
I'm thinking this should be done during processing the data into the database, rather than doing it in code on the shipped product. This includes all the `ITEMS_FORCEDMETAGROUP`, `ITEMS_FORCEDMARKETGROUP`, `ITEMS_FORCEGROUP`, etc.

The reason for moving them out of pyfa proper and into the data processing scripts is two-fold:

* decreased processing and complexity as it related to the market code
* prevents situations like #1403 wherein an item was deleted in the database, but wasn't removed from the list in the service (these lists aren't really maintained all that much).

As I'm not sure of the far-reaching implications of this, or any possible reasons for keeping the code as-is, this is simply a reminder to evaluate the situation and make a determination based on that.

Low - medium priority

**Comment by DarkFenX** [comment]
These lists have to be implemented somewhere. CCP data still can be inconsistent. E.g. recently I've checked if we still need this bit:
```
        self.ITEMS_FORCEDMETAGROUP = {
            "'Habitat' Miner I": ("Storyline", "Miner I"),
            "'Wild' Miner I": ("Storyline", "Miner I"),
            "Medium Nano Armor Repair Unit I": ("Tech I", "Medium Armor Repairer I"),
            "Large 'Reprieve' Vestment Reconstructer I": ("Storyline", "Large Armor Repairer I"),
            "Khanid Navy Torpedo Launcher": ("Faction", "Torpedo Launcher I"),
            "Dark Blood Tracking Disruptor": ("Faction", "Tracking Disruptor I")}
```
And we still do. All of these items have have no metagroup info.

To reduce processing costs, we *might* move it to data dumping script. However, with some overrides it still will not be possible: at the very least, limited edition ship group. If we do that, it will affect ship calculations (e.g. ADC won't be fittable to Malice).

But we cannot get rid of maintenance cost in any case. These have to be maintained by person which handles Pyfa update for EVE expansion.
