### ISSUE TITLE
Export HTML not working

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1411]
This is for version 2.0.0b3

Clicking on File>Export HTML
results in the backup fits dialog box hanging
and force close being the only recovery option.
A blank pyfaFits.html is created in the installed pyfa versions folder.

**Comment by Neugeniko** [comment]
Checked this and appears fixed.

**Comment by lunedis** [comment]
What does the HTML export even do, with the IGB removed?

**Comment by Neugeniko** [comment]
It gives you a html file where you can navigate your fits and open them in osmium. I guess for taking to work were pyfa might not be installed, hehe?

**Comment by blitzmann** [comment]
> What does the HTML export even do, with the IGB removed?

Admittedly it's pretty redundant now, but I know of some folks that still like this functionlity, and it doesn't really hurt to keep it included. It just kind of exists. <_<
