### ISSUE TITLE
Export Skills Needed not working

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1412]
This is for version 2.0.0b3

Clicking on File>Export Skills Needed
then Selecting a EVEMon skills training file (*.emp)
results in a invalid emp file that evemon wont import.
The message popup box on export remains in the foreground
until the computer is reset.

**Comment by blitzmann** [comment]
Thanks for the report. I am interested in knowing how EVEMon is fairing these days - is it still updated? Still used? I know they had a bit of a rough patch when they switched developers. I would need to know why it fails to import, would you happen to have a sample file to test with?

The fact that the export dialog remains open is probably related to your other issues - the progress dialogs as a whole may be bugged, will take a look tonight. Thanks!

**Comment by Neugeniko** [comment]
Here is the evemon file it created for me.

**Comment by blitzmann** [comment]
kk, it was an encoding issue. The emp file it produced wasn't even produced correctly, which would explain why EVEMon rejected it. I would try it again with the latest commit and see if it's working now :)

**Comment by blitzmann** [comment]
gonna mark this as fixed for now, let me know if the EVEMon stuff doesn't actually work

**Comment by Neugeniko** [comment]
This is fixed from the file menu. This is NOT fixed from the context menu Export Missing Skills (right click skill book next to a fit/character combo that needs skills) .

**Comment by blitzmann** [comment]
Totally forgot that was a thing! Checking now

**Comment by blitzmann** [comment]
Ah wait, that one copies to clipboard, not generates an EVEMon file.

Going to rename it to "Copy Missing Skills"

**Comment by Neugeniko** [comment]
Well it does copy to clipboard so i guess this is fixed.

**Comment by Neugeniko** [comment]
The fixed label was removed for a trivial reason. Probably should put it back.

**Comment by blitzmann** [comment]
@Neugeniko thanks for reminding me :) Would have totally missed this
