### ISSUE TITLE
Minor mistake - module stats

### ISSUE THREAD

**Issue by Seavert** [pyfa-org/Pyfa#1413]
Standup Market Hub I (and probably all service modules).
Shown attribute: Service Module Fuel Need.
Shown value: Plutonium Charge S Blueprint (1136).
"Fahrenheit 451".

In fact attribute 2108 has name "serviceModuleFuelConsumptionGroup".
So value 1136 is not type_id, but group_id - "Fuel Block".

**Comment by blitzmann** [comment]
Hmm, interesting. Will take a look, thanks :)

**Comment by blitzmann** [comment]
This seems to be a bug on CCPs side. 

https://esi.tech.ccp.is/latest/dogma/attributes/2108/?datasource=tranquility

Unit ID = 116, which is TypeID, not GroupID.

I'll file a bug report about this :)

**Comment by blitzmann** [comment]
Bug report EBR-145044 filed, just gotta wait for CCP to fix it (if they feel so inclined)

**Comment by Seavert** [comment]
Dark age is over.

**Comment by blitzmann** [comment]
Huzzah!
