### ISSUE TITLE
Canot remove cap boosters and scripts from structure cargo

### ISSUE THREAD

**Issue by jacobmatthewjansen** [pyfa-org/Pyfa#1414]
## Bug Report
It is not possible to remove cap boosters and scripts from the cargo of structures without exporting the fit and editing the pyfa block (and then importing the fit).  It is possible to add cap boosters and scripts to the cargo of structures but the cargo is not selectable when editing the fit.  

### Expected behavior:
Scripts should be able to be added to the cargo for structures as we now have the scram script as well as the ECM scripts.  The Cargo should be a functioning tab when editing the fits of structures

### Actual behavior:
The cargo tape is not a functioning tab when editing fits of structures

### Detailed steps to reproduce:
Add a script to a Fortizar cargo and then try to remove it

### Fits involved in EFT format (Edit > To Clipboard > EFT):

[Fortizar, CARGO PROBLEMS]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

[Empty Service slot]
[Empty Service slot]
[Empty Service slot]
[Empty Service slot]
[Empty Service slot]

Cap Booster 800 x1000
Targeting Range Dampening Script x1000
Standup Gravimetric ECM Script x1000
Standup Ladar ECM Script x1000
Standup Magnetometric ECM Script x1000
Standup Radar ECM Script x1000
Missile Range Disruption Script x1000
Armor EM Resistance Script x1000
Armor Thermal Resistance Script x1000
Focused Warp Scrambling Script x1000
Standup Focused Warp Scrambling Script x1000

### Release or development git branch? Please note the release version or commit hash:
1.35.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
OSX 10.13.3

### Other relevant information:
N/A

**Comment by blitzmann** [comment]
Hello, and thanks for the report!

> The cargo tape is not a functioning tab when editing fits of structures

Structures don't have cargo, so this tab was never intended to be used for structures. However, I do see the appeal of having a space to store things like ammo / scripts for structures, I'll look into adding cargo support :)

> Add a script to a Fortizar cargo and then try to remove it

This is probably an old bug in which we disable the cargo tab, but we don't disable the functionality of adding things to cargo via the context menu. This should all clear up if I get the cargo space working for structures :)
