### ISSUE TITLE
Character Editor Save as creates two characters.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1419]
This is for version v2.0.0b3.

Create a blank Character.
Select a fit and grant this character missing skills.
In Character editor click save as for this character. (Save as dialog window size is too small too)
Enter a name and click ok.

Results in.
A newly saved character with the copied skills.
And a newly saved character with empty skills.

**Comment by blitzmann** [comment]
So... this is odd. 

https://github.com/pyfa-org/Pyfa/blob/8f42822d9ef41d741daa3520404603a6f73b6c02/gui/characterEditor.py#L906

Change is called twice when saving. still looking into it

**Comment by blitzmann** [comment]
I have no f'ing idea why this is happening, really confusing. Seems that every time the dialog is attempting to close, it runs the `change()`  function again.

I'm going to get rid of that dialog and use the same one that pops up when editing the character name. It's a better looking dialog anyway <_<

**Comment by blitzmann** [comment]
Oh... this also affect 1.35. >.<

**Comment by blitzmann** [comment]
Fixed in master, pulled into 2.x
