### ISSUE TITLE
Error exporting overrides.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1420]
This is for version v2.0.0b3.

Go into the attribute editor.
Edit some attribute.
Click File>Export
Set a name and click save.

Attempting to export a overrides file results in this error.
OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.11.1
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\propertyEditor.py", line 130, in OnExport
TypeError: a bytes-like object is required, not 'str'

The exported file is empty. Should have overrides in it.

**Comment by Neugeniko** [comment]
Checked this and appears fixed.

**Comment by blitzmann** [comment]
woo!
