### ISSUE TITLE
Apply version information to Windows .exe

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1429]
![image](https://user-images.githubusercontent.com/3904767/36634018-586530b6-196c-11e8-9432-759aebccc762.png)

A little backstory. Due to the way builds worked for 1.x, this version information never changed (1.15 was the last time we generated Windows binaries for pyfa 1.x, since then we've simply been replacing the code with updates and never touching the binary). There was an issue a while back, #493, that was never addressed, partly because of the difficulty of changing that information without doing a new binary build (which was a PITA).

With 2.x and the use of PyInstaller, this should be much more straightforward. Have to get an idea of how PyInstaller can create an executable with versioning information, but I don't imagine it'll be too difficult.

**Comment by blitzmann** [comment]
Tried to figure this out, seems to also be a PITA. I've added the version file to dist_assets/win, but putting this to the side for now, may have to ping pyinstaller team

**Comment by blitzmann** [comment]
I'm just gonna say fuck it. If there's a legitimate need to versioning in the exe file itself, let me know and I'll consider looking into this again. But it seems to be a huge pain in the ass

**Comment by minlexx** [comment]
:rofl: Can you please leave some links where I can read about this topic?
