### ISSUE TITLE
Cursor is not shown when renaming a fit for the second time.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1431]
### Expected behavior:
Cursor is shown when renaming a fit.

### Actual behavior:
Cursor is not shown when renaming a fit for the second time.

### Detailed steps to reproduce:
Select a fit
Rename it
Rename it a second time and note no cursor.

* Work around is to go back in the ship tree and come back to the fits.

### Release or development git branch? Please note the release version or commit hash:
py3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win 10

**Comment by blitzmann** [comment]
This also happens in 1.x...

That's very odd, nothing immediately comes to mind as a reason for this.

**Comment by Neugeniko** [comment]
This one is tough. There is a correlation between the state of the background and whether the cursor is shown that could be a hint.

**Comment by blitzmann** [comment]
Might be easy enough to to a `.SetFocus()` on the TextCtrl whenever it's shown. Doesn't fix the underlying cause of why, but it's a quick fix without any negative side effects that I can think of (if it works)

**Comment by blitzmann** [comment]
So I believe this is the cause:

fitItem.py:

`self.tcFitName.Bind(wx.EVT_KEY_DOWN, self.editCheckEsc)`

Removing this fixes it, however I believe we still want the ESC to close the edit. I'm not sure why this is the case, and the problem is exacerbated by the fact that this is a drawn widget

**Comment by Neugeniko** [comment]
I have the previous line as the cause.

self.tcFitName.Bind(wx.EVT_KILL_FOCUS, self.editLostFocus)

**Comment by Neugeniko** [comment]
I can comment out that line, modify editLostFocus to not take events and call it at the end of renamefit to hack around this and get the cursor all the time.

**Comment by blitzmann** [comment]
>I have the previous line as the cause.

Ah, nice catch, I was going off memory from a previous test >.<

But you lead me to the right thing, added `event.Skip()` to that function and it seems to have fixed it. Can you test latest commit?

**Comment by Neugeniko** [comment]
Seems to work now, can rename fits multiple times and retains the cursor. This is a nice QOL fix for ppl who rename fits alot, like me \o/ .

**Comment by blitzmann** [comment]
Awesome! Will mark as fixed, thanks!
