### ISSUE TITLE
Export DNA, Multibuy doesn't respect Export Loaded charges preference.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1433]
### Expected behavior:
When export loaded charges is off I expect no loaded charges to be exported in DNA Export.
When export loaded charges is on I expect loaded charges to be exported in Multibuy.

### Actual behavior:
When export loaded charges is off loaded charges are exported in DNA Export.
When export loaded charges is on loaded charges are not exported in Multibuy.

### Detailed steps to reproduce:
(1)
Set preference off for export loaded charges.
Select a fit with charges loaded.
Press Ctrl-C and select DNA
Press Ctrl-V
Note the fit has charges in cargo

(2)
Set preference on for export loaded charges.
Select a fit with charges loaded.
Press Ctrl-C and select Multibuy
View Clipboard and note multibuy output has no loaded charges listed.

### Release or development git branch? Please note the release version or commit hash:
py3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win 10

**Comment by blitzmann** [comment]
Hmm, yeah looks like DNA just includes them by default.

Not sure I can reproduce what you report about the multi-buy. The charges are added / not added correctly depending on the setting for me.

**Comment by Neugeniko** [comment]
Ill have another look at multibuy.

**Comment by blitzmann** [comment]
Thanks @Neugeniko!

**Comment by Neugeniko** [comment]
My mistake I must have had tunnel vision and missed the charges in the middle of the list. Multibuy does respect the export loaded charges preference.

**Comment by blitzmann** [comment]
No worries! Thanks for the report as always :D

**Comment by Neugeniko** [comment]
I take it charges are handled with cargo by dna?

**Comment by blitzmann** [comment]
Yeah, DNA isn't smart enough to say "this was loaded into this weapon". It sees it in the format and says "that's not a module, must be in the cargo" and sticks it in the cargobay. This can be seen on those fittings you cshare in the in-game chat; they are powered by DNA, and don't support much.

I'm kind of hoping with CCP developing out a chat system using XXMP as a backend that they can develop a new, more robust format.
