### ISSUE TITLE
Error in Character Editor after importing same character file twice.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1440]
### Expected behavior:
When selecting the second character imported in character editor I expect the character info to be shown. 

### Actual behavior:
When selecting the second character imported in character editor, the following error is thrown.
OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.2.4
Logbook version: 1.2.1
Requests version: 2.18.4
Dateutil version: 2.6.1

####################

Traceback (most recent call last):
  File "C:\Program Files (x86)\Newark\prog\Pyfa\gui\characterEditor.py", line 504, in charChanged
    self.btnSecStatus.SetLabel("Sec Status: {0:.2f}".format(char.secStatus or 0.0))
ValueError: Unknown format code 'f' for object of type 'str'

### Detailed steps to reproduce:
Load the app.
File>Import Character
Select the attached file
File>Import Character
Select the attached file
Go to character editor
Select the 2nd character with the same name.
Note error.

### Release or development git branch? Please note the release version or commit hash:
py3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win 10

### Other relevant information:

Attached File:
[Florinio (after plan VNI & Vexor).zip](https://github.com/pyfa-org/Pyfa/files/1758001/Florinio.after.plan.VNI.Vexor.zip)

EDIT: Also note, for some reason importing a character navigates the ship browser.
EDIT: Also happens if the two imports use different character files. And happens on every 2 4 6 even character imported.

**Comment by blitzmann** [comment]
Thanks! Will take a look at this :)

**Comment by blitzmann** [comment]
Also present in 1.x

**Comment by Neugeniko** [comment]
Any idea why the ship browsers gets navigated here when doing a character import?

**Comment by blitzmann** [comment]
> Any idea why the ship browsers gets navigated here when doing a character import?

After testing it out a bit more... so, I think it's a by-product of double clicking as mentioned above: it seems the last click is registered on the main window, which is usually over the ship browser. See photo:

![image](https://user-images.githubusercontent.com/3904767/36735721-d1c0e7d6-1ba4-11e8-8e15-b959922e2ef1.png)

Not exactly sure how or why this might happen, nor any ideas on how it might be fixed. There may be a style for `wx.FileDialog` that we can use to prevent clicks from bubbling up, that would be the first place to look methinks
