### ISSUE TITLE
File Dialogs: Double clicking registers through dialog and onto main window

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1447]
https://github.com/pyfa-org/Pyfa/issues/1440#issuecomment-368758385

This may not be a fixable thing, I need to create a small test application to see if I can get this to reproduce easily, then ask around if this is a bug or if we're missing something like a style for the FileDialog

**Comment by Neugeniko** [comment]
So far I am unable to reproduce this issue with the Import Fitting dialog.

**Comment by blitzmann** [comment]
So, I can't reproduce with a small skeleton application (see below). That leads me to believe that maybe it's has to do with how we're processing events for the ship browser widgets (they have a bunch of different mouse events that they bind to). Further testing is required.

```
import wx


class MyFrame(wx.Frame):

    def __init__(self):
        wx.Frame.__init__(self, None, wx.ID_ANY, size=(600, 600))

        mainSizer = wx.BoxSizer(wx.VERTICAL)

        panel = wx.Panel(self, wx.ID_ANY)

        button = wx.Button(panel, wx.ID_OK, "Open File Dialog")
        button.Bind(wx.EVT_BUTTON, self.OpenFileDialog)
        mainSizer.Add(button, 0, wx.ALL, 5)

        panel.SetSizer(mainSizer)

        panel.Bind(wx.EVT_LEFT_DOWN, self.OnLeftDown)
        self.Layout()

    def OnLeftDown(self, event):
        print("Left Down")

    def OpenFileDialog(self, event=None):
        dlg = wx.FileDialog(
            self,
            "Open file",
            wildcard="XML (*.xml)|*.xml|All Files (*)|*",
            style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST | wx.FD_MULTIPLE
        )

        if dlg.ShowModal() == wx.ID_OK:
            print("File selected")

# Run the program
if __name__ == "__main__":
    app = wx.PySimpleApp()
    frame = MyFrame().Show()
    app.MainLoop()
```

**Comment by blitzmann** [comment]
`self.Bind(wx.EVT_LEFT_UP, self.OnLeftUp)` in `SFBrowserItem` is the culprit it seems. Indeed, adding a handler for this event on the sample above reproduces the issue. Now to figure out how to fix it.

**Comment by blitzmann** [comment]
https://groups.google.com/forum/#!topic/wxpython-users/Ns87yYCOPzM

Fingers crossed we get a couple answers. If nothing happens within a few days, I'll post on the wxPython issues page for support :)

**Comment by blitzmann** [comment]
Good to know! I'll wait a few more days and try to ping Robin if the usegroup doesn't turn up anything.

**Comment by blitzmann** [comment]
I've logged an issue at https://github.com/wxWidgets/Phoenix/issues/777

Hopefully can get a few answers here :)

**Comment by blitzmann** [comment]
It's been noted on the wxPython issue that this is really an issue with wxWidgets, and has been around forever, Robin suggested a workaround utilizing `wx.Yield()` but I wasn't able to figure out how to get it to work in the simple example provided. And then we have to deal with how we would do this for out much more complex use case.

I'm putting this on the back burner for now - it's a pretty small bug / annoyance, will have to take a look the next time I have some free time to kill. Open to others making suggestions / patches :)

**Comment by blitzmann** [comment]
Got a bit of help on the wxPython issue page, was able to fix this after that. It's a bit ugly, but functional. :D
