### ISSUE TITLE
Bug Report - Survey Scanner

### ISSUE THREAD

**Issue by RedViper9** [pyfa-org/Pyfa#1450]
## Bug Report
OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.35.1 Stable - YC120.2 1.2
pyfa root: C:\Program Files (x86)\pyfa
save path: C:\Users\_Redacted_\.pyfa
fs encoding: mbcs

EXCEPTION: 'NoneType' object has no attribute 'ID'

  File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinMarketBrowser\itemView.py", line 115, in selectionMade
    items = sMkt.getItemsByMarketGroup(mg)
  File "C:\Program Files (x86)\pyfa\library.zip\service\market.py", line 641, in getItemsByMarketGroup
    forceditms = set(self.getItem(itmn) for itmn in self.ITEMS_FORCEDMARKETGROUP_R[mg.ID])
  File "C:\Program Files (x86)\pyfa\library.zip\service\market.py", line 641, in <genexpr>
    forceditms = set(self.getItem(itmn) for itmn in self.ITEMS_FORCEDMARKETGROUP_R[mg.ID])
  File "C:\Program Files (x86)\pyfa\library.zip\service\market.py", line 391, in getItem
    item = eos.db.getItem(identity, *args, **kwargs)
  File "C:\Program Files (x86)\pyfa\library.zip\eos\db\gamedata\queries.py", line 59, in checkAndReturn
    return function(*args, **kwargs)
  File "C:\Program Files (x86)\pyfa\library.zip\eos\db\gamedata\queries.py", line 94, in getItem
    itemNameMap[lookfor] = item.ID

### Expected behavior:
Market > Scanning Equipment > Survey Scanners
Should list survey scanners.

### Actual behavior:
Does not list survey scanners, produces error pasted above.

### Detailed steps to reproduce:
Go to: Market > Scanning Equipment > Survey Scanners
Tried with a variety of different ships including no ship, various characters.
Uninstalled / Reinstalled fresh since previously I was overwriting the existing installation.
Problem persists.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
Hulk (blank or fitted), Ishkur (blank), Atron (blank), close pyfa and reload so no ship is in tab, all failed.

### Release or development git branch? Please note the release version or commit hash:
Release 1.35.1 Stable - YC120.2 1.2
Installed via Win .exe file.

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10 Pro

**Comment by blitzmann** [comment]
Thanks @RedViper9! Duplicate #1403. This is a known bug that was fixed, just hasn't been deployed yet (it was not considered a large enough bug to warrant a point release on it's own).

I will probably do a point release this weekend to include various fixes to bugs that have recently been discovered. If you need a build with this bug fixed, see the mentioned issue for an updated build. :)

**Comment by Neugeniko** [comment]
Also present in py3 branch.

**Comment by blitzmann** [comment]
Hrm, seems I never committed a removal of another item from the market service. I've committed another fix in master and py3 branch
