### ISSUE TITLE
Import Character fails to import CCP EVE API XML files.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1453]
### Expected behavior:
EVE API Character file gets imported.

### Actual behavior:
Character is not imported. No error.

### Detailed steps to reproduce:
File > Import Character File
Select and OK the attached File below
Note no character is added to the character list.

 
### Release or development git branch? Please note the release version or commit hash:
py3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
[Start Minmatar.zip](https://github.com/pyfa-org/Pyfa/files/1773295/Start.Minmatar.zip)

**Comment by Neugeniko** [comment]
Looks like the XML file parser is expecting bytes instead of the new unicode? stream our open provides.

xmlparser.ParseFile(file)
Parse XML data reading from the object file. file only needs to provide the read(nbytes) method, returning the empty string when there’s no more data.

So line 66 in service/character.py should read

with open(path, mode='rb') as charFile:

Will make a pull request.

will make a

**Comment by Neugeniko** [comment]
Not a issue in 1.35.1

**Comment by blitzmann** [comment]
Thanks for the report and fix! Just merged it :)
