### ISSUE TITLE
Warp Disruption Field Generators & Standup Focused Warp Disruptor working incorrectly.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1456]
### Expected behavior:
These modules only turn off MWD when they have a scrambling script loaded.

### Actual behavior:
These modules turn of MWD all the time.

### Detailed steps to reproduce:
Self project the following fit and note the mwd is turned off irrespective of it being loaded
with disruption, scrambling or none scripts.
Also project the Standup Focused Warp Disruptor and note the same.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Broadsword, AC IP PS MW]

IFFA Compact Damage Control
Gyrostabilizer II
Gyrostabilizer II
Tracking Enhancer II

50MN Y-T8 Compact Microwarpdrive
Large F-S9 Regolith Compact Shield Extender
Adaptive Invulnerability Field II
Large F-S9 Regolith Compact Shield Extender
Adaptive Invulnerability Field II
Adaptive Invulnerability Field II

425mm AutoCannon II
425mm AutoCannon II
Warp Disruption Field Generator II
425mm AutoCannon II
425mm AutoCannon II
425mm AutoCannon II

Medium Core Defense Field Extender II
Medium Core Defense Field Extender II

### Release or development git branch? Please note the release version or commit hash:
py3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win 10

**Comment by Neugeniko** [comment]
https://support.eveonline.com/hc/en-us/articles/115004925705-Warp-Scrambling-and-Warp-Disruption

**Comment by Neugeniko** [comment]
warpscrambleblockmwdwithnpceffect.py and structurewarpscrambleblockmwdwithnpceffect.py are the places where the mwd is turnoff.

**Comment by Neugeniko** [comment]
warpdisruptsphere.py effects the Warp Disruption Field Generators. But it has some garbage? that is causing another bug. They also turn off MJD so we need to turn those off too. I am unable to reproduce the original bug that started this issue.

All this stuff I dont think it belongs here.

fit.ship.boostItemAttr("mass", module.getModifiedItemAttr("massBonusPercentage"))
fit.ship.boostItemAttr("signatureRadius", module.getModifiedItemAttr("signatureRadiusBonus"))
fit.modules.filteredItemBoost(lambda mod: mod.item.group.name == "Propulsion Module",
                              "speedBoostFactor", module.getModifiedItemAttr("speedBoostFactorBonus"))
fit.modules.filteredItemBoost(lambda mod: mod.item.group.name == "Propulsion Module",
                              "speedFactor", module.getModifiedItemAttr("speedFactorBonus"))
fit.ship.forceItemAttr("disallowAssistance", 1)

**Comment by Neugeniko** [comment]
OK warpdisruptsphere.py is for the ship module and structurewarpscrambleblockmwdwithnpceffect.py is for the structure module. warpscrambleblockmwdwithnpceffect.py is for normal scrams. The following file changes work.

**warpdisruptsphere.py**
```
# warpDisruptSphere
#
# Used by:
# Modules from group: Warp Disrupt Field Generator (7 of 7)
from eos.saveddata.module import State

type = "projected", "active"
runTime = "early"


def handler(fit, module, context):
    #fit.ship.boostItemAttr("mass", module.getModifiedItemAttr("massBonusPercentage"))
    #fit.ship.boostItemAttr("signatureRadius", module.getModifiedItemAttr("signatureRadiusBonus"))
    #fit.modules.filteredItemBoost(lambda mod: mod.item.group.name == "Propulsion Module",
    #                              "speedBoostFactor", module.getModifiedItemAttr("speedBoostFactorBonus"))
    #fit.modules.filteredItemBoost(lambda mod: mod.item.group.name == "Propulsion Module",
    #                              "speedFactor", module.getModifiedItemAttr("speedFactorBonus"))
    #fit.ship.forceItemAttr("disallowAssistance", 1)
    #
    #if "projected" in context:
    #    fit.ship.increaseItemAttr("warpScrambleStatus", module.getModifiedItemAttr("warpScrambleStrength"))
    #
    #   if module.charge is not None and module.charge.ID == 45010:
    #        for mod in fit.modules:
    #            if not mod.isEmpty and mod.item.requiresSkill("High Speed Maneuvering") and mod.state > State.ONLINE:
    #                mod.state = State.ONLINE
    if "projected" in context:
        fit.ship.increaseItemAttr("warpScrambleStatus", module.getModifiedItemAttr("warpScrambleStrength"))
        if module.charge is not None and module.charge.ID == 45010:
            for mod in fit.modules:
                if not mod.isEmpty and mod.item.requiresSkill("High Speed Maneuvering") and mod.state > State.ONLINE:
                    mod.state = State.ONLINE
                if not mod.isEmpty and mod.item.requiresSkill("Micro Jump Drive Operation") and mod.state > State.ONLINE:
                    mod.state = State.ONLINE
```

**structurewarpscrambleblockmwdwithnpceffect.py**
```

# Not used by any item
from eos.saveddata.module import State

# Not used by any item
runTime = "early"
type = "projected", "active"


def handler(fit, module, context):
    #if "projected" not in context:
    #    return

    #fit.ship.increaseItemAttr("warpScrambleStatus", module.getModifiedItemAttr("warpScrambleStrength"))

    # this is such a dirty hack
    #for mod in fit.modules:
    #    if not mod.isEmpty and mod.item.requiresSkill("High Speed Maneuvering") and mod.state > State.ONLINE:
    #        mod.state = State.ONLINE
    if "projected" in context:
        fit.ship.increaseItemAttr("warpScrambleStatus", module.getModifiedItemAttr("warpScrambleStrength"))
        if module.charge is not None and module.charge.ID == 47336:
            for mod in fit.modules:
                if not mod.isEmpty and mod.item.requiresSkill("High Speed Maneuvering") and mod.state > State.ONLINE:
                    mod.state = State.ONLINE
                if not mod.isEmpty and mod.item.requiresSkill("Micro Jump Drive Operation") and mod.state > State.ONLINE:
                    mod.state = State.ONLINE
```

**Comment by Neugeniko** [comment]
The micro jump field generator has no active state so this code cant be shown to turn it off.

**Comment by Neugeniko** [comment]
There is a bug, also present in 1.35.1, as well as here. Where the state of the mwd shows as online but stats under misc & targeting show it as active. Some sort of race?

**Comment by Neugeniko** [comment]
fit.ship.forceItemAttr("disallowAssistance", 1) stops all projected effects?

**Comment by Neugeniko** [comment]
I double checked everything with the in game simulator as to the rather complex operation of the WDFG.

**Comment by blitzmann** [comment]
Lots of info here, will try to process as soon as I can. Will respond hopefully tonight :)

**Comment by Neugeniko** [comment]
Should stuff that is projected and stuff that is applied to the ship be seperate effects files? Because I have to seperate the projected from the other effects . warpdisruptsphere.py above updated.

**Comment by blitzmann** [comment]
> Should stuff that is projected and stuff that is applied to the ship be seperate effects files? 

Negative. if the effect needs to do something different depending on the context in which it's run, it should be handled just as you've handled it.

Can you go ahead and create a pull requestfor this issue and the fixes you're proposing? It's easier to review in a PR :)

It seems like these all work well (i do have a question about `warpDisruptSphere`, right now you have it not affecting mass/sig/etc of Projecting fit if there's not charge. I think it's supposed to always do those? but you said you checked in game as to the calculations, just wanted to clarify)

**Comment by Neugeniko** [comment]
> It seems like these all work well (i do have a question about warpDisruptSphere, right now you have it not affecting mass/sig/etc of Projecting fit if there's not charge. I think it's supposed to always do those? but you said you checked in game as to the calculations, just wanted to clarify)

The in game simulator only adjusts mass, sig etc of the projecting fit if the module is on and it has no charge. I've also confirmed this with pilot of heavy interdiction cruisers.

**Comment by Neugeniko** [comment]
PR has been put in.

**Comment by Neugeniko** [comment]
Also present in master.
