### ISSUE TITLE
Citadel HP and Full Power mode calculations

### ISSUE THREAD

**Issue by patrickebates** [pyfa-org/Pyfa#1460]
Took me awhile to realize exactly what was going on when I had a Tatara build with 200 million EHP, but I think I have tracked it down to an issue with how you are applying Full Power mode to the citadels.

If I strip out or turn off all of the service modules, the armor and shield HP drops correctly to 2/3 of the structure HP.  Add or enable a single service module, and the armor and shield HP rise to equal the structure.  So far so good.

Now add or enable a second service module.  The 50% bonus to armor and shield HP is added again, even though it should only be calculated once.

Expand that to a Tatara with five service modules enabled, and you end up with 91.1M each for armor and shield.

**Comment by blitzmann** [comment]
> Now add or enable a second service module. The 50% bonus to armor and shield HP is added again, even though it should only be calculated once.

Well... fuck. Hrm... gonna have to think about this one. Thanks for the report, as well as the preliminary investigation!

**Comment by blitzmann** [comment]
Huh, that was easier than I thought

**Comment by blitzmann** [comment]
it will take a few minutes to build, but once it's done, an updated build should be available here:
https://ci.appveyor.com/project/blitzmann/pyfa/build/master-518/artifacts

if you could report back and let me know if it works well, that would be great :)

**Comment by patrickebates** [comment]
Looks like a winner to me.  The HP is stable with the Tatara settings I mentioned above.  I went through and disabled and enabled service modules to verify.

**Comment by blitzmann** [comment]
\o/
