### ISSUE TITLE
What IDE is Pyfa mostly programmed in?

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1461]
I've been using bash on ubuntu on windows for text search, edit, git etc. And just python 3.6 installed. No debugger until yesterday when I tried Pycharm educational. Today im looking at Pydev on eclipse. What do you use blitzman?

**Comment by blitzmann** [comment]
PyCharm is God. 

You haven't been using a debugger all this time? My apologies, I should have mentioned this a while back lol. I have a PyCharm Professional open-source license, but the regular Community edition would work just fine. I've never really used anything else but PyCharm - when I was first getting started it was a lot of Notepad++ and `print` statements lolol

**Comment by blitzmann** [comment]
PyCharm also has Git integration, so you can change branches, view the log, do merge conflicts, etc. However, I personally use [GitExtensions](https://github.com/gitextensions/gitextensions) for managing my git (except merge conflicts, I do those in PyCharm... it's just so nice and much better than kdiff or whatever the fuck the default is in GitExtensions)
