### ISSUE TITLE
Reimplement proxy support

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1465]
pyfa has migrated over to using the `requests` package for all it's network calls. I haven't had time to research how to implement proxy support, so have disabled the code and removed controls from the GUI. Need to look into how to properly apply proxy information

**Comment by minlexx** [comment]
Requests library should have its own proxy support.
http://docs.python-requests.org/en/master/user/advanced/#proxies

I could look at it, but unfortunately I failed to build wxPython extension for cpython 3.7 branch under my ubuntu 16.04 (it built fine for py3.5, which is default for ubuntu 16.04, but for some reason Pyfa requires python 3.6!) So I don't have a build evironment set up for 2.x... Maybe I should try to compile python3.6 and retry wxPython with 3.6 branch...

**Comment by blitzmann** [comment]
Thanks for the info! Will take a look if you don't get a chance to

>unfortunately I failed to build wxPython extension for cpython 3.7 

Python 3.7? That isn't out yet, so maybe you're trying to build a development copy of the next version?
 AFAIK wxPython supports up to 3.6.

> but for some reason Pyfa requires python 3.6!

Well... honestly, it's only required because that's what I have, I can almost guarantee it'll work with 3.5 as we aren't using any of the new 3.6 features.

You should be able to change the following in `prereqsCheck.py` to get it running with 3.5:

```
    if sys.version_info < (3, 6):
        msg = "pyfa requires python 3.6"
        raise PreCheckException(msg)
```

Additionally, check https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04/ for python wheels for ubuntu 16.04 so that you don't have to build it :)

**Comment by Neugeniko** [comment]
The change to requests seems to work for api skills and prices.  py3 branch.

**Comment by minlexx** [comment]
@blitzmann 
> Python 3.7? That isn't out yet

Yeah, I'm compiling from git https://github.com/python/cpython/branches - 3.7 branch. This is very easy in deb-based Linux distros - literally few commands and you're done
```
sudo apt-get build-dep python3.5
git clone https://github.com/python/cpython.git
cd cpython
git checkout -b 3.7 origin/3.7
mkdir build && cd build
../configure --prefix=/usr/local --enable-shared
make -j8 && sudo make install
```

> Additionally, check https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04/ for python wheels for ubuntu 16.04 so that you don't have to build it :)

Cool! Thanks, it's very helpful. I've built cpython 3.6 with commands above (only changed 3.7 to 3.6) and successfully installed wxPython 4.0.1 from that wheel, additionally needed `apt install libwebkitgtk-3.0-0` to make `import wx.html2` to work... now Pyfa 2.0.0b4 (git) is working ;)

**Comment by blitzmann** [comment]
Glad you got it working! Linux support is indeed much more... involved, unfortunately because wxPython 4 is so new. Just FYI:

>  installed wxPython 4.0.1 

I would recommend 4.0.0b2. There's a few issues beyond beta 2 that I'm currently waiting on responses from Robin Dunn about.

Will take a look at the pull request, thanks!
