### ISSUE TITLE
Importing fits from old pyfa export fails

### ISSUE THREAD

**Issue by NoMercy82** [pyfa-org/Pyfa#1466]
## Bug Report
Pyfa fails to 'Import fittings' from an XML document generated by pyfa 1.35.1 option to 'Backup all fittings'.

### Expected behavior:
Pyfa should import all fittings.

### Actual behavior:
Dialog remains on screen stating '00:00:00' elapsed time and does not import fittings.

### Detailed steps to reproduce:
Open pyfa 2 beta. (I am on version 2.0.0b3). File -> Import Fittings -> Select file.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
XML file generated from previous version of Pyfa

### Release or development git branch? Please note the release version or commit hash:
2.0.0b3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
I'm happy to provide my xml file for you to test against if you wish. I'm unsure whether this is old pyfa not exporting them correctly or new pyfa not importing them correctly.

**Comment by blitzmann** [comment]
Beta 4 should fix this, please test on that version (the update notification doesn't currently work correctly, so you may not be aware it's out).

**Comment by NoMercy82** [comment]
You are correct, the import worked in beta 4, tried and tested now. However pyfa did hang my machine for around 15 seconds once it had completed the import, then crashed without showing an error.
