### ISSUE TITLE
py3: Ubuntu 16.04 crash when switching characters in character editor

### ISSUE THREAD

**Issue by minlexx** [pyfa-org/Pyfa#1468]
### Release or development git branch? Please note the release version or commit hash:
py3 branch at commit b296e0709c408aef5a9b1a50637c8430e66688f6

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Ubuntu 16.04, python 3.6, wxPython 4.0.1 from pre-built wheel (from https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04/ - `wxPython-4.0.1-cp36-cp36m-linux_x86_64.whl` )

Crash happens when populating skills tree control.

The message: 
```
(pyfa.py:24172): Gtk-WARNING **: A node was inserted with a parent that's not in the tree.
This possibly means that a GtkTreeModel inserted a child node
before the parent was inserted.
```

Is displayed in run console, and a crash happens shortly afterwards:
```
Gtk:ERROR:/build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkrbtree.c:465:_gtk_rbtree_insert_after: assertion failed: (_gtk_rbtree_is_nil (tree->root))
```

Either a bug in wxPython, or in Pyfa code - I don't know, guilty python lines of code are:
https://github.com/pyfa-org/Pyfa/blob/py3/gui/characterEditor.py#L549-L551

Initially, skills list for `All V` character is populated and displayed OK. Then when you try to create a new character, or switch to existing custom character, crash happens.
At the first iteration of loop, the line `ree.AppendItem(childId, "dummy")` is executed, and the Gtk-warning is printed. At the second iteration, previous line is executed `childId = tree.AppendItem(root, name, imageId, data=('group', id))` and causes a crash in wxGtk libs.

Full crash log with backtrace from gdb: https://paste.pound-python.org/show/MtCobJCDB1t3iGg3QGve/

**Comment by blitzmann** [comment]
Trey wxPython 4.0.0b2. This might be a manifestation of #1421

**Comment by minlexx** [comment]
@blitzmann yes, looks like it is. The same crash happens in windows, too...
I have a some traceback (may give some hints for developers in https://github.com/wxWidgets/Phoenix/issues/767 , if needed)

**Comment by blitzmann** [comment]
@minlexx looks like it's been fixed on the wxWidgets side, hopefully we'll get an idea on when it'll be available for wxpython
