### ISSUE TITLE
Error on exit on Windows 10 64 bit

### ISSUE THREAD

**Issue by thermanjh** [pyfa-org/Pyfa#1470]
<!--
OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.35.2 Stable - YC120.2 1.2
pyfa root: F:\CCP\pyfa
save path: C:\Users\therman\.pyfa
fs encoding: mbcs

EXCEPTION: [Errno 13] Permission denied: u'C:\\Users\\therman\\.pyfa\\settings\\pyfaEOSSettings'

  File "F:\CCP\pyfa\library.zip\gui\mainFrame.py", line 352, in OnClose
    SettingsProvider.getInstance().saveAll()
  File "F:\CCP\pyfa\library.zip\service\settings.py", line 107, in saveAll
    settings.save()
  File "F:\CCP\pyfa\library.zip\service\settings.py", line 126, in save
    with open(self.location, "wb") as f:

**Comment by blitzmann** [comment]
> Error on exit on Windows 10 64 bit

> No description provided.

I'm not sure what to do with this information 😛 

Is there an error message that you're getting? What version? Anything in the log files in `~/.pyfa`?

**Comment by blitzmann** [comment]
@thermanjh Can you provide any more information on this issue? If not, I'll be forced to close it as there's not much I can do - I'm not getting an error on exit, nor has anyone else reported it. Thanks :)

**Comment by blitzmann** [comment]
Closing this due to lack of information. Please open a new ticket with more information if you can, thanks! :)
