### ISSUE TITLE
Standup Missile Guidance Enhancers have a active state.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1474]
### Expected behavior:
Standup Missile Guidance Enhancers are passive modules.

### Actual behavior:
Standup Missile Guidance Enhancers have a active state.

### Detailed steps to reproduce:
Make a new Tatara fit.
Add a Standup Missile Guidance Enhancer to it.
Note the module can be made active.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Tatara, Tatara fit]

Standup Missile Guidance Enhancer I
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

[Empty Service slot]
[Empty Service slot]
[Empty Service slot]
[Empty Service slot]
[Empty Service slot]

### Release or development git branch? Please note the release version or commit hash:
py3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win 10

**Comment by blitzmann** [comment]
Should be a pretty simple fix. This items effect is declared as a `type = "active"` - probably a copy and paste issue on my part when I rushed to get citadels fixed in 1.35. There's probably a few more passive standup modules that are listed as active modules as well.

I won't be able to make a fix to this until tonight - if you get to it before I do, feel free to submit a PR. :)

**Comment by Neugeniko** [comment]
Ill check for other modules then.

**Comment by Neugeniko** [comment]
A quick run thru standup modules found that Standup Warp Disruption Burst projector has no effect implemented?

**Comment by blitzmann** [comment]
> A quick run thru standup modules found that Standup Warp Disruption Burst projector has no effect implemented?

Very possible. then again, its one of those modules that doesn't really have a good effect inside of pyfa. I believe that module is an AoE disruption bubble that is active for like 30 seconds. It basically says the ship can't warp for a period of time, which is not really a state we keep track of in pyf, or need to (other than the `warpScrambleStatus` of the target fit)

**Comment by Neugeniko** [comment]
How do I find how a effect is implemented? For example the structure ballistic control system has a effect structureBallisticControlSystem but I cant find that text anywhere in the codebase.

**Comment by blitzmann** [comment]
Brace yourself, legacy code awaits: `eos/effects` is a repository for all the effects in pyfa, which are described as python files. So `structureballisticcontrolsystem.py` would be a file that describes how that effect is implemented.

Fun fact: starting pyfa in debug mode (`python pyfa.py -d`, or just adding `-d` to the list of script options in PyCharm) allows you to open the items window, browse to effects, and right click on the effect. This will open the effect file with whatever program you have associated with `.py` files (for me it's PyCharm) allowing you easy access to see effect implementation.

**Comment by Neugeniko** [comment]
So structuremissileguidanceenhancer.py seems to be off in that it is checking for skill requirements for the structure missile charge and like you said it is marked as active. I'll check on the server which charges groups it applies to, might not work on guided bombs

BEFORE
```
# Not used by any item
type = "active"


def handler(fit, container, context):
    for srcAttr, tgtAttr in (
            ("aoeCloudSizeBonus", "aoeCloudSize"),
            ("aoeVelocityBonus", "aoeVelocity"),
            ("missileVelocityBonus", "maxVelocity"),
            ("explosionDelayBonus", "explosionDelay"),
    ):
        fit.modules.filteredChargeBoost(lambda mod: mod.charge.requiresSkill("Missile Launcher Operation"),
                                        tgtAttr, container.getModifiedItemAttr(srcAttr),
                                        stackingPenalties=True)
```

**Comment by Neugeniko** [comment]
It only applies to two missile groups just like structure bcs. I'll put in a PR.

AFTER

```
# Not used by any item
type = "passive"


def handler(fit, container, context):
    missileGroups = ("Structure Anti-Capital Missile", "Structure Anti-Subcapital Missile")
    for srcAttr, tgtAttr in (
            ("aoeCloudSizeBonus", "aoeCloudSize"),
            ("aoeVelocityBonus", "aoeVelocity"),
            ("missileVelocityBonus", "maxVelocity"),
            ("explosionDelayBonus", "explosionDelay"),
    ):
        fit.modules.filteredChargeBoost(lambda mod: mod.charge.group.name in missileGroups,
                                        tgtAttr, container.getModifiedItemAttr(srcAttr),
                                        stackingPenalties=True)
```

**Comment by Neugeniko** [comment]
I'll make a seperate issue for the aoe bubble projector effect.

**Comment by blitzmann** [comment]
> didn't know how to make a new one.

Think we discussed this last night, but wanted to just reiterate here: Best to make separate branches for separate issues, then PR those branches into pyfa's 2.x branch :)

Thanks for the contribution, it's been merged :)

**Comment by Neugeniko** [comment]
Also present in master.

**Comment by blitzmann** [comment]
Thanks, I'll try to identify the commits to cherry pick into master to get them fixed over there
