### ISSUE TITLE
Standup Warp Disruption Burst Projector has no active state.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1475]
### Expected behavior:
You can activate this module to see its effect on capacitor.

### Actual behavior:
You cannot activate this module.

### Detailed steps to reproduce:
Import the following fit and note you cannot activate the module.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Keepstar, Keepstar fit]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

Standup Warp Disruption Burst Projector
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

[Empty Service slot]
[Empty Service slot]
[Empty Service slot]
[Empty Service slot]
[Empty Service slot]
[Empty Service slot]
[Empty Service slot]

### Release or development git branch? Please note the release version or commit hash:
py3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
win 10

**Comment by Neugeniko** [comment]
Could we have its effects file look something like this so that it both active (you can see its effect on cap) and the 1 point of warp jamming from bubbles.

```
# doomsdayAOEBubble
#
# Used by:
# Module: Standup Warp Disruption Burst Projector
type = "projected", "active"


def handler(fit, module, context):
    if "projected" in context:
        fit.ship.increaseItemAttr("warpScrambleStatus", 1)
```

**Comment by Neugeniko** [comment]
People are telling me bubbles have infinite warp jam points. SO above wont be a accurate representation of bubble effects.

**Comment by blitzmann** [comment]
> People are telling me bubbles have infinite warp jam points. So above wont be a accurate representation of bubble effects.

It is what it is. There's no real way to simulate bubbles in pyfa. Thanks for the PR!

**Comment by blitzmann** [comment]
Got it in master, thanks for the heads up!
