### ISSUE TITLE
Attribute Renamed? disallowRepeatingAction is now disallowRepeatingActivation?

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1480]
I was looking into the average capacitor usage of various modules and noticed the code for the average cycle time for MJD, Bomb Launcher etc was never getting executed. This code relied on the function, disallowRepeatingAction in module.py.

### Expected behavior:
def disallowRepeatingAction(self): function returns appropriate value for mjd, bomb launchers and other non repeating modules.

### Actual behavior:
def disallowRepeatingAction(self): function always returns false.

### Detailed steps to reproduce:
Launch pyfa in debug mode.
Add a MJD to a fit.
Show stats on the module and note the property Disallowrepeatingaction is 0.

### Release or development git branch? Please note the release version or commit hash:
py3 or 1.35.2

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
win 10

### Other relevant information:
I cant find the attribute disallowRepeatingAction in the current datadump just disallowRepeatingActivation.

So in module.py.
BEFORE
```
    def disallowRepeatingAction(self):
        return self.getModifiedItemAttr("disallowRepeatingAction", 0)
```
AFTER
```
    def disallowRepeatingAction(self):
        return self.getModifiedItemAttr("disallowRepeatingActivation", 0)
```

works.

**Comment by Neugeniko** [comment]
I'll put in a PR.

**Comment by blitzmann** [comment]
Thanks for the fix @Neugeniko!
