### ISSUE TITLE
Numerous modules have no active state but should show cap use.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1484]
### Expected behavior:
Modules like the reaper, lance, gtfo, bosonic, mjfg etc use cap.

### Actual behavior:
Modules dont use cap since they can't be activated.

### Release or development git branch? Please note the release version or commit hash:
1.35.2 or py3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
win 10

**Comment by blitzmann** [comment]
Those are all doomsdays, right? I don't believe there's any effects associated with any of them.

**Comment by Neugeniko** [comment]
Micro jump field generator is a command destroyer only module and the rest are doomsdays. They do have effects, just no effects file I believe.

**Comment by Ebag333** [comment]
All you have to do is what CCP does and use the Active effect.

I have this in place in my fork. It's really easy.

**Comment by Neugeniko** [comment]
Got a link to the commit? Thou I'm not sure if a want to add such a broad change.

**Comment by blitzmann** [comment]
> All you have to do is what CCP does and use the Active effect.

You mean `online`? I don't believe this is true for all effects. I think I looked into that a while ago, might be different now. 

>Micro jump field generator is a command destroyer only module and the rest are doomsdays. They do have effects, just no effects file I believe.

Aye, this is what I meant. A modules... activeness... is determined by having at least one effect that is of type `active`

**Comment by Neugeniko** [comment]
Can you have a effects file with just the type set and no handler?

**Comment by blitzmann** [comment]
> Can you have a effects file with just the type set and no handler?

Erm... I don't believe so. You could double check to make sure. But then handler could be something simple like

```
def handler(fit, module, context):
    pass
```

**Comment by blitzmann** [comment]
> Erm... I don't believe so.

I take that back, just tested on a web. it still activates it, just doesn't do anything. See:

```
# remoteWebifierFalloff
#
# Used by:
# Modules from group: Stasis Grappler (7 of 7)
# Modules from group: Stasis Web (18 of 18)
type = "active", "projected"
```

**Comment by Neugeniko** [comment]
I have used -

```
def handler(fit, module, context):
    return
```

previously for the standup warp disruption burst projector but if that works then ill use it.

**Comment by Ebag333** [comment]
Yeah, online. Same diff since Pyfa uses a different term for it.

Keying off an "active" effect doesn't really fix the problem, it's a hacky work around, it won't scale for future additions, and it's not the way CCP does it. 

I did some DB diffs and Online effect matches exactly, it's what CCP uses to allow for modules to be activated. You can see this off modules that they have changed and removed it so people can't turn a module on.

I can try and dig up the CR it's probably a discrete PR. I fixed this like a year ago, so it's not exactly fresh.

**Comment by Neugeniko** [comment]
The micro jump field generator and gravitational transportation field oscillator is fine with just `type = "active", "projected"` but the reaper, lance and bosonic show a non useful dps, in game simulator shows them as zero (because they are aoe and variable). Gotta work out how to zero dps for those.

**Comment by Neugeniko** [comment]
Whats the best way to zero the dps of a item?  I can do this but its a hack.
```

def handler(fit, module, context):
    fit.modules.filteredItemMultiply(lambda mod: mod.item.requiresSkill("Doomsday Operation"), "emDamage", 0)
    fit.modules.filteredItemMultiply(lambda mod: mod.item.requiresSkill("Doomsday Operation"), "explosiveDamage", 0)
    fit.modules.filteredItemMultiply(lambda mod: mod.item.requiresSkill("Doomsday Operation"), "thermalDamage", 0)
    fit.modules.filteredItemMultiply(lambda mod: mod.item.requiresSkill("Doomsday Operation"), "kineticDamage", 0)
```

**Comment by blitzmann** [comment]
> I can try and dig up the CR it's probably a discrete PR. 

Probably no need, if it is as you say, it should basically be an `if "online" in mod.effects` when checking if active or not. I will want to look at scripting out a few checks to check for potential pitfalls, but yeah, if the "online" effect is the method to determine activation, we can use that as a basic catch all. :)

> The micro jump field generator and gravitational transportation field oscillator is fine with just type = "active", "projected" but the reaper, lance and bosonic show a non useful dps, in game simulator shows them as zero (because they are aoe and variable). Gotta work out how to zero dps for those.

hrm, yeah, not sure how to handle that one at the moment. The DPS calculations are automatic (not done through effects) and based on some standardized attributes that those modules must have.

It might be okay to keep the iffy DPS for now, or maybe skip DPS calcs if it's currently trying to calc for a Doomsday group or something - we can research how to best tweak the DPS calcs tailored for doomsday weapons (I'm not well-versed in the mechanics of these modules, so not really sure how one would calculate a good DPS for it.)

**Comment by blitzmann** [comment]
> Whats the best way to zero the dps of a item? I can do this but its a hack.

I would rather not do it this way, because if the user ever wants to see what kind of damage the thing outputs, this would zero it from the item stats, even if we don't want to show it on the DPS panel.

**Comment by Neugeniko** [comment]
For the Structure Arcing Vorton Projector the current dps we have is for the first target, that doomsday jumps and does 15% less per target upto 5 targets.  For the other aoe doomsdays here we have the dps for 1 target in the aoe.

**Comment by Neugeniko** [comment]
Sticking with the damage to one target I think is fine. Because most of the time people ask how much dps will 'I' (one) take on average. Its the DOT beam of the aoe doomsdays that is a problem, how much time do we spend in it? For the bosonic its longer than reaper or lance probably, no clear answer. We could just leave the dps calc for em as is and notify the user that its a dot weapon (multiple damage ticks within 1 cycle).

**Comment by Ebag333** [comment]
The special ones are trickier, but the standard DDs are easy

**Comment by Neugeniko** [comment]
Standard dds already work.  It shows a alpha and its dps.

**Comment by Ebag333** [comment]
https://github.com/Pyfa-fit/Pyfa-fit/pull/129/commits/724862827506e0d7962273484c52bbf0ae8e6365

There's the fix for making Online modules actually active.  Once you do that you can remove all the other various workarounds.

There's also fixes in there to make the various Titan DDs work properly.

**Comment by Neugeniko** [comment]
For bomb launchers we accept that the dps is from 1 target in the area of effect all the time. So the same for aoe dot dds is no different. Thanks for the dd code, blitzmann can you use?

The online effect is for everything that can be onlined, not active. It even includes shield extenders. No good.

```
mysql> select t.typename from dgmtypeeffects a, invtypes t where a.effectid=16 and a.typeid=t.typeid and t.typename like "%extender%";
+-----------------------------------------------+
| typename                                      |
+-----------------------------------------------+
| Small Shield Extender I                       |
| Small Shield Extender II                      |
| Medium Shield Extender I                      |
| Medium Shield Extender II                     |
| Large Shield Extender I                       |
| Large Shield Extender II                      |
| Micro Shield Extender I                       |
| Micro Shield Extender II                      |
| Large Azeotropic Restrained Shield Extender   |
| Small Azeotropic Restrained Shield Extender   |
| Medium Azeotropic Restrained Shield Extender  |
| Medium F-S9 Regolith Compact Shield Extender  |
| Small F-S9 Regolith Compact Shield Extender   |
| Large F-S9 Regolith Compact Shield Extender   |
| Luther Veron's Modified Shield Extender       |
| CONCORD Micro Shield Extender                 |
| CONCORD Medium Shield Extender                |
| CONCORD Large Shield Extender                 |
| Thukker Modified Medium Shield Extender       |
| QA Shield Extender                            |
| Small 'Wolf' Shield Extender                  |
| Small 'Trapper' Shield Extender               |
| Medium 'Canyon' Shield Extender               |
| Large 'Sheriff' Shield Extender               |
| Thukker Small Shield Extender                 |
| Thukker Large Shield Extender                 |
| Thukker Medium Shield Extender                |
| Caldari Navy Small Shield Extender            |
| Republic Fleet Small Shield Extender          |
| Caldari Navy Medium Shield Extender           |
| Republic Fleet Medium Shield Extender         |
| Caldari Navy Large Shield Extender            |
| Republic Fleet Large Shield Extender          |
| Capital Shield Extender I                     |
| Capital Azeotropic Restrained Shield Extender |
| Capital F-S9 Regolith Compact Shield Extender |
| Capital Shield Extender II                    |
| CONCORD Capital Shield Extender               |
| True Sansha Capital Shield Extender           |
| Dread Guristas Capital Shield Extender        |
| Domination Capital Shield Extender            |
| Standup QA Shield Extender                    |
+-----------------------------------------------+
42 rows in set (0.02 sec)

```

**Comment by Neugeniko** [comment]
I'm going to put in a PR to address the OP issues. And open a issue for the dd dps fix.

**Comment by Neugeniko** [comment]
I keep finding more modules that use cap but dont have a online state :( . I will do a sql query to give me all groups that use cap and check them off. Then put in another issue when I have the complete list.

**Comment by Neugeniko** [comment]
The following groups are the remaining groups of items that use cap but have no active state.

Jump Portal Generators.
Cargo Scanners
Ship Scanners
Survey Scanners
Passive Targeters

Should we look into any of them?

**Comment by blitzmann** [comment]
Thanks @Neugeniko! I'll look into making a script that can be run to find other modules that have cap usage but don't have an effect file - could be run during updates as a quick check to ensure things like this don't get missed in the future. :)

As noted, the `online` fix suggested is unfortunately not a proper fix. I knew I had looked into it previously because it really does seem like it would work (although, the method Ebag came up with was much simplier, just creating an `online` effect file - I was thinking of something more complicated with checking the list of effects for "online" and blah blah blah). pyfa will continue to use the standard method of determination a per effect basis which modules can be in an `active` state. Thanks all!
