### ISSUE TITLE
Clicking on drones too fast causes pyfa to crash

### ISSUE THREAD

**Issue by mcelrath** [pyfa-org/Pyfa#1499]
Clicking (too fast) on drones to remove them causes the following crash.

OS version: 	Linux-4.13.0-37-generic-x86_64-with-Ubuntu-17.10-artful
Python: 	2.7.14
wxPython: 	3.0.2.0
SQLAlchemy: 	1.1.9
Logbook: 	1.1.0
pyfa version: 1.35.2 Stable - YC120.2 1.2
pyfa root: /home/mcelrath/EVE/pyfa
save path: /home/mcelrath/.pyfa
fs encoding: UTF-8

EXCEPTION: <eos.saveddata.drone.Drone object at 0x7f3714e53b50> is not in list

  File "/home/mcelrath/EVE/pyfa/gui/builtinAdditionPanes/droneView.py", line 225, in removeItem
    self.removeDrone(drone)
  File "/home/mcelrath/EVE/pyfa/gui/builtinAdditionPanes/droneView.py", line 230, in removeDrone
    sFit.removeDrone(fitID, self.original.index(drone))

**Comment by Neugeniko** [comment]
I've tried reproducing on win 10 from code and exe with no luck.

**Comment by blitzmann** [comment]
I can try on my Ubuntu VM, but it'll be a while before I get to this. @mcelrath are you able to consistently reproduce the issue?

**Comment by blitzmann** [comment]
@mcelrath Can you still reproduce with the new 2.x builds?

**Comment by blitzmann** [comment]
Going to close this issue as it may very well be fixed with the upgrades 2.x has, @mcelrath please test in latest releases, and post a new bug report if you experience any issues! Thanks!
