### ISSUE TITLE
Error when adding/removing EVE SSO character.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1501]
### Expected behavior:
No error when signing on via EVE SSO>Add Character Menu Item

### Actual behavior:
The following error occurs when signing on.

OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.0.5
Logbook version: 1.2.1
Requests version: 2.11.1
Dateutil version: 2.6.1

####################

Traceback (most recent call last):
  File "C:\Program Files (x86)\Newark\prog\Pyfa\gui\characterEditor.py", line 799, in ssoListChanged
    self.noCharactersTip.Hide()
RuntimeError: wrapped C/C++ object of type StaticText has been deleted

### Detailed steps to reproduce:
Click Add character via the EVE SSO menu.
Login in web page.
Error pops up after callback address is reached.

### Release or development git branch? Please note the release version or commit hash:
esi

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
win 10

**Comment by Neugeniko** [comment]
The following happens when revoking character access too.

Traceback (most recent call last):
  File "C:\Program Files (x86)\Newark\prog\Pyfa\gui\characterEditor.py", line 795, in ssoListChanged
    self.charChoice.Hide()
RuntimeError: wrapped C/C++ object of type Choice has been deleted

**Comment by blitzmann** [comment]
yeah, this was one of the errors I was running into. it's when you add or revoke a character, a window that was closed is still accepting the event. Haven't pinpointed it yet. :/

**Comment by Neugeniko** [comment]
Do you have skills coming in yet?

**Comment by blitzmann** [comment]
They should be :) You have to do it via the refresh button on the main window - I don't yet have a button in the character editor to kick it off
