### ISSUE TITLE
Export fit to eve does not have success/fail message.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1502]
### Expected behavior:
Success/fail message when exporting fit to eve.

### Actual behavior:
No feedback.

### Detailed steps to reproduce:
Login a EVE SSO character
'Export to EVE' the below fit
Note there is no success/fail message in the export to eve window.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Bellicose, ttt]

Damage Control II
Ballistic Control System II
Ballistic Control System II
Ballistic Control System II

50MN Microwarpdrive II
Large Shield Extender II
Adaptive Invulnerability Field II
Sensor Booster II
Target Painter II

Heavy Assault Missile Launcher II, Mjolnir Javelin Heavy Assault Missile
Heavy Assault Missile Launcher II, Mjolnir Javelin Heavy Assault Missile
Heavy Assault Missile Launcher II, Mjolnir Javelin Heavy Assault Missile
Heavy Assault Missile Launcher II, Mjolnir Javelin Heavy Assault Missile

Medium Anti-EM Screen Reinforcer I
Medium Hydraulic Bay Thrusters I
Medium Hydraulic Bay Thrusters I

Infiltrator II x3
Acolyte II x2

Caldari Navy Mjolnir Heavy Assault Missile x264
Scan Resolution Script x1

### Release or development git branch? Please note the release version or commit hash:
esi

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
win 10

**Comment by blitzmann** [comment]
Got the status messages showing up again. 👍
