### ISSUE TITLE
Boosts are broken in Pyfa

### ISSUE THREAD

**Issue by carbotaniuman** [pyfa-org/Pyfa#1508]
Bug: Boosts from other ships do not apply.

Reproduce: Take any ship that has a Command Burst.

Apply it to any other ship and Boosts do not update.

Running Pyfa version v2.0.0b5

**Comment by alexanderdarino** [comment]
Same issue with 1.36. I tried it with mining bursts from a Porpoise - not affecting anything.

**Comment by Neugeniko** [comment]
Just to make sure the fleet boost tab is the one with the vertical <<< fleet insignia.

**Comment by alexanderdarino** [comment]
@Neugeniko none of these steps helped address the issue. The Porpoise is clearly being projected on the barges with active and script-fitted command modules and none of the effects are being properly taken into consideration.

**Comment by blitzmann** [comment]
Sorry about being MIA for a bit! A little more information would be helpful (for example, fits involved). I can assign a simple Claymore with Skirmish Burst loaded with Interdiction charge to a tackle frigate and it works fine (scram increases in range)

Also, make sure the command fits are in the proper area. command ships shouldn't go in "Projected" panel, but instead the "Command" panel, as @Neugeniko suggested. Just want to make sure that's clear :)

**Comment by blitzmann** [comment]
No worries. Just got really busy at work ;)

> Any chance these two could be consolidated into one tab?

It's been discussed, specifically when command bursts were first being introduced, however there are complications involved. I'm sure there's an issue page that details the reasons, but long story short is that although similar (for the user), the application of command effects have nearly zero overlap with projected effects.

**Comment by blitzmann** [comment]
Going to close this as there's lack of activity and op hasn't replied back. @carbotaniuman if you're still having issues, please reopen another ticket, but I thbink it's simply that you have the two tabs mixed up
