### ISSUE TITLE
Can't view Drones on Augoror Fit

### ISSUE THREAD

**Issue by alexanderdarino** [pyfa-org/Pyfa#1511]
Each and every time I open one of my Augoror fits (which has no drone mods or rigs but does have some drones in it), I get this message:

OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.36.0 Stable - YC120.3 1.8
pyfa root: C:\Program Files (x86)\pyfa
save path: C:\Users\alexa\.pyfa
fs encoding: mbcs

EXCEPTION: 'Drone' object has no attribute 'rawCycleTime'

  File "C:\Program Files (x86)\pyfa\library.zip\gui\statsPane.py", line 75, in fitChanged
    view.refreshPanel(fit)
  File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinStatsViews\rechargeViewFull.py", line 109, in refreshPanel
    tank = fit.effectiveSustainableTank if self.effective else fit.sustainableTank
  File "C:\Program Files (x86)\pyfa\library.zip\eos\saveddata\fit.py", line 1432, in effectiveSustainableTank
    eshps = self.damagePattern.calculateEffectiveTank(self, self.sustainableTank)
  File "C:\Program Files (x86)\pyfa\library.zip\eos\saveddata\fit.py", line 1081, in sustainableTank
    self.calculateSustainableTank()
  File "C:\Program Files (x86)\pyfa\library.zip\eos\saveddata\fit.py", line 1146, in calculateSustainableTank
    cycleTime = mod.rawCycleTime

I am henceforth unable to add/view/delete the drones associated with this fit. I'm pretty sure the drones I have on this fit are medium armor repair drones, but since I cannot view them I cannot confirm.

**Comment by alexanderdarino** [comment]
I don't know why it says I have Windows 8 when I actually have the latest stable (non-early, non-preview, etc) release of Windows 10. I guess hat's a separate bug for you!

**Comment by Neugeniko** [comment]
I've put in Pull Request 1515 to fix this issue.

**Comment by alexanderdarino** [comment]
I assume this will address other affected ships? Having the same issue with the Inquisitor

**Comment by blitzmann** [comment]
Thanks for the report, and the quick bug fix @Neugeniko ! Sorry I've been a bit slow getting to these lately, will review the PR and merge if appropriate.

>I don't know why it says I have Windows 8 when I actually have the latest stable (non-early, non-preview, etc) release of Windows 10. I guess hat's a separate bug for you!

I think internally windows 10 is considered windows 8? I dunno lol

**Comment by blitzmann** [comment]
FWIW, I can't reproduce. @Neugeniko , do you have a fit that displays this issue? I set up an Aug with a single med armor repair bot, turned it on, and self projected it. No error.

**Comment by alexanderdarino** [comment]
For me, simply opening an Inquisitor or Augoror fit which contains an armor rep drone produces the error message and leaves me unable to open the Drones tab. If I create a new Augoror with the drones, close the tab, reopen I also get the error.

> I think internally windows 10 is considered windows 8? I dunno lol

Please say it isn't so! (╯°□°）╯︵ ┻━┻

**Comment by Neugeniko** [comment]
@blitzmann I am unable to reproduce at this time.. hang on i just tried something. Turn on 'factor in reloads' and  try self projecting the following fit.

[Augoror, Issue 1511]

800mm Crystalline Carbonide Restrained Plates
Energized Adaptive Nano Membrane II
Damage Control II
Energized Adaptive Nano Membrane II
Capacitor Power Relay II

Cap Recharger II
10MN Afterburner II
Cap Recharger II

Medium Remote Armor Repairer II
Medium Remote Armor Repairer II
Drone Link Augmentor II
Medium Remote Armor Repairer II
Medium Remote Armor Repairer II

Medium Capacitor Control Circuit I
Medium Capacitor Control Circuit I
Medium Capacitor Control Circuit I


Medium Armor Maintenance Bot I x1

**Comment by blitzmann** [comment]
Finally got around to confirming this, @Neugeniko's fix seems to be good, thanks for the clarifications on how to reproduce!
