### ISSUE TITLE
Bug. MacOS. Remove module

### ISSUE THREAD

**Issue by bershadskiy** [pyfa-org/Pyfa#1516]
## Bug Report
tried to change previous saved fit. have error msg when removed modules.

### Expected behavior:
module(s) must be removed

### Actual behavior:
no action except error msg

### Detailed steps to reproduce:
open fit, saved in previous beta release of Pyfa
try to remove any high slot module
catch error msg and report it to developers

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Raven, ангел]

Ballistic Control System II
Ballistic Control System II
Ballistic Control System II
Capacitor Flux Coil II
Capacitor Flux Coil II

Adaptive Invulnerability Field II
Adaptive Invulnerability Field II
X-Large Shield Booster II
Shield Boost Amplifier II
Large Cap Battery II
Missile Guidance Computer II, Missile Precision Script
Missile Guidance Computer II, Missile Precision Script

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

Large Capacitor Control Circuit II
Large Capacitor Control Circuit II
Large Capacitor Control Circuit I

### Release or development git branch? Please note the release version or commit hash:OS version: Darwin-17.4.0-x86_64-i386-64bit
Python version: 3.6.3 (default, Oct 22 2017, 22:24:50) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.1

####################

Traceback (most recent call last):
  File "/Users/ryan/pyfa/gui/contextMenu.py", line 138, in handler
  File "/Users/ryan/pyfa/gui/builtinContextMenus/itemRemove.py", line 40, in activate
ValueError: Module(ID=19739, name=Cruise Missile Launcher II) at 0x11ae6e128 is not in list

####################

Traceback (most recent call last):
  File "/Users/ryan/pyfa/gui/builtinViews/fittingView.py", line 281, in kbEvent
  File "/Users/ryan/pyfa/gui/builtinViews/fittingView.py", line 390, in removeModule
  File "/Users/ryan/pyfa/gui/builtinViews/fittingView.py", line 390, in <listcomp>
  File "/Users/ryan/pyfa/eos/saveddata/module.py", line 204, in modPosition
ValueError: Module(ID=19739, name=Cruise Missile Launcher II) at 0x11adc0ac8 is not in list

####################

Traceback (most recent call last):
  File "/Users/ryan/pyfa/gui/contextMenu.py", line 138, in handler
  File "/Users/ryan/pyfa/gui/builtinContextMenus/itemRemove.py", line 40, in activate
ValueError: Module(ID=19739, name=Cruise Missile Launcher II) at 0x11ae6e128 is not in list

**Comment by blitzmann** [comment]
Thanks fore the report! It might be a little bit before I can test, but can you tell me if you can consistently reproduce this issue?

**Comment by bershadskiy** [comment]
i'm not sure what's going on. in v2.0.0b5 i don't see error msg anymore. but removing CML still working strangely. after module deletion icon stays. but not always. few other fits working good. fits, created in current version works. so maybe issue can be moved to backstack as hardly reproducible or even not relevant.

**Comment by blitzmann** [comment]
@bershadskiy can you try v2.0.2? There was a bug that was fixed that prevented the GUI from updating (so module removals / stats / pretty much everything having to do with changing fits).

**Comment by blitzmann** [comment]
Going to close this as I'm fairly certain it's fixed with 2.0.2+. if you're still having issues, please let me know by opening another issue! Thanks!
