### ISSUE TITLE
Wrong math in CPU, Capacitor and EHP

### ISSUE THREAD

**Issue by Ernedar** [pyfa-org/Pyfa#1517]
## Bug Report
Hello, I tried my ingame build for my Gila and it seems to be broken. I do not have all 5 skills but with my current skills this have different outcome.

### Expected behavior:
Capacitor stable at like 8%, CPU will sit in 474 / 475 and EHP is sitting in 36,6k 

### Actual behavior:
capacitor +29Gj income and 65Gj outcome, lasts 1m26s, CPU 519/475, 24.9k EHP

### Fits involved in EFT format (Edit > To Clipboard > EFT):

[Gila, Stable Gila]

Damage Control II
Drone Damage Amplifier II
Drone Damage Amplifier II

Adaptive Invulnerability Field II
Pithum C-Type Medium Shield Booster
Shield Boost Amplifier I
Republic Fleet Large Shield Booster
Republic Fleet Large Cap Battery
10MN Afterburner II

Prototype 'Arbalest' Rapid Light Missile Launcher, Scourge Light Missile
Prototype 'Arbalest' Rapid Light Missile Launcher, Scourge Light Missile
Prototype 'Arbalest' Rapid Light Missile Launcher, Scourge Light Missile
Prototype 'Arbalest' Rapid Light Missile Launcher, Scourge Light Missile
Drone Link Augmentor I

Medium Capacitor Control Circuit I
Medium Anti-Thermal Screen Reinforcer II
Medium Core Defense Field Extender II

Caldari Navy Vespa x2
Caldari Navy Vespa x4

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win 10

**Comment by Neugeniko** [comment]
With All5 skills in game I am seeing over cpu by 36, same in pyfa. In game with All5 skill the capacitor is over cap/sec 28GJ/sec, same in pyfa. In game with All5 Skills cap lasts 1min48sec, same in pyfa.
