### ISSUE TITLE
Wrong capacitor calculation

### ISSUE THREAD

**Issue by psychojf** [pyfa-org/Pyfa#1518]
## Bug Report
wrong calculation in capacitor depleiting time...

### Expected behavior:
my fits is cap stable at 68.9 % in pyfa so i expected it to be the same in-game with same skill, same implants, same gear/fittings

### Actual behavior:
showing cap stable at 48.4 in-game instead of 68.9% we see in pyfa

### Detailed steps to reproduce:
see fits below

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Golem, GOLEM PVE]

Vizan's Modified Capacitor Power Relay
Republic Fleet Ballistic Control System
Republic Fleet Ballistic Control System
Republic Fleet Ballistic Control System

Raysere's Modified Heavy Capacitor Booster, Navy Cap Booster 400
Pith X-Type Shield Boost Amplifier
Pith X-Type Large Shield Booster
Pithum A-Type Adaptive Invulnerability Field
Pithum A-Type Adaptive Invulnerability Field
Republic Fleet Target Painter
Missile Guidance Computer II, Missile Range Script

Torpedo Launcher II, Inferno Rage Torpedo
Torpedo Launcher II, Inferno Rage Torpedo
Torpedo Launcher II, Inferno Rage Torpedo
Torpedo Launcher II, Inferno Rage Torpedo
Bastion Module I
[Empty High slot]
[Empty High slot]
[Empty High slot]

Large Hydraulic Bay Thrusters II
Large Rocket Fuel Cache Partition II

Hobgoblin II x5
Hornet II x5
Warrior II x5

High-grade Crystal Alpha
High-grade Crystal Beta
High-grade Crystal Gamma
High-grade Crystal Delta
High-grade Crystal Epsilon
High-grade Crystal Omega
Sansha Modified 'Gnome' Implant
Inherent Implants 'Squire' Capacitor Management EM-805
Zainou 'Gnome' Shield Operation SP-905
Zainou 'Deadeye' Rapid Launch RL-1005
Agency 'Hardshell' TB7 Dose III
Antipharmakon Thureo

Scourge Rage Torpedo x2500
Scourge Javelin Torpedo x1500
Nanite Repair Paste x500
Navy Cap Booster 400 x80
Missile Range Script x1
Missile Precision Script x1

### Release or development git branch? Please note the release version or commit hash:
exact same problem with pyfa v2.0.0b5 and with pyfa v1.36.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
windows 10

**Comment by Neugeniko** [comment]
The capsim in game and pyfas are not identical. Pyfa staggers similar modules which results in higher cap stability. Also the pyfa takes a average of the cap rather than the lowest point which I think is what the in game sim is using, this also results in a higher cap stability point.

**Comment by psychojf** [comment]
thanks for this reply my friend !
i understand that the capsim in pyfa might not be identical compared to the one in-game and its fine...but there's big difference here...i mean...in this fit if everything is ON with navy cap 200 booster (instead of navy cap booster 400) it said in Pyfa that my cap will deplete in 59min....in-game it said 6 min 52sec...so its a big difference ? with same fit, same implant, same everthing... im not bashing on anyone here and i should say that im super really happy with this awesome tool either if calculation is not perfect....they maybe did somes change in cap calculation in-game...? im using this toool for a while and never noticed that big of a difference that's why i was asking :)  thanks anyway and have a good day

**Comment by GoldenCoins** [comment]
This is because you have a capacitor booster module.

Those modules screw up the math a bit and the in-game fit window does NOT take these into account. 

If pyfa says you are stable then you are actually stable, so long as you don't run out of cap booster ammo

**Comment by psychojf** [comment]
thanks guys ! :)
