### ISSUE TITLE
DPS graph problem

### ISSUE THREAD

**Issue by dyh135** [pyfa-org/Pyfa#1521]
## Bug Report

Graph does not show the dps after changing "Target Velocity (m/s)" with Carriers(fighters loaded)

### Expected behavior:
Show the dps graph after changing the "Target velocity"

### Actual behavior:

Nothing shows in the graph, and bottom line shows "Invalid values in 'Nidnoggur fit'

### Detailed steps to reproduce:

1. Create new Nidhoggur fit
2. fit 3 squad of Einherji, with active ability missile attack, Turret attack
3. open graph
4. change the "Target Velocity (m/s) to any value, e.g. 12
5. dps line disappear, "Invalid values in 'Nidnoggur fit"

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Nidhoggur, Nidhoggur fit]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

Einherji I x9
Einherji I x9
Einherji I x9

### Release or development git branch? Please note the release version or commit hash:

pyfa v2.0.0b5

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10

**Comment by blitzmann** [comment]
Thanks for the bug report! A quick peak displays this exception message:

`gui.graphFrame: math domain error`

Hell if I know what that mean though, but I'll look into it :)

**Comment by blitzmann** [comment]
Got this fixed with the help of @watchmecalculate pointing me in the right direction :D Thanks!
