### ISSUE TITLE
Suggestion Pyfa-2.0.0 to change pyfa User Path to .pyfa2

### ISSUE THREAD

**Issue by Roesjka** [pyfa-org/Pyfa#1523]
## Bug Report
Suggestion

### Expected behavior:
default 

### Fits involved in EFT format (Edit > To Clipboard > EFT):
n/a

### Release or development git branch? Please note the release version or commit hash:
2.0.0.0b5

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Debian stretch and buster

### Other relevant information:
Suggest to change in line 78 .pyfa to .pyfa2 in config.py.
Makes it easier to have stable and beta version separate

**Comment by blitzmann** [comment]
Hey there!

I understand it may be easier for a few folks that run with both versions, however I think it's going to stay the same, at least for now. The beta releases should be saving as a completely different fitting database at the moment while it's in beta, but once it's released as Stable (planning for May 8th), it should be a seamless change for the majority of users, without having to worry about moving files to and from old directory to new directory.

I believe there is a argument that you can run pyfa with that specifies the directory to use as it's user directory. If there isn't, there should be, and I would much rather have something like that. :)
