### ISSUE TITLE
Structure missile combat rigs have no effect

### ISSUE THREAD

**Issue by bronzer** [pyfa-org/Pyfa#1526]
Bug Report:
Adding missile precision and projection rigs has no effect to the missiles on the structure

Expected behavior:
Adding rigs should modify the explosion radius/velocity and flight time of structure missiles.

Actual behavior:
No effect;

Fits involved in EFT format (Edit > To Clipboard > EFT):
[Astrahus, rig test]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Standup Multirole Missile Launcher I, Standup Heavy Missile
[Empty High slot]
[Empty High slot]
[Empty High slot]

Standup M-Set Missile Precision I
Standup M-Set Missile Projection I
[Empty Rig slot]

[Empty Service slot]
[Empty Service slot]
[Empty Service slot]

Release or development git branch? Please note the release version or commit hash:
1.36 and 2.0.0b5

Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win 10

**Comment by blitzmann** [comment]
Thanks for the bug report!

Sorry it took a while, this must have slipped in between the cracks, and then with the 2.0 release everything has been hectic lol.

I'm pretty sure I have them fixed now though. 👍 Will be available in the next release!
