### ISSUE TITLE
Bug/FR: Unable to copy text from info dialogs

### ISSUE THREAD

**Issue by alexanderdarino** [pyfa-org/Pyfa#1529]
You can select text just fine, but Ctrl+C won't copy text on Windows in the latest version of the Pyfa 1.x.

![image](https://user-images.githubusercontent.com/671964/39391491-3176d81a-4a72-11e8-90dd-4bda81b3c8f1.png)

**Comment by blitzmann** [comment]
Hey there @alexanderdarino, this has been long-standing issue, but don' think I've ever made an issue to track it. Thanks! IIRC, the traits stuff is in a HTML view, so I'mm not sure if it would easy or not to implement some sort of selection copy. Will look into this when I can!

**Comment by blitzmann** [comment]
Gonna throw a help wanted on this in case anyone is feeling interested in working on this one before I get around to it.

**Comment by blitzmann** [comment]
Thanks so much to @minlexx for implementing this feature! Will be out with the next release :)
