### ISSUE TITLE
Summer expansion

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1530]
This is a collection of notes on new new stuff coming to EVE for the summer expansion. I want to make absolutely clear that I am not guaranteeing that this stuff will make it into pyfa by the time the expansion hits - there's a significant amount of fundamental tweaks. A lot of these ideas here are just me spitballing and don't represent final form 

## Mutators

Mutated items seem to be a completely new item (different item ID). These items are not populated with the required attributes (see below)... I assume that CCP is tracking which item it came from to use it's base attributes, and then applying or overriding certain attribute values on top of that.

```
[+] 10MN Abyssal Afterburner
  [+|n] medPower
  [+|y] moduleBonusAfterburner
  [+|n] online
  [+|y] overloadSelfSpeedBonus
  [+] capacity: 0
  [+] mass: 1.0
  [+] radius: 1.0
  [+] requiredSkill1: 3450.0
  [+] requiredSkill1Level: 4.0
  [+] volume: 25.0
```

At it's most basic form, I think this would be a relatively easy thing to accomplish. pyfa could have a `mutators` table that is linked to a `module.ID` and references an attribute with it's new value, and ehen the module loads, it loads any mutators that it has with it. Should look into the current attribute override functionality to see if there's anything in there that we can reuse, or if this is going to require something new

Unknowns:
* How the hell is this exported / imported? As far as I can tell, the XML export and copy to clipboard in EVE only contains the (eg) "10MN Abyssal Afterburner". I am unsure if ESI provides more information on what this was based on, will have to get with a CCP dev about this.
* How do we know if an item is able to be mutated? There has to be some sort of mapping table, I just haven't found it yet in the data files or on ESI.
* UI. If we're going to keep the base module around (instead of swapping it out for the "mutated" type), we're going to need a way to distinquish it from the base module. 

## Abysmal space

Looks like these act much the same way as wormhole space. HOWEVER, from a quick playthrough, it seems that you might be able to have multiple environment effects active at a time? There were times I was flying through a cloud, and an effect happened. Currently the wormhole effect only allows 1 of it's type... with Abysmal space might need to allow multiple.

## New weapon system

The only flashy thing about this is the fact that is has a range of dps - every cycle the weapon is active it adds a multiplier. Not exactly sure how to convey this information just yet, maybe simply have a dps "range" displayed, or put the range in the "misc" column, or an entirely new panel that allows you to select number of cycles to calculate for?

**Comment by alexanderdarino** [comment]
Where are you getting this preview information from? At the time of writing, I do not see a new dev blog containing this.

**Comment by blitzmann** [comment]
@alexanderdarino There are forum posts on the test server forum, as well as SISI has the new content currently. :)

**Comment by Neugeniko** [comment]
The show info on a abyssal module on sisi shows the parent module and mutagen used. So yeah everything is remembed.

**Comment by Neugeniko** [comment]
If your considering counting cycles to determine variable dps then consider just counting something more generic like 'fight length' which can be used down the track for cap/tank simulation too.

**Comment by blitzmann** [comment]
> The show info on a abyssal module on sisi shows the parent module and mutagen used. So yeah everything is remembed.

Indeed, however I don't think this is exposed via APIs for us to get at that information for importing / exporting. Need to chat with a ccp dev about that and see if it's in the pipeline. >.<

**Comment by captaincrutches** [comment]
Each module type that can be mutated has around 3-5 stats that get rolled regardless of what meta level you use it on.  In terms of UI, my thought was for each of those module types have a "Abyssal" option such that when you add it to a fit you need to put in the values you rolled for those stats (absolute i.e. what you see in show info on it, not percent).  Since every mutated module is unique, I don't really see a harm in making you do that every time unless there's some way to save rolls in pyfa, at least until you lose the mod...

I don't know how the API's going to work, but worst case the fit can get pulled down with an item id that just says "this is a mutated mod" and we get some prompt to put in the mutated stats in the fit.

Just my .02 isk, spitballing here.

**Comment by shadowclaw** [comment]
For the new weapon system DPS, I like the idea of have it display as a range with a breakdown in a tool tip maybe.  For example "(150 to 300) DPS", where 150 is the DPS after 1 cycle and 300 is the DPS after the 5th cycle (I think I remember them saying it took 5 cycles in one of the fanfest presentations).  The tool tip could than have a breakdown of what the DPS is for each cycle count.  Also don't forget that whatever method is selected would also need to be added to the display for volley as well.

**Comment by blitzmann** [comment]
Small update:

The new weapon system and effects for the new ships was recently implemented, courtesy of @DarkFenX. Should note that the DPS listed for the new weapons is the value after ramp up. There's some information about how long it takes to hit full DPS in the Misc column for the weapon.

I think this will have to do for now, we can take a look at potentially better ways to display a DPS range at a later time, maybe in a point release after the main release.

I haven't worked on anything else due to other pressing bugs, but I hope to start looking into the changes required to support this expansion. 

I am still unsure if mutator support will be coming in pyfa immediately following the expansion - it might be a while before true support is had. I'm having trouble finding this data in the client dump, and there hasn't been any ESI endpoints exposing information about them. Unsure if the data will be included in the SDE.

Environments are things I will still need to figure out - are they applied the same as wormhole environments? How can I differentiate between wormhole and abysmal? How about the localized effects? Lots of things to look into, and my main priority will be to figure this out rather than mutators (as I'm certain we'll be able to handle this with just a few tweaks, rather than a completely new feature)

**Comment by blitzmann** [comment]
Looking at the abysmal environments... christ, another curve ball

```
SELECT t.typeID, t.typeName, a.attributeName 
from invtypes t
JOIN dgmtypeattribs dta ON t.typeID = dta.typeID
JOIN dgmattribs a ON dta.attributeID = a.attributeID
WHERE t.typeID IN (
	47381
	,47382
	,47383
	,47384
	,47385
	,47386
	,47390
	,47391
	,47392
	,47378
	,47379
	,47380
	,47387
	,47388
	,47389
	)
ORDER BY t.typeID
```

At first look, it looks like they are using the gang boost logic for their effects, at least these attributes show a bunch of `warfareBuff` attributes. The gang code in pyfa is a mess, and I think it came with a bunch of... assumptions? I dunno, I'll have to look at the effects themselves and see if they are implemented the same way. I would assume CCP implemented it this way due to the localization effects one may run into - I don't think they stack, instead the one with the greater force is applies (just link gang links, which is one of the reasons why gang links were so wonky to implement)

**Comment by blitzmann** [comment]
Currently working on the weather affects for abysmal space: https://github.com/pyfa-org/Pyfa/tree/abysmal_weather

It's very rough at this stage, the context menu is all screwy, but I just needed something quick to apply to the fit and start testing the effects.

**Comment by blitzmann** [comment]
Closing this in support of the individual issues. :)
