### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by Comeonnnnnn** [pyfa-org/Pyfa#1531]
Dont have any knowledge of coding/programming
i tried to do an SSO login to add an account but it said there was an error
So here is what the error said

OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 799, in ssoListChanged
RuntimeError: wrapped C/C++ object of type StaticText has been deleted

**Comment by blitzmann** [comment]
Hi there!

Thanks for the report. This is already being tracked here: https://github.com/pyfa-org/Pyfa/issues/1501. Also note that even though you get an error, it still does what you wanted it to do (adding a character)

This is one of the things that I'm hoping to tackle before launch on the 8th :)
