### ISSUE TITLE
Error importing character skills

### ISSUE THREAD

**Issue by phuture2k** [pyfa-org/Pyfa#1536]
## Bug Report
I tried to import a character using EVE SSO but couldn't import skills due to an error.

### Expected behavior:
No error, skills imported.

### Actual behavior:
All skills show as "Not Learned". Got this error:

> OS version: Windows-10-10.0.16299-SP0
> Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
> wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
> SQLAlchemy version: 1.1.10
> Logbook version: 1.0.0
> Requests version: 2.18.4
> Dateutil version: 2.6.0
> 
> ####################
> 
> Traceback (most recent call last):
>   File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 795, in ssoListChanged
> RuntimeError: wrapped C/C++ object of type Choice has been deleted
> 
> ####################
> 
> Traceback (most recent call last):
>   File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 799, in ssoListChanged
> RuntimeError: wrapped C/C++ object of type StaticText has been deleted

### Detailed steps to reproduce:
- Go to character editor
- Create new character
- Select EVE SSO.
- Log in with EVE SSO.

### Release or development git branch? Please note the release version or commit hash:
v2.0.0b6

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
It can import/export fits from EVE.

**Comment by blitzmann** [comment]
Hey there!

This is a known GUI bug, see #1501. I'll be taking a look at fixing this before the stable release next week :)
