### ISSUE TITLE
Skills reset on esi error

### ISSUE THREAD

**Issue by Fundaris** [pyfa-org/Pyfa#1537]
## Bug Report
The Characterskills get reset when receiving an error from esi.

### Expected behavior:
Skills shouldn't be reset

### Actual behavior:
Skills get reset

### Detailed steps to reproduce:
1. Refresh charakter skills
2. Get an ESI error

If you want a 100% error rate. Test it when the server is down with an **uncached** character.

### Release or development git branch? Please note the release version or commit hash:
v2.0.0b6

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win 10

**Comment by blitzmann** [comment]
Hrm, interesting... When the server is down, what response code does it send? I could just point it to a testing api that always gives that response code and see what happens...

Also, does the server go down on a regular interval (like how TQ reboots daily) that you know of?

**Comment by Fundaris** [comment]
ESI is a cache api if data is not avaiable it ask the monolith(TQ)
And then send a respone like nginx would do x)

When TQ isn't awnsering:
HTTP 502 with "{\"error\":\"Timeout contacting tranquility\",\"timeout\":10}"

But there are more which can happen like:
HTTP 403 with "{\"error\": \"Get https:\/\/login.eveonline.com\/oauth\/verify: net\/http: request canceled (Client.Timeout exceeded while awaiting headers)\", \"sso_status\": 502}"

HTTP 503 with "<!DOCTYPE HTML PUBLIC \"-\/\/W3C\/\/DTD HTML 4.01\/\/EN\"\"http:\/\/www.w3.org\/TR\/html4\/strict.dtd\">\r\n<HTML><HEAD><TITLE>Service Unavailable<\/TITLE>\r\n<META HTTP-EQUIV=\"Content-Type\" Content=\"text\/html; charset=us-ascii\"><\/HEAD>\r\n<BODY><h2>Service Unavailable<\/h2>\r\n<hr><p>HTTP Error 503. The service is unavailable.<\/p>\r\n<\/BODY><\/HTML>\r\n"

Another 502: "<html>\r\n<head><title>502 Bad Gateway<\/title><\/head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway<\/h1><\/center>\r\n<\/body>\r\n<\/html>\r\n"

There should be more but my log channel is messed up with other logging stuff currently.

Currently I get frequently the First 502 and the 403 one.

U can test it in 8min from now since TQ will reboot there

**Comment by blitzmann** [comment]
> U can test it in 8min from now since TQ will reboot there

Whelp, guess I missed it this time lol! I'll have to wait for this weekend since I can't really debug this during work

> In my eyes u should just check if you got an HTTP 200 and then set skills else it should terminate with an error stating try again (later)

Absolutely, this should be the case. Not sure why it's not the case right now. Thanks for the info, I'll take a look at it :)
