### ISSUE TITLE
Error when deleting fitting without any modules

### ISSUE THREAD

**Issue by j0holo** [pyfa-org/Pyfa#1539]
## Bug Report

Just started using the program. Connected pyfa with EVE SSO. Created a new character and
linked it with SSO. Created new fitting and deleted the fitting asap. No modules added.

### Expected behavior:

It doesn't give an error.

### Actual behavior:

It gives me an error about that an object doesn't have a name attribute. (object is None).

### Detailed steps to reproduce:

- Create a new character
- Connect character with EVE SSO API
- Create a new fitting
- Delete fitting without adding any modules

### Fits involved in EFT format (Edit > To Clipboard > EFT):

I picked the Panther in this case.

### Release or development git branch? Please note the release version or commit hash:

v2.0.0b6

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10

### Other relevant information:

OS version: Windows-10-10.0.17134-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinViews\fittingView.py", line 301, in fitRemoved
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 1206, in refreshFit
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 1210, in recalc
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by blitzmann** [comment]
This is a symptom of a pretty old bug, it happens (sometime?) when you delete a fit while it's open. It has to do with the way and order pyfa deletes fits. It's something that I want to really look into refactoring after we release 2.0 next week :)

Duplicate #1384
