### ISSUE TITLE
Error when deleting a fit

### ISSUE THREAD

**Issue by davedev** [pyfa-org/Pyfa#1542]
### Expected behavior:

Fit is deleted

### Actual behavior:

Fit is deleted and program displays error message (pasted at bottom)

### Detailed steps to reproduce:

Click red delete icon on fit.  Crash message appears.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

I can't paste it because I deleted it.

### Release or development git branch? Please note the release version or commit hash:

pyfa v2.0.0b6

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows-10-10.0.17134

### Other relevant information:

OS version: Windows-10-10.0.17134-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinViews\fittingView.py", line 301, in fitRemoved
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 1206, in refreshFit
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 1210, in recalc
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by blitzmann** [comment]
Duplicate #1384
