### ISSUE TITLE
Crash when deleting fits

### ISSUE THREAD

**Issue by lholden** [pyfa-org/Pyfa#1543]
## Bug Report
OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinViews\fittingView.py", line 301, in fitRemoved
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 1206, in refreshFit
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 1210, in recalc
AttributeError: 'NoneType' object has no attribute 'name'

### Expected behavior:
Not crashing :D

### Actual behavior:
Crashing :(

### Detailed steps to reproduce:
I was going through various fits and editing / deleting. I deleted a fit and crashed. This is the third or so time I've had it happen.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
I dunno, it got deleted ;)

### Release or development git branch? Please note the release version or commit hash:
2.0.0b6

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10. Also happened earlier in Fedora on my laptop.

**Comment by blitzmann** [comment]
Thanks for the report! Duplicate #1384, but I just made a fix for it :)

**Comment by lholden** [comment]
Oop sorry :D. Glad to hear though!
