### ISSUE TITLE
Can't add characters

### ISSUE THREAD

**Issue by Nostro01** [pyfa-org/Pyfa#1554]
I'm getting this error everytime i try to add a character. This happens, when i try to add a character in the SSO Character Manager and in the Character Editor.

> OS version: Windows-10-10.0.17134-SP0
> Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
> wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
> SQLAlchemy version: 1.1.10
> Logbook version: 1.0.0
> Requests version: 2.18.4
> Dateutil version: 2.6.0
> 
> ####################
> 
> Traceback (most recent call last):
>   File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\esiFittings.py", line 329, in addChar
>   File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 210, in login
>   File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 244, in startServer
>   File "C:\Python36\lib\socketserver.py", line 453, in __init__
>   File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\server.py", line 110, in server_bind
>   File "C:\Python36\lib\http\server.py", line 138, in server_bind
>   File "C:\Python36\lib\socket.py", line 673, in getfqdn
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 6: invalid continuation byte

**Comment by blitzmann** [comment]
Duplicate, or at least related, to #1550
