### ISSUE TITLE
Dialogs pop-up off screen. Multi-monitor setup, Windoze

### ISSUE THREAD

**Issue by Wennid** [pyfa-org/Pyfa#1558]
### Expected behavior:

Dialog boxes should ideally be visible and within 'reach' of the mouse cursor.

### Actual behavior:

All dialog boxes pop-up just above the top edge of the screen.

### Detailed steps to reproduce:

Have two monitors. Primary display on the right, secondary on the left. Pull up the character editor. Where is it? Press Alt+spacebar, then M, then press and hold the down arrow key.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

n/a

### Release or development git branch? Please note the release version or commit hash:

Release 2.0, although it happened with earlier versions too (possibly all versions for all I know)

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10

### Other relevant information:

Only happens when the "main display" is on the right. Closing PYFA, setting the left display to be the 'main' and then restarting PYFA eliminates the issue (but gives me a crick in my neck). The alt+spacebar workaround is also fine if you're not opening and closing dialogs much, so this isn't a high priority issue, esp. with all the ESI/SSO crap you've got on your plate atm ;P

**Comment by Wennid** [comment]
Looks like it may only be the character editor (and its children). At least the module stats window doesn't have this problem.

**Comment by blitzmann** [comment]
Yeah, some windows that should be dialog boxes aren't actually dialog boxes (due to old reasons that should be irrelevant now). I need to go back and clean them up. Shouldn't be too terribly difficult, just a bit time consuming. Thanks for the reminder! :)

**Comment by DarkFenX** [comment]
Secondary window management has been reworked a few releases ago (both auxiliary windows like char editor and dialogs like fit deletion confirmation). I could not reproduce this issue.

Reopen if it still reproducible on your PC.
