### ISSUE TITLE
MAC: Character Editor unable to link eve char / general ESI Problem

### ISSUE THREAD

**Issue by hugohase** [pyfa-org/Pyfa#1563]
## Bug Report

first error:

<img width="418" alt="grafik" src="https://user-images.githubusercontent.com/24372315/39867698-7409c974-5456-11e8-82bf-f7b5b0783712.png">

(ESI Module will not load)

-->

S version: Darwin-17.5.0-x86_64-i386-64bit
Python version: 3.6.3 (default, Oct 22 2017, 22:24:50) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.1

####################

Traceback (most recent call last):
  File "/Users/ryan/pyfa/gui/esiFittings.py", line 329, in addChar
  File "/Users/ryan/pyfa/service/esi.py", line 209, in login
AttributeError: 'Esi' object has no attribute 'settings'

### Release or development git branch? Please note the release version or commit hash:

Release 2.0 
### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

mac os 10.13.4

**Comment by Fundaris** [comment]
Look at #1548

**Comment by blitzmann** [comment]
@Fundaris thanks for stepping up and linking all these duplicates! You the man!

@hugohase indeed, please check the log itself to see if you have the same issue (SSL error). I still haven't figured out a way to reproduce this unfortunately, but I will be coming out with a point release tonight hopefully that reworks all the ESI stuff, so maybe it will be solved with that?

**Comment by hugohase** [comment]
hi
 
Hi,
sorry for the late answer. i have updated now to 2.0.1 and at least i can get the sso working. I will do some further testing and will come back if i find a problem.thanks a lot for your work and the support.

 
-----Ursprüngliche Nachricht-----
 Von: "Ryan Holmes" [notifications@github.com]
 Gesendet: Di. 15.05.2018 00:59
 An: "pyfa-org/Pyfa" [Pyfa@noreply.github.com]
 Kopie: "hugohase" [hugohase.hamm@freenet.de],  "Mention" [mention@noreply.github.com]
 Betreff: Re: [pyfa-org/Pyfa] MAC: Character Editor unable to link eve char / general ESI Problem (#1563)

@Fundaris thanks for stepping up and linking all these duplicates! You the man!
@hugohase indeed, please check the log itself to see if you have the same issue (SSL error). I still haven't figured out a way to reproduce this unfortunately, but I will be coming out with a point release tonight hopefully that reworks all the ESI stuff, so maybe it will be solved with that?
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
-----Ursprüngliche Nachricht Ende-----

Sichern Sie sich mit freenet Mail start 50 GB Cloud-Speicher zusätzlich zu Ihrem werbefreien Postfach sowie höchste Sicherheitsstandards.
https://email.freenetde/start/index.html

**Comment by blitzmann** [comment]
Thanks, awesome that it seems to work! If you're having any other issues, simply open a new ticket 👍
