### ISSUE TITLE
pyfa 2 font issues on linux

### ISSUE THREAD

**Issue by Arherion** [pyfa-org/Pyfa#1564]
o/

After updating to 2.0.0 fonts in fitting section and tabs became weird (all system settings are the same for both):

2.0.0
![pyfa 2.0.0](https://i.imgur.com/mPwFU8I.png)

1.36
![pyfa 1.36](https://i.imgur.com/qCtJ9Ni.png)

OS: Arch linux

Expected: fonts should looks like the same as for 1.36

**Comment by alexanderdarino** [comment]
Fonts are different in Windows 2.x as well

**Comment by kaestchen** [comment]
OS: Fedora27

but with wxPython i would expect grafical bugs to be cross-plattform too

**Comment by blitzmann** [comment]
Indeed, this is a thing that happened due to the upgrade to wxPython, their font rendering was tweaked a bit. TBH, I haven't had time to sit down and get anal about the font sizes since it's a relatively small problem. The fonts in pyfa as a whole could probably use some love, they've always been a bitch to deal with due to every platform using them in different ways.

A quick way of changing the size of the is through https://github.com/pyfa-org/Pyfa/blob/master/gui/utils/fonts.py - you can just make the sizes `(6, 7, 8)` and see how that looks and feels. :)

**Comment by blitzmann** [comment]
I've added the `help wanted` label to this in case anyone is interested in picking up a personal project before I get to it lol. pyfa doesn't handle font's very well, and one of the motivations of moving to wxPython 4 was to better support proper font support. Need to also understand that the OS X client renders font sizes differently. There are certain widgets (like our gauges) where the font size doesn't seem to really change, but then some things they do (like the module listing and tabs). Not sure what the difference between these two are, but something to research and possibly apply client-wide

**Comment by BoraVyvorant** [comment]
I'm also seeing changes in font size between pyfa v1 and pyfa v2 under macOS 10.13.4, but in my case it's going the other way (v2 ends up with smaller text, which is not great for my old eyes).

v1.36:

![v1 36](https://user-images.githubusercontent.com/12691802/40046585-3505dee8-5825-11e8-9ea8-fecfeacf47b4.png)

v2.0.1:

![v2 0 1](https://user-images.githubusercontent.com/12691802/40046598-3bfe0108-5825-11e8-97d2-c7671c725de1.png)

It's not the end of the world, obviously, but it would be nice to at least revert the sizes to roughly what they were before, or at best provide some control over them from the UI.

**Comment by blitzmann** [comment]
Yeah, each platform seems to treat them differently, which is why it's always been a pain in the ass. Controlling them from the UI would be the ultimate end goal, absolutely, but it is a bit of a process since all GUI elements will probably have to be touched.

**Comment by DarkFenX** [comment]
Fitting pane fonts do not respect font settings from font.py

**Comment by blitzmann** [comment]
That should be a quick fix, at least until more investigation can find a better solution :D

**Comment by DarkFenX** [comment]
Well, obviously it should still use fonts.py, but should have separate entry for fitting pane - just to make sure mac users are still handled separately.

**Comment by DarkFenX** [comment]
Decided to take a deeper look into differences. In fitting pane, with `wx.Font(10, wx.SWISS, wx.NORMAL, wx.BOLD)`:

```
default encoding: 43 (FONTENCODING_UTF8)
face name: Sans
family: 74 (FONTFAMILY_SWISS)
native font info desc: Sans Bold 10
native font info user desc: Sans Bold 10
pixel size: (10, 17)
point size: 10
style: 90 (FONTSTYLE_NORMAL)
weight: 92 (FONTWEIGHT_BOLD)
```

In market item list, which is the proper font:
```
default encoding: 43 (FONTENCODING_UTF8)
face name: Cantarell
family: 70 (FONTFAMILY_DEFAULT)
native font info desc: Cantarell 11
native font info user desc: Cantarell 11
pixel size: (8, 20)
point size: 11
style: 90 (FONTSTYLE_NORMAL)
weight: 90 (FONTWEIGHT_NORMAL)
```

So, i suppose that setting some of font parameters manually is bad idea. Namely, setting swiss style sets sans, which is different face type from face type used in other widgets (cantarell). So, getting system or default font should be the way to go. I found 2 ways to do that: `font = self.GetFont()` and `font = wx.SystemSettings.GetFont(wx.SYS_DEFAULT_GUI_FONT)`. The latter is used in column sizing code below, so i guess i will stick to it.

**Comment by DarkFenX** [comment]
Should be fixed in 051e601f14d2b226895e7f1065fa6b68856d2b95 - but i tested only on linux. Hopfully, it works under windows and mac as well. If someone can check it, please do.

**Comment by DarkFenX** [comment]
This is py2/wx3 pyfa:

![image](https://user-images.githubusercontent.com/275209/40777656-29df5e86-64d7-11e8-89ee-54794a9c98cf.png)

At least tab headers are smaller, maybe there're more differences which are hard to spot with naked eye.

**Comment by DarkFenX** [comment]
I changed tab headers as well, switched from 10pt to 8pt. If it looks too small on Macs (too small compared to win/linux or too small compared to old version), we might want to use fonts.NORMAL size (which is defined as 11 for MacOS).

We should review how pyfa handles fonts later, currently it's a bit messy: some parts are using defines from fonts, some parts use values hardcoded in widgets.

**Comment by blitzmann** [comment]
Thanks for looking into this @DarkFenX, I agree the changes made so far look good. Will test on OS X and get you a build as well by tomorrow.

Also agree that fonts are a mess in general. There was talk long ago about making them (or at least the size) user-specific, buyt default to system defaults, because some people find the current size too large / too small, and there's no real way to change it. But that would require a complete audit of the GUI to find all the little places it touches.

**Comment by blitzmann** [comment]
Go head and mark this issue as fixed whenever you feel you're done with the twekas :)

**Comment by DarkFenX** [comment]
I think I'm gucci with changes as-is (from visual side, but my inner perfectionist isn't happy with font-related code mess at all, but that's another story). Let's close it after we confirm that fonts look alright on macs.

**Comment by blitzmann** [comment]
Yeah, it looks really small on macs unfortunately. Left is 2.1.1 release, right is latest master with new font tweaks

![screen shot 2018-06-02 at 10 39 14 am](https://user-images.githubusercontent.com/3904767/40877582-563f5bf4-6651-11e8-97ce-bd6e73efe883.png)

**Comment by blitzmann** [comment]
So, it would seem that on the 1.x branch, we were using NORMAL https://github.com/pyfa-org/Pyfa/blob/1.x/gui/chromeTabs.py

This might actually be my bad... chrome_tabs was migrated to wxPhoenix a long time ago for shits and giggles in another repo. Then nothing was done with it. In the meantime, various fixes and improvements were made over the years to the 1.x chrome tabs (such as a bit better font support). But when we moved to wxPhoenix for the entire application, I just took the already migrated chrome tabs...

So there's probably newer stuff in 1.x version that never got migrated over to the newer version. >_>

**Comment by blitzmann** [comment]
https://ufile.io/kf7ur

Here's a build for the current font changes for mac, in case anyone is interested...

**Comment by DarkFenX** [comment]
@blitzmann could you play with point size on mac and say which looks the best (closest to font in market panel, for example)? Under linux, fonts look as in other widgets with this code:
```
        self.font = wx.SystemSettings.GetFont(wx.SYS_DEFAULT_GUI_FONT)
        self.font.SetPointSize(11)
```
Unfortunately, i have no idea how to modify mac build you've just uploaded, so cannot do it myself.

**Comment by DarkFenX** [comment]
Or, alternatively, do bunch of debugging prints for font in market panel, and see what kind of output it produces. Add this code to itemView.py, beginning of selectionMade method:
```
        from logbook import log, ERROR
        font = self.GetFont()
        log(ERROR, 'font pointsize {}'.format(font.GetPointSize()))
```
Then check logs for used font params.

**Comment by blitzmann** [comment]
@DarkFenX sorry for the late response. Can you give the latest master a test? Should be the same (I believe), and this looks correct on both Windows and Mac for me.

**Comment by DarkFenX** [comment]
@blitzmann fonts look fine to me on linux. However, as i assume commit d4d55c026a2b32a09344b252459d8548d110eec4 is supposed to fix it, I have few questions:

1) Line 1388 still has font size hardcoded, is it intended? Why?
2) How does it fix fitting panel fonts? As far as i understand, they are supposed to be identical to fonts in market item list. And BoraVyvorant in his comment posted few pics which show how fonts were changed. Are we going to do anything about it?

**Comment by blitzmann** [comment]
> Line 1388 still has font size hardcoded, is it intended? Why?

Nope, just missed it! :P

> How does it fix fitting panel fonts? A

I left the fitting panel alone as, IIRC, it was pretty darn close to what it looked like in 1.x. Could be remembering incorrectly, as I didn't really focus on these that much, I basically just brought the tabs in line. Will double check. :)

**Comment by DarkFenX** [comment]
One of my friends who uses mac and who launched pyfa after a year of inactivity said that fonts are really bad compared to what they were, so i suppose they are not that close (i didn't double check, but pretty sure he meant fitting panel).

**Comment by DarkFenX** [comment]
@blitzmann did you have chance to check fitting panel on mac?
