### ISSUE TITLE
2.x Bugs: Numerous UI Issues

### ISSUE THREAD

**Issue by alexanderdarino** [pyfa-org/Pyfa#1565]
1. The text on tabs should end in ellipses (...) when the full ship name cannot fit
2. #1564 Fonts have changed from the 1.x series; tab fonts in particular should be made smaller to better fit contents
3. **When having multiple ships open, changing tabs sometimes does not update the contents of the right panel** <<< this makes Pyfa 2.0 unusable.
4. Sometimes when deactivating an active module, a green checkmark remains visible instead of the yellow circle (right panel indicates module is deactivated)
5. Sometimes when deleting a module, the module continues to appear as if it is fitted even when it is clearly removed (right panel indicates module is removed)
6. Takes a long time to start up on Windows (~20s); this issue was not present in the 1.x series.

And some others. I'll update this as I find them.

**Comment by secondfry** [comment]
Double up on long start-up time on Windows – it's crazy long, doing `python pyfa.py` is 10x faster.

And doubling on third bullet – open any T3C fit and start clicking other fits in left panel. Right one will not update following the click and it's behavior is unpredictable. https://i.imgur.com/Buc9O5Z.png

**Comment by fornicatory** [comment]
Can confirm three of alexanderdarinos six issues. Alexanderdarino no offense meant but if you number
your issues it would be less confusing for the devs/users when referencing them ;

Am using Windows 7 with stable Pyfa 2.0.0

Can confirm the following issues:

1)  Sometimes when deactivating an active module, a green checkmark remains visible instead of the yellow circle (right panel indicates module is deactivated)

2) Sometimes when deleting a module, the module continues to appear as if it is fitted even when it is clearly removed (right panel indicates module is removed)

3) Takes a long time to start up on Windows (~20s); this issue was not present in the 1.x series.

Top work on this application. Very much appreciated,

P.

**Comment by alexanderdarino** [comment]
@fornicatory I've numbered them all; feel free to update your comment to match the numbers I listed.

**Comment by blitzmann** [comment]
>The text on tabs should end in ellipses (...) when the full ship name cannot fit

This is a lot more effort than I think you may realize /o\ Once things die down though, I can take a look at what's involved. :)

The font thing I'm not worried about right now, to be frank. Should be tweaked, but there's a few other things that need to happen. 

The GUI not updating is something that a few folks have mentioned to me, and it's throwing me for a loop. @alexanderdarino, @secondfry , @fornicatory are you able to reproduce consistently with the same or similar fits? If so, please please please send me your `saveddata.db` file to sable.blitzmann@gmail.com with a link to this issue, and some **detailed** steps on how to reproduce (if you think you're being obnoxiously detailed, get more detailed! :P) 

I'm wondering it it has to do with something in the code breaking when doing the fitting calcs, and thus the GUI never receiving the signal to update. If that's the case, I'm thinking it has to do with certain fits, or what's on those fits.

>Takes a long time to start up on Windows (~20s); this issue was not present in the 1.x series.

The fuck?

Can you guys try some of the beta releases for 2.0? I'm interested to see if this has been a problem and none of the beta testers have run into it. Also, attaching logs might help (as each line in the log files has a timestamp, I can try to pinpoint what exactly is taking a long time)

> Top work on this application. Very much appreciated

![image](https://user-images.githubusercontent.com/3904767/40028084-08d8be5a-57ab-11e8-935c-2f2a1147715e.png)

Thanks :P

**Comment by fornicatory** [comment]
Very much serious.  Too many people are quick to complain and glacial to praise.
Will test and report back as requested. Is my birthday today so alcohol is impairing
my QA foo. Tomorrow afternoon should see results.

Once again thank you for your hard work.

Regards.

**Comment by blitzmann** [comment]
> s my birthday today so alcohol is impairing my QA foo. 

Happy belated birthday! woot woot!

And thanks so much for the encouragement :)

**Comment by blitzmann** [comment]
All, there is a test build in #1586 that I would like for you guys to run to see if the UI bugs with it not updating are fixed / improved. Please give it a test :)

**Comment by blitzmann** [comment]
I'm going to close this as half of the issues here were resolved in #1586. 

As for the other issues...

> Takes a long time to start up on Windows (~20s); this issue was not present in the 1.x series.
If this is still a problem, please open another issue.

> The text on tabs should end in ellipses (...) when the full ship name cannot fit

This is more of a nice to have, although if we were to implement it it would mean that the ellipses would cover space that the ship name would, further limiting the information available. I'm open to discussion on this, but my initial reaction to this is "not needed", and the work behind it sounds terrifying /o\ :P

And the font one already has it's own issue for tracking.

Thanks all! :)

**Comment by blitzmann** [comment]
@alexanderdarino @secondfry  @fornicatory Please see #1605 for discussions on long start up times, and please follow the guidance of posting log files (or at least the first chunk, especially if you see a large gap in time stamps)
