### ISSUE TITLE
Can't link character to Eve SSO

### ISSUE THREAD

**Issue by fcipriani** [pyfa-org/Pyfa#1567]
## Bug Report
Can't link character to Eve Online Character with EVE SSO

### Expected behavior:
The skills are fetched into the skills tab, button "Log In With Eve SSO" disappears

### Actual behavior:
Trying to paste SSO info manually I get the error:

OS version: Windows-7-6.1.7601-SP1
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 799, in ssoListChanged
RuntimeError: wrapped C/C++ object of type StaticText has been deleted

### Detailed steps to reproduce:
Change preferences EVE SSO authentication method -> Manual
Open Pyfa Character Editor, create new Character, select character, open the EVE SSO tab, click Log In With EVE SSO, authorize, copy info, paste into "SSO Login" window. Got this error a couple of times using the "local server" preference option as well. Could never get it to work in any case.

### Release or development git branch? Please note the release version or commit hash:
I downloaded pyfa-2.0.0-yc120.3-1.8-win.zip, c1e239b

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Info included in the error

**Comment by fcipriani** [comment]
Sorry this seem the same as #1552, guess it just need to be merged there.

**Comment by blitzmann** [comment]
indeed, it is a duplicate (and an issue that has been fixed :D). Thanks for the report tho!
