### ISSUE TITLE
Market hub selection for pricing does not appear to work

### ISSUE THREAD

**Issue by jasconius** [pyfa-org/Pyfa#1570]
## Bug Report
Market hub selection for pricing does not appear to work

### Expected behavior:
Changing the market and resetting the cache should produce new pricing based on location

### Actual behavior:
The price always seems to be JITA pricing no matter what

### Detailed steps to reproduce:
Change the market in the preferences, reset cache

### Fits involved in EFT format (Edit > To Clipboard > EFT):
any

### Release or development git branch? Please note the release version or commit hash:
2.0 release

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
Confirmed in person at Rens that the pricing is not even close

**Comment by blitzmann** [comment]
Can you ocnfirm that you'r using eve-marketdata as a source?

**Comment by jasconius** [comment]
yes that is confirmed

**Comment by blitzmann** [comment]
It seems this might be an issue with eve-marketdata. I took a look at we're sending the correct `system_id`. I'll try to get in touch with the dev to see if I'm screwing up somewhere.

I may also just fucking move to ESI-based market prices... would have to look into that.

**Comment by blitzmann** [comment]
After getting into touch with the developer, it seems it might be an issue on their end. It also seems that there is a lack of time to fix it, so not sure if it's going to be fixed.,

As a workaround, if you need system-specific market data, please use evemarketer as the source. 

I will additionally be evaluating the use of EVE's ESI market endpoints.

**Comment by DarkFenX** [comment]
Closing as we can do nothing about this issue.
