### ISSUE TITLE
'Hardshell' tank booster not applying to capital reps

### ISSUE THREAD

**Issue by muleooo** [pyfa-org/Pyfa#1571]
## Bug Report
The three tank boosters, for example, Agency 'Hardshell' TB7 Dose III, don't work in pyfa on capital shield/armor reps. They do work in game.

### Expected behavior:
Adding a 'Hardshell' drug should increase capital shield booster and capital armor repairer repair amounts by the relevant %.

### Actual behavior:
The drugs, they do nothing!

### Detailed steps to reproduce:
Load a fit with a capital shield/armor rep. Add a Hardshell drug.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

[Rorqual, Rorqual fit]

Capital Armor Repairer I
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

Capital Shield Booster I
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

Agency 'Hardshell' TB7 Dose III

### Release or development git branch? Please note the release version or commit hash:
2.0.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 7

**Comment by mumbleskates** [comment]
Hardshell boosters do not affect capital reps in game.

**Comment by blitzmann** [comment]
> Hardshell boosters do not affect capital reps in game.

Indeed, don't think this is a bug. :)

**Comment by muleooo** [comment]
Huh interesting. It works on sisi but not in tranquility, looks like it was a bug they're going to fix next patch.

**Comment by blitzmann** [comment]
Ah, yeah, the sisi versions have different effects. This should be one of the things I check for when I do an update. 👍

**Comment by mumbleskates** [comment]
I already knew this from tq, and tested it on sisi before posting. It behaved the same both places, at least on that boot of sisi.
