### ISSUE TITLE
Deletion of fit causes crash to desktop

### ISSUE THREAD

**Issue by Hoeya** [pyfa-org/Pyfa#1573]
## Bug Report

When deleting a fit, sometimes will cause a crash to desktop. 

### Expected behavior:

When you press the red button to delete a fit, it comes up with a prompt asking user if they are sure they wish to delete fit. If yes is selected, fit is deleted. 

### Actual behavior:

Fits seems to randomly cause a crash to desktop on deletion. If you try to delete two fits with the same fitting, it can trigger this, but have had it happen even on a single deletion. 

### Detailed steps to reproduce:

Create a fit, or choose an old fit. Delete fit. Try until it causes a crash. 

### Fits involved in EFT format (Edit > To Clipboard > EFT):

Any. Tried this with multiple ship types, ships. It doesn't seem to be related to a specific ship or type. 

### Release or development git branch? Please note the release version or commit hash:

Release branch.  pyfa-2.0.0-yc120.3-1.8-win

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10 

### Other relevant information:

**Comment by blitzmann** [comment]
This is an old, old bug (#164 and all other associated bugs) with fit deletions that can cause the program to just die. it is definitely on my radar to address once I smooth out 2.0 and also get pyfa up to speed with the next expansion data. :)
