### ISSUE TITLE
Character skills should refresh when changing SSO character (edited)

### ISSUE THREAD

**Issue by Zyrixion** [pyfa-org/Pyfa#1577]
EDIT:  It does work, but requires you to select a character as pilot of a fit and press the small, unlabeled "Refresh API" button before any skills will populate.  You should probably add a button to force api update to the actual character editor, since it took me half an hour to figure out where the hell the button was.

## Bug Report

Character skills do not import despite logging in with SSO.

### Expected behavior:

Log in with SSO, character skills should populate.

### Actual behavior:

Log in with SSO, absolutely nothing happens, appears to complete successfully but skills do not populate.

### Detailed steps to reproduce:

Try to import skills to a new character I guess.

### Release or development git branch? Please note the release version or commit hash:

Release branch, pyfa-2.0.1-yc120.3-1.8-win

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 7.

**Comment by blitzmann** [comment]
> EDIT: It does work, but requires you to select a character as pilot of a fit and press the small, unlabeled "Refresh API" button before any skills will populate. You should probably add a button to force api update to the actual character editor, since it took me half an hour to figure out where the hell the button was.

Yeah, it was on the list of things to do and I never got around to it. >.<

I'm going to reopen this and make sure progress on that gets tracked so that it doesn't fall off my radar 👍

**Comment by blitzmann** [comment]
Added a button to the character editor SSO section to fetch skills. It's not automatic, as I don't people accidentally overwriting skills if they acidently change the sso character.

cec61fc225cf30426c907ca26c85eae062316c6a
