### ISSUE TITLE
Fit export via API no longer returns a success message

### ISSUE THREAD

**Issue by jasconius** [pyfa-org/Pyfa#1580]
I wouldn't call this a bug, just a minor feature enhancement

In 1.x, when you would export a fit, you would get a "200 OK" message in the UI indicating it had worked

with the updated SSO exporting (which I love), you don't get the same explicit success message

Adding something like this back would be helpful

**Comment by blitzmann** [comment]
Duplicate #1502

I think I'm going to wait for the ESI stuff to stabilize a bit and make sure there aren't any other pressing issues that will cause another refactoring. I need to do another once over the SSO windows and make sure error handling is properly implemented (I know it's not for the export window), as well as success messages. :)
