### ISSUE TITLE
UI doesn't change upon removing module. Have to constantly restart Pyfa to get it to display correctly

### ISSUE THREAD

**Issue by GoldenCoins** [pyfa-org/Pyfa#1586]
Here is a video of the issue:
https://streamable.com/03azr

At start:
You can see that the dps is listed as 1004, all BCS modules in low slots are present

0:13:
One BCS module is removed. Stats panel updates to show DPS reduced to 958, but fitting panel UI still shows that module is present

0:22: 
Upon trying to double click/add a new BCS module from the market group panel, it does not allow me to do so, as it thinks that there are no free slots. Even though one was actually removed

0:51:
Upon re-opening pyfa, and re-opening that fit, the UI now shows that the module has in fact been removed, despite it not showing this before.

This happens VERY frequently, and so when updating or making fits I have to close pyfa once every 2-3 minutes just to get it to work.

Log File:
[pyfa-2018-05-16.log](https://github.com/pyfa-org/Pyfa/files/2011070/pyfa-2018-05-16.log)

**Comment by blitzmann** [comment]
Thanks for the information, and especially the video.

Does this happen only after you've been using pyfa for a while? Can you get it to reproduce consistently with a detailed list of steps? Or does it seem to just start happening randomly?

I've been trying to reproduce the issue for a couple days now, and I'm not able to ever see this :(

Will take a look at the logfile for any hints, thanks for supplying it :)

**Comment by blitzmann** [comment]
Think I got it! It happens whenever you close a fitting tab. I think it has to do with the following:

```

    def Destroy(self):
        print("+++++ Destroy " + repr(self))
        print(self.parent.Unbind(EVT_NOTEBOOK_PAGE_CHANGED))
        print(self.mainFrame.Unbind(GE.FIT_CHANGED))
        print(self.mainFrame.Unbind(EVT_FIT_RENAMED))
        print(self.mainFrame.Unbind(EVT_FIT_REMOVED))
        print(self.mainFrame.Unbind(ITEM_SELECTED))

        d.Display.Destroy(self)
```

Whenever the fitting tab closes, this block of code runs. What it's supposed to do is deregister that specific fitting tab from the events. What I think it's doing instead of deregistering all fitting tabs... Which is no good.

So, you have ship 1, ship 2, and ship 3. You open ship 1 and 2 in tabs. When you're on ship 2, you close ship 1. ship 2 tab is now broken. You open ship 3. Ship 3 works (since it was initialized after we closed and deregistered all the events).

This kind of ties into the shitty fit deletion process that we currently have and is planned to refactor... now I'm wondering if I should kill two birds with one stone and try to solve both issues.

but, for now, I can reproduce (at least most of the reported UI bugs)

Also, fun fact, labels can have emojis. 😆

**Comment by blitzmann** [comment]
@GoldenCoins @alexjurkiewicz @secondfry @fornicatory can you try this build? Only windows build for now, but I'm hoping this takes care of the UI update issues. 

https://ufile.io/6xel7

**Comment by fornicatory** [comment]
Have been testing version linked above v2.0.1-2-g806f17f6e.
So far have had no problems with modules or tabs. Also the startup time has improved.

Can confirm possible link to the deletion process.  If you follow:

You have ship 1 and ship 2. You open ship 1 and 2 in tabs. When you're on ship 2, you close ship 1.
Then delete ship 1 fitting you get the following error:

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinViews\fittingView.py", line 289, in fitRemoved
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\multiSwitch.py", line 46, in DeletePage
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\chrome_tabs.py", line 247, in DeletePage
TypeError: list indices must be integers or slices, not NoneType

Hope this helps.

**Comment by blitzmann** [comment]
Thanks @fornicatory for the info, will test this out tonight and try to get a fix out there. I'm hoping to delay the deletion refactor until after the next expansion hits, but we'll see about at least sweeping some of these errors under the rug >_>.

**Comment by fornicatory** [comment]
No worries saw the todo in the code and thought a refactor was planned.
Looked for the delete error I mentioned above in the issues and the error
text was different to previous reports so listed it in this thread.

Rugs are extremely useful in all professions ;)

**Comment by blitzmann** [comment]
is there anyone else that can confirm if this seems to solve the basic problem of the GUI not refreshing?
