### ISSUE TITLE
bitmap_loader.py throws an error in line 87 if using zipped image files

### ISSUE THREAD

**Issue by NamelessNewbie** [pyfa-org/Pyfa#1590]
## Bug Report

I tried building the new sisi branch with cx_freeze, and after a long fight managed to get it working - however, it crashes with TypeError: initial_value must be str or None, not bytes in bitmap_loader.py in line 87. Apparently this is a python 2/3 issue. It works if I use the unzipped image files instead of the zipped ones, so the issue seems to be in  "archive = zipfile.ZipFile(os.path.join(config.pyfaPath, 'imgs.zip'), 'r')"

### Release or development git branch? Please note the release version or commit hash:

pyfa-singularity

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Win 10

### Other relevant information:
 cx_Freeze 6

**Comment by blitzmann** [comment]
> I tried building the new sisi branch with cx_freeze

pyfa no longer supports cx_freeze. Instead use pyinstaller (using this spec file `https://github.com/pyfa-org/Pyfa/blob/master/dist_assets/win/pyfa.spec`)

Specifically, use the following command within the root pyfa directory

`python3 -m PyInstaller --clean --windowed --noconsole -y ./dist_assets/win/pyfa.spec`

**Comment by NamelessNewbie** [comment]
Oh sweet, thanks for clearing that up! I'll try it with pyinstaller. I did get it to work with cx_freeze after a while tho.
