### ISSUE TITLE
Fits do not export to Eve

### ISSUE THREAD

**Issue by MarHelmer** [pyfa-org/Pyfa#1593]
## Bug Report
Since upgrading to v2.0.2, when attempting to export fits from Pyfa to Eve, nothing happens.  Hitting the export button yields no success or error message and the fit does not show up in Eve; the standard message about communicating with the server to export the fit does not show up, either.  This is true across all characters (I tried it with all seven I have loaded into Pyfa) and all fits, even freshly loaded fits and brand-new test fits.  Reloading Pyfa does not help.  Updating character information with the green arrows button seems to succeed.

### Expected behavior:
The fit should export and a message should appear stating that Pyfa is communicating with Eve.  The fit should then show up in Eve.

### Actual behavior:
No message shows up during export and the fit does not show up in Eve.

### Detailed steps to reproduce:
Open any fit.  Click the EVE SSO menu and click Export To Eve.  Select any character from the dropdown.  Click Export Fit.  Nothing will happen.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
This is true across all fits in my DB, including freshly loaded and brand-new test fits.

### Release or development git branch? Please note the release version or commit hash:
This is a new issue as of v2.0.2.

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10 Pro 64-bit v1803, build 17134.48.

### Other relevant information:
Reloading Pyfa, rebooting the computer, and creating brand new fits did not resolve the issue.

**Comment by MarHelmer** [comment]
Hi again.  So in 2.0.1 and 2.0.0, the export window would flash a message about how it's communicating with the server or something—I can't remember specifically, but I believe it was connectivity-related and not about success or failure.  I don't think it's that important, however.

I restarted the client (and Pyfa, and my computer), but the fits have not shown up.  When I use Pyfa to browse my fittings, it can retrieve all my extant fits, but the fits that should have been uploaded are not in the list.

Again, this is new behavior specific to 2.0.2; everything worked perfectly in 2.0.1 and 2.0.0.

I have attached my log files from the last three days.  I upgraded to 2.0.2 on the evening of 2018-05-19, so if the log files are helpful, you should have a way to see any changes.

I have also created a video demonstrating the issue: https://youtu.be/rOqjgMFF2KI

[pyfa-2018-05-18.log](https://github.com/pyfa-org/Pyfa/files/2020359/pyfa-2018-05-18.log)
[pyfa-2018-05-19.log](https://github.com/pyfa-org/Pyfa/files/2020360/pyfa-2018-05-19.log)
[pyfa-2018-05-20.log](https://github.com/pyfa-org/Pyfa/files/2020361/pyfa-2018-05-20.log)

**Comment by blitzmann** [comment]
Thanks so much, all this is helpful!

I'll look into it and get back to you. In the meantime, you can go the long way and save fitting to XML and import in eve. It's a shitty way, but it'll get the fit into the game :)

**Comment by blitzmann** [comment]
Also, re: the video

It seems that you're expecting the fit to show up in the browse fitting window after exporting. This may or may not happen, depending on the steps taken.

The browse fittings API call is cached on CCPs side for 15 (?) minutes. So if you go to browse fittings, hit Fetch Fits, that data is not going to change until after 15 minutes, no matter what you do in game or in pyfa (create fitting in game, export in pyfa, etc). The only asterisk next to this is if you delete a fitting, but that's because I'm caching all the deleted fit IDs and explicitly not displaying them (so that users aren't wondering why a delete fit is still sitting around)

pyfa does a horrible job (read: makes no attempt at) conveying this information properly, which is something I want to work on soon. Just wanted to throw that out there for clarity :)

**Comment by MarHelmer** [comment]
Thanks for clarifying how the fetched fits display.  I can confirm that they don't show up in the game or after restarting Pyfa about an hour later.

**Comment by blitzmann** [comment]
Status should be shown now, woot!

**Comment by MarHelmer** [comment]
Nice! Thanks so much for all your hard work.

**Comment by blitzmann** [comment]
I try! 😛 

Thanks! The next release will probably be next week, probably a day or two after the expansion. :)
