### ISSUE TITLE
Additions window information area does not dynamically resize

### ISSUE THREAD

**Issue by MarHelmer** [pyfa-org/Pyfa#1594]
## Bug Report
Since upgrading to v2.0.2, when attempting to resize the additions window, the information area does not resize with the window. Reloading Pyfa and changing fits does not help.

### Expected behavior:
The information area should dynamically resize as the window is expanded or contracted.

### Actual behavior:
The information area is static in size.

### Detailed steps to reproduce:
Click and drag to resize the size of the additions window.  The information area remains static in size.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
This is true across all fits in my DB, including freshly loaded and brand-new test fits.

### Release or development git branch? Please note the release version or commit hash:
This is a new issue as of v2.0.2.

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10 Pro 64-bit v1803, build 17134.48.

### Other relevant information:
Reloading Pyfa, rebooting the computer, and creating brand new fits did not resolve the issue.

**Comment by MarHelmer** [comment]
I have since tried again and it does indeed seem to be working correctly.  I am sorry for the trouble; please close this ticket.  If the issue crops up again, I will create a GIF for you and reopen this thread.  Thanks!

**Comment by blitzmann** [comment]
Thanks for double checking! Maybe have been a fluke the first time around, no worries!

**Comment by irwiss** [comment]
@blitzmann Not sure if this is specifically this bug(it reproduces after restarts), but similar bug reproduction: 

* Open pyfa (mine is v2.6.0)
* Click header of Additions panel to minimize it
* Click header again to restore
* Try dragging the window up/down

You'll see contents stop resizing as you resize the panel
