### ISSUE TITLE
March updates: Machariel changes not yet applied

### ISSUE THREAD

**Issue by Pzenarch** [pyfa-org/Pyfa#1601]
The Machariel profile is out of date.  The new profile has 6 mid slots and 6 low slots (as opposed to PyFA's 5 mid slots and 7 low slots), features a 7.5% per level bonus to large projectile falloff (instead of the previous 10%), and the signature radius has increased by 30.

This changes were announced in the March update (link below), not sure when they came into effect, but it might be worth reviewing the other changes in that update in case they also need to be applied.

https://www.eveonline.com/article/p4ejjg/balance-changes-coming-in-the-march-release

### Expected behavior:

When creating a Machariel fit, there should be 6 mid slots, and 6 low slots, a 7.5% per level bonus to large projectile falloff, and a signature radius 30 higher than it currently is.

### Actual behavior:

There are currently 5 mid slots and 7 low slots, a 10% per level bonus to large projectile falloff, and a signature radius 30 lower than it should be.

### Detailed steps to reproduce:

n/a

### Fits involved in EFT format (Edit > To Clipboard > EFT):

n/a

### Release or development git branch? Please note the release version or commit hash:

2.02 release branch.

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10.

### Other relevant information:

n/a

**Comment by blitzmann** [comment]
Hrm, the data that pyfa uses comes directly from EVE, so I'm not sure how this got missed... Will take a look when I get home :)

**Comment by blitzmann** [comment]
So, just checked with my local 2.0.2..

![image](https://user-images.githubusercontent.com/3904767/40312086-d37a48e8-5cdf-11e8-9dca-7cdff53772bd.png)

I'm showing 8/6/6, with the correct traits... is this not the same as yours? Are you looking at older fits which may have had the old config (pyfa should automatically update them, but it could be bugged)?

**Comment by Pzenarch** [comment]
This was after creating a new fit, though I do have a few existing ones using the old layout ... and I have been doing in-line upgrades of PyFA for ... a while now.  I'm not on the correct machine for testing, but can try clearing out the user data folder when I get back, see if that resolves the problem.

**Comment by Pzenarch** [comment]
Here's a screenshot of what I'm seeing, for the record.  I've sent the savedata.db file to you via email, and to confirm, all machariel fits in the file are affected ... as well as any new ones created.

![asdasd](https://user-images.githubusercontent.com/3662922/40324401-511877ac-5d30-11e8-9999-c83e5126507d.png)

**Comment by blitzmann** [comment]
That is super odd... it looks like pyfa is using an old eve database...

did you install with the installer, or do you use the zip file and copy and paste over the previous install for every upgrade?

**Comment by Pzenarch** [comment]
For all releases prior to 2.0.2, my standard installation procedure was to delete the contents of the PyFA folder, and unzip the new version in its place.  With the release of 2.0.2, I used the installer but did not pre-clear the folder.  I did however install over 2.0.1.

**Comment by blitzmann** [comment]
> For all releases prior to 2.0.2, my standard installation procedure was to delete the contents of the PyFA folder, and unzip the new version in its place. With the release of 2.0.2, I used the installer but did not pre-clear the folder. I did however install to the same location that I had been using for 2.0.1.

This might be the case. If you've been using the extract zip file up until 2.0.2, those files don't have an uninstaller. The un/installer knows which files to touch to remove. The 2.0.2 is supposed to uninstall the 1.x versions, but that only works if it was previously installed. It sounds like the 2.0.2 installer simply tried to overwrite things in the target directory, and I'm not really sure what that does (does it overwrite? does it keep the old one? ¯\_(ツ)_/¯)

Glad to hear that clearing the installation worked for you. :) Gonna close this
