### ISSUE TITLE
Old behavior RAH do not applied to Uniform damage pattern

### ISSUE THREAD

**Issue by vmech** [pyfa-org/Pyfa#1602]
### Expected behavior:
Cant show by technical reasons.

### Actual behavior:
![](https://image.prntscr.com/image/BTQGyLcXSDqgznWyWipu7Q.png)
Default armor resists with inactive RAH:
![](https://image.prntscr.com/image/1tkjoP2gR-2pVhWRwhLtDQ.png)
Armor resists and EHP stay the same after activating RAH:
![](https://image.prntscr.com/image/52_MbqaDQHyPylId0FuLVw.png)
Any other damage patterns correctly applying resists (100% thermal damage on shot):
![](https://image.prntscr.com/image/IGXA41ZxSwOa_cQGkCVNTQ.png)

### Detailed steps to reproduce:
n/a

### Fits involved in EFT format (Edit > To Clipboard > EFT):
n/a

### Release or development git branch? Please note the release version or commit hash:
2.0.2 release branch

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
With unchecked *Preferences* setting RAH works properly.

**Comment by blitzmann** [comment]
Can you go into a bit more detail ont he values that you're getting vs the values that you expect? A few screenshots for the "actual" vs "expected" doesn't help much, especially when I don't knwo what the different screenshots are representing. I'm not able to really dig in right now, but a more detailed description of the problem would be helpful for when I can look at this :)

**Comment by vmech** [comment]
@blitzmann nope, I cant. With unchecked option *Set RAH to match (old behavior)* PYFA cant set omni-resists (15/15/15/15) onto active RAH. Onto inactive only.

**Comment by blitzmann** [comment]
I feel like there is a language barrier here, but I also think I see what you mean now that I'm home and able to play with it. When the option is set, it doesn't actually apply any resists when it's a uniform damage, correct?

I think I have this fixed with aeb1a80e73b1f8357160b1b63f701c1dc09c713a

**Comment by vmech** [comment]
> When the option is set, it doesn't actually apply any resists when it's a uniform damage, correct?

Yes :)
