### ISSUE TITLE
Error with login in SSO (Manual)

### ISSUE THREAD

**Issue by CurrencyCop** [pyfa-org/Pyfa#1614]
1) Installed Pyfa
2) set login SSO method - manual
3) Open character window
4) Click on Log In with EVE SSO
5) Get "block of text"
6) Inject this block in special windown in Pyfa
7) Profit... (Error)
8) Trying steps 4-7 three times

```
OS version: Windows-7-6.1.7601-SP1
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 799, in ssoListChanged
RuntimeError: wrapped C/C++ object of type StaticText has been deleted

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 799, in ssoListChanged
RuntimeError: wrapped C/C++ object of type StaticText has been deleted

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 799, in ssoListChanged
RuntimeError: wrapped C/C++ object of type StaticText has been deleted

```

**Comment by blitzmann** [comment]
what version of pyfa are you on?

**Comment by blitzmann** [comment]
Also, these are GUI event errors... I believe it should still get the sso data

**Comment by CurrencyCop** [comment]
2.0.0

**Comment by CurrencyCop** [comment]
so tell me - after get sso data - i must get my character with learned skills? I have my character in list but skills are not imported =(

**Comment by blitzmann** [comment]
Yep, thought I fixed this at some point. :)

Curious... did you not receive an upgrade notification when starting your 2.0.0 client?

**Comment by CurrencyCop** [comment]
nope

**Comment by CurrencyCop** [comment]
it's turned on, maybe i just miss it? notification have checkbox "don't show on start"? I am starting v2.0.0 and no any notification...
