### ISSUE TITLE
Installation via git clone and pip with requirements.txt on Linux error

### ISSUE THREAD

**Issue by Enteneller2017** [pyfa-org/Pyfa#1617]
I get this error when trying to update the requirements with: python -m pip install -r requirements.txt
```
Invalid requirement: '<!DOCTYPE html>'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/req/req_install.py", line 252, in from_line
    req = Requirement(req)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/packaging/requirements.py", line 97, in __init__
    requirement_string[e.loc:e.loc + 8]))
InvalidRequirement: Invalid requirement, parse error at "u'<!DOCTYP'"
```
The sole reason I'm going this route to update pyfa is that I don't want to use third party packages, because they usually carry their own issues with them and having to trust the packager and also being able to get a recent version. Is the way I'm doing it a good method or is there any other potentially easier way to update pyfa other than running those two lines?
   git pull
   python -m pip install -r requirements.txt

I'm on Xubuntu 16.04.4. I have installed python3.6 (deadsnakes/ppa).

**Comment by Enteneller2017** [comment]
Installed pip especially for python3.6 and upgraded it as well for exactly that version, not just python3 (as that would call python 3.5, which is the latest in the ubuntu repo). This is what follows:

Invalid requirement: '<!DOCTYPE html>'
Traceback (most recent call last):
  File "/home/name/.local/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/home/name/.local/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1632, in parseString
    raise exc
  File "/home/name/.local/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/home/name/.local/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/name/.local/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/name/.local/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/name/.local/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/home/name/.local/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/name/.local/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3378, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/home/name/.local/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/name/.local/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 2689, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/name/.local/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 252, in from_line
    req = Requirement(req)
  File "/home/name/.local/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 97, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'<!DOCTYP'"

**Comment by blitzmann** [comment]
Huh, looks like it can't parse `requirements.txt` for some reason...

You could always just install each of the packages listed in `requirements.txt` individually and see if that works.

**Comment by Enteneller2017** [comment]
I'm looking for an easy intuitive and safe way to handle updating the tool. :)
And instead of trying to fetch every single requirement (which didn't work at some point, because the Ubuntu repo is as slow as anything to update packages) I thought it would be way less tedious to let pip work through your requirements list. It has worked in the past on this Ubuntu distro, like a year ago. 

If you provided an easy to use version like a zip to simply extract and start it right away or a flatpak or AppImage that would handle the dependencies mess better, that would be something I'd cherish. Having to deal subproblems of dependencies turns me off, as they keep changing. :D

wxPython seems to be at 3.0 in the ubuntu repo atm.

**Comment by blitzmann** [comment]
> If you provided an easy to use version like a zip to simply extract and start it right away or a flatpak or AppImage that would handle the dependencies mess better, that would be something I'd cherish. 

A linux build with PyInstaller is planned (basically what you ask for, something that comes self-contained), but no ETA on it yet.

> wxPython seems to be at 3.0

This won't work then. Try installing from https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ as previously mentioned (download the `.whl` file and run that through pip)

> I'm looking for an easy intuitive and safe way to handle updating the tool. :)

Once you get the environment set up correctly, updating it should be as easy as `git pull`.

I'm not sure why the `requirements.txt` file isn't working for you, but again I would recommend installing each of the packages inside `requirements` one by one (so, for example, `pip install logbook >= 1.0.0`)

**Comment by Enteneller2017** [comment]
Thanks Sable. 

Downloaded the Logbook (which was left out of the -r requirements.txt, the rest of the missing files were fetched fine it seems) from here: https://pypi.org/project/Logbook/#files
Checked the sha256. Then cd to download dir and:

python3.6 -m pip install Logbook-1.4.0-cp36-cp36m-win_amd64.whl 
Logbook-1.4.0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.
pip install wheel
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (0.29.0)

**Comment by minlexx** [comment]
> Logbook-1.4.0-cp36-cp36m-win_amd64.whl
Looks like wheel for windows (win_amd64)

**Comment by Enteneller2017** [comment]
Oops, right. 
No linux packages, just the source for linux it seems. Can pip build it from source automatically?

**Comment by minlexx** [comment]
```
$ /usr/local/bin/python3.6 -m pip install --user --upgrade logbook
Collecting logbook
Installing collected packages: logbook
  Found existing installation: Logbook 1.3.3
    Uninstalling Logbook-1.3.3:
      Successfully uninstalled Logbook-1.3.3
Successfully installed logbook-1.4.0
```
Looks like it doesn't need to. Kubuntu 16.04

**Comment by Enteneller2017** [comment]
That worked.
How do you cope with wxpython on Kubuntu? Upgrading the same way didn't work.

**Comment by minlexx** [comment]
wxPython:
```
$ /usr/local/bin/python3.6 -m pip install --user https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04/wxPython-4.0.0b2-cp36-cp36m-linux_x86_64.whl
```

**Comment by Enteneller2017** [comment]
Updated pyfa the same way described above via pip and requirements using python3.6. The following comes up when trying to start pyfa.

Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/local/src/pyfa/Pyfa/gui/errorDialog.py", line 40, in HandleException
    with config.logging_setup.threadbound():
AttributeError: 'NoneType' object has no attribute 'threadbound'

Original exception was:
Traceback (most recent call last):
  File "pyfa.py", line 104, in <module>
    config.defPaths(options.savepath)
  File "/usr/local/src/pyfa/Pyfa/config.py", line 116, in defPaths
    data = yaml.load(file, Loader=yaml.FullLoader)
AttributeError: module 'yaml' has no attribute 'FullLoader'

**Comment by blitzmann** [comment]
@Enteneller2017 

The SQL error you mention arent errors, they are just print statements. I think they were recently moved to the logs tho

please open a new issue if you are still having issues :)
