### ISSUE TITLE
Rorqual drone speed error

### ISSUE THREAD

**Issue by BikerGitHub** [pyfa-org/Pyfa#1625]
### Expected behavior:
'Excavator' Ice Harvesting Drone should be 254m/s

### Actual behavior:
pyfa shows 'Excavator' Ice Harvesting Drone 310m/s

### Detailed steps to reproduce:
use my skills simulation in game and in pyfa

my skills:
Acceleration Control 4
Accounting 0
Advanced Drone Avionics 0
Advanced Industrial Ship Construction 0
Advanced Industry 0
Advanced Infomorph Psychology 0
Advanced Laboratory Operation 0
Advanced Large Ship Construction 0
Advanced Mass Production 4
Advanced Mass Reactions 0
Advanced Medium Ship Construction 0
Advanced Planetology 0
Advanced Small Ship Construction 0
Advanced Spaceship Command 5
Advanced Target Management 0
Advanced Weapon Upgrades 0
Afterburner 3
Amarr Battlecruiser 0
Amarr Battleship 0
Amarr Carrier 0
Amarr Core Systems 0
Amarr Cruiser 0
Amarr Defensive Systems 0
Amarr Destroyer 0
Amarr Dreadnought 0
Amarr Drone Specialization 0
Amarr Encryption Methods 0
Amarr Freighter 0
Amarr Frigate 0
Amarr Industrial 0
Amarr Offensive Systems 0
Amarr Propulsion Systems 0
Amarr Starship Engineering 0
Amarr Strategic Cruiser 0
Amarr Tactical Destroyer 0
Amarr Titan 0
Anchoring 0
Archaeology 1
Arkonor Processing 0
Armor Layering 0
Armor Rigging 0
Armored Command 0
Armored Command Specialist 0
Assault Frigates 0
Astrogeology 5
Astrometric Acquisition 1
Astrometric Pinpointing 0
Astrometric Rangefinding 1
Astrometrics 3
Astronautic Engineering 0
Astronautics Rigging 0
Auto-Targeting Missiles 0
Biology 5
Bistot Processing 0
Black Ops 0
Bomb Deployment 0
Broker Relations 0
Burst Projector Operation 0
CPU Management 5
Caldari Battlecruiser 0
Caldari Battleship 0
Caldari Carrier 0
Caldari Core Systems 0
Caldari Cruiser 0
Caldari Defensive Systems 0
Caldari Destroyer 0
Caldari Dreadnought 0
Caldari Drone Specialization 0
Caldari Encryption Methods 0
Caldari Freighter 0
Caldari Frigate 0
Caldari Industrial 0
Caldari Offensive Systems 0
Caldari Propulsion Systems 0
Caldari Starship Engineering 0
Caldari Strategic Cruiser 0
Caldari Tactical Destroyer 0
Caldari Titan 0
Capacitor Emission Systems 3
Capacitor Management 4
Capacitor Systems Operation 5
Capital Artillery Specialization 0
Capital Autocannon Specialization 0
Capital Beam Laser Specialization 0
Capital Blaster Specialization 0
Capital Capacitor Emission Systems 0
Capital Energy Turret 0
Capital Hybrid Turret 0
Capital Industrial Ships 4
Capital Projectile Turret 0
Capital Pulse Laser Specialization 0
Capital Railgun Specialization 0
Capital Remote Armor Repair Systems 0
Capital Remote Hull Repair Systems 0
Capital Repair Systems 0
Capital Shield Emission Systems 3
Capital Shield Operation 4
Capital Ship Construction 0
Capital Ships 3
Cloaking 4
Cloning Facility Operation 0
Command Burst Specialist 5
Command Center Upgrades 0
Command Destroyers 0
Command Ships 0
Common Moon Ore Processing 0
Connections 0
Contracting 2
Controlled Bursts 2
Core Subsystem Technology 0
Corporation Contracting 0
Corporation Management 0
Covert Ops 0
Criminal Connections 0
Crokite Processing 0
Cruise Missile Specialization 0
Cruise Missiles 0
Customs Code Expertise 0
Cybernetics 5
Cynosural Field Theory 3
Dark Ochre Processing 0
Daytrading 0
Deep Core Mining 4
Defender Missiles 0
Defensive Subsystem Technology 0
Diplomacy 0
Diplomatic Relations 0
Distribution Connections 0
Doomsday Operation 0
Doomsday Rapid Firing 0
Drone Avionics 5
Drone Durability 3
Drone Interfacing 4
Drone Navigation 5
Drone Sharpshooting 4
Drones 5
Drones Rigging 0
Drug Manufacturing 0
EM Armor Compensation 0
EM Shield Compensation 0
Electromagnetic Physics 0
Electronic Attack Ships 0
Electronic Engineering 0
Electronic Superiority Rigging 0
Electronic Warfare 1
Electronics Upgrades 5
Empire Control 0
Energy Grid Upgrades 4
Energy Pulse Weapons 3
Energy Weapon Rigging 0
Evasive Maneuvering 4
Exceptional Moon Ore Processing 4
Exhumers 4
Expedition Frigates 3
Explosive Armor Compensation 0
Explosive Shield Compensation 0
Fast Talk 0
Fighter Hangar Management 0
Fighters 0
Flag Cruisers 0
Fleet Command 0
Frequency Modulation 0
Fuel Conservation 0
Gallente Battlecruiser 0
Gallente Battleship 0
Gallente Carrier 0
Gallente Core Systems 0
Gallente Cruiser 0
Gallente Defensive Systems 0
Gallente Destroyer 0
Gallente Dreadnought 0
Gallente Drone Specialization 0
Gallente Encryption Methods 0
Gallente Freighter 0
Gallente Frigate 0
Gallente Industrial 1
Gallente Offensive Systems 0
Gallente Propulsion Systems 0
Gallente Starship Engineering 0
Gallente Strategic Cruiser 0
Gallente Tactical Destroyer 0
Gallente Titan 0
Gas Cloud Harvesting 5
Gneiss Processing 4
Gravimetric Sensor Compensation 0
Graviton Physics 0
Guided Missile Precision 0
Gunnery 4
Hacking 1
Heavy Assault Cruisers 0
Heavy Assault Missile Specialization 0
Heavy Assault Missiles 0
Heavy Drone Operation 3
Heavy Fighters 0
Heavy Interdiction Cruisers 0
Heavy Missile Specialization 0
Heavy Missiles 0
Hedbergite Processing 0
Hemorphite Processing 0
High Energy Physics 0
High Speed Maneuvering 1
Hull Upgrades 4
Hybrid Weapon Rigging 0
Hydromagnetic Physics 0
Ice Harvesting 5
Ice Harvesting Drone Operation 5
Ice Harvesting Drone Specialization 3
Ice Processing 0
Industrial Command Ships 3
Industrial Reconfiguration 3
Industry 5
Infomorph Psychology 4
Infomorph Synchronizing 0
Information Command 0
Information Command Specialist 0
Interceptors 0
Interdictors 0
Interplanetary Consolidation 0
Invulnerability Core Operation 3
Jaspet Processing 0
Jump Drive Calibration 0
Jump Drive Operation 1
Jump Freighters 0
Jump Fuel Conservation 0
Jump Portal Generation 0
Jury Rigging 0
Kernite Processing 0
Kinetic Armor Compensation 0
Kinetic Shield Compensation 0
Laboratory Operation 0
Ladar Sensor Compensation 0
Large Artillery Specialization 0
Large Autocannon Specialization 0
Large Beam Laser Specialization 0
Large Blaster Specialization 0
Large Disintegrator Specialization 0
Large Energy Turret 0
Large Hybrid Turret 0
Large Precursor Weapon 0
Large Projectile Turret 0
Large Pulse Laser Specialization 0
Large Railgun Specialization 0
Laser Physics 0
Launcher Rigging 0
Leadership 5
Light Drone Operation 3
Light Fighters 0
Light Missile Specialization 0
Light Missiles 0
Logistics Cruisers 0
Logistics Frigates 0
Long Distance Jamming 0
Long Range Targeting 3
Magnetometric Sensor Compensation 0
Marauders 0
Margin Trading 0
Marketing 0
Mass Production 5
Mass Reactions 0
Mechanical Engineering 0
Mechanics 3
Medium Artillery Specialization 0
Medium Autocannon Specialization 0
Medium Beam Laser Specialization 0
Medium Blaster Specialization 0
Medium Disintegrator Specialization 0
Medium Drone Operation 3
Medium Energy Turret 0
Medium Hybrid Turret 0
Medium Precursor Weapon 0
Medium Projectile Turret 0
Medium Pulse Laser Specialization 0
Medium Railgun Specialization 0
Megacorp Management 0
Mercoxit Processing 4
Metallurgy 4
Micro Jump Drive Operation 0
Mining 5
Mining Barge 5
Mining Connections 0
Mining Director 5
Mining Drone Operation 5
Mining Drone Specialization 3
Mining Foreman 5
Mining Frigate 5
Mining Upgrades 4
Minmatar Battlecruiser 0
Minmatar Battleship 0
Minmatar Carrier 0
Minmatar Core Systems 0
Minmatar Cruiser 0
Minmatar Defensive Systems 0
Minmatar Destroyer 0
Minmatar Dreadnought 0
Minmatar Drone Specialization 0
Minmatar Encryption Methods 0
Minmatar Freighter 0
Minmatar Frigate 0
Minmatar Industrial 0
Minmatar Offensive Systems 0
Minmatar Propulsion Systems 0
Minmatar Starship Engineering 0
Minmatar Strategic Cruiser 0
Minmatar Tactical Destroyer 0
Minmatar Titan 0
Missile Bombardment 0
Missile Launcher Operation 1
Missile Projection 0
Molecular Engineering 0
Motion Prediction 2
Nanite Engineering 0
Nanite Interfacing 0
Nanite Operation 0
Navigation 5
Negotiation 0
Neurotoxin Control 0
Neurotoxin Recovery 0
Nuclear Physics 0
ORE Freighter 3
ORE Industrial 3
Offensive Subsystem Technology 0
Omber Processing 0
Outpost Construction 0
Plagioclase Processing 0
Planetology 0
Plasma Physics 0
Power Grid Management 5
Precursor Battleship 0
Precursor Cruiser 0
Precursor Frigate 0
Procurement 0
Projectile Weapon Rigging 0
Propulsion Jamming 1
Propulsion Subsystem Technology 0
Pyroxeres Processing 0
Quantum Physics 0
Radar Sensor Compensation 0
Rapid Firing 2
Rapid Launch 0
Rare Moon Ore Processing 4
Reactions 0
Recon Ships 0
Remote Armor Repair Systems 0
Remote Hull Repair Systems 0
Remote Reactions 0
Remote Sensing 0
Repair Drone Operation 0
Repair Systems 3
Reprocessing 5
Reprocessing Efficiency 5
Research 0
Research Project Management 0
Resistance Phasing 0
Retail 0
Rocket Science 0
Rocket Specialization 0
Rockets 0
Salvage Drone Operation 0
Salvaging 3
Science 5
Scientific Networking 0
Scordite Processing 0
Scrapmetal Processing 0
Security Connections 0
Sensor Linking 0
Sentry Drone Interfacing 3
Sharpshooter 2
Shield Command 0
Shield Command Specialist 0
Shield Compensation 0
Shield Emission Systems 5
Shield Management 5
Shield Operation 5
Shield Rigging 0
Shield Upgrades 4
Signal Dispersion 0
Signal Suppression 0
Signature Analysis 3
Signature Focusing 0
Skirmish Command 0
Skirmish Command Specialist 0
Sleeper Encryption Methods 0
Sleeper Technology 0
Small Artillery Specialization 0
Small Autocannon Specialization 0
Small Beam Laser Specialization 0
Small Blaster Specialization 0
Small Disintegrator Specialization 0
Small Energy Turret 0
Small Hybrid Turret 3
Small Precursor Weapon 0
Small Projectile Turret 0
Small Pulse Laser Specialization 0
Small Railgun Specialization 0
Social 1
Sovereignty 0
Spaceship Command 5
Spatial Phenomena Generation 0
Spodumain Processing 0
Starbase Defense Management 0
Structure Doomsday Operation 0
Structure Electronic Systems 0
Structure Engineering Systems 0
Structure Missile Systems 0
Supply Chain Management 0
Support Fighters 0
Surgical Strike 1
Survey 3
Tactical Logistics Reconfiguration 0
Tactical Shield Manipulation 5
Tactical Weapon Reconfiguration 0
Takmahl Technology 0
Talocan Technology 0
Target Breaker Amplification 0
Target Management 3
Target Navigation Prediction 0
Target Painting 0
Thermal Armor Compensation 0
Thermal Shield Compensation 0
Thermodynamics 1
Torpedo Specialization 0
Torpedoes 0
Trade 2
Trajectory Analysis 1
Transport Ships 0
Tycoon 0
Ubiquitous Moon Ore Processing 3
Uncommon Moon Ore Processing 4
Veldspar Processing 0
Visibility 0
Warhead Upgrades 0
Warp Drive Operation 5
Weapon Destabilization 0
Weapon Disruption 0
Weapon Upgrades 4
Wholesale 0
Wing Command 0
XL Cruise Missile Specialization 0
XL Cruise Missiles 0
XL Torpedo Specialization 0
XL Torpedoes 0
Yan Jung Technology 0

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Rorqual, Rorqual copy]

Reactor Control Unit II
Power Diagnostic System II
Capacitor Flux Coil II
Damage Control II

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
Drone Navigation Computer II
Drone Navigation Computer II
Drone Navigation Computer II
Drone Navigation Computer II

Industrial Core I
Mining Foreman Burst II, Mining Laser Optimization Charge
Mining Foreman Burst II, Mining Equipment Preservation Charge
Mining Foreman Burst II, Mining Laser Field Enhancement Charge
Cynosural Field Generator I
Large YF-12a Smartbomb
Pulse Activated Nexus Invulnerability Core
[Empty High slot]

Capital Anti-EM Screen Reinforcer I
Capital Anti-EM Screen Reinforcer I
Capital Anti-Thermal Screen Reinforcer I

'Excavator' Ice Harvesting Drone x5

### Release or development git branch? Please note the release version or commit hash:
v2.1.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
windows 10

**Comment by blitzmann** [comment]
Thanks for this info, and for the skill listing!

These are the things affecting the drone''s velocity:

![image](https://user-images.githubusercontent.com/3904767/40817134-afce592e-651e-11e8-8513-1261e5d84c54.png)

Make sure that in game your industrial core is ON when comparing it to pyfa's values (or, set the core to OFF in pyfa). Turning the core off in pyfa produces a speed of 248m/s; closer, but slightly lower than your reported value.

Can you double check the various modules activated on your ship in game and make sure those are reflected correctly in pyfa? Screenshots of the fitting window help, as well as a screenshot of the `Show Info` for the drone showing it's boosted velocity attribute.

**Comment by blitzmann** [comment]
@BikerGitHub Can you please double check values in game as per the last comment? It might be easier to test in SISI so that you can activate any modules required and view the stats in a less hostile environment :)

**Comment by blitzmann** [comment]
@BikerGitHub Really need some confirmation here, otherwise I'm going to have to close this issue as I can't reproduce myself (I don't own a Rorqual ☹️ )

**Comment by blitzmann** [comment]
@BikerGitHub I'm gonna have to close this issue as I'm almost sure it may have something to do with the modules that you had active at the time. If you would like to test again and report back, would be happy to reopen and investigate if there truely is a problem. But I don't have a Rorqual, nor can I fly one, so I cannot personally test. :/
