### ISSUE TITLE
Inconsistent new tab behavior when importing from clipboard

### ISSUE THREAD

**Issue by austin-whittington** [pyfa-org/Pyfa#163]
If you have a tab with a saved fit open, using Ctrl-V to import a fit replaces the current tab with the import fit. 
![image](https://cloud.githubusercontent.com/assets/7832905/4102657/98103cbe-3136-11e4-955b-5ac6e4dc6ae6.png)
![image](https://cloud.githubusercontent.com/assets/7832905/4102661/a85526ca-3136-11e4-85af-4037ec7a2c89.png)

However, if you open a new tab before importing, using Ctrl-V makes another new tab instead of filling the new tab you just made. 
![image](https://cloud.githubusercontent.com/assets/7832905/4102662/b3151764-3136-11e4-91c7-0ee275a1c0d3.png)
![image](https://cloud.githubusercontent.com/assets/7832905/4102664/bbe4c966-3136-11e4-8b00-75fd1bd6e902.png)

**Comment by DarkFenX** [comment]
It opens fits in new tabs for me now. I couldn't reproduce the issue. Reopen if still actual.
