### ISSUE TITLE
Cannot import EVE API XML character files

### ISSUE THREAD

**Issue by fsufitch** [pyfa-org/Pyfa#1631]
### Expected behavior:

Using `File > Import Character File` and giving it an XML character file successfully imports it as a character to use with fittings.

### Actual behavior:

Nothing happens. The logs show nothing.

### Detailed steps to reproduce:

1. Get the XML file inside this ZIP: [Minmatar Starter.zip](https://github.com/pyfa-org/Pyfa/files/2073337/Minmatar.Starter.zip).
2. Start Pyfa
3. `File > Import Character File` and select the XML file.
4. Observe as nothing happens.

### Release or development git branch? Please note the release version or commit hash:

![image](https://user-images.githubusercontent.com/4542769/40991913-390e1312-68c3-11e8-87f5-b1e3d40f8827.png)

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10 Professional, Version 1803, Build 17134.48

**Comment by blitzmann** [comment]
![image](https://user-images.githubusercontent.com/3904767/40992344-8a97f490-68c4-11e8-9f19-1dacd5772f48.png)

lol

I did this when stripping out EVE XML stuff, commented this out so that I could evaluate later. later never came.

Should be easy enough to fix this though

**Comment by WatchMeCalculate** [comment]
Was looking into this a bit and saw that import is also failing on this particular xml file with `xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 1`

**Comment by WatchMeCalculate** [comment]
Well barring the return statement in run(), there were some issues with the xml. Loading it into an interpreter it had some funky unicode going on `'ï»¿<?xml version="1.0"?>`  After sanitizing that it appeared that saveddata/character.py was missing apiUpdateCharSheet.

**Comment by blitzmann** [comment]
Merged in the fix from @WatchMeCalculate, thanks!

**Comment by fsufitch** [comment]
Closing this since it's fixed.

**Comment by blitzmann** [comment]
I actually like to keep these things open until a release is made. helps with writing up the changelog, and also shows people on current release that this known issue has been addressed :D

**Comment by fsufitch** [comment]
Roger, my bad :)
