### ISSUE TITLE
AttributeError: 'FittingView' object has no attribute 'FVsnapshot'

### ISSUE THREAD

**Issue by surculus12** [pyfa-org/Pyfa#1633]
### Expected behavior:
N/A

### Actual behavior:
N/A

### Detailed steps to reproduce:
Happens randomly when I'm doing something. (i.e. seems triggered when I'm doing things like turning on modules or looking at a module's market group, but seemingly no actual pattern or specific trigger.)

### Fits involved in EFT format (Edit > To Clipboard > EFT):
Has happened fit-independent, but here is what was open last time it happened:

```
[Confessor, Pulse probes]
Nanofiber Internal Structure II
Nanofiber Internal Structure II
Small Ancillary Armor Repairer, Nanite Repair Paste
Heat Sink II
Heat Sink II

5MN Quad LiF Restrained Microwarpdrive
Warp Disruptor II
Stasis Webifier II

Sisters Expanded Probe Launcher, Sisters Combat Scanner Probe
Small Focused Pulse Laser II, Scorch S
Small Focused Pulse Laser II, Scorch S
Small Focused Pulse Laser II, Scorch S
Small Focused Pulse Laser II, Scorch S
[Empty High slot]

Small Energy Locus Coordinator II
[Empty Rig slot]
[Empty Rig slot]
```

```
[Confessor, App.14]

Heat Sink II
Heat Sink II
Nanofiber Internal Structure II
Nanofiber Internal Structure II
Small Ancillary Armor Repairer, Nanite Repair Paste

5MN Cold-Gas Enduring Microwarpdrive
Stasis Webifier II
Warp Disruptor II

[Empty High slot]
[Empty High slot]
Small Focused Beam Laser II, Imperial Navy Multifrequency S
Small Focused Beam Laser II, Imperial Navy Multifrequency S
Small Focused Beam Laser II, Imperial Navy Multifrequency S
Small Focused Beam Laser II, Imperial Navy Multifrequency S

Small Ancillary Current Router I
Small Energy Locus Coordinator II
Small Energy Locus Coordinator II
```

```
[Vagabond, Red Kardia's Vagabond]

Assault Damage Control II
Capacitor Flux Coil II
Capacitor Flux Coil II
Capacitor Flux Coil II
Capacitor Flux Coil II

Caldari Navy Warp Scrambler
Gist X-Type Large Shield Booster
Gist X-Type Large Shield Booster
Gistum A-Type 10MN Afterburner

Corpii A-Type Small Energy Nosferatu
425mm AutoCannon II, Republic Fleet EMP M
425mm AutoCannon II, Republic Fleet EMP M
425mm AutoCannon II, Republic Fleet EMP M
425mm AutoCannon II, Republic Fleet EMP M
425mm AutoCannon II, Republic Fleet EMP M

Medium Capacitor Control Circuit II
Medium Capacitor Control Circuit II
```

### Release or development git branch? Please note the release version or commit hash:
v2.1.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
OS version: Windows-10-10.0.15063-SP0

### Other relevant information:
```
OS version: Windows-10-10.0.15063-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\chrome_tabs.py", line 1292, in OnTimer
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinViews\fittingView.py", line 724, in Snapshot
AttributeError: 'FittingView' object has no attribute 'FVsnapshot'
```

**Comment by blitzmann** [comment]
Thanks for the info!

This happens during the `MakeSnapshot` function (which is what builds the window when hovering over a tab that you don't have active). It's not really impeding calculations or anything, it's purely a GUI bug, although not one that's I've run into.

The whole `MakeSnapshot` thing should probably be evaluated in depth and improved in general (do people even still use it??)

**Comment by surculus12** [comment]
Ah yeah, I can consistently reproduce it by hovering over (some, but not all) tabs.

Looking at `MakeSnapshot`, this seems to be caused by the first two lines:
```
[...]
        if self.FVsnapshot:
            del self.FVsnapshot
[...]
```
Instead of deleting the attribute, setting it back to `None` should fix this issue. Is there a particular reason it's deleted? (I can't see one at a glance.)

**Comment by blitzmann** [comment]
> Instead of deleting the attribute, setting it back to None should fix this issue. Is there a particular reason it's deleted? (I can't see one at a glance.)

**Comment by blitzmann** [comment]
Thanks for the PR! I've merged it into master. Indeed, it doesn't fix the root error, but at least it should fix the user's perception of it. If it doesn't generate for some reason, then oh well. Like I said, need to look into that code more deeply at some point.
