### ISSUE TITLE
Crucifier Navy Issue falloff penalty missing

### ISSUE THREAD

**Issue by croikle** [pyfa-org/Pyfa#1635]
## Bug Report

The Crucifier Navy Issue's -85% penalty to Weapon Disruptor falloff doesn't appear to be applied, although the penalty to optimal range is.

### Expected behavior:

0 skill character with Tracking Disruptor I on Crucifier Navy Issue has range 6 km + 3 km.

### Actual behavior:

0 skill character with Tracking Disruptor I on Crucifier Navy Issue has range 6 km + 20 km.

### Detailed steps to reproduce:

1. Create a Crucifier Navy Issue fit with a Tracking Disruptor I.
2. Set the Character preset to "All 0".
3. Observe the listed range.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

~~~
[Crucifier Navy Issue, xxx]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

Tracking Disruptor I
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]
~~~

### Release or development git branch? Please note the release version or commit hash:

v2.1.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

OS X 10.13

**Comment by blitzmann** [comment]
Huh, looks like we're trying to change the `falloff` attribute, and not the `falloffEffectiveness` attribute... Will take a look at this, thanks!

**Comment by blitzmann** [comment]
Hmm, doesn't seem to have been a big problem, just with this effect
