### ISSUE TITLE
Export HTML Option

### ISSUE THREAD

**Issue by rinakondur** [pyfa-org/Pyfa#1637]
Not really a bug since Osmium is dead (RIP) but the Export HTML option obviously no longer works as intended. Would it be possible to adjust the export feature to just export it to an HTML block listing the fits with collapsible spoilers? I'm almost positive I'm about the only person wanting this but it could be useful for keeping a website available of doctrine fits and such. Would make my life easier just exporting a file to update things instead of copying and pasting everything over. Not a huge deal, just an idea. Keep up the good work!

**Comment by burnsypet** [comment]
Do you want it to keep the current collapsible layout, but rather than linking to Osmium just display an EFT block instead?

I think that would be fairly straightforwards to do.

**Comment by rinakondur** [comment]
I like the collapsible layout. If it just expanded to show the EFT block that'd be great.

**Comment by blitzmann** [comment]
Hi @rinakondur!

Sorry, thought I replied to this. Agreed, the HTML export is i need of some work. Also agreed that you might be one of the only people who has noticed 😛 

@burnsypet sounds like a decent plan, just use a styled `<pre>` tag that shows the EFT fit. We could expand on this and show the fit as a styled list format and have the EFT block available, would be more work though.

**Comment by burnsypet** [comment]
Looks something like this now:

![image](https://user-images.githubusercontent.com/6990224/41247787-0bccfff6-6da7-11e8-89a1-67332a0a3da3.png)

**Comment by rinakondur** [comment]
Perfect! Exactly what I was picturing in my mind.

**Comment by blitzmann** [comment]
@burnsypet look great! lease submit a PR so I can include it into master :)

**Comment by blitzmann** [comment]
PR submitted and merged, thanks @burnsypet!

I forgot to include this with the recent pre-release build :( if you need a build, let me know and I can get one for you including this change :)
