### ISSUE TITLE
Abyssal Modules: Can't handle import/export

### ISSUE THREAD

**Issue by DinKartay** [pyfa-org/Pyfa#1641]
edit by @blitzmann: Import/export of fits with abyssal modules fail across the board for all formats (EFT, ESI, etc). Need to test these.

---

### Expected behavior:
Right-clicking abyssal modules in a copied fit should yield the option "Revert to <base module type>", and viewing the module stats should yield the tab with which one can modify the relevant (mutaplasmid) attributes.

### Actual behavior:
Neither of the aforementioned options appear.

### Detailed steps to reproduce:

- Create a new fit for any ship.
- Fit a module that you can mutate, and do so (right-click, apply mutaplasmid). Modify one or more attributes.
- Create a copy of the fit (green plus).

- Note the correctly named abyssal module in the copy (e.g. "5mn Abyssal Microwarpdrive")
- Note that the stats applied to the module (e.g. speed boost %) are equal to the unmodified base module's.
- Note that right-clicking the copied module does not allow the removal of the mutaplasmid (or the addition of one).

### Release or development git branch? Please note the release version or commit hash:
v2.2.0b1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:

**Comment by blitzmann** [comment]
There isn't really a good way to handle exporting / importing abyssal modules, at least in the EFT format. That format just doesn't store that information. I could give it that information, but then we run the risk of breaking other programs that may use that format. Could also consider a pyfa-specific format. Similar to https://github.com/pyfa-org/Pyfa/issues/1597#issuecomment-396968079

I think the short term fix would be to use the base module in exports and imports. Maybe later try to get a window to pop up when trying to import an abyssal module to edit the values, or at least notify the user that they need to edit it.

**Comment by blitzmann** [comment]
Additionally, as a catch all, if you have a module that is an abyssal module, but no base item or mutaplasmid associated with it, it could be invalidated and removed from the fit as it's essentially vestigial at that point.

**Comment by blitzmann** [comment]
So I've implemented invalidation of modules that are imported without the proper data. In this case, if you're trying to import an Abyssal module from EFT, it's simply going to ignore it since it doesn't know what to do with it. As of right now, we do export with this data simply to show that there is a module there.

For now this will work. Of course, this could be expanded upon in the future if there's a demand for it to allow us to prompt the user for the information we require when importing, but this could be tricky with the threaded imports.
