### ISSUE TITLE
Abyss: Activation time/duration values in the 'mutaplasmid' module stats tab are displayed in ms with the suffix "s"

### ISSUE THREAD

**Issue by DinKartay** [pyfa-org/Pyfa#1642]
### Detailed steps to reproduce:

- Create a new fit
- Fit a module that can have it's cycle time modified by a mutaplasmid (e.g. an armor repairer)
- Apply a mutaplasmid to the module.
- Right-click, show module info, and open the mutaplasmid tab.
- Observe the values for cycle time being presented as seconds (s) but being equivalent to the actual values in milliseconds (ms).

### Release or development git branch? Please note the release version or commit hash:
v2.2.0b1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:

![image](https://user-images.githubusercontent.com/3904767/41377386-dc162c22-6f29-11e8-99b3-c137e706e7d1.png)

Affected mutaplasmid 'types' (by module type they apply to):
- Energy Neutralizers
- Armor Repairers
- Shield Boosters
- Ancillary Armor Repairers
- Ancillary Shield Boosters

**Comment by blitzmann** [comment]
Huh, nice find! Also don't know how I'm going to fix that. The suffixes come from ccp themselves. Could be a few unit conversions that I'm failing to do. Will have to take a look, thanks!

**Comment by blitzmann** [comment]
Ah, indeed, the unit needs a bit of tweaking. We do this here in the attributes tab: https://github.com/pyfa-org/Pyfa/blob/6fdcce12a36442e5180bc849eb9afbe8db6afa41/gui/builtinItemStatsViews/itemAttributes.py#L240

Hrm... will try to move this logic to the attribute itself.

**Comment by blitzmann** [comment]
Currently working on this on branch origin/issue/1642, it's not completely done and will require a bit more testing to make sure everything displays / saves properly.

**Comment by blitzmann** [comment]
Done! 

![image](https://user-images.githubusercontent.com/3904767/41451655-07fdd2be-703c-11e8-8c7e-6ef7de40a04f.png)

We now display a converted value that represents the unit, and store the inverse on the attribute. Works well!

Thanks for bringing this to my attention! :D
