### ISSUE TITLE
Automatically create custom steps for abyssal attribute input

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1648]
Currently, the value inputs step by 1. Need to figure out a way to step by different orders of magnitude, depending on the magnitude of the attribute value itself.

For example, attribute value is 45000, step should (probably) be, 100. Attributes is 0.3154, step should (probably) be 0.001.

**Comment by blitzmann** [comment]
@burnsypet not really sure there's going to be a good way to solve that, unfortunately. It's either we keep the increment the same and one side reaches the end faster, or we change increments based on which "side" we're on to keep the same number of increments.

I feel like the second option would be a bad idea - as a user, I expect the increment to stay the same regardless. Users will just have to understand that one side is "larger" than the other due to the skew. 

If you can please make a PR for that, I'l like to test it out and include it! :)

**Comment by blitzmann** [comment]
@burnsypet if you could make a PR for your suggestion, I can take a look at it this weekend and get it merged in. :)

**Comment by blitzmann** [comment]
@burnsypet any progress on this piece? I don't want to step on your toes if you still have this branch out there somewhere, and want you to get the credit for it if you're planning on submitting a PR for it. Let me know so I know where this issue lies :)

**Comment by DarkFenX** [comment]
Just realized that I implemented it a while ago, in ae23fba6b79bed314d59233c2ed19fe27d415b23

**Comment by DarkFenX** [comment]
Closing as it has been out for a few releases already
