### ISSUE TITLE
Pyfa 2.1.1, linux, Graph disabled

### ISSUE THREAD

**Issue by Morkal** [pyfa-org/Pyfa#1655]
Hello
pyfa 2.1.1 , 
linux
Python 3.6.5
Successfully installed cycler-0.10.0 matplotlib-2.0.0 numpy-1.11.0 pyparsing-2.2.0 python-dateutil-2.7.3 pytz-2018.4 six-1.10.0

Pyfa working well
But Graph option is disabled all the time

No errors in log, just 

> sqlite:////home/User/.pyfa/saveddata.db?check_same_thread=False
> sqlite:////home/User/Apps/pyfa/eve.db?check_same_thread=False
> Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by blitzmann** [comment]
I'm assuming you figured this out, yeah? What was the reason?

**Comment by Morkal** [comment]
Not yet, still investigation.
I found 3 different version of python on my linux work machine.
Running pyfa from console like python3.6 pyfa.py
So first i think i installed matplotlib to wrong version of python and close issue to not waste time
Also foind in logs:
WARNING: gui.graphFrame: Matplotlib failed to import.  Likely missing or incompatible version. 

I try to reinstall matplotlib with no success, maybe need complete reinstall of python3.6. 
Now just delayed thurther investigation because not have enough free time,
