### ISSUE TITLE
Factor in reload time setting needs Pyfa restarted to take effect

### ISSUE THREAD

**Issue by SubjectXXX** [pyfa-org/Pyfa#1656]
## Bug Report
Factor in reload time on capacitor usage, damage and tank in Fitting engine section of preferences  does not apply instantly, client needs to be restarted. Reopening fitting does not help.

Is this intentional?

### Expected behavior:
When OK is clicked when changing this setting, open fittings should be updated to reflect this change.

### Actual behavior:
Client needs to be restarted for setting to take effect.

### Release or development git branch? Please note the release version or commit hash:
v2.1.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win10

**Comment by SubjectXXX** [comment]
Also v2.2.0b1

**Comment by blitzmann** [comment]
Hrm, will need to check this out. I don't think it's intentional. Thanks for bringing this up :)

**Comment by malleusmintaka** [comment]
activating/deactivating/changing/... of a module on the fit (doesn't have to be one changing the stat, e.g. damage control for rapid lights) works aswell

**Comment by blitzmann** [comment]
This slipped off the radar, but got this it fixed! 🤘
