### ISSUE TITLE
Unable to close item stats window on linux

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1657]
1. Open stats window for any item from currently open fit
2. Attempt to close it with Close button (not window manager's close button)
3. Attempt to close it again

Window is not closed on both attempts. 2nd attempt produces following output:
```
OS version: Linux-4.16.0-1-amd64-x86_64-with-debian-buster-sid
Python version: 3.6.6rc1 (default, Jun 13 2018, 06:59:48) 
[GCC 8.1.0]
wxPython version: 4.0.1 (wxWidgets 3.0.4)
SQLAlchemy version: 1.2.8
Logbook version: 1.3.3
Requests version: 2.18.4
Dateutil version: 2.6.1

####################

Traceback (most recent call last):
  File "/home/dfx/src/eve/pyfa/gui/itemStats.py", line 148, in closeEvent
    self.parentWnd.UnregisterStatsWindow(self)
  File "/home/dfx/src/eve/pyfa/gui/mainFrame.py", line 333, in UnregisterStatsWindow
    self.statsWnds.remove(wnd)
ValueError: list.remove(x): x not in list
```
Closing via window manager's close button works as intended.

Bisect blames following commit: 47016c682e1cc1eb96d1c3d455ca223f5add0ca7

**Comment by MaruMaruOO** [comment]
Should be fixed with #1666.
The event.Skip() in 47016c6 only triggers an additional handler for the event rather than deleting the window directly.
Thus the patch binds the close button so triggers an actual close event.

**Comment by blitzmann** [comment]
Nice catch to both of you. Thanks for the fix @MaruMaruOO!

**Comment by andrewd18** [comment]
The fix for this does not have valid syntax. PyFA now crashes on load.

> OS version: Linux-4.17.4-1-ARCH-x86_64-with-arch-Arch-Linux
> Python version: 3.6.6 (default, Jun 27 2018, 13:11:40) 
> [GCC 8.1.1 20180531]
> wxPython version: 4.0.1 (wxWidgets 3.0.4)
> SQLAlchemy version: 1.2.9
> Logbook version: 1.4.0
> Requests version: 2.19.1
> Dateutil version: 2.7.3
> 
> ####################
> 
> Traceback (most recent call last):
>   File "/home/andrew/bin/Pyfa/pyfa.py", line 131, in <module>
>     from gui.mainFrame import MainFrame
>   File "/home/andrew/bin/Pyfa/gui/mainFrame.py", line 45, in <module>
>     from gui.mainMenuBar import MainMenuBar
>   File "/home/andrew/bin/Pyfa/gui/mainMenuBar.py", line 26, in <module>
>     import gui.graphFrame
>   File "/home/andrew/bin/Pyfa/gui/graphFrame.py", line 27, in <module>
>     import gui.display
>   File "/home/andrew/bin/Pyfa/gui/display.py", line 23, in <module>
>     from gui.viewColumn import ViewColumn
>   File "/home/andrew/bin/Pyfa/gui/viewColumn.py", line 70, in <module>
>     from gui.builtinViewColumns import (  # noqa: E402, F401
>   File "/home/andrew/bin/Pyfa/gui/builtinViewColumns/baseName.py", line 33, in <module>
>     from gui.builtinContextMenus.whProjector import WhProjector
>   File "/home/andrew/bin/Pyfa/gui/builtinContextMenus/whProjector.py", line 1, in <module>
>     from gui.contextMenu import ContextMenu
>   File "/home/andrew/bin/Pyfa/gui/contextMenu.py", line 182, in <module>
>     from gui.builtinContextMenus import (  # noqa: E402,F401
>   File "/home/andrew/bin/Pyfa/gui/builtinContextMenus/itemStats.py", line 2, in <module>
>     from gui.itemStats import ItemStatsDialog
>   File "/home/andrew/bin/Pyfa/gui/itemStats.py", line 105
>     self.closeBtn.Bind(wx.EVT_BUTTON, (lambda e: self.Close())))
>                                                                ^
> SyntaxError: invalid syntax
>

**Comment by blitzmann** [comment]
@andrewd18 thanks! Should be fixed now

**Comment by andrewd18** [comment]
Confirming Pyfa loads and the item window is now closable on Linux. Thanks!

**Comment by DarkFenX** [comment]
Thanks guys!
