### ISSUE TITLE
CPU Implants Not Applying

### ISSUE THREAD

**Issue by shadowclaw** [pyfa-org/Pyfa#1658]
## Bug Report
CPU implants don't seem to be applying correctly

### Expected behavior:
My character has CPU Management at lvl 5 and the Zainou 'Gypsy' CPU Management EE-601 implant.
The CPU output multiplier listed in the "Affected By" tab in the Ship Stats should be higher than 1.25

### Actual behavior:
Removing/Adding the implant doesn't change the CPU output of the ship

The ship has a base output 240, In game the simulated output is 317.89 but in pyfa the output is 300

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Covetor, Covetor Group Mining]

Mining Laser Upgrade II
Mining Laser Upgrade II
Mining Laser Upgrade II

Limited Adaptive Invulnerability Field I

Strip Miner I
Strip Miner I

Medium Anti-EM Screen Reinforcer I
Medium Anti-EM Screen Reinforcer I
Medium Anti-Thermal Screen Reinforcer I

Acolyte II x5

### Release or development git branch? Please note the release version or commit hash:
v2.1.1 EVE Data Version 1321734

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 7 Pro x64

**Comment by burnsypet** [comment]
Hey man when I try this on my Pyfa installation I can see the affected by value of the implant in the ship stats:

![image](https://user-images.githubusercontent.com/6990224/41854522-58220d6a-7888-11e8-83b6-2bdd7502c105.png)

The CPU Output is calculated as 240 * 1.25 = 300 * 1.01 = 303. I'm not sure where your in game value of 317.89 is from, the only way I can get close to that in Pyfa is with a 6% implant which comes out as 318, or with a full set of Genolutions plugged in as well. Can you check to make sure you don't have any other implants activated in game that might be giving you a CPU bonus?

**Comment by shadowclaw** [comment]
Sorry I forgot about the Genolution set giving a CPU bonus.  I do have the full set both in game and in pfya.
In that ship stats windows the only one I see is the CPU Management Skill.  The only non-skill items are the two Rigs and the shield mod.

**Comment by burnsypet** [comment]
That's odd, can you see it with a green tick in the implants tab below the fittings window?

![image](https://user-images.githubusercontent.com/6990224/41856572-4f9222de-788d-11e8-9252-4615553189ce.png)

**Comment by shadowclaw** [comment]
At work right now but I will check this later tonight.  Also if there are any other logs or anything that would make this easier let me know and I can get them at the same time.

**Comment by shadowclaw** [comment]
Alright so this looks like it was a user error the whole time.  The "Use Fit-specific implants" option was selected.  When I changed it to "Use Character Implants" everything seems to be working.  Is there a way to make the "Use Character Implants" option the default for new fits?  Also is there an easy way to change all of the existing fits to that? (I assume this can be done by editing the database but I haven't really looked at it in any detail)

**Comment by blitzmann** [comment]
> Is there a way to make the "Use Character Implants" option the default for new fits?

Not currently, but I can see that being a thing.

> Also is there an easy way to change all of the existing fits to that? (I assume this can be done by editing the database but I haven't really looked at it in any detail)

Not within pyfa, but you can absolutely use a sqlite editor to do this. the `fits.implantLocation` column is either a `0` (fir fit-specific) or `1` for character implants :P

If you're not able to edit it yourself, send it over to me at sable.blitzmann@gmail.com (and let me know here that you've sent it, it's not an email I check often). The file is usually `%userprofile%/.pyfa/saveddata.db`. I can quickly update all records in the table to go off of character implants. :)

**Comment by blitzmann** [comment]
@shadowclaw #1667 made in your honor 😛 

gonna close this issue as it's a non-issue \o/

**Comment by shadowclaw** [comment]
Cool, thanks.  I can edit the DB myself, I just wasn't sure what to edit.  This also explains why a lot of my other fits don't quite match in game. :smile:
