### ISSUE TITLE
Setting to determine default implant location for new fits

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1667]
From #1658

Should look into adding a setting in the preferences to allow the user to select Fit or Character implant locations to be the default for new fits.

**Comment by blitzmann** [comment]
Adding a `help wanted` flag. This is low-hanging fruit item and I think could be a good start fopr someone interested in working it. If you plan to work it, please let me know here. Otherwise, I will get to this as I can. :)

**Comment by MaruMaruOO** [comment]
Working on this, I should have something up within the next day.

**Comment by MaruMaruOO** [comment]
Added a possible implementation with #1668 
Feel free to shorten the UI string or variable names if you find them too verbose.
We may want to keep an eye on putting too many check boxes in general preferences going forward but 
I don't think it's quite a problem yet.

I've also made the implant location persistent when copying fits, although I can easily change it back if desired.
On that note I have a patch in the works to improve fit copying. I'll post about it tomorrow to work out exactly what people do/don't want copied.

**Comment by blitzmann** [comment]
Looks like a good patch 👍 I'm okay with the working for now, will test this out and get it included before the next release (been delayed by a few days - there's an issue with CCPs data in TQ regarding mutaplasmid that I'm waiting on them to fix)

> On that note I have a patch in the works to improve fit copying. I'll post about it tomorrow to work out exactly what people do/don't want copied.

I would assume a copy is just that - a literal copy of the fit with as much duplicated as we can? <_<

**Comment by MaruMaruOO** [comment]
> I would assume a copy is just that - a literal copy of the fit with as much duplicated as we can? <_<
Fair point, I've submitted #1671 which I think catches everything.
Should make messing around with carrier/super/fleet fits involve far less clicking.
