### ISSUE TITLE
Error when adding new charaters

### ISSUE THREAD

**Issue by tozo** [pyfa-org/Pyfa#1672]
### Expected behavior:
Being able to add new characters to Pyfa

### Actual behavior:
In the SSO Character Management window, when I click on "Add character", it displays the exception below:
```
OS version: Windows-7-6.1.7601-SP1
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\esiFittings.py", line 331, in addChar
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 111, in login
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 129, in startServer
  File "C:\Python36\lib\socketserver.py", line 453, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\server.py", line 113, in server_bind
  File "C:\Python36\lib\socketserver.py", line 467, in server_bind
OSError: [WinError 10049] The requested address is not valid in its context
```
The path `C:\Users\holme\` looks strange, since that doesn't exist on my machine.

### Detailed steps to reproduce:
Open Pyfa, click EVE SSO -> Manage Characters -> Add Charater

### Fits involved in EFT format (Edit > To Clipboard > EFT):
No fits, it's a new installation

### Release or development git branch? Please note the release version or commit hash:
Version 2.1.1.

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 7

### Other relevant information:
I tried both the zip and installer version they both threw the same exception.

ps: I saw there is another issue about character creation, but since that's a different problem I opened a new one.

**Comment by tozo** [comment]
Thanks, it worked!

**Comment by blitzmann** [comment]
The next release will include an error message with details on enabling manual mode whenever an error like this occurs. Gonna close this issue :)

**Comment by PHSashaQuetzalcoatl** [comment]
Hi!, sorry for the bother, im having "kinda" the same problem,
It sends me from "Managing settings > Authorize > Copy and paste the code" to this (I already tried auto the method but nothing happens):
![image](https://user-images.githubusercontent.com/46877148/51447727-87541080-1ce6-11e9-933d-d3d07eb40d98.png)
![image](https://user-images.githubusercontent.com/46877148/51447733-8f13b500-1ce6-11e9-8002-75596a588b32.png)

**Comment by blitzmann** [comment]
@PHSashaQuetzalcoatl Hi there! Sorry for the very late reply, must have missed this. This problem is due to an outdated pyfa. Lots of people had this issue because our update notification broke lol. Please update to the latest pyfa and you should be able to sign on again :)
