### ISSUE TITLE
Cap battery mutaplasmid error

### ISSUE THREAD

**Issue by NomadThanatos** [pyfa-org/Pyfa#1673]
### Expected behavior:
Open mutaplasmid stats UI

### Actual behavior:
Error

### Detailed steps to reproduce:
1. Get any cap battery fit on a ship.
2. Apply mutaplasmid.
3. Module stats.
4. Oops, error.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Vargur, Test]

Republic Fleet Gyrostabilizer
Republic Fleet Gyrostabilizer
Republic Fleet Gyrostabilizer
Republic Fleet Gyrostabilizer
Tracking Enhancer II

Gist X-Type 500MN Microwarpdrive
Adaptive Invulnerability Field II
Sensor Booster II, Scan Resolution Script
X-Large Abyssal Shield Booster
Large Abyssal Cap Battery
Tracking Computer II, Optimal Range Script

800mm Repeating Cannon II, Republic Fleet Fusion L
800mm Repeating Cannon II, Republic Fleet Fusion L
800mm Repeating Cannon II, Republic Fleet Fusion L
800mm Repeating Cannon II, Republic Fleet Fusion L
Bastion Module I
[Empty High slot]
[Empty High slot]
[Empty High slot]

Large Capacitor Control Circuit II
Large Capacitor Control Circuit II

Warrior II x5
Hammerhead II x5

### Release or development git branch? Please note the release version or commit hash:
Version v2.3.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows-10-10.0.17134-SP0

### Other relevant information:
OS version: Windows-10-10.0.17134-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\contextMenu.py", line 138, in handler
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinContextMenus\itemStats.py", line 69, in activate
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\itemStats.py", line 99, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\itemStats.py", line 168, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinItemStatsViews\itemMutator.py", line 73, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 52, in getStaticBitmap
TypeError: StaticBitmap.SetBitmap(): argument 1 has unexpected type 'NoneType'

**Comment by MaruMaruOO** [comment]
Should be fixed with #1677 
Was caused by the game not having an icon for 'Capacitor Warfare Resistance Bonus'.

**Comment by blitzmann** [comment]
There were a few oddities in the EVE data this release.  The Small Abyssal Nos doesn't have a type name (I manually added one), and it was set to published (when it shouldn't be published according to other abyssal items). There were a few missing iconIDs from the data which required a tweak to our icon processing script, which I suspect was part of the reason for this issue.

Thanks for the bug report @NomadThanatos , as well as the quick fix @MaruMaruOO !

**Comment by blitzmann** [comment]
Ah, got it, it was the icon for the attribute, not the item itself. 👍
