### ISSUE TITLE
Importing fits from clipboard not functioning at all with v2.3.0

### ISSUE THREAD

**Issue by fspigel** [pyfa-org/Pyfa#1678]
### Expected behavior:

Pressing Ctrl+V with a valid fitting in the clipboard should load a new fitting into the client

### Actual behavior:

Nothing happens after pressing Ctrl+V 

### Detailed steps to reproduce:

1.) Find a valid fitting in EFT text format, or choose an existing fit in pyfa, press Ctrl+C, select EFT and click OK

2.) With the pyfa window selected, either press Ctrl+V, or select Edit -> From Clipboard

### Fits involved in EFT format (Edit > To Clipboard > EFT):

Any

### Release or development git branch? Please note the release version or commit hash:

Release version v2.3.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10, 64 bit

### Other relevant information:

Several other people on comms confirmed they had the same bug with v2.3.0

**Comment by blitzmann** [comment]
Duplicate #1674
