### ISSUE TITLE
EFT Clipboard fit or Importing of fittings will not work !

### ISSUE THREAD

**Issue by Bashfulmerc** [pyfa-org/Pyfa#1679]
## Bug Report
New release pyfa2.3.0

### Expected behavior:
import of file or Clipboard EFT

### Actual behavior:
file or Clipboard EFT will not load

### Detailed steps to reproduce:
did multiple attempts

### Fits involved in EFT format (Edit > To Clipboard > EFT):
EFT fit from EVE using Ctrl F > To Clipboard > Pyfa
Pyfa file import fitting and selected the proper fitting file

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 7 Professional

### Other relevant information:
The file load went into an infinite loop and nothing happened.
Had to exit from Windows using Ctrl-Delete and then Log Off to kill Windows Activity

**Comment by MarHelmer** [comment]
Chiming in to confirm this bug is new to 2.3.0 and exists on Windows 10 as well.

**Comment by blitzmann** [comment]
Duplicate #1674
