### ISSUE TITLE
CPU penalty of Mining Laser Upgrades calculates not correctly for Strip Miners 

### ISSUE THREAD

**Issue by CBon** [pyfa-org/Pyfa#1698]
## Bug Report
CPU penalty of Mining Laser Upgrades calculates not correctly for Strip Miners 

### Expected behavior:
Modulated Strip Miner II CPU = ~72 tf

### Actual behavior:
Modulated Strip Miner II CPU = 75 tf

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Mackinaw, Thick Ass]

'Carpo' Mining Laser Upgrade
Mining Laser Upgrade II
Mining Laser Upgrade II

Dread Guristas Adaptive Invulnerability Field
Dread Guristas Adaptive Invulnerability Field
Survey Scanner II
Small F-S9 Regolith Compact Shield Extender

Modulated Strip Miner II
Modulated Strip Miner II

Medium Core Defense Field Extender II
Medium Core Defense Field Extender II

### Release or development git branch? Please note the release version or commit hash:
2.3.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by blitzmann** [comment]
I have the following affecting the strip miners

![image](https://user-images.githubusercontent.com/3904767/44296208-e6b97a80-a287-11e8-892e-82cdedcef79d.png)

Are you basing your "expected" on values directly from EVE? 

I've noticed that if I remove the `Carpo` upgrade, the CPU use drops to 71.8, which could be rounded up to 72 in the game. Can you please double check your fitting in game, and also not any implants you may be using that might affect things?

If everything looks fine, then the next step I would ask is to try to get as slim a fit at possible that still shows a discrepancy between EVE and pyfa - remove all the "extra" modules that aren't affecting the CPU, and then try to see if you can narrow down which ones might be causing it.

**Comment by blitzmann** [comment]
Adding a stacking penalty to the CPU penalty gives me 72.8 per strip miner... is this what shows in the in-game showinfo for that module? If you hover over the value in game, I think it would should you the decimal places

**Comment by CBon** [comment]
![image](https://user-images.githubusercontent.com/11840574/44296268-dcb56d00-a2c3-11e8-9f16-e679476b03d6.png)

**Comment by CBon** [comment]
![image](https://user-images.githubusercontent.com/11840574/44296279-4d5c8980-a2c4-11e8-8858-64cf3ef8cd44.png)

**Comment by CBon** [comment]
2 'Carpo' and 1 MLUII...

**Comment by CBon** [comment]
Mining Updates 4

**Comment by blitzmann** [comment]
@CBon well there we go then :) You only had one carpo in the original post, and I didn't know about Mining Upgrades 4. Fixing this in pyfa shows:

![image](https://user-images.githubusercontent.com/3904767/44296295-1a959f80-a28a-11e8-88f0-4b635834f31e.png)

72.5 ~~ 72.49

Doesn't seem to be an issue, can you confirm on your end?

**Comment by CBon** [comment]
Sorry. My mistake. It's ok

**Comment by blitzmann** [comment]
No worries! Fly safe o/
