### ISSUE TITLE
Porpoise, Azbel, Raitaru, Sotiyo missing icon/image in fittings.

### ISSUE THREAD

**Issue by feyyd** [pyfa-org/Pyfa#1703]
## Bug Report
Industrial Command Ship -> Porpoise icon missing
Engineering Complex -> Azbel/Raitaru/Sotiyo icons missing

### Expected behavior:
Show Icons

### Actual behavior:
No Image icon displayed

### Release or development git branch? Please note the release version or commit hash:
2.3.1 Release

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by blitzmann** [comment]
For the porpoise, this is (probably) because the res file has a double `//` in the path:

res:/dx9/model/ship/ore/battleship/oreb1/icons//21362_64.png

**Comment by blitzmann** [comment]
Indeed, this is the reason for all the items mentioned. Nice catch :)
