### ISSUE TITLE
2.5.0b1 Always asking for update unless suppressed

### ISSUE THREAD

**Issue by feyyd** [pyfa-org/Pyfa#1711]
## Bug Report
2.5.0b1+command always asking for update (unless supressed)

### Expected behavior:
If this is latest, no update message

### Actual behavior:
Always asks to update.

### Detailed steps to reproduce:
Load pyfa

### Release or development git branch? Please note the release version or commit hash:
2.5.0b1+command

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by blitzmann** [comment]
Huh

Apparently, `v2.5.0b1+command > v2.5.0b1` according to the versioning identification we use. I never put the `+command` into the `config.py`

Hrm... gonna try to remove the `+command` from the tag then I think

**Comment by blitzmann** [comment]
There's no easy way to fix it right now unfortunately. I've already linked around to https://github.com/pyfa-org/Pyfa/releases/tag/v2.5.0b1%2Bcommand to gather feedback, If I rename the tag, that link will no longer work.

I'll add a blurp in nthe release about using the "Don't remind me again for this release" option

**Comment by blitzmann** [comment]
Gonna keep this open until another release happens, just in case someone else thinks to report it :D
