### ISSUE TITLE
2.5.0b1 redo not placing to same slot

### ISSUE THREAD

**Issue by feyyd** [pyfa-org/Pyfa#1712]
## Bug Report
Clicking redo sometimes puts module in wrong slot

### Expected behavior:
Clicking redo puts module back into the slot it was at if its still available

### Actual behavior:
Clicking redo puts module back into same slot

### Detailed steps to reproduce:
Delete an item from any fit from the top of the module list, module A
Delete another item underneath it, module B
redo -> module B is put into first available slot (module A's empty slot)
redo -> module A is put into first available slot (module B's empty slot)

### Fits involved in EFT format (Edit > To Clipboard > EFT):
all

### Release or development git branch? Please note the release version or commit hash:
2.5.0b1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
Certain fits rely on module position for heat distribution so might be prudent to preserve module slot information, and if the slot is not available on redo, then append.

**Comment by blitzmann** [comment]
Nice find!

**Comment by feyyd** [comment]
I'll leave this open til new release
