### ISSUE TITLE
Add Liquid Ozone to the list of available items

### ISSUE THREAD

**Issue by rmk2** [pyfa-org/Pyfa#172]
I was wondering whether it would be possible to add Liquid Ozone to the item list, since we have all provisions in place to add items to a ship's cargo bay. This would make it a lot easier to see whether a given ship can be used as a cyno ship, especially since the Cynosural Field Generator already has "consumptionType" and "consumptionQuality" as fields, with the latter also already calculating correctly the amount of LO needed depending on the level of Cynosural Field Theory.

This would be a first step towards adding all 4 fuel types for capital ships as well, I suppose, though I'm not sure whether that would be more involved due to the differencce between fleet hangar and fuel bay. At least LO is just straight up cargo like any other item.

**Comment by damienb** [comment]
Adding a misc group would be fine, though I'm not sure how many more categories you'd add anyway.

Having various consumables in there would be handy. Add things like Liquid Ozone, various topes.

**Comment by Nahaz** [comment]
Just want to express that having fuel available to add to fits would be handy

**Comment by fivesixzero** [comment]
It could just be added under "Ammo". Nanite Paste is already in that section. Could put Stront in there too.

**Comment by blitzmann** [comment]
Notes in #600
