### ISSUE TITLE
Bad stats for ship fitting

### ISSUE THREAD

**Issue by seraphx2** [pyfa-org/Pyfa#1726]
## Bug Report
After creating the fit listed below, it said I was .7% over my CPU limit, meaning all I needed was a 1% CPU implant. After building the fit for Hinata, in-game, I ended up having to buy a 3% CPU implant just to get within .04% of my max CPU.

### Expected behavior:
[redacted]

### Actual behavior:
[redacted]

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[redacted]

### Release or development git branch? Please note the release version or commit hash:
2.4.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by blitzmann** [comment]
Hi @seraphx2 

I'm going to need a bit more information, specifically your characters skills. Would you be able to post them by going to the character editor, selecting the character, and then clicking the small "export" button in the lower right corner?

Additionally, double check that you have exactly the same fit and implants active in EVE vs pyfa. If they are the same, then the next step would be to try to find the offending modules - compare the CPU consumption of modules between In Game (when they are fitted, should be able to go to Show Info and take a look at their calculated value) and pyfa. let me know if you notice any discrepancies between them.

One thing that I notice right off the bat is that pyfa thinks the max CPU for that ship is 441.8 with your skills, where the in game fitting window is showing 455... I'm unsure of why there is a large discrepancy there?

**Comment by umdv** [comment]
@blitzmann Discrepancy is because he has ee603 ingame while ee601 is active in pyfa.
Better question is why @seraphx2 has 0.2 CPU left from 455 (he spent 454.8 then) instead of his planned 444.9. I have same only if I fit T2 target painter.
So it's maybe about _updating_ skills in pyfa and checking what is actually fitted ingame?

**Comment by seraphx2** [comment]
that's because I have the CPU implant in in EVE and can't turn it off in game like I can in game. lol. I suppose I could use the simulator instead.

Robert Burke | Gamer / Developer
Sent from Outlook<https://aka.ms/qtex0l> on my iPhone

________________________________

**Comment by blitzmann** [comment]
> Discrepancy is because he has ee603 ingame while ee601 is active in pyfa.

He mentioned that in the original post, so wasn't concerned about it. Indeed, could be a skills thing, however, in that case you would usually get worse stats in pyfa, not better. :)

@seraphx2 glad you got it figured out. That explains the CPU usage discrepancy, however I'm still perplexed as to why your manticore in game shows a higher CPU cap than pyfa. When you update your skills in pyfa, does that correct itself?

Also, in the future, please don't redact information unless it's extremely sensitive. Its good to keep the information available for archival and documentation purposes of the bug :)

**Comment by seraphx2** [comment]
I wouldn't normally, except there was no bug and I felt it was sort of personal info that no longer needed to be there. and the base CPU is increased when you have the implant turned on so because the 603 was plugged in, of course the ships base available CPU is going to be higher. In pyfa, the 1% was technically off, and even if I turned it on, it would still be lower than in-game because it's only a 1%.
