### ISSUE TITLE
Error when using proxy with authentication

### ISSUE THREAD

**Issue by pico2220** [pyfa-org/Pyfa#1729]
When using a Proxy with authentication, accessing the "Preferences" or "EVE SSO" pages leads to an error:

`File “C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\settings.py”, line 251, in autodetect
ValueError: too many values to unpack (expected 2)`

Reason:
The Proxy with authentication has this form:
http://username:password@ip:port/

In line 251 in Settings.py only one ":" is expected but the line has two ":" so the split command fails.

Possible Solution:
Insert directly before line 251:
`    atpos = proxyline.find("@")`
`    if atpos != -1:`
`        proxyline = proxyline[(atpos+1):]`

**Comment by blitzmann** [comment]
Duplicate #1708 it was recently closed, just reopened it. Fix will come out with next release :)
