### ISSUE TITLE
The Entosis moduel dont have the +100% sensor strength bonus when activated

### ISSUE THREAD

**Issue by zino73** [pyfa-org/Pyfa#1730]
## Bug Report
Since Eve online March 2018 Release : ( https://www.eveonline.com/article/p5w1jb/patch-notes-for-march-2018-release ) 

its mentionnated : 

> Balance changes to the Entosis Link Modules:
...
> +100% sensor strength to any ship with an active cycling entosis link

### Expected behavior:
+100% sensor strength to any ship with an active cycling entosis link

### Actual behavior:
+100% sensor strength to any ship with an active cycling entosis link

### Detailed steps to reproduce:
Pyfa (still at 22 Sensor Strenght with an active entosis module fitted)
https://i.imgur.com/SVVFcCy.png

IG simulator (at 44.08 Sensor Strenght with an active entosis module fitted):
https://i.imgur.com/YggkkuK.png

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Drake, test]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Entosis Link I
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
V2.4.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 7

**Comment by blitzmann** [comment]
Thanks for the report! indeed, must have missed for that patch, nice find!
