### ISSUE TITLE
Jump portal generation skill incorrectly affecting BFG stront consumption.

### ISSUE THREAD

**Issue by Lucius-Q-User** [pyfa-org/Pyfa#1731]
## Bug Report
if a character has levels in Jump portal generation, pyfa shows reduced stront consumption for the bfg.

### Expected behavior:
Stront consumption of the BFG should stay at 2k units

### Actual behavior:
Stront consumption of the BFG is shown as 2k - (2k * 0.1 * levels in JPG)

### Detailed steps to reproduce:
Load a fit for a titan
Set character to all skills 5
Fit a BFG
R-click on the bfg and select module stats -> attributes

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Ragnarok, Ragnarok]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Bosonic Field Generator
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
v2.5.0b1+command

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Linux

**Comment by blitzmann** [comment]
Hi there! Just not getting around to debugging this...

Are you sure this is how it works in-game? The effect for that skill is defined as applying to all modules that requires the `Jump Portal Generation` skill - it doesn't seem to discriminate against the modules in any other way, so from what I can tell this skill should apply to the BFG.

I am not well versed in capital modules though, so I may be completely incorrect with it. If there some supporting documentation that you can provide showing that this is indeed a pyfa bug? in-game screenshots would be a good place to start :)

**Comment by lunedis** [comment]
Jump Portal Generation skills actually reduces BFG strontium consumption ingame, so pyfa is working correclty here.

**Comment by blitzmann** [comment]
thanks for the confirmation @lunedis , I believe you're correct. Gonna close this issue, please open a new one if there's something missed :)
