### ISSUE TITLE
Alpha clones (at least Gallente ones) can use T2 drones

### ISSUE THREAD

**Issue by WPettersson** [pyfa-org/Pyfa#1732]
## Bug Report

My alpha clone can load and launch T2 drones, while pyfa says that shouldn't be possible. This might be because there's old data somewhere, I think originally alphas couldn't use T2 drones but later it was changed.

### Expected behavior:

An alpha character with Light Drones V trained should be marked as being able to fly T2 drones.

### Actual behavior:

Skillbook in top-right is red, stating that Light Drones V is needed.

### Detailed steps to reproduce:

Load alpha character with Light Drones V trained. Load Hobgoblin II into drone day. pyfa should report that the character can fly the ship (green skillbook in top-right, not red)

### Fits involved in EFT format (Edit > To Clipboard > EFT):

[Tristan, Test]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

Hobgoblin II x1
### Release or development git branch? Please note the release version or commit hash:

Development, latest master

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Gentoo

### Other relevant information:

My alpha character is Gallente. I don't know if it's going to only be Gallente alpha clones that can fly T2 drones.

**Comment by blitzmann** [comment]
can you double check to make sure light drones is skilled to V.

The alpha support in pyfa is implemented as a skill level cap, meaning the base character needs to have level V. I'm able to copy an all 5 character and apply alpha clone and it shows it accepting a Hob II.

Please double check your skills - it may be that the character has outdated skills that need an API refresh.

**Comment by WPettersson** [comment]
I tried updating the skills, and it didn't seem to have any effect. I then decided to completely remove my old ~/.pyfa folder, since it has been around since 2011 and hasn't been used in years. I then re-did everything, and now it does seem to work just fine. I'm going to guess that yes, it was just outdated skills that needed an API refresh. Sorry for bothering you.

**Comment by blitzmann** [comment]
>I tried updating the skills, and it didn't seem to have any effect. I then decided to completely remove my old ~/.pyfa folder, since it has been around since 2011 and hasn't been used in years. I then re-did everything, and now it does seem to work just fine. I'm going to guess that yes, it was just outdated skills that needed an API refresh. Sorry for bothering you.

Removing `~/.pyfa` shouldn't be the fix, although...

>  since it has been around since 2011 and hasn't been used in years.

If you're coming back from a long break, I can see that it might cause problems. However, if there was any error, you should have received and error pop up.

Do you happen to still have the old database file by chance that you can send to sable.blitzmann@gmail.com? Would like to take a look at it and see if there's anything I can find with  regards to it not updating.

**Comment by WPettersson** [comment]
Unfortunately, I did just straight up delete it. I also remember that I first installed wxPython (with pip) at the version listed in requirements.txt, but that had some bugs so I had to update wxPython to be able to see the skills list properly, maybe that had some impact.

**Comment by blitzmann** [comment]
> so I had to update wxPython to be able to see the skills list properly, maybe that had some impact.

Must be talking about #1421, but that really should only be a GUI bug, shouldn't affect data

Well, sucks that the database is gone, but I'm glad you're back up and running :) Thanks!
