### ISSUE TITLE
VirusTotal 2 viruses found

### ISSUE THREAD

**Issue by Some-T** [pyfa-org/Pyfa#1734]
Is this a confirmed false positive: [![Screenshot from Gyazo](https://gyazo.com/4e7ed596eedf481edc16c431f65e461a/raw)](https://gyazo.com/4e7ed596eedf481edc16c431f65e461a)

specifically the file pyfa.exe

**Comment by blitzmann** [comment]
If you downloaded from githib, it's a false positive. Unfortunately there's not much we can do about antivirus picking  up pyfa as malicious, besides spending a few hundred dollars on a exe signing

**Comment by blitzmann** [comment]
no problem!
