### ISSUE TITLE
wxPython version 4.0.0b2 not working

### ISSUE THREAD

**Issue by Tetractys** [pyfa-org/Pyfa#1742]
Hi!
I have some wxPython version problem. In the following image is reported the wxPython version i have INSTALLED == 4.0.0b2 - Installed from this page: https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04/

![image](https://user-images.githubusercontent.com/465836/45816318-7fa24200-bcdb-11e8-89c1-fe8a8fcc768b.png)

This instead is the error i receiving:

![image](https://user-images.githubusercontent.com/465836/45816393-cbed8200-bcdb-11e8-88a3-cac3975b04f8.png)

All other packages in the "requirements.txt" file are satisfied.

If the >must have< version is the 4.0.0b2+ (with the plus "+") i absolutely don't know where i can download it....

My system:
![image](https://user-images.githubusercontent.com/465836/45817097-ec1e4080-bcdd-11e8-88ad-270ce3a8fe86.png)

Thanks in advance! (sorry but on python i'm a total noob...)

David

**Comment by minlexx** [comment]
Have you tried to use `pip3` (or even `pip3.6`) while checking installed? Ubuntu may have `pip` to use python2 py default.

**Comment by blitzmann** [comment]
^ most likely this, double check which version of pip you're using. Probably best to go with `python3.6 -m pip install <package>` to ensure the proper one

**Comment by Tetractys** [comment]
Thank you to answer me so fast! I got the point about the version 3.x of python :) I rolled back with my Timeshift backup and I'm ready to do a fresh start.
Btw, could you please indicate me the link to the correct mandatory WxPython version (4.0.0b2+)?
That would help greatly!
D.

**Comment by blitzmann** [comment]
4.0.0b2 should work, the one for cp36 if you're using python 3.6. Additionally, the latest 4.0.3 might also work, but I haven't yet attempted to test with that version yet

**Comment by blitzmann** [comment]
@Tetractys any update?

**Comment by blitzmann** [comment]
Going to close this issue - @Tetractys if you need any further assistance getting set up, please reach out :)

**Comment by Tetractys** [comment]
I was in the hospital for urgent surgery. I'll try as soon as possible. Thank you for all the assistance you gave me. ;)

**Comment by blitzmann** [comment]
@Tetractys sorry to hear that! Hope everything is going smoothly!
