### ISSUE TITLE
Entropic radiation sinks have no "Variations" on their context menu or or "Compare" tab in their Module Stats window

### ISSUE THREAD

**Issue by MarHelmer** [pyfa-org/Pyfa#1744]
## Bug Report
Entropic radiation sinks have no "Variations" on their context menu or or "Compare" tab in their Module Stats window.

### Expected behavior:
Right-clicking a module should show its variations in a submenu. Its stats window should show a comparison tab.

### Actual behavior:
Neither of the appropriate context menu or tab is displayed.

### Detailed steps to reproduce:
1. Load an Entropic Radiation Sink of any type.
2. Right click the fitted module.
3. Note that no "Variations" context menu is available.
4. Click "Module Stats".
5. Note that no "Compare" tab is available.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
N/A

### Release or development git branch? Please note the release version or commit hash:
2.5.0b1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by blitzmann** [comment]
looks like these arent being populated into invmetatypes. unsure if its due to underlying eve data or an issue with our conversion script, but gonna bet on it being an eve issue. will look further this week

**Comment by blitzmann** [comment]
So it looks like this might be an issue with EVE data (like your last bug, keep it up! 😉)

https://gist.github.com/blitzmann/5242e3b2685465754f1e3ca767100f8d

This is the source of the information, it links types to their parent type. Radiation Sinks are not part of it (tech 1 is typeID `47908`)

Checking the client, I can see that it's not listed as a variation either. Will log this as a bug with CCP

**Comment by blitzmann** [comment]
Bug created: EBR-161220

**Comment by MarHelmer** [comment]
Damn, that's a pretty weird oversight on their behalf! Thanks for alerting them to it and I'm glad I was able to point you to it.

**Comment by blitzmann** [comment]
So, it seems that this was half-fixed by CCP. The tech 1's have variations, but the tech 2 is still missing in that mapping.

**Comment by DarkFenX** [comment]
Has been fixed in EVE data for a while now.
