### ISSUE TITLE
C2 Wolf Rayet effects do not apply to Light Entropic Disintegrators

### ISSUE THREAD

**Issue by MarHelmer** [pyfa-org/Pyfa#1745]
## Bug Report
Projecting a C2 Wolf Rayet weather effect does not modify the dps calculation for Light Entropic Disintegrators.

### Expected behavior:
Other Wolf Rayet wormhole effects seem to properly recalculate the dps for Light Entropic Disintegrators. This is not so for C2 effects.

### Actual behavior:
No dps recalculation is shown.

### Detailed steps to reproduce:
1. Open a Damavik fit and load a Light Entropic Disintegrator onto it.
2. Project a C2 Wolf Rayet wormhole weather effect on to the fit.
3. Note that no dps change has been calculated.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Damavik, Damavik fit]

Entropic Radiation Sink II
Entropic Radiation Sink II
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]

Light Entropic Disintegrator II, Occult S
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
2.5.0b1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by blitzmann** [comment]
This actually seems like a bug in EVE - the c2 wormhole doesn't have the precursor effect, whereas the other ones do. 

![image](https://user-images.githubusercontent.com/3904767/45991268-14959a00-c052-11e8-8b00-66577c6e20b3.png)

Will submit a bug report to CCP about this

**Comment by blitzmann** [comment]
EBR-161161 created

**Comment by MarHelmer** [comment]
Glad to help! Thanks for filing a ticket with the devs.

**Comment by blitzmann** [comment]
Checking up on this issue, according to latest TQ data, this is still a thing. Will comment on the bug report, and maybe ping a dev about this.

**Comment by DarkFenX** [comment]
Had been fixed by CCP in past 6 months i believe
