### ISSUE TITLE
Changing hybrid charges increases stored price of Void S / Null S

### ISSUE THREAD

**Issue by WPettersson** [pyfa-org/Pyfa#1759]
## Bug Report
Some prices (in particular, Null S, Void S) were insanely high. Like 5e37 high, which I investigated. Deleting prices forces a refresh, and gathers the right price (about 50ISK). However, whenever I change the charge of one of my blasters, the price of Void and Null in my cargo goes up by a factor of about 1000. Actually, it's exactly 1000, until floating point errors starts showing up. 

### Expected behavior:
Changing charges in a blaster shouldn't change prices.

### Actual behavior:
Changing charges changes prices.

### Detailed steps to reproduce:
Using the attached fit, keep changing the charge in any of the neutron blasters, either with right-click or double-clicking on a new charge. Each time, the cost of Void S and Null S increases.

I've tested on other ships, and it doesn't seem to depend on ship. I've also tested with other ammo, and only Void S and Null S prices seem affected. I've even checked missiles, and while I couldn't spot any missiles increasing in price, changing the missile in a RLML I also increased the cost of Void S/Null S.

I've even uploaded a video I shot at http://strudel-hound.com/pyfa.mkv but note that my screen capture apparently doesn't capture the right-click menus, so the first few charge changes seem to show me clicking on nothing and then the charge changing. You can see this charge change by looking at the actual fitting table though.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Enyo, Hunter]

EFFA Compact Assault Damage Control
Magnetic Field Stabilizer II
Tracking Enhancer II
Adaptive Nano Plating II

5MN Y-T8 Compact Microwarpdrive
Initiated Compact Warp Scrambler
Fleeting Compact Stasis Webifier

Light Neutron Blaster II, Uranium Charge S
Light Neutron Blaster II, Guristas Uranium Charge S
Light Neutron Blaster II, Void S
Light Neutron Blaster II, Antimatter Charge S
Small Ghoul Compact Energy Nosferatu

Small Anti-Explosive Pump I
Small Processor Overclocking Unit I

Null S x1000
Void S x1000
Thorium Charge S x1

### Release or development git branch? Please note the release version or commit hash:

I'm running master branch off git, 9ec54c90046231ebb8006e3e9884802c5a53f027

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Gentoo

### Other relevant information:

I'm comfortably with Python, I can debug stuff if someone gives me a hint as to where to look, but I don't know where to get started on this.

**Comment by Neugeniko** [comment]
I had this happening with t2 drones. check your price source is eve-marketdat.com and not blank under window>preferences>general>Default Market Prices. Also reset prices at window>preferences>database>delete all prices.

**Comment by WPettersson** [comment]
Yup, price source is eve-marketdata.com (Jita). I tried resetting the prices, on the first re-scan of prices Null S and Void S are 51.5 and 48.1

However, that's wrong. I have 1000 of each in my cargo, so the price should be 51.5k and 48.1k. This is getting me closer to the issue. It seems the problem is that if you have multiples of something in your cargo bay.

If you have `x` of an item in your cargo bay, changing the charge of a gun/turret/missile launcher will also multiply the price of the item by `x`. I've even tested this with large cargohold optimization II, putting two in my cargo then swapping ammo around. My guess for now is that the code that works out how much stuff in your cargo is worth is updating the prices table in the database with the cost of the whole stack, for some reason. Time to get digging into code.

**Comment by WPettersson** [comment]
Turns out it was a minor mistake to make, that had layers of implications. The `price.price` item, when changed, also updated the price in the DB, so just had to avoid the call which actually changed price.price and it all works fine now.

**Comment by blitzmann** [comment]
@WPettersson I believe this may have already been fixed, albeit on a different branch. Can you pull down the `release/v2.5.0` branch and see if it shows the same issue?

**Comment by WPettersson** [comment]
Correct, the v2.5.0 branch does not show the same issue, and has a near-identical fix.

**Comment by blitzmann** [comment]
Thanks for the update!
