### ISSUE TITLE
Updated values in eve.db do not appear in application

### ISSUE THREAD

**Issue by fonsui** [pyfa-org/Pyfa#1763]
### Expected behavior:
Updated eve.db with new values for October release changes, expected to see new values in application for:

4x intys: removed interdiction nullification from role bonus text
Crow: improved base agility from 3.7 to 3.25
Damavik: removed one low slot, added one mid

### Actual behavior:
Old values still display

### Detailed steps to reproduce:
Edit the database and see if application displays new values

### Fits involved in EFT format (Edit > To Clipboard > EFT):
Not relevant, issue occurs with fresh user .pyfa folder

### Release or development git branch? Please note the release version or commit hash:
2.5.0b1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win 10

### Other relevant information:
N/A

**Comment by fonsui** [comment]
This is resolved, I found that the application was loading the database from %userprofile%\AppData\Local\Virtual Store\Program Files (x86)\pyfa\eve.db, either instead of, or alongside the one in the Program Files folder in the root, where the application is actually installed.

**Comment by seraphx2** [comment]
But they still need to address the missing values which prompted the self-edit to the DB.

**Comment by fonsui** [comment]
I was only reporting what I thought was a bug; data updates are a known need and I am sure a data update will be handled through the regular release cycle.

**Comment by blitzmann** [comment]
Indeed, new release is planned for tonight. Been busy this week.

Re:virtual store, this was an annoying issue that has come back, but it was known. should be fixed again with the upcoming release. :)

**Comment by blitzmann** [comment]
2.5.0 is out :D
