### ISSUE TITLE
v2.5.0 - Error when opening Monitor fittings

### ISSUE THREAD

**Issue by GKFC** [pyfa-org/Pyfa#1767]
Incidentally, the error dialog box thrown won't allow copy / paste (instead opening up the copying fit dialog box underneath it), and the focus shifts to the "copy" dialog box, so I have to move the error box, quit the copy box, then I can quit the error box instead... not a great experience there.

But I've attached an image of the error instead.

![screen shot 2018-10-12 at 15 19 43](https://user-images.githubusercontent.com/24534756/46848153-0e663280-ce34-11e8-81eb-58fc5cdd1fd9.png)

I had 4 fitting tabs previously open, and now the first (Monitor) fit tab is labelled "Empty Tab" even though there's a fit underneath:

[Monitor, FC]

50MN Microwarpdrive II
Target Painter II
Medium Micro Jump Drive

Sisters Expanded Probe Launcher, Sisters Combat Scanner Probe

Eifyr and Co. 'Rogue' Acceleration Control AC-603

Quafe Zero
Agency 'Overclocker' SB7 Dose III

Nanite Repair Paste x250
Sisters Combat Scanner Probe x6
Sisters Core Scanner Probe x8

If I switch to another ship fit then back to the Monitor it throws another (similar) exception:

![screen shot 2018-10-12 at 15 26 57](https://user-images.githubusercontent.com/24534756/46848043-546ec680-ce33-11e8-9587-65d3e084a1bd.png)

Happens if I switch to a Pacifier fit there too.  Think it has something to do with that first tab / ships specifically...

Cheers,

G.

**Comment by blitzmann** [comment]
Paging @m-sasha, is it possible this is related to the hd-images stuff?

I'll take a look tonight, thanks for the bug report!

**Comment by m-sasha** [comment]
Yeah, I guess it's because the Monitor doesn't have a race icon, and getImage just does
```cls.getBitmap(name, location).ConvertToImage()```

**Comment by blitzmann** [comment]
Got it. yeah, there are a few images that are known to be broken and working as intended for all intents and purposes. Previously it was returning None, but not it's trying to to a ConvertToImage on the None and it's having a fit.

I've got a fix for it and will release tomorrow. :D thanks all!

**Comment by GKFC** [comment]
Thanks much appreciated  :-)

Does that include doing something about the additional box being spawned when trying to copy the error text?  The text copy box being put (hidden) under the error box instead of actually copying the text itself?

Not sure if it's just a Mac thing, but it means currently I have to then move the error box, close the text copy box, then printscreen the error box, then close that box, and upload that as an image instead... like in this instance... which is rather protracted.

I can open as a separate issue if you'd prefer.

**Comment by GKFC** [comment]
Thanks that'd be great.

To be clear though, the error message is one dialog box, but after hitting CMD+C to try and copy the text it spawns the other box underneath.  It's not multiple error boxes.

**Comment by blitzmann** [comment]
> To be clear though, the error message is one dialog box, but after hitting CMD+C to try and copy the text it spawns the other box underneath. It's not multiple error boxes.

hrm, odd. I'll have to check on my mac client, because I don't think this is a thing that's happening for windows
