### ISSUE TITLE
Implant stats not updating upon removal

### ISSUE THREAD

**Issue by feyyd** [pyfa-org/Pyfa#1777]
## Bug Report
Removing Implant doesn't update stats until another implant is added, or current implant is replaced with another implant.

### Expected behavior:
Upon removing implant, stats should reflect not having said implant.

### Actual behavior:
Upon removing implant, stats remain as though the implant was still plugged in.

### Detailed steps to reproduce:
Using Fitting Specific Implants.  Plug in CPU implant.  Observe stat increase.  Remove CPU implant, no change to CPU stat.  Plug in any implant, implant stats will be recalculated correctly.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
All

### Release or development git branch? Please note the release version or commit hash:
2.5.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
As far as I can tell, the only thing that forces the implants to recalculate, is putting in another implant.  
Tested with CPU/PG/Navigation/Laser DPS implants, looks like all implants are affected.

**Comment by blitzmann** [comment]
Hrm, probably not signaling a fit refresh event after adding implant. I'll check tonight - if that's the case, super easy fix :D

**Comment by GKFC** [comment]
Yes I've noticed this one as well.

Seems to be that the fit refresh isn't being done after removing the first implant in addition to when adding the next one?
