### ISSUE TITLE
Feature request - Filling slot with a module

### ISSUE THREAD

**Issue by petosorus** [pyfa-org/Pyfa#1779]
(This is something I started working on)

I would like a feature where we would have an option to fill the (relevant) available slots with a module.

The main usecase is me fitting 8 guns on a battleship. Now I can double click 8 times or copy with ctrl + drag, but it's a bit annoying.
I would want to add one module to my fit, right-click on it, and clicking an option "Fill With Module" would fit 8 guns to the ship.

Current analysis : 

- A module should be fitted only withing its limits. One DCU, no more guns than turret hardpoints, etc.
- Hardpoints limitation could apply automatically at the moment.
- One of a kind modules could be harder, it's something I have to check.
- Due to the current state of pyfa, MWDs or ABs would be cloned all active at the same time. This is not in the scope of this issue. The case of filling with prop mods also does not happen often.
- The Do action seems pretty straightforward. The Undo action is a bit harder. What do we want to do exactly? Save the former state of the fit and restore it? Just removing all modules of that kind? I have to check what's done elsewhere to get familiar with the feature.
- It could be nice having the option on market search too, but it's trickier as it only applies to thing you can fit. Not to cargo, drugs, implants, drones, etc.

**Comment by blitzmann** [comment]
Tested and worked well! There might be edge cases, but we can deal with those if they ever happen. Thanks for the work!
