### ISSUE TITLE
Feature Request - Make used Additions visible

### ISSUE THREAD

**Issue by Dawnkeeper** [pyfa-org/Pyfa#1784]
Right now you have to click on each tab in the Additions section to see if it is used.

It would be nice to see on one glance whether a ship has notes, uses Implants and so on.

This could be done by writing the labels in bold or adding a symbol as soon as this category is used.

**Comment by blitzmann** [comment]
Hi @Dawnkeeper!

This has been mentioned before #1717. I haven't had time to really dig into it as it's kind of a low priority thing, but it seems like at least a few folks might find this helpful. The other issue went in a little bit of a different direction, requesting things like counts and stuff that might be very tricky to do. However, I do like the idea of having the tab bolded to show that there's something there, and this would be a much easier thing to do.

I'm going to try to get something like this implemented by the next release, but again, this would be a low priority thing.

Also tagging this as `help wanted` in case someone drops by looking for something a bit "easier" to do. A bit of info on how this might work:  whenever a fit is changed, an event happens which is captured by all the various addition panes. We can, as part of our event processing, determine if we should flag this panel as having items. We would, with some mechanism, tell the tab to turn bold - this would be the most tricky part, as I don't believe we currently have a way of communicating with the tab or having the tab change font characteristics.

**Comment by petosorus** [comment]
Hi Dawnkeeper, hi Blitz

I'm interested at taking at look at it during today, I'll update if I feel good with it :)

**Comment by blitzmann** [comment]
Awesome, thanks @petosorus!

**Comment by petosorus** [comment]
You were right, I don't see a way to get the tab at the moment. I'm going to fiddle with it for a bit then!

**Comment by DarkFenX** [comment]
Extended version of this was implemented in 2.11.1
