### ISSUE TITLE
Pre-spoolup and post-spoolup damage stats support

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1792]
Presently, pyfa shows damage stats for triglavian guns after full spoolup.

I created spoolup_support banch (based on master) where i already implemented backend support. Signatures of some methods fetching damage stats has changed, see f39ba27a13a7595dc8d30eb4632f56a544437002

Now to the UI part: I have no idea how to do it. Tooltip? Showing range in dps panel?

This is how stats are fetched from the backend:
```
        stats = (("labelFullDpsWeapon", lambda: fit.getWeaponDps(spool=True), 3, 0, 0, "%s DPS", None),
                 ("labelFullDpsDrone", lambda: fit.getDroneDps(), 3, 0, 0, "%s DPS", None),
                 ("labelFullVolleyTotal", lambda: fit.getTotalVolley(spool=True), 3, 0, 0, "%s", "Volley: %.1f"),
                 ("labelFullDpsTotal", lambda: fit.getTotalDps(spool=True), 3, 0, 0, "%s", None))
```
To fetch prespoolup values, just pass spool=False to methods which fetch data.

Any discussion or help on UI side is greatly appreciated (especially if you can code UI side yourself).

**Comment by blitzmann** [comment]
@DarkFenX Looked at this tonight, we could absolutely do this in a tooltip. Alternatively (or in addition to), we can do something similar to "Factor in Reload Time" and have a context menu which toggles displaying pre / post spool up.

**Comment by blitzmann** [comment]
@DarkFenX Updated the branch with my changes, please test. If there's a difference between pre and post spool up, it will display as `pre-post DPS` on tooltip.

I also create a variable that displays pre or post, although it's hardcoded right now to display post. We can use this for a future toggle (will look into this).

**Comment by DarkFenX** [comment]
I just checked and it works. However, i think that there should be some hint that it is pre- and post-spoolup damage, because otherwise it can be interpreted some other way (e.g. damage spread, with top end of range shown for stats).

**Comment by blitzmann** [comment]
Hrm, good point. I'll take a look tonight and see what can be worked out :)

**Comment by blitzmann** [comment]
Can't reproduce :(

**Comment by DarkFenX** [comment]
1) Open some fit
2) Press ctrl-t to open new tab
```
Traceback (most recent call last):
  File "/home/dfx/Workspace/eve/pyfa/gui/statsPane.py", line 75, in fitChanged
    view.refreshPanel(fit)
  File "/home/dfx/Workspace/eve/pyfa/gui/builtinStatsViews/firepowerViewFull.py", line 176, in refreshPanel
    valueStrTooltip = dpsToolTip(preSpoolVal(), postSpoolVal(), (prec, lowest, highest))
  File "/home/dfx/Workspace/eve/pyfa/gui/builtinStatsViews/firepowerViewFull.py", line 157, in <lambda>
    stats = (("labelFullDpsWeapon", lambda: fit.getWeaponDps(spool=False), lambda: fit.getWeaponDps(spool=True), 3, 0, 0, "%s DPS", None),
AttributeError: 'NoneType' object has no attribute 'getWeaponDps'
```

**Comment by blitzmann** [comment]
Ah, got it to reproduce. It doesn't happen all the time... it's weird. Seems to only happen if you ctrl+t from a fit with DPS values. I tried from a Coveter and a rifter fit without any loaded ammo, and it doesn't do it, but a rifter with loaded ammo and a caracal seems to trigger it.

**Comment by DarkFenX** [comment]
Fixed this bug and added spoolup dps/rr spread in sisi branch.
