### ISSUE TITLE
DPS Graph: Sum of dps of all Fighters, active or not, is displayed

### ISSUE THREAD

**Issue by DinKartay** [pyfa-org/Pyfa#1793]
## Version
Release v2.5.1 (f854627)

### Expected behavior:
Graphed DPS should be the result of the sum of the DPS of the 'active' fighters, to match turret and drone graph behaviour.

### Actual behavior:
Displayed DPS is the sum of the DPS of all fighters, active or not.
This also means that e.g. on a normal carrier (max 3 squadrons), storing more than 3 results in more than 3 squadrons being simulated; a technical impossibility for carriers.

### Detailed steps to reproduce:
1. Load a carrier fit (or Caiman/Komodo). Fill the fighter bay with fighters, leave some active and some inactive. Note the correctly displayed DPS in the "Firepower" section.
2. Simulate the DPS graph of the fit (Window>Graph).
3. Observe that the DPS is higher than the "Firepower" DPS (assuming there are inactive fighters).
4. Change the state (active/inactive) of fighters, observe lack of effect.
5. Change the active ability of an inactive fighter, observe the change in graphed DPS

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by blitzmann** [comment]
This was fixed with 2.6.1 👍
