### ISSUE TITLE
Unable to paste fits with apostophe

### ISSUE THREAD

**Issue by kiwimind** [pyfa-org/Pyfa#1795]
## Bug Report
When copying and pasting a fit into Pyfa, if the fit name has an apostrophe in it, nothing happens.

### Expected behavior:
Fit imported.

### Actual behavior:
Nothing.

### Detailed steps to reproduce:
I was pasting the following fit:
```
[Exequror Navy Issue, Anorak’s Absolution]
Damage Control II
Magnetic Field Stabilizer II
Magnetic Field Stabilizer II
Prototype Armor Kinetic Hardener I
Prototype Armor Thermal Hardener I
Medium Armor Repairer II

Cap Recharger II
Phased Scoped Target Painter
Tracking Computer II
10MN Y-S8 Compact Afterburner

Modal Neutron Particle Accelerator I
Modal Neutron Particle Accelerator I
Modal Neutron Particle Accelerator I
Modal Neutron Particle Accelerator I
Modal Neutron Particle Accelerator I

Medium Anti-Kinetic Pump I
Medium Capacitor Control Circuit I
Medium Capacitor Control Circuit I

Hobgoblin II x5

Caldari Navy Antimatter Charge M x7080
Tracking Speed Script x1
Optimal Range Script x1
```

When removing the apostrophe from the fit's name, i.e. change `Anorak’s Absolution` to `Anoraks Absolution` it works fine.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
See above.

### Release or development git branch? Please note the release version or commit hash:
2.5.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
OS X 10.14.1

**Comment by kiwimind** [comment]
Yep, changing the smart quote with a regular one does work, however I copied this fit from a website so still think that this is an issue, as many people may well be going via Word or similar.

I guess this then opens up a whole can of worms about supporting unicode. 🤘

**Comment by Asday** [comment]
Does importing the fit into EVE with that fake apostrophe work?  Does it work with ar:b:itrary unicode?

**Comment by blitzmann** [comment]
>I guess this then opens up a whole can of worms about supporting unicode. 🤘

You have no idea... :P

That being said, this really shouldn't be too difficult to just take that and plant it into the fit name, not sure why it actually breaks.

That also being said, there have been times when eve CCP name things with smart quotes. Though, it doesn't normally break pyfa, so unsure why this would (other than the fact that we are parsing it instead of simply displaying it)

**Comment by blitzmann** [comment]
For what it's worth, I actually just got around to testing this. On Windows, this imports fine. I'll have to test this in OSX to see what funkiness comes from this

**Comment by burnsypet** [comment]
It's odd, your fit seems to import without any issues for me on OSX 10.13.3 using pyfa v2.6.1

**Comment by kiwimind** [comment]
Just tested and you're right, it does import into v2.6.1. It wasn't importing into v2.6.0.

Guess this can be marked as closed...

**Comment by blitzmann** [comment]
¯\_(ツ)_/¯
