### ISSUE TITLE
Unable to split drone stacks.

### ISSUE THREAD

**Issue by GKFC** [pyfa-org/Pyfa#1802]
Hi,

There used to be a right-click option until very recently, but when (e.g.) I put a group of 4 Warriors into my fit I can't split them up anymore.

Was a useful feature to have, can it be put back please?

Cheers,

G.

**Comment by GKFC** [comment]
Having browsed the release notes I see this was deliberate...

Still, can it please come back?

For example, a Dramiel has room for 4 drones in it's hold but can only launch 3.  It's useful to be able to put all 4 in the hold, split them up to see actual DPS (with 1 spare) then copy the entire fit into EVE without having to MacGyver it afterwards.

Cheers,

G.

**Comment by blitzmann** [comment]
This was an unfortunate casualty of the progress made for undo/redo support. I've always thought it was an odd feature, and never really saw a use for it. 

I'll take a look at it to see what needs to be done to re-implement :)

**Comment by GKFC** [comment]
Thanks if you could that'd be great.

Yeah it's a bit of niche feature, but nice-to-have nonetheless...

**Comment by cdgori** [comment]
Just noting that I miss this too.  I found a (partial) workaround, where I can add another stack (or partial stack) of the same drone (say a Stratios, can control 4 heavies, and I want 2 sets of 4 heavies in the drone bay), so I try to make it that way so I can see the drone DPS correctly but also have the fit copy correctly for buying the fit.

Sometimes in my example Stratios fit, I'll create a stack of 4, then drag a 5th one and it will start a new stack in the drone bay.  Other times it gets added to the first stack as a 5th drone.  I can't figure out what makes pyfa do one thing vs the other yet.

**Comment by DarkFenX** [comment]
Fixed in 98e834fd30a7e47ccc60588f1c2dfe2455acf3a7 and 7ae8d1dc1af85d04273bd34f65c20e311c5c8e9c
