### ISSUE TITLE
Mining amount ship bonus is affecting Ice Harvesting drones

### ISSUE THREAD

**Issue by Noert** [pyfa-org/Pyfa#1809]
### Expected behavior: 
Mining yield hull bonus on drone ships (Vexor, Praxis) does not affect mining yield of Ice Harvesting drones

### Actual behavior: 
Mining yield bonus is applied to Ice drones (i.e. I get 1,500 m3 mining amount per drone which is impossible)

### Detailed steps to reproduce: 
Fit a Vexor or Praxis with ice harvesting drones, check the mined amount

### Release or development git branch? Please note the release version or commit hash:
release 2.6.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
Praxis does not have a  drone mining yield bonus at all, yet it is applied to both Ice and Mining drones. This must also be a bug.

**Comment by blitzmann** [comment]
For the praxis, it indeed has an effect called `shipBonusMiningDroneAmountPercentRookie`, so I'm assuming it's supposed to have bonuses to mining amount. It may be that the description of the roles is busted, or some other bug within the EVE data. 

As for ice harvesting amount being lumped up as the normal mining bonus... I'm not sure. I'll have to double check when I get to my desktop what groups these are supposed to be applied to.

**Comment by blitzmann** [comment]
Seems you're correct, the mining effect affects items that require "Mining Drone Operation", whereas the effect in pyfa is targeting items of group "Mining Drone".

Not sure how wide-spread this issue is, but I'll try to take a closer look at the mining effects

**Comment by blitzmann** [comment]
k, did a project search for effects affecting the `miningAmount` attribute, and double checked these against the eve data. I changed three, two relating to the two ships mentioned here, and the other being the Arbitrator.

A note on the Arbitrator, it seems that it will indeed increase ice harvesting amount. The effect is defined as affecting items which require the Drones skill, which includes Ice Harvester drones. I would be interested to confirm this in game and file a bug report

**Comment by Noert** [comment]
> EDIT: can't test ice harvester drones on arby as they aren't available on free account >.<

Thanks for getting on it so quickly! 

As a matter of fact, they are bonused inside the EVE client, yet are not bonused on the Vexor. 
I'll test if it has any real effect (it shouldn't, because it ore is only extracted as whole items) as soon as I can, but in the meantime I'll report this to CCP as well. 

Screenshot from TQ: https://i.imgur.com/CNS5uTg.png

**Comment by Noert** [comment]
Just in case, I would also like to mention that Gnosis has the same issue as Praxis with mining drone bonus.

**Comment by blitzmann** [comment]
Gnosis shares the same effect as the Praxis, so should also be fixed with the patch :)

Huh, I forgot that EVE now has the ghost fitting stuff. Maybe that would allow me to test some of these things on SISI without being able to actually fit them. Regardless, I'll also make a bug report to CCP about this when I get home 👍
