### ISSUE TITLE
Loading script into projected RSB leads to a crash

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1811]
Current master.

1. Create any fit (e.g. retribution)
2. Project any remote sensor booster onto fit
3. Load lockrange script into it

Pyfa crashes with following traceback:
```
Traceback (most recent call last):
  File "/home/dfx/Workspace/eve/pyfa/gui/builtinContextMenus/moduleAmmoPicker.py", line 231, in handleAmmoSwitch
    self.mainFrame.command.Submit(cmd.GuiModuleAddChargeCommand(fitID, charge.ID if charge is not None else None, self.modules))
  File "/home/dfx/Workspace/eve/pyfa/gui/fitCommands/guiAddCharge.py", line 17, in __init__
    self.positions = [mod.modPosition for mod in modules]
  File "/home/dfx/Workspace/eve/pyfa/gui/fitCommands/guiAddCharge.py", line 17, in <listcomp>
    self.positions = [mod.modPosition for mod in modules]
  File "/home/dfx/Workspace/eve/pyfa/eos/saveddata/module.py", line 275, in modPosition
    return self.owner.modules.index(self)
ValueError: Module(ID=1964, name=Remote Sensor Booster II) at 0x7f44f83a3358 is not in list
```

**Comment by blitzmann** [comment]
It's part of the command refactoring, it's trying to get the position of the module, and it's assuming it's a module on the fit (rather than a projected module). Gonna dig into this a bit and see if there's a simple way of fixing it

**Comment by blitzmann** [comment]
Think I got a fix for it... not as eloquent as I would hope for, but it seems to work. Basically involves sending into the `FitSetChargeCommand` command if we're working with projected module charges, and switches off which list to use based on that. Also noticed that the global charge picker is also broken (and probably has been forever?) - fixed that too
