### ISSUE TITLE
`(α)` shows up when renaming a character that is set to alpha 

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1816]
Right now, when you set a character to alpha, `(α)` shows up for the character name to signal that they have a restricted skill set. This is only really supposed to show up for the character drop down - when editing, it's supposed to show the literal name of the character, but right now it's showing the mdified name.

![image](https://user-images.githubusercontent.com/3904767/49346519-e6d85d00-f661-11e8-9716-014f036a20e2.png)

Saving this causes double (α) as well

**Comment by burnsypet** [comment]
In entityEditor.py around about line 134 we can regex away the (α) for alpha characters:

```
        if active.alphaCloneID:
            trimmed_name = re.sub(' \(\u03B1\)$', '', active.name)
            dlg.SetValue(trimmed_name)
        else:
            dlg.SetValue(active.name)
```

This removes the (α) when the user opens the dialog.

**Comment by blitzmann** [comment]
Hrm, we could. I would be okay with that in the short term, but believe the proper solution would be to fix it at the character level. The entity editor is used for other things, and having instance-specific code in it feels wrong.

If you could make a PR with this fix, I'll keep it on hold for a bit until either the next release or we are able to evaluate the character class and figure out why this happens.

**Comment by burnsypet** [comment]
It's possible that we could do it in the CharacterEntityEditor instead, I'll do a bit more digging.

**Comment by blitzmann** [comment]
That will work for now :)
