### ISSUE TITLE
Add base module and mutaplasmid info to item mutation panel

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1817]
There's no way to obtain that info at the moment which makes it hard to know what you're working with (base module can be seen only from 'revert' context menu item, used mutaplasmid is not seen anywhere).

**Comment by blitzmann** [comment]
o/ @burnsypet!

Something like that would be a great start at the very least. long term- we should have the ability, from there, to select a new base module or mutaplasmid, but I have a feeling it might not be as easy as just changing to a new item. But that could be done during a later iteration I would imagine.

If you could make a PR for what you have right now (maybe add a bit more border to those two lines of text to space them out a bit), we can get that in, and that way we'll at least have the info available.

**Comment by DarkFenX** [comment]
@burnsypet yes. For now i want just info rather than being able to do any replacements, which is more complex.

**Comment by DarkFenX** [comment]
I don't think you need description in parenthesis - it's kind of obvious what is base and what is mutaplasmid, isn't it?

I'd also play a bit with padding so text has more space around it (looks a bit low to my taste but I am not UI expert), but apart from that looks great.

**Comment by blitzmann** [comment]
Could also lay it out like this

`<base module>                   <mutaplasmid>`

**Comment by DarkFenX** [comment]
Another possibility: might also take just first word from mutaplasmid name to save space, if that's needed (Decayed/Gravid/Unstable), and maybe avoid having separate entry for mutaplasmid (e.g. put base item name and mutaplasmid grade in parenthesis).

**Comment by blitzmann** [comment]
@burnsypet would you be able to make that PR this weekend? Planning on an official release early next week

**Comment by DarkFenX** [comment]
Added it to master myself. Might not look pretty, so adjust if needed.

![image](https://user-images.githubusercontent.com/275209/52721756-6ddb7700-2fbb-11e9-9952-828f83d7c651.png)

**Comment by DarkFenX** [comment]
@blitzmann by the way I had to change default size of stats window for GTK (vertical dimension to fit mutations tab info - all the buttons, base item info and at least 4 sliders, horizontal - to fit "affected by" tab for most items which was hidden before), could you revise defaults for windows and mac (or maybe someone else who's reading this)?

**Comment by blitzmann** [comment]
@DarkFenX I'll double check os x and windows window sizes... wish there was a better way of doing that, but meh
