### ISSUE TITLE
Cannot add new characters

### ISSUE THREAD

**Issue by brightvalley** [pyfa-org/Pyfa#1818]
Characters added through SSO Character Management are not appearing in the character dropdown list. What could I be doing wrong?

**Comment by blitzmann** [comment]
The character list in pyfa is different from the sso characters. You have to create a new pyfa character and link them to the sso character in the sso tab in the character editor.

**Comment by blitzmann** [comment]
Try that and let me know of it works =)

**Comment by blitzmann** [comment]
@brightvalley any update?

**Comment by brightvalley** [comment]
Apologies (installing several pcs right now)... yes, that worked as you
said, and thanks. Adding a character isn't very intuitive how that process
works, unlike the rest of the app.

**Comment by blitzmann** [comment]
> Adding a character isn't very intuitive how that process works, unlike the rest of the app.

I'm starting to get that feeling too. It was fine when the Character editor was the only place to do character stuff, but now we have the sso characters which are separated. not really sure how to fix this, maybe a message on the sso character box stating that you're only adding a repository of signed in characters, and to go to the character editor to assign them. Will give a bit more thought on that, but for now, gonna close this issue :)
