### ISSUE TITLE
(Projected?) Armour Repairers cause KeyError [2.7.0b1]

### ISSUE THREAD

**Issue by ftsartek** [pyfa-org/Pyfa#1825]
## Bug Report

Certain applications of armour repairers will throw a KeyError upon any interaction (adding, removing, projecting reps), as well as a different KeyError when removing projected reps from fits.

Appears to be inconsistent about what can cause the error, as I can reproduce it on a logi Legion fit and a Nestor with a projected Leshak, but some things (e.g. rep Loki and Guardian) don't seem to have the same problems.

Appears to only be an issue when there are more than 3 reps involved, across the fit you're changing and any projected fits.

### Expected behavior:

No error thrown, interacting with fits work as normal.

### Actual behavior:

Error thrown, occasionally actions will not immediately work (however, upon restarting pyfa or re-opening the fit they do sometimes work)

### Detailed steps to reproduce:

Make a simple nestor/legion rep fit, project it onto itself and ensure the fits have at least 2 reps each. 

KeyError when removing a projected fit was caused when trying to remove a projected Leshak with 4 reps.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

[Nestor, TEST]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Large Solace Scoped Remote Armor Repairer
Large Solace Scoped Remote Armor Repairer
Large Solace Scoped Remote Armor Repairer
Large Solace Scoped Remote Armor Repairer
Large Solace Scoped Remote Armor Repairer
Large Remote Capacitor Transmitter II
Large Remote Capacitor Transmitter II

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

Ogre II x5

Simple fit that will do the job to reproduce the error.

### Release or development git branch? Please note the release version or commit hash:

v2.7.0b1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10 Pro x64

### Other relevant information:

Errors thrown (first is for reps projected, second is removing leshak fit)

>pyfa vv2.7.0b1
>EVE Data Version: 1435052 (2018-12-12 22:48:30)
>
>OS version: Windows-10-10.0.17134-SP0
>Python version: 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
>wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
>SQLAlchemy version: 1.0.5
>Logbook version: 1.4.1
>Requests version: 2.21.0
>Dateutil version: 2.7.5
>
>####################
>
>Traceback (most recent call last):
>  File "C:\projects\pyfa\gui\statsPane.py", line 75, in fitChanged
>  File "C:\projects\pyfa\gui\builtinStatsViews\rechargeViewFull.py", line 113, in refreshPanel
>  File "C:\projects\pyfa\eos\saveddata\fit.py", line 1298, in effectiveSustainableTank
>  File "C:\projects\pyfa\eos\saveddata\fit.py", line 1288, in sustainableTank
>  File "C:\projects\pyfa\eos\saveddata\fit.py", line 1349, in calculateSustainableTank
>KeyError: 'Remote Armor Repairer'
>
>####################
>
>Traceback (most recent call last):
>  File "C:\projects\pyfa\gui\fitCommands\calc\fitRemoveProjectedFit.py", line 27, in Do
>  File "C:\Python36\lib\site-packages\sqlalchemy\ext\associationproxy.py", line 738, in __delitem__
>  File "C:\Python36\lib\site-packages\sqlalchemy\orm\collections.py", line 1234, in __delitem__
>KeyError: 133
>
>####################

**Comment by DarkFenX** [comment]
I fixed this issue in current master. However, i have few questions. But before all, few things to explain:

1) Before adding spoolup support to projected reps, RRs + sustainability calculation worked following way: fit projects RRs on self -> sustainability of RRs is taken into consideration; fit receives RRs from another fit - sustainability of RRs is assumed to always be at 100%
2) After my fix, sustainability of RRs is assumed to be 100% all the time, no matter if they are self-projected or projected from another fit.

Now, options how it can be fixed:
1) Leave current fix - assume 100% uptime all the time
2) Implement old behavior - take sustainability for self-projected RRs into consideration, ignore it for RRs projected from another fits
3) Always take sustainability into consideration, even when receiving RRs from another fit. This one will definitely require certain investigations to be done (to make sure it is sane from logic PoV when it comes to sustainability calcs, and attainable within current pyfa fitting engine)

I need some feedback on how would you (and other users) prefer it to behave. I suppose 3) is the most preferred, if not then 1), and 2) looks weirdest to me (but that's how it worked, might implement it for "compatibility")

**Comment by ftsartek** [comment]
3 is probably the best option, yes - especially since sustainability (particularly under neut pressure) is of interest.

**Comment by DarkFenX** [comment]
But out of 1) and 2), which option would you prefer? Current code 1) could be relatively easy changed to 2), because we know that current engine provides functionality to do that.

For 3), separate issue will be created anyway.

**Comment by ftsartek** [comment]
I think 2 is probably the better option of the two because it allows for at least SOME sustainability calculation.

**Comment by DarkFenX** [comment]
Ok. Let's leave this issue open until I change current code to implement old logic 2), then #1826 can be used to track progress on 3)

**Comment by blitzmann** [comment]
Closing this as the issue has been fixed, and another issue was created to work on better supporting projected RR values (if possible)
