### ISSUE TITLE
Module info causes error

### ISSUE THREAD

**Issue by Manngunner** [pyfa-org/Pyfa#1831]
### Other relevant information:
I've tried the newer versions of wxPython and SQLAlchemy but this did not work either.

pyfa v2.7.0 (git)
EVE Data Version: 1435052 (2018-12-12 09:48:30)

OS version: Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.0.5
Logbook version: 1.4.1
Requests version: 2.21.0
Dateutil version: 2.7.5

####################

Traceback (most recent call last):
  File "/tmp/Pyfa-2.7.0/gui/contextMenu.py", line 138, in handler
    menuHandler.activate(context, selection, i)
  File "/tmp/Pyfa-2.7.0/gui/builtinContextMenus/itemStats.py", line 69, in activate
    ItemStatsDialog(stuff, fullContext)
  File "/tmp/Pyfa-2.7.0/gui/itemStats.py", line 99, in __init__
    self.container = ItemStatsContainer(self, victim, item, itmContext)
  File "/tmp/Pyfa-2.7.0/gui/itemStats.py", line 171, in __init__
    self.desc = ItemDescription(self.nbContainer, stuff, item)
  File "/tmp/Pyfa-2.7.0/gui/builtinItemStatsViews/itemDescription.py", line 28, in __init__
    wx.C2S_HTML_SYNTAX) + "' >" + desc + "</body>"
wx._core.wxAssertionError: C++ assertion "isOpaque" failed at /tmp/pip-build-h4d7obxh/wxPython/ext/wxWidgets/src/common/colourcmn.cpp(228) in GetAsString(): alpha is lost in HTML syntax

**Comment by blitzmann** [comment]
Is this the first time it's happened? How about with earlier versions (if you've used earlier versions)?

The errors is with the Item Description tab, and to my knowledge there hasn't been any work on that piece of code in a while, so unsure why it's throwing errors all of a sudden

**Comment by blitzmann** [comment]
Also, do you know which module this was that you tried to open? Even if it seems to be every module, be specific :)

**Comment by blitzmann** [comment]
@Manngunner I assume you have, as part of your theme, opacity set (can see through windows), correct? I think that's why it's breaking - we're trying to convert the windows color to a hex code, but hex doesn't support alpha channel, which allows for the see through.

I think I have a fix that might work, if you can please test the lastest master and let me know

**Comment by blitzmann** [comment]
I'm curious... can you post a screenshot of what it looks like?
