### ISSUE TITLE
[2.7.0] Inertial Stabilizers signature modifier computed without stacking penalty

### ISSUE THREAD

**Issue by vmech** [pyfa-org/Pyfa#1832]
Signature modifiers for stack of Inertial Stabilizers computed without stacking penalties and show much more resulting value than real (showed ingame Fitting/Simulation).

Perhaps when calculating rigs with signature modifier there is a similar problem (**can't confirm for sure**).

### Expected behavior:
Signature radius = **164** (Astronautics rigging skill in **4**)

![](https://i.imgur.com/Fcr3EfD.png)

### Actual behavior:
Signature radius = **181**

![](https://i.imgur.com/wTalw1O.png)

### Fits involved in EFT format (Edit > To Clipboard > EFT):

[Viator, Viator]
Inertial Stabilizers II
Inertial Stabilizers II
Inertial Stabilizers II

Republic Fleet Medium Shield Extender
50MN Y-T8 Compact Microwarpdrive
EM Ward Amplifier II

Covert Ops Cloaking Device II
Small Tractor Beam II

Medium Hyperspatial Velocity Optimizer II
Medium Cargohold Optimization II

### Release or development git branch? Please note the release version or commit hash:

Release 2.7.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10 64-bit

**Comment by blitzmann** [comment]
Hrm, you're right, Inertial Stabalizers were not penalized. Fixed. :)
