### ISSUE TITLE
Implants do not re-calculate signature after removing

### ISSUE THREAD

**Issue by billytheme** [pyfa-org/Pyfa#1833]
## Bug Report
When removing any implants, pyfa does not recalculate the relevant stats, leaving them on their impant values, rather than recalculated to the implant-less value

### Expected behavior:
When removing implants, pyfa should recalculate relevant stats

### Actual behavior:
When removing implants, pyfa does not recalculate relevant stats

### Detailed steps to reproduce:
Create fit
Note down an attribute to be affected by an implant
Add relevant implant to Fit
Observe the attribute has changed
Remove implant from fit
Observe attribute has not changed back to it's original value

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Retribution, Retribution]

Coreli A-Type Small Armor Repairer
EFFA Compact Assault Damage Control
Nanofiber Internal Structure II
Heat Sink II
Extruded Compact Heat Sink

5MN Quad LiF Restrained Microwarpdrive
Eutectic Compact Cap Recharger

Small Focused Beam Laser II
Small Focused Beam Laser II
[Empty High slot]
Small Focused Beam Laser II
Small Focused Beam Laser II

Small Capacitor Control Circuit II
Small Capacitor Control Circuit II

Aurora S x4
Gleam S x4
Imperial Navy Gamma S x4
Imperial Navy Infrared S x4
Imperial Navy Standard S x4
Imperial Navy Ultraviolet S x4

### Release or development git branch? Please note the release version or commit hash:
Release 2.5.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
Tested with Snakes, Halos, Slaves, and Inherent Implants 'Noble' Repair Systems RS-601

**Comment by DarkFenX** [comment]
Works on Mac OS X on 2.7.0 for me (tested with LG slave epsilon). @billytheme could you check on the latest release?

**Comment by DarkFenX** [comment]
Also please check which implant mode Pyfa is using (character-specific of fit-specific implants) when you're reproducing issue.

**Comment by billytheme** [comment]
Yep, it appears somewhere along the line I either clicked "stop reminding me to update" or something. because I updated and the bug was fixed.

**Comment by DarkFenX** [comment]
ok cool, closing then
