### ISSUE TITLE
Scrolling up/down on mutated module sliders doesn't work on Mac OS X

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1834]
1. Open leshak fit
2. Add entropic radiation sink II
3. Apply decayed mutaplasmid to it
4. Open module properties
5. Scroll up/down above spin box (tried with touchpad)

Result:
Value doesn't change

Expected:
Value changes like I press up/down spinbox buttons

Pyfa 2.7.0, Mac OS X 10.14 (18A391)

**Comment by blitzmann** [comment]
Seems like this is missing in windows too.

**Comment by DarkFenX** [comment]
It does work for quite many releases now (do not remember when I changed scrolling up/down event handling), but scrolls a little too fast to my taste. No idea how to change that, and it's topic for another ticket.
