### ISSUE TITLE
Bomb Deployment Changes.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1838]
Just a heads up. Hoboleaks shows this change for 15/1/2019 patch.

28073 - Bomb Deployment (Missiles) , Rate Of Fire Bonus: -10.0 => None
Reactivation Delay Reduction: None => -10.0

So skillBombDeploymentModuleReactivationDelayBonus
will probably need to be modified sometime in the future.

**Comment by DarkFenX** [comment]
Taken care of in latest master.
