### ISSUE TITLE
Feature Request: Support Ctrl+Backspace for deleting whole words in search bar

### ISSUE THREAD

**Issue by lunedis** [pyfa-org/Pyfa#1845]
In many text applications you can use Ctrl+Backspace to delete whole words.

This does not work in Pyfa (tested on OS Win 7), it just writes a small rectangle.

**Comment by blitzmann** [comment]
Hrm, interesting... Gonna mark this as `help wanted` - this is a pretty minor bug, but I think it might be easy enough for anyone to pick up and attempt a fix (or at least research into it). I just don't have a whole lot of time right now :(

**Comment by WatchMeCalculate** [comment]
FWIW:
https://trac.wxwidgets.org/ticket/10344
this is a known issue/wontfix

**Comment by blitzmann** [comment]
Well, that thread is a wild ride. Nice catch! Will review your PR and hopefully get this merged in / provide feedback
