### ISSUE TITLE
EHE value not being applied correctly

### ISSUE THREAD

**Issue by muleooo** [pyfa-org/Pyfa#1854]
## Bug Report
Pyfa's Emergency Hull Energizer's effect on the hull resists doesn't match those that the game calculates. Pyfa seems to be ignoring the base hull resist.

### Expected behavior:
EHE's 95% hull resist should be applied on top of the base 33%, ie. 1-(1-0.33)(1-0.95)=0.9665=97%

### Actual behavior:
Pyfa just sets the hull resist to 95%, ignoring the base resist

### Detailed steps to reproduce:
1. Simulate/fit EHE to a hull in EVE
2. Fit EHE to a hull in Pyfa
3. Observe that there's a discrepancy

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Apostle, Apostle fit]

Capital Emergency Hull Energizer I
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
2.7.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by DarkFenX** [comment]
Indeed, quite significant bug, i wonder why nobody noticed it yet. Game applies this modification with postMul operator and we did postAssign instead. Fixed in 509849fbf5448652abaf3c009103139bafe5465c
