### ISSUE TITLE
Installation instructions for linux

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#186]
Got following mail recently:

hello i'm Lele.

put this into " read me "

sudo apt-get install python-dateutil python-sqlalchemy python-wxglade

Not all people are expert about Linux.

bye
Lele

**Comment by poettler-ric** [comment]
For Fedora <= 21 (and probably CentOS 6/7)  it is:
```sudo yum install wxPython python-sqlalchemy python-dateutil```

If you're lazy you can use the rpm I've built (I will try to keep it up-to-date as long as I am playing EVE):
https://copr.fedoraproject.org/coprs/poettlerric/pyfa/
The sources for the rpm are available here (feel free to steal from it or fork it):
https://github.com/poettler-ric/fedora-spec/tree/master/pyfa
