### ISSUE TITLE
update requirements.txt

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1861]
theres a couple of security updates, as well as an updated wxpython. This is actually already done just making an issue to remember to mention it for release logs

if you run pyfa from source, one breaking change: you will need to update pyyaml. The other updates are recommended, but optional for a functioning application. :)

**Comment by ForlornWongraven** [comment]
Can you add this information about pyyaml in https://github.com/pyfa-org/Pyfa#dependencies ?

**Comment by DarkFenX** [comment]
@ForlornWongraven why about pyyaml? It's just one of dependencies and it is listed in requirements.txt

**Comment by ForlornWongraven** [comment]
I could only install the requested wxPython version after I upgraded pyyaml. Due to the requirement.txt pip tries to install wxPython before anything else so I always ended up with an wxPython error.

pip3 install --user --upgrade pyyaml
pip3 install --user -r requirements.txt

**Comment by DarkFenX** [comment]
What is your pip version and OS? I will try to replicate it - to ensure that reordering works.

**Comment by ForlornWongraven** [comment]
lsb_release -id 
Distributor ID:	Fedora
Description:	Fedora release 30 (Thirty)

pip3 --version
pip 19.0.3 from /usr/lib/python3.7/site-packages/pip (python 3.7)

uname -r 
5.2.9-200.fc30.x86_64

**Comment by DarkFenX** [comment]
See #2025. Fill new issue next time please.

I will try to check it out on next week.
