### ISSUE TITLE
Move all enums to `eos.const` (and convert to built-in enums)

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1862]
Right now Enums are strewn around the various class files (eg: ImplantLocation is in `fit.py`). These can cause issues if you need just the Enum without all the other crust that the file imports.

I've created `eos.cont` and moved `Module.Slots` enum to that to better support a feature that was merged in. We should take some time to continue this process and move all the other definitions into this file.

Additionally, should evaluate using Python 3's built-in enums. This will cause some issues for some definitions (Slot was one of them), so we should be careful and test each application. But this should be a relatively easy code cleanup effort.

Going to mark this as `help wanted` ass it's generally low-level and doesn't require a whole lot of planning or complexity. If someone wants to take a whack at it before I can get around to it, feel free - just state your intention here :)

**Comment by DarkFenX** [comment]
You can use https://github.com/pyfa-org/eos/tree/master/eos/const as reference. Pretty sure similar organization is one of the better (at least, if current eos uses any EVE constants).

**Comment by blitzmann** [comment]
@DarkFenX This is a slightly different request, although the confusion doesn't help since I named the file `const` lol. We don't really have EVE constants anywhere in pyfa, and if we do they are scattered around. Not debating whether or not we should have a const fiile much like what new eos has eventually, but this was more directed towards all the enums that we have that are intertwined with other modules. This makes it difficult to simply import the enum without importing the rest of the things. For example, GUI needs to import ImplantLocation to use it. However, to import it, we must also import all the imports in `eos.saveddata.fit` which is probably something we don't really want. I ran into this problem for the Slot enum, where importing it from `eos.saveddata.module` caused errors because other things had to load that couldn't at that time. :)

**Comment by IndictionEve** [comment]
It's done.
This was way more tricky then expected. From a freaking out code interpreter during rewriteing the code, to figuring out the different behavors of eos.enum to python.enum and make it work again.
I changed the code step by step and made a lot of tests to make sure everything works like before. 
I hope you are fine with the result.

**Comment by blitzmann** [comment]
Thanks @IndictionEve for taking on this task! I haven't had time to really dig through the changes, but will hopefully get to it this week and provide feedback / merge as-is :) From what I've seen though on the PR, everything looks pretty solid.
