### ISSUE TITLE
Error deleting implant

### ISSUE THREAD

**Issue by brightvalley** [pyfa-org/Pyfa#1863]
When I attempted to delete an implant (highlight and press delete key) from the additions/implants tab I received the following error:

pyfa vv2.7.0
EVE Data Version: 1435052 (2018-12-12 03:48:30)

OS version: Windows-10-10.0.17134-SP0
Python version: 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.0.5
Logbook version: 1.4.1
Requests version: 2.21.0
Dateutil version: 2.7.5

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\builtinAdditionPanes\implantView.py", line 145, in kbEvent
  File "C:\projects\pyfa\gui\builtinAdditionPanes\implantView.py", line 207, in removeImplant
ValueError: Implant(ID=10217, name=Ocular Filter - Improved) at 0xbfa73b0 is not in list

**Comment by blitzmann** [comment]
Hi @brightvalley !

Can you consistently reproduce this issue? I just attempted it and didn't get any issue. The error itself is saying that the implant that you're trying to delete isn't in the list, which is weird.

**Comment by blitzmann** [comment]
Aha, seems to be when you attempt to delete an implant from the Character implant source.

Just and fyi, the character implants aren't removable from the fitting window - you must manage them through the character editor. But this is something that we should check to avoid error
