### ISSUE TITLE
Evaluate feasibility and effectiveness of combining all effects into one file during build time

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1864]
One of the things that never sat right with me is the fact that pyfa's effects are literal python files that get imported during runtime when needed. Although usually minor, importing can cause performance issues. Looking at a profile for #1605, the `io.open` due to the import is the biggest draw (unsure if this is causing everyones startup lag issues, or just an individual). It should be noted that not everyone experiences this (I can't reproduce on any of my machines).

I was thinking, it might be an interesting exercise to try to combine these effect files into one module that would be imported. 

From:

```
# energyNeutralizerFalloff
#
# Used by:
# Modules from group: Energy Neutralizer (54 of 54)
from eos.saveddata.module import State
from eos.modifiedAttributeDict import ModifiedAttributeDict

type = "active", "projected"


def handler(fit, src, context, **kwargs):
    if "projected" in context and ((hasattr(src, "state") and src.state >= State.ACTIVE) or
                                    hasattr(src, "amountActive")):
        amount = src.getModifiedItemAttr("energyNeutralizerAmount")

        if 'effect' in kwargs:
            amount *= ModifiedAttributeDict.getResistance(fit, kwargs['effect'])

        time = src.getModifiedItemAttr("duration")

        fit.addDrain(src, time, amount, 0)
```

To something like this:

```

...

def energyneutralizerfalloff():
    from eos.saveddata.module import State
    from eos.modifiedAttributeDict import ModifiedAttributeDict
    
    type = "active", "projected"
    
    
    def handler(fit, src, context, **kwargs):
        if "projected" in context and ((hasattr(src, "state") and src.state >= State.ACTIVE) or
                                        hasattr(src, "amountActive")):
            amount = src.getModifiedItemAttr("energyNeutralizerAmount")
    
            if 'effect' in kwargs:
                amount *= ModifiedAttributeDict.getResistance(fit, kwargs['effect'])
    
            time = src.getModifiedItemAttr("duration")
    
            fit.addDrain(src, time, amount, 0)

    return locals()

...
```

Each effect would be given it's own function - we would use the same as the current filename. That function will do everything the file did, including imports, The current effect generator would then simply run this function to get back a list of locals, which would allow us to access the internal handler / types / anything else we use for it.

This would be something that would be available on builds, not from source. That should allow us as developers to continue using the same structure we've been using. 

It should be stressed that this is all theoretical - not been tested or anything. Just putting up an issue so that I can remember to try it out at some point.

**Comment by blitzmann** [comment]
Generating this file was actually incredibly simple... `effect_rollup` branch. There's probably some errors (I can think of booster side effects off the top of my head) but for the most part it works. I can't speak yet as tot he performance difference of this, gonna have to dig a bit deeper into that and also test out the generated build for this branch.

**Comment by DarkFenX** [comment]
Please make them case-sensitive then. IIRC there were issues in the past due to collisions in names (some industrial ship-related bonuses).

**Comment by blitzmann** [comment]
I agree @DarkFenX . I've made the change to have the files names `effect<ID>.py`. When these are rolled up. I still have a few things that I need to test before marking this complete, then I want to try to profile it and see if there's any discernible difference having all effects live within one file for builds.
