### ISSUE TITLE
Feature Request: Range of Projected

### ISSUE THREAD

**Issue by tungstenmeteor** [pyfa-org/Pyfa#1865]
Might be a tall ask, but it would be amazing to choose how far away a ship or structure is while projecting it onto a fit, in part to test cap stability against neutralizers outside their optimal range.

Could be expanded upon with an 'incoming dps' section alongside firepower/reps/etc. to test a fit's tank against incoming DPS at varying ranges.

Thanks for your time either way!

**Comment by blitzmann** [comment]
> Might be a tall ask

Probably is. While this information would be good to have, I'm not sure how feasible it would be to implement within the current codebase. We can certainly have a range associated with projects modules and fits, but taking that into consideration when applying the modifications maybe more trouble than it's worth unfortunately.

It's definitely something to look into though the next time we're playing around in that bit of the codebase :)

**Comment by DarkFenX** [comment]
FYI i think it is doable and I mostly got it working in projected_range branch. I've added support for projection range to database and pass it through calculation engine to effects. UI part is done as well. Out of actual effects, only scram effect is changed to support it. It works, so now we need to change more effects, and feature will be done.

How it works:
- projection of fit: modules of the projected fit are projected at the specified range, drones/fighters at 0 (intended)
- drones, fighters, modules: projected at specified range

Projection range is passed to the effect, so we might implement support for some effects but ignore in others (e.g. i see little sense to implement it for bombs).

**Comment by DarkFenX** [comment]
ef226898c06792de853682035d794849f6488187 adds effect support
