### ISSUE TITLE
Character Editor Skills not shown

### ISSUE THREAD

**Issue by Roesjka** [pyfa-org/Pyfa#1866]
## Bug Report
pyfa: Character Editor

### Expected behavior:
Showing Skills

### Actual behavior:
Only seeing an S and Level
![image](https://user-images.githubusercontent.com/12376567/53892994-a0faae80-402d-11e9-9a61-e73e7ffd5fe9.png)

### Detailed steps to reproduce:
Just opening Character Editor

### Fits involved in EFT format (Edit > To Clipboard > EFT):
Fits not involved, they show fine.

### Release or development git branch? Please note the release version or commit hash:
Pyfa 2.70

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Debian buster

### Other relevant information:
On Win10 it shows fine. On Debian its just annoying. If it has been reported earlier or if their is a fix
my apologies for not finding it.

**Comment by DarkFenX** [comment]
This is known issue with specific version of wx on specific platforms. I am debian user myself and it works fine under wayland and is bugged under xorg (or vice versa). Will find and link issue later.

**Comment by DarkFenX** [comment]
Just checked and it works under wayland (so most likely doesn't under xorg - will check at home).

I can't find issue in our repository, but it's definitely a bug which has been known. I just don't know if there's an upstream issue which tracks it, @blitzmann might know more.

**Comment by blitzmann** [comment]
> This is known issue with specific version of wx on specific platforms.

I think this is actually different than https://github.com/pyfa-org/Pyfa/issues/1421. I didn't know this was a thing. Confirmed broken on Ubuntu on my end. :/

**Comment by blitzmann** [comment]
Got a temp fix for it in `master`

TreeListCtrl behaves very oddly. On GTK, it doesn't seem like you can resize the columns even though they [default to resizable](https://wxpython.org/Phoenix/docs/html/wx.dataview.TreeListCtrl.html#wx.dataview.TreeListCtrl.AppendColumn)

On GTK (with the fix), the level column is abnormally large, whereas on windows it's a fine width, but part of it is hidden with horizontal scrolling:

![image](https://user-images.githubusercontent.com/3904767/54491334-2daa3580-4894-11e9-8569-bc09eb7ef892.png)

![image](https://user-images.githubusercontent.com/3904767/54491340-369b0700-4894-11e9-8289-1c861f538d20.png)

Additionally, I wasn't able to get a barebones example working for the original issue to report back upstream. One of these days when I get a bit more time I'll look into this issue a bit further, but for now it should at least be usable :)

**Comment by Roesjka** [comment]
Thanks very much, it works fine for me now. :+1:
