### ISSUE TITLE
Module Variation Inconsistacy.

### ISSUE THREAD

**Issue by ASB2** [pyfa-org/Pyfa#1870]
## Bug Report

On any ship that can fit a non covert ops cloak, when you right click and choose a covert ops cloak from the variations sub menu the covert ops cloak will be fitted to the ship and then it will be automatically removed leaving an empty high slot. 
### Expected behavior:

Covert Ops Cloak either does not appear in the variations sub menu or covert ops cloak is not selectable. 

### Actual behavior:

When covert ops cloak is selected and placed on the ship, then the cloak module will then be removed from the ship automatically cause it is not a valid module for the selected ship type. 

### Detailed steps to reproduce:

Select Panther in the fitting window.

Fit an improved cloaking device II to the ship. 

Right click the Improved Cloaking Device II then select the variations submenu and then click on Covert OPs Cloaking Device II 

The improved cloaking device II will be replaced by the covert ops cloaking device II. The covert ops cloaking device II wil then be removed from the ship and the high slot will be empty.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

[Panther, Panther fit]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Improved Cloaking Device II
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:

Release Version

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10

### Other relevant information:
Works with any ship that can fit a non covert ops cloaking device.

**Comment by blitzmann** [comment]
So there's two issues:

* Cov Ops cloak doesn't actually fit this ship.
* Because of this, replace the module with it fails. Before we replace the module, we need to remove the previous module. We never undo that removal.

I have an idea on how to address both issues

**Comment by blitzmann** [comment]
This was easier than expected, however I'm going to want @DarkFenX  to have a quick look at the code before I merge into master, simply because it touches low level logic on what allows modules to fit.

![image](https://user-images.githubusercontent.com/3904767/54502244-f4a7aa80-48ff-11e9-9379-6cfad08ee049.png)
