### ISSUE TITLE
Export options take too much space

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1872]
Debian Testing x86-64
Pyfa from price_optimize branch (commit 22fc6cb13c93267770fa5e51c22fed401cab499f)
Xorg, GNOME 3 with standard theme, 3840x2160 with 200% UI scaling
Python 3.7.2
wxPython version: 4.0.4 (wxWidgets 3.0.4) from debian repos

When several formats specify export options, sizer with export options takes height of the tallest export option sizer. I.e. if one format has 4 options and another 3, both will have height of 4 "rows".

![image](https://user-images.githubusercontent.com/275209/54076025-715ed700-42b7-11e9-8bab-eee066df0b4f.png)
(notice how EFT section has much more padding between options)

This bug appears with proportion attribute of these sizers set to 1 (commit d2b306d0302d6f66890578373deb0eae32531e96 changed them to 0 as temporary workaround).

**Comment by DarkFenX** [comment]
Filled upstream bug as https://github.com/wxWidgets/Phoenix/issues/1181

**Comment by blitzmann** [comment]
@DarkFenX I think we determined this to be a proportion issue with the sizer? Can we mark this as fixed, or was there something else broken about it that I'm forgetting lol

**Comment by DarkFenX** [comment]
Just my understanding is broken. I thought that sizers will scale to window size proportionally to its contents, but apparently not.

**Comment by blitzmann** [comment]
Closing this as it related to an issue that presented after latest release
