### ISSUE TITLE
Pyfa 2.7.0 error on Ubuntu 18.04

### ISSUE THREAD

**Issue by ArticFoxNL76** [pyfa-org/Pyfa#1875]
pyfa v2.7.0 (git)
EVE Data Version: 1435052 (2018-12-12 10:48:30)

OS version: Linux-4.18.0-16-generic-x86_64-with-Ubuntu-18.04-bionic
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0]
wxPython version: 4.0.1 (wxWidgets 3.0.4)
SQLAlchemy version: 1.3.1
Logbook version: 1.4.3
Requests version: 2.18.4
Dateutil version: 2.8.0

####################

Traceback (most recent call last):
File "pyfa.py", line 132, in
from gui.mainFrame import MainFrame
File "/home/articfox/bin/Pyfa-2.7.0/gui/mainFrame.py", line 53, in
from gui.copySelectDialog import CopySelectDialog
File "/home/articfox/bin/Pyfa-2.7.0/gui/copySelectDialog.py", line 23, in
from service.port.eft import EFT_OPTIONS
File "/home/articfox/bin/Pyfa-2.7.0/service/port/init.py", line 2, in
from .port import Port, IPortUser
File "/home/articfox/bin/Pyfa-2.7.0/service/port/port.py", line 28, in
from bs4 import UnicodeDammit
ModuleNotFoundError: No module named 'bs4'

I am getting this error and i cannot seem to find the problem, please help me out.

Tnx

**Comment by ArticFoxNL76** [comment]
I found the problem bs4 not installed fixt it with this command;

sudo apt-get install python3-bs4

Tnx

**Comment by blitzmann** [comment]
for future reference, it's much easier to not go through the distro package manager to get the dependancies, but rather go through `pip`. The only package that I can think of that would benefit from a distro package would be wxPython, and that's simply because there are binary components to it

**Comment by DarkFenX** [comment]
It makes sense to install via distro package manager just because these dependencies will not break when python is upgraded, unlike pip-installed dependencies.
