### ISSUE TITLE
C++ assertion "item.IsOk()" failed

### ISSUE THREAD

**Issue by robert-zibreg** [pyfa-org/Pyfa#1879]
## Bug Report
Pyfa error displayed when right clicking searched item and selecting Implant Market Group

### Expected behavior:
Implant Market Group is opened

### Actual behavior:
pyfa error

### Detailed steps to reproduce:
Open Pyfa, paste Impetus Glamourex Booster in Market search, two results pop up, right click first result -> click Implant Market Group

### Fits involved in EFT format (Edit > To Clipboard > EFT):
no fits were open at the time (empty tab)

### Release or development git branch? Please note the release version or commit hash:
pyfa vv2.7.0
EVE Data Version: 1435052 (2018-12-12 10:48:30)

OS version: Windows-10-10.0.17763-SP0
Python version: 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.0.5
Logbook version: 1.4.1
Requests version: 2.21.0
Dateutil version: 2.7.5

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
Stack:
`Traceback (most recent call last):
  File "C:\projects\pyfa\gui\contextMenu.py", line 138, in handler
  File "C:\projects\pyfa\gui\builtinContextMenus\marketJump.py", line 51, in activate
  File "C:\projects\pyfa\gui\marketBrowser.py", line 100, in jump
  File "C:\projects\pyfa\gui\builtinMarketBrowser\marketTree.py", line 92, in jump
wx._core.wxAssertionError: C++ assertion "item.IsOk()" failed at ..\..\src\msw\treectrl.cpp(1032) in wxTreeCtrl::GetItemParam(): invalid tree item`

**Comment by blitzmann** [comment]
I cannot reproduce on latest master, but can on the latest 2.7.0 release. This leads me to think that this has been solved (and I remember addressing an issue with market groups, don't remember what it was exactly though)

Going to assume this has been fixed, but will keep this open until we make a new release to verify. :)

**Comment by robert-zibreg** [comment]
@blitzmann Sounds good, will wait for new release

**Comment by blitzmann** [comment]
@robert-zibreg let us know if you run into this issue again :)
