### ISSUE TITLE
Abyssal Weather projected effects do not apply to drones

### ISSUE THREAD

**Issue by fonsui** [pyfa-org/Pyfa#1880]
The two effects applied by each Abyssal weather type are not applied to drones. The following drone stats are affected by Abyssal weather, and are therefore subject to inaccuracy until this is remedied:

1) Each individual damage type resistance, for shields, armor, and hull (all sites but Dark)
2) Scan resolution (Exotic)
3) Armor HP (Firestorm)
4) Shield HP (Gamma)
5) Velocity (Dark)
6) Optimal range (Dark)
7) Falloff range (Dark)

To verify this, simply observe the reported stats both with and without the weather effect applied, and examine the "Affected by" tab in the "Drone info" dialog.

**Comment by DarkFenX** [comment]
How did you check that these effects do apply to drones? I know that 5-7 are likely to be true (at the very least 6), but not about others.

**Comment by IndictionEve** [comment]
A corpmate confirmed this. 
Abyssal effects apply on drones, too.

**Comment by fonsui** [comment]
It is widely known that these effects apply to drones, but if you would like confirmation I can grab some screenshots. Please let me know if you would like this.

**Comment by DarkFenX** [comment]
No, i do not think it's needed. 

We just should keep in mind that every effect which affects ship directly also affects drones (e.g. system-wide effects, projected effects applied to drones etc). We will fix abyssal effects before next release.

**Comment by fonsui** [comment]
Just checked on Singularity, charges loaded in launchers are not affected by Abyss resistance penalties. Doubtful that they would apply in space, as viewing the loaded charge information shows all stats as impacted by the actual current scenario.

**Comment by DarkFenX** [comment]
I meant charges in space. You can check that by smartbombing thermal missile with thermal smartbomb in k-space and in firestorm, for example.

**Comment by fonsui** [comment]
Understood, so the attributes on a loaded charge are modified by hull/skills/implants/boosters, but not the weather; that only happens once a charge is in space. If I have the opportunity to test this, I will do so.

**Comment by DarkFenX** [comment]
I am confident that attributes of loaded charges are not modified. Guns (which do not launch any actual projectiles) do not modify their charges. Missiles gain modified attributes once they are launched in space (all the damage multipliers are applied to their base damage values, for example). In theory CCP could show modified attributes of a missile or "non-assembled" drones in cargo, but that most likely will use client-side dogma which works a little differently.

Anyway, small test with thermal missile and smartbomb would help to understand that. Guristas (NOT dread guristas) Inferno Heavy Assault Missile has 240 hp and 20% thermal resistances (300 ehp vs thermal). Medium t2 plasma smartbomb deals 140 thermal damage. If my understanding is correct, it would deal 112 damage to missile in k-space and 140 damage in firestorm.

**Comment by fonsuiplaysvideogames** [comment]
I discussed this with CCP Signal, who works closely with this system, and he confirmed that all entities in space are impacted by these environmental effects. This includes missiles and drones.

**Comment by fonsuiplaysvideogames** [comment]
With the introduction of permanent Hydra implants, it would be helpful to my work on building a Dark Abyss Gila if this issue was addressed. If you can squeeze in the time to deal with this one, it would be appreciated. I cannot write code myself, but if there is reference work to do (looking up typeIDs, attributes, etc.) I can offer my assistance with that.

**Comment by DarkFenX** [comment]
@fonsuiplaysvideogames it should be somewhat simple. Find all abyssal effects which affect drones, find those effects in `eos/effects.py` (huge file with all the definitions) and add code which affects drones. More often than not you even do not have to code anything yourself, just find how it is implemented in other effects and copy-paste, changing attribute values.

This is how I got into coding pyfa btw, not knowing how to code as well.

**Comment by fonsuiplaysvideogames** [comment]
Found the place that needed changes, it was in fit.py. Tested locally and it appears to work properly, so I've submitted a pull request for this.
