### ISSUE TITLE
Pyfa crashes on attempt to export to HTML

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1889]
This bug is most likely affects all databases with significant amount of fits. I cannot publish mine due to security concerns.

1. Open pyfa
2. Press "File > Export to HTML"

Expected: full HTML file is generated

Observed: progress bar is shown, approximately at 2 seconds pyfa crashes (closes), traceback is written to stdout:
https://gist.github.com/DarkFenX/5745bec42e277983ded018eff6a9e880

**Comment by blitzmann** [comment]
It works for me on Windows, but I do recall a couple of people running into this recursion issue. How many fits do you have?

**Comment by DarkFenX** [comment]
1136. I was slowly removing them today and I think at around 300-ish it started to crash in just 50% of cases (so it depends on available resources and timings it seems).

**Comment by DarkFenX** [comment]
For some reason it doesn't crash anymore on the very sama machine, Closing issue.
