### ISSUE TITLE
Remove XML and DNA fit export/import facilities

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1891]
Currently they are disabled just on UI in master. If nobody is missing them after the release until the release after that, it's worth to clean the code up.

**Comment by DarkFenX** [comment]
XML is still used to "backup all fits / restore", which is wrong from my perspective, as there's data loss even when it comes to fit itself (data on mutated modules is lost, let alone command booster / projected effect etc). It should be either rewritten to use EFT format which supports more features, or changed to rely on sqlite database file somehow.

**Comment by blitzmann** [comment]
We really should have a lossless format. I've always like the idea of having a standard format like https://github.com/osmium-org/common-loadout-format/blob/master/specifications/spec-common-loadout-format-01.md, one that can be extended.

**Comment by DarkFenX** [comment]
The closest to be lossless is EFT format i believe. However, it loses:

- module status (active/online, but shows offline)
- implant status
- booster status and side-effect status
- drone status
- fighter status and fighter ability status
- projected effects
- command bonuses

**Comment by DarkFenX** [comment]
Apparently some people use those, so closing it.
