### ISSUE TITLE
Do not activate assault DC upon fitting

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1894]
From my perspective such 'emergency mode' modules like ADC (and maybe PANIC) should not be activated when you fit them, as user has to deactivate them to see normal ship stats.

**Comment by blitzmann** [comment]
Do these modules have a "isEmergency" attribute or the like? I don't see how we can do this without hardcoding a list of items / attributes that signal to skip the default state

**Comment by DarkFenX** [comment]
No, it's just my perception of them. Every time i fit ADC to HAC / AF i have to do additional click to turn it off to see its regular stats. I have no such issues with PANIC as I am not fitting rorquals that much (and as pyfa doesn't have PANIC effect implemented), but i just extended my thinking to these too.

**Comment by skyride** [comment]
@blitzmann Assault Damage Control's all have effectID 7012 "moduleBonusAssaultDamageControl".

![image](https://user-images.githubusercontent.com/903638/54941839-bb85c080-4f25-11e9-9ccb-44efcb5f0a94.png)

**Comment by DarkFenX** [comment]
Added in ba337599c2a34c7ba931e4da3678b017b7aa1388
