### ISSUE TITLE
error if try to delete the first item in the projected tab

### ISSUE THREAD

**Issue by psychojf** [pyfa-org/Pyfa#1899]
## Bug Report
if i press delete on the "drag an item of fit...." first line in projected tab it crash

### Expected behavior:
nothing's suppose to happen since it not suppose to be deletable ??

### Actual behavior:
ERROR!
pyfa v2.8.0
EVE Data Version: 1459933 (2019-02-16 05:18:51)

OS version: Windows-10-10.0.17763-SP0
Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]
wxPython version: 4.0.4 (wxWidgets 3.0.5)
SQLAlchemy version: 1.0.5
Logbook version: 1.4.3
Requests version: 2.21.0
Dateutil version: 2.8.0

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\builtinAdditionPanes\projectedView.py", line 132, in kbEvent
  File "C:\projects\pyfa\utils\deprecated.py", line 16, in new_func
  File "C:\projects\pyfa\service\fitDeprecated.py", line 367, in removeProjected
AttributeError: 'NoneType' object has no attribute 'ID'

### Detailed steps to reproduce:
see pic
![image](https://user-images.githubusercontent.com/38178167/54884912-e2bc8f00-4e4c-11e9-9f8b-edb6d3581617.png)

if i click on the item saying "drag an item of fit...." and i press delete it giving me the error here:
![image](https://user-images.githubusercontent.com/38178167/54884929-05e73e80-4e4d-11e9-9038-9ec04c40c5df.png)

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
windows 10

**Comment by blitzmann** [comment]
Thanks! Fixed with above commit

**Comment by psychojf** [comment]
thanks very nice work guys !
