### ISSUE TITLE
Resistance Rigs Applying All Resistances

### ISSUE THREAD

**Issue by LtRoyal** [pyfa-org/Pyfa#1905]
## Bug Report
Resistance Rigs Applying All Resistances

### Expected behavior:
When applying a specific resistance rigs (Small Anti-Thermal Pump II) should only add Thermal resistances to armor.

### Actual behavior:
When applying a specific resistance rigs (Small Anti-Thermal Pump II) or and or different resistances plates; is also adding all other resistances as if it was a Damage Control. 

### Detailed steps to reproduce:
Add any Small armor resistances to to Frigate or Destroyer.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Cruor, Harlett Joss]

Reactive Armor Hardener
Small Ancillary Armor Repairer, Nanite Repair Paste
True Sansha Adaptive Nano Plating
Damage Control II

X5 Enduring Stasis Webifier
J5b Enduring Warp Scrambler
5MN Y-T8 Compact Microwarpdrive

Dual Anode Pulse Particle Stream I, Imperial Navy Multifrequency S
Small Knave Scoped Energy Nosferatu
Dual Anode Pulse Particle Stream I, Imperial Navy Multifrequency S
Small Knave Scoped Energy Nosferatu

Small Anti-Explosive Pump II
Small Energy Collision Accelerator I
Small Anti-Thermal Pump II

Imperial Navy Acolyte x1

Zainou 'Gypsy' CPU Management EE-603

Zainou 'Gypsy' CPU Management EE-601 x1

### Release or development git branch? Please note the release version or commit hash:
Version v2.8.0
Eve Data Version: 1459933 (2019-02-16 10:18:51)

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 8.1

**Comment by DarkFenX** [comment]
Disable reactive armor hardener and check again. If it reproduces - reopen.

**Comment by LtRoyal** [comment]
Thank you and sorry for wasting your time o7
