### ISSUE TITLE
Broken EWAR Drone support for DPS graph

### ISSUE THREAD

**Issue by PaladinOne** [pyfa-org/Pyfa#1911]
Maybe related to #532 from years ago, viewing a DPS Graph for a ship fit equipped with Minmatar E-War Drones (Berserker SW-900, Berserker TP-900), toggling the drones on/off does not impact the graph (in the way that would be expected from what toggling a regular Webifier or Target Painter module does).

Windows 10, pyfa 2.8.0

Example fit:

[Maelstrom, Test]

[Empty Low slot]
Gyrostabilizer II
Gyrostabilizer II
Gyrostabilizer II
Tracking Enhancer II

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
Stasis Webifier II
Target Painter II
Tracking Computer II, Tracking Speed Script

800mm Repeating Cannon II, Republic Fleet EMP L
800mm Repeating Cannon II, Republic Fleet EMP L
800mm Repeating Cannon II, Republic Fleet EMP L
800mm Repeating Cannon II, Republic Fleet EMP L
800mm Repeating Cannon II, Republic Fleet EMP L
800mm Repeating Cannon II, Republic Fleet EMP L
800mm Repeating Cannon II, Republic Fleet EMP L
800mm Repeating Cannon II, Republic Fleet EMP L

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

Berserker SW-900 x2
Berserker TP-900 x2

Generating a DPS Graph vs a sample target {10 degrees, 0-20km range, 100 sig radius, 3000 velocity}, toggling whether the Drones are on or off does not affect the graph.

**Comment by DarkFenX** [comment]
Done in dps_sim_graph branch 
![image](https://user-images.githubusercontent.com/275209/60825451-65771900-a1b4-11e9-93c7-1497d7744bba.png)
