### ISSUE TITLE
Covert Ops Cloak II using 10100tf CPU on Tengu

### ISSUE THREAD

**Issue by Oenoes** [pyfa-org/Pyfa#1912]
### Expected behavior:
Cover Ops Cloaking Device II should use 100tf of CPU

### Actual behavior:
Cover Ops Cloaking Device II adds 10100tf to the CPU load for a Tengu hull

### Detailed steps to reproduce:
Try to add a Covert Ops Cloaking Device II to the following fit.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Tengu, Tengu]

Ballistic Control System II
Caldari Navy Ballistic Control System
Damage Control II

Federation Navy 10MN Afterburner
Gistum B-Type Medium Shield Booster
Pith B-Type Shield Boost Amplifier
Adaptive Invulnerability Field II
Adaptive Invulnerability Field II
EM Ward Field II
Missile Guidance Computer II, Missile Range Script

Heavy Missile Launcher II, Scourge Fury Heavy Missile
Heavy Missile Launcher II, Scourge Fury Heavy Missile
Heavy Missile Launcher II, Scourge Fury Heavy Missile
Heavy Missile Launcher II, Scourge Fury Heavy Missile
Heavy Missile Launcher II, Scourge Fury Heavy Missile
Heavy Missile Launcher II, Scourge Fury Heavy Missile
[Empty High slot]

Medium Capacitor Control Circuit I
Medium Bay Loading Accelerator I
Medium Core Defense Operational Solidifier I

Tengu Core - Electronic Efficiency Gate
Tengu Defensive - Amplification Node
Tengu Offensive - Accelerated Ejection Bay
Tengu Propulsion - Chassis Optimization

### Release or development git branch? Please note the release version or commit hash:
v2.8.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by DarkFenX** [comment]
Expected behavior when you do not have covops subsystem fitted. Heavily penalizing CPU for non-covops subs is the way CCP prevents players from using it, unless covops sub is fitted.
