### ISSUE TITLE
Changing mutated item stats is not undoable

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1920]

**Comment by blitzmann** [comment]
> The only remaining item is undo of mutator value changes, which might be tricky to do as it will need to be reflected on item stats windows, if they are still open.

Just my 2c, I don't think we should track the changes as they are applied in the item stats window, but rather track the changes as they are when the user closes the item stats window. The reason being that tweaking the stats could cause a large amount of "StatChange" commands to queue up, even if they don't represent values the user was looking for. So it would be annoying to have to hit undo 20 times which would undo various tweaks. 

Either that, or we can have a separate queue while the window is open, and undoing while the window has focus would undo those tweaks, but they won't be posted to the fit as "finalized" stats until the window closes

**Comment by DarkFenX** [comment]
I thought about that and i agree. I created this issue because this tracking, as well as UI implementation (some "apply" button) takes time and i do not have it atm, rather would do it later.

**Comment by DarkFenX** [comment]
Also, i think we should discuss how it works UI-wise. I'd like to have following 2 things:

- ability to preview item changes on main fitting screen (i.e. fit recalculation as we're changing the values, like we have now)
- ability to aggregate multiple changes into single command

So, UI-wise i see following solution: add 1 button to mutaplasmid page, "revert", which reverts to initial state of item (at the time stats window was opened). This way it's possible to:

- revert to old values and keep changing stats as you wish
-

**Comment by DarkFenX** [comment]
Fixed in b3ef55cb7f03d70c1412412310eea0e4c02e832c
