### ISSUE TITLE
Typo on module stats window

### ISSUE THREAD

**Issue by kiwimind** [pyfa-org/Pyfa#1924]
## Bug Report
When viewing the module stats window, there is a typo:
![image](https://user-images.githubusercontent.com/114639/56221193-b36efb80-6061-11e9-8d0b-cad92ed519cd.png)

Veiw should read View.

### Detailed steps to reproduce:
Right click on a module and view its stats, then go to Attributes tab.

### Release or development git branch? Please note the release version or commit hash:
v2.8.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
OS X 10.14.4

**Comment by kiwimind** [comment]
PR raised

**Comment by DarkFenX** [comment]
Thanks.
