### ISSUE TITLE
Fitting wrong-size rigs can crash pyfa

### ISSUE THREAD

**Issue by Migi** [pyfa-org/Pyfa#1929]
## Bug Report

Fitting wrong-sized rigs can crash pyfa.

### Expected behavior:

Fitting wrong-sized rigs should either show a pop-up that the hull doesn't allow those rigs, or it should just do nothing.

### Actual behavior:

Sometimes, it crashes the program immediately. Sometimes it only crashes pyfa after trying to interact with that rig (removing it or replacing it with another module).

### Detailed steps to reproduce:

1. Open pyfa
2. Create a new fit for a frigate.
3. Drag a large rig from the panel below the market panel to one of the open rig slots.
4. Get this error:

```
pyfa v2.9.0
EVE Data Version: 1492195 (2019-04-16 15:50:22)

OS version: Windows-7-6.1.7601-SP1
Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]
wxPython version: 4.0.4 (wxWidgets 3.0.5)
SQLAlchemy version: 1.0.5
Logbook version: 1.4.3
Requests version: 2.21.0
Dateutil version: 2.8.0

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\builtinViews\fittingView.py", line 527, in fitChanged
  File "C:\projects\pyfa\gui\builtinViews\fittingView.py", line 481, in generateMods
TypeError: '<' not supported between instances of 'NoneType' and 'int'

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\builtinViews\fittingView.py", line 192, in OnMouseMove
IndexError: list index out of range

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\builtinViews\fittingView.py", line 192, in OnMouseMove
IndexError: list index out of range
```

### Release or development git branch? Please note the release version or commit hash:

Pyfa v2.9.0, though this happened on earlier versions too.

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 7, 64 bit.

### Other relevant information:

N/A

**Comment by DarkFenX** [comment]
Fixed in 7131cdbac6136f663a7fd90d82fe76224b66567b
