### ISSUE TITLE
Fighter DPS graph doesn't respect "factor in reload time"

### ISSUE THREAD

**Issue by SomeoneStrange** [pyfa-org/Pyfa#1930]
Missile Attacks are showing more damage in graph mode than the theoretical max shown in DPS indicator. See screenshot:
https://i.imgur.com/dU08jGI.png

Regular turret attacks and LRFs appear to be unaffected.

Testing with ingame simulator shows Graph damage to be accurate.

**Comment by DarkFenX** [comment]
I believe this is due to "factor in reload time" option (which is toggled via firepower context menu). DPS panel seems to respect this setting while DPG graph does not. So, the real bug here is graph.

**Comment by DarkFenX** [comment]
Fixed in 9261d29ac17a058d79082bb12f132ab9b5ce1f72
