### ISSUE TITLE
Ammo switcher with Ctrl key pressed does not change ammo in all modules but only in clicked one

### ISSUE THREAD

**Issue by Jacik** [pyfa-org/Pyfa#1958]
"Removed menu item to change charges in all modules, now regular ammo switcher handles charges in all modules when Ctrl key is pressed" - this doesn't work on MacOS (MacbookPro HW)

**Comment by DarkFenX** [comment]
Does it work with cmd?

**Comment by DarkFenX** [comment]
We're using cmdDown so far: https://wxpython.org/Phoenix/docs/html/wx.KeyboardState.html#wx.KeyboardState.CmdDown
```
Returns True if the Control key or Apple/Command key under OS X is pressed.
```

**Comment by Jacik** [comment]
Yes it works with CMD

**Comment by DarkFenX** [comment]
@Jacik does it cause any inconveniences on Mac? I can easily switch to "True" Ctrl (so that it's Ctrl on mac too), but I'm unsure if it's worth to.

**Comment by DarkFenX** [comment]
Reopen/comment if cmd/ctrl use is still an issue for you

**Comment by Jacik** [comment]
@DarkFenX No, its fine. CMD is used very often as replacement for CTRL. Just change description in release note, so people will know about it.

**Comment by DarkFenX** [comment]
Will do.
