### ISSUE TITLE
Cant add ammo to all gun anymore, and rigs on upwellstructures (worked fine on 2.8)

### ISSUE THREAD

**Issue by RustyX5** [pyfa-org/Pyfa#1959]

**Comment by DarkFenX** [comment]
Please read release notes regarding it:
https://github.com/pyfa-org/Pyfa/releases/tag/v2.9.1
> "Change Charge (All)" menu item has been removed, use regular charge switcher with Ctrl key pressed instead
> Added option to "General" section which controls behavior of ammo switcher. By default it is set to change ammo just for selection without Ctrl and for all modules with Ctrl

**Comment by RustyX5** [comment]
Hi, thanks for reply. Oh didn't see that in the patch notes..pressing ctrl key works fine.

As for the structure rigs though, i just worked it out..you need to drag them across to the fitting now, not simply doubleclick and they get added automatically. Not sure if this was intentional, but just to let you know.

Thanks again

________________________________

**Comment by DarkFenX** [comment]
It was not intentional. Fixed in 99d72956e8010ef233407111b6b0d218aabf35c5

**Comment by DarkFenX** [comment]
> pressing ctrl key works fine

Just in case you haven't noticed - there's option to reverse and load into all by default.
