### ISSUE TITLE
Triage + shield boost amplifier stacking penalty regression

### ISSUE THREAD

**Issue by muleooo** [pyfa-org/Pyfa#1961]
Thanks for this, it was indeed missing stacking flags in the triage effect file. There should be a release tomorrow with this fix. =)

_Originally posted by @blitzmann in https://github.com/pyfa-org/Pyfa/issues/141#issuecomment-49628346_

**Comment by muleooo** [comment]
![Screenshot_208](https://user-images.githubusercontent.com/2170565/56862515-1dfe3080-69ac-11e9-89d7-9f42817be6d4.png)
![Screenshot_209](https://user-images.githubusercontent.com/2170565/56862516-1dfe3080-69ac-11e9-8c33-235d23537a5e.png)
![Screenshot_210](https://user-images.githubusercontent.com/2170565/56862517-1e96c700-69ac-11e9-9515-8c09929d9589.png)

**Comment by DarkFenX** [comment]
Thanks for your report! Will fix it before next release.

**Comment by DarkFenX** [comment]
Fixed in 4b65662c9f6872f300563af42f0a6ba0c4ec170c
