### ISSUE TITLE
Scroll speed slow in preferences

### ISSUE THREAD

**Issue by aydjay** [pyfa-org/Pyfa#1963]
## Bug Report
Scroll speed in preferences -> market tab is not consistent with scroll speed of the "Category" section.

### Expected behavior:
Speed of both scroll bars to be consistent.

### Actual behavior:
Market preferences speed very slow.

### Detailed steps to reproduce:
Open preferences, scroll category up and down with scroll wheel on mouse, note the speed.

Select "Market and prices" category, scroll with the scroll wheel on mouse and note the very slow scroll speed.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

No fits See gif for illustration:

![2019-04-29_13-58-59](https://user-images.githubusercontent.com/9460838/56897888-92f26880-6a87-11e9-857f-f2d91a8361e4.gif)

### Release or development git branch? Please note the release version or commit hash:
V2.9.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by DarkFenX** [comment]
Related to #1909. It's known issue, i just couldn't be bothered to create new one.

**Comment by DarkFenX** [comment]
Fixed in bdd4a8cfb7e6ae4bc833f4af84ac653aca92c42b
