### ISSUE TITLE
Rorqual drone damage and speed incorrect due to change in game mechanics. 

### ISSUE THREAD

**Issue by pilotchute** [pyfa-org/Pyfa#1966]
## Bug Report
The Rorquals Siege module (the Industrial core) now stacks with penalties with both Drone Navigation Computers and Drone Damage Amplifiers. 

### Expected behavior:
Industrial core stacks with penalties apply when using with DNCs and DDAs

### Actual behavior:
The industrial core doesn't stack with penalties when using DNCs and DDAs

### Detailed steps to reproduce:
Fit a Rorqual with an industrial core, a DDA I and a DNC I

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Rorqual, Rorqual fit]

Drone Damage Amplifier I
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

Drone Navigation Computer I
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Industrial Core I
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

'Excavator' Ice Harvesting Drone x1
'Excavator' Mining Drone x1
Garde I x1
Hammerhead I x1
Hobgoblin I x1
Ogre I x1

### Release or development git branch? Please note the release version or commit hash:
release 2.9.2

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
mac osx 10.14.4

**Comment by DarkFenX** [comment]
Good catch. Pretty sure it's been like that for a long time, not a recent change in mechanics. Pyfa had drone damage bonus stacking penalized, only drone speed was wrong. Fixed in e9f3453b045287920df786592cef4726548e78a2.
