### ISSUE TITLE
"Change charge in all modules of the same type" option does not work properly

### ISSUE THREAD

**Issue by MarHelmer** [pyfa-org/Pyfa#1974]
## Bug Report
The option to change charges in all modules of the same type does not work as expected when this option is enabled in the Preferences window.  Toggling the option off and on (and saving in between toggles) does not help.

Holding down Ctrl works to enforce this behavior, but pressing Alt cancels out of the submenu to activate the menu bar.

### Expected behavior:
When the option is enabled, changing the charge in any module should change the charges in all modules of the same type, regardless of how many are selected.

### Actual behavior:
Even when the option is enabled, changing the charge in any modules changes the charge in only the selected module, even if other modules of the same type are fit.

### Detailed steps to reproduce:
Load or create a fit and add at least two modules of the same type.  Ensure that the "Change charge in all modules of the same type" option is enabled in the General Preferences window.  Attempt to change the charge in just one module; only that module's charge will change.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
All fits are affected, across multiple restarts of both the program and the system.

### Release or development git branch? Please note the release version or commit hash:
2.9.4dev3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
I believe this feature worked as intended in the stable release of 2.9.3.

**Comment by DarkFenX** [comment]
Good catch! Fixed in 0b00e288639526ee5992266f0da21c413684c24b
