### ISSUE TITLE
Market Data is wrong

### ISSUE THREAD

**Issue by BlackAce21** [pyfa-org/Pyfa#1984]
## Bug Report
https://i.imgur.com/OeTU4sp.png

### Expected behavior:
That prices be "somewhat" accurate

### Actual behavior:
They are not always accurate

### Detailed steps to reproduce:
Go to Jita and compare market prices in pyfa to market prices ingame

### Fits involved in EFT format (Edit > To Clipboard > EFT):
All of them

### Release or development git branch? Please note the release version or commit hash:
v2.9.3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 7

### Other relevant information:
Perhaps this is a caching issue with the back end database website that pyfa is pulling information from because I assume each client isn't individually pinging the ESI for market information but can we get slightly better updates? I mean being over 90 mill off the mark shows a pretty big lag time since 3.22.2019 was the last time the price was that low according to the market history ingame and its now 5.24.2019. This is more a QoL thing since its simply a matter of being convenient to know how much a build will cost beforehand but it's something I would like to see be made a lot more accurate. Even if its just once per week it gets updated ya know? Thx in advance.

**Comment by DarkFenX** [comment]
What are your pyfa market settings? What are your pyfa network settings? Do you have (!) next to prices in the fitting window?

**Comment by BlackAce21** [comment]
Some more digging on this reveals that Pyfa is using eve-marketdata.com as its market endpoint service....which is of course responsible for the problem. They are displaying the correct price in the listings for specific market entries but somehow arriving at the wrong "average" figure. Either not accounting for random sell orders that is effecting the price average or simply screwed up in some other way.

**Comment by DarkFenX** [comment]
Choose eve-marketer then in options, should fix that. Does not look like a pyfa issue.

**Comment by BlackAce21** [comment]
Is there a way to force update the market data? Making the change in options seems to have no effect. Also in related news is it possible to request more options for market data such as eve appraisal and better options for making price pulling determinations? I know that eve appraisal for example has options to pull market data based on current max price as well as average which depending on the circumstances could lead to more reliable market data in the moment. Seeing this information at a glance may also be helpful instead of just having a flat price value being pulled from some place magical that may or may not be giving accurate results.

**Comment by DarkFenX** [comment]
> Is there a way to force update the market data?

Preferences > Database > Delete All Prices

As for more options/data - sure, but someone has to implement.

I find evemarketer + Jita pretty accurate for me so far btw.

**Comment by BlackAce21** [comment]
#1570 kinda looks like someone is already thinking about it. evemarketer seems accurate so far now that I have the data actually loaded. Thank you for the help. Hope to see market data expanded in coming releases.
