### ISSUE TITLE
Veles weapons are misnamed

### ISSUE THREAD

**Issue by MarHelmer** [pyfa-org/Pyfa#1986]
## Bug Report
This is probably just a database quirk.  In-game, Veles weapons are referred to as Light/Heavy/Supratidal Veles Entropic Disintegrator, but in Pyfa, they're Veles Light/Heavy/Supratidal Entropic Disintegrators.  This can cause export for in-game ESI fitting sync, shopping list, Fleet-Up uploads, etc.

While Pyfa's displayed naming convention is indeed the correct one—the faction name typically comes before the item size class and item name—EVE obstinately disagrees.

As a note, the Pyfa-labeled Veles Entropic Radiation Sink may also fall prey to this foible after its release.

**Comment by DarkFenX** [comment]
What is your pyfa release and what EVE server are you comparing it to?

**Comment by MarHelmer** [comment]
...Derp.  I'm on 2.9.4dev3 and comparing to Tranquility. Please ignore 
me, close this thread, and mutter things about shame.

**Comment by DarkFenX** [comment]
Actually nvm, there should be name mappings which autoresolve this issue. Reopening

**Comment by DarkFenX** [comment]
Fixed in 45452ca680984831c530282f8efa1c4119640972
