### ISSUE TITLE
Cap Amount Vs Time graph is not affected by cap booster reload or neuts

### ISSUE THREAD

**Issue by jacobmatthewjansen** [pyfa-org/Pyfa#1991]
## Bug Report
The Cap Amount Vs Time graph seems to be only a function of regents and does no factor in cap boosters or neuts.  

### Expected behavior:
If a cap booster is included on the fit or a neut is projected onto the fit, the Cap Amount vs. Time plot should reflect this.  Importantly, the plot should factor in reload time for the cap booster.  

### Actual behavior:
The plot is unaffected and appears to be only a function of cap regeneration.  

### Detailed steps to reproduce:

1. Open Fit
2. Ensure Cap booster is online and loaded
3. Project Neut onto fit
4. Open Graphs
5. Select "Cap Amount vs. Time"

### Fits involved in EFT format (Edit > To Clipboard > EFT):
```
[Ikitursa, pyfa bug]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
Small Capacitor Booster II, Navy Cap Booster 150

Heavy Entropic Disintegrator II, Occult M
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]


Hammerhead II x5


Navy Cap Booster 150 x100
```

### Release or development git branch? Please note the release version or commit hash:
v2.9.4

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
OSX 10.13.6

### Other relevant information:
N/A

**Comment by DarkFenX** [comment]
It simulates cap regen and just cap regen, starting from 0 cap. I will add another graph later which simulates cap consumption / cap gains with all sources and sinks taken into consideration, starting from 100%.
