### ISSUE TITLE
Unable to search fittings with Chinese character

### ISSUE THREAD

**Issue by zhlzhl123** [pyfa-org/Pyfa#1996]
Windows 10
v2.9.3

**Comment by DarkFenX** [comment]
Post character, as well as name of fitting if possible, please.

**Comment by zhlzhl123** [comment]
I am so sorry that I made this mistake. It do work with Chinese character, I just forgot that there should be more than three characters.

However, it is possible to change this mechanism since one character is enough for finding the fitting named with Chinese or Japanese in most of the cases. (We usually named the fitting no more than three characters because there is no need to do that).

Thanks.

**Comment by DarkFenX** [comment]
Alright, i will check if there's a way to detect language and change the logic.

**Comment by zhlzhl123** [comment]
Well, since the search is done automatically when the keyword is reached three characters, why not add an option so that we can force it to search by pressing the "Enter"? 

(Sometimes different characters from different languages may mix together, like "肉装VNI，扫射A", the logic for detecting language may be hard)

**Comment by DarkFenX** [comment]
Changed in e77ada4e8ccf638109f2e4b1b86441be14d725b7. Now if string has any CJK symbols, min amount of characters is 1. If you have some experience with unicode, please review if my way to detect that makes sense:

https://github.com/pyfa-org/Pyfa/blob/master/utils/cjk.py
https://stackoverflow.com/questions/1366068/whats-the-complete-range-for-chinese-characters-in-unicode
