### ISSUE TITLE
Feature Request: Cap Delta by Default

### ISSUE THREAD

**Issue by MarHelmer** [pyfa-org/Pyfa#1997]
I think the cap delta tooltip is a fantastic feature and I find it far more useful than the total cap numbers.  I suggest an option be added to make cap delta the default display (with the absolute numbers in the tooltip).

**Comment by DarkFenX** [comment]
Just curious, how do you use this stat (given that cap stability/cap time readout alone should cover most of needs)?

Personally, i find both stats equally useless (delta and gain/loss), so might make delta and neut resist default without an option as well.

**Comment by DarkFenX** [comment]
I guess there's a use-case, quickly estimating how many extra neuts you can take before breaking

**Comment by MarHelmer** [comment]
Yes, that's exactly it: neut tolerance. Between the delta and the neut
resistance percentage, I can estimate how likely enemies may affect my cap
stability.

**Comment by DarkFenX** [comment]
Changed in e8f09514abf98351c78df1e75ac645036a6babe9
