### ISSUE TITLE
Add ability to export individual mutated modules

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#2003]
To paste them into other fits, for example. Implementation details need to be refined.

**Comment by fonsui** [comment]
I have considered a larger feature that would add this functionality by matter of course - addition of an "abyssal" subcategory for each module that it is applicable for, and interfacing with mutaplasmid.space (or directly with the game) for maintaining a database of modules that you own, in addition to modules you create for simulations.

I recognize that this is a way bigger idea, and deserves a suggestion post in and of itself, but it was relevant to the feature being discussed, so I chose to share the thought here. If you think that is a direction you might want to go in, I can post a suggestion for that with further refinement of the details.

**Comment by DarkFenX** [comment]
This is larger feature indeed. I plan to implement just export until next release, so let's keep this issue just for it.

**Comment by DarkFenX** [comment]
Added in 035c69c60a198298652072be4908a3ad17e96464
