### ISSUE TITLE
Cap sim doesn't delay activation of cap boosters until ship actually needs cap

### ISSUE THREAD

**Issue by robfrancken** [pyfa-org/Pyfa#2006]
## Bug Report
Cap booster charges not calculating cap **lasts** duration correctly.

### Expected behavior:
Swapping from 200 to 400 cap booster charge should increase cap lasts time.

### Actual behavior:
With 200 booster charge: cap lasts 20s

With 400 booster charge: cap lasts 13s

* All modules activated.

### Detailed steps to reproduce:
Toggle between 200 and 400 booster charges.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Tristan, Autocannons]

Small Ancillary Armor Repairer, Nanite Repair Paste
Energized Adaptive Nano Membrane II
Small Armor Repairer II

1MN Afterburner II
Initiated Compact Warp Disruptor
Small Electrochemical Capacitor Booster I, Navy Cap Booster 200

150mm Light AutoCannon II, Hail S
Small Gremlin Compact Energy Neutralizer
150mm Light AutoCannon II, Hail S

Small Nanobot Accelerator I
Small Nanobot Accelerator I
Small Nanobot Accelerator I

Hobgoblin II x5

Standard Exile Booster

### Release or development git branch? Please note the release version or commit hash:
Release v2.9.4

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by DarkFenX** [comment]
I think it works like intended. Pyfa activates all modules right away (including cap booster) and you run out of cap before you have a chance to activate cap booster 2nd time, while with 200s you can do 2nd activation before you run out of cap which gives you +200 and thus extra running time.

There's no logic in place to delay booster activation. We're using [capacitor sim](https://github.com/pyfa-org/Pyfa/blob/master/eos/capSim.py) written by entity and we just feed activation parameters into it. If you want to teach it to activate modules intelligently (cap boosters as example), it has to be rewritten/modified.

**Comment by DarkFenX** [comment]
Fixed in 6db178e4d2f6934f252841c63ca69955d2467d2f. Now cap sim delays cap booster activation until:

1) Using cap charge will not overshoot max (eg it will use 400 charge when you are 200 or below in your max 600 cap ship)
2) Ship is in need of more cap than it has at the present moment (e.g. you have 300 cap out of 600, you have 400 charge waiting for activation, and your ship needs 500 cap for activation of some module)
