### ISSUE TITLE
Heretic Base Powergrid

### ISSUE THREAD

**Issue by RustyX5** [pyfa-org/Pyfa#2010]
Hi, can you check the base powergrid on the heretic (amarr interdictor). In game its 60 pg and with max skills its 75pg, however in your program the base is PG is 69 and max skills is 86.25. I'm not sure...can you check this, i've got corporates to confirm also. This is on version 2.9.4 so not sure if your program not updated or CCP has dropped a patch no one knows about or they nerfed the heretic and no one knows lol..i'm not sure.

Thanks mate

**Comment by DarkFenX** [comment]
Might have been stealth nerf indeed. Last time we updated db was in may and i didn't bother to update it because there was no relevant announcements.

Will check slightly later.

**Comment by DarkFenX** [comment]
![image](https://user-images.githubusercontent.com/275209/60905406-b1da5b80-a27d-11e9-803b-86a0723b1779.png)

Are you sure you don't have some overrides of PG modules?

**Comment by DarkFenX** [comment]
Reopen if you're still confident that it's a bug
