### ISSUE TITLE
DB Update for new VNI

### ISSUE THREAD

**Issue by fonsui** [pyfa-org/Pyfa#2012]
Please put out an update with the changes implemented on 7/25, mainly the new Vexor Navy Issue attributes/bonuses.

**Comment by DarkFenX** [comment]
I will. I wanted to finish graph changes and several bugfixes but it takes more time than i originally expected.

Gonna make build with the changes tomorrow.

**Comment by DarkFenX** [comment]
https://github.com/pyfa-org/Pyfa/releases/tag/v2.9.5

**Comment by fonsui** [comment]
Thanks for handling this! Your work is much appreciated.
