### ISSUE TITLE
Issues with fit search on Windows 

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#2013]
https://i.redd.it/3zkcga17ri831.png

More info: https://old.reddit.com/r/Eve/comments/c9ilti/anybody_else_have_chronic_problems_with_pyfa/

**Comment by H296** [comment]
If any logs would help with this issue please reply here.

**Comment by DarkFenX** [comment]
back up <user folder>/.pyfa before trying older versions.

I will get to this bug, but I want to finish coding some features first.

**Comment by DarkFenX** [comment]
@H296 i tried to reproduce issue with your database and it was alright even on quite resource-restricted VM (windows 8.1 running inside virtualbox - 3gb ram and quite low cpu speed).

https://transfer.sh/qRdeu/fit_search.flv

**Comment by H296** [comment]
I've downgraded to 2.9.4, still had chronic crashing problems. Downgraded to 2.9.1, it's been okay-ish, doesn't crash as often but can still get choked with searching.

**Comment by DarkFenX** [comment]
I am afraid it's rather low-level issue with wxPython (UI toolkit we're using). If i were able to reproduce it on my machines, I could isolate bit of code which is causing it and report to wxPython maintainers. But as my attempts failed, you are kinda out of luck.

Few other wild guesses - do you have any anti-virus or anti-malware monitors installed, if yes, which? Do you have DEP (data execution prevention) enabled in windows' settings? Do you have any other security-tightening mechanisms you're aware of? How much free RAM do you have when you run search?

**Comment by DarkFenX** [comment]
I suppose #2121 was the duplicate of it, judging by the error message. Closing.
