### ISSUE TITLE
Pyfa not starting on second monitor

### ISSUE THREAD

**Issue by mithlug** [pyfa-org/Pyfa#2015]
## Bug Report
Pyfa doesn't seem to behave as most windows do by default.

### Expected behavior:
Closing a window on a specific monitor as the active window can be dragged around should make the window start on that monitor.

### Actual behavior:
After having closed pyfa when it was active on my second monitor (non-primary) it opens on my primary monitor.

### Detailed steps to reproduce:
Have two monitors, notice which is primary and secondary.
Launch pyfa, drag it to second monitor.
Close it (maybe fullsize it first and then restore size).
Launch it again. Pyfa does not open on the same monitor as you closed it on.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
n/a

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
Would be a great QoL improvement as pyfa could easily start on second monitor then as eve starts on primary. Not really urgent though.

**Comment by DarkFenX** [comment]
There's way to select that, it seems:

http://www.blog.pythonlibrary.org/2018/06/13/wxpython-set-which-display-the-frame-is-on/

Unfortunately, the only dual-monitor setup I have access to is Debian running on Wayland, and this code doesn't work there. If anyone could run this code and see if it works under windows - it would be much appreciated.

If it does, we can modify pyfa to remember and select proper monitor.

**Comment by DarkFenX** [comment]
Should be fixed in 20bee1196a5346c2bdfa5652728d082872f19dae (although i cannot test it on dual-monitor setup atm).

**Comment by blitzmann** [comment]
can test it :) will report back

**Comment by DarkFenX** [comment]
Just tested on my linux dual-monitor setup. Works as expected on xorg, doesn't work on wayland (which is also to be expected, it doesn't allow apps to control their windows via setposition).

**Comment by mithlug** [comment]
Yep, tested with 2.10.0, it worked for me on windows 10.
