### ISSUE TITLE
explosion velocity bonus from offline module

### ISSUE THREAD

**Issue by brohee** [pyfa-org/Pyfa#2017]
## Bug Report
The "ML-EKP 'Polybolos' Ballistic Control System" explosion velocity bonus is applied wether the module is online or not

### Expected behavior:

Not applied when module offline

### Actual behavior:

No difference in explosion velocity

### Detailed steps to reproduce:

Offline a polybolos BCS, notice how explosion velocity is not affected in charge stats

### Fits involved in EFT format (Edit > To Clipboard > EFT):

[Raven Navy Issue, Mission application]

ML-EKP 'Polybolos' Ballistic Control System
ML-EKP 'Polybolos' Ballistic Control System
Caldari Navy Ballistic Control System
Caldari Navy Ballistic Control System
Caldari Navy Co-Processor

Core X-Type 100MN Afterburner
Gist X-Type X-Large Shield Booster
Gist X-Type Shield Boost Amplifier
Caldari Navy Adaptive Invulnerability Field
Caldari Navy Adaptive Invulnerability Field
Large Cap Battery II
Missile Guidance Computer II, Missile Precision Script

Caldari Navy Cruise Missile Launcher, Scourge Fury Cruise Missile
Caldari Navy Cruise Missile Launcher, Scourge Fury Cruise Missile
Caldari Navy Cruise Missile Launcher, Scourge Fury Cruise Missile
Caldari Navy Cruise Missile Launcher, Scourge Fury Cruise Missile
Caldari Navy Cruise Missile Launcher, Scourge Fury Cruise Missile
Caldari Navy Cruise Missile Launcher, Scourge Fury Cruise Missile
Caldari Navy Cruise Missile Launcher, Scourge Fury Cruise Missile
Caldari Navy Cruise Missile Launcher, Scourge Fury Cruise Missile

Large Warhead Rigor Catalyst II
Large Warhead Rigor Catalyst II
Large Warhead Flare Catalyst II

'Augmented' Hammerhead x1
'Augmented' Hobgoblin x3
Gecko x1

### Release or development git branch? Please note the release version or commit hash:

pyfa v2.9.6

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10 64

**Comment by DarkFenX** [comment]
Works for me. 128 m/s with all mods online, 125 m/s with one offline and 119 with both offline.

**Comment by brohee** [comment]
It now works for me too... Is there some caching layer that could explain what I saw?

**Comment by DarkFenX** [comment]
Nope. Could be some weird effect ordering problem which affect some complex cases (e.g. projected keres' damp strength taken before Electronic Superiority gang boost and applied to current fit) but UI always takes calculation results after everything has been completely calculated, so I am unsure how it could have happened.

If you run into similar issues again - please reopen and list steps to reproduce again, even if issue is seemingly random.
