### ISSUE TITLE
Problem with JITA prices

### ISSUE THREAD

**Issue by Meduza1111** [pyfa-org/Pyfa#2021]
#1842  Bug Report
wrongly displayed JITA price. Today i setup new fit for drekavac, counted in Pyfa 470M, i came to jita to buy it and was surprised by 870M.
So i made some analyze
Pyfa - Corpus X-Type Armor Thermal Hardener 95M
eve-marketdata.com > 145M
http://evemarketer.com > 145M
no idea, why i see 95M in pyfa. Tried to change Default provider, but no change.
screenshots attached

And i checked all stuff from my fit and there were horrible differences. Can you please check it?

### Release or development git branch? Please note the release version or commit hash:
v2.9.6.

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
W10
![eve_marketer](https://user-images.githubusercontent.com/40168547/63466751-3535c200-c464-11e9-89b4-4d53f5127a11.png)
![EVEMarketer](https://user-images.githubusercontent.com/40168547/63466757-3bc43980-c464-11e9-8992-bc2531cee7d1.png)

**Comment by DarkFenX** [comment]
1) screenshot of your pyfa market preferences please
2) prices are cached for 24 hours. Try clearing cache (preferences - database - delete all prices) and restarting pyfa. If it helps, run price optimization before going to jita. It refreshes all prices older than 2 hours

**Comment by Meduza1111** [comment]
![image](https://user-images.githubusercontent.com/40168547/63467140-0f5ced00-c465-11e9-93c4-17ec800656ff.png)
![image](https://user-images.githubusercontent.com/40168547/63467176-23085380-c465-11e9-8c5f-b41f14e8391c.png)
![image](https://user-images.githubusercontent.com/40168547/63467246-4a5f2080-c465-11e9-9b4b-d98a5292b802.png)

you can see Pyfa price 18M, evemarketer 122M, eve market data - probably problem is here. Price is same as marked on screenshot. No idea, why there is 18M a bellow best seller price 122M. Anyway, i changed default server, but still price is 18M

**Comment by Meduza1111** [comment]
ah, you answer meanwhile, i will check and let you know. Thanks for amazing quick answer.

**Comment by Meduza1111** [comment]
Problem solved, clearing cache (preferences - database - delete all prices) and restarting pyfa works well.

thanks a lot

**Comment by DarkFenX** [comment]
Seems like EVE market data is fucking up. Cannot do anything about that. Gonna change default price server to EVE marketer for now. If EVE market data keeps fucking up, i will just remove it as an option.
