### ISSUE TITLE
Minokawa can only use one Command Burst again.

### ISSUE THREAD

**Issue by Bazzek** [pyfa-org/Pyfa#2036]
## Bug Report
Minokawa and Lif can still not enable 2 command bursts (reopen of #2031)

### Expected behavior:
Minokawa and Lif can use 2 command burst modules

### Actual behavior:
1 command burst gets off-lined when the other gets turned on.

### Detailed steps to reproduce:
Make a minokawa/Lif fit, add 2 command bursts, the second one will receive a "off-line red x)

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Minokawa, Minokawa fit]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Shield Command Burst I /OFFLINE
Armor Command Burst II
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
Running on master branch (2.10.1 is version number displayed) through github.
I did a rebase from the git repo to make sure i had no lingering stuff for some odd reason.

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Xubuntu 19.04

### Other relevant information:
Obviously it also goes wrong with a fully fitted minokawa

I tested a Hel, Thanatos and rorq and those seem fine.

**Comment by DarkFenX** [comment]
Oops, when testing carriers/supers/titans i forgot that faxes also have this bonus. Fixed in a9ad0944222c371a844abe4e16ebdfce34329a9c
