### ISSUE TITLE
Ewar not applying properly on titan / 80% resistance bonus

### ISSUE THREAD

**Issue by Boot103** [pyfa-org/Pyfa#2037]
## Bug Report
Ewar not applying to titans properly

### Expected behavior:
80% resistance when applying ewar to titans

### Actual behavior:
The ewar doesn't seem to be applying on titans properly

### Detailed steps to reproduce:
Project tracking disruption on a titan. It projects 100% instead of 20%

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Ragnarok, Yea]

Republic Fleet Tracking Enhancer
Republic Fleet Tracking Enhancer
Republic Fleet Gyrostabilizer
Republic Fleet Gyrostabilizer
Republic Fleet Gyrostabilizer
Republic Fleet Gyrostabilizer

Pithum A-Type EM Ward Amplifier
CONCORD Capital Shield Extender
CONCORD Capital Shield Extender
Pithum A-Type Adaptive Invulnerability Field
Pithum A-Type Adaptive Invulnerability Field
10000MN Afterburner II
Capital Capacitor Booster II

Quad 800mm Repeating Cannon II
Quad 800mm Repeating Cannon II
Quad 800mm Repeating Cannon II
Quad 800mm Repeating Cannon II
Quad 800mm Repeating Cannon II
Quad 800mm Repeating Cannon II
'Gjallarhorn' Explosive Doomsday
Cynosural Field Generator I

Capital Core Defense Field Extender II
Capital Core Defense Field Extender II
Capital Core Defense Field Extender II

High-grade Ascendancy Alpha
High-grade Ascendancy Beta
High-grade Ascendancy Gamma
High-grade Ascendancy Delta
High-grade Ascendancy Epsilon
High-grade Ascendancy Omega

### Release or development git branch? Please note the release version or commit hash:
2.10.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by DarkFenX** [comment]
Duplicate of #2030, has been fixed & released in 2.10.1 already
