### ISSUE TITLE
Windows flags PYFA install executable as virus

### ISSUE THREAD

**Issue by billytheme** [pyfa-org/Pyfa#2040]
## Bug Report
When downloading the latest (v2.10.1) pyfa version, Windows Antivirus flags the install file as a Trojan:Win32/Detplock and quarantines it

### Expected behavior:
Windows should not flag PYFA as a virus

### Actual behavior:
Windows flags PYFA as a virus

### Detailed steps to reproduce:
Disable other antivirus software, so that the default Windows Antivirus is running
Download PYFA v2.10.1 windows install executable
Check Windows Antivirus logs

### Fits involved in EFT format (Edit > To Clipboard > EFT):
None

### Release or development git branch? Please note the release version or commit hash:
Release, v2.10.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by DJRBuckingham** [comment]
Also occurs on Windows 7 with Virus/Spyware definition version 1.301.714.0.

pyfa-v2.10.0-win.exe is not flagged as a threat.

**Comment by DarkFenX** [comment]
No idea why is that. Nothing has changed in build process, only python code changed slightly - but nothing suspicious was added/changed, only regular "business logic" and few UI code changes.

Virustotal also shows that executable is clean: https://www.virustotal.com/gui/file/21b7b038de786468a630fd284904b25fd9e5686b55d162839d4df008a9414b92/detection

**Comment by DarkFenX** [comment]
Sad part about it is: https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/developer-faq

Certificate costs around 500 usd/year (also according to corpmate), so I am not going to bother with it to sign installers/executables.

Changing installer to MSI might be an option, but I have no idea if it guarantees that installer won't be flagged, I have no idea how windows anti-virus works.

**Comment by DarkFenX** [comment]
https://ci.appveyor.com/project/blitzmann/pyfa/builds/27110244/artifacts appveyor keeps history of builds, and this is the build, so you can check that I did not change the build.

Github API can be used to check that too:
https://api.github.com/repos/pyfa-org/Pyfa/releases/19472884
```
    {
      "url": "https://api.github.com/repos/pyfa-org/Pyfa/releases/assets/14694164",
      "id": 14694164,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDE0Njk0MTY0",
      "name": "pyfa-v2.10.1-win.exe",
      "label": "",
      "uploader": {
        "login": "blitzmann",
        "id": 3904767,
        "node_id": "MDQ6VXNlcjM5MDQ3Njc=",
        "avatar_url": "https://avatars1.githubusercontent.com/u/3904767?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/blitzmann",
        "html_url": "https://github.com/blitzmann",
        "followers_url": "https://api.github.com/users/blitzmann/followers",
        "following_url": "https://api.github.com/users/blitzmann/following{/other_user}",
        "gists_url": "https://api.github.com/users/blitzmann/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/blitzmann/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/blitzmann/subscriptions",
        "organizations_url": "https://api.github.com/users/blitzmann/orgs",
        "repos_url": "https://api.github.com/users/blitzmann/repos",
        "events_url": "https://api.github.com/users/blitzmann/events{/privacy}",
        "received_events_url": "https://api.github.com/users/blitzmann/received_events",
        "type": "User",
        "site_admin": false
      },
      "content_type": "application/octet-stream",
      "state": "uploaded",
      "size": 41209109,
      "download_count": 3197,
      "created_at": "2019-09-01T22:27:59Z",
      "updated_at": "2019-09-01T22:28:01Z",
      "browser_download_url": "https://github.com/pyfa-org/Pyfa/releases/download/v2.10.1/pyfa-v2.10.1-win.exe"
    },
```

**Comment by billytheme** [comment]
Yeah I wasn't worried about it being a virus, just trying to alert people that it's a thing that windows is doing. I've installed the update already

**Comment by DarkFenX** [comment]
Is 2.11.0 alright, or does it also trigger defender AV?

**Comment by DarkFenX** [comment]
According to reports from few people I know it does not. Closing issue. Hopefully it does not happen in future.
