### ISSUE TITLE
Add option to ignore drone control range

### ISSUE THREAD

**Issue by alexanderdarino** [pyfa-org/Pyfa#2044]
Been a while since I've used Sentries, but I'm preeeeeeeeeeetty sure their targeting range is completely independent of your control range, which should only affect your ability to issue commands to them. In the damage graphs for a Droneboat, their damage drops to zero past your ship's control range. Here is a graph for a blank Dominix fielding 5x Warden IIs w/ L5 skills:

![image](https://user-images.githubusercontent.com/671964/64982512-5be0f000-d88c-11e9-8a85-b08feba8cec4.png)

Here is what I expect to see (slapped on a bunch of drone range mod/rigs)

![image](https://user-images.githubusercontent.com/671964/64982585-8468ea00-d88c-11e9-9743-2b96d17aaa97.png)

This problem exists using any Drone Mode in the damage graph. Is this a bug?

**Comment by DarkFenX** [comment]
Intended, but can be discussed to change it.

That's how drones work:
- initial aggro: if target is within drone control range (DCR), drones start executing their order. If it is outside of DCR, drones refuse to do anything
- if target moves outside of DRC, drones keep following it. Sentries keep shooting, mobile drones keep following and shooting
- mobile drones sometimes have issue with deaggroing if target is moving faster than their orbit (no-mwd) speed, after that you cannot aggro them again if target is outside of DCR

That means, sentries are not any different than mobile drones (in this regard, and quit possibly any other).

I can add extra option to ignore drone control range, but what's the use-case would be?

**Comment by alexanderdarino** [comment]
From what I've observed, what you've described regarding DCR is slightly incorrect. DCR only applies to your ability to issue commands, and has no impact on anything else. For example: Suppose I'm 60km from my drones, and both my drones and I are 100km away from my target (ie. we've formed an isosceles triangle). The drones are within my DCR of 65km and the target is within my targeting range, so I have a target lock on them. If these are light/medium/heavy drones, I can still command my drones to target them, even though this target is further than 65km from the drones (ie. distance from drones to target exceeds DCR). In other words, DCR does not restrict the targeting range of drones. So as long as drones are within DCR of your ship and you have a target lock, you can command your drones to engage that target; that is the only two criteria; the distance between the drones and the target are irrelevant. Another example where this works: The drones, myself, and the target are in a straight line in that order. Drones are 60km to my left within my DCR of 65km, and target is 60km to my right. I can instruct the drones to engage the target to my right even though they are 120km away from the drones (exceeding the DCR). I have experienced this scenario many times due to heavy use of MJDs while ratting, so I can vouch that these numbers (the triangle or straight line of ranges between myself, my drones, and the target) are accurate. Not once have I ever received an error message or experienced my drones disobeying me because the distance between them and the target exceeds the DCR even though I'm within the DCR of the drones.

I mentioned it's been a while since I've used sentries, but I don't think the mechanics are different. Suppose you, your sentries, and the enemy are in a straight line in that order. You are 60km from your sentries, and you are 200km from your enemies and are able to lock them from that distance. This means there is 140km distance between your sentries and your enemy, but I'm pretty sure you can still command your sentries to attack the enemy since the sentries are still within your control range (ie. the distance between you and the drones) and you have a target lock on the enemy.

If what I say is true for all drones, the behavior needs to be changed. On the other hand, if for some reason sentry mechanics are different (ie. works for lights/mediums/heavies but not for sentries), it's still worth having an "ignore drone control range" flag precisely because of your second bullet point: "if target moves outside of DRC, drones keep following it. Sentries keep shooting, mobile drones keep following and shooting"; we might want the damage graph to show that very scenario.

**Comment by alexanderdarino** [comment]
For reference:

EVE uni: You can only command a drone to attack/repair/mine a target if that target is within a certain range of your ship; this range is known as the "drone control range"

Hover over DCR in Fitting window: Maximum range for issuing commands to drones

There is no evidence suggesting drones cannot engage targets at a distance exceeding the DCR as long as the distance between you and the drones themselves are within DCR. As described above, my observations is that drones can and do engage targets at a greater distance all the time. I do not believe sentries are exempt from this behavior.

**Comment by DarkFenX** [comment]
Well, i know a thing or two about drones (as I did VERY extensive testing of drone mechanics and drone AI for AT11 :P), but failed to express my knowledge. What i forgot to mention is that DCR is a value measured between drone carrier and its target.

Pyfa assumes that you drop sentries/mobile drones and issue attack order to them. In this case, drones will not attack past your DCR. If you have dominix, and target is 61km away from you, you will not be able to aggress drones on it no matter where your drones are located: near you ship or 50km away from you and 11km away from your target. You can easily test it yourself.

Now, that this part of mechanics is clear, question is - should pyfa assume that sentries are dropped right next to drone carrier? If no, how should that be worked around? Checkbox to ignore drone control range, or some extra controls to define drone position?

**Comment by alexanderdarino** [comment]
Cognitive dissonance is kicking in. I'm logging in right now to verify and see which of our two realities is correct 😝 

Assuming your Dystopian, Orwellian reality is the one we live in: I think both options should co-exist. Why both? Because they give different 'views'. One assumes the drones are always with the the ship, and the drone damage scales exactly with the ship's turrets would in the distance vs dps graph; the other puts the drones in a fixed state (similar to how mobile drones are currently implemented with regards to them being on the target) independent of the ship's weapons.

**Comment by alexanderdarino** [comment]
@DarkFenX I am pleased to announce that my version of the mechanics description is correct. I do not say this in a "Haha you were wrong I was right" fashion (believe me when I say I'm not that kind of guy), but in the sense that I'd much rather EVE employed my mechanics than what you described.

Here is the situation I just created: I planted a sentry ~50km to my left and an alt of mine ~50km to my right. My DCR is 60km. I was able to instruct my sentry to my left to attack the target to my right event though the distance between the two exceeds 60km. The line isn't perfectly straight but it is unambiguously clear that the distance between the sentry and target exceed the DCR. See screenshot

![image](https://user-images.githubusercontent.com/671964/65018367-ef4f0b00-d8f6-11e9-9147-fd6946ac2ddf.png)

**Comment by DarkFenX** [comment]
I suggest re-reading my previous message. Especially this part:

> DCR is a value measured between drone carrier and its target

And this:

> If you have dominix (base DCR is 60km with All V), and target is 61km away from you, you will not be able to aggress drones (sentries and mobile drones, doesn't matter) on it no matter where your drones are located: near you ship or 50km away from you and 11km away from your target.

It does NOT work the way you described earlier (drones within DCR - can attack anyone, even if target is outside of DCR). Just run the test i suggested and see yourself.

**Comment by alexanderdarino** [comment]
Yes, I see it now. My (incorrect) understanding had always been that DCR affected your ability to issue command to your drones based on your distance to the drones, but after smashing through cognitive dissonance with a sledge hammer and running a few experiments, I've come to see what you mean. Complete and total paradigm shift in my mind!

The solutions you suggested were both appropriate. As I stated before, I think they should both be implemented as options for the reasons I already described: both provide useful views for different contexts in which they would be used. Regarding the sentry drone distance feature: there are many situations in which I'd want to plant my drones in one place and I'd attack from another, and therefore would want a fixed metric for sentry distance. As for justifying the Ignore DCR feature: in sentry camps, or any situation in which the drone carrier moves far from sentries in the middle of a battle, it is not unreasonable to expect an enemy to enter and leave the DCR, in which case the sentries would keep on shooting after they leave.

Thanks for your detailed explanations and patience explaining this to me. Totally blew my mind of 7 years of going by wrong information and not once experiencing reason to believe otherwise save for these experiments I've just performed 😂

**Comment by DarkFenX** [comment]
I think i will implement option to ignore DCR to cover these cases (e.g. when target leaves DCR). Implementing option to control drone positions is too complex, given that there's no UI to control that. It could be part of some bigger feature, where you can select positions of all ships in simulation, but I am not going to code it anytime soon.

Case when sentry ship is away from sentries can be modelled by disabling DCR restriction and disabling all weapons except for sentry drones. Not the best solution, but still doable. Especially considering that sentry ships rarely have other weapons (except for sentry + cruise rattlesnake, which is also a rare sight).

**Comment by DarkFenX** [comment]
Fixed in 7dd063f04e6d5710e6ce15f21d836fa22a38d188

**Comment by DarkFenX** [comment]
Also, sharing some knowledge regarding drone behavior:

![image](https://user-images.githubusercontent.com/275209/65032370-affed980-d94b-11e9-9605-896b66f0ca81.png)
