### ISSUE TITLE
Automatically add Pyfa character when adding ESI character

### ISSUE THREAD

**Issue by Zixradoom** [pyfa-org/Pyfa#2045]
### Expected behavior:
ESI character available in the character drop down

### Actual behavior:
ESI characters not available in the character drop down

### Detailed steps to reproduce:
1) fresh install of pyfa on windows 10
2) Character Menu Option -> Manage ESI Characters -> Add Character
3) choose fit
4) click "Character:" drop down top right
5) character not available

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Vargur, Umbra II]

Tracking Enhancer II
Tracking Enhancer II
Gyrostabilizer II
Gyrostabilizer II
Gyrostabilizer II

Gist B-Type Large Shield Booster
Adaptive Invulnerability Field II
Adaptive Invulnerability Field II
Republic Fleet Large Cap Battery
Large Micro Jump Drive
Tracking Computer II

800mm Repeating Cannon II
800mm Repeating Cannon II
800mm Repeating Cannon II
800mm Repeating Cannon II
Small Tractor Beam II
Salvager II
Salvager II
Bastion Module I

Large Projectile Burst Aerator II
Large Capacitor Control Circuit I

Salvage Drone I x5
Warrior II x10

### Release or development git branch? Please note the release version or commit hash:
Version v2.11.0
EVE Data Version: 1564394 (2019-09-10 07:28:33)

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by DarkFenX** [comment]
Yeah, this is not how it works (but how it should).., you add ESI character, but even then you have to add Pyfa character, go to EVE SSO tab, pick ESI character (thus linking the two) and pull the data.

I will change this issue to be improvement, so that pyfa creates new character which has name of added ESI character with his skills, if such character hasn't been created yet.

**Comment by DarkFenX** [comment]
Done in #2159, also adjusted the behavior a little in dcb058a718ada4e1539fb6b198654a0ce30cf7c0
