### ISSUE TITLE
Crashes Pyfa

### ISSUE THREAD

**Issue by mithlug** [pyfa-org/Pyfa#2047]
pyfa v2.11.0
EVE Data Version: 1564394 (2019-09-10 13:28:33)

OS version: Windows-10-10.0.18362-SP0
Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.8
Logbook version: 1.5.2
Requests version: 2.22.0
Dateutil version: 2.8.0

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\builtinViews\fittingView.py", line 619, in fitChanged
  File "C:\projects\pyfa\gui\builtinViews\fittingView.py", line 750, in refresh
  File "C:\projects\pyfa\gui\display.py", line 219, in refresh
  File "C:\projects\pyfa\gui\builtinViewColumns\misc.py", line 56, in getText
  File "C:\projects\pyfa\gui\builtinViewColumns\misc.py", line 615, in __getData
KeyError: 'resistancesViewFull'

I get this error when I try to open a fit. Anything I can do on my end to fix it?

**Comment by DarkFenX** [comment]
Probably there is workaround, as well as a proper fix. Show me your settings on this page:

![image](https://user-images.githubusercontent.com/275209/65829056-005e2b80-e2aa-11e9-92ce-2dffe26b30f5.png)

**Comment by DarkFenX** [comment]
Anyway, I suspect that you had your resistance stats view disabled. Pyfa indeed breaks when it happens, but other way than yours. The way it breaks for you implies that you have tank view disabled as well.

I fixed various errors like this in 0bb732300e824ef1970fdf7b6b8a8cf776496029, but won't close this issue until you post your settings to confirm that.

**Comment by mithlug** [comment]
Yeah, you're correct! Thanks! All's working good now! :)
![bug fix](https://user-images.githubusercontent.com/1127843/65900204-c24e2e00-e3b5-11e9-9e0c-2abb31570321.png)
