### ISSUE TITLE
Black on Black text in Item Description

### ISSUE THREAD

**Issue by Heceldi** [pyfa-org/Pyfa#2048]
In gui/builtinItemStatsViews/itemDescription.py

When running a dark theme, this results in black on black text due to improper handling of color tags. For reference here, https://wxpython.org/Phoenix/docs/html/html_overview.html under List of supported tags

BODY does not support STYLE

Bad:
```
        desc = "<body style='background-color: {}; color: {}'>{}</body>".format(
            bgcolor.GetAsString(wx.C2S_CSS_SYNTAX),
            fgcolor.GetAsString(wx.C2S_CSS_SYNTAX),
            desc
        )
```

Fix is simply converting to appropriate tags, and using HTML4.0 compliant colors, as covered in html documentation, see previous link.

Good:
```
        desc = "<body bgcolor='{}' text='{}'>{}</body>".format(
            bgcolor.GetAsString(wx.C2S_HTML_SYNTAX),
            fgcolor.GetAsString(wx.C2S_HTML_SYNTAX),
            desc
```

With change, text renders in the appropriate SYS_COLOUR_WINDOWTEXT color.

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Arch ∞
Windows 10.1903

**Comment by Heceldi** [comment]
FWIW, Traits shows as Black on White regardless system setting. Attributes is correct background and has correct title field colors and "Fitting" (first drop down item)... after that, it's black on black.  Will submit those separately, working on where to fix.

**Comment by DarkFenX** [comment]
Would be great if you just collected all of those fixes in a single pull request. I never used dark theme myself, but I have an option to switch to dark theme to debug that or verify your fixes.

**Comment by Heceldi** [comment]
To give you an idea what I'm seeing, attaching a screenshot. 

For what it's worth, I didn't see where it was getting set easily for attributes and traits. I did fork it, and can setup a pull for you to fix it. Will have to delve a little more. 

If similar html/css was used elsewhere, then an alternative here would be switching wx.html.HtmlWindow for wx.html2.WebView. Rather than a very stripped down interpreter, it's a rendering engine, so the css styles should be honored. Might make maintenance easier down the road, since css styles should work as expected. Tossing that out there.

**Comment by DarkFenX** [comment]
I'd say, do not waste any time on non-obvious fixes. High chances are that it's wxpython/wxwidgets issue. Just fix whatever is obvious and report the rest here, I will take a look at them myself.
