### ISSUE TITLE
Stratios Incorrect max CPU

### ISSUE THREAD

**Issue by HyaeksVers** [pyfa-org/Pyfa#2051]
## Bug Report
Stratios has in correct Max CPU

### Expected behavior:
Should have 515 CPU all lv 5

### Actual behavior:
Has 500 Cpu

### Detailed steps to reproduce:
Try and build a stratios

### Fits involved in EFT format (Edit > To Clipboard > EFT):
Any.

### Release or development git branch? Please note the release version or commit hash:
Pyfa v2.11.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by DarkFenX** [comment]
Check your implants in game. High chances that you have 3% CPU implant.

Base stratios CPU is 400, *1.25 from fitting skill = 500.

**Comment by HyaeksVers** [comment]
Yes my bad, genolution slot 1 and 4, sorry about that

**Comment by DarkFenX** [comment]
No worries!
