### ISSUE TITLE
Overhauling jargon dictionary

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#2053]
This one has been bothering me for quite a while. Reference: https://github.com/pyfa-org/Pyfa/blob/master/service/jargon/defaults.yaml

Some of entries I've never seen being used, like `400pl: 400mm Plates` or `1400rt: 1400mm Artillery` or `cab: 10000mn`.
Some do not match my knowledge of jargon: `odi: Overdrive Injector` (OD has always been used in this case)
Some are conflicting: `rsb: Remote Shield Booster` (in my experience, rsb is remote sensor booster, and remote shield booster is often called with generic term RR / shield RR)

So, what we need is to add a way to hide 2 terms behind one jargon entry (and add corresponding support to search engine) and review jargon dictionary to get rid of non-obvious stuff.

Any input is welcome. Even if you just want to say which entries you are using on regular basis and which problems do you have. I will make such post with mine habits a bit later.

**Comment by NathenSample** [comment]
The issue with jargon is exactly that, it's jargon. It varies between groups of people.

To take your RSB example, if you told me about an RSB(ar-ess-bee), I'd immediately presume you meant a remote shield booster, if you wanted to talk about a remote sensor booster that would be an rsebo(ar-see-boh).

And that's just comparing the difference between two english speaking people, imagine the multitude of slang, all of which is entirely valid, which exists throughout the entirety of the eve community.

**Comment by DarkFenX** [comment]
Sure I realize that it's subjective. But within a context (i.e.: EVE community) you can find out which terms exist and quantify which are more spread than others. So I think it's not a good approach to try to apply assumptions of someone who has no experience with EVE jargon to this, but rather see how jargon is actually used by those who do use it.

That said, i believe with support of multi-term jargon entries we could just assign `Remote Shield Booster` and `Remote Sensor Booster` to RSB. But I'd prefer to do it if someone actually refers to remote shield boosters with RSB.

**Comment by DarkFenX** [comment]
So, list of things I am personally using often:

- races, all of them (in/cn/db/ts etc)
- lml, haml, hml: acronyms for some of missile launchers
- rlml, rhml, rtl: rapid launchers of different sizes
- fvb: focused void bombs
- ab, mwd: propmods
- mjd, mjfg: micro jump drives/fields
- aar: ancillary armor rep
- anp: Adaptive Nano Plating
- asb: Ancillary Shield Booster
- sba: Shield Boost Amplifier
- dc, adc: damage controls, normal and assault
- eanm: Energized Adaptive Nano Membrane
- lar, mar, sar: armor reps of various sizes
- laar, maar, saar: ancillary armor reps of various sizes
- msb, lsb, xlsb: shield boosters of various sizes
- masb, lasb, xlasb: ancillary shield boosters of various sizes (ok i never used small but it makes sense)
- sse, mse, lse: shield extenders of various sizes (but some like lse display alot of garbage)
- rah: reactive armor hardener
- panic: rorq invuln mod
- bcs, mfs, hs, dda: damage mods (using gyro for gyrostabilizer)
- mge, mgc: missile application mods
- tc, te: gun application mods
- dla, dnc, fsu: drone and fighter related upgrades
- rsebo, reccm: Remote Sensor Booster (although reccm is quite legacy already)
- et: Remote Capacitor Transmitter
- rtc/tl: Remote Tracking Computer
- wdfg: Warp Disruption Field Generator
- td: Tracking Disruptor
- tp: Target Painter
- gd: Guidance Disruptor
- pds, pdu: power diagnostic system
- rcu: Reactor Control Unit
- sebo: Sensor Booster
- sa: Signal Amplifier
- mapc: Micro Auxiliary Power Core
- nsa: Networked Sensor Array
- acr: Ancillary Current Router
- ccc: Capacitor Control Circuit
- smc: Semiconductor Memory Cell
- cdfe: Core Defense Field Extender
- lg: Low-grade
- mg: Mid-grade
- hg: High-grade

Things which i use seldomly or see myself using when i need particular module:
- ac: autocannon
- xlcml, cml: cruise missile launchers, normal and capital
- istab: inertial stabilizer
- wcs: warp stab
- dcu, adcu: damage controls, normal and assault
- ssb, sasb: small normal and ancillary shield boosters
- bcu: missile damage mod
- magstab: hybrid damage mod
- mlu: mining laser upgrade
- infinipoint: Warp Disruption Field Generator
- infiniscram: Warp Disruption Field Generator
- md: Guidance Disruptor
- point: Warp Disruptor
- cpr: Capacitor Power Relay
- coproc: Co-Processor
- eccm: Sensor Booster (really legacy)
- jam: ECM
- sigamp: Signal Amplifier
- am: Antimatter
- pp: Phased Plasma
- mf: Multifrequency
- lm: Light Missile
- lo: Liquid Ozone
- ham: Heavy Assault Missile
- hm: Heavy Missile
- cm: Cruise Missile
- nrp: Nanite Repair Paste
- np: Nanite Repair Paste
- bubble: Warp Disrupt Probe

Things which I do not like as they are:
- odi: overdrive (should be od)
- raar: remote ancil rep, no entry

**Comment by DarkFenX** [comment]
Correct approach to jargon revision would be to go through various item groups and think how they can be searched for (jargon entries, key words if jargon entries are not available, also have to gauge amount of clutter search query produces).

**Comment by DarkFenX** [comment]
Changes are merged to `singularity` branch. Following entries have been removed:
```
# sizes
large: heavy
heavy: large

# weapons
rt: Artillery
bs: Blaster
rg: Railgun
pl: Pulse Laser
bl: Beam Laser
ml: Missile Launcher
lnb: Light Neutron Blaster
lib: Light Ion Blaster
leb: Light Electron Blaster
hnb: Heavy Neutron Blaster
hib: Heavy Ion Blaster
heb: Heavy Electron Blaster
nbc: Neutron Blaster Cannon
ibc: Ion Blaster Cannon
ebc: Electron Blaster Cannon
isb: Ion Siege Blaster
capbc: Ion Siege Blaster
hawbc: Triple Neutron
tnb: Triple Neutron
125rg: 125mm Railgun
150rg: 150mm Railgun #also catches dual 150mm railguns
75rg: 75mm
200rg: 200mm Railgun
250rg: 250mm Railgun #also catches dual 250mm railguns
350rg: 350mm Railgun
425rg: 425mm Railgun
caprg: 1000mm Railgun
1000rg: 1000mm Railgun
125ac: 125mm AutoCannon
150ac: 150mm AutoCannon
200ac: 200mm AutoCannon
220ac: 220mm AutoCannon
180ac: 180mm AutoCannon
425ac: 425mm AutoCannon #catches both regular 425mm and dual
650ac: 650mm Repeating Cannon
800ac: 800mm Repeating Cannon #catches both regular 800mm and quad
hawac: Quad 800mm #for those who want to quickly find the HAW ac
2500ac: 2500mm Repeating Cannon
capac: 2500mm Repeating Cannon
250rt: 250mm Artillery
280rt: 280mm Artillery
650rt: 650mm Artillery
720rt: 720mm Artillery
1200rt: 1200mm Artillery
1400rt: 1400mm Artillery
3500rt: 3500mm Artillery
caprt: 3500mm Artillery
dlp: Dual Light Pulse
# gpl: Gatling Pulse Laser - conflicts with giga pulse
sfp: Small Focused Pulse
fmp: Focused Medium Pulse
hpl: Heavy Pulse Laser #also catches dual heavy
mpl: Mega Pulse Laser #also catches quad mega
cappl: Dual Giga Pulse
gpl: Dual Giga Pulse
hawpl: Quad Mega Pulse
sfb: Small Focused Beam
dlb: Dual Light Beam
fmb: Focused Medium Beam
qlb: Quad Light Beam
hbl: Heavy Beam Laser #catches dual heavy
mbl: Mega Beam Laser
tbl: Tachyon Beam Laser
gbl: Dual Giga Beam Laser
capbl: Dual Giga Beam Laser

hal: Heavy Assault Missile Launcher
tpl: Torpedo Launcher

hawml: Rapid Torpedo Launcher
hawtl: Rapid Torpedo Launcher
captl: XL Torpedo Launcher
capcml: XL Cruise Missile Launcher
capcl: XL Cruise Missile Launcher

# Propulsion Modules
smwd: 5mn
sab: 1mn
mmwd: 50mn
mab: 10mn
lmwd: 500mn
lab: 100mn
cmwd: 50000mn
cab: 10000mn

# Tank Modules
100pl: 100mm Plates
200pl: 200mm Plates
400pl: 400mm Plates
800pl: 800mm Plates
1600pl: 1600mm Plates
25000pl: 25000mm Plates
ain: Adaptive Invulnerability Field

cpl: 25000mm Plates
lap: 1600mm Plates
sfc: Shield Flux Coil
thrf: Thermal Dissipation Field
knrf: Kinetic Deflection Field
emrf: EM Ward Field
exrf: Explosive Deflection Field
thra: Thermal Dissipation Amplifier
knra: Kinetic Deflection Amplifier
emra: EM Ward Amplifier
exra: Explosive Deflection Amplifier

# Weapon Upgrades
bc: Ballistic Control System


# Engineering
cpu: Co-Processor
spr: Shield Power Relay
cbat: Cap Battery
cbst: Capacitor Booster

# Ammo/Charges
cnam: Caldari Navy Antimatter
fnam: Federation Navy Antimatter
inmf: Imperial Navy Multifrequency
mc: Mining Crystal
wdp: Warp Disrupt Probe
sp: Scanner Probe
ars: Armor Resistance Script

# Rigs
tap: Trimark Armor Pump
aap: Anti- Pump
pcu: Processor Overclocking Unit
asr: Anti- Screen Reinforcer
```
Quite many have been added. See current list [here](https://github.com/pyfa-org/Pyfa/blob/fc93c61fcf7ef857e74344035b72bf9b54f939d4/service/jargon/defaults.yaml).

I also added ability to search for items using regex (`re:` prefix) and changed the way built-in and user jargon works: user file is empty by default, but default jargon is still taken. So user adds to or overrides built-in jargon. This means that whenever we update jargon file, existing users will be able to have these updates.
