### ISSUE TITLE
Feature Request: Add Capsule to Available Ship Hulls

### ISSUE THREAD

**Issue by alexanderdarino** [pyfa-org/Pyfa#2056]
Oddly enough, there are many times I find myself needing to reference the stats of a capsule in relation to designing other fits, and it's such an inconvenience to have to reference the stats in game. Common questions/use cases that arise that justifies adding capsules into Pyfa:

- How do skills affect capsule stats? This is particularly important for shield/armor/hull - it might be enough of a difference to survive that one extra smartbomb. Speaking of which: Given resists and raw HP, which damage type should I opt for when I fit pod-killing smartbombs?
- What's the sig radius of a capsule? Important to computing lock times for other weapons
- What's the warp speed of a capsule? How likely am I to race it to its destination and destroy it there?
- etc

This is all information that would be handy to have readily available in Pyfa. **_We already have shuttles - why not capsules?_**

**Comment by DarkFenX** [comment]
Indeed. Added in 1efe4ee5e58099bb17859d56e4313529882dca82 - now capsules will be in Shuttle group, starting from next database update.

If you think they should be added to any other group instead (like their own Capsule group), do tell, this can be changed easily.
