### ISSUE TITLE
[Feature request or clarification request] Scan strength, deviation, duration

### ISSUE THREAD

**Issue by mithlug** [pyfa-org/Pyfa#2058]
I can't find the scan strength, deviation, duration of the fitted probe and launcher. Find something about scan strength at 2AU range... It is wildly mismatched with my in-game numbers and make little sense, is it an old way of using the number?

**Comment by DarkFenX** [comment]
Scan strength at 2 AU range in tooltip was introduced before EVE introduced probe strength readout to probing window. So yes it is different. I might change it to match in-game, but i will have to check how exactly it works there.

All "raw" stats are shown on probe itself.

![image](https://user-images.githubusercontent.com/275209/66276999-0b641d80-e8a1-11e9-83c1-9a8342341de9.png)

The value you see on tooltip or in probe scanner window needs extra processing, but is based on these numbers.

**Comment by DarkFenX** [comment]
Scan time is attribute of module itself, rather than probe.

**Comment by mithlug** [comment]
base sensor strength matched perfectly with my probe window, personally I'm happy and consider it closed but removing the old info and put the actually interesting info could be a good enhancement.

**Comment by DarkFenX** [comment]
@mithlug what's "actually interesting" info for you? Please be as specific as possible.
Scanning time, devitation are normally nearly irrelevant, from my experience, scanning strength is key parameter. In which form would you like to see it? Base sensor strength attribute?

**Comment by mithlug** [comment]
Sry, yeah, scanning strength, the current value presented under the probe info. That way I could see how it changes depending on charge, ship, skill etc.

**Comment by DarkFenX** [comment]
Reopening until it is changed

**Comment by DarkFenX** [comment]
Changed in 8d81db0a3a2868311bd03960ac6f118d0f3daac6
