### ISSUE TITLE
Hound wrong values.

### ISSUE THREAD

**Issue by frakc** [pyfa-org/Pyfa#2059]
i have drastically different dps values for hound in Pyfa nad in game?
pyfa shows 478 DSP
ingam efitting 900DPS

[Hound, Falendor Mar's Hound]

Ballistic Control System II
Ballistic Control System II
Ballistic Control System II

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
Polarized Torpedo Launcher, Nova Rage Torpedo
Polarized Torpedo Launcher, Nova Rage Torpedo
Polarized Torpedo Launcher, Nova Rage Torpedo
[Empty High slot]

Small Warhead Calefaction Catalyst II
[Empty Rig slot]

**Comment by DarkFenX** [comment]
Shows 983 dps for me.

Please right-click DPS stats panel and check:

- if reload option is on
- if any target resists profile is selected

I suspect you have reload turned on vs 50% explosive resist profile.

**Comment by frakc** [comment]
yep my bad(
