### ISSUE TITLE
[Implants] Add ability to create an Implant Set Editor group from the fit view

### ISSUE THREAD

**Issue by Gochim** [pyfa-org/Pyfa#2073]
Generally simplify work with implants groups. 

## Suggestion
Give an ability to create new set in the Implant Set Editor from the Implants tab in the main view of the fit.

## Expected behavior 
In the main fit window, switch to the "Implant" tab. In the context menu select "Create new implant set". On selection - ask for the name of a new group.

--- Edit. By "Create new implant set" I mean create a new group from implants that are currently in the "implants" list for the fit.

**Comment by DarkFenX** [comment]
Accepted pull request with some extra renames. Will fix some bugs later, and maybe will add ability to disable it.

**Comment by DarkFenX** [comment]
There's issue with it: when user presses "cancel", it opens implant set editor anyway.

**Comment by DarkFenX** [comment]
Changed in 8c2788fd78a4b2576e0bb526f8d67d263e2a7e7b
