### ISSUE TITLE
Tactical Destroyer modes gui

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#208]
How best to interact with modes of t3 destroyers.

Some ideas:
* Design a new stats panel. Can either be something as simple as a drop down menu, or something a little more flashy such as the three mode icons with the current selected one highlighted. Or, instead of icons, use of toggle buttons.
    * Disadvantages: More vertical screen space required for pyfa -- since pyfa has to have a minimum vertical space set to encompass the vertical height of all stat panels, this would add space that will only be occupied when working on a t3 dessy. UPDATE: While doing the mockups shown below, The vertical space required is not so bad, and we would't need to adjust the minimum screen required - the price panel would just overflow and the user would have to collapse a panel. This may be acceptable.
    * Advantages: fairly easy to do (if we incorporate icons, might be more difficult as blending of the UI icons would be required and I'm not a graphic artist)
    * Mock-ups (non-functional)(out of these two, I prefer the toggle buttons, and I believe 32x32 icons would extend ):

![toggles](https://cloud.githubusercontent.com/assets/3904767/5294706/9c47d8bc-7b57-11e4-85ee-98b633d7d2f2.PNG)

![dropdown](https://cloud.githubusercontent.com/assets/3904767/5294643/b6ebd6ce-7b56-11e4-83ff-813bc4fd198d.PNG)

* Design a new fitting toolbar. This will be situated under the module fitting window, and includes icons / toggles for tactical mode. We can also include other features such as quick export to clipboard.
    * Disadvantages: Much more work to integrate. We would also need more functions to be included in the toolbar to have it be worth the effort
    * Advantages: doesn't increase minimum vertical space, will provide a nice container for future features / helpers

**Comment by Ebag333** [comment]
@blitzmann  Does this need to stay open since you've since done a solution for this?

It makes more sense where it's at now than moving it to the stats pane, plus we don't have room on the stats pane.

**Comment by blitzmann** [comment]
Yeah, I'm gonna close this. I still thin adding it to the stats pane would be nifty, but maybe in a :future: version of pyfa :)
