### ISSUE TITLE
Damage graphs against different resist profiles are identical

### ISSUE THREAD

**Issue by ErwinMadelung** [pyfa-org/Pyfa#2081]
I'm not sure if this is a bug or simply not implemented as a feature (yet).

### Expected behavior:
In the graph window you can choose between several target profiles. Those include "ideal target", "uniform (50%)" and so on. They refer to different resist profiles. The graph for "uniform (50%)" should be exactly half of the graph for "ideal target".

### Actual behavior:
The graphs against different resist profiles are identical:
![image](https://user-images.githubusercontent.com/38285590/68781135-97ebc380-0637-11ea-8aff-e931cfd207ce.png)

**Comment by DarkFenX** [comment]
Top-right to vector controls there is a menu icon. You have "ignore resistances" turned on. If you have them turned off, target list shows target resists and Y axis is named "effective DPS".

**Comment by ErwinMadelung** [comment]
I'm a derp. Ty for the answer.
