### ISSUE TITLE
Implement missile range bonus which compensates attacker's ship radius

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#2083]
https://forums-archive.eveonline.com/default.aspx?g=posts&m=6523910#post6523910

> Q: How does the missile change work?
> A: Missiles 'fly' from the center of your ship to the target. This with especially large ships (such as a Leviathan) this can cause problems. They have a range (flight time * speed) of (for example) 40km. But because the missile has to fly across the radius of the Leviathan (8km in this example) their effective range is only 32km.
> Missiles now get a small bonus to their flight time based on the radius of the ship launching them. So in the above example they will hit targets 40km away.

This is not implemented in pyfa, and it affects some edge-cases like rapid torp phoenix too much (ATM attacker ship radius is considered only for graphs, but we should consider it for all cases probably).

**Comment by DarkFenX** [comment]
Since f778f9ceae639168aa1896bf92a9ae1bb4018a7d we consider ship radius to show missile range in range column. I asked Larrikin to provide formula details in slack, so waiting for his input to actually close it.

**Comment by hooper82** [comment]
Once a missile is launched (that is, after all the ship, skill, module bonuses are applied), the `explosionDelay` is modified:

- If launched by NPCs: `explosionDelay *= missileEntityFlightTimeMultiplier`
- If launched by a Character: `explosionDelay += attackingShipBallRadius / missileVelocity * 1000`

`missileVelocity` is taken after all ship/skill/module bonuses are applied.
The `1000` is for unit conversion.

**Comment by DarkFenX** [comment]
Added flight time bonus in f80b7d972f2a035ac23c11dd6aa1c20efc259b4b

**Comment by DarkFenX** [comment]
@ErwinMadelung, answer to this question might be interesting to you
