### ISSUE TITLE
No Module named 'markdown2'

### ISSUE THREAD

**Issue by boolves** [pyfa-org/Pyfa#2090]
pyfa v2.14.2
EVE Data Version: 1604553 (2019-11-12 04:15:35)

OS version: Linux-5.3.11-arch1-1-x86_64-with-glibc2.2.5
Python version: 3.8.0 (default, Oct 23 2019, 18:51:26) 
[GCC 9.2.0]
wxPython version: 4.0.6 (wxWidgets 3.0.4)
SQLAlchemy version: 1.3.11
Logbook version: 1.5.3
Requests version: 2.22.0
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "/usr/share/pyfa/pyfa.py", line 136, in <module>
    from gui.mainFrame import MainFrame
  File "/usr/share/pyfa/gui/mainFrame.py", line 62, in <module>
    from gui.updateDialog import UpdateDialog
  File "/usr/share/pyfa/gui/updateDialog.py", line 28, in <module>
    import markdown2
ModuleNotFoundError: No module named 'markdown2'

**Comment by pezz** [comment]
This is a specific Arch Linux / AUR issue due to the recent python 3.8.0 update.

Rebuilding python-markdown2 from the AUR resolves this.

**Comment by DarkFenX** [comment]
It is not specific to Arch. Every time your `python3` link changes (e.g. instead of linking to `python3.7` starts linking to `python3.8`), you lose all your prereqs which were installed via pip, because those are stored in version-specific directories like `~/.local/lib/python3.7/site-packages`.

So every time it happens, you have to reinstall all the prerequisites which you previously installed via pip.

**Comment by pezz** [comment]
Things are not built and installed using pip in general on Arch, dependencies are built individually and left under the control of the system package manager pacman.

But the manifestation of this problem and fix are similar.

**Comment by DarkFenX** [comment]
Well, yeah. It might be omission by python3/markdown2 maintainer, in case markdown2 is installed as system package. Doesn't change the way pyfa is related to it, though.

**Comment by pezz** [comment]
Oh nah, totally agree, wasn't trying to imply that pyfa was the issue at all, sorry if it came across like that.

**Comment by boolves** [comment]
Thanks guys. Will rebuild.
