### ISSUE TITLE
Import fitting xml and clipboard failing

### ISSUE THREAD

**Issue by LucidityCrash** [pyfa-org/Pyfa#2091]
## Bug Report

As of release  2.14.1 I can't import EFT fittings from clipboard or import xml

### Expected behavior:

Fit is imported.

### Actual behavior:

Clipboard import just appears to do nothing, and leaves the following in the log :
Import XML just hangs on the importing page with the progress bar just spinning and elapsed time sitting at 0.  Have to kill task in Task Manager to exit.

[2019-11-17 11:57:37.624497] ERROR: gui.mainFrame: Attempt to import failed:
<fit text>

### Detailed steps to reproduce:
either try and paste plain text fit or use import xml menu option - nothing fancy

### Fits involved in EFT format (Edit > To Clipboard > EFT):
Can provide privately :)

### Release or development git branch? Please note the release version or commit hash:

Release 2.14.1 and 2.14.2

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Window 10

**Comment by DarkFenX** [comment]
Send the data to phoenix@mail.ru, will look into it.

**Comment by DarkFenX** [comment]
Your fit format is malformed. For cargo, it specifies amount of items as `x 100` instead of `x100`, while EFT format almost had it as latter string.

Where did you get this from?

**Comment by DarkFenX** [comment]
After changes in bec58a5772fdb48f532b68c5d407916543f82644 pyfa will process such errors more gracefully. Your EFT format now imports, just w/o cargo items.

XML import failure was pyfa's fault. It did not tolerate extra node attributes. Fixed in e649683a4d420b1187d6538ee58e2e0322c25f87

**Comment by DarkFenX** [comment]
Leaving it open until I found out what produces malformed EFT export.

**Comment by LucidityCrash** [comment]
That can't be the only problem as the XML fails to import too

**Comment by LucidityCrash** [comment]
Found the issue with the xml 
<?xml version="1.0" ?> works 
<?xml version="1.0" encoding="UTF-8"?> doesn't

**Comment by DarkFenX** [comment]
This issue appeared due to fb48f2b5d4ee08bf53240894dc342ee89ac887cc, which implemented fix for `Pasting malformed text into Additions panel does not cause an error message anymore`. I do not want to dig into why this fix uncovered it, but the fix I implemented now looks appropriate.

XML pasted from buffer did not work exactly due to the issue you posted. It has been fixed already, as I mentioned.

**Comment by LucidityCrash** [comment]
Thanks for the quick fix ...

The broken EFT was from a custom page that shares fittings for our alliance ... there was a bug in it which introduced a space after the x.  I believe I've got that bug resolved now.
This tool is also generating the xml and I think I've found a way to stop it adding the encoding option to the header, just need to test it.
