### ISSUE TITLE
Indy Cyno not available for Venture

### ISSUE THREAD

**Issue by tungstenmeteor** [pyfa-org/Pyfa#2093]
Ventures can't fit Industrial Cynos in pyfa. This is a recent functionality change in Eve.
Ventures also get a 50% liquid ozone cost reduction in the Beat around the Boosh update.

**Comment by DarkFenX** [comment]
They got it after the update. The latest pyfa release contains all the changes released with initial "beat around the boosh" version.

I will probably make another release today to have this change included too.

**Comment by DarkFenX** [comment]
Fixed in 043c43022121867e3a589a9a703fb2bd16d7df7c
