### ISSUE TITLE
Feature Request: DPS mouse over shows breakdown of EM,Thermal,Kinetic, Explosive DPS.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#2098]
Hi,
It is pretty tedious to calculate the damage profile of a ship manually and then use the damage profile editor. It would really handy if the damage profile of a ship was available with a mouse over on dps or something similar.

Cheers,
Neug

**Comment by DarkFenX** [comment]
Since I reimplemented graphs this should be pretty trivial, as damage info is already exposed as em/therm/kin/explo, and UI just takes total damage.

**Comment by DarkFenX** [comment]
@Neugeniko do you think it's better to expose absolute values or percentages?

**Comment by DarkFenX** [comment]
I added basic implementation into 39edec60e36bba8e6b4e4d418f0aae8bd4ec27c3. Now, tooltip is formatted as following (numbers are arbitrary):
```
Em: 22.2%
Thermal: 33.3%
Kinetic: 44.4%
Explosive: 55.5%
```

When some damage type is absent it just doesn't get added.

However, it does not play well with spoolup weapons. Those had `Spool up: 500-2500` added to the tooltip and still have.

The resistance values shown in tooltip are for current fit settings (i.e. whatever you choose as spoolup value for your disintegrators). The values `500-2500` in the spoolup section of tooltip are min and max values regardless of fit settings. It is quite obvious that as disintegrator spools up, damage ration changes, if fit has any other damage sources (like drones).

So - any ideas on how to fit everything into single tooltip? Consider worst-case scenario: total dps tooltip for ship like drekavac with disintegrator and bunch of EM / kinetic drones (say, 2 praetors and 2 vespas).

**Comment by DarkFenX** [comment]
One way is just not to show damage type distribution for min and max spoolup values:
```
Spool up: 500-2500
Em: 22.2%
Thermal: 33.3%
Kinetic: 44.4%
Explosive: 55.5%
```

Another way is to condense damage distribution values:
```
22.2% / 33.3% / 44.4% / 55.5%
Pre spoolup: 500, 11.1% / 22.2% / 33.3% / 44.4%
Full spoolup: 2500, 33.3% / 44.4% / 55.5% / 66.6%
```

**Comment by Neugeniko** [comment]
The basic infomation looks great. A percentage is good for general info and also is good for punching it into the damage profile editor cause it shows percentages there too.

I'm unsure about the spool up format. I have the same problem in my public facing spreadsheets
for npc analysis on what value of spool up to use. I think its better to show the profile that matches the dps figures shown.

**Comment by DarkFenX** [comment]
Well, pyfa shows all 3 figures, but min and max are hidden in tooltip (with a hint in the panel, that weapon is variable damage). I agree we have to show damage type split for the figures shown in the dps panel itself. The question is, however, do we want to show them for min spool and max spool values, and if yes - how do we present all this info?

**Comment by Neugeniko** [comment]
I think it is too much information to include the max/min spool info in a tool tip. Maybe group the current dps with the current profile to try indicate that it doesnt apply to the spool value: and then people can change the spool up percentage in preference to see the different current profile.

Current: 448
Em: 22.2%
Thermal: 33.3%
Kinetic: 44.4%
Explosive: 55.5%
-----------------
Spool up: 448-2500

**Comment by DarkFenX** [comment]
Agreed, at least it looks less confusing. I changed order to show spoolup values on top though. Spoolup-enabled tooltip:

![image](https://user-images.githubusercontent.com/275209/70072030-45367380-1607-11ea-8293-03f921ea6052.png)

Regular tooltip:

![image](https://user-images.githubusercontent.com/275209/70072074-5aab9d80-1607-11ea-8486-3013dbd56c37.png)

Closing the issue.
