### ISSUE TITLE
Feature Request: Effective cap regen tooltip.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#2099]
the neutralizer resistance tool tip could use some addition information.

Namely effective cap  regen after neut resists.  Only shown for positive cap regen with mouse over the neut resist text. effective cap regen = cap regen/(1-ship neut resist).

**Comment by DarkFenX** [comment]
Added in 72c74513ce37deb18f573527029994fa9eca898b:

![image](https://user-images.githubusercontent.com/275209/70173729-82246800-16e4-11ea-88ed-04f4ca002fb9.png)

**Comment by Neugeniko** [comment]
Right now it will only show effective excess gain if you have something draining cap. You should be able to see it as long as you have neut resistance and positive excess gain.

**Comment by DarkFenX** [comment]
Fixed in a15896044dd6596eb20f4b31e6f3677e7ecdc6db

**Comment by Neugeniko** [comment]
Looks good.
