### ISSUE TITLE
Toggling Factor in Reload doesnt recalculate tank stats.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#2114]
Since factor in reload  has effected tank stats for a long while now, the tank stats (reload of nanite paste/boosters in AAR/ASB) should also recalculate when setting factor in reload from the right click firepower menu.

Using the fit below with paste and boosters in the aar/asb. Toggle the factor in reload and note the tank stats dont get recalculated, you have to manually deactivate/reactivate a module to get the recalculation.

[Retribution, sustained ancil shield booster extra test]

Small Ancillary Armor Repairer, Nanite Repair Paste
Small Armor Repairer II
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

Small Ancillary Shield Booster, Cap Booster 25
Small Shield Booster II

Small Energy Neutralizer II
Small Remote Capacitor Transmitter II
Small Ancillary Remote Shield Booster, Cap Booster 25
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]

**Comment by Neugeniko** [comment]
Also when you toggle the factor in reload and go back to a fit which was calculated with a different factor in reload, the fit is not recalculated (cached?).

**Comment by DarkFenX** [comment]
The first part has been fixed for some time. Maybe just on sisi branch (which i just merged into master), unsure. But it cannot be reproduced anymore nevertheless. As for second part - it might be tricky one.

**Comment by DarkFenX** [comment]
Nvm, i have fixed 2nd part already, too.
