### ISSUE TITLE
CCP have changed Invasion NPCs, recalculate damage and target profiles.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#2122]
I'm going to recalculate these profiles and put in a pull request.

Cheers,
Neug

**Comment by DarkFenX** [comment]
@Neugeniko LG nirvana was introduced. I want to do a release today (to include it and other 2 important bug fixes - broken sirens and broken effect resistance support). If you think you can do it in next few hours, then I can wait for it. Otherwise it will ship in the release after this one.

**Comment by Neugeniko** [comment]
> @Neugeniko with today's patch, LG nirvana was introduced. I want to do a release today (to include it and other 2 important bug fixes - broken sirens and broken effect resistance support). If you think you can do it in next few hours, then I can wait for it. Otherwise it will ship in the release after this one.

I should have it done within the hr.

**Comment by DarkFenX** [comment]
Great! Thank you.

**Comment by Neugeniko** [comment]
Ok its done and triple checked.

**Comment by DarkFenX** [comment]
Thanks, merged.

**Comment by DarkFenX** [comment]
@Neugeniko 
```
Renamed groups:
    "b'Invading Precursor Entities'": "b'Triglavian Entities'",
    "b'Retaliating Amarr Entities'": "b'EDENCOM Entities'",
    "b'Retaliating Caldari Entities'": "b'Drifter Entities'",
    "b'Retaliating Gallente Entities'": "b'Sleeper Entities'",
    "b'Retaliating Minmatar Entities'": "b'Rogue Drone Entities'",
```
I renamed 1st entry, but i think last 4 just have to be removed. Please tell me what to do with all this stuff.

**Comment by Neugeniko** [comment]
i will get back to you shortly

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Neugeniko** [comment]
"b'Invading Precursor Entities'": "b'Triglavian Entities'",
is ok


the other four should be like this template
"b'Retaliating <racial> Entities'": "b'<racial> EDENCOM Entities'",

as they are encountered together by race never mixed and need a separate profile

i will work on the drifter,rogue drones  & sleeper damage and target
profile for invasions(new trig space) when i get some time.

**Comment by DarkFenX** [comment]
Ok, thanks
