### ISSUE TITLE
Single-resist shield hardeners/platings do not update EHP values

### ISSUE THREAD

**Issue by david-e-wood** [pyfa-org/Pyfa#2126]
## Bug Report
When adding certain shield hardeners/resistance platings to fits, the EHP values on the right panes do not update.

### Expected behavior:
All single-resist hardeners/platings should update EHP values.

### Actual behavior:
Only kinetic hardeners/platings update EHP values.

### Detailed steps to reproduce:

* Set up fit from below section.

* Add any basic T1/T2 single-resist shield hardener or resistance plating except kinetic. EHP numbers on the right do not update

* Equip a kinetic version. EHP numbers update.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

[Caracal, Caracal fit]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

Medium Shield Booster II
Cap Recharger II
Cap Recharger II
Cap Recharger II
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:

Release version 2.16.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 7

### Other relevant information:

I didn't check if this effects armor EHP numbers too.

**Comment by DarkFenX** [comment]
Screenshot of main window please. Likely incoming damage is set to 100% kinetic.

**Comment by david-e-wood** [comment]
> Likely incoming damage is set to 100% kinetic.

Whoops, my mistake, you are correct.
