### ISSUE TITLE
Pyfa 2.16.2/3 Started flipping the UI to "RTL"

### ISSUE THREAD

**Issue by leonbur** [pyfa-org/Pyfa#2128]
A picture is worth a thousand words:

![Capture](https://user-images.githubusercontent.com/8167543/73277063-4db7be80-41f2-11ea-8f9f-ef728611abee.PNG)

This started as I updated from 2.16.0 to 2.16.2 as well as 2.16.3.
I am located in the middle east but my Windows is localed to EN-US. 

Environment:
Windows 10 64bit, Python 3.6.

**Comment by DarkFenX** [comment]
This is likely caused by update of wxpython 4.0.7. Could you make screenshots of all relevant regional settings in windows? I will try to reproduce it.

**Comment by DarkFenX** [comment]
https://github.com/wxWidgets/Phoenix/issues/1008 this ticket contains more info, please try changing the setting the ticket mentions

**Comment by leonbur** [comment]
My mistake, it appears that my region is set to Israel (even though the UI localization remains English). When I set it to United States the Pyfa UI goes back to normal. 
It's still a bug though, right?

Current Region:
![current region](https://user-images.githubusercontent.com/8167543/73356430-050c0e00-42a3-11ea-840e-5606fad1f068.PNG)

All Regions:
![all regions](https://user-images.githubusercontent.com/8167543/73356448-11906680-42a3-11ea-9501-ea6e10966a4c.PNG)

**Comment by DarkFenX** [comment]
Ok as a next step, could you confirm again that 2.16.1 worked for you even if it's set to Israel?

**Comment by leonbur** [comment]
Tested both 2.16.1 and 2.16.0:

2.16.1 is incorrect just like the newer versions
2.16.0 works correctly

**Comment by DarkFenX** [comment]
I posted a comment to the issue i linked above. I do not think there's anything I can do, except for switching back to wxpython 4.0.6 (which I will probably do, as 4.0.7 doesn't seem to fix anything from our other upstream bugs).

**Comment by DarkFenX** [comment]
@leonbur https://ci.appveyor.com/project/DarkFenX/pyfa/builds/30527549/artifacts try one of these builds.

To fix several issues, I had to update multiple libraries and make pyfa a 64-bit application. Among those library updates there was python update to 3.8, which should fix this issue for you (if info from wxpython maintainers is correct).

**Comment by leonbur** [comment]
The new build doesn't solve the issue.

**Comment by DarkFenX** [comment]
I reproduced the issue on my win8.1. Just setting "formats" to Hebrew seems to lead to this issue. Both ways suggested by wxpython maintainers did not work so far.

**Comment by DarkFenX** [comment]
Worked around it in 61a01805cc28d2c1e17d8c76a05f58ec5ba11102
