### ISSUE TITLE
Popups on wrong monitor

### ISSUE THREAD

**Issue by NikolasCalypso** [pyfa-org/Pyfa#2130]
### Expected behavior:
Popups on the same monitor as pyfa main window (or at least primary monitor).

### Actual behavior:
Popups on my 3rd monitor (my television... grrr)

### Detailed steps to reproduce:
Open pyfa
Open a fit
ctrl+c

### Fits involved in EFT format (Edit > To Clipboard > EFT):
any/na

### Release or development git branch? Please note the release version or commit hash:
release

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
win 10

**Comment by DarkFenX** [comment]
Make a screenshot please and describe your full monitor configuration (displays with resolution info, video card info, how displays are plugged to video cards).

Although by the nature of the issue it seems to be wxpython/wxwidgets issue, so out of our control. I just might be able to change a few things exposed to Pyfa, but I need to be able to reproduce it 1st.

**Comment by NikolasCalypso** [comment]
https://i.postimg.cc/K80Pd2n4/pyfa-popup.png

Here's a screenshot for you. As you can see the popup is on the "wrong" monitor. It is on monitor 2, instead of monitor 3. 

Monitors from left to right are:
#2 (1920x1080) Samsung 52" smart TV (Model: UN50H5203AF) (HDMI)
#1 (1920x1080) Benq 27" GL2760H (HDMI)
#3 (1920x1200) I-Inc iH282 (DVI<->HDMI)

All powered by a single Radeon Rx480. 

I believe the number (from system display info) corresponds to the hardware port on the video card, but I'm not 100% on that. 

I did a bit of testing for you, and my best guess is that "something happens" that causes Pyfa to reset to default position. The pop ups go to monitor 2, and if I close and open Pyfa, it starts up on monitor 2 as well. I haven't figured out what "something" is yet. I can't 100% reproduce it just by opening and closing, but this does happen to me on a very regular (almost daily sometimes) basis.

If it turns out we can't reliably reproduce this, can I request a feature be added to auto open (or an option to open last closed tabs)? This way I can just close and open Pyfa a couple of times, and it would be far less bothersome if I didn't lose my open tabs every time I did that.

**Comment by DarkFenX** [comment]
![image](https://user-images.githubusercontent.com/275209/74247119-a27d2e00-4cf6-11ea-97e3-8f8ba992eae7.png)

You mean this option, or something different?

**Comment by NikolasCalypso** [comment]
Yeah, just found that, thanks. That will make things easier for sure.

**Comment by NikolasCalypso** [comment]
So, Pyfa went back to monitor 2 again today. There was also an update, so I guess that would count as "something happened".  Any chance you could have a fresh install default to primary monitor instead of tertiary?

**Comment by DarkFenX** [comment]
Last release I reverted wxpython to 4.0.6 due to an issue https://github.com/wxWidgets/Phoenix/issues/1515

Was it working just fine for you the release before that?

**Comment by NikolasCalypso** [comment]
I recently came back to eve from a break, so its been a while since I've used Pyfa, but I want to say this has been going on for years. Its just always been this "random" annoying thing.

**Comment by NikolasCalypso** [comment]
Okay, I think I have this figured out.

When I turn off my secondary monitor, everything gets shifted to the tertiary monitor, including Pyfa (I don't know whose idea this was, but its a real pain). So, I drag Pyfa (and everything else) back to secondary, when I turn it back on. 

However, the problem is, all the Pyfa popups stay on tertiary monitor, and even when exiting Pyfa and relaunching it, it will launch and show pop-ups on the tertiary monitor (instead of secondary). 

After turning the monitor on, I have to move Pyfa to secondary monitor, close it, open it, move it back to secondary monitor again, close it again, open it again, and then it will stay on the secondary monitor until next time.

**Comment by DarkFenX** [comment]
Interesting. But, as I mentioned already, this is a functionality which is out of our control. We cannot choose where various dialogs will pop up from our code. So - as sad as it may sound - you might have to live with those ugly work-arounds. Rewriting pyfa with another UI toolkit might help, but it is not something we can expect in near future.

**Comment by NikolasCalypso** [comment]
Okay, fair enough. I'll keep troubleshooting on my end and see if that will help any. I have a suspicion that something is malfunctioning. The system is acting like the secondary monitor gets unplugged when it is turned off, and none of the others show that behavior.
