### ISSUE TITLE
dps calculations don't include abyss weather

### ISSUE THREAD

**Issue by NikolasCalypso** [pyfa-org/Pyfa#2131]
### Expected behavior:
dps calculations to include abyss weather (resistance penalties)

### Actual behavior:
dps calculations do not include abyss weather (resistance penalties)

### Detailed steps to reproduce:
load a fit
select em ammo
add 'electrical storm 3' addition

### Fits involved in EFT format (Edit > To Clipboard > EFT):
any/na

### Release or development git branch? Please note the release version or commit hash:
release

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
win10

### Other relevant information:
checked multiple fits, weather types, and damage profiles. pyfa does show reduced resistances for defense, but not increased dps as it would be, due to the reduced resistances on your target.

**Comment by DarkFenX** [comment]
@NikolasCalypso what do you have set as current target, and where (DPS stats panel or graph window)?

**Comment by NikolasCalypso** [comment]
Okay, I think I found the problem here. I had target resists set to (omni 50%) to approximate some of the battleships in the abyss. I had "Electrical Storm 3" added to Additions->Projected. I was expecting this to show the effective firepower numbers change because of the projection, but it does not.

But, I found under "Target Resists->NPC->Abyssal->Gamma T4/T5->Drifter" changes the effective firepower numbers.

So, its there, and I can use it, that's great... it just seems a bit redundant to have to select the same projection twice. I think you could consolidate all the Abyss NPCs in to one menu and use the projected weather effect. But that's a pretty minor change.

Closing this off, as technically the option is available, and correct. :) Thanks.

**Comment by DarkFenX** [comment]
Yeah, weather is coded to affect only the fit which you are looking at. Changing it to proper environment, which affects current fit, all projected fits and targets is not an easy task. Maybe during rewrite of pyfa...
