### ISSUE TITLE
Add flatpak build option

### ISSUE THREAD

**Issue by mainerror** [pyfa-org/Pyfa#2133]
I'm intending to dedicate some of my time to include [flatpak](https://docs.flatpak.org/en/latest/introduction.html) build support into the build process if that effort is welcome.

This should be rather straightforward, since flatpak doesn't impose any project structure or built chain requirements unlike Snapcraft or AppImage.

**Comment by DarkFenX** [comment]
Linux builds are something that @blitzmann wanted to do when he made pyfa build jobs (according to comments he left there or in some issues) but never ended up doing it. I also never got to it.

If you can add it - that would be great. Ask any questions, I might be able to integrate it with our build process if necessary.

**Comment by mainerror** [comment]
Alright. First I'll get flatpak to build locally, smooth off the rough edges, then I'll integrate it in the build process and then I'll create a pull-request.

**Comment by blitzmann** [comment]
I actually just heard about flatpak like two weeks ago, and thought it
would be a cool way to finally get linux builds distributed for pyfa. It
would be wonderful if you can get it working :D

**Comment by WhyNotHugo** [comment]
Flatpak support would be super valuable. It seems that pyfa only works with older python versions, so native packages on Linux (like the [AUR](https://aur.archlinux.org/packages/pyfa) one) no longer work.

Flatpak allows bundling outdated versions of dependencies when necessary like this.

Do any of you guys have an existing manifest? I can try iterating on that.

**Comment by blitzmann** [comment]
We have automated Linux AppImage builds as of a few releases ago now. Simply download the AppImage, chmod +x it, run it, and it _should_ work. As with everything in Linux, YMMV.

**Comment by WhyNotHugo** [comment]
> Simply download the AppImage, chmod +x it, run it, and it should work. As with everything in Linux, YMMV.

AppImages never update, so it'll be pinned to the original version forever.

**Comment by DarkFenX** [comment]
> AppImages never update, so it'll be pinned to the original version forever.

Pinned to original version of what? Of libraries bundled with it, or something different?

**Comment by WhyNotHugo** [comment]
> Pinned to original version of what? Of libraries bundled with it, or something different?

Whatever version you download and set up is the version you're stuck forever. There's no update mechanism in place.

**Comment by DarkFenX** [comment]
oh, right. There is no way to do that except for doing some kind of wrapper, as far as i know

**Comment by outergod** [comment]
Hello, I have created a working Flatpak version of Pyfa at https://github.com/outergod/io.github.pyfaorg.Pyfa. It comes with all associated benefits, such as the ability to find it via package managers that include Flatpaks such as GNOME Software, and automatic updates. Would you be willing to maintain it?

**Comment by DarkFenX** [comment]
@outergod I am currently working on a pyfa calculation engine rewrite (in a private repo atm, a rust copycat of https://github.com/pyfa-org/eos with http interface), so current codebase has lower priority and I am just maintaining it. Adding more to maintenance in this case is not a great idea imo, since I don't want to spend extra time to figure out how to maintain a flatpak package (and update it every release).

Once I have new fitting tool up and running, I'd be interested in it.
