### ISSUE TITLE
2.17.1 Opening character editor throws an error

### ISSUE THREAD

**Issue by leonbur** [pyfa-org/Pyfa#2136]
Title says it all. here's the error window output:

> pyfa v2.17.1
> EVE Data Version: 1663997 (2020-02-11 15:13:50)
> 
> OS version: Windows-10-10.0.18362-SP0
> Python version: 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
> wxPython version: 4.0.7.post2 (wxWidgets 3.0.5)
> SQLAlchemy version: 1.3.13
> Logbook version: 1.5.3
> Requests version: 2.22.0
> Dateutil version: 2.8.1
> 
> ####################
> 
> Traceback (most recent call last):
>   File "gui\characterSelection.py", line 183, in charChanged
>   File "gui\mainFrame.py", line 443, in OnShowCharacterEditor
>   File "gui\auxFrame.py", line 59, in openOne
>   File "gui\characterEditor.py", line 170, in __init__
>   File "gui\characterEditor.py", line 111, in __init__
>   File "gui\builtinViews\entityEditor.py", line 57, in __init__
> wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(LC_ALL, NULL), "C") == 0" failed at ..\..\src\common\intl.cpp(1579) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
> Things are going to break, please only change locale by creating wxLocale objects to avoid this!
>

**Comment by DarkFenX** [comment]
Thanks. And meh, maybe I will have to revert to wxpython 4.0.6 after all, unless I will find a way to work around this issue too.

**Comment by DarkFenX** [comment]
This is another manifestation of an upstream issue, which was originally filed for pyfa as #2134. Added comment to actual upstream issue: https://github.com/wxWidgets/Phoenix/issues/1515#issuecomment-585764207

Will fix by rolling back to 4.0.6

**Comment by pezz** [comment]
Just FYI - updated Arch Linux to 2.17.2 and the character editor works fine, python-wxpython version on Arch is 4.0.7.2 (last updated Feb 04).

Cheers.

**Comment by DarkFenX** [comment]
Yeah it is most likely windows-specific issue. Still there is a chance you can reproduce it under linux, but you need specific locale settings for that.

**Comment by pezz** [comment]
Ah damn, sorry for that - I did not notice that it was a Windows issue.

A lot of wxpython problems tend to be Linux problems as well heh, bad assumption. :)
