### ISSUE TITLE
it *really* needs dark mode

### ISSUE THREAD

**Issue by TRUELIKEtheRIVER** [pyfa-org/Pyfa#2140]
### Expected behavior:
eyes not hurting from a blinding screen

### Actual behavior:
eyes hurting from a blinding screen

### Detailed steps to reproduce:

use your eyes
### Release or development git branch? Please note the release version or commit hash:
yes

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

win10
### Other relevant information:
for the love of god add a dark mode

**Comment by blitzmann** [comment]
Duplicate #1206
