### ISSUE TITLE
Damage Pattern Editor issue

### ISSUE THREAD

**Issue by Lampucera** [pyfa-org/Pyfa#2145]
#1842 1. Open Dama Bug Report

pyfa v2.18.1
EVE Data Version: 1684558 (2020-03-11 11:50:22)

OS version: Windows-10-10.0.18362-SP0
Python version: 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.14
Logbook version: 1.5.3
Requests version: 2.23.0
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "gui\patternEditor.py", line 215, in OnInputTimer
AttributeError: 'NoneType' object has no attribute 'emAmount'

### Expected behavior:

Attempting to add damage in the Damage Pattern Editor was Unsuccessful by clicking on it manually and entering values

### Detailed steps to reproduce:
1. open Damage Pattern Editor
2. input eg. 45 in Kinectic
3. select next damage field ... stop. error.

### Release or development git branch? Please note the release version or commit hash:
[Gnosis, Gnosis II]

Magnetic Field Stabilizer II
Vortex Compact Magnetic Field Stabilizer
Damage Control II
Drone Damage Amplifier II
Drone Damage Amplifier II
Tracking Enhancer II

10MN Y-S8 Compact Afterburner
Limited Adaptive Invulnerability Field I
Limited Adaptive Invulnerability Field I
Large F-S9 Regolith Compact Shield Extender
Large F-S9 Regolith Compact Shield Extender
Medium Compact Pb-Acid Cap Battery

250mm Prototype Gauss Gun
250mm Prototype Gauss Gun
250mm Prototype Gauss Gun
250mm Prototype Gauss Gun
250mm Prototype Gauss Gun
Drone Link Augmentor I

Medium Core Defense Field Purger I
Medium Core Defense Field Purger I
Medium Core Defense Field Purger I

Hammerhead I x5
Hobgoblin II x5

Antimatter Charge M x40
Lead Charge M x2040
Uranium Charge M x2040

### Other relevant information:

![image](https://user-images.githubusercontent.com/62102583/76521091-6b6c7a80-6464-11ea-8d51-b6d6141d8489.png)

**Comment by DarkFenX** [comment]
This happens because you have no damage pattern selected. I will add code to gray input boxes out in such case.

**Comment by DarkFenX** [comment]
Fixed in 74cd6d48da06a80517e37953349d6104acfb9801. Made it consistent with other editors - now it will prompt you to enter name of new damage pattern when you have none in the editor

**Comment by Lampucera** [comment]
Awesome, thank you for support.
