### ISSUE TITLE
[SOLVED] Error message at SSO login when using Firefox Containers (solution below)

### ISSUE THREAD

**Issue by radub7** [pyfa-org/Pyfa#2148]
I'm trying to add characters to Pyfa: I made a new character, clicked Login with Eve SSO button, the login page at https://login.eveonline.com/oauth/authorize opened and I logged in.
After clicking the Authorize button I get the error in the screenshot embedded below:
![Firefox_Screenshot_2020-03-18T14-14-04 700Z](https://user-images.githubusercontent.com/28403211/76970315-99016a00-6923-11ea-9ec4-7de667dc34f1.png)
I've deleted the .pyfa folder, reinstalled pyfa from scratch, tried different browsers, no dice.
I get this error for about a month now.
I'm using Windows 10 Pro 64bit v.1909.
Anyone knows what the problem might be?

**Comment by blitzmann** [comment]
Hi @radub7 

Can you try again? Seems to be working for me. Just tried with the latest version 2.18.1 and it added my character:

![image](https://user-images.githubusercontent.com/3904767/76983212-664f7580-6913-11ea-9952-bcd45a4abdcb.png)

It's possible that the authentication proxy went down for a short time - I'll have to take a look at the server logs to see if there's anything going on (can't do so at the moment).

**Comment by radub7** [comment]
Solution found! I am using Firefox and Containers, and I placed Eve Online in its own container. Pyfa.io must be added to the same container, also cookies must be enabled.
