### ISSUE TITLE
Attribute overrides do not activate

### ISSUE THREAD

**Issue by wfharris** [pyfa-org/Pyfa#2157]
## Bug Report

Attribute Overrides do not activate when set.

### Expected behavior:

1. Change an attribute using Menu -> Global -> Attribute Overrides and then setting an override.
2. Use module that is overridden in a fit
3. Enable overrides using Global -> Turn Overrides On.
4. The module changes the stats when Overrides are turned On.

### Actual behavior:

Nothing changes when Global -> Turn Overrides On is enabled, or when it's disabled.

### Detailed steps to reproduce:

See above.

I was able to get overrides to enable by doing Fit -> Enable (or Disable) fitting restrictions. This seems to somehow cause the overrides to take effect.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

Any fit using the overridden modules

### Release or development git branch? Please note the release version or commit hash:

pyfa v2.19.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10 (OS Build 18362.720)

### Other relevant information:

Enabling or disabling fitting restrictions seems to cause a 'flush' of the system and causes any overrides to take effect from that point on, so it's a workaround for the time being.

**Comment by DarkFenX** [comment]
Try latest singularity build: https://github.com/pyfa-org/Pyfa/releases/tag/v2.19.1dev1 I believe your issue is solved there. Next tranquility release will have it as well.

**Comment by DarkFenX** [comment]
I will just assume that it is fixed and close it. If the issue still persists on linked build - feel free to reopen.

**Comment by wfharris** [comment]
I can confirm this is fixed in v2.19.1dev1
