### ISSUE TITLE
All Ships Under-fitting Weapons By 1

### ISSUE THREAD

**Issue by Kae96** [pyfa-org/Pyfa#2162]
### Expected behavior: 
Every ship has X amount of turret or launcher slots and so should be able to fit up to X amount of weapons

### Actual behavior: 
Every ship is instead only able to fit X-1 weapons so is always 1 short of it's maximum

### Detailed steps to reproduce: 
Create a new fit for any ship, find the appropriate weapon to fit, rclick and select fill with module. 

### Release or development git branch? Please note the release version or commit hash: 
2.20.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10): 
Win10

**Comment by DarkFenX** [comment]
Confirmed. Will work on the fix and release a hotfix soonish.

**Comment by DarkFenX** [comment]
Fixed by 652ea482232c08d9c9cf6e6b254ad0701102e447
