### ISSUE TITLE
Wrong booster calculation

### ISSUE THREAD

**Issue by FireCulex** [pyfa-org/Pyfa#2178]
It shows 4.96 cycle time in pyfa, in game it shows 4.71

6s - 21.6% Armor Repair Modules  is 4.71

[Oneiros,]

Imperial Navy 800mm Steel Plates
True Sansha Capacitor Power Relay
True Sansha Capacitor Power Relay
Centum C-Type Energized Adaptive Nano Membrane
Centum C-Type Energized Adaptive Nano Membrane

Shadow Serpentis Remote Tracking Computer
Shadow Serpentis Remote Tracking Computer
Shadow Serpentis Remote Tracking Computer
Corelum B-Type 10MN Afterburner

Large Remote Armor Repairer II
Large Remote Armor Repairer II
Large Remote Armor Repairer II
Large Remote Armor Repairer II

Medium Capacitor Control Circuit II
Medium Capacitor Control Circuit II

[Eos,]

Centum A-Type Energized Adaptive Nano Membrane
Centum A-Type Energized EM Membrane
Shadow Serpentis Damage Control
Imperial Navy Drone Damage Amplifier
Centum A-Type Energized Explosive Membrane
Imperial Navy 1600mm Steel Plates

Shadow Serpentis Remote Sensor Booster
Shadow Serpentis Remote Sensor Booster
Shadow Serpentis Remote Sensor Booster
Gistum A-Type 50MN Microwarpdrive

Armor Command Burst II, Armor Energizing Charge
Armor Command Burst II, Rapid Repair Charge
Armor Command Burst II, Armor Reinforcement Charge
Skirmish Command Burst II, Rapid Deployment Charge
Small Tractor Beam I
Auto Targeting System I

Medium Command Processor I
Medium Command Processor I

**Comment by DarkFenX** [comment]
most likely you have armored/FN/IN mindlink in game, which you do not have in pyfa. With it, duration is 4.71 in pyfa

**Comment by FireCulex** [comment]
Correct, I didn't realize I had the wrong slot 10 implant selected. oops.
