### ISSUE TITLE
Toggling mining yield while target resists are enabled will repeatedly concatenate "( Effective )" to the firepower menu label

### ISSUE THREAD

**Issue by elasota** [pyfa-org/Pyfa#2182]
## Bug Report
Toggling mining yield while effective resists are enabled will repeatedly concatenate "( Effective )" to a UI label next to the firepower options menu

### Expected behavior:
"( Effective )" text should only appear once

### Actual behavior:
"( Effective )" text appears multiple times

### Detailed steps to reproduce:
- Start pyfa
- Create a new Rifter fitting
- Add a 200mm AutoCannon I and load it with EMP S
- Expand the "Firepower" panel
- If the Firepower panel is set to mining yield, click the button labeled "Click to toggle mining yield" to put it back in DPS mode
- Click the 3-lined icon across from "Firepower"
- Under "Target Resists", select "Uniform (25%)"
- Click the button in the Firepower panel labeled "Click to toggle mining yield" **twice**
- Notice that there is now an "( Effective )" label next to the 3-lined icon
- Click the "Click to toggle mining yield" button 2 more times
- Notice that the label now reads "( Effective )( Effective )".  This process can be repeated.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Rifter, Rifter fit]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

200mm AutoCannon I
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

EMP S x5000

### Release or development git branch? Please note the release version or commit hash:
Release v2.20.3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by DarkFenX** [comment]
Fixed in 05c2c4176250dc05eabd4c89adcd316f503810c5
