### ISSUE TITLE
Incorrectly calculated dps

### ISSUE THREAD

**Issue by ForThePolis** [pyfa-org/Pyfa#2183]
### Fits involved in EFT format (Edit > To Clipboard > EFT): 
[Machariel, My Machariel]

Damage Control II
Republic Fleet Gyrostabilizer
Republic Fleet Gyrostabilizer
Republic Fleet Gyrostabilizer
Republic Fleet Tracking Enhancer
Republic Fleet Tracking Enhancer

Tracking Computer II
Republic Fleet 100MN Afterburner
Republic Fleet X-Large Shield Booster
Shield Boost Amplifier II
Adaptive Invulnerability Shield Hardener II
Adaptive Invulnerability Shield Hardener II

Republic Fleet 800mm Repeating Cannon, EMP L
Republic Fleet 800mm Repeating Cannon, EMP L
Republic Fleet 800mm Repeating Cannon, EMP L
Republic Fleet 800mm Repeating Cannon, EMP L
Republic Fleet 800mm Repeating Cannon, EMP L
Republic Fleet 800mm Repeating Cannon, EMP L
Republic Fleet 800mm Repeating Cannon, EMP L
Drone Link Augmentor II

Large Projectile Metastasis Adjuster II
Large Projectile Ambit Extension I
Large Projectile Ambit Extension I

Hornet II x5
Vespa II x2
Vespa II x3
Wasp II x2

vs.

[Machariel, My Machariel]

Damage Control II
Republic Fleet Gyrostabilizer
Republic Fleet Gyrostabilizer
Republic Fleet Gyrostabilizer
Republic Fleet Tracking Enhancer
Republic Fleet Tracking Enhancer

Tracking Computer II
Republic Fleet 100MN Afterburner
Republic Fleet X-Large Shield Booster
Shield Boost Amplifier II
Adaptive Invulnerability Shield Hardener II
Adaptive Invulnerability Shield Hardener II

800mm Repeating Cannon II, EMP L
800mm Repeating Cannon II, EMP L
800mm Repeating Cannon II, EMP L
800mm Repeating Cannon II, EMP L
800mm Repeating Cannon II, EMP L
800mm Repeating Cannon II, EMP L
800mm Repeating Cannon II, EMP L
Drone Link Augmentor II

Large Projectile Metastasis Adjuster II
Large Projectile Ambit Extension I
Large Projectile Ambit Extension I

Hornet II x5
Vespa II x2
Vespa II x3
Wasp II x2

**Comment by DarkFenX** [comment]
With all 5 character, 817 dps for the first fit and 862 dps for the second one. I guess the character you used had large projectile specialization on a quite low level.

**Comment by ForThePolis** [comment]
Hey DarkFenX,

That is interesting, I don't get the same numbers.  Even using the "All 5" character I show 838 dps for the first and 885 for the second.  Ignoring the number differences, though, the first fit should be doing more dps even though pyfa is showing it to have lower dps.  The only difference between the two fits are the guns and the republic fleet cannons should do more damage than the tech II Cannons.

**Comment by ForThePolis** [comment]
I'm an idiot. ignore all this.

**Comment by DarkFenX** [comment]
No problem :P
