### ISSUE TITLE
Blocked by SmartScreen

### ISSUE THREAD

**Issue by octocatx** [pyfa-org/Pyfa#2184]
Can the app be digitally signed so that Microsoft Defender and associated security programs whitelists it?

**Comment by blitzmann** [comment]
Duplicate #2043

In short: no. It's pricey to get a cert for signing the executable. The SmartScreen issue is a minor annoyance, but I believe most folks trust pyfa and know to just ignore it.;

pyfa is a free tool and thus hard to get someone to commit to annual payments just for code signing. The risk is mitigated by the fact that pyfa itself is open source, as well as it's build pipelines. So if someone is concerned thay can always evaluate the code itself to make sure it's safe
