### ISSUE TITLE
Electrical Abyssal Weather does not affect resists

### ISSUE THREAD

**Issue by zipy124** [pyfa-org/Pyfa#2185]
## Bug Report
When adding Abyssal weather to your fit, they all correctly subtract resistance except electrical, which should give a penalty to EM resistance, it also does not seem to affect capictor like it should.

### Expected behavior:
Cap recharge decreased aswell as EM resistance

### Actual behavior:
Nothing

**Comment by DarkFenX** [comment]
Cap recharge time is decreased, which effectively increases your cap recharge per second, and that's what I see in pyfa.

Has something changed that it needs to be updated?

**Comment by DarkFenX** [comment]
Closing as invalid. Reopen if there is anything I actually missed.
