### ISSUE TITLE
Auto-Targeting System Locked Targets Bonus Missing

### ISSUE THREAD

**Issue by brightvalley** [pyfa-org/Pyfa#2190]
In version 2.20.3, when adding an auto-targeting system to a fit and turning it on there is no locked targets bonus added to the base locked targets value.

**Comment by DarkFenX** [comment]
Please post full fit. You are probably on 12 targets already which is the cap.

Final targets = min(from skills, from ship). Auto targeting system increases only amount of targets available from ship, and skills are capped at 12 (2 base + 5 from basic skill + 5 from advanced).

**Comment by brightvalley** [comment]
I have two screenshots for you, one without the Auto Targeting System I and the other with it installed and turned on. In both cases the ship shows 5 targets. Am I misreading this?

![auto-targeting system - none](https://user-images.githubusercontent.com/44230719/82443271-d5a62a80-9a66-11ea-866a-7457bfd5ce5a.PNG)
![auto-targeting system - on](https://user-images.githubusercontent.com/44230719/82443273-d5a62a80-9a66-11ea-8312-993179f296d9.PNG)

**Comment by DarkFenX** [comment]
> Please post full fit and **character Targeting and Advanced Targeting skill levels**.

**Comment by brightvalley** [comment]
Target Management 3
Advanced Target Management not injected

[Gnosis,EDENCOM Anti-Triglavian Armor]
Domination Medium Armor Repairer
Energized Adaptive Nano Membrane II
Reactive Armor Hardener
Armor Explosive Hardener II
Energized Adaptive Nano Membrane II
Domination Medium Armor Repairer

10MN Afterburner II
Cap Recharger II
Large Compact Pb-Acid Cap Battery
Cap Recharger II
Large Compact Pb-Acid Cap Battery
Missile Guidance Computer II, Missile Precision Script

'Arbalest' Heavy Missile Launcher, Caldari Navy Nova Heavy Missile
'Arbalest' Heavy Missile Launcher, Caldari Navy Nova Heavy Missile
'Arbalest' Heavy Missile Launcher, Caldari Navy Nova Heavy Missile
'Arbalest' Heavy Missile Launcher, Caldari Navy Nova Heavy Missile
'Arbalest' Heavy Missile Launcher, Caldari Navy Nova Heavy Missile

Medium Nanobot Accelerator II
Medium Ancillary Current Router I
Medium Nanobot Accelerator II


Valkyrie I x5
Warrior I x5


Caldari Navy Nova Heavy Missile x3600
Nanite Repair Paste x200
Mobile Tractor Unit x1

**Comment by DarkFenX** [comment]
Target Management 3 leaves you with target cap of 5, regardless of what ship provides. That's how EVE works. Are you sure that in game you have more than 5 lockable targets?

**Comment by brightvalley** [comment]
I must be misreading this. Thank you.

**Comment by DarkFenX** [comment]
np, it might be non-intuitive sometimes
