### ISSUE TITLE
[Request] Fitting page - change column icons to text

### ISSUE THREAD

**Issue by Luunae** [pyfa-org/Pyfa#2193]
I'm fairly new - have only been playing for about a month and a half and the icons aren't obvious, and I've had to puzzle out the few of them that I know. The rest are just a spot of confusion.

Using text rather than icons would be a great clarity improvement.

Alternatively, alt/title text when hovered over it so you can see the name of the thing?

**Comment by DarkFenX** [comment]
You can hover over items themselves to see explanation tooltip. Sometimes it makes more sense since it provides more detailed explanation - one column can contain various entries which are different in nature (mostly it concerns "Misc" column).

Is that not sufficient?

**Comment by Luunae** [comment]
Ah, I did not know that was a thing - it wasn't apparent or intuitive.

Usually when there's hover-over notes on an item in a grid (Excel, etc.) there's an indication of such. A small triangle in the corner of the cell, or similar. That's not really appropriate when it's hover-over for almost everything though... Eh..

**Comment by blitzmann** [comment]
> So IMHO it is a little counterintuitive to hover over e.g. column values to get the information. 

Indeed, the grid column headers don't have tooltips. I think I tried looking into it at some point and it was not something that was feasible to do. So the cell itself gets the tooltip instead.

> if you look at the "Recharge rates"

The recharge rate panel does indeed have tooltips that show you what is what, if you hover over the right thing ;)

![image](https://user-images.githubusercontent.com/3904767/137246284-6757fb0c-594b-41a4-8f5a-9fbe5ca236ef.png)
![image](https://user-images.githubusercontent.com/3904767/137246337-83b5d3f6-36db-4d0f-a0fb-032812cefab5.png)
![image](https://user-images.githubusercontent.com/3904767/137246351-009c5909-26ca-4896-9cd6-f3d4e6eb8938.png)

Damn near everything has a tooltip associated with it somehow, so it's not feasible to have any other indicator. I think this might just be a case of getting used to how pyfa is laid out and how / what information is presented, just as with any GUI.

I'm going to close this issue as a `wontfix`, but if you ever notice any information that could be included in a tooltip lacking, please open a specific issue for that one (or submit a PR!)
