### ISSUE TITLE
Feature request: currently open fits as target resist profiles

### ISSUE THREAD

**Issue by luiscastilho** [pyfa-org/Pyfa#2194]
It would be nice to have currently open fits as options in the Target Resists menu. This way it would be possible to know your DPS against an specific fit.

The resists could be calculated as the weighted mean of the target fit resistances, using shield/armor/hull HP as the weight maybe. Max speed and signature radius could be taken from the target fit as well.

**Comment by DarkFenX** [comment]
The functionality you are looking for is included in graphs, with "ignore target resistances" option off.

There is no way to fit such a rich functionality on simple DPS panel - even just resist mode selection, let alone target signature, movement vectors etc. Graph panel is the right place for all that.

**Comment by luiscastilho** [comment]
Makes sense. Thanks!
