### ISSUE TITLE
Can't activate cargo scanner

### ISSUE THREAD

**Issue by lmicra** [pyfa-org/Pyfa#2195]
## Bug Report

Can't activate cargo scanner.

### Expected behavior:

Cargo scanner active, when clicking module.

### Actual behavior:

Cargo scanner offline.

### Detailed steps to reproduce:

Add cargo scanner to fit.
Click circle to activate.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

```
[Heron, Heron]
Cargo Scanner I
```

### Release or development git branch? Please note the release version or commit hash:

Release 2.21.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10

**Comment by lmicra** [comment]
Same behavior with the remaining scanners:

[Heron, Heron]
Cargo Scanner I
Survey Scanner I
Ship Scanner I

**Comment by DarkFenX** [comment]
That's kinda intentional since they are not auto-repeating modules and for some of them it doesn't make sense to run more than 1 time (besides ship scanner). I can easily fix it, though.

**Comment by DarkFenX** [comment]
Fixed in 181e1e1e30d95770c703da9bbf475b3128034c54

**Comment by lmicra** [comment]
Thanks for the quick fix. My OCD monster is now much calmer.
