### ISSUE TITLE
[Feature Request] Strip loaded charges when exporting to eve

### ISSUE THREAD

**Issue by esheyw** [pyfa-org/Pyfa#2196]
Could we get a checkbox for this? I like having cargo as full as is possible while leaving room for rigs, for ease of multifit, but I'd also like to use the fits as command or for graphs etc, and would like to avoid doing the extra math of cargo minus fitted charges. Although, I suppose, alternatively if its easier, a checkbox for 'cargo counts as including fitted charges' for the bar would work too, but just stripping on export seems cleaner to me.

**Comment by DarkFenX** [comment]
True. I always have had issues with this too actually. Will try to change that for next release.

**Comment by DarkFenX** [comment]
Done in b558ae381017234d9fe8fef85bdfd1fb5058a4e2
