### ISSUE TITLE
So could you please provide x86 version for users?

### ISSUE THREAD

**Issue by vivian-oier** [pyfa-org/Pyfa#2207]
It **NOT** a bug report.

So could you please provide x86 version for users?The install program can only run on x64 platform. In fact it **may** can run as well as both platform.

**Comment by vivian-oier** [comment]
You could ignore thisk kinds of report. Users can deal this kind of problems by **themselves** if they need to run pyfa on x86 platform. It must be a problem if the installer gets flagged by multiple AV monitors.

**Comment by KagurazakaNyaa** [comment]
https://www.eveonline.com/article/q6b32b/32-bit-client-deprecation

I don’t think that in the case where the game itself does not support 32-bit, third-party tools still need to support 32-bit.

**Comment by DarkFenX** [comment]
@vivian-oier yet users choose to cry on reddit creating negative reputation for project, raising concerns about credibility etc. I am sorry but unless there is a reliable way to remove those false positives, we won't provide 32 bit builds.

**Comment by blitzmann** [comment]
Agreed on all points. If eve doesn't support 32 bit, I don't think we should.

If there's a need for pyfa on 32-bit machines, it's relatively easy to get the source and run it through the python interpreter. I would maybe say we could go as far as adding an unofficial build on appveyor / travis for 32bit machines, but really I'm not sure how many folks would be interested and doubt it's worth the time

**Comment by vivian-oier** [comment]
It doen not a matter. I will build it myself. Thanks.
