### ISSUE TITLE
TypeError when exporting to ESI immediately after importing fit from clipboard

### ISSUE THREAD

**Issue by aj-m** [pyfa-org/Pyfa#2209]
### Expected behavior:
I have a fit in EFT format that I paste into pyfa. I immediately export the fit to ESI, the fit exports correctly.

### Actual behavior:
After pasting the fit and selecting the character to export to, I get an error message with a traceback and the fit fails to export.

### Detailed steps to reproduce:
Paste a new fit into pyfa. Without changing tabs, bring up the export to ESI window via keyboard shortcut or menu. Export to any ESI character. Receive stack trace.
```
Traceback (most recent call last):
  File "gui\esiFittings.py", line 289, in exportFitting
  File "service\port\port.py", line 318, in exportESI
  File "service\port\esi.py", line 75, in exportESI
TypeError: object of type 'NoneType' has no len()
```
 * Export Loaded Charges can be on or off, it doesn't seem to affect whether or not the bug triggers.
 * Switching tabs to another fit and back seems to be a workaround, as the fit will export successfully after doing that.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
```
[Stork, Stork: Ricardomoras]

Damage Control II
Co-Processor II

Republic Fleet Medium Shield Extender
Republic Fleet Medium Shield Extender
Micro Jump Field Generator
Multispectrum Shield Hardener II
1MN Y-S8 Compact Afterburner
EM Shield Amplifier II

Shield Command Burst II, Shield Extension Charge
Shield Command Burst II, Shield Harmonizing Charge
Arbalest Compact Light Missile Launcher, Caldari Navy Scourge Light Missile
Arbalest Compact Light Missile Launcher, Caldari Navy Scourge Light Missile
[Empty High slot]
[Empty High slot]

Small Command Processor I
Small Core Defense Field Extender II


Caldari Navy Scourge Light Missile x1000
Nanite Repair Paste x100
Active Shielding Charge x600
Shield Extension Charge x600
Shield Harmonizing Charge x600
Mobile Cynosural Inhibitor x1
```

### Release or development git branch? Please note the release version or commit hash:
Release 2.22.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows-7-6.1.7601-SP1

### Other relevant information:
I added an alt to my ESI characters a few minutes before triggering the bug.

**Comment by blitzmann** [comment]
Can confirm, will take a look
