### ISSUE TITLE
DroneOrder crash when fit is opened

### ISSUE THREAD

**Issue by kanyda** [pyfa-org/Pyfa#2224]
Opening a muninn fit and I get this error:

pyfa v2.22.1
EVE Data Version: 1751741 (2020-06-18 06:35:35)

OS version: Windows-10-10.0.18362-SP0
Python version: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.17
Logbook version: 1.5.3
Requests version: 2.24.0
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "gui\builtinAdditionPanes\projectedView.py", line 202, in fitChanged
  File "gui\builtinAdditionPanes\projectedView.py", line 218, in refreshContents
  File "gui\builtinAdditionPanes\projectedView.py", line 165, in droneSort
AttributeError: type object 'DroneView' has no attribute 'DRONE_ORDER'

This is the fit: 

[Muninn, 2018 standard muninn]

Assault Damage Control II
Gyrostabilizer II
Gyrostabilizer II
Power Diagnostic System II
Tracking Enhancer II
Tracking Enhancer II

50MN Y-T8 Compact Microwarpdrive
Large Shield Extender II
Multispectrum Shield Hardener II
Large Shield Extender II

720mm Howitzer Artillery II, Tremor M
720mm Howitzer Artillery II, Arch Angel Proton M
720mm Howitzer Artillery II, Arch Angel Titanium Sabot M
720mm Howitzer Artillery II, Arch Angel EMP M
720mm Howitzer Artillery II, Quake M

Medium Core Defense Field Extender II
Medium Core Defense Field Extender I

**Comment by kanyda** [comment]
Copying the fit and pasting it I don't get the same crash. However the fit that causes the crash has command links and applied items (probably ships like vigils). https://i.imgur.com/EJ4GX9F.png

**Comment by blitzmann** [comment]
Do you always get the error when you open it on your pyfa?

If so, can you email me your `saveddata.db` file to `holmes.ryan.90+pyfa@gmail.com`?

**Comment by DarkFenX** [comment]
It has been an issue with drones in projected tab. Has been resolved in 2.24.0.
