### ISSUE TITLE
Defender Missile is not subject to Ballistic Control bonus

### ISSUE THREAD

**Issue by awwaawwa** [pyfa-org/Pyfa#2229]
## Bug Report
Defender Missile is not subject to Ballistic Control bonus

### Expected behavior:
The damage current value is higher than the base value
### Actual behavior:
![image](https://user-images.githubusercontent.com/8493196/87541072-3fdbf400-c6d3-11ea-969e-07dd94b9c2dc.png)
The damage current value is equal to the base value high

### Detailed steps to reproduce:
Sabre->Add Defender Launcher I->Set charge Defender Missile I-> Add Ballistic Control System->Check the Charge Stats

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Sabre, Sabre fit]

Ballistic Control System II
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Defender Launcher I, Defender Missile I
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
Release v2.23.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by DarkFenX** [comment]
Is it subject to BCS bonus in game?

**Comment by Candyguitar** [comment]
I've just checked and found that the BCS bonus does apply in-game:
![ENk0XdCNki](https://user-images.githubusercontent.com/66836510/87567973-d0f3a080-c6bc-11ea-9de4-61edb37e4449.jpg)

**Comment by DarkFenX** [comment]
Fixed in 52063beea96839d72bca9dd78604a27a1f7c9622
