### ISSUE TITLE
'Upwell Standard Outpost Rig' not applying bonuses

### ISSUE THREAD

**Issue by JOS654** [pyfa-org/Pyfa#2255]
# Expected behavior:
'Upwell Standard Outpost Rig' not applying bonuses

### Actual behavior:
Seems like no bonus its applied, pds range shows 3km when in reality its ~29ish km

### Fits involved in EFT format (Edit > To Clipboard > EFT):
['Marginis' Fortizar, AAAAA]

Standup Ballistic Control System I
Standup Ballistic Control System I
Standup Layered Armor Plating I
Standup Layered Armor Plating I
Standup Layered Armor Plating I

Standup Cap Battery I
Standup ECM Jammer Burst Projector
Standup Focused Warp Disruptor II
Standup Stasis Webifier I
Standup Target Painter II

Standup Guided Bomb Launcher I, Standup Light Guided Bomb
Standup Multirole Missile Launcher II, Standup Cruise Missile
Standup Multirole Missile Launcher II, Standup Cruise Missile
Standup Multirole Missile Launcher II, Standup Cruise Missile
Standup Point Defense Battery II
Standup XL Energy Neutralizer I
Standup XL Energy Neutralizer I

Upwell Standard Outpost Rig
[Empty Rig slot]
[Empty Rig slot]

Standup Capital Shipyard I
Standup Cloning Center I
Standup Invention Lab I
Standup Manufacturing Plant I
Standup Market Hub I
Standup Reprocessing Facility I
Standup Research Lab I
[Empty Service slot]

For reference in game fitting window:
https://i.imgur.com/syBPkLs.png

**Comment by DarkFenX** [comment]
Indeed, its effect is not implemented. Also, there is an issue with importing ships which contain `'` in their names. Fixed the import issue, will add effect a bit later.

**Comment by DarkFenX** [comment]
Done in ccb395d592242b39e6d7c7e475b80e2dcc43c3d7
