### ISSUE TITLE
where is the language setting in newest pyfa if I may ask?

### ISSUE THREAD

**Issue by jimmcnulty998** [pyfa-org/Pyfa#2259]
can't find language setting on newest PYFA

**Comment by blitzmann** [comment]
The translations? It's not in the normal pyfa releases at the moment, as it's still in review: #2202

The feature is ready to be merged in I think, but there were a few things that we needed to double check and sign off on. For the past week I've been heads down on another project and haven't put as much attention on this as I should. We'll put a focus on it this week and try to get it merged in by this weekend. :)
