### ISSUE TITLE
'Structure Electronic Systems' skill bonus not applied to Standup Variable Spectrum ECM modules

### ISSUE THREAD

**Issue by PaladinOne** [pyfa-org/Pyfa#2263]
The skill 'Structure Electronic Systems' does not reduce the capacitor consumption of an Astrahus Standup Variable Spectrum ECM modules.
The in-game fitting simulator shows that the skill does reduce the module's capacitor consumption.

Sample fit:
```
[Astrahus, Astrahus fit]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

Standup Variable Spectrum ECM I, Standup Radar ECM Script
Standup Variable Spectrum ECM II, Standup Radar ECM Script
Dread Guristas Standup Variable Spectrum ECM, Standup Radar ECM Script
Standup Focused Warp Disruptor I, Standup Focused Warp Scrambling Script

Standup Heavy Energy Neutralizer I
Standup Heavy Energy Neutralizer I
Standup Heavy Energy Neutralizer I
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

[Empty Service slot]
[Empty Service slot]
[Empty Service slot]
```
The Standup Focused Warp Disruptor has its Capacitor consumption reduced (which is correct), however the ECMs do not.

Version: Release 2.27.0
OS: Windows 10

**Comment by DarkFenX** [comment]
Indeed. Seems like their group was renamed at some point. Fixed in 70969cc9fb0e34325c7818bdf30b30d69f9f0b9a
