### ISSUE TITLE
New NPC's are coming to the abyss and will need damage and target profiles.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#2265]
Internal damage and target profiles need to be added for angel, concord and sansha npc in the abyss (sisi) and update existing profiles as some npcs have been added to those groups.

**Comment by Neugeniko** [comment]
How do we add new internal target & damage profiles, just a new index at the end?

**Comment by Neugeniko** [comment]
If I add damage profiles to the end, they are not sorted alphabetically. Can you sort them when you generate the menus?

**Comment by Neugeniko** [comment]
I think we have talked about damage profiles menu sorting before. It nice to have em in order of range for ammo types (sorted by index) and by name for npcs, so there is no easy solution.

**Comment by Neugeniko** [comment]
#2268 This pull request has all the required changes as of the live tq patch.

**Comment by Neugeniko** [comment]
@DarkFenX How are things going with the rest of the patches changes?

**Comment by Neugeniko** [comment]
Reissued a pull request, #2273, taking into account changes to concord npcs.

**Comment by DarkFenX** [comment]
Thank you very much.

**Comment by DarkFenX** [comment]
@Neugeniko regarding sorting, those IDs are not stored anywhere between sessions, so you can adjust them at will. How are they used in sorting - unsure, will check a bit later.

**Comment by DarkFenX** [comment]
Target profiles are sorted by full name, but built-in damage patterns are sorted by the way they are defined. Maybe not the best idea to define sort order on the backend, but it allowed me to sort them the way i like. I changed it to be alphabetical in 39b08baff053df9bfef98fcf2c807f1f57c6183a

**Comment by Neugeniko** [comment]
Thanks for accepting the pull request. I had to reissue it a few times as it is early and ccp are still adjusting these npcs.
