### ISSUE TITLE
pyfa won't install when installer is named "pyfa"

### ISSUE THREAD

**Issue by bluninja1234** [pyfa-org/Pyfa#2272]
### Expected behavior:
Pyfa installs normally

### Actual behavior:
Pyfa displays a message saying "please close pyfa before continuing"

### Detailed steps to reproduce:
Name the installer "pyfa.exe"

### Release or development git branch? Please note the release version or commit hash:
2.28.2

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by blitzmann** [comment]
Huh. Well, yeah, that's a bit annoying.

I changed the text to the following for clarification: 
>Please close pyfa before continuing. When closed, please go back to the previous step and continue. If you have named this installer pyfa.exe, please rename it and restart installation

I think actually trying to fix it is more trouble than it's worth tbh

**Comment by bluninja1234** [comment]
Yeah, I wouldn't worry about it either. I was just annoyed that I had to delete the old installer and download the new installer every time.
