### ISSUE TITLE
Add new target and damage profiles for invasion drifters, rogue drones and sleepers.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#2281]
New content, Triglavian space, was added recently with new enemies. We need profiles for them.

**Comment by DarkFenX** [comment]
Do older profiles stay?
What about old system-wide effects, under "destructible beacons", are they still actual or can be removed (besides the triglavian one)?

**Comment by Neugeniko** [comment]
System wide effects are still used I believe, i will double check a edencom
effect to be sure that is still in.
