### ISSUE TITLE
Drugs Missing from 2.31.0

### ISSUE THREAD

**Issue by HindenPeter** [pyfa-org/Pyfa#2288]
## Bug Report
No Boosters are included in the latest Pyfa build apart from "Serenity November Season Pass" and "Nanoheuristic Clone Mapper"

### Expected behavior:
Boosters should be available under the "Booster" list in the Market tab

### Actual behavior:
They aren't there

### Detailed steps to reproduce:
I don't really think there are any steps apart from opening Pyfa

### Fits involved in EFT format (Edit > To Clipboard > EFT):
Any and all

### Release or development git branch? Please note the release version or commit hash:
Release, v2.31.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win 10

### Other relevant information:
N/A

**Comment by MadameSolette** [comment]
If i right click on a booster in the cargo tab and search market group it will come this error:

pyfa v2.31.0
EVE Data Version: 1842315 (2020-11-10 09:18:18)

OS version: Windows-10-10.0.19041-SP0
Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.20
Logbook version: 1.5.3
Requests version: 2.24.0
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "gui\contextMenu.py", line 174, in handler
  File "gui\contextMenu.py", line 307, in _baseActivate
  File "gui\builtinContextMenus\itemMarketJump.py", line 59, in activate
  File "gui\marketBrowser.py", line 105, in jump
  File "gui\builtinMarketBrowser\marketTree.py", line 101, in jump
wx._core.wxAssertionError: C++ assertion "item.IsOk()" failed at ..\..\src\msw\treectrl.cpp(1032) in wxTreeCtrl::GetItemParam(): invalid tree item

**Comment by OlekSkilgannon** [comment]
I can also confirm the above two issues, boosters are not in the market menu but you are able to manually search for them if you can remember the names. I also get the above error when right clicking on a booster after searching and selecting the search market group option.

**Comment by ivveh** [comment]
Can confirm this issue mentioned above. Small image to illustrate the initial problem (of not being able to find them in categories unless you do a specific search). 
![image](https://user-images.githubusercontent.com/3943915/99189783-40f55e80-2763-11eb-8726-d58c1894f05f.png)

**Comment by DarkFenX** [comment]
Issue is that CCP puts either market groups, or items in any given market group. This one had both.

Has been fixed in 10613c9070bca2cfe4a86a6d8a8300501f0ed7be, will be available in next release. Now we prefer showing sub-groups over items.
