### ISSUE TITLE
Error when projecting ECM ship onto a fit

### ISSUE THREAD

**Issue by jonwessels** [pyfa-org/Pyfa#2289]
### **Bug Report**

pyfa v2.31.0
EVE Data Version: 1842315 (2020-11-10 10:18:18)

OS version: Windows-7-6.1.7601-SP1
Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.20
Logbook version: 1.5.3
Requests version: 2.24.0
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "gui\statsPane.py", line 79, in fitChanged
  File "gui\builtinStatsViews\targetingMiscViewMinimal.py", line 218, in refreshPanel
AttributeError: 'str' object has no attribute 'foramt'

### **Steps to reproduce**

Issue occurs when projecting a fit which has active ECM modules onto another fit. Occurs with any ship with ECM module, and with all ECM modules from what I could tell.

**Comment by DarkFenX** [comment]
Has already been fixed in 2696b480faf74151c1bd1a9c7b9e35a2605c4ce4, will be available in next release
