### ISSUE TITLE
Mining Foreman Burst - Mining Equipment Preservation Charge bonus not applying to Crystals

### ISSUE THREAD

**Issue by PaladinOne** [pyfa-org/Pyfa#2290]
## Bug Report
Modulated Strip Miner IIs, equipped with Mining Crystals, on a ship affected by a Mining Foreman Burst with the Mining Equipment Preservation Charge, are not affected by the Burst.

### Expected behavior:
Mining Crystals used by a ship affected by a Mining Equipment Preservation Charge command burst should have their volatility values decreased, and thus their estimated lifespans increased

### Actual behavior:
Neither Mining Crystals nor Strip Miners are Affected by the Equipment Preservation Charge, and thus volatility and lifespans are unaffected.

### Detailed steps to reproduce:
Using the following sample Covetor fit, with the following sample Rorqual fit applied under Command, check the effects lists of the Strip Miners and Mining Crystals with the Command-applied Rorqual enabled and disabled. Notice the missing effect, and the unchanged Volatility values.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
```
[Covetor, T2 crystals]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]

Modulated Strip Miner II, Common Moon Ore Mining Crystal I
Modulated Strip Miner II, Common Moon Ore Mining Crystal II

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]
```

```
[Rorqual, ore]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Industrial Core II
Mining Foreman Burst II, Mining Laser Optimization Charge
Mining Foreman Burst II, Mining Laser Field Enhancement Charge
Mining Foreman Burst II, Mining Equipment Preservation Charge
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]


Mining Foreman Mindlink
```
### Release or development git branch? Please note the release version or commit hash:
Release v2.30.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by DarkFenX** [comment]
Fixed in 4160b0838855fee16b5dd5cf083c28b20e5015b0
