### ISSUE TITLE
Jargon: Searching market for 'HAM' does not return Heavy Assault Missile Launchers

### ISSUE THREAD

**Issue by PaladinOne** [pyfa-org/Pyfa#2291]
## Bug Report
Searching the market for 'HAM' returns all types of Heavy Assault Missiles, Hammerhead drones, and Heavy Assault Missile implants, but does not return Heavy Assault Missile _Launchers_.

### Expected behavior:
Searching for 'HAM' should return Heavy Assault Missile Launchers, ideally at the top of the results list

### Release or development git branch? Please note the release version or commit hash:
Release 2.30.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by DarkFenX** [comment]
`HAM` returns ammo, `HAML` returns launchers. We could return both for HAM, but wouldn't it be too many search results?

Regarding sorting - i think it needs quite alot of code modifications, at the moment it is just DB query which takes jargon into consideration, then showing results with default sorting order

**Comment by PaladinOne** [comment]
I read through the jargon `defaults.yaml` after submitting this, and I see the `HAM `vs `HAML `distinction. `HAML `is consistent with the jargon of other launchers, but `HAM `always felt like the more common thing to search for (and thus felt unintuitive when it didn't give the launchers).

There's currently 36 items returned by a `HAM` search (24 missiles, 6 drones, 6 implants), and 13 items returned by `HAML`. Increasing the `HAM `return count to 49 doesn't immediately feel like too many returned results, and it resolves this what-feels-like-oddity. So I think I would prefer having `HAM `return both.

As for the sorting, that's just kind of an "in an ideal world" thing, and it doesn't matter too much.

**Comment by DarkFenX** [comment]
Changed in c29d567255ba79bdd29ba9fa664ed8d6c0277506. I decided to implement it since it appears pyfa puts launchers after missiles anyway for queries like `HAM`.
