### ISSUE TITLE
Regression: PYFA no longer has the new Abyssal damage profiles

### ISSUE THREAD

**Issue by Iwilsonp** [pyfa-org/Pyfa#2293]
## Bug Report
When Abyssal Deadspace was updated with the new spawns PYFA included the new NPC damage distributions for CONCORD, Angel Cartel, etc. Those distributions vanished in v 2.31.0.

### Expected behavior:
Here are the NPC damage profiles available in v2.30.0:
![pyfa_damages_v2 30 0](https://user-images.githubusercontent.com/16428760/100296196-972f8200-2f59-11eb-8913-dd94cf06df04.png)

### Actual behavior:
Here are the NPC damage profiles available in v2.31.0 and v2.32.0:
![pyfa_damages_v2 32 0](https://user-images.githubusercontent.com/16428760/100296195-9696eb80-2f59-11eb-9aae-15d18fa3f5a4.png)

### Detailed steps to reproduce:
1. Upgrade PYFA to >=v2.31.0
2. Distributions have changed to the old options
3. Downgrade PYFA to v2.30.0
4. New damage distributions are back.

### Operating system and version:
This was seen under Windows 10 using the .exe installer.

**Comment by DarkFenX** [comment]
Good catch, fixed in 031a3c2d3e7b532f054790457e5f879ac9694ce2
