### ISSUE TITLE
Incorrect name for Projected > Abyssal Weather > Localized, Caustic vs Tachyon Cloud

### ISSUE THREAD

**Issue by PaladinOne** [pyfa-org/Pyfa#2296]
In the Projected tab, the Abyssal Weather > Localized cloud options are listed as Bioluminescent, Caustic, and Filament. Caustic Clouds were removed in the Depths of the Abyss update in September, and replaced with Tachyon Clouds (which increase flight speed and reduce inertia.)
The effects of these clouds were updated correctly, however the names were not changed.

### Release or development git branch? Please note the release version or commit hash:
Release 2.32.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by DarkFenX** [comment]
Issue is that we're using internal names, and internal name of those items is still "Caustic". I guess i will have to adjust that.

**Comment by DarkFenX** [comment]
Fixed in 008b6a887d47834b568c72e06421db92c957530d and e85b618cbc3cb867bbe9526a2aed666cd82fecb5
