### ISSUE TITLE
Pyfa doesn't start after upgrading python 3.9.0. - error report pasted below

### ISSUE THREAD

**Issue by ErwinMadelung** [pyfa-org/Pyfa#2298]
## Bug Report
Pyfa doesn't start but gives error report:

> pyfa v2.32.0
> EVE Data Version: 1852074 (2020-11-24 09:28:02)
> 
> OS version: Linux-5.9.11-arch2-1-x86_64-with-glibc2.32
> Python version: 3.9.0 (default, Oct  7 2020, 23:09:01) 
> [GCC 10.2.0]
> wxPython version: 4.0.7.post2 (wxWidgets 3.0.5)
> SQLAlchemy version: 1.3.20
> Logbook version: 1.5.3
> Requests version: 2.25.0
> Dateutil version: 2.8.1
> 
> ####################
> 
> Traceback (most recent call last):
>   File "/usr/share/pyfa/pyfa.py", line 148, in <module>
>     from gui.mainFrame import MainFrame
>   File "/usr/share/pyfa/gui/mainFrame.py", line 47, in <module>
>     from gui.characterEditor import CharacterEditor
>   File "/usr/share/pyfa/gui/characterEditor.py", line 23, in <module>
>     import roman
> ModuleNotFoundError: No module named 'roman'

### Expected behavior:

That it starts ;)

### Actual behavior:

error report above

### Detailed steps to reproduce:

I just upgraded to python 3.9.0 and also many python modules got an upgrade. So I kinda suspect that it's due to one of those upgrades. But I'm too lazy to roll them back.

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

arch linux btw (as it says in the copy paste above)

**Comment by DarkFenX** [comment]
You are correct, your dependencies do not migrate to new version, if you have installed them via pip. You have to reinstall them from scratch.
