### ISSUE TITLE
Fit works in pyfa but not in-game

### ISSUE THREAD

**Issue by TarkisEVE** [pyfa-org/Pyfa#2299]
### Fits involved in EFT format (Edit > To Clipboard > EFT):

[Tornado, ESS 10mn]

Gyrostabilizer II
Gyrostabilizer II
Gyrostabilizer II
Reactor Control Unit II

10MN Afterburner II
Large Shield Extender II
Large Azeotropic Restrained Shield Extender
Tracking Computer II, Optimal Range Script
Tracking Computer II, Optimal Range Script

1400mm Howitzer Artillery II, Republic Fleet EMP L
1400mm Howitzer Artillery II, Republic Fleet EMP L
1400mm Howitzer Artillery II, Republic Fleet EMP L
1400mm Howitzer Artillery II, Republic Fleet EMP L
1400mm Howitzer Artillery II, Republic Fleet EMP L
1400mm Howitzer Artillery II, Republic Fleet EMP L
1400mm Howitzer Artillery II, Republic Fleet EMP L
1400mm Howitzer Artillery II, Republic Fleet EMP L

Medium Ancillary Current Router I
Medium Ionic Field Projector II
Medium EM Shield Reinforcer II

Synth Drop Booster
Agency 'Pyrolancea' DB3 Dose I

Quake L x800
Nanite Repair Paste x200
Republic Fleet EMP L x800
Republic Fleet Fusion L x800
Republic Fleet Phased Plasma L x800

### Release or development git branch? Please note the release version or commit hash:

v2.32.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10 64bit

**Comment by DarkFenX** [comment]
Please link skills of your characters on https://eveskillboard.com/. I suspect one of skills is less than perfect (weapon upgrades, AWU, power grid upgrades, shield upgrades, or something similar).

**Comment by TarkisEVE** [comment]
eveskillboard (perfect fitting skills including riggings): https://eveskillboard.com/pilot/Tarkis

error message: "To bring 1400mm Howitzer Artillery II online requires 17.63 cpu units, but only 17.59 of the 427.50 units that your computer produces are still available."

picture of fit and error: https://i.imgur.com/xmV59yO.png

**Comment by DarkFenX** [comment]
Ok, this seems to be another manifestation of #1962. CPU need of every gun is 17.625 before rounding to 2 digits. EVE rounds it up, we round it down. I have to add that EVE rounds it up only in this specific case, in other cases it can round it down. It is impossible to fix it properly, refer to linked ticket for further info. It is a very rare case, but it may happen.
