### ISSUE TITLE
Error when deleting fit from EVE

### ISSUE THREAD

**Issue by daniel-s** [pyfa-org/Pyfa#2308]
## Bug Report

When trying to delete a fitting from the "Browse EVE Fittings" window I get a crash report rather than the fitting being deleted.

### Expected behavior:

That the fitting be deleted from my toon's list of fittings in EVE.

### Actual behavior:

Crash report

### Detailed steps to reproduce:

Fit --> Browse ESI fittings --> Fetch fits --> Select fitting --> Delete from EVE

### Fits involved in EFT format (Edit > To Clipboard > EFT):

[Probe, Probe]

Navy Micro Auxiliary Power Core
Damage Control II
Ballistic Control System II

Warp Scrambler II
Republic Fleet Medium Shield Extender
1MN Monopropellant Enduring Afterburner
5MN Y-T8 Compact Microwarpdrive

Rocket Launcher II
Rocket Launcher II
125mm Gatling AutoCannon II

Small Ancillary Current Router II
Small EM Shield Reinforcer II
Small Core Defense Field Extender II

Acolyte II x3
Hobgoblin II x4

Barrage S x472
Inferno Javelin Rocket x400
Inferno Rage Rocket x750
Mjolnir Javelin Rocket x400
Mjolnir Rage Rocket x786
Nova Rage Rocket x474
Scourge Rage Rocket x600
Caldari Navy Scourge Light Missile x396
Inferno Light Missile x482
Nanite Repair Paste x32
Republic Fleet Carbonized Lead S x877
Caldari Navy Nova Rocket x152

### Release or development git branch? Please note the release version or commit hash:

Release

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 8.1

### Other relevant information:

The crash report:

pyfa v2.33.0
EVE Data Version: 1860847 (2020-12-08 19:34:44)

OS version: Windows-8.1-6.3.9600-SP0
Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.20
Logbook version: 1.5.3
Requests version: 2.25.0
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "gui\esiFittings.py", line 159, in deleteFitting
IndexError: tuple index out of range

**Comment by fudgewaffle** [comment]
I also receive this error exactly every time I try to delete from EVE. No matter the fit the error is the same.

**Comment by zhaoweny** [comment]
It seems the structure of esi fitting has changed. Paging @DarkFenX and @blitzmann to look into this.

**Comment by lenninscjay** [comment]
@zhaoweny @DarkFenX @blitzmann, requesting this feature be repaired also please (affects deleting all ESI fittings as well - although that option doesn't provide an error code and fails silently.) As far as I know, pyfa is the only utility to delete all fittings and start from scratch. There is a python script by Hirmuolio that is similarly outdated. https://github.com/Hirmuolio/eve-fit-deleter/blob/master/README.md

**Comment by lenninscjay** [comment]
also paging @jrdn as this affects the 'delete all' functionality (which I very much appreciate). I've trying to understand the API and troubleshoot on my own local copy but haven't had success yet.

**Comment by DarkFenX** [comment]
Hey sorry for being inactive for so long. I believe it broke with the internationalization update. Should be fixed now.
