### ISSUE TITLE
Enhancement: Graphs DPS with Reload Time

### ISSUE THREAD

**Issue by SMCJB** [pyfa-org/Pyfa#2320]
If you graph distance(x) vs dps(y) the dps currently ignores missile reload time. Is there a way we could have dps factoring in missile reload time as an option like we do on the fittings page?

**Comment by DarkFenX** [comment]
There is. Just turn it on a fit (RMB DPS panel - factor in reload time) and it will be included in graphs.

Any kind of graph over time ignores that setting, though, and always takes reload in consideration:

![image](https://user-images.githubusercontent.com/275209/112455179-886fa500-8d6a-11eb-85b0-6a4e91fe3c39.png)

**Comment by DarkFenX** [comment]
Reopen if you are not happy with how it is implemented, but since there is possibility to do that, I consider your question answered.
