### ISSUE TITLE
Missing stacking penalties on overheated artillery with bastion module

### ISSUE THREAD

**Issue by Hirmuolio** [pyfa-org/Pyfa#2328]
## Bug Report

Overheated artillery on marauder with bastion module have wrong rate of fire.

### Expected behavior:

Overheat ROF bonus is stacking penalized with bastion module ROF bonus.

### Actual behavior:

Overheat ROF bonus is not stacking penalized with bastion module ROF bonus.

### Detailed steps to reproduce:

Fit Vargur with artillery and bastion module. Overheat the guns.

With my skills and the fit below Pyfa thinks the artillery cycle time is 12.3 seconds but ingame fit will have cycle time of 12.57 seconds.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

```
[Vargur, Vargur]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

1400mm Howitzer Artillery II, Quake L
1400mm Howitzer Artillery II, Quake L
1400mm Howitzer Artillery II, Quake L
1400mm Howitzer Artillery II, Quake L
Bastion Module I
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
```

### Release or development git branch? Please note the release version or commit hash:

Release 2.34.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10.

**Comment by DarkFenX** [comment]
Fixed in 241c744d405f5c376a4e02aa93e986b4602ab9e8
