### ISSUE TITLE
Bastion bonus to missile velocity calculated incorrectly

### ISSUE THREAD

**Issue by Lithorex** [pyfa-org/Pyfa#2330]
PYFA:

![golembug](https://user-images.githubusercontent.com/81427918/112650119-5c782080-8e4b-11eb-89e5-a403a60b4814.PNG)

Ingame:

![golemingame](https://user-images.githubusercontent.com/81427918/112649458-c0e6b000-8e4a-11eb-93b9-7858ce37a520.png)

PYFA calaculates a missile velocity about 550m/s above the ingame value, resulting in the program displaying a missile range ~9 kilometres higher than the true 97.7km range ingame.

If bastion is inactive PYFA displays a velocity stat equal to that ingame, meaning that the issue must lie somewhere in how PYFA calaculates the Bastion Module's bonus.

**Comment by DarkFenX** [comment]
Fixed in ace00d495ac991c479c048eda280465076b0e268
