### ISSUE TITLE
Target Spectrum Breaker still not updated

### ISSUE THREAD

**Issue by ZaleMandrapilias** [pyfa-org/Pyfa#2332]
TSB has been reworked in game to the Signature Radius Suppressor. I'm using version 2.34.0 which I think is the most recent update and the mod has not been updated yet to reflect it's in-game attributes

**Comment by DarkFenX** [comment]
i've been buried under workload. It has been updated in dev branch but to make a release i wanted to fix some localization stuff and macOS build. I fixed (or rather finished transition of) localization infrastructure and gave up on macOS build for this release, which is inbound soon. Sorry for that
