### ISSUE TITLE
IndexError under Notes - Ctrl + Backspace Character Sequence

### ISSUE THREAD

**Issue by cpuhurtz** [pyfa-org/Pyfa#2335]
### Expected behavior:
In the "Additions" section, while typing in the "Notes" tab, Ctrl + Backspace will delete the previous work until the cursor reaches white space (or some other miscellaneous character).

### Actual behavior:
Pyfa will produce an IndexError in the pyfa error prompt. 

### Detailed steps to reproduce:
Select a fitting. Toward the bottom of pyfa, under the "Additions" section, select the 'Notes' tab. Begin typing anywhere in the white space. Hit the "Ctrl + Backspace" character sequence to produce the error dialog.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Buzzard, T2 Exploration Intro]

Nanofiber Internal Structure II
[Empty Low slot]

Data Analyzer II
Relic Analyzer II
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Covert Ops Cloaking Device II
Core Probe Launcher II
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
pyfa v2.34.0 (Release) 

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10 Pro (x64) - OS Build: 19042.928 - Windows Feature Experience Pack 120.2212.551.0

### Other relevant information:
Really benign, likely low-priority bug. Just wanted to place it here for awareness.
The error that was produced within the dialog:  
-------------------------------------------------------
pyfa v2.34.0
EVE Data Version: 1878176 (2021-02-23 13:08:40)

OS version: Windows-10-10.0.19041-SP0
Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.23
Logbook version: 1.5.3
Requests version: 2.25.1
Dateutil version: 2.8.1

Traceback (most recent call last):
  File "gui\builtinAdditionPanes\notesView.py", line 29, in OnKeyDown
  File "gui\utils\helpers_wxPython.py", line 22, in HandleCtrlBackspace
IndexError: string index out of range

**Comment by DarkFenX** [comment]
Seems like this is a wx bug which is out of our control. Best i can do is put some guards in place to prevent from crashing. Done in b42254cb61bbc3d4df61a4da0ad5ddf14a5b6eae. On machines with this crash it will be suppressed, but ctrl-backspace still will not work.
