### ISSUE TITLE
Bastion Module discrepancies with ingame

### ISSUE THREAD

**Issue by DreamyDays1988** [pyfa-org/Pyfa#2336]
### Expected behavior:
Pyfa calulated falloff should match ingame simulator falloff with bastion module on

### Actual behavior:
Pyfa calculate falloff does not match ingame simulator falloff with bastion module on

### Detailed steps to reproduce:
1. Apply >=2 falloff-modifying modules
2. Apply Bastion Module I
3. Compare Ingame simulator falloff with pyfa calculated falloff

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Vargur, WTM Optimal]

Sentient Damage Control
Republic Fleet Gyrostabilizer
Republic Fleet Gyrostabilizer
Republic Fleet Gyrostabilizer
Republic Fleet Gyrostabilizer

Pithum A-Type Multispectrum Shield Hardener
Large Micro Jump Drive
Pith X-Type X-Large Shield Booster
Gist X-Type 500MN Microwarpdrive
Federation Navy Tracking Computer, Optimal Range Script
Pithum A-Type Multispectrum Shield Hardener

800mm Repeating Cannon II, Hail L
Small Coaxial Compact Remote Armor Repairer
800mm Repeating Cannon II, Hail L
Bastion Module I
800mm Repeating Cannon II, Hail L
Small Coaxial Compact Remote Armor Repairer
800mm Repeating Cannon II, Hail L
Small Tractor Beam II

Large Projectile Burst Aerator II
Large Projectile Ambit Extension I

High-grade Ascendancy Alpha
High-grade Ascendancy Beta
High-grade Ascendancy Gamma
High-grade Ascendancy Delta
High-grade Ascendancy Epsilon
Eifyr and Co. 'Rogue' Warp Drive Speed WS-618
Zainou 'Deadeye' Trajectory Analysis TA-706
Inherent Implants 'Squire' Capacitor Management EM-806
Eifyr and Co. 'Gunslinger' Surgical Strike SS-906
Eifyr and Co. 'Gunslinger' Large Projectile Turret LP-1006

Synth Blue Pill Booster
Synth Sooth Sayer Booster
Agency 'Pyrolancea' DB5 Dose II

Barrage L x15000
Hail L x30000

### Release or development git branch? Please note the release version or commit hash:
v2.34.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
Pyfa calculate falloff matches ingame simulator falloff without bastion module correctly.
So the discrepancy seems to come from bastion module handling.
![Vargur Ingame](https://user-images.githubusercontent.com/84129948/118115855-73d39300-b424-11eb-9424-d4c2670fd6a0.png)
![Vargur Calc](https://user-images.githubusercontent.com/84129948/118115858-759d5680-b424-11eb-8c4a-b9a2f58a57c5.png)
![Vargur Pyfa](https://user-images.githubusercontent.com/84129948/118115859-7635ed00-b424-11eb-90f0-523304627825.png)

**Comment by DarkFenX** [comment]
Fixed in 5763954f516711f8c5f230b1c213c191f8ec6492
