### ISSUE TITLE
Bastion Module - Golem

### ISSUE THREAD

**Issue by NovaSoldier** [pyfa-org/Pyfa#2340]
### Expected behavior:
Dps in game

Golem with torps:
- Without Bastion -  game = 1486.4 dps with reload and no drones
- With Bastion - game = 3077.4 dps with reload and no drones
- Alpha damage - 10939 dmg

### Actual behavior:
Dps in Pyfa 

Eg. Golem with torps:
- Without Bastion - pyfa = 1486 dps with reload and no drones
- With Bastion - pyfa = 2587 dps  with reload and no drones
- Alpha damage - 10939 dmg

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Golem, Golem fit]

Caldari Navy Ballistic Control System
Caldari Navy Ballistic Control System
Caldari Navy Ballistic Control System
Caldari Navy Ballistic Control System

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Torpedo Launcher II, Inferno Rage Torpedo
Torpedo Launcher II, Inferno Rage Torpedo
Torpedo Launcher II, Inferno Rage Torpedo
Torpedo Launcher II, Inferno Rage Torpedo
[Empty High slot]
[Empty High slot]
[Empty High slot]
Bastion Module I

Large Bay Loading Accelerator I
Large Warhead Calefaction Catalyst I

Zainou 'Snapshot' Torpedoes TD-603
Zainou 'Deadeye' Rapid Launch RL-1003

### Release or development git branch? Please note the release version or commit hash:
v2.35.0 - Eve Data Version 1903677 (2021-05-19)
### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10
### Other relevant information:
All outher marauders match the dps and alpha damage with and without the bastion module.

**Comment by DarkFenX** [comment]
Fixed in 91fbcd4eb44bafbecad850a325ede19f7e5dd6fa
