### ISSUE TITLE
Add Shield/Armor/Capacitor transfer per second for Logi ships

### ISSUE THREAD

**Issue by Iiridayn** [pyfa-org/Pyfa#235]
I'd like to see what my shield, armor, and capacitor transfer per second are when designing logistics ships. This might work under firepower as another option to the button that changes the display to mining amounts. I don't particularly care about structure transfer per second.

**Comment by lunedis** [comment]
I'm currently trying to implement this by building a 3rd StatsView besides Firepower and Mining.

I copied the MiningYieldViewFull and made a new class called OutgoingViewFull, changed some stuff there (which should be syntactically correct) and also called OutgoingViewFull.register() at the end.
I inserted "outgoingViewFull" in the __init__.py.

Pyfa still doesn't find the View if trying to load it by changing the switch button in FirepowerView or making it a default view. As far as I understand pyfa the following line in StatsView should load all views?
```python
from gui.builtinStatsViews import *
```

Should I commit my code so you can see my commit or do you have any ideas what my mistake might be?

**Comment by blitzmann** [comment]
Yeah, go ahead and commit the code to you repo on another branch off master. I can take a look at it. IIRC the switching between panels was pretty hackish. The contributor that did it did a great job, but the panel system just wasn't designed with the idea of turning panels on and off. It's probably something to do with that.

**Comment by lunedis** [comment]
![image](https://cloud.githubusercontent.com/assets/9085102/8557142/acbc25c4-24fb-11e5-964d-4af11990942e.png)

I did something.

https://github.com/lunedis/Pyfa/commit/d033e4a8d919664d3ae210098291e38df71d3256

**Comment by droppedoncaprica** [comment]
Nice dude!

**Comment by blitzmann** [comment]
I will take a look at it as I can. We just release v1.13.0, so we until the next release to polish this up if needed. =)

**Comment by blitzmann** [comment]
Sorry about the delay, but I was working on some other stuff. Took a look at your patch, and overall I like it. There is an issue tho:

![capture](https://cloud.githubusercontent.com/assets/3904767/8890693/0a390a48-32d8-11e5-9c6f-fa2004ec21ab.PNG)

Too much text will overflow and obscure the button, which cannot happen as there is no way to make the stats area wider, and the user may get stuck on a display if they have large enough text there. There seems to be a space between the icon and the text - not sure if that's just how it's laid out, or if there is an issue with the gui grid.

There's also the issue of what to do with Remote Hull repair, and possible RR/Cap drones. Of course, there's only 3 slots that we can really work with. Or maybe it can look like the Recharge Rates -- but then that introduces the problem of resizing the panel when we select that panel, and IIRC that would be difficult to do.

Or, we can switch between "recharge rates" and "outgoing effects" and just replace the passive shield recharge with cap stuff, and incorporate drones. But that raises the question on how we can switch between them as currently there's not much room to put a button. Maybe be able to click an icon in the header or something...

Honestly have no idea, there's a lot of options, none of them which really fit great. It could be argued that no one does RR hull tanking, and if they did they still have that info in the module listing. So we could leave that out if needed. And drones can be added to the overall rep amount, and the module / drone breakdown can be added as a tooltip.

Your call. At the very least, that text overflow has to be fixed =)

**Comment by blitzmann** [comment]
@lunedis Can you look into this again, or is time limited? Let me know so that I can prioritize this properly. =)

**Comment by Abaddon16** [comment]
I'd like to see this happen too. There are modules also that detract from the effectiveness that would need to be included in the calculations as well. I'm just starting to look at the code myself, it would take a good chunk of time to even begin to understand this, but I'll try.

**Comment by Abaddon16** [comment]
So I've been looking into this a significant amount (I'm trying to get some other things to work too) but I can't seem to get a good way to do it. However, I have come up with some ideas as to how it could work. 

You could put the repair and neut into another panel, with another toggle but have the toggle left justified. I haven't been able to do it myself (I'm quite new to this project, and Python in general), but I have been trying. I don't know how to go about cycling through the fit looking for all of the bits and bonuses/negations, and look for what would add to it (still trying to figure out the project).

**Comment by Ebag333** [comment]
@blitzmann want to flag this one as resolved?

**Comment by blitzmann** [comment]
Ah yes, thanks for reminding me.

Merged with 3209459e6d831ade0f68011da668372369004110 (#995)
