### ISSUE TITLE
Astero: wrong drone bandwidth shown in resources section

### ISSUE THREAD

**Issue by SimonKunzmann** [pyfa-org/Pyfa#2353]
### Expected behavior:
Astero has 25 Mbit/sec Drone bandwidth, so the Resources section should show 25 Mbit/sec:

![AsteroBug2](https://user-images.githubusercontent.com/4259389/131255475-5715fc40-6731-4f64-9cba-653ffa6a5f6e.png)

### Actual behavior:
Astero Resources section shows 12.5 Mbit/sec:

![AsteroBug1](https://user-images.githubusercontent.com/4259389/131255476-326d5dff-9703-41c2-af1d-aaf81ab643cf.png)

### Detailed steps to reproduce:
Add 5 light Drones to the astero and try to enable them. Resources section shows 25 / 12.5 mbit/s used

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Astero, Ninja Explo Relic Astero]

Nanofiber Internal Structure II
Inertial Stabilizers II
Type-D Restrained Overdrive Injector
'Halcyon' Core Equalizer I

Relic Analyzer I
5MN Cold-Gas Enduring Microwarpdrive
Scan Rangefinding Array I
Scan Rangefinding Array I

Sisters Core Probe Launcher
Covert Ops Cloaking Device II

Small Low Friction Nozzle Joints I
Small Polycarbon Engine Housing I
Small Emission Scope Sharpener I

Hornet EC-300 x10
Hornet EC-300 x5

Sisters Core Scanner Probe x16

### Operating system and version:
Windows 10

**Comment by gaunts** [comment]
![image](https://user-images.githubusercontent.com/3473452/132533133-b8f272ac-e313-44e8-b4d3-6b4b32c157fb.png)

**Comment by SimonKunzmann** [comment]
Oh i missed that. Sorry
/Close
