### ISSUE TITLE
macOS app version is wrong

### ISSUE THREAD

**Issue by vitorgalvao** [pyfa-org/Pyfa#2361]
## Bug Report

To accurately display version information, macOS apps need to have the `CFBundleVersion` and `CFBundleShortVersionString` tags in `Info.plist`.

In Pyfa’s case, the latter is set to a static `0.0.0` and the former is absent.

### Expected behavior:

App should have version numbers updated by release.

### Actual behavior:

App’s version is at a constant `0.0.0`.

### Detailed steps to reproduce:

Right-click the app in the Finder and do `Get Info` (<kbd>⌘</kbd><kbd>I</kbd>).

Alternatively, inspect the `pyfa.app/Contents/Info.plist` file.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

N/A.

### Release or development git branch? Please note the release version or commit hash:

Any.

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

macOS (any version).

### Other relevant information:

If they’re not set during the build process, `CFBundleVersion` and `CFBundleShortVersionString` can be added after it’s done by directly editing the `Info.plist`:

```bash
# Change these values
app_path='/PATH/TO/APP/HERE'
app_version='VERSION NUMBER HERE'

# Keep these as they are
/usr/libexec/PlistBuddy -c "Add :CFBundleVersion string ${app_version}" "${app_path}/Contents/Info.plist" # Add missing
/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString string ${app_version}" "${app_path}/Contents/Info.plist" # Modify existing
```

That would use the same version number for both fields. Technically they should be different, but that’s a secondary concern. An accurate version number is important for macOS to know which app to open in ambiguous situations; for users who expect the information available via the Finder; and for interoperability with other apps.

**Comment by blitzmann** [comment]
@vitorgalvao  can you test this build out? 

https://ci.appveyor.com/project/pyfa-org/pyfa-f3suj/builds/42986861/job/h31f1qg8yd9lyofj/artifacts

I'm in the build config for other reasons, and thought I would add this. Thanks for the commands, was super easy. If this works out, we can get this merged in

**Comment by vitorgalvao** [comment]
Confirmed as working. The `v` prefix is redundant, but that’s a secondary concern.

**Comment by blitzmann** [comment]
We'll keep it in there unless it causes issues. The version gets spit out via a script and is consistent across all our builds. 

We'll get this tweak merged in soon :)

**Comment by blitzmann** [comment]
Closing, this was merged in a while ago
