### ISSUE TITLE
Windows throws virus warning on latest release (v2.38.1)

### ISSUE THREAD

**Issue by Pelion123** [pyfa-org/Pyfa#2371]
On Windows 10 Home 19042.1288

When downloading pyfa-v2.38.1-win.exe from /releases, windows fails the download, throws a virus warning, and nukes the exe.

Note:  This is my first time trying to install pyfa on this computer so I don't know if this is new to this version, but I didn't see another ticket about it and nothing shows up when searching for "virus".

![image](https://user-images.githubusercontent.com/93771177/140504162-55e47143-baa1-45fb-8acb-71d73da950b3.png)

![image](https://user-images.githubusercontent.com/93771177/140504238-c281821a-c696-470c-8082-81bef5970fda.png)

Probably a false positive?

**Comment by blitzmann** [comment]
As long as you've downloaded it from GitHub or our AppVeyor artifacts, this is a false positive. You'll have to disable whatever anti virus software you have. Unfortunately there's not much we can do without signing the code (which takes $$$) or submitting the program as a false positive to whatever authority is blocking it (which takes 🕑)(which anti virus are you using?)

**Comment by Pelion123** [comment]
Hi, Thanks for the feedback.

This was just the standard windows defender.

________________________________

**Comment by blitzmann** [comment]
Hrm, I have windows defender enabled and I can download it just fine. I wonder if you have stricter security settings somehow.

**Comment by DarkFenX** [comment]
@blitzmann defender's behavior is stricter for executables with unknown for it signature. So, first tens/hundreds of users which launch it, have to do more clicks to get past it.
