### ISSUE TITLE
Many warnings on startup

### ISSUE THREAD

**Issue by rumline** [pyfa-org/Pyfa#2372]
## Bug Report
Running 2.38.1 from a "git clone" on Windows. On startup of pfya.py, many warning messages are displayed.

### Expected behavior:
No warnings displayed

### Actual behavior:
E:\Games\Pfya\service\market.py:263: SAWarning: relationship 'DynamicItem.applicableItems' will copy column mutaplasmids.typeID to column mutaplasmidItems.typeID, which conflicts with relationship(s): 'DynamicItemItem.mutaplasmid' (copies mutaplasmids.typeID to mutaplasmidItems.typeID). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="mutaplasmid"' to the 'DynamicItem.applicableItems' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  self.les_grp = types_Group()
E:\Games\Pfya\service\market.py:263: SAWarning: relationship 'Item.mutaplasmids' will copy column mutaplasmids.typeID to column mutaplasmidItems.typeID, which conflicts with relationship(s): 'DynamicItemItem.mutaplasmid' (copies mutaplasmids.typeID to mutaplasmidItems.typeID). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="mutaplasmid"' to the 'Item.mutaplasmids' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  self.les_grp = types_Group()
E:\Games\Pfya\service\market.py:263: SAWarning: relationship 'Fit._Fit__modules' will copy column fits.ID to column modules.fitID, which conflicts with relationship(s): 'Module.owner' (copies fits.ID to modules.fitID). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="owner"' to the 'Fit._Fit__modules' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  self.les_grp = types_Group()
E:\Games\Pfya\service\market.py:263: SAWarning: relationship 'Fit._Fit__projectedModules' will copy column fits.ID to column modules.fitID, which conflicts with relationship(s): 'Fit._Fit__modules' (copies fits.ID to modules.fitID), 'Module.owner' (copies fits.ID to modules.fitID). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="_Fit__modules,owner"' to the 'Fit._Fit__projectedModules' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  self.les_grp = types_Group()
E:\Games\Pfya\service\market.py:263: SAWarning: relationship 'Fit._Fit__boosters' will copy column fits.ID to column boosters.fitID, which conflicts with relationship(s): 'Booster.owner' (copies fits.ID to boosters.fitID). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="owner"' to the 'Fit._Fit__boosters' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  self.les_grp = types_Group()
E:\Games\Pfya\service\market.py:263: SAWarning: relationship 'Fit._Fit__drones' will copy column fits.ID to column drones.fitID, which conflicts with relationship(s): 'Drone.owner' (copies fits.ID to drones.fitID). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="owner"' to the 'Fit._Fit__drones' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  self.les_grp = types_Group()
E:\Games\Pfya\service\market.py:263: SAWarning: relationship 'Fit._Fit__fighters' will copy column fits.ID to column fighters.fitID, which conflicts with relationship(s): 'Fighter.owner' (copies fits.ID to fighters.fitID). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="owner"' to the 'Fit._Fit__fighters' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  self.les_grp = types_Group()
E:\Games\Pfya\service\market.py:263: SAWarning: relationship 'Fit._Fit__cargo' will copy column fits.ID to column cargo.fitID, which conflicts with relationship(s): 'Cargo.owner' (copies fits.ID to cargo.fitID). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="owner"' to the 'Fit._Fit__cargo' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  self.les_grp = types_Group()
E:\Games\Pfya\service\market.py:263: SAWarning: relationship 'Fit._Fit__projectedDrones' will copy column fits.ID to column drones.fitID, which conflicts with relationship(s): 'Drone.owner' (copies fits.ID to drones.fitID), 'Fit._Fit__drones' (copies fits.ID to drones.fitID). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="_Fit__drones,owner"' to the 'Fit._Fit__projectedDrones' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  self.les_grp = types_Group()
E:\Games\Pfya\service\market.py:263: SAWarning: relationship 'Fit._Fit__projectedFighters' will copy column fits.ID to column fighters.fitID, which conflicts with relationship(s): 'Fighter.owner' (copies fits.ID to fighters.fitID), 'Fit._Fit__fighters' (copies fits.ID to fighters.fitID). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="_Fit__fighters,owner"' to the 'Fit._Fit__projectedFighters' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  self.les_grp = types_Group()

**Comment by blitzmann** [comment]
@rumline I'm assuming it's the same situation as #2373, you have incorrect versions of various libraries and packages used by pyfa. Please use a virtual env and install the requirements as noted in the requirements.txt file in the root of the repo.

If that doesn't work, please reply. Thanks!
