### ISSUE TITLE
Preferences screen doesn't function

### ISSUE THREAD

**Issue by rumline** [pyfa-org/Pyfa#2373]
## Bug Report
Attempting to use the Global -> Preferences menu item creates an error window.

### Expected behavior:
A preferences windows appears without error

### Actual behavior:
Select Global -> Preferences from the menu
Error message is displayed:

pyfa v2.38.1
EVE Data Version: 1957858 (2021-10-28 05:15:53)

OS version: Windows-10-10.0.19043-SP0
Python version: 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
wxPython version: 4.1.1 (wxWidgets 3.1.5)
SQLAlchemy version: 1.4.26
Logbook version: 1.5.3
Requests version: 2.26.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "E:\Games\Pfya\gui\mainFrame.py", line 486, in OnShowPreferenceDialog
    with PreferenceDialog(self) as dlg:
  File "E:\Games\Pfya\gui\preferenceDialog.py", line 68, in __init__
    prefView.populatePanel(page)
  File "E:\Games\Pfya\gui\builtinPreferenceViews\pyfaGeneralPreferences.py", line 93, in populatePanel
    langBox.Add(wx.StaticText(panel, wx.ID_ANY,
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_CENTRE_VERTICAL)" failed at ..\..\src\common\sizer.cpp(2147) in wxBoxSizer::DoInsert(): Vertical alignment flags are ignored in vertical sizers

**Comment by blitzmann** [comment]
> Python version: 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
wxPython version: 4.1.1 (wxWidgets 3.1.5)

These are unsupported versions for pyfa. I assume you're running from source?

The EXE that is built for windows runs Python 3.7.9 and wxPython 4.0.6. wxPython 4.1 has known issues, see #2179 

Please install python packages based on requirements.txt. If you have any further questions, please post them here
