### ISSUE TITLE
Unable to move or place drones into the drone bay of the vigilant

### ISSUE THREAD

**Issue by Wizbit1977** [pyfa-org/Pyfa#2382]
Cannot place drones into the VIgilant ship drone bay

to place drones in the drone bay

clicking the drones or dragging them doesnt move them or add them

try to place drones into a vigilant ship

### Release or development git branch? Please note the release version or commit hash:

win 10

**Comment by DarkFenX** [comment]
Fixed in 1561d9f58144147f5a577523e3efd48397880402

**Comment by DarkFenX** [comment]
Reopening until new release is out
