### ISSUE TITLE
Missile Range Not Displaying - Version 2.39.0 DEV2

### ISSUE THREAD

**Issue by xErgoProxyx** [pyfa-org/Pyfa#2385]
Looks like the missile range under the range tab isn't showing up - so far no missile based ships I've looked at show the value unless I mouse over it and wait for a few seconds. I'll attach screen shots. 

https://imgur.com/a/7jgWbNX

**Comment by DarkFenX** [comment]
Yep, I also noticed it and it is fixed already, check dev3
