### ISSUE TITLE
Drone Optimal not displayed in Additions section Drones tab

### ISSUE THREAD

**Issue by fonsuiplaysvideogames** [pyfa-org/Pyfa#2386]
The Drones tab in the Additions section erroneously no longer displays the optimal range, see screenshot. Observed in current release (2.39.0).

![image](https://user-images.githubusercontent.com/60384561/145360521-0a34042a-497b-4671-9f05-cbab0f3d4a8f.png)

**Comment by DarkFenX** [comment]
Fixed in a7c2f700b493a0592b35e3220e6ade9604d943ae
