### ISSUE TITLE
Resistance calculated wrong on expedition frigates

### ISSUE THREAD

**Issue by AlexLeninEve** [pyfa-org/Pyfa#2387]
## Bug Report
On Endurance looks like resistances from ship skill calculated back-way: with all0 char it have 20% thermal and with all5 it have 4%:
https://i.imgur.com/4Fw1ieL.png
https://i.imgur.com/KoaDkCb.png
Everything else like PG/CPU/HP scaled correctly with general skill bonuses.

On Prospect it has 90% EM resistance out of nowhere:
https://i.imgur.com/b4Bsyk3.png
while in-game stats saying it's 0%:
https://i.imgur.com/i41ti0u.png

### Detailed steps to reproduce:
Play with fits from below

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Endurance, Endurance fit]

[Empty Low slot]
Signal Amplifier II
Signal Amplifier II

5MN Cold-Gas Enduring Microwarpdrive
Warp Disruptor II
Warp Scrambler II
Medium Shield Extender II

Improved Cloaking Device II
[Empty High slot]
[Empty High slot]

Small Polycarbon Engine Housing II
[Empty Rig slot]

[Prospect, Prospect fit]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

5MN Cold-Gas Enduring Microwarpdrive
Warp Disruptor II
Warp Scrambler II

Covert Ops Cloaking Device II
200mm AutoCannon II, Republic Fleet Depleted Uranium S
200mm AutoCannon II, Republic Fleet Depleted Uranium S

[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
v2.39.0
EVE Data Version: 1975905 (2021-12-07 14:11:59)

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by DarkFenX** [comment]
It was a bug with EVE data. CCP fixed it yesterday, data will be included in a later release.
