### ISSUE TITLE
fuel consumption for Large Industrial core II maybe calculated wrong in pyfa

### ISSUE THREAD

**Issue by HoinzBHD** [pyfa-org/Pyfa#2394]
### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Orca, Orca Nunu Boni future]

Damage Control II
Reinforced Bulkheads II

Multispectrum Shield Hardener II
Multispectrum Shield Hardener II
Thermal Shield Hardener II
EM Shield Hardener II
EM Shield Hardener II

Large Remote Shield Booster II
Large Industrial Core II
Small Tractor Beam II
Mining Foreman Burst II, Mining Laser Optimization Charge
Mining Foreman Burst II, Mining Laser Field Enhancement Charge
Mining Foreman Burst II, Mining Equipment Preservation Charge

Large Transverse Bulkhead II
Large Transverse Bulkhead II
Large Transverse Bulkhead II

'Augmented' Ice Harvesting Drone x1
'Augmented' Mining Drone x5
Hobgoblin II x5
Hornet II x5
Mining Drone II x5
Warrior II x5

Mining Foreman Mindlink

Mining Equipment Preservation Charge x600
Mining Laser Field Enhancement Charge x600
Mining Laser Optimization Charge x600
Mobile Depot x1
500MN Cold-Gas Enduring Microwarpdrive x1

### Other relevant information:
![orca industrial core pyfa bug](https://user-images.githubusercontent.com/96523693/147074223-014efda0-684d-4d18-b14b-1e9abff4ac72.png)

**Comment by DarkFenX** [comment]
Fixed in 8cbe094ee6a8744d11cc948e7980ee77e0cdd12e
