### ISSUE TITLE
Mutated Drone Specialization Not Shown in Character Editor

### ISSUE THREAD

**Issue by Eliza513F** [pyfa-org/Pyfa#2399]
### Detailed steps to reproduce: 
1: Launch pyfa
2: At the top left, select Editors -> Character Editor
3: Select a character from the dropdown menu that has previously been added via ESI
4: In the skills menu, open the Drones category and scroll down to where Mutated Drone Specialization should be (the list is sorted alphabetically), and observe its absence
5: Confirm it isn't there by typing Mutated Drone Specialization into the search bar right above the skills menu

### Other relevant information: A screenshot of the bug is attached to this bug report
![Bug Screenshot](https://user-images.githubusercontent.com/95322039/149601876-5c9e69c5-5080-4ce1-ada4-cb02afa6f0be.png)

**Comment by blitzmann** [comment]
This skill was inadvertently being unpublished, and thus being skipped. I've fixed this, and it seems to be working. Should be available in the next release :)
