### ISSUE TITLE
Feature alpha account

### ISSUE THREAD

**Issue by Kaitenn-dev** [pyfa-org/Pyfa#2408]
Hi,
First thanks for continuing the support on pyfa
Is it possible to add on pyfa maximum skill alpha? (same to all lv5 preset)
Thanks for answer, have a good day!

**Comment by blitzmann** [comment]
@Kaitenn-dev sorry for the delay

This is easy enough to do. Simply copy the level 5 pre-set character, and apply the Alpha clone to it. 

![image](https://user-images.githubusercontent.com/3904767/159626256-ba223fb0-3ab3-4ab4-ad5c-844ba8fc8dcc.png)

The alpha clone sets a cap on certain skills, so if you have an all 5 character with alpha caps, it' effectively a maxed out alpha character.

Thanks!

**Comment by jerclarke** [comment]
Thanks for this answer! I tried and it really is easy.

But would it be hard to add this as a default preset? A lot of players never figure out the character editor and the clone state pulldown. It feels like a really logical match to the "All 5" preset, and I know there's a lot of people who like to check a fit is Alpha-friendly. 

Seems like something that would get used a lot, and wouldn't hurt anyone. 

Thanks for considering, I understand if it's just not something you want :)
