### ISSUE TITLE
No Edencom Ammo in incoming damage pattern

### ISSUE THREAD

**Issue by Woodius** [pyfa-org/Pyfa#2413]
Hello, 

I tried to test some fits and realised there is no Edencom ammo option in incoming damage pattern. That would be nice addon if possible.

Thanks, Woodius

**Comment by fonsuiplaysvideogames** [comment]
![image](https://user-images.githubusercontent.com/60384561/159123306-afc22914-7ac3-409a-8353-130cee76027d.png)

**Comment by DarkFenX** [comment]
Added in 86e171f13d4006690d239eea34ab501cbad89116. Please bear in mind that ratios for some ammo types are very different (see the table above, thanks for it btw), what we have in pyfa now is the same as I did for exotic plasma - average of ratios across all 3 sizes.
