### ISSUE TITLE
Resistances cannot be changed in the Fit Graphs under AppImage

### ISSUE THREAD

**Issue by maiklooper** [pyfa-org/Pyfa#2432]
## Bug Report
Under the exe file you could change the resist mode of ships on which you project the damage of other ships this option seems not to be there in the AppImage file.

### Expected behavior:
![pyfa_exe](https://user-images.githubusercontent.com/103245044/162390308-4202c85c-ac7f-4184-aa0b-cc58fe07d5db.png)

### Actual behavior:
![pyfa_appImage](https://user-images.githubusercontent.com/103245044/162390367-edcdae94-2896-41f7-9a80-9509268b5c57.png)

### Detailed steps to reproduce:
You can reproduce that with any fit:

1. Open a fit
2. Go to "Fit" --> "Graphs" or press "Strg+G"
3. Open a currently open fit in the list where it says "[...] to have the your fit graphed against it"
4. Right click the fit in the right list and look at the options (like "Target Profile")
5. The "Resist Mode" option is missing in the AppImage file

### Fits involved in EFT format (Edit > To Clipboard > EFT):
any fit works

### Release or development git branch? Please note the release version or commit hash:

- pyfa-v2.42.0-win.exe
- pyfa-v2.42.0-linux.AppImage

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Linux Mint 20.1 Cinnamon

**Comment by blitzmann** [comment]
hrm, that's very interesting, There shouldn't be anything restricting that menu from showing up in the linux build unless

Is it for all fits? Can you post the specific fit you're using? Are you using the ALL 5 character?

**Comment by fonsuiplaysvideogames** [comment]
Make sure the "Ignore Target Resists" option in the little burger menu on the graphs dialogue box is unchecked; when this option is checked, it removes the "Resist Mode" submenu:
![image](https://user-images.githubusercontent.com/60384561/162535571-0b0f7262-4fe3-4dd6-bdf8-5047bfb7a9cd.png)
![image](https://user-images.githubusercontent.com/60384561/162535598-bfd10c83-6b98-463b-b197-f3ddaa7e55c0.png)
![image](https://user-images.githubusercontent.com/60384561/162535617-9283a1c3-043e-4d8a-9524-6658e4712e5b.png)

**Comment by maiklooper** [comment]
The "Ignore Target Resists" option worked.
Thank you
