### ISSUE TITLE
Drone Synthesis Projector Trait Description not Updated

### ISSUE THREAD

**Issue by Bluedagger21** [pyfa-org/Pyfa#2433]
### Expected behavior:
![image](https://user-images.githubusercontent.com/2181149/162549151-2a47ecbe-3ec3-4e84-a64a-4736a944c9dc.png)

### Actual behavior:
![image](https://user-images.githubusercontent.com/2181149/162549161-a1fc577a-ad1c-4a68-a41b-76daaf101bc6.png)
Only the description is wrong. Attributes shows the increased CPU changes to 60

### Detailed steps to reproduce:
Show subsystem stats on Proteus Offensive - Drone Synthesis Projector Subsystem and view Traits tab

### Release or development git branch? Please note the release version or commit hash:
v2.42.0 release

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by blitzmann** [comment]
Can you link the patch notes where that screenshot comes from?

**Comment by DarkFenX** [comment]
It's fixed now. And it was issue with CCP-provided data, we do not maintain those descriptions.
