### ISSUE TITLE
no damage bonus associated with tengu subsystem kinetic

### ISSUE THREAD

**Issue by 2Bad4Ux2** [pyfa-org/Pyfa#2438]
## Bug Report

On tengu, with accelerated ejection kinetic gives a dps bonus but regardless missile type, no bonus is given.
### Fits involved in EFT format (Edit > To Clipboard > EFT): [Tengu, 100mn]

Ballistic Control System II
Ballistic Control System II
Power Diagnostic System II

100MN Afterburner II
Republic Fleet Stasis Webifier
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
Republic Fleet Medium Cap Battery
Republic Fleet Warp Disruptor

Heavy Missile Launcher II, Caldari Navy Scourge Heavy Missile
Heavy Missile Launcher II, Caldari Navy Scourge Heavy Missile
Heavy Missile Launcher II, Caldari Navy Scourge Heavy Missile
Heavy Missile Launcher II, Caldari Navy Scourge Heavy Missile
Heavy Missile Launcher II, Caldari Navy Scourge Heavy Missile
Heavy Missile Launcher II, Caldari Navy Scourge Heavy Missile
[Empty High slot]

Medium Ancillary Current Router II
Medium Capacitor Control Circuit II
Medium Capacitor Control Circuit I

Tengu Defensive - Amplification Node
Tengu Offensive - Accelerated Ejection Bay   ****no damage bonus as stated****
Tengu Propulsion - Fuel Catalyst
Tengu Core - Augmented Graviton Reactor

Mid-grade Crystal Alpha
Mid-grade Crystal Beta
Mid-grade Crystal Gamma
Mid-grade Crystal Delta
Mid-grade Crystal Epsilon
Zainou 'Gypsy' CPU Management EE-603
Eifyr and Co. 'Gunslinger' Motion Prediction MR-703
Eifyr and Co. 'Gunslinger' Medium Projectile Turret MP-803
Eifyr and Co. 'Gunslinger' Large Projectile Turret LP-1003

Standard Blue Pill Booster

**Comment by xpapahet** [comment]
you do something wrong. 
all works fine for me. check your subsystem skill lvl in pyfa

**Comment by DarkFenX** [comment]
402 with non-kinetic, 502 with kinetic on all 5 skills. Seems like an issue on your side (probably with subsystem skill level, as @xpapahet stated)
