### ISSUE TITLE
ElectroPunch damage profile is incorrect

### ISSUE THREAD

**Issue by aebe** [pyfa-org/Pyfa#2455]
## Bug Report

The built in damage profile for [T2] ElectroPunch is incorrect. It gives thermal and explosive damage, while the actual damage is EM and kinetic.

### Expected behavior:

The damage profile should be EM and kinetic, with slightly more EM

### Actual behavior:

The damage profile is thermal and explosive, with slightly more thermal

### Detailed steps to reproduce:

1. Look at the damage profile in pyfa
2. Look at the actual damage stats for ElectroPunch in game

### Fits involved in EFT format (Edit > To Clipboard > EFT):

N/A

### Release or development git branch? Please note the release version or commit hash:

2.43.0 release

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10

### Other relevant information:

This is an easy fix at `eos/saveddata/damagePattern.py` line 69, but it wasn't clear to me how the average across sizes is calculated so I  didn't make a PR for it. My best guess is everything is just shifted over one cell, i.e. it should be 

```
    (-28, (_c(_t('Condenser Packs')) + '|' + _t('[T2] ElectroPunch'), 50547, 0, 49453, 0)),
```

**Comment by DarkFenX** [comment]
Fixed in 289acc099c1ebdec4f97cd95ecc5aacf5963d0b4
