### ISSUE TITLE
Feature request: dark theme

### ISSUE THREAD

**Issue by xtalia** [pyfa-org/Pyfa#2458]
Good evening! 
Is it possible to add a dark theme for this program, please? 
If you do not use linux or macos, where it is possible to apply a normal dark theme to the entire environment, then it will not look so good in Windows. The dark theme adds the ability to study the fitting of ships at night comfortable. 

Thank you very much.

**Comment by Anonymous3x7** [comment]
Same request, the white really hurt my eyes.

That would make an already great app far above great!

**Comment by bkmvlgit** [comment]
Would be great, i use dark theme in all applications that support it, a lot nicer to look at.

**Comment by huuxfluux** [comment]
Yes please my eyes **_hurt_**!

**Comment by shanahanjrs** [comment]
+1

**Comment by DarkFenX** [comment]
Indeed
