### ISSUE TITLE
[Feature Suggestion] Short search term

### ISSUE THREAD

**Issue by KZdavid** [pyfa-org/Pyfa#2465]
Now Pyfa need at least 3 characters to search. It make sense for language such as English. But for Chinese, 3 characters are too many. Could you lower the length for searching to 1 or 2? Or let user decide the shortest length for searching.
Best regards
KZdavid, a Chinese pyfa user

**Comment by DarkFenX** [comment]
I thought i reduced this limit for CJK languages. This line is responsible for it in ship browser: https://github.com/pyfa-org/Pyfa/blob/master/gui/builtinShipBrowser/navigationPanel.py#L91

Do you mean market browser? Or does it not work in ship browser anymore? If so, give me your search term and a few fit names which could match it.

**Comment by 1072387333** [comment]
I think it should be market browser. In Chinese, the names of UAV and some T2 ammunition are very short. For example, the Chinese name of "warrior" is "武士", which has only two characters, so we can't retrieve it。

There are also many items like “Acolyte”（侍僧）“Wasp”（胡峰）“Ogre”（蛮妖）“Javelin”（标枪）“Void”（涅槃）“Tremor”（战栗）“Mystic”（奥秘）“Gleam”（微光），etc 。

There are more, I can't list them all. They are mainly concentrated in ammunition and UAVs.

**Comment by DarkFenX** [comment]
ok, that should be easy

**Comment by DarkFenX** [comment]
Done in 7892e637b25476f2ca725df54543309ede43a356
