### ISSUE TITLE
Request: EANM > Multispectrum cross-lookup missing?

### ISSUE THREAD

**Issue by bugme143** [pyfa-org/Pyfa#2474]
New patch for the Navy Battlecruisers seems to have removed the ability to search for EANMs using the old regex method of searching for shortened words, such as "ener ada nano" for EANMs. Can this be added back in?

**Comment by DarkFenX** [comment]
I am unsure when it worked, and how it worked if it did. Default definitions are here: https://github.com/pyfa-org/Pyfa/blob/master/service/jargon/defaults.yaml

You can define your own jargon definitions in <user>/.pyfa/user_jargon.yaml if you want that specific thing back in

**Comment by bugme143** [comment]
Oh hell yeah! I didn't know about that! Thank you very much!
