### ISSUE TITLE
Copy fit in EFT format to clipboard fails

### ISSUE THREAD

**Issue by bkmvlgit** [pyfa-org/Pyfa#2480]
## Bug Report
When i hit CTRL+C on a fit and choose EFT i get the following error

pyfa v2.48.0
EVE Data Version: 2154998 (2022-11-10 01:10:09)

OS version: Windows-10-10.0.19041-SP0
Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.23
Logbook version: 1.5.3
Requests version: 2.28.1
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "gui\copySelectDialog.py", line 161, in Validate
  File "gui\copySelectDialog.py", line 188, in exportEft
  File "service\port\port.py", line 305, in exportEft
  File "service\port\eft.py", line 90, in exportEft
  File "service\port\eft.py", line 210, in exportFighters
  File "service\port\eft.py", line 207, in fighterSorter
AttributeError: 'Fighter' object has no attribute 'fullName'

### Expected behavior:
Fit copied to clipboard for import in the game

### Actual behavior:
Error message

### Detailed steps to reproduce:
Choose fit in pyfa, hit ctrl+c to copy in the new window choose EFT (i have all boxed checked) press ok and the error pops up.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
https://imgur.com/w3ow0G7 fit in question taken earlier from Zkill, tried another faction fortizar fit with the same result, trying with a Mackinaw fit it works.

### Release or development git branch? Please note the release version or commit hash:
Release branch 2.48.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:

This worked fine in the previous release of pyfa so something changed in this release.

**Comment by DarkFenX** [comment]
Was fixed, will be available in the next release.
