### ISSUE TITLE
Loki Defensive - Covert Reconfiguration overheating bonus is not applied

### ISSUE THREAD

**Issue by beedogcc** [pyfa-org/Pyfa#2484]
## Bug Report
As title.

### Expected behavior:
The subsystem's overheating bonus should also be applied to Overload Shield Boost Bonus.

### Actual behavior:
The bonus is not applied when setting a shield booster to overheat.

### Detailed steps to reproduce:
- Create a Loki fit
- Install Covert Reconfiguration subsystem
- Install a shield booster to the fit
- Set the shield booster to overheat
- Check the shield booster's module stats and observe that the "Overload Shield Boost Bonus" is 10% for current value

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Loki, Loki fit]

[Empty Low slot]

Dread Guristas Large Shield Booster
[Empty Med slot]

[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

Loki Defensive - Covert Reconfiguration
[Empty Subsystem slot]
[Empty Subsystem slot]
[Empty Subsystem slot]

And for comparison, a Tengu fit where the bonus is applied properly:
[Tengu, Tengu fit]

Dread Guristas Large Shield Booster
[Empty Med slot]
[Empty Med slot]

[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

Tengu Defensive - Covert Reconfiguration
[Empty Subsystem slot]
[Empty Subsystem slot]
[Empty Subsystem slot]

### Release or development git branch? Please note the release version or commit hash:
Release 2.48.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
N/A

![image](https://user-images.githubusercontent.com/105969916/201638974-75570237-f688-4ab7-a26f-4bc8fdb34c08.png)
![image](https://user-images.githubusercontent.com/105969916/201639019-f1e2a155-b25d-4737-8434-9cdddc37ef00.png)

**Comment by DarkFenX** [comment]
Thanks. Fixed in dd93f348e61057ca7c224c62573280b257fa82fc
