### ISSUE TITLE
Zainou 'Snapshot' Auto-Targeting Explosion Radius FR-1005 bonus not applied

### ISSUE THREAD

**Issue by diviner1024** [pyfa-org/Pyfa#2487]
## Bug Report
"Zainou 'Snapshot' Auto-Targeting Explosion Radius FR-1005"'s bonus to auto-targeting missile explosion radius is not applied.

### Expected behavior:
 auto-targeting missile explosion radius should be reduced by this implant.

### Actual behavior:
auto-targeting missile explosion not applied in test with raven navy issue and cruise auto-target missile.

### Detailed steps to reproduce:

Fit a raven navy issue below. Testing with other ships also confirms this issue.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

[Raven Navy Issue, Raven Navy Issue fit]

Caldari Navy Ballistic Control System
Caldari Navy Ballistic Control System
Caldari Navy Ballistic Control System
Ballistic Control System II
Damage Control II

Caldari Navy Large Shield Extender
Caldari Navy Large Shield Extender
Missile Guidance Computer II, Missile Precision Script
Multispectrum Shield Hardener II
Multispectrum Shield Hardener II
Missile Guidance Computer II, Missile Precision Script
Missile Guidance Computer II, Missile Precision Script

Cruise Missile Launcher II, Scourge Auto-Targeting Cruise Missile I
Cruise Missile Launcher II, Scourge Auto-Targeting Cruise Missile I
Cruise Missile Launcher II, Scourge Auto-Targeting Cruise Missile I
Cruise Missile Launcher II, Scourge Auto-Targeting Cruise Missile I
Cruise Missile Launcher II, Scourge Auto-Targeting Cruise Missile I
Cruise Missile Launcher II, Scourge Auto-Targeting Cruise Missile I
Cruise Missile Launcher II, Scourge Auto-Targeting Cruise Missile I
Cruise Missile Launcher II, Scourge Auto-Targeting Cruise Missile I

Large Hydraulic Bay Thrusters I
Large Warhead Rigor Catalyst II
Large Warhead Rigor Catalyst II

Zainou 'Deadeye' Missile Projection MP-705
Zainou 'Deadeye' Guided Missile Precision GP-805
Zainou 'Deadeye' Target Navigation Prediction TN-905
Zainou 'Snapshot' Auto-Targeting Explosion Radius FR-1005

### Release or development git branch? Please note the release version or commit hash:

Release v2.48.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10

**Comment by DarkFenX** [comment]
Fixed in e21789d29c2153cd4a835afc3f6f5433fb14eacc
