### ISSUE TITLE
[Enhancement] Add Adam4eve.eu as a Market Price API

### ISSUE THREAD

**Issue by ZaxLofful** [pyfa-org/Pyfa#2497]
Adam4eve.eu is probably the best source of data out there. Evermarketer goes down all the time.

Can we get this as an option?

**Comment by ZaxLofful** [comment]
I just saw other options being added, can we get this as well?

Is there a way to add this custom?

**Comment by DarkFenX** [comment]
This flew under my radar. Will add it if I get link to a page with some docs / examples. I tried to find it myself but couldn't in a few mins, not gonna spend more time on search atm, sorry.
