### ISSUE TITLE
cannot build pyfa with sqlalchemy 2.0.8

### ISSUE THREAD

**Issue by yurats** [pyfa-org/Pyfa#2502]
## Bug Report
Looks like module relation was renamed to relationship in sqlalchemy 2.x.x

### Expected behavior:
pyfa builds normally from git

### Actual behavior:
File "/var/tmp/portage/games-util/pyfa-9999/work/pyfa-9999/eos/db/gamedata/alphaClones.py", line 21, in <module>
    from sqlalchemy.orm import relation, mapper, synonym
ImportError: cannot import name 'relation' from 'sqlalchemy.orm' (/usr/lib/python3.10/site-packages/sqlalchemy/orm/__init__.py)

### Release or development git branch? Please note the release version or commit hash:
[b248cde](https://github.com/pyfa-org/Pyfa/commit/b248cdefdda05193d7238f94611f6622e6c17de1)

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Gentoo Linux, Python 3.10, sqlalchemy 2.0.8

**Comment by UriAnteo** [comment]
Had the same problem when using Python 3.11 - solved this by also installing Python 3.7 (listed as requirement) and specifying it as the version to use when creating the virtual environment:
`py -3.7 -m venv PyfaEnv` instead of `python -m venv PyfaEnv`

**Comment by yurats** [comment]
> Had this problem with Python 3.11; solved by also installing Python 3.7 (listed as requirement) and specifying it as the version to use when creating the virtual environment by doing `py -3.7 -m venv PyfaEnv` instead of `python -m venv PyfaEnv`

but it does not make sense at all, i.e. for example python 3.7 removed from gentoo's portage tree (and outdated).

**Comment by DarkFenX** [comment]
FYI i tried to migrate pyfa to sqlalchemy 2.x while bumping up dependency versions. It was a pain on many many levels. I gave up, pyfa stays on the newest 1.x
