### ISSUE TITLE
Flatpak distribution of Pyfa

### ISSUE THREAD

**Issue by asbytes** [pyfa-org/Pyfa#2510]
Hello!

I have flatpak project for Pyfa at https://github.com/asbytes/com.github.Pyfa
Can i publish it on Flathub.org? Or you could pull the repo and publish it by yourself,
because Flathub.org states that it prefers the apps be published by their authors.

**Comment by foundObjects** [comment]
+1 for this, I literally had building the same thing on my TODO list for tomorrow. Please pick this up officially, it would be a really nice QoL addition to the project for a lot of us.

**Comment by foundObjects** [comment]
> Hello!
> 
> I have flatpak project for Pyfa at https://github.com/asbytes/com.github.Pyfa Can i publish it on Flathub.org? Or you could pull the repo and publish it by yourself, because Flathub.org states that it prefers the apps be published by their authors.

I'm unable to build this flatpak as is, it dies fairly early on with:

```
[arglebargle@archx16 com.github.Pyfa-flatpak]$ flatpak-builder --repo=repo flatpakbuildir com.github.Pyfa.json --force-clean

(flatpak-builder:108988): Json-WARNING **: 13:41:58.907: Failed to deserialize "modules" property of type "gpointer" for an object of type "BuilderModule"
Emptying app dir 'flatpakbuildir'
Downloading sources
Starting build of com.github.Pyfa
Cache hit for python-3.7, skipping build
Cache miss, checking out last cache hit
========================================================================
Building module gnome-themes-extra in /home/arglebargle/working/com.github.Pyfa-flatpak/.flatpak-builder/build/gnome-themes-extra-2
========================================================================
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: linking file 'm4/libtool.m4'
libtoolize: linking file 'm4/ltoptions.m4'
libtoolize: linking file 'm4/ltsugar.m4'
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
Can't exec "intltoolize": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 293.
autoreconf: error: intltoolize failed with exit status: 2
Error: module gnome-themes-extra: module gnome-themes-extra: Child process exited with code 2
```

It looks like I'm missing a build dependency but I don't see any special internationalization addon for org.gnome.Sdk.

**Comment by DarkFenX** [comment]
I am putting majority of my spare time into nextgen calculation core for pyfa (which is in private repo for now). As such, I'd prefer to spend as little as possible on pyfa maintenance.

If you link me publication process and what has to be changed to support that, I can look into it. If it's not too much hassle, I can do it myself. If it's too much, i'd prefer if you do it.

**Comment by Nathan-LS** [comment]
+1 it would be cool to have pyfa on flathub because flatpaks are distro-agnostic and flatpak updates are automated for users without the need to redownload the latest app image. I was considering making my own flatpak of pyfa but it's nice to see one already exists.


To answer your question about publishing, here are the [app publishing instructions](https://docs.flathub.org/docs/for-app-authors/submission/). The app publishing can be done either by the app developer or a third party. Once approved, a new repo gets created under the [flathub organization](https://github.com/flathub/) and the submitter gets write access. On new commits to this branch the flatpak is built and published to flathub through their [build process](https://docs.flathub.org/docs/for-app-authors/maintanance#buildbot).

**Comment by asbytes** [comment]
Pyfa published on Flathub:
https://flathub.org/apps/io.github.pyfa_org.Pyfa

I had to change app id from _com.github.Pyfa_ to _io.github.pyfa_org.Pyfa_. If you installed and used Pyfa from my github repo, please rename app directory from _~/.var/app/com.github.Pyfa_ to _~/.var/app/io.github.pyfa_org.Pyfa_

Please report related issues to flathub repository:
https://github.com/flathub/io.github.pyfa_org.Pyfa
