### ISSUE TITLE
Hybrid Weapon Falloff

### ISSUE THREAD

**Issue by HeitorLeal** [pyfa-org/Pyfa#2521]
## Bug Report
Hybrid Weapons are displaying wrong fallof

### Expected behavior:
7.805m falloff on pyfa

### Actual behavior:
4.020m falloff

### Detailed steps to reproduce:
Any hybrid weapon blaster/railgun small/medium/large shows smaller falloff

### Release or development git branch? Please note the release version or commit hash:
v2.53.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by Matthew-Amszynski** [comment]
07 I'm fairly new to programing and just started looking through here for things to work on just for practice. 

Can you provide the or a sample fit that causes this to happen for you ? 

also Pyfa seems to display the gun ranges like this  Opti + Fall off  where eve displays it as Opti , range within. If you take your Pyfa fit and add the Opty + Fall off from Pyfa it should match in game ?

[Small Hybrids In Pyfa](https://gyazo.com/dcbc9eb4437c0c34b3d2bcbb315147ad) adding this up you get 8,250 same as is displayed in eve

There's also a chance I don't understand your problem if that's the case please let me know so I can look more in to it.

**Comment by HeitorLeal** [comment]
It happens on all hybrid weapons no matter the size (small, medium, large) or type (railgun/blaster) the longer the falloff the bigger the gap between correct value and PyFa bellow I have it showing for my character skills both in Pyfa and ingame

[Kronos, Blaster Boi]

Multispectrum Energized Membrane II
Explosive Energized Membrane II
Magnetic Field Stabilizer II
Magnetic Field Stabilizer II
Magnetic Field Stabilizer II
Corpus X-Type Large Armor Repairer
Capacitor Power Relay II

Large Micro Jump Drive
Large Cap Battery II
Cap Recharger II
Cap Recharger II
Cap Recharger II

Neutron Blaster Cannon II
Neutron Blaster Cannon II
Neutron Blaster Cannon II
Neutron Blaster Cannon II
Bastion Module I
Imperial Navy Large EMP Smartbomb
Imperial Navy Large EMP Smartbomb

Large Nanobot Accelerator I
Large Auxiliary Nano Pump I


Hornet II x5
Caldari Navy Vespa x5
Hornet EC-300 x2

![image](https://github.com/pyfa-org/Pyfa/assets/6700513/41749279-6ee7-468c-aa60-6abcfd58ae1e)

**Comment by HeitorLeal** [comment]
Yeah I think I actualy missinterpreted the way fallloff is showing ingame vs pyfa, I think its actually right
