### ISSUE TITLE
ModuleNotFoundError: No module named 'roman'

### ISSUE THREAD

**Issue by clevNull** [pyfa-org/Pyfa#2522]
## Bug Report

pyfa v2.53.0
EVE Data Version: 2291895 (2023-06-13 18:48:15)

OS version: Linux-6.4.2-arch1-1-x86_64-with-glibc2.37
Python version: 3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429]
wxPython version: 4.2.0 (wxWidgets 3.2.2.1)
SQLAlchemy version: 1.3.24
Logbook version: 1.5.3
Requests version: 2.28.2
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "/usr/share/pyfa/pyfa.py", line 148, in <module>
    from gui.mainFrame import MainFrame
  File "/usr/share/pyfa/gui/mainFrame.py", line 47, in <module>
    from gui.characterEditor import CharacterEditor
  File "/usr/share/pyfa/gui/characterEditor.py", line 23, in <module>
    import roman
ModuleNotFoundError: No module named 'roman'

### Expected behavior:

start pyfa from konsole

### Actual behavior:

error

### Detailed steps to reproduce:

1. start konsole from Run
2. start pyfa from konsole

### Release or development git branch? Please note the release version or commit hash:

origin/master

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

6.4.2-arch1-1

### Other relevant information:

solved:

from file characterEditor.py
comment line 23:import roman

from file characterSelection.py
comment line 25:import roman

**Comment by DarkFenX** [comment]
It is specified in requirements.txt file. You don't run the program without dependencies installed
