### ISSUE TITLE
Feature request: update lang.pot for new annotated strings

### ISSUE THREAD

**Issue by zhaoweny** [pyfa-org/Pyfa#2529]
Hello, *long time no see*

I downloaded newest release for Pyfa, and I noticed that some strings are not translated. e.g. "Enforce Token Expiration" from [this](https://github.com/pyfa-org/Pyfa/blob/master/gui/builtinPreferenceViews/pyfaEsiPreferences.py#L37) file.

I dig into it and It seems `locale/lang.pot` is not updated and new annotated strings are not available for translation. Please consider updating `lang.pot`, instructions can be found at [locale/README.md](https://github.com/pyfa-org/Pyfa/blob/master/locale/README.md).

Thanks for your time reading this issue.

**Comment by zhaoweny** [comment]
That's fine. I guess I can dig into this and make a PR :).

**Comment by DarkFenX** [comment]
Im looking into it

**Comment by DarkFenX** [comment]
Fixed in 2d51da4d0210ba6fe5616b7ef2df989ceb56f218. Will keep it in mind when adding/changing msgids now
