### ISSUE TITLE
Precursor ships specific spaceship command skill is missing in RMB -> Change Ship Skills menu

### ISSUE THREAD

**Issue by ccloned** [pyfa-org/Pyfa#2530]
![image](https://github.com/pyfa-org/Pyfa/assets/34341105/caa83df7-d978-4d60-8880-33bf9f214b49)

I'm unable to change almost any precursor ship skill on the run, screenshot shows Leshak case.

**Comment by DarkFenX** [comment]
Leshak's bonuses affect only its gun. This menu is supposed to expose what affects specific item (leshak itself, or gun, or rep, etc).
