### ISSUE TITLE
Disruptive Lance Damage Graph

### ISSUE THREAD

**Issue by cyentw** [pyfa-org/Pyfa#2531]
## Bug Report
The disruptive lance when viewed under the damage graph is incorrect about the applied dps to a target profile, and overestimates the applied damage. It seems as if it thinks it has a signature radius of 2500, when it really has a signature radius of 10000. I tested this with a Karura shooting at a paladin with 4 huginn paints applied to it, which brings it up to a signature radius of 2.84k.

### Expected behavior:
The damage graph should show that the disruptive lance will only apply around 1/4 of the total dps.

### Actual behavior:
The damage graph shows that the disruptive lance will apply 100% of the total dps.

### Detailed steps to reproduce:
1. Create a lancer dreadnought fit 
2. Create a target profile fit that has a signature around 2500 (paladin with applied 4 huginn paints works)
3. Open the damage graph from the lancer fit and use the target fit as the damage profile
4. Observe the damage graph

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Karura, kurwa]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
‘Steel Yari’ Kinetic Disruptive Lance
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]

[Paladin, pal]

[Empty Low slot]
[Empty Low slot]
Dark Blood Large Armor Repairer
Dark Blood Large Armor Repairer
Imperial Navy Capacitor Power Relay
Imperial Navy Multispectrum Energized Membrane
Imperial Navy Multispectrum Energized Membrane

Imperial Navy Cap Recharger
Imperial Navy Cap Recharger
Republic Fleet Large Cap Battery
Republic Fleet Large Cap Battery

Bastion Module I
Centum C-Type Medium Remote Armor Repairer
Improved Cloaking Device II
Large EMP Smartbomb II
Mega Pulse Laser II
Mega Pulse Laser II
Mega Pulse Laser II
Mega Pulse Laser II

Large Capacitor Control Circuit II
Large Capacitor Control Circuit II

Republic Fleet Warrior x5
Hornet EC-300 x3
Vespa EC-600 x2

### Release or development git branch? Please note the release version or commit hash:
pyfa v2.53.0dev1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
Titan lances do the same thing
Screenshot of my damage graph https://i.imgur.com/ycUKJNp.png

**Comment by DarkFenX** [comment]
Yep, noticed it myself today, fixed already
