### ISSUE TITLE
evemarketer is now dead

### ISSUE THREAD

**Issue by xpapahet** [pyfa-org/Pyfa#2536]
Can we have https://evetycoon.com/docs for prices?

**Comment by adr1um** [comment]
+1

**Comment by DarkFenX** [comment]
Added in 6f3ab6cee8d3c2d36cedd2f8f98a125dafe1ea9c, will be included in next release. But eve-tycoon API forces us to make 1 request per item which is pretty bad. I'd advise to use fuzzwork.
