### ISSUE TITLE
Dependency update: linux release tracking issue

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#2549]
This issue is for tracking major issues which appeared with release of https://github.com/pyfa-org/Pyfa/releases/tag/v2.57.3

Report inability to launch pyfa, crashes, weird looking UI here.

Changes: dependencies updated, and AppImage build process was changed. Since it now includes minimal amount of dependencies (which was just enough to make it work on installations I had access to), it's very likely that AppImage won't launch on some installations due to missing libraries. Those issues are especially important to know.

**Comment by DarkFenX** [comment]
Ok im blind and confused libtiff versions (we bundle libtiff5, error is about libtiff6). Looks like something requests to load libtiff6, which is provided only by your system, and it tries to use libjpeg function which is not defined in bundled libjpeg version. So, need to figure out dependency chain, and bundle top-level library which needs that with AppImage

**Comment by wereii** [comment]
I do have `gdk-pixbuf2` installed, `/usr/lib/libtiff.so.6` is provided by `libtiff` package - so probably wxPython or one of it's dependencies in the appimage have been built with `libtiff.so.6` but the same lib on Arch does not conatain same symbols, that's a bummer.

You could try making a symlink in the appimage from libtiff.so.6 to libtiff.so.5 (hacky I know).

**Comment by DarkFenX** [comment]
I think it's error-prone. I will just bundle needed libs in appimage.

**Comment by DarkFenX** [comment]
@wereii try updated release please https://github.com/pyfa-org/Pyfa/releases/tag/v2.57.0dev2

**Comment by wereii** [comment]
https://termbin.com/jtia

Pyfa now starts but there are some errors right at the start.  
Just going thru the `File`, `Fit`, `Character`, ... tabs there is a lot of the `GLib-GObject-CRITICAL` errors generated, guessing something with the images in the menus.

And Opening `Global > Preferences` or `Editors > Character Editor` crashes pyfa with the: 

```
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
[1]    20009 IOT instruction (core dumped)  ./pyfa-v2.57.0dev2-linux.AppImage 2> log.txt
```

**Comment by DarkFenX** [comment]
Can you upload `/org/gtk/libgtk/icons/16x16/status/image-missing.png` somewhere?

**Comment by wereii** [comment]
This path does not exist  as is (there is no root `/org` directory by default on probably any linux).  
I did some searches for the file name but no hits both in pyfa files and outside, I will keep looking but I have to bolt now, be back in about an hour.

**Comment by wereii** [comment]
So according to this https://gitlab.gnome.org/GNOME/gimp/-/issues/7337 the path in question should be a "compiled" resource.

I had a look around for same errors and arrived to this thread https://github.com/bottlesdevs/Bottles/issues/230#issuecomment-1737248279 - trying the fix in linked comment (without the root path, that seems wrong):

`XDG_DATA_DIRS="$HOME/.local/share:/usr/local/share/:/usr/share/" ./pyfa-v2.57.0dev2-linux.AppImage`

I get pyfa running without any errors, the tabs that crashed the app before are gone, the icons in menus are back and they are even the right theme (instead of white windows I get same theme as other GTK apps). 

Though now I am unsure if this wasn't just a misconfiguration on my part.

**Comment by DarkFenX** [comment]
What's `XDG_DATA_DIRS`'s value without override?

**Comment by DarkFenX** [comment]
https://docs.gtk.org/gtk3/running.html those are the variables which count. Will play with those and ping you again once I have new build.

AppImage on my system ignores system theme setting btw, running it as `GTK_THEME=Adwaita:dark ./pyfa-v2.57.0dev2+5-g89f1e0a12-linux.AppImage` works fine. So there is definitely some env variable fine-tuning left to do.

**Comment by wereii** [comment]
> What's XDG_DATA_DIRS's value without override?

Empty. According to a quick search apps can fallback to a given default but not every app does? I have not noticed any problems with other gtk apps without this value.

The whole XDG is notoriously confusing, at least from my experience. 

There seems to be some talk about defaulting or not for these variables: https://github.com/AppImage/AppImageKit/issues/481  

So as you say, in the entry script of the appimage, you could do:

```sh
export XDG_DATA_DIRS="${XDG_DATA_DIRS:-default_value_here}" 
```
this should make sure the variables are always set to either user or default value.
(the "set default" syntax is explained here https://stackoverflow.com/a/2013589/588179)

**Comment by DarkFenX** [comment]
will it work fine with base empty value though? (when value starts from `:`, not first path, I never ran into this situation)

**Comment by wereii** [comment]
Ah, I was thinking that the entry point of the AppImage could be a shell script exporting the vars then `exec`ing `python3.11 ... .../.../pyfa.py` but I see there is now `AppImageBuilder.yml` - not familiar with that one.

I can handle "fixing" XDG_ vars for Arch in the AUR package so I guess it's not really required (except as you said, it seems to ignore gtk theme without it?)

**Comment by DarkFenX** [comment]
If you think your OS has nothing to do with setting those variables, I still might try to play with setting them in `AppImageBuilder.yml`. But if I do that, they will be pointing to bundled resources, not to system ones (since, well, system has to handle that). All I need to do is to find a way to append bundled paths to variable, no matter if it's defined or not, which will also preferably work in env variables section w/o extra hacks.

**Comment by wereii** [comment]
My current theory is that apps using these vars should be ready to use the freedesktop defaults if they are unset (which in this case actually applies to the deps of pyfa, wxPython and lower) but I do not have a concrete information to show so for now let's leave it out, but if someone else with different distro arrives here then it should be set in pyfa somewhere.

**Comment by wereii** [comment]
https://wiki.archlinux.org/title/XDG_Base_Directory
this seems to source the information from here (which is the offical doc for XDG) https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by DarkFenX** [comment]
Ok so let's say I want to do following things:

1) If `XDG_DATA_DIRS` is empty, set it to `/usr/local/share:/usr/share`
2) No matter if it was empty or not, append `:${APPDIR}/usr/share` to it

The issue is, I have only 1 step per variable to do that (AppDir/runtime/env is a YAML mapping), is there a way to do that in bash?

**Comment by wereii** [comment]
in bash yes, 

```sh
# set default if not exists
XDG_DATA_DIRS="${XDG_DATA_DIRS:-/usr/local/share/:/usr/share/}" 
# append AppImage location as fallback
XDG_DATA_DIRS="$XDG_DATA_DIRS:$APPDIR/usr/share"
# set globally
export XDG_DATA_DIRS
```

**Comment by DarkFenX** [comment]
Well, it has to be a one-liner, I can't do multiple steps in here: https://github.com/pyfa-org/Pyfa/blob/346184d06a20a8b48a85192c159c94195e8f7168/dist_assets/linux/AppImageBuilder.yml#L63

anyway, for now I think setting default should be good (as long as it's interpreted properly), please check this build: https://ci.appveyor.com/project/pyfa-org/pyfa/builds/48687116/job/rec55i5t63sspxr9/artifacts

**Comment by wereii** [comment]
Ah, tried downloading the first one but my browser crashed before it got it whole and now I am getting error 
`{"message":"Artifacts download limit (1024 MB/day) exceeded."}`

**Comment by DarkFenX** [comment]
It's probably project-based, but yes. Idk i can get a build out (via making a draft release) but no idea where to upload it

**Comment by wereii** [comment]
I've sent you email (to the address on your gh profile) I could get some storage for you to upload to in few minutes if the wormhole approach does not work.

**Comment by DarkFenX** [comment]
But now it also crashes on my laptop:
```
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted
```

**Comment by DarkFenX** [comment]
Judging by this file: https://github.com/AppImageCrafters/appimage-builder/blob/main/appimagebuilder/modules/setup/apprun_2/apprun2.py

appimage-builder doesn't use bash to interpret env variables. For the variable in question it takes its value as string in `parse_env_input()` (with variable substitution before that, i think), then in `_configure_runtime_environment()` it just sets them. There is no extra fancy stuff.

In the latter function btw there is a block:
```
        global_env = Environment(
            {
                "APPIMAGE_UUID": bundle_id,
                "XDG_DATA_DIRS": [
                    "$APPDIR/usr/local/share",
                    "$APPDIR/usr/share",
                    "$XDG_DATA_DIRS",
                ],
                "XDG_CONFIG_DIRS": ["$APPDIR/etc/xdg", "$XDG_CONFIG_DIRS"],
                "APPDIR_LIBRARY_PATH": self._get_appdir_library_paths(),
                "PATH": [*self._get_bin_paths(), "$PATH"],
            }
        )
```
Which means that system default paths are not used by default (for bundled software it sets paths, so it never receives empty variable; but even if it was empty, bundled software doesn't know much about system paths i imagine), which also means that paths need to be set explicitly. This seems to be a bug in appimage-builder really, since it needs to add system default paths if the variable is empty.

For now, I will remove variable override, and add issue in the appimage-builder repo.

**Comment by DarkFenX** [comment]
Theoretically we can take definition of `XDG_DATA_DIRS` as specified in `_configure_runtime_environment()`, but also add system paths to it (to make sure they are always there, even if duplicated).

**Comment by wereii** [comment]
Yes, confirming it now works without crashes or the errors generated into terminal.  :tada:

**Comment by willl03** [comment]
Hi, when I try to run pyfa in WSL 2 Ubuntu 22.04 it gives the following errors:

**Comment by DarkFenX** [comment]
We don't package all the dependencies in appimage, some are still provided by the system. In this case it seems that libgdk doesn't have its dependency bundled in the appimage, and it can't find needed functionality in your system libraries. But this is weird because ubuntu 22.04 is used as build system, so idk why this mismatch happens.

Dependency of the package: https://packages.ubuntu.com/jammy/libgtk-3-0
A bit more useful context: https://github.com/libsdl-org/SDL/issues/5376#issuecomment-1075589041

@willl03 could you update your system (one of libwayland-* libs) and see if issue persists?

**Comment by engineer1109** [comment]
> Hi, when I try to run pyfa in WSL 2 Ubuntu 22.04 it fails with the following error - np before the dependency update.
> 
> ./pyfa.AppImage Traceback (most recent call last): File "/tmp/.mount_pyfa.AHK2JFE/opt/pyfa/pyfa.py", line 27, in import config File "/tmp/.mount_pyfa.AHK2JFE/opt/pyfa/config.py", line 4, in import wx File "/tmp/.mount_pyfa.AHK2JFE/usr/local/lib/python3.11/dist-packages/wx/**init**.py", line 17, in from wx.core import * File "/tmp/.mount_pyfa.AHK2JFE/usr/local/lib/python3.11/dist-packages/wx/core.py", line 12, in from ._core import * ImportError: /tmp/.mount_pyfa.AHK2JFE/usr/lib/x86_64-linux-gnu/libgdk-3.so.0: undefined symbol: wl_proxy_marshal_flags

Me too

**Comment by DarkFenX** [comment]
Let's use #2600 for marshal_flags issue. I am closing this generic one.
