### ISSUE TITLE
Error: Bitmap(): arguments did not match any overloaded call

### ISSUE THREAD

**Issue by Tetractys** [pyfa-org/Pyfa#2551]
## Bug Report
Traceback (most recent call last):
  File "/tmp/.mount_pyfa-vVLCopz/opt/pyfa/gui/chrome_tabs.py", line 791, in OnSize
    self.UpdateSize()
  File "/tmp/.mount_pyfa-vVLCopz/opt/pyfa/gui/chrome_tabs.py", line 800, in UpdateSize
    self.AdjustTabsSize()
  File "/tmp/.mount_pyfa-vVLCopz/opt/pyfa/gui/chrome_tabs.py", line 1367, in AdjustTabsSize
    tab.SetSize((tabWidth, self.height))
  File "/tmp/.mount_pyfa-vVLCopz/opt/pyfa/gui/chrome_tabs.py", line 423, in SetSize
    self.InitTab()
  File "/tmp/.mount_pyfa-vVLCopz/opt/pyfa/gui/chrome_tabs.py", line 482, in InitTab
    self.ComposeTabBack()
  File "/tmp/.mount_pyfa-vVLCopz/opt/pyfa/gui/chrome_tabs.py", line 517, in ComposeTabBack
    bk_bmp = wx.Bitmap(self.tab_width, self.tab_height)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Bitmap(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
  overload 4: argument 1 has unexpected type 'float'
  overload 5: argument 1 has unexpected type 'float'
  overload 6: argument 1 has unexpected type 'float'
  overload 7: argument 1 has unexpected type 'float'
  overload 8: argument 1 has unexpected type 'float'
  overload 9: argument 1 has unexpected type 'float'
  overload 10: too many arguments

### Expected behavior:
Program opening

### Actual behavior:
Generate a window with the unexpected issue report

### Release or development git branch? Please note the release version or commit hash:
Release

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
pyfa v2.57.0dev2
EVE Data Version: 2438956 (2023-11-30 12:44:04)

Arch Linux - testing branch
OS version: Linux-6.6.4-arch1-1-x86_64-with-glibc2.38
Python version: 3.11.6 (main, Oct 23 2023, 22:48:54) [GCC 11.4.0]
wxPython version: 4.2.1 (wxWidgets 3.2.2.1)
SQLAlchemy version: 1.4.50
Logbook version: 1.7.0.post0
Requests version: 2.31.0
Dateutil version: 2.8.2

### Other relevant information:
Ask me.

**Comment by DarkFenX** [comment]
Which interface scaling factor do you have?

The reason I ask is I don't see any operation in chrome tabs which could end up in a float number. I suspect some getter returns tab width which is float, and this float "infects" other ints.

Anyway, I made sure we don't pass floats in f8f01cd63cb0a7a4d6729867437e5ac4381685d9. Will be fixed in next release.

**Comment by DarkFenX** [comment]
Fixed in v2.57.1
