### ISSUE TITLE
Windows Defender found pyfa.exe 2.57.2 malicious 

### ISSUE THREAD

**Issue by raimondsL** [pyfa-org/Pyfa#2553]
[https://www.virustotal.com/gui/file/a1e066ee7c07b7d37b9b2573e7f0aa994ea43c0918b8a6995f8dfa02aac94398/details](https://www.virustotal.com/gui/file/a1e066ee7c07b7d37b9b2573e7f0aa994ea43c0918b8a6995f8dfa02aac94398/details)

**Comment by ktwb** [comment]
Yup, same here, newest version of pyfa is a problem...

**Comment by DarkFenX** [comment]
More context: https://github.com/pyfa-org/Pyfa/issues/2550

Surprisingly enough, 3 more antiviruses which reported `pyfa-v2.57.2-win.zip` okay, report `pyfa.exe` which is sitting in the zip as malicious (Bkav Pro, SecureAge, Zillya):

- .exe: https://www.virustotal.com/gui/file/acf94f756edd701209b9e2ebe3678275a96e5058d9abf119a4175fb5bc51ad4e
- .zip: https://www.virustotal.com/gui/file/8c887e9926dfc0611c18180830ae832587faa9b80600c8e3ac97f3de2ecb5269?nocache=1

Report this as false positive, please. I will try reverting pyinstaller another step, 6.1.0 -> 6.0.0 (thought when it's just Avast/AVG report false positive is ok, but apparently windows defender scan isn't part of virustotal anymore).

**Comment by DarkFenX** [comment]
Also make a screenshot of what exactly windows defender says.

**Comment by DarkFenX** [comment]
Yep. I am waiting for a corpmate to finish windows update to give me exact this info.

So, the windows defender issue is solved by windows update.

**Comment by raimondsL** [comment]
> Yep. I am waiting for a corpmate to finish windows update to give me exact this info (if it resolves the issue or not).
> 
> So, the windows defender issue is solved by windows update.
> 
> edit: or am I reading it wrong and windows update didn't exactly help? "Threat restored" is confusing

It was me restoring the threat.

**Comment by DarkFenX** [comment]
Ok, so just to confirm, it was detected as a threat despite latest update installed, and "restoring" threat means telling system it's not a virus (= false positive)?

(i am not familiar with terms or interface of windows defender)

**Comment by raimondsL** [comment]
> Ok, so just to confirm, it was detected as a threat despite latest update installed, and "restoring" threat means telling system it's not a virus (= false positive)?
> 
> (i am not familiar with terms or interface of windows defender)

It means it's still a threat. I just put it back

**Comment by DarkFenX** [comment]
Ok thanks.

**Comment by DarkFenX** [comment]
Changed pyinstaller version in fc436912754bd7d4ef86e6ff038f1eaed5a78cc6, please try this build and see if windows defender complains about it: https://ci.appveyor.com/project/pyfa-org/pyfa/builds/48713422/job/p3y42tsnfi3e3j5w/artifacts

If it doesn't, I will make a release

**Comment by raimondsL** [comment]
Windows Security is dumb, but it worked for me. i'd recommend at least one more confirmation

**Comment by DarkFenX** [comment]
There already were reports from pyinstaller side, e.g. this: https://github.com/pyinstaller/pyinstaller/issues/7967#issuecomment-1773906836

And pyinstaller version is all that matters. Windows defender doesn't check pyfa code i think. I will wait for confirmation from my corpmate and will make a release.

**Comment by DarkFenX** [comment]
https://github.com/pyfa-org/Pyfa/releases/tag/v2.57.3
