### ISSUE TITLE
When using Color Slot mode, the colors do not connect naturally.

### ISSUE THREAD

**Issue by winter0729** [pyfa-org/Pyfa#2554]
## Bug Report
When using Colot Slot, the colors do not connect naturally, and the color breaks for each column.

### Expected behavior:
Colors should be naturally connected.
This worked correctly in version 2.56.0.
![image](https://github.com/pyfa-org/Pyfa/assets/42881884/15c16d75-d9de-497e-ad81-e8a9c42aa059)

### Actual behavior:
The color breaks for each column.
Starting with version 2.57.0, the following symptoms occur

![image](https://github.com/pyfa-org/Pyfa/assets/42881884/5b913f84-de04-4db2-a19a-98030dbe35d9)

### Detailed steps to reproduce:
Edit-> Prefs-> turn on color fitting view by slot (from above 2.57.0 or later.)

### Release or development git branch? Please note the release version or commit hash:
Release 
b5e77415cfd0e873eb4e44ae3ca6ef349f4ef304
0dc2632fc41efae726e22352a9a65e736a6b0c5f

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 11

**Comment by DarkFenX** [comment]
On linux, they do connect. I will look into possible reasons (we won't revert to older wx, but possibly newer wx exposes a way to control it), but ultimately someone with windows will have to check and/or debug.

**Comment by DarkFenX** [comment]
This is what pyfa is using for fitting view: https://docs.wxpython.org/wx.ListCtrl.html (with style `wx.LC_REPORT`).

**Comment by DarkFenX** [comment]
@winter0729 https://ci.appveyor.com/project/pyfa-org/pyfa/builds/48717843/job/in8ux3r2l71ne6wy/artifacts try this build

**Comment by winter0729** [comment]
It works, Thank you.
![image](https://github.com/pyfa-org/Pyfa/assets/42881884/51fca6f6-913c-4464-b233-f3b5ed346661)

**Comment by DarkFenX** [comment]
Cool. Will be included in the next release
