### ISSUE TITLE
MacOS DPS values are higher than in Windows version

### ISSUE THREAD

**Issue by Skybladev2** [pyfa-org/Pyfa#2570]
## Bug Report

MacOS Pyfa shows higher DPS values than Windows version.

For instance, if we fit Thrasher with 7 200mm AutoCannon II, Hail S, Character All 5, no implants or boosters, MacOS version shows 330 DPS:
![pyfa macos](https://github.com/pyfa-org/Pyfa/assets/548735/2d0a41b5-fa1c-4860-986b-68890dcd1b3c)

Windows version shows 305 DPS:
![pyfa windows](https://github.com/pyfa-org/Pyfa/assets/548735/0f180e9d-298e-4fa6-963a-a11f9bc95f7b)

### Expected behavior:
DPS values match for each version

### Actual behavior:
MacOS DPS is 330 while Windows DPS is 305

### Detailed steps to reproduce:
* Create new fit for Thrasher
* Add 7 200mm AutoCannon II
* Add charges Hail S
* Select Character "All 5"

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Thrasher, Thrasher fit copy]

[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

200mm AutoCannon II, Hail S
200mm AutoCannon II, Hail S
200mm AutoCannon II, Hail S
200mm AutoCannon II, Hail S
200mm AutoCannon II, Hail S
200mm AutoCannon II, Hail S
200mm AutoCannon II, Hail S
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
v2.57.3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
MacOS Sonoma 14.2.1, Windows 10

**Comment by fruitchewy** [comment]
tested 2.57.3 on windows and mac as well as latest commit on mac and I'm seeing 314 on all which seems to be correct

**Comment by DarkFenX** [comment]
One has "factor reload" turned on, another does not. Right-click DPS pane to change it.

Shit UI not to have an indicator for that, I know.
