### ISSUE TITLE
Simulating extreme neut pressure, when only inject tanking is possible

### ISSUE THREAD

**Issue by Luckbox777** [pyfa-org/Pyfa#2571]
Hi, I'm wondering if it's possible to simulate situation, frequently occurring during capital fights, when you are neut pressured by bunch of Bhaals with staggered neuts and can activate reppers only by injecting cap boosters, so only one repper cycle is possible per one injection.
It's hard to compare different fits for that particular situation, unless I'm missing something. I'd appreciate any info on that. Thanks

**Comment by Luckbox777** [comment]
On the same note: is it possible to chance attribute of the module to one outside the range allowed by mutaplasmids? For example, changing default 10s shield booster cycle time to 12s

**Comment by DarkFenX** [comment]
I have some experience in this (did many AT fits and quite a few of fax/dread fits for neut rich metas) and I am doing it the manual way. Rough algorithm is:

- you check how many injections you get per minute with reload considered and without it
- multiply HP you can get per cycle * resist multiplier * injects per second (with or without reload, depending on which number you need)
- with the number you received for non-reload tanking, make sure you don't die during downtime (during cap booster or ASB reload), which can happen on dual-rep ninazus or non-CSE minokawas

The thing is, your scenario is *very* specific, while whole set of similar scenarios is much more broad. For example assuming only injects give you cap, this is very fax/dread-centric scenario. There are others as well:

- incoming cap transfers to pulse XLASB in the AT
- incoming cap transfers to pulse RRs on guardians/basis/nestor
- incoming cap transfers to pulse anything on other ships, e.g. guns on an abaddon

To support proper generic case, you need to write fully fledged simulator with lots of controls (e.g. user needs control over when to inject - in case heated cap booster cycles faster than reps, how cap transfers are staggered, what to do when you have multiple mods with different cycle times, do you keep your hardener up during cap booster down time (e.g. single invuln on a minokawa using a nosf - does it cycle properly, do you have proper target without neut resist?)). Those are very specific scenarios, and I do think it's better to let people those specific scenarios somewhat manually.

As for your second question - there is an override editor, you can change attributes at will there.

**Comment by DarkFenX** [comment]
Forgot to mention that under *extreme* neut pressure you might fail to activate mods even under injection (tested with 5 talisman small neut curses doing injection of small charge followed by activation of a shield hardener like 10 years ago, it wasn't reliable - so nobody guarantees that server won't process a bhaal neut between your cap injection and rep activation)

**Comment by Luckbox777** [comment]
> Forgot to mention that under _extreme_ neut pressure you might fail to activate mods even right after injection (tested with 5 talisman small neut curses doing injection of small charge followed by activation of a shield hardener like 10 years ago, it wasn't reliable - so nobody guarantees that server won't process a bhaal neut between your cap injection and rep activation)

Appreciate the info! Very good points o7
