### ISSUE TITLE
Linux AppImage v2.57.3 - missing libpcre2-32.so.0:

### ISSUE THREAD

**Issue by rupi-lol** [pyfa-org/Pyfa#2572]
Starting the AppImage under Debian Bookworm gets the following:

```
ImportError: libpcre2-32.so.0: cannot open shared object file: No such file or directory
```

**Comment by rupi-lol** [comment]
Installing it locally resolves this, but release notes stated you wanted the report. (Thx for providing the AppImage, it makes live easier)

**Comment by DarkFenX** [comment]
Seems to be rather small, can bundle it as well. Added it to bundle in 69ef7825af7ec0502de9efc0fea8a9420cb5f9a1, let's pray it doesn't break anything.
