### ISSUE TITLE
Mercoxic calculation does not account for rigs

### ISSUE THREAD

**Issue by TinkeringGoblin** [pyfa-org/Pyfa#2577]
## Bug Report
as the title said when looking at the details on the mercoxic mining, it does not account for a mercoxic rig.

### Expected behavior:
expected mercoxic rig to increase mining yeild 

### Actual behavior:
no increase

### Fits involved in EFT format (Edit > To Clipboard > EFT):

[Hulk, Merc Hulk T2]

Mining Laser Upgrade II
Mining Laser Upgrade II
Mining Laser Upgrade II

Large F-S9 Regolith Compact Shield Extender
Multispectrum Shield Hardener II
Survey Scanner II
Domination EM Shield Amplifier

Modulated Deep Core Strip Miner II, Mercoxit Asteroid Mining Crystal Type B II
Modulated Deep Core Strip Miner II, Mercoxit Asteroid Mining Crystal Type B II

Medium Mercoxit Mining Crystal Optimization I
Medium Ancillary Current Router II

Acolyte II x5
Mining Drone I x5

Eifyr and Co. 'Alchemist' Gas Harvesting GH-805
Inherent Implants 'Highwall' Mining MX-1005
### Release or development git branch? Please note the release version or commit hash:

2.57.3
### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

windows

**Comment by DarkFenX** [comment]
Fixed in b959d9dd07fa25caf0ba409d6c07e8ea83538178
