### ISSUE TITLE
Not allowing multiple modules of Scan Array type in mid slots.

### ISSUE THREAD

**Issue by miroslav77** [pyfa-org/Pyfa#2580]
## Bug Report
In-game I can fit multiple modules of Scan Acquisition Array, Scan Pinpointing Array, Scan Rangefinding Array, but in the Pyfa client I am still limited to 1 only.

### Expected behavior:
Allow fitting multiple modules of the type in mid slots.

### Actual behavior:
Only one module of the type is allowed.

### Detailed steps to reproduce:
Start fitting a ship and try to put multiple modules like Scan Rangefinding Array

### Release or development git branch? Please note the release version or commit hash:
release

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 11

### Other relevant information:
v2.57.3

**Comment by DarkFenX** [comment]
Tried fitting it in game:

> 15:38:31	Hint	You're unable to fit Scan Acquisition Array II to Pacifier. You can only fit 1 of type Scanning Upgrade Time but already have 1.

Scan Acquisition Arrays are limited, the rest are not. This seems to be consistent with pyfa. If you can't fit 2+ rangefinding/pinpointing, feel free to reopen.
