### ISSUE TITLE
Colour mode on high/med/low etc racks is broken

### ISSUE THREAD

**Issue by TFT-Ben** [pyfa-org/Pyfa#2585]
Colour mode now adds extremely dull colours to the window that makes the window illegible

**Comment by TFT-Ben** [comment]
![image](https://github.com/pyfa-org/Pyfa/assets/50218131/d5025e09-60a2-4257-ae39-722f81c9c517)
screenshot for reference

**Comment by DarkFenX** [comment]
Which OS is it, and do you use dark OS theme?

**Comment by TFT-Ben** [comment]
Win 10, systemwide dark mode is enabled
![image](https://github.com/pyfa-org/Pyfa/assets/50218131/614590bc-b15e-4e24-9fa7-b0e6ef38a2be)

**Comment by DarkFenX** [comment]
That explains it. Fixed in bb53e75bfe0f02452658413a5de90b97b1e07a89, will try to make new release soonish (but not now, in case there are more bugs reported). Please disable rack colors as a temporary measure.

**Comment by TFT-Ben** [comment]
Have done - no worries, thanks!
