### ISSUE TITLE
Can't open character editor in China

### ISSUE THREAD

**Issue by huxim** [pyfa-org/Pyfa#2587]
## Bug Report
pyfa v2.58.0
EVE Data Version: 2497879 (2024-02-20 20:05:56)

OS version: Windows-10-10.0.19045-SP0
Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
wxPython version: 4.2.1 (wxWidgets 3.2.2.1)
SQLAlchemy version: 1.4.50
Logbook version: 1.7.0.post0
Requests version: 2.31.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "gui\mainFrame.py", line 444, in OnShowCharacterEditor
  File "gui\auxWindow.py", line 63, in openOne
  File "gui\characterEditor.py", line 159, in __init__
  File "gui\characterEditor.py", line 810, in __init__
  File "gui\characterEditor.py", line 839, in ssoListChanged
  File "gui\characterEditor.py", line 843, in charChanged
  File "service\esi.py", line 33, in getInstance
  File "service\esi.py", line 40, in __init__
  File "service\esiAccess.py", line 94, in __init__
  File "requests\models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://login.eveonline.com/.well-known/oauth-authorization-server

### Expected behavior:
character editor should be opened

### Actual behavior:
character editor can't open

### Detailed steps to reproduce:
1. Use China IP
2. open character editor
3. error will appear

### Release or development git branch? Please note the release version or commit hash:
pyfa v2.58.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
OS version: Windows-10-10.0.19045-SP0

### Other relevant information:
If I use vpn/proxy, character editor will open properly.

**Comment by bilegole** [comment]
和pyfa本身没有关系，这里是pyfa试图访问eve的web服务，但由于中国大陆的防火墙存在制止了你的电脑到eve服务的连结。

**Comment by huxim** [comment]
> 和pyfa本身没有关系，这里是pyfa试图访问eve的web服务，但由于中国大陆的防火墙存在制止了你的电脑到eve服务的连结。

不,是eve服务器限制了中国IP:
HTTPError: 403 Client Error: Forbidden for url:

**Comment by bilegole** [comment]
那你找pyfa开发组也没用啊，pyfa和eve不是一起的

**Comment by huxim** [comment]
> 那你找pyfa开发组也没用啊，pyfa和eve不是一起的

不是,哪怕我没网,也不应该阻止我打开本地应用的窗口啊

**Comment by DarkFenX** [comment]
I agree character window shouldn't be broken due to network failures.

Does it open if you disable network (in preferences > enable network, try disable all network, or EVE servers part)?

**Comment by huxim** [comment]
> I agree character window shouldn't be broken due to network failures.
> 
> Does it open if you disable network (in preferences > enable network, try disable all network, or EVE servers part)?

Still can't open
