### ISSUE TITLE
Colors in dark mode are still hard to read in MacOS (11.7.10)

### ISSUE THREAD

**Issue by JohnnyFonseca** [pyfa-org/Pyfa#2593]
the last update made so it is now very good on the fitting window, but it still hard to read on the market part of the UI as you can check on the Screenshot bellow:

![Captura de Tela 2024-02-25 às 10 52 05](https://github.com/pyfa-org/Pyfa/assets/160975466/65e017ff-1de6-45bf-9713-3a6e14bd1f53)

**Comment by DarkFenX** [comment]
I don't see pyfa overriding any of that. Seems like it's a wxpython issue, so no promises to fix it in short term

**Comment by DarkFenX** [comment]
Fixed in 82a912858f1e558b38a2a2869e8600db5e27563e
