### ISSUE TITLE
NotImplementedError python stacktrace upon app launch (Linux version)

### ISSUE THREAD

**Issue by cdcooksey** [pyfa-org/Pyfa#2604]
## Bug Report

On two different Linux machines, I receive this stracktrace when launching Pyfa

```
pyfa v2.58.1
EVE Data Version: 2497879 (2024-02-20 22:35:56)

OS version: Linux-6.8.0-76060800daily20240311-generic-x86_64-with-glibc2.38
Python version: 3.11.9 (main, Nov 10 2011, 15:00:00) [GCC 13.2.0]
wxPython version: 4.2.1 (wxWidgets 3.2.2.1)
SQLAlchemy version: 1.4.50
Logbook version: 1.7.0.post0
Requests version: 2.31.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/wx/core.py", line 3427, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/pyfa/gui/mainFrame.py", line 245, in ShowUpdateBox
    with UpdateDialog(self, release, version) as dlg:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/pyfa/gui/updateDialog.py", line 65, in __init__
    self.browser = wx.html2.WebView.New(self)

NotImplementedError
```

### Fits involved in EFT format (Edit > To Clipboard > EFT):

No fits, tried on new install with fresh Pyfa install. 
![Screenshot from 2024-04-21 22-04-38](https://github.com/pyfa-org/Pyfa/assets/1116789/0d11cb5e-9f06-49bc-ae98-4e22c40ab06a)

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Affects Pop OS & Linux Mint. Latest desktop release for both.

**Comment by DarkFenX** [comment]
Are you running from source, or using provided appimage?

Either way, it is an issue with wxpython (it was compiled without html support), see more details [here](https://stackoverflow.com/questions/66283225/why-is-it-not-available-in-centos-wx-html2-webview-control). If you are running from source, you have to fix it. If from appimage, I need to review why bundled wx doesn't have it.

(judging by traceback, looks like you are running from source, though)

**Comment by DarkFenX** [comment]
`configure: WARNING: WebKit not available, disabling wxWebView`

**Comment by DarkFenX** [comment]
Installing `libwebkit2gtk-4.1-dev` fixed it for me
