### ISSUE TITLE
copy to clipboard > ESF returns error

### ISSUE THREAD

**Issue by brjens** [pyfa-org/Pyfa#2613]
## Bug Report
When I copy to the clipboard, and then select ESF I get this response:
pyfa v2.58.3
EVE Data Version: 2563119 (2024-04-29 17:47:50)

OS version: Windows-10-10.0.19045-SP0
Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
wxPython version: 4.2.1 (wxWidgets 3.2.2.1)
SQLAlchemy version: 1.4.50
Logbook version: 1.7.0.post0
Requests version: 2.31.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "gui\copySelectDialog.py", line 161, in Validate
  File "gui\copySelectDialog.py", line 208, in exportEfs
  File "service\port\efs.py", line 705, in exportEfs
  File "service\port\efs.py", line 654, in getShipSize
  File "service\port\efs.py", line 650, in <lambda>
AttributeError: 'NoneType' object has no attribute 'ID'

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Retriever, *Simulated Retriever Fitting]

Mining Laser Upgrade II
Mining Laser Upgrade II
Mining Laser Upgrade II

Multispectrum Shield Hardener II
ML-3 Scoped Survey Scanner

Modulated Strip Miner II
Modulated Strip Miner II

Medium EM Shield Reinforcer I
Medium EM Shield Reinforcer I
Medium Core Defense Field Extender I

### Release or development git branch? Please note the release version or commit hash:
pyfa v2.58.3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win 10 I used the win exe to install

### Other relevant information:
I reinstalled pyfa, and no difference

**Comment by brjens** [comment]
ship type might be an explanation. When I did one of my reinstalls I tried to export a navy catalyst fitting and it worked.

**Comment by kgasiorowski** [comment]
Indeed - all of the other ship types worked. If you try to export any "Industrial" ship type, it throws an exception. Try exporting a Prowler or Orca, for example, I bet you'll get the same results. Don't need to fit any modules or anything either.
