### ISSUE TITLE
Please sign source code tag in Git

### ISSUE THREAD

**Issue by AdamMajer** [pyfa-org/Pyfa#262]
Currently tags in git repository are not signed. I think it would be a benefit if the tags were cryptographically signed. You can do that with `git tag -s <tagname>`

**Comment by blitzmann** [comment]
We use GitHub's web interface to create tags when we make a release, so it's not something that we do at the command level. What are the benefits of doing such a thing?

**Comment by AdamMajer** [comment]
Signed tag essentially signs the entire archive as being authentic. No one can tamper with it.

I've noticed that it is possible to sign the tag, and then make a release with the GitHub interface. They do not seem to interfere. For example, I've made a Debian package for Pyfa and I was able to use a signed tag for that without problems.

  https://github.com/AdamMajer/Pyfa/releases

On another note, if you guys want, I can provide Debian package files for your releases.

**Comment by DarkFenX** [comment]
I'm using git command line interface to create the tag. Will look into signing it next time i'm doing a release.

Regarding debian releases - would be cool, however i am not sure how we can integrate it to release everything together.

**Comment by blitzmann** [comment]
Hey @AdamMajer,

With the v1.19.0 release, I went ahead and set up a key pair and signed the tag. Public key can be found here:

https://pgp.mit.edu/pks/lookup?op=vindex&search=0xA0702F954C53D05F

Maybe you can walk me through what else I can do? I know that keys are based on a web of trust, but I don't have any signatures on my public key considering it's brand new (and also that I'm somewhat new to actually using PK crypto). Let me know =)

**Comment by AdamMajer** [comment]
Thank you very much! That's helpful.

Web of trusts is not as important here as just keeping that key consistent. So if you sign with same key going forward, that key is already imported for me, so I can check signatures and immediately know that next version was prepared/signed by same person (or at least same key). For example, no one at github can impersonate you anymore.

It's just a consistency check that makes tampering with repositories nearly impossible.

**Comment by blitzmann** [comment]
Thanks. Lets hope I just remember to sign it for future releases. Been thinking of making a release script anyway that would automatically upload to github, so if that happens I can just integrate it with that hopefully. =)
