### ISSUE TITLE
[Nevermind] Implants for fit deleted when "Use Character Implants" is chosen

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [pyfa-org/Pyfa#2639]
** Never mind** The feature works as expected, I just messed up the input, and didn't see the implants.
*(If its possible to delete this issue, go ahead and do it.)*

Where a fit includes implants when copied into Pyfa, the implants are permanently removed from the fit once the "Use Character Implants" option is selected.

Why aren't the implants 'disabled', like boosters are?

Unless I'm missing something, the problem with the current approach is that one cannot compare 'bare-bone' fits with other ship configurations.

**Comment by x4132** [comment]
To delete the issue, mark it as closed
