### ISSUE TITLE
Request: improved tooltip description for Radius value in Target Profile editor

### ISSUE THREAD

**Issue by vahlback** [pyfa-org/Pyfa#2640]
What this value did was a complete mystery to me so I had to dig through the code to find out. Suggest something like this: 

> Radius
The radius of the sphere that represents a ship/drone in space. Affects range calculations.

Looks like `gui.targetProfileEditor.TargetProfileEntityEditor` row 126, I'd try to make a PR for it myself but these text strings seems to be present in multiple files so I wasn't sure if I'd be doing it right

**Comment by DarkFenX** [comment]
Changed, thanks for suggestion
