### ISSUE TITLE
[BUG] Incorrect Value for F-89 Compact Signal Amplifier

### ISSUE THREAD

**Issue by ZaxLofful** [pyfa-org/Pyfa#2642]
## Bug Report

The value that is used in calculations from CPU for the item "F-89 Compact Signal Amplifier" are incorrect. In the stats viewer it says it uses 16 CPU (which from in-game is correct), but then it only adds 12 to the CPU in the fitting GUI.

### Expected behavior:

It should add 16 CPU to the CPU total in the GUI.

### Actual behavior:

It only adds 12 (which is the value of different metas of the Signal Amp [Sentient Signal Amplifier])

### Detailed steps to reproduce:

Swap the variations of the Signal Amplifier and it'll show incorrect values when swapped to "F-89 Compact Signal Amplifier".

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Vexor Navy Issue, Security runner]

Drone Damage Amplifier II
Drone Damage Amplifier II
Damage Control II
Multispectrum Energized Membrane II
F-89 Compact Signal Amplifier
'Meditation' Medium Armor Repairer I

50MN Quad LiF Restrained Microwarpdrive
Stasis Webifier II
Medium Cap Battery II
Tracking Computer II

Heavy Neutron Blaster II
Heavy Neutron Blaster II
Heavy Neutron Blaster II
Drone Link Augmentor II

Medium Explosive Armor Reinforcer II
Medium Capacitor Control Circuit II
Medium Semiconductor Memory Cell II

Acolyte II x10
Hobgoblin II x10
Hammerhead II x5
Ogre II x2

Navy Cap Booster 50 x184
Federation Navy Antimatter Charge M x5240
Federation Navy Iron Charge M x5000
Optimal Range Script x2
Tracking Speed Script x1

### Release or development git branch? Please note the release version or commit hash:
Release Branch

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 11

### Other relevant information:

![In-Game Description](https://github.com/user-attachments/assets/caec08eb-62f4-46b5-8cfc-51a7069d6971)
![Without the Module](https://github.com/user-attachments/assets/e2fc1c53-d9f5-40a6-aa00-78fca62cea52)
![With the Module](https://github.com/user-attachments/assets/8765e006-79bd-493a-b438-06f4befa53cd)

**Comment by DarkFenX** [comment]
It adds 12 because of electronics upgrades skill.
