### ISSUE TITLE
Standup Fighters not displayed in fighter bay of citadel (MacOS)

### ISSUE THREAD

**Issue by julius-thomas** [pyfa-org/Pyfa#2643]
## Bug Report

When adding (double clicking) standup shadows from the market to a citadel, they are not displayed in the fighter tab.

### Expected behavior:
Fighters are listed in the fighter tab

### Actual behavior:
<img width="801" alt="image" src="https://github.com/user-attachments/assets/a493292e-51ff-4151-bd9d-1cc0a5852f9b">

### Detailed steps to reproduce:

On the macOS client, simply add fighters to a structure bay.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

Any empty citadel fits.

### Release or development git branch? Please note the release version or commit hash:

v2.60.2 (v2.60.2
EVE Data Version: 2731103 (2024-10-30 12:46:15))

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

MacOs 15.1 (24B83)

### Other relevant information:

```pyfa v2.60.2
EVE Data Version: 2731103 (2024-10-30 12:46:15)

OS version: macOS-10.16-x86_64-i386-64bit
Python version: 3.11.0 (main, Dec  8 2022, 16:43:53) [Clang 12.0.0 (clang-1200.0.32.28)]
wxPython version: 4.2.1 (wxWidgets 3.2.2.1)
SQLAlchemy version: 1.4.50
Logbook version: 1.7.0.post0
Requests version: 2.31.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "gui/builtinAdditionPanes/fighterView.py", line 292, in fitChanged
  File "gui/builtinAdditionPanes/fighterView.py", line 262, in fighterKey
ValueError: tuple.index(x): x not in tuple
```

**Comment by DarkFenX** [comment]
This has been fixed in latest preview build. Non-preview build will be released today.
