### ISSUE TITLE
Fails to launch with  version `OPENSSL_3.2.0' not found (required by /lib64/libcurl.so.4)

### ISSUE THREAD

**Issue by clarg18** [pyfa-org/Pyfa#2646]
## Bug Report
clarg@fedora:~/Applications$ ./pyfa-v2.61.0-linux_8d0c7d8c023e9a8c92195b417581b83d.AppImage 
/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
Traceback (most recent call last):
  File "/tmp/.mount_pyfa-vGLVWGJ/opt/pyfa/pyfa.py", line 27, in <module>
    import config
  File "/tmp/.mount_pyfa-vGLVWGJ/opt/pyfa/config.py", line 4, in <module>
    import wx
  File "/tmp/.mount_pyfa-vGLVWGJ/usr/local/lib/python3.11/dist-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/tmp/.mount_pyfa-vGLVWGJ/usr/local/lib/python3.11/dist-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: /tmp/.mount_pyfa-vGLVWGJ/usr/lib/x86_64-linux-gnu/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /lib64/libcurl.so.4)

### Expected behavior:
GUI Launches

### Actual behavior:
App crashes before GUI launches

### Detailed steps to reproduce:
Run the app image

### Release or development git branch? Please note the release version or commit hash:
current stable v2.61.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
OS: "Fedora Linux 40 (KDE Plasma)"
Kernel: 6.11.6-200.fc40.x86_64
Architecture: x86_64
CPU: AMD Ryzen 9 5900X 12-Core Processor
Memory: 31Gi

### Other relevant information:
Using Wayland

**Comment by DarkFenX** [comment]
Can you test [v2.60.2](https://github.com/pyfa-org/Pyfa/releases/tag/v2.60.2)? I wonder if it's wxpython version update (4.2.1 -> 4.2.2) or changes in the environment

**Comment by nwolber** [comment]
I've tested v2.61.0 on EndeavourOS and it crashed with the same error. If I switch to v2.60.2 i get the error from #2648.

**Comment by Crystal4276** [comment]
Same here on Arch (2.60.2 had the same issue):

❯ ./pyfa-v2.61.0-linux.AppImage 
Traceback (most recent call last):
  File "/tmp/.mount_pyfa-vFQ29ab/opt/pyfa/pyfa.py", line 27, in <module>
    import config
  File "/tmp/.mount_pyfa-vFQ29ab/opt/pyfa/config.py", line 4, in <module>
    import wx
  File "/tmp/.mount_pyfa-vFQ29ab/usr/local/lib/python3.11/dist-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/tmp/.mount_pyfa-vFQ29ab/usr/local/lib/python3.11/dist-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: /tmp/.mount_pyfa-vFQ29ab/usr/lib/x86_64-linux-gnu/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /usr/lib/libcurl.so.4)

**Comment by clarg18** [comment]
Any chance of a fix? This completely breaks the app on [a subset of?] Linux devices.

**Comment by ppfeufer** [comment]
Still happening with v2.61.1 …

**Comment by DarkFenX** [comment]
Well, my only fix is to revert to wxpython 4.2.1. I believe its wheels were built with more demanding dependencies which break it for you guys. I am unsure I can fix it by changing built environment (at least easy enough). So I will just revert wxpython version, the only issue it brings is segfault on app exit.

**Comment by DarkFenX** [comment]
https://ci.appveyor.com/project/pyfa-org/pyfa/builds/51070584/job/m1qcv35a53gjv797/artifacts try this build. If it works I will make a release soon-ish

**Comment by Crystal4276** [comment]
Hi

> https://ci.appveyor.com/project/pyfa-org/pyfa/builds/51070584/job/m1qcv35a53gjv797/artifacts try this build. If it works I will make a release soon-ish (keep in mind downloads are limited, so if a few people download before you, it might get blocked)

Worked for me !

**Comment by DarkFenX** [comment]
Reopen if https://github.com/pyfa-org/Pyfa/releases/tag/v2.61.2 doesn't work
