### ISSUE TITLE
Fc40: 2.60.2 SegFault

### ISSUE THREAD

**Issue by Cyborgscode** [pyfa-org/Pyfa#2647]
OS: Fedora 40
DE: Cinnamon
Version: 2.60.2

$./pyfa-v2.60.2-linux.AppImage' 
Gtk-Message: 19:41:00.518: Failed to load module "xapp-gtk3-module"
Unable to revert mtime: /usr/share/fonts/arial
07:41:01 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
07:41:01 PM: Debug: Adding duplicate animation handler for '1' type
07:41:01 PM: Debug: Adding duplicate animation handler for '2' type
07:41:06 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
07:41:06 PM: Debug: Adding duplicate animation handler for '1' type
07:41:06 PM: Debug: Adding duplicate animation handler for '2' type
Unable to revert mtime: /usr/share/fonts/arial

** (pyfa.py:158072): WARNING **: 19:41:10.549: AT-SPI: Could not obtain desktop path or name

** (pyfa.py:158072): WARNING **: 19:41:10.616: atk-bridge: GetRegisteredEvents returned message with unknown signature

** (pyfa.py:158072): WARNING **: 19:41:10.616: atk-bridge: get_device_events_reply: unknown signature

** (pyfa.py:158072): WARNING **: 19:41:10.617: atk-bridge: get_device_events_reply: unknown signature
src/nv_gbm.c:288: GBM-DRV error (nv_gbm_create_device_native): nv_common_gbm_create_device failed (ret=-1)

Could not create GBM EGL display: EGL_SUCCESS. Aborting...
Abgebrochen (Speicherabzug geschrieben)

**Comment by DarkFenX** [comment]
Reopen if https://github.com/pyfa-org/Pyfa/releases/tag/v2.61.2 doesn't work

**Comment by Cyborgscode** [comment]
2.61.2 works.
