### ISSUE TITLE
Bhaalgorn Jump Capable?

### ISSUE THREAD

**Issue by jdc843** [pyfa-org/Pyfa#2650]
## Bug Report

Right-Click menu option "Change Ship Skills" erroneously shows
Jump Drive Operation
&
Jump Fuel Conservation
among the required ship skills.

Per what I see in the Eve client's "Show Info" page on the Bhaalgorn, this is not a jump capable ship.
Since I can't fly jump ships yet, I can't verify that.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Bhaalgorn, Incursion Doctrine 3.1]

Fit deleted but did not include any jump mods.

### Release or development git branch? Please note the release version or commit hash:
Release v2.61.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
None

**Comment by cryonox** [comment]
That's not a bug. The right click -> change ship skills is not "required skill list". to see required skills list ,you need to go to ship stats and go to "required" tab. The reason jump drive calibration and jump drive operation show up in  there even though it "seems" they are not used is most likely becuase they show up in the dogma expression tree.

**Comment by DarkFenX** [comment]
Those effects technically affect ship even if attributes are not used for anything.
