### ISSUE TITLE
2.60.2 -> 2.61.1 upgrade copy to clipboard no longer works

### ISSUE THREAD

**Issue by oldtechaa** [pyfa-org/Pyfa#2651]

**Comment by oldtechaa** [comment]
Just tested and the issue was present in 2.61.0 as well, but definitely _not_ in 2.60.2.

**Comment by oldtechaa** [comment]
I suspect https://github.com/pyfa-org/Pyfa/commit/bbe3e931f73255ecf50109f746878a37b4c8e798

**Comment by DarkFenX** [comment]
Yes, most likely it breaks it somehow. Works for me on gnome/X11 though. I am reverting wx version nevertheless.

**Comment by oldtechaa** [comment]
I can try an X11 session and see if that helps, still on KDE. Let me check.

**Comment by oldtechaa** [comment]
I can confirm that it works fine in an X11 KDE session.

**Comment by DarkFenX** [comment]
Reopen if https://github.com/pyfa-org/Pyfa/releases/tag/v2.61.2 doesn't work

**Comment by oldtechaa** [comment]
Fixed in 2.61.2, thanks.
