### ISSUE TITLE
New build prevents MWD activiation

### ISSUE THREAD

**Issue by DreadOp** [pyfa-org/Pyfa#2652]
### Expected behavior: 
Activate MWD

### Actual behavior:
Switched between offline and online (AB works fine)

### Detailed steps to reproduce:
Fit MWD, click it off, does not click back on.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
Multiple. 

### Release or development git branch? Please note the release version or commit hash:
v2.61.2

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by DarkFenX** [comment]
Check for projected scrams/WDFGs or fits with scrams/WDFGs. I do not have this issue.

**Comment by DreadOp** [comment]
Clean reinstall fixed it.

**Comment by DarkFenX** [comment]
Weird, but glad that it works for you
