### ISSUE TITLE
Separate log file is created whenever something is logged

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#327]
On windows, not sure about os x

This happens when something is logged, even with the release version. Thankfully, the only time a release should show this is if an actual error happens (WARN or above). However, it happens if log is DEBUG. Does not happen when running from source. 

Not really a big thing, and might even be useful to notify the user when something has been logged that needs to be addressed. Just wasn't expecting it. The log file that is produced is basically identical to the log file we save in the users save path.

![capture](https://cloud.githubusercontent.com/assets/3904767/8638511/cece9456-288b-11e5-8e6a-643ea5b4d4e2.PNG)

**Comment by Ebag333** [comment]
I don't know if this is an issue anymore, and #986 should take care o f it.....

We might even be able to bubble up a popup in the GUI.  Dunno if we want to go that far.

**Comment by blitzmann** [comment]
It probably is still an issue, but I plan on revisiting after we integrate logbook.

> We might even be able to bubble up a popup in the GUI. Dunno if we want to go that far.

https://github.com/pyfa-org/Pyfa/pull/247

Like this. I still think it would be beneficial to hook into exceptions and at least let the user know something happen and direct them to the log, but that can be figured out at a later time.

**Comment by blitzmann** [comment]
Gonna close this issue since this is probably no longer a thing.
