### ISSUE TITLE
Feature request: add option to show damage graphs for more than one ammo type

### ISSUE THREAD

**Issue by jordillo** [pyfa-org/Pyfa#342]
<3 pyfa!  :-)

request: add option to quickly show damage graphs for more than one ammo type

suggestion: add checkbox "show graphs for all ammo types currently in cargo hold" to graph window

reason: one of the great things about pyfa is that it allows me to see at what range it is advantageous to switch ammo types against a given target to do max dps. it's a bit tricky though. my workaround currently looks like this:

1) create several copies of the same fit
2) load different ammo into each copy. let's say void, antimatter and null.
3) open the damage graph window for void and enter range, sig radius and speed of a probable target
4) pull the copies that have antimatter and null loaded onto the graph window from the ships tab

now i have the damage graphs for all ammo types in one window and can see that, for example, highest dps from 0-8 km is with void, 8-15 km is antimatter, 15+ is null

the process is somewhat cumbersome though. adding the requested option would be a great help. there should be a way of pre-selecting desired ammo types though to avoid a messy graph, for example with all the laser crystals or ships that use both turrets and missiles.

thanks for pyfa!

**Comment by blitzmann** [comment]
While I do like the idea, this is a more complicated problem than what it seems on the surface.

1) When we switch ammo, we have to recalculate the whole fit. This is very inefficient, but is something that is address with the new engine (whenever we get around to rewriting the GUI)
2) How do we handle different guns? Or even different weapon systems? Say you have 3 laser turrets and 3 rocket launchers, with ammo in the cargo for each. Not only that, but one of each module is t2, while the other is t1, and so now you have t2 ammo. How exactly do we choose which ammo pattern is represented by the graph?

It may be possible for us to allow you to show a snapshot of the fit in the graph - basically configure it the way you want, send the snapshot. Then change ammo the way you want, send the snapshot, etc. That is the only feasible way I can see this working, although I would love more discussion on this.

**Comment by DarkFenX** [comment]
I do not think it is viable. Just copy fits and load different ammo types if you need that. It's not very convenient but i see no good UI to let user switch ammo
