### ISSUE TITLE
Importing fits does not update cache of number of ships per category

### ISSUE THREAD

**Issue by ghost** [pyfa-org/Pyfa#345]
Using Pyfa 1.13.2

Import XML with my fittings from EVE (created in EFT 2.31)
Click "Hide empty ship groups" in browser
Only ship groups shown are the ones I have manually created fits for in pyfa

If I go in and edit the fit (open/close is enough) then it will show up when I choose to hide empty groups.

**Comment by Nahaz** [comment]
Restarting Pyfa seems to make it refresh fits and find imported ones

**Comment by blitzmann** [comment]
Well, the amount of ships are cached so as to not spend time counting them all the time. But it seems that the imports don't update the cache. I'll take a look into it when I get some time, but it's pretty low on the priority list.

**Comment by odracir123** [comment]
If you could point me to an example using the cache and where the import should take place I'd like to have a look.

**Comment by blitzmann** [comment]
Off the top of my head, the cache is located as a dictionary in shipbrowser.py. It's created when the categories are cached. The imports are located in mainframe.py, and there's a few different ones - import from clipboard, and import from file.

I haven't looked at it in a while. It's probably an easy fix.

**Comment by petosorus** [comment]
I'm not sure this is still relevant.
When I open a fit, from file or clipboard, the fitting browser changes view for that ship list of fits.
If you then click "back", the categories are up-to-date.

**Comment by blitzmann** [comment]
Indeed, this seems to have been fixed at some point. 😀
