### ISSUE TITLE
Suggestion: Offer a description/notes field for fits

### ISSUE THREAD

**Issue by resinneublem** [pyfa-org/Pyfa#364]
Just something small to allow people to write some notes down about the fit

**Comment by blitzmann** [comment]
This is another thing that I was looking into, especially when looking into a tagging system. The problem here as with the tagging system is that I am not really sure where to put the UI for this, and I'm not sure how useful it'll be (effort vs reward)

**Comment by resinneublem** [comment]
Oh I was thinking a new tab in the Additions at the bottom.

**Comment by blitzmann** [comment]
Hmm... it's possible. Sounds like was o.smium does.

**Comment by resinneublem** [comment]
I'm working on a PR for this. Not sure when it'll be ready.

**Comment by Ebag333** [comment]
@resinneublem 

nice!

What's your plan for implementing this?  I was considering just a new tab pointing to a new field in SQL.

**Comment by resinneublem** [comment]
@Ebag333 yeah that's all I'm doing. Getting the hang of wxPython and the codebase is the main delay for me.

**Comment by Ebag333** [comment]
wxPython is awful. Good luck with that. 

If you want to get on the Pyfa slack I might be able to point out a few things for you, if you're stuck somewhere.
https://pyfainvite.azurewebsites.net/
