### ISSUE TITLE
Performance: Exporting HTML is much slower on Mac than Windows

### ISSUE THREAD

**Issue by resinneublem** [pyfa-org/Pyfa#366]
Any idea what is causing the HTML export to be so slow on Apple?

**Comment by blitzmann** [comment]
I have no idea. I only hop onto my hackintosh partition when there is a problem, so I'll take a look when I have some time. Gonna have to test out wx3 branch changes on os x soon anyway.

HTML export itself it somewhat broken. Do you have it to auto export on changes? We always get complaints from folks about slow downs, or even crashes, usually when that feature is enabled, and we usually tell them to turn it off and simply export manually through the file menu. I have a feeling it's to do with it trying to access the database when it's locked. Could be unrelated, dunno

**Comment by blitzmann** [comment]
I actually just tried HTML export on Windows and it crashed. =(

**Comment by resinneublem** [comment]
>  Do you have it to auto export on changes? We always get complaints from folks about slow downs, or even crashes, usually when that feature is enabled, and we usually tell them to turn it off and simply export manually through the file menu. 

I turned it on briefly on the Mac, but it pretty much halted the app. Manually exporting my fits takes a few seconds on the Mac and less than a sec on Windows.

Perhaps I can dive in and see about profiling the difference and put together a PR if I can figure out what the cause is.

**Comment by resinneublem** [comment]
Just tested it. About 10-11 seconds on Mac. Less than a second on Windows.

**Comment by blitzmann** [comment]
I can't seem to reproduce. The export takes roughly the same amount of time for me on my OS X. >_>

**Comment by resinneublem** [comment]
Going to close this. Don't know if it's still an issue. I stopped using the HTML export a while ago. (And stopped playing on the mac)
