### ISSUE TITLE
Suggestion: New user setting to stop exporting ammo charges

### ISSUE THREAD

**Issue by resinneublem** [pyfa-org/Pyfa#368]
Often I wish I could export a fit without the loaded charges and only include stuff in the cargohold. Especially because I'll flip back and forth with ammo or scripts to see the numbers change.

I know you can empty the equipped charges before exporting, but that's a pain.

**Comment by blitzmann** [comment]
So, instead of this

    [Hawk, 2x ASB]

    Damage Control II
    Co-Processor II

    1MN Afterburner II
    Medium Ancillary Shield Booster
    Warp Scrambler II
    Medium Ancillary Shield Booster
    Stasis Webifier II

    Rocket Launcher II, Caldari Navy Mjolnir Rocket
    Rocket Launcher II, Caldari Navy Mjolnir Rocket
    Rocket Launcher II, Caldari Navy Mjolnir Rocket
    Rocket Launcher II, Caldari Navy Mjolnir Rocket
    [Empty High slot]

    Small Anti-EM Screen Reinforcer I
    Small Anti-EM Screen Reinforcer I


    Scourge Rage Rocket x200
    Navy Cap Booster 50 x68

You want this:

    [Hawk, 2x ASB]

    Damage Control II
    Co-Processor II

    1MN Afterburner II
    Medium Ancillary Shield Booster
    Warp Scrambler II
    Medium Ancillary Shield Booster
    Stasis Webifier II

    Rocket Launcher II
    Rocket Launcher II
    Rocket Launcher II
    Rocket Launcher II
    [Empty High slot]

    Small Anti-EM Screen Reinforcer I
    Small Anti-EM Screen Reinforcer I


    Scourge Rage Rocket x200
    Navy Cap Booster 50 x68

**Comment by ChrisKing517** [comment]
I second this!

**Comment by resinneublem** [comment]
Sorry, I missed this notification. Yep that's exactly what I'm thinking.

It's not so bad with rockets, hybrids, or projectiles. It's mainly for lasers (don't need extra crystals) and cap boosters (sometimes has problems with cargo space).
