### ISSUE TITLE
Cannot start on custom locale when installation path contains non-English characters

### ISSUE THREAD

**Issue by WiseFerret** [pyfa-org/Pyfa#379]
My pyfa is installed in /home/yotam/הורדות/pyfa.

Trying to bypass issue #378 (https://github.com/DarkFenX/Pyfa/issues/378), I try to force 
English locale. This is what I get:

```
yotam@ape:~/הורדות/pyfa$ LC_ALL=C ./pyfa.py
Traceback (most recent call last):
  File "./pyfa.py", line 79, in <module>
    config.defPaths()
  File "/home/yotam/הורדות/pyfa/config.py", line 69, in defPaths
    sys.modules['__main__'].__file__))), sys.getfilesystemencoding())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd7 in position 12: ordinal not in range(128)
```

When I install pyfa in my home folder (/home/yotam/pyfa), which does not include non-English characters, the same commands launches pyfa in the desired locale perfectly.

**Comment by blitzmann** [comment]
I thought we fixed this like last year. Will look into it. In the meantime... run via an ASCII path

**Comment by blitzmann** [comment]
Can you try `LC_ALL=en_US.UTF-8` instead? Using `LC_ALL=C` did not work for me (I assume because out files are written in ASCII, not Unicode? I'm not too familiar with locales and how they inheritely work)

**Comment by WiseFerret** [comment]
When I run LC_ALL=en_US.UTF-8 ./pyfa.py the program loads fine even when the path contains non-ascii characrters; however, it suffers from the same issue described in issue #378. The interface is right-to-left, and is broken.
It seems that LC_ALL=C is needed on right-to-left locales.

**Comment by blitzmann** [comment]
Specifically what is your locale set to?

**Comment by WiseFerret** [comment]
LANG=he_IL.UTF-8
LANGUAGE=he_IL:he
LC_CTYPE="he_IL.UTF-8"
LC_NUMERIC=he_IL.UTF-8
LC_TIME=he_IL.UTF-8
LC_COLLATE="he_IL.UTF-8"
LC_MONETARY=he_IL.UTF-8
LC_MESSAGES="he_IL.UTF-8"
LC_PAPER=he_IL.UTF-8
LC_NAME=he_IL.UTF-8
LC_ADDRESS=he_IL.UTF-8
LC_TELEPHONE=he_IL.UTF-8
LC_MEASUREMENT=he_IL.UTF-8
LC_IDENTIFICATION=he_IL.UTF-8
LC_ALL=

**Comment by blitzmann** [comment]
I don't really know what to tell you bud. =/ this is out of my area of knowledge. I'll keep this open and maybe someone else can chime in.

**Comment by Ebag333** [comment]
PR is pushed that I believe will fix this: #854

**Comment by blitzmann** [comment]
@WiseFerret Are you still around and monitoring this thread? If so, let me know - I want to get you a test package that includes @Ebag333's possible fix. We would want you to test on your locale, and also with `LC_ALL=C`, and make sure the path issue is solved

**Comment by WiseFerret** [comment]
Srill here :-) Where can I get the package?

**Comment by blitzmann** [comment]
I'll have to build one for you. I'll give you a link for download here when it's ready (I'll try to get it tomorrow) :)

**Comment by blitzmann** [comment]
@WiseFerret Totally forgot you're on Linux lol. I don't need to build you a package, just wrap of the source files. Here you go.

[pyfa-20170111-29d0f1-linux.zip](https://github.com/pyfa-org/Pyfa/files/697920/pyfa-20170111-29d0f1-linux.zip)

Could you test to see if they have the same path issues? Thanks!

**Comment by WiseFerret** [comment]
After downloading the package pyfa-20170111-29d0f1-linux.zip, the workaround is still not working. I get:

```
yotam@ape:~/הורדות/pyfa$ LC_ALL=C ./pyfa.py
Traceback (most recent call last):
  File "./pyfa.py", line 113, in <module>
    config.defPaths(options.savepath)
  File "/home/yotam/הורדות/pyfa/config.py", line 128, in defPaths
    import eos.config
  File "/home/yotam/הורדות/pyfa/eos/config.py", line 8, in <module>
    sys.getfilesystemencoding())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd7 in position 12: ordinal not in range(128)
```

However, running pyfa without custom locale, i.e. 
`yotam@ape:~/הורדות/pyfa$ ./pyfa.py`
Works well now, and pyfa launches in proper English locale even though my system uses Hebrew, so I do not need the workaround any more.

**Comment by blitzmann** [comment]
Excellent to hear! I'll mark this as fixed then :)

Thanks for taking the time to test this out

**Comment by blitzmann** [comment]
@WiseFerret We're having some issues with the fix that was put in place, namely paths with Russian characters are broken. I'm thinking about reverting back and adding a more nuanced fix for the other path issue this fix addressed (#548), but I want to get in touch with you personally to find out more information about the error that you are receiving.

It's much easier to debug these things in real time when we both have some time instead of through issues / email. Would you be able to get on Slack by chance? There is a button at the top of the README that points to a sign up. Once you're in, you can find me in the user directory (@blitzmann). We can chat there about things that work / things that don't.

I am particularly interested in how you have your environment set up. I have a Linux Mint VM and created a user with a hebrew locale (exported in `~/.xprofile`). I then reverted pyfa all the weay back to 1.15 (roughly the time this issue was reported), and yet I was able to launch it fine, so I still can''t really reproduce your specific error. It's more than likely that I simply don't have the correct locale set up or something.

![image](https://cloud.githubusercontent.com/assets/3904767/23151619/5e1a9538-f7ca-11e6-8666-064761bc56d3.png)

Anyway, ping me on Slack when you have a chance to chat. :)

**Comment by minlexx** [comment]
@blitzmann Linux has all in UTF-8 (as you can see on your screen), windows has windows-1251 for Russian, for example.

**Comment by blitzmann** [comment]
Reopening until I can get confirmation that this is still a thing. :D

**Comment by blitzmann** [comment]
@WiseFerret in case you didn't get it in slack, I'd like for you to test with this please.

[Pyfa-unicodetests.zip](https://github.com/pyfa-org/Pyfa/files/800945/Pyfa-unicodetests.zip)

I'll be in slack for most of the day tomorrow, we can chat then :)

**Comment by WiseFerret** [comment]
`~/הורדות/Pyfa-unicodetests$ py ./pyfa.py` runa well. Note that when exporting HTML the directory "[...]/pyfa" is hard-coded, so when it is run from Pyfa-unicodetests it throws an error.
However:
`yotam@ape:~/הורדות/Pyfa-unicodetests$ LC_ALL=C ./pyfa.py 
Traceback (most recent call last):
  File "./pyfa.py", line 120, in <module>
    config.defPaths(options.savepath)
  File "/home/yotam/הורדות/Pyfa-unicodetests/config.py", line 85, in defPaths
    pyfaPath = getPyfaRoot()
  File "/home/yotam/הורדות/Pyfa-unicodetests/config.py", line 64, in getPyfaRoot
    root = unicode(root, sys.getfilesystemencoding())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd7 in position 12: ordinal not in range(128)
`

**Comment by blitzmann** [comment]
@WiseFerret can you expand on this:

> Note that when exporting HTML the directory "[...]/pyfa" is hard-coded, so when it is run from Pyfa-unicodetests it throws an error.

What error does it throw? It should be easy to fix these things with file import and exports.

But the latest version works for you without running `LC_ALL=C` correct?

**Comment by WiseFerret** [comment]
Without LC_ALL=C everything seems normal.

When trying to export to html I get a dialog box saying: `Invalid Path

The following path is invalid or does not exist: 
/home/yotam/הורדות/pyfa/pyfaFits.html

Please verify path location pyfa's preferences.`

This problem does not occur when I try to import anything, or to export fittings or skills.

**Comment by WiseFerret** [comment]
Sorry for the misclick :-)

**Comment by blitzmann** [comment]
Thanks for the clarification. 

Can you go into preferences and reset the path to see if that fixes it?

**Comment by WiseFerret** [comment]
Yes, it does.
...However, the generated file contains only partial information (attached
here). This seems to be a different issue :-)

**Comment by blitzmann** [comment]
Did you attach the file to the email responder? You'll have to go to github itself and drag the file to attach it, as it doesn't work with email attachments. :)

**Comment by WiseFerret** [comment]
Here you go.
[pyfaFits.html.txt](https://github.com/pyfa-org/Pyfa/files/801424/pyfaFits.html.txt)

**Comment by blitzmann** [comment]
it outputs as a txt file?

**Comment by WiseFerret** [comment]
No, I added the .txt so I can upload it here. Just remove the .txt suffic.
BTW, I exported it without logging in.

**Comment by blitzmann** [comment]
gotcha. thanks. So the probelm seems to be that the shows the hulls, but not the actual fits, correct?

**Comment by WiseFerret** [comment]
Right.

**Comment by blitzmann** [comment]
Can confirm, opening a new issue about it.

But hey, at least you're not having any path issues. :)
