### ISSUE TITLE
Mindlinks

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#392]
CCP changed a bit how mindlinks work on the backend. They used to suppress the Skill effect on the ship and apply their own effect. Now they simply modify the skill's effect and give it a straight up percentage boost not based on skill level by using a `post_assign`, meaning it is assigned after all other calculations are performed.

pyfa doesn't yet support `post_assign` properly (it's a newish thing maybe?). For this reason I will be using the old method of skill suppression as it works the same way (and I also believe for the purposes of tracking what's affecting what, users want to know that a Mindlink is giving them that bonus rather than a skill that is being boosted by the mindlink)

Regardless, `post_assign` is something I need to look into eventually. Seems like the fleet boosting code also takes `gangBonus` and `gangBoost` effect variables into account?

**Comment by blitzmann** [comment]
Also, fleet bonuses in pyfa are jacked. How the fuck does this even work?

**Comment by Neugeniko** [comment]
Mining Mindlink mining amount bonus doesnt seem to be applying correctly. Same with Shield Bonus of Siege, Caldari & Minmatar Mindlinks. Other mindlinks look fine.

**Comment by blitzmann** [comment]
Wait, they don't work? I specifically remember looking into them and verifying that they work.

**Comment by Neugeniko** [comment]
If I just delete " * level " in siegewarfareshieldcapacitybonusreplacer.py
miningforemanmindlinkminingamountbonusreplacer.py  skirmishwarfareagilitybonusreplacer.py

Things work as expected fine. I just copied what armorwarfarearmorhpreplacer.py  was doing.

**Comment by blitzmann** [comment]
Yep. Apparently there is some code that's silently catching the exception about the missing level variable, hence why I didn't pick it up to begin with. 

Thanks for looking into this!

**Comment by blitzmann** [comment]
Fixed

**Comment by blitzmann** [comment]
I shouldn't have closed this, as we still need a `post_assign` =/

**Comment by Ebag333** [comment]
Fleet bonuses are going away and mindlink bonuses are changing entirely.  Recommend closing this @blitzmann

**Comment by blitzmann** [comment]
I added the flag to remind me to look at this later when fleet bonuses get overhauled... however, are mindlinks still a thing with the new stuff? And if so, we still need that modifier (well, maybe we don't need that modifier if this is the only thing that uses it)

**Comment by Ebag333** [comment]
Mindlinks are still a thing but completely reworked so they aren't touching the fleet boost stuff (because CCP wants to burn that code with fire).

**Comment by Ebag333** [comment]
Just adding a mention to #738 as that purges links.

**Comment by blitzmann** [comment]
Closing this for now. Will revisit if needed.
