### ISSUE TITLE
Mac, Text Size Changes

### ISSUE THREAD

**Issue by JoshuaNotowitz** [pyfa-org/Pyfa#398]
this is definitely a small thing and might only happen on macs with high res screens
Some text is appearing smaller than it used to while other text is appearing blurry.
Old 
<img width="1917" alt="screen shot 2015-11-03 at 10 55 37 am" src="https://cloud.githubusercontent.com/assets/8390690/10918522/feaa92a4-821a-11e5-8b74-71437783f580.png">
New
<img width="1916" alt="screen shot 2015-11-03 at 10 55 14 am" src="https://cloud.githubusercontent.com/assets/8390690/10918531/08a8c532-821b-11e5-8359-07004922f96e.png">

**Comment by blitzmann** [comment]
This is a known thing. We used to use wxpython changed the way they render fonts in 2.9, and so fonts may look a bit different. I tried to get them as close as possible to the old look, but slight variations may be present. This is low on the priority list at the moment, considering the recent OS X build has apparently broken for a lot of folks.

It could definitely be due to having the retina display or whatever it's called, though I am not positive. I do not have a legit Mac to test on.

**Comment by thorr18** [comment]
I noticed right away that for my display I got a much cleaner beautiful font after downloading pyfa-1.16.1-parallax-1.0-mac-wx3 (except the font on the tabs). Only the module icons got perhaps worse. 
Old was so blurry: 
<img width="1680" alt="screen shot 2015-11-05 at 7 38 09 am" src="https://cloud.githubusercontent.com/assets/3753521/10973174/10639de8-8391-11e5-9ba6-fb1bd4c66fd6.png">

**Comment by blitzmann** [comment]
Oh wow, I just noticed the difference between the two. Yeah, the fonts look much better although I am not opposed to tweaking the sizes if needed. Thank you for the images guys, it clears a few things up for me. 

As for the blurry text - those are custom drawn widgets, and the blurry text is actually superimposed onto a bitmap which has a defined size, which make sense that it is blurry as all other icons are blurry. I would need to figure out how, if it's possible, to increase the DPI for these and other fixed-sized icons. 

Also, please subscribe to #289 to keep up with the OS X build discussion - I could use images like this in the future to test out other stuff, and possibly get some of the remaining text cleared up. I'll leave this issue open as well to track any progress on the DPI issues specifically.

**Comment by blitzmann** [comment]
Gonna close this in favor of the more recent Fonts issue (pyfa needs, as a whole, much better font handling). besides, this one was during the wx3 move (2.x is now wxPython 4.0)
