### ISSUE TITLE
Character implants

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#422]
This is a popular feature request, and something I think pyfa should work towards. This thread will compile my thoughts and progress on this feature.

The feature itself is pretty simple: instead of having fit-specific implants, we have implants that travel with that characters. We actually already had most of the character implant stuff supported in the backend, but the GUI was disabled. After fixing it up a tad, I've now got characters with implants.

![capture](https://cloud.githubusercontent.com/assets/3904767/11025577/eb396e12-866a-11e5-8960-f8280bbbf06e.PNG)

![capture](https://cloud.githubusercontent.com/assets/3904767/11025584/00b314e6-866b-11e5-9243-40685e53c72c.PNG)

This is currently what I have. Fit implants override character implants.

Right now, implants are turned on/off in the database, but character implants should not be, as it will affect all other fits using that character. So the toggle needs to be based on the slot number of the implant instead of the implant itself, and be on a per-fit basis. This will require some DB tweaking, and I'm don't yet have a plan on how to load/save this to the database.

I'll also take a look at implementing implant sets. There probably wont be any fancy GUI here - it will probably act like the damage / target resists in that you set them up in a window, and can apply them via right click menu.

**Comment by narthollis** [comment]
If you are creating implant sets, it may be worth creating sets based on information provided in the API as the full implant list is now provided there, along with the implants in all jump clones (And jump clones have names).

**Comment by blitzmann** [comment]
You mean add implants when importing skills from the API? We could do that =)

**Comment by narthollis** [comment]
Yeah, when importing the skills, add implant sets for the currently installed implants, as well as for all jump clones with implants. 

It's all on the Char/CharSheet.xml.aspx endpoint.

**Comment by blitzmann** [comment]
might have to start thinking about this in a different way https://forums.eveonline.com/default.aspx?g=posts&m=6389150#post6389150

**Comment by blitzmann** [comment]
The original plan here was to merge both fit-specific and character implants, and give the user the option to enable/disable them. If the character had implants, this would be be the default for the fit, but a user could override them by selecting another implant for the same slot. That's why you see some ship icons in the previous screenshot.

This worked in all but one aspect: toggling the character implants. Unfortunately, if we toggle the character implants, that toggles them for all fits using that character, which is not what we want. In order to do something like this would require jumping through a bunch of hoops, probably using Association Proxies (which I swear I am never touching again), and have a generally confusing mechanism.

So instead, I heeded some advise: if you have a character with implants, the situation is rare in which you would unplug implants to work with one fit. So instead of creating a convoluted association between fit and character implants, I've decided to separate them and add a toggle to select which one the user wants to source from. 

![1](https://cloud.githubusercontent.com/assets/3904767/13730676/c25eafb0-e92b-11e5-9757-01a09cb3484d.PNG)
![2](https://cloud.githubusercontent.com/assets/3904767/13730677/c5af5c1e-e92b-11e5-91c1-5a1865edeed1.PNG)
WIP

Character implants are "online" and the state cannot be toggled. However, I realize there may be times when a user may want to toggle a character implant to see what affect that has on the fit (for example, if this pod is destroyed, can the ship still be fitted). I plan to allow the user to copy character implants to fit-specific implants via context menu.

I also plan to allow creation of implants sets, which can also be applied to the fit via context menu

Jump clones is something I am also thinking about,  but not sure how it will be implemented yet. We shall see.

**Comment by narthollis** [comment]
Regarding jump clone and implant groups - perhaps instead of a "Use Character Implants" radio option it could be a "Use implant group" drop-down select?

**Comment by blitzmann** [comment]
I was thinking of something similar, we'll see how it turns out

**Comment by blitzmann** [comment]
Check out `char_implants` implants branch for the latest. Implant sets (definite feature) and jump clones (possible feature) not yet implemented at this time, but I want to make sure that the basics work for now. I'll be making a pre-release for this branch for folks to test.

**Comment by MrNukealizer** [comment]
As of the pre-release version there seems to be a bug with set bonuses on character implants. Looking at a fit with the same set of implants gives different results depending on whether it's using fit-specific or character sets. It appears to just not calculate the set bonuses for the character implants.  
![Correct](https://cloud.githubusercontent.com/assets/1545777/13945953/a652af70-efce-11e5-8cca-66be91b82f98.PNG)  
![Incorrect](https://cloud.githubusercontent.com/assets/1545777/13945956/a833f150-efce-11e5-88f8-ac1d35b20f21.PNG)

**Comment by blitzmann** [comment]
That may be completely possible. The effect code is probably looking at the implants for the fit, rather than the "applied implants". Good catch, I'll have to take a look this week. I'll also do another pre-release for the implant sets once that's wrapped up. =)

**Comment by blitzmann** [comment]
@MrNukealizer I took a look and they are indeed applying to the fit implants explicitly. 

However, I also believe that implant sets are being calculated incorrectly to begin with. After looking through some forum posts (https://forums.eveonline.com/default.aspx?g=posts&m=3904939), it's possible we don't do it right (but I'll have to do some manual calculations later). Not sure how easy both of those will be to fix, but I'll work on it. =)

**Comment by MrNukealizer** [comment]
The math may be wrong in some situations, but at least for that particular set in the screenshot it's correct. As far as I can tell every stat matches up perfectly with ingame performance.

**Comment by blitzmann** [comment]
https://github.com/pyfa-org/Pyfa/commit/71d33f34291fd668487ee2bba627fe0da84d72ff should fix the character implants. The commit after that also fixes a calculation bug in which the character implants were not properly clearing previous calculation results.

I've manually verified that Slave and Snake sets are correctly calculated, so I'm gonna assume everything else works too. It's all multiplicative, so it'll give us the same result no matter which way we do it. In our case, every implant applies it's set bonus on the correct attribute to every other implant, instead of making one big total multiplier. as the forum post does.

**Comment by blitzmann** [comment]
This feature was release with v1.21.0, closing. \o/
