### ISSUE TITLE
1.16.2: IDP ARES Generic detected

### ISSUE THREAD

**Issue by bobbyroberts99** [pyfa-org/Pyfa#425]
After downloading and executing pyfa-1.16.2-parallax-1.1-win, AVG detected [ARES Generic](http://www.avgthreatlabs.com/ww-en/virus-and-malware-information/content/generic-virus/?name=IDP.ARES.Generic&utm_source=TDPU&utm_medium=IDP&PRTYPE=IS).

Just want to let you know about this. I find Pyfa to be very useful and easy to use, but before I proceed with upgrading, I just want to make sure that it's safe. What can you tell me about this?

**Comment by blitzmann** [comment]
It is safe. I've gotten a few reports that AVG is flagging as a false positive. The binary most likely has the same sequence of bits somewhere inside it that matches a known malware that AVG scans for, hence the positive. I still need to get in touch with AVG and get it whitelisted.

Does the zip download work fine?

**Comment by bobbyroberts99** [comment]
I used the zip to upgrade to 1.15 from 1.13 and that seems to work fine (although I did notice recently that when I added CovertOps cloak to a fit that Electronic Upgrades V was not included in the list of skills I still need to train--file a separate issue?)

Because the release notes say that I'd have to delete the 1.16.1 before using the zip for 1.16.2, I haven't tried that zip. I'm going to hold at 1.16.1 until AVG is whitelisted.

**Comment by blitzmann** [comment]
No, if your going from 1.16.1 to 1.16.2 you dont need to delete the directory. Thats only if upgrading from 1.15 and down, since they had a different directory structure. 

I am wonderinf if its only the installer that is flagged, or both the installer and the binaries in the zip. Please download the zip and extract somewhere (doesnt have to be normal pyfa location if you dont want, just some place to test) and test it out to see if avg has a fit.

Also 1.16.2 fixes the bug you discribed  with the modifier not applying.

**Comment by bobbyroberts99** [comment]
I think my upgrade path was 1.13 to 1.15 via zip. 1.15 to 1.16.1 via zip. If you don't see any potential problems, I'll upgrade to 1.16.2 with zip later today.

**Comment by blitzmann** [comment]
Oh, so you're not using the installer...

It's very weird though. I just installed AVG and was able to download and run both the zip archive and the installer without it flagging it. I did submit a request to AVG for review though, hopefully it will be fixed up.

**Comment by bobbyroberts99** [comment]
I just used the installer to upgrade to 1.16.2. AVG didn't protest but required skills for Covert Ops Cloaking Device II still seem wrong to me (I also need Electronics Upgrades 5 & Covert Ops 1).

- [astero & my skills](http://i.imgur.com/j7IBXnp.png)
- [Skills required](http://i.imgur.com/qi0qBc6.png)

I don't know if there's a problem because of how I upgraded in the past or if there's a bug. Is there a way to test the install for integrity? 

If you want me to open a new issue for the Covert Ops cloaking device, please let me know and I will.

**Comment by bobbyroberts99** [comment]
Just downloaded, extracted and ran AVG against pyfa-1.16.2-parallax-1.1-win.zip. No protests from AVG. I didn't actually start this version just in case it might mess with the other copy that's already installed.

**Comment by blitzmann** [comment]
Forgot about this issue. I'm going to close as I don't think we've gotten any more complaints about AVG. If you're still having issues with the cov ops skill and whatnot, please open a new issue. Thanks =)
