### ISSUE TITLE
OS X 10.11 - Sometimes Listboxes don't completely refresh

### ISSUE THREAD

**Issue by thorr18** [pyfa-org/Pyfa#453]
Sometimes when switching between lists, old items will persist and mix in with the new items being loaded. I've noticed this on a Crest fit screen before and here I've a screenshot of it mixing two different market module lists; it failed to overwrite the two items shown on the previous list. 
Going to a blank list, like "Propulsion" before going back to a list will clear the problem. 
<img width="386" alt="listboxrefreshproblem" src="https://cloud.githubusercontent.com/assets/3753521/11466923/93b681ee-96f9-11e5-9047-873bea9c785c.png">

and this one: 
<img width="390" alt="incompletelistboxrefresh" src="https://cloud.githubusercontent.com/assets/3753521/11466786/83d8f370-96f8-11e5-8a10-756648488926.png">

Prerelease 1.16.3 OSX 10.11.1

**Comment by thorr18** [comment]
As soon as I hover the pointer over the market scrollbar, it renders a color-change/highlight of the scroll bar and in that instant it also corrects the module list. I can repeat over and over.

**Comment by blitzmann** [comment]
Does this happen all the time from what you can tell, or is it variable?

Part of the code is to clear the display. I may need to add a `Layout()` to refresh the GUI though. I'll test it when I get home

**Comment by thorr18** [comment]
Right now It's looking pretty consistent. For some reason there were other times when it would complete the refresh on it's own without touching the scrollbar, but the refresh would be very delayed. I can't reproduce the delayed refresh issue anymore. 
Right now I am trying several different transitions and each time I go from a longer list of items to a list with fewer items there is no problem. However, each and every time I am going from a list with fewer items to one with more, I get the problem shown in the screenshots. 
I confirmed it is happening on 1.16.2 WX3 as well, but does not happen on non-WX3

**Comment by blitzmann** [comment]
I can't get this to reproduce on 10.10. I haven't tried on my 10.7 VM image

I've tried going to and from large to small lists to no avail. It works pretty well actually =(. I wonder if this has anything to do with the slow GUI issue with 10.11. I have no idea how to fix it, and I haven't been able to get a 10.11 test environment up and running.

**Comment by thorr18** [comment]
If I log into CREST, then I get the delayed list refresh behavior, as if a CREST thread somehow periodically triggers refreshes of my lists. I am consistently seeing this. 
Every time I test without logging into CREST first, I get no list refresh, until I hover past the scrollbar, as I originally reported. 
So, I guess this is why I reported the issue "Sometimes" happens, but now I see consistency. 

(OSX 11.2, all downloaded Wx3 build versions)

**Comment by blitzmann** [comment]
Are you still having this problem?

I feel like 10.11 has a lot of issues that the previous versions don't, and I'm not sure why. I still haven't really pushed myself to get a 10.11 hackintosh to help check these...

Can you possibly produce a video so I can see exactly what events are happening? One with the listbox not clearing, and one with the CREST thing refreshing after a certain delay (which makes no sense, tbh)

**Comment by unpoetical** [comment]
I can confirm I've seen messed up market lists in osx 10.11.2.

I usually see it if I choose open-market-group from an item in a fit.   The market item list is a jumble of relevant and non-relevant items.   Clicking on the market group name in the left pane refreshes the list.

**Comment by blitzmann** [comment]
Just got a 10.11 hackintosh set up, can confirm as well. The text and icon don't refresh, which is odd. When it fixes itself, the real items are unmasked for lack of a better explanation. Once I get a dev environment set up on this I can hopefully debug it properly.

**Comment by blitzmann** [comment]
Guys, can anyone confirm if this is still a thing in 2.x releases? I'm hoping the GUI version upgrade fixes some of these older mac issues, just trying to figure out what's still relevant and what's not

**Comment by thorr18** [comment]
This issue only triggered after logging into CREST, so if CREST is dead then so is this issue.

**Comment by blitzmann** [comment]
We still use a lot of the old code from the CREST stuff, but I agree, unless this happens again, might as well close the issue.
