### ISSUE TITLE
Unable to import fittings, 1.16.3 -wx3 version for OS X, 10.7.5

### ISSUE THREAD

**Issue by SuperiorMonkey** [pyfa-org/Pyfa#456]
This is two separate bugs, but the issues are so closely tied I feel they should be considered together.
First is that the ability to copy fits from the clipboard seems to have broken. The menu is just greyed out. This is bad, I use it all the time to bring in fits posted on my alliance website. Then I tried the fallback method, I pasted the fitting text into a text document. Saved it as plain text, and as html. Tried to import each file, and both times the "importing file" progress window just sat there. Still animating, but no importing, and no ability to cancel it. Had to force quit out.

Please fix at least one of these so I can bring new fittings into pyfa.

**Comment by blitzmann** [comment]
Oh, this is a breaking bug. I am glad you caught it.

I will verify tonight and work on a fix asap. In the meantime, can you run pyfa with the debug flag through the terminal, as such: `pyfa.app/Contents/MacOS/pyfa -d` and post the output of importing the fit from file. Also try Cmd+C to copy a fit and Cmd+V to import a fit - and let me know if it works or any log output that does not.

Also, do you know if this happened with 1.16.2-wx3?

**Comment by SuperiorMonkey** [comment]
Last question first: I was one of the people who couldn't run 16.2 with -wx3 because of the CoreGraphics.framework location problem. I am currently running one that I believe you sent me a torrent link to, although I'm not sure exactly what version (just says 1.16.3 git).

Cmd+V doesn't work, does nothing at all actually.
Well now that's interesting. Two things change when I launch pyfa using the Terminal. One is that the window spawns in the foreground instead of invisibly in the background. The other is that importing my plaintext file doesn't crash. It still doesn't import though, here's the Terminal text:
2015-12-01 03:18:07,920 service.fit              WARNING  Unicode BOM not found in file /Users/mukansamonkey/Documents/Storm Hurricane.txt.
2015-12-01 03:18:07,920 service.fit              WARNING  Attempting to decode file /Users/mukansamonkey/Documents/Storm Hurricane.txt using UTF-8 page.
2015-12-01 03:18:07,920 service.fit              WARNING  File /Users/mukansamonkey/Documents/Storm Hurricane.txt decoded using UTF-8 page.
Just to verify, I launched it again using the Dock, and it went boom again.

**Comment by blitzmann** [comment]
So, this only seems to happen with the binary build. Works fine when running through the interpreter. I am assuming it has to do with the `argv_emulation` setting as that's the only difference between the pre-release and 1.16.2

Also, with the file import:

* It must be a file format that is recognized, such as the EFT cfg files, or the XML files. pasting an eft fit into a text document may or may not work, I'm not sure
* Importing a known good xml file works if you run pyfa via `pyfa.app/Contents/MacOS/pyfa`. Very strange. I'm honestly at a lost as to what I can do here. Will continue looking into it.

**Comment by blitzmann** [comment]
I have a tentative fix to the import/export problems. I'm still not sure what causes them, but OSX generally does some funky things with it's menu, so wxPython (or more likely wxWidgets) is not handling the menu events correctly. It is odd that it works when running through a terminal and not with the package, but I don't know what significance that has. The meat of the problem is that the menu item, for some reason, is being disabled.

The fix right now is to simply override `wx.ID_PASTE` (and to be on the safe side `wx.ID_COPY`) to a new ID that we can work with as normal on OSX. These default IDs are sometimes treated differently depending on the operating system, so overriding them allows us to erase any special properties they may carry.

I haven't looked at the import dialog crash yet

**Comment by blitzmann** [comment]
I tried to look into the import crash / freeze last night Didn't get very far, however I noticed that it works great without issue when running the pyfa executable through the terminal and not through the app launcher.. There have been a few other issues that were caused with the app launcher, so this is something to look into.

**Comment by SuperiorMonkey** [comment]
Copying from/to the clipboard is functional as of 1.17.1. Closing this one.

**Comment by blitzmann** [comment]
I'm reopening as there's still the problem of the hang when importing file ;)

**Comment by thorr18** [comment]
On pre-release 1.17.2 (git), I'm able to import xml with OSX (11.2) and can get 'malformed xml' pop-up messages.

**Comment by blitzmann** [comment]
Guys, glcan you upload the xml files youre using? The recent changes may have helped diagnose the issue, but its still weird that 8t seems to wor when running it through the ttermina and not as an app

**Comment by blitzmann** [comment]
Closing this as possibly obsolete - with pyfa 2.x, we use a new GUI version, as well as use a new packager, so I'm trying to clean up these old issues that may not be applicable anymore.

If you're still having troubles with any of the above issues, please open a new issue. Thanks!
