### ISSUE TITLE
CREST User-supplied details not working

### ISSUE THREAD

**Issue by tehFred** [pyfa-org/Pyfa#460]
When I try to add a character, I login and authorize a character, which loads the page saying "Done. Please close this window.", but no characters are added to the CREST Character Management window. 

I have tried multiple characters on multiple accounts, and when using implicit mode it worked fine.

**Comment by blitzmann** [comment]
1) Restart pyfa - there is a known issue with switching to user-supplied keys from implicit mode until you restart the process.
2) Double check the client details (they are probably okay because IIRC CCP will tell you that they are not when trying to login)
3) Is there anything in your log file (`~/.pyfa/log.txt`)?
4) If problem persists, please run pyfa in debug mode (start with the `-d` flag) and reproduce, and then post logfile (make sure you search for and edit out your secret key if it displays)

Also, what OS are you one?

**Comment by tehFred** [comment]
1. Restarted pyfa (and my whole machine since yesterdays post), same issue.
2. I'm assuming the client details are fine given that I'm allowed to login and select a character to use with crest.
3. log.txt is empty, redoing this with -d
4. http://pastebin.com/raw.php?i=iUpB0fQV
I am running Windows 8.1 x64

**Comment by blitzmann** [comment]
Hi there,

Sorry, been busy with the holidays. I still cannot reproduce, and the pastebin that you provided has expired (I didn't know they did that). Would you mind running again in debug mode and posting the output?

**Comment by tehFred** [comment]
http://pastebin.com/raw/SfRVhfrM

I did the following steps:

Launch pyfa
CREST > Manage Characters
Add Character
Selected character, clicked authorize
"Done. Please close this window." so I close the tab
Back in pyfa, no characters are listed in the character management window, so I quit pyfa and copied the entire contents from ~/.pyfa/log.txt into that pastebin.


While writing these steps I did it again and left pyfa open for longer before closing it (as I was writing this) and now this is at the end of the log file: 
2016-01-12 19:21:49,710 service.server           DEBUG    Server timed out waiting for connection

Just tried it again and got the same entry into the log. It seems to be around a minute before that time-out appears in the log.

Here is a new pastebin with my 3 attempts:  http://pastebin.com/raw/D8YY2Aqv

**Comment by blitzmann** [comment]
You keep getting a 400 Bad Request status, and I have no idea why.

Can you perhaps make a new application on the dev site and use the new client details, and test with that?

I will see about making some files with extra debugging that you can add to pyfa to help pinpoint the issue.

**Comment by blitzmann** [comment]
Oh, I was able to reproduce.

Check your client settings and make sure there are no spaces before or after the text in client secret and client id, then retry. If it works, wonderful! I'll make a change to trim the whitespace off when saving it.

**Comment by tehFred** [comment]
I was running 1.17.1. Trimming whitespace I found at the end of the secret has fixed the problem, thanks!

**Comment by blitzmann** [comment]
Awesome! There's a new commit that should address this as long as someone re-applies the client details. should ship with next release, whenever that happens
