### ISSUE TITLE
Additional graphs

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#463]
With the Frostline release, CCP added falloff for RR modules, which means we now may want to know how much we are repping at which range. This would require a new graph. y = HP/s, x = range. Maybe different collors for the different things (shield, armor, neuts, cap when it's added in the future)

[Someone on Reddit](https://www.reddit.com/r/Eve/comments/3vplh0/pyfa_orbit_velocity/) was also asking about orbit velocities of ships, which I think would also be neat to add as a graph. y = max velocity, x = range.

This open issue isn't a promise any of this will get done - I still need to actually look at the graphing code and not kill myself in the meantime. If anyone else wants to take a whack at it, feel free and let me know.

**Comment by resinneublem** [comment]
Adding another reddit thread that mentioned orbit velocities too: https://www.reddit.com/r/Eve/comments/3zg3gw/whats_the_formula_for_calculating_maximum_rads/

I'm still not quite sure what the orbital velocity formula is, but that would very interesting.

**Comment by DarkFenX** [comment]
Multiple graphs were added in 2.9.4 and more yet to come. Closing this ticket as "more graphs" has been implemented, kind of.
