### ISSUE TITLE
Missing icon files - 1.17.1

### ISSUE THREAD

**Issue by thorr18** [pyfa-org/Pyfa#476]
* 'Warp Disruption Fields' - 'icons/36_15.png'
* 'Remote Armor Repairers' - icons/remote_repair.png'
* 'Remote Hull Repairers' - 'icons/remote_repairer.png'
* 'icons/marketicon_caldari.png' - 'Caldari Subsystems' category icon (not missing item icons)
* 'icons/marketicon_amarr.png' - 'Amarr Subsystems' category icon (not missing item icons)
* 'icons/marketicon_gallente.png' - 'Gallente Subsystems' category icon (not missing item icons)
* 'icons/marketicon_minmatar.png' - 'Minmatar Subsystems' category icon (not missing item icons)

**Comment by blitzmann** [comment]
I finally got around to fixing these. Will be out in point release tomorrow. =D
