### ISSUE TITLE
Ship drag image gets stuck

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#479]
Someone messaged me:

> http://puu.sh/lYXFa/2adce3df8e.png http://puu.sh/lYXJs/0f9c932637.png
> This happens alot. Ussualy can fix it by going back to pyfa, but now It's staying on my screen.

I don't really know how to reproduce this, but I've had the issue as well. As soon as I can reproduce consistently, I can start looking into the issue

**Comment by Ebag333** [comment]
Solution: don't use wxPython.

(Can we close this now @blitzmann? :D )

**Comment by blitzmann** [comment]
I'm going to keep this open. I was able to reproduce it, just never got around to posting about it. I got it to reproduce when right clicking during a drag. It should be a matter of canceling the drag on right click.

However, the drag, IIRC, only really is needed for fleet booster support, which is going away soon. It might also work with the projection pane, dunno yet. I'm going to tag this as such so that I can look at it again when that happens and verify.

**Comment by Ebag333** [comment]
It probably happens with all drags, modules, ships, etc. Like dragging them to the projection tab.

**Comment by blitzmann** [comment]
> It probably happens with all drags, modules, ships, etc. Like dragging them to the projection tab.

No, only with fit drags. Other drags don't create a drag image. Also, confirmed that fits can be dragged to projection view, so this bug will have to be fixed eventually.

**Comment by blitzmann** [comment]
Got a fix for it. For documentation, this was the exception happening:

```
Traceback (most recent call last):
  File "C:\Users\Ryan\Sync\Git\blitzmann\Pyfa\gui\shipBrowser.py", line 1554, in OnContextMenu
    self.PopupMenu(menu, pos)
  File "C:\Users\Ryan\Sync\WinPython-32bit-2.7.10.1\python-2.7.10\lib\site-packages\wx-3.0-msw\wx\_core.py", line 11144, in PopupMenu
    return _core_.Window_PopupMenu(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "Assert failure" failed at ..\..\src\common\wincmn.cpp(3346) in DoNotifyWindowAboutCaptureLost(): window that captured the mouse didn't process wxEVT_MOUSE_CAPTURE_LOST
```
