### ISSUE TITLE
Mining upgrade modules don't affect Modulated Strip Miner II

### ISSUE THREAD

**Issue by unpoetical** [pyfa-org/Pyfa#482]
Toggling the Mining Laser Upgrade I & II on and off in this fit have no effect.   pyfa reports that Modulated Strip Miner II with T1 crystals underperforms against T1 Strip Miner I with 3 ML upgrade I.

Maybe similar to #454.

[Retriever Fit.xml.zip](https://github.com/DarkFenX/Pyfa/files/69311/Retriever.Fit.xml.zip)

<img width="1368" alt="screen shot 2015-12-21 at 11 52 19 pm" src="https://cloud.githubusercontent.com/assets/10162326/11948118/24e54f92-a83e-11e5-91a8-e51ae5cc2739.png">

pyfa-1.17.2 (git) [8e2892533649529ab038cfe06f2d27f3a062f13e] on OSX El Capitan 10.11.2 with wx3.

**Comment by blitzmann** [comment]
possible relation to #376. The mining amount attribute is correctly modified, but we also have a specialtyMiningAmount attribute that we need to account for that is not being represented correctly. I am not a miner and the math can be a bit funky. Will look into this as soon as I can  =)

**Comment by Ebag333** [comment]
#771 fixes the crystal issue....I think.

Need someone that actually mines to get me actual stats.  None of my chars have _any_ mining skills to speak of, so this isn't something I can test myself.

Looking at it, based off bonuses and such it _looks_ right, but I would like to see some hard numbers in game.  Basically what fit was used, and how much you mined after 1 cycle (units and m3), and how long that cycle was.  Can then verify that matches the Pyfa stats.

**Comment by DarkFenX** [comment]
Currently effect is properly implemented.

New eos dump:
```
$ python3 getmods.py -e miningYieldMultiplyPercent
effect miningyieldmultiplypercent.py (id: 1882)
  build status: success
  state: online
    Modifier 1:
      source attribute: miningAmountBonus
      operator: post_percent
      target filter: domain_skillrq
      target domain: ship
      target filter skillrq: Mining
      target attribute: miningAmount (not penalized)
```

Pyfa eos code:
```
class Effect1882(BaseEffect):
    """
    miningYieldMultiplyPercent

    Used by:
    Variations of module: Mining Laser Upgrade I (5 of 5)
    Module: Frostline 'Omnivore' Harvester Upgrade
    """

    type = 'passive'

    @staticmethod
    def handler(fit, module, context, **kwargs):
        fit.modules.filteredItemBoost(lambda mod: mod.item.requiresSkill('Mining'),
                                      'miningAmount', module.getModifiedItemAttr('miningAmountBonus'), **kwargs)
```
