### ISSUE TITLE
FreeBSD port (instructions)

### ISSUE THREAD

**Issue by f-andrey** [pyfa-org/Pyfa#484]
Hello,
I'm make porting pyfa in FreeBSD http://www.freshports.org/games/pyfa/
Now for install
````
pkg install pyfa
````
or
````
make -C /usr/ports/games/pyfa install clean
````

Unfortunately, supporting DPSGRAPHING (default disabled) require accept patch https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=205294 or add the following lines in /etc/libmap.conf
````
[/usr/local/lib/python2.7/site-packages/wx-3.0-gtk2/]
libgcc_s.so.1   gcc48/libgcc_s.so.1
````

**Comment by blitzmann** [comment]
Hey, thanks for supplying this information and getting graphing to work on FreeBSD. I will include these instructions in the readme. =)
