### ISSUE TITLE
Window drawing error, OSX 10.7.5

### ISSUE THREAD

**Issue by SuperiorMonkey** [pyfa-org/Pyfa#485]
I reported this on an earlier version, but could not get a screen grab at the time. Now I have one:
http://i.imgur.com/ISANdoK.png
You will note that the last couple pixels on the right aren't the pyfa window, they are other apps behind it. So the right-hand column is drawing incorrectly sometimes.

As far as duplication steps: Select a ship fit, so the right-hand column populates with data. Close the Resources drop-down by clicking the black triangle, then open it again. The whole column should redraw incorrectly. I checked the other drop downs, the bug only occurred when I toggled Resources. 

Also note that the incorrect draw goes away if the entire window is resized at all. Although actually, it doesn't go away… the weird spacing between the CPU/PG bars and the drone bars is still there. It just stole space from the center fitting column so that the right-hand column is now oversized to fit its contents inside the window. What _does_ fix it is restarting, when it starts up there is no fit displayed, and the items drawn in the right-hand column have their normal spacing.

**Comment by blitzmann** [comment]
Haven't forgotten about this issue, just have been dealing mostly with a windows bug that crashes the character editor. Trying to work through OS X things now. 

Cannot reproduce on 10.10 (both -wx3 and non-wx3). I will have to try 10.7 on my VM.

**Comment by blitzmann** [comment]
So I'm curious if this is still an  issue with the new 2.x releases? Are you able to test?

**Comment by blitzmann** [comment]
Whelp, I can't reproduce on 10.10 with pyfa 2.0.2. That being said, osx 10.7 isn't really supported anymore. The build machine is a 10.10, and so it's not guaranteed to work on lower versions.

If this is still occurring, please open a new issue. :)

Thanks!
