### ISSUE TITLE
CREST timeout (2FA)

### ISSUE THREAD

**Issue by Nahaz** [pyfa-org/Pyfa#492]
I use two factor authentication and have to wait for an email and I sometimes experience a connection refused when adding characters in user-defined mode. I'm guessing there's a time out on the local webserver that pyfa opens?

Nothing huge but when managing 3+ accounts it can be noticeable.

**Comment by blitzmann** [comment]
There is a time out, it's currently ~ 60 seconds. I did not consider two factor auth and the time delay that would cause. I will look into user-defined timeout in the settings.

**Comment by blitzmann** [comment]
@Nahaz custom timeout settings has been added with 969952c, hope it helps. =)
