### ISSUE TITLE
pyfa windows package claims to be version 1.15

### ISSUE THREAD

**Issue by thorr18** [pyfa-org/Pyfa#493]
This affects crash reports and viewing file info on the executable. 
Pyfa 1.17.1 using windows installer claims to be Application/Product Version 1.15.1.0

**Comment by blitzmann** [comment]
Hrm, probably something with the installer. Will have to check. How about when installing pyfa, does it give the proper version?

**Comment by blitzmann** [comment]
Hmm, this is actually due to the executable in the skeleton having a version. I'll either find a way to change it or just remove it outright to prevent confusion
