### ISSUE TITLE
Pyfa locks up on Mac 10.11.2, need to restart.

### ISSUE THREAD

**Issue by bvelasquez** [pyfa-org/Pyfa#498]
Not sure what the exact steps are to reproduce.  However, after trying to delete modules from fits, the interface no longer responds and I get the bouncing progress bar in the ship fits tab when I try to display the ships.  I will try and get reliable steps.

![pyfa_1_18_0_-_python_fitting_assistant_and_documents](https://cloud.githubusercontent.com/assets/2302210/12279103/f7063818-b939-11e5-8cff-b061ed9f4d06.png)

**Comment by blitzmann** [comment]
Is this with the latest version? Did the previous version work? Are you using `-mac` or `-mac-wx3` build?

**Comment by blitzmann** [comment]
Also, check `~/.pyfa/log.txt` and post what you've got there, if anything. If you can reliably reproduce, try running pyfa with `-d` flag (and try running it directly as `pyfa.app/Contents/MacOS/pyfa -d`)

**Comment by blitzmann** [comment]
@bvelasquez Any updates on this?

**Comment by bvelasquez** [comment]
@blitzmann Sorry for delay.  I'll post the log shortly.  I believe it has something to do with updating prices and the fact that I was at work and maybe the firewall was affecting the update.  I turned off price updates and it seemed to help.  I'll double-check this and let you know.

**Comment by bvelasquez** [comment]
@blitzmann Ok, running directly and getting log entries now.  If it happens again, I will send you the data.

**Comment by blitzmann** [comment]
Price updates shouldn't affect this, it happens in a different thread. Getting that loading symbol on the ship browser (which I have never actually seen happen before) tells me it's waiting for the data from the database (or another thread has crashed for whatever reason). If you can get reproducible steps, I can start giving you instructions on which files to change to at least get more debug data (unless I can reproduce issue myself). 

Let me know, thanks!

**Comment by bvelasquez** [comment]
Still haven't reproduced.  You can either close this or move it to some backlog.

**Comment by blitzmann** [comment]
Okay, I will close this then. If you are ever able to reproduce it, feel free to reopen =)
