### ISSUE TITLE
Incorrect DPS calculating for Dramiel fitting

### ISSUE THREAD

**Issue by techalexx** [pyfa-org/Pyfa#506]
Pyfa calculating 153 dps for imported skills, in game - 132,9

![image](https://cloud.githubusercontent.com/assets/14972280/12411953/c572e990-be93-11e5-9584-9afbc0b561f8.png)
![2016 01 19 07 03 03](https://cloud.githubusercontent.com/assets/14972280/12411986/19d45f28-be94-11e5-99bd-f3e12d578b02.png)

**Comment by blitzmann** [comment]
Please post fit when reporting bugs. Screenshots are great and encouraged, but transcribing fit from screen shot is a pain and doesn't give me all the info sometimes (drones in this case)

```
[Dramiel, issue506]

Internal Force Field Array I
Micro Auxiliary Power Core I
Republic Fleet Gyrostabilizer

Medium Shield Extender II
Gistii B-Type 1MN Afterburner
5MN Y-T8 Compact Microwarpdrive
Faint Epsilon Warp Scrambler I

150mm Light AutoCannon II, Republic Fleet Phased Plasma S
150mm Light AutoCannon II, Republic Fleet Phased Plasma S
[Empty High slot]

Small Polycarbon Engine Housing I
Small Core Defense Field Extender I
Small Projectile Burst Aerator I
```

That being said, the DPS in pyfa is correct as far as I can tell. I've also checked with osmium and EFT, both of which give me the same value of 153. Note that while the in game fitting window is useful, it does take some liberty with a few things and calculates things a bit differently than most fitting programs (EHP being one of the big differences between client and fitting programs).
