### ISSUE TITLE
Cannot fit Covert Ops cloak t2 module on the Procurer

### ISSUE THREAD

**Issue by Logonz** [pyfa-org/Pyfa#507]
As the title suggests you cannot fit Covert Ops cloak t2 module on the Procurer as far as i can see.

**Comment by thorr18** [comment]
#473 & #499 reported that they can't be fit to the prospect, I assume for the same reason.

**Comment by Logonz** [comment]
Excuse the multiple, searched Procurer and couldn't find a single issue

**Comment by Logonz** [comment]
Thats because im a retard and it's called Prospect and not procurer, closing...
