### ISSUE TITLE
New graphs?

### ISSUE THREAD

**Issue by bvelasquez** [pyfa-org/Pyfa#508]
Not an issue but request for information.  Is the graph system plugin based?  Is it possible to create new graphs via access of the information provided by the set of ships dragged into the ship listing?  

I would like a graph to calculate combat simulation of two ships given there velocity/sig/angle/distance and also taking into account each ships DPS, EHP, and repair/recharge rates to determine which ship will reach an EHP of zero over a period of time.

Is this possible with the provided framework?

**Comment by blitzmann** [comment]
Graphing support for pyfa is somewhat convoluted. It is a plugin system, however we only have 1 "plugin" for it - the current DPS graph - so functionality beyoind that hasn't been tested. To be completely honest, I've never really touched the graphing stuff other than to fix bugs or add minor features - what is there has been there for years, long before I joined the project. I believe the whole thing needs a rewrite.

Now, is it possible for it to execute your example? It will almost certainly need some reworking of the code to differentiate attacking vs victim, and then logic to handle more than 2 fits. As it stands right now, every plugin (in this case, our sole DPS plugin) loads each fit via this command: `view.getPoints(fit, values)`. The `getPoints()` method of the plugin is what does that math, and spits back points to plot. But you can see here that there's no input at the moment for multiple fits (so having one fit affect another fit is currently not supported).

A decent plugin system would include a plug-in specific wx.Panel to handle inputs and the like.

And then there's the math involved with a full on combat situation, which makes me shudder thinking about it.

I am not against someone attempting this (as well as #463), however I probably won't deal with it. If someone is interested in helping on with pyfa's graphing, then you would start with `gui/graphFrame.py` for the main GUI, and then the plugins should be kept in `gui/builtinGraphs/`. 

Also, gonna close this as it's somewhat related to #463. I would be happy continuing conversation about new graphs or general graphing support there =)
