### ISSUE TITLE
Character editor can't edit skill levels when run from hotkey or char selection

### ISSUE THREAD

**Issue by mmaucher** [pyfa-org/Pyfa#513]
When opening the character editor via Ctrl+E or from the Character Selection, skill levels can't be edited (right click doesn't open the choice for skill levels).
When opening the character editor by clicking on the menu bar (Window -> Character Editor), skills can be edited as usual.

This bug appears since commit 253ebdc4e1f9d618a84e8da88200710dd999aaee .

This is on Linux Ubuntu.

**Comment by blitzmann** [comment]
I knew there was bound to be bugs with that commit. Didnt test that particular bit. Will look into it, thanks.

Besides the context menu not working, does it otherwise function?

**Comment by mmaucher** [comment]
I noticed cases where skill descriptions didn't turn invisible after closing them (so my screen was cluttered with skill descriptions after viewing some). Not at a Computer right now, so I can't reproduce.

**Comment by blitzmann** [comment]
Confirmed in Debian, however I can't reproduce the differences in opening with ctrl+e / character selection / menu. This is very odd. I'm gonna try to revert the offending commits once we figure out an alternative. I'm not sure why this happens; probably has something to do with popups being handled differently from within a dialog, and other dialogs spawned from a dialog not closing correctly. Fuck if I know.

**Comment by blitzmann** [comment]
Can you test the latest master and see if this is still an issue?

**Comment by mmaucher** [comment]
The latest master resolves this issue.
