### ISSUE TITLE
Alternate OSX distribution method

### ISSUE THREAD

**Issue by thorr18** [pyfa-org/Pyfa#515]
I have made a script for installing Pyfa packagemanager-style on OSX (and potentially Linux). 
A version of it can be seen [here](https://github.com/thorr18/homebrew-formulae/blob/master/pyfa.rb)

With a couple commands, Pyfa can update/install along with all it's dependencies without relying on the distributable you usually put together on an ancient version of OSX. Maybe it's too much to hope for, but perhaps this will eliminate some of the issues we have or generally make things smoother for OSX. I've got it auto-updating Pyfa on launch too. It can toggle between launching older versions that it has previously installed and optionally installs untagged pre-release versions. 

I was playing with a modified setup (a version of which can be seen [here](https://github.com/thorr18/Pyfa/blob/master/setup.py)) that just runs the old setup stuff unless it detects OSX. 

This isn't a pull request or an issue, just wanted to let it be known. It's working for me, but it's not ready for the wild yet. I'm gonna tweak it when I get back from travel in a few days, make a little bit of documentation, release it, and maintain it if it proves helpful to anyone.

**Comment by blitzmann** [comment]
Thank you! I am very interested in seeing where this goes, and can offer testing on the OSX versions that I have (10.7, 10.8, 10.10, 10.11). I am assuming this is similar to Arch Linux's PKGBUILD system which directs the package manager what to download and install and where to move everything to.

The only set back is that it's a completely different distribution method, and I'm not versed enough to understand the pros / cons or the implications of switching. But until that is sorted out, I would be happy to have something like this alongside the main releases, kind of how we have Linux packages listed in the README.

Do you have a quick how-to on getting this up and running?

**Comment by thorr18** [comment]
Uh, yeah, I thought I was gonna get to this last week and then I got stuck traveling to the ends of the earth. 
I'm on OSX 11.3, so it will be nice to have someone try on 10.x when I get back.

**Comment by blitzmann** [comment]
Gonna close this issue as someone else offered something similar which is now in the README. Feel free to continue discussion though, thanks may change =)
