### ISSUE TITLE
Missing graphics in latest release.

### ISSUE THREAD

**Issue by bvelasquez** [pyfa-org/Pyfa#516]
I'm missing the icons next to the market modules.  Attached is screen shot.

Running on Windows 7, used the .exe installation file.

![screenshot_021016_013415_pm](https://cloud.githubusercontent.com/assets/2302210/12962634/2473dc60-cffb-11e5-986d-b2169138a797.jpg)

**Comment by blitzmann** [comment]
Huh, icon info is missing from the database... Very strange, it was fine with my test dump 2 days ago. Will look into it.

**Comment by bvelasquez** [comment]
Probably all related to missing info in the DB, but other places are affected as well in the application.

![screenshot_021016_020526_pm](https://cloud.githubusercontent.com/assets/2302210/12963452/73d8398c-cfff-11e5-8f68-6815a82d6d66.jpg)

**Comment by blitzmann** [comment]
Yeah, pretty much all icons that are linked from the database. All GUI icons should still be present.

This seems like a change in the EVE cache files. A quick fix would be to use old icon information, which should be fine for this release, as nothing has really changed on the EVE side that we are concerned about for this release. I may have to get in touch with Entity to see if he can investigate the issue with reverence.

**Comment by blitzmann** [comment]
The data that we dump from cache that determines icon names seems to have moved. When the database was compiled, Reverence didn't get the correct data. I've opened up a ticket and hope Entity contacts me soon so that we may fix the issue at the source. For now though, I have a database that seems to be fine - will test and examine the data more in depth and release another version tonight.

**Comment by bvelasquez** [comment]
Great, thanks @blitzmann

**Comment by blitzmann** [comment]
Gonna mark this as fixed. It's still not solved in reverence where we get it data from the cache, but since ccp is now dumping all their data in YAML format I can convert it to something we can use and get correct information.
