### ISSUE TITLE
User-selected price source

### ISSUE THREAD

**Issue by bvelasquez** [pyfa-org/Pyfa#517]
Is this in a configuration file somewhere?  I'm not sure what market (Jita maybe), but would like to change the market to my staging system/station.

**Comment by thorr18** [comment]
Currently no setting for that. It's hardset in your service/price.py to system "30000142" (Jita)

**Comment by bvelasquez** [comment]
Perhaps an option in settings that allows entering the ID (which is available via many methods) as a quick/dirty way of changing this.

**Comment by blitzmann** [comment]
Yeah, I can do this. The issue that was preventing it from being implemented was that we didn't want to include solar system info in the database, but entering an ID could definitely work (even if it's not so user-friendly).

**Comment by bvelasquez** [comment]
@blitzmann Great. Call it an "advanced user" feature and not worry about the user experience for now.  It still would be a step in the right direction.  Thanks.

**Comment by ppfeufer** [comment]
How bout a "simple" select? Just for Jita, Amarr, Dodixie and Rens ....

That's 4 systems, I think that should be doable and no one has to do some obscure rituals to get a system ID.

**Comment by blitzmann** [comment]
I was actually thinking about possibly using CREST or the EVE XML API to look up the system ID. Never made it that far though, got bogged down with something else.

**Comment by blitzmann** [comment]
A simple implementation has been added via #934. Only does a few systems, but we may be able to expand if needed.
