### ISSUE TITLE
Error message: Locale 'en_GB' cannot be set

### ISSUE THREAD

**Issue by ppfeufer** [pyfa-org/Pyfa#527]
Getting said error message when starting Pyfa with the current git build.

![screenie_232](https://cloud.githubusercontent.com/assets/2989985/13554446/45b5e524-e3a8-11e5-91d5-cfb8a6bd8a50.png)

OS: Linux

**Comment by blitzmann** [comment]
Thanks for letting me know. Can you try the latest master branch? I've completely removed the locale stuff and replaced it with simple string formatting, which should clear this up. It's only used to determine thousands separators, not too worried about switching between `,` and `.`

**Comment by ppfeufer** [comment]
Yep, working again as expected. Thank you!

**Comment by blitzmann** [comment]
Great, thanks!
