### ISSUE TITLE
Drag and drop over existing module

### ISSUE THREAD

**Issue by AccountForPyfa** [pyfa-org/Pyfa#528]
While dragging and dropping a module from the market panel onto a fit, I was surprised to discover that it would not 'overwrite' a module already in place, and I had to manually empty the slot before I could fit a different module in its place. Proposal is thus that the functionality of fitting modules over existing modules be implemented.

**Comment by ppfeufer** [comment]
+1 for this, would make things definitely a bit easier.

**Comment by blitzmann** [comment]
Can't say this is a bad thing. I'll put it on the todo list. =)

**Comment by blitzmann** [comment]
Done. If you drop over an existing module, it will replace it as long as the module fits. If it doesn't not fit (you dropped over the wrong slot or something), it will try to ad the module with the current logic (try to find at least one open slot that allows the module to fit).
