### ISSUE TITLE
siege module doesn't apply damage bonus on missiles launchers

### ISSUE THREAD

**Issue by discipleofphage** [pyfa-org/Pyfa#531]
it seems the siege modules (t1 and t2) do not apply the damage bonus to xl missile launchers on the dreadnought pheonix (damage bonus does work on other dreadnoughts).
![siege_module](https://cloud.githubusercontent.com/assets/16583064/13673025/4a23c3ce-e6a5-11e5-825d-a5ae9695c84d.JPG)

**Comment by blitzmann** [comment]
Thanks! I have corrected this and the fix should be out with the official stable release. =)
