### ISSUE TITLE
ECM stats are way off with the 1.20 release

### ISSUE THREAD

**Issue by gospadin** [pyfa-org/Pyfa#533]
Basic Falcon fit carried over from pre-patch, with t1 dispersion augmentor and two t1 distortion amplifiers.

Character in-game is all-4 for relevant skills:
In-game:  Optimal 44km, Falloff +41km, strength 12.5 (4.4)

All-5 character in PYFA:
PYFA 1.20: Optimal 31.6km, Falloff +29.7km, strength 10.4 (3.48)

I've recreated the fit from scratch incase something bad carried over, but doesn't seem to help.

**Comment by gospadin** [comment]
![image](https://cloud.githubusercontent.com/assets/16710755/13706889/5394ae18-e764-11e5-952c-81c1be0c7f6d.png)

**Comment by gospadin** [comment]
![image](https://cloud.githubusercontent.com/assets/16710755/13706921/7e9fc17e-e764-11e5-8f22-b0109d47d0a2.png)

**Comment by blitzmann** [comment]
Hi, and thanks for providing screenshots. 

I cannot reproduce. Your pyfa screenshot has me worried, in that you are using the All 5 character but it does not seem that the skill are being applied. I made the exact same fit in my pyfa, with no problems

![capture](https://cloud.githubusercontent.com/assets/3904767/13709179/83b6c81c-e780-11e5-8157-fd3019d1b57d.PNG)

Also, I checked the fit under my own character and on SISI (both of which have the same skills and levels), and the stats match up, so I'm assuming something is off with your installation. Can you please double check the character, make sure it's set to All 5 and that it's not something like a duplicate? Also, go into character editor and take a look at the skills and levels for the all 5 character to make sure they are indeed set to all level 5. Please let me know. The alternative would be to privately send me your user database (`~/.pyfa/saveddata.db`) so I can take a look at the character issue (sable.blitzmann@gmail.com)

**Comment by gospadin** [comment]
FWIW, I nuked my .pyfa directory, and now it appears correct.  Something
must have polluted my setup from an older pyfa install.

Thanks!  (consider this closed from my perspective)

**Comment by blitzmann** [comment]
I am thinking that your all 5 character was corrupted somehow. That's the only explanation I have without having the database (unless you backed it up). I don't know what would have caused it between 1.19 and 1.20 - there were no changes to characters at all.

Anyway, glad it's fixed. I hope you backed up your fits, it's a pain to start from scratch =/
