### ISSUE TITLE
Crest Fetch Fits [bug?]

### ISSUE THREAD

**Issue by Dasoren** [pyfa-org/Pyfa#536]
I have installed pyfa 1.20.0 windows, on windows 10. 
I have manually set my CREST client details.
I was able to load up my 2 characters.
When I loadup "Browse Eve Fittings" and press "Fetch Fits" for ether character, It looks like it is loading but never loads and does not show any error. 

This was tested on 2 accounts, on 2 windows 10 systems. Both apps where restarted after the client details where entered. Please note that the crest api details where freshly made.

About 4 hours after the CREST details where made, they started working. I do not think this is a bug with pyfa, but not totally sure. Also if it is a bug of some kind, it would be good to let the users know it may take some time for the CREST details to work. I looked all over this repo for this issue and on the EVE CREST pages and did not find an answer. The Fetch Fits just started working after a few hours, so I think EVE CREST is just a little slow.

If this is not a pyfa issue, at lest leave this Issue here for other users to find with this problem or something. Sorry for the grammer/rambling. I am sleepy, and will edit this later when I am more awake.

**Comment by blitzmann** [comment]
I know CREST was having issues before the patch from what I've read on #devfleet; bunch of server errors. It's quite possible CREST is still having issues. And what you describe leads me to believe that it's a problem on EVEs side. This also explains why characters were added fine:  that isn't through CREST, but instead through EVE's SSO.

Did pyfa hang with a "Fetching fits" message, or did that disappear eventually?

**Comment by blitzmann** [comment]
Gonna close this issue as I believe this was an issue with the CREST server. The issue will still show up if folks search for it though. =)
