### ISSUE TITLE
Capacitor warfare resist on cap batteries messes with cap stability calculation

### ISSUE THREAD

**Issue by ZarosTenjin** [pyfa-org/Pyfa#537]
Hello,
i've just pulled the march release and worked on my guardian fit when i noticed that adding a cap battery seems to mess with the capacitor stability calculation. I think this bug was introduced with version 1.2.0. I've repulled 1.19.2 where the fit still worked out fine and compared. Here's the same fit in both versions as screenshot
![selection_012](https://cloud.githubusercontent.com/assets/17838944/13763895/1634c556-ea4a-11e5-986d-dd08ea911600.png)
.
I'm just eyeballing but does the -25% neut efficiency of the cap battery maybe get calculated as -25% cap recharge?

Cheers

**Comment by blitzmann** [comment]
Please post eft version of fit, and ill take a look into it

**Comment by ZarosTenjin** [comment]
Fit from screenshot:
```
[Guardian, vulfpeck doctrine L5]

Damage Control II
True Sansha Armor EM Hardener
True Sansha Armor Thermal Hardener
True Sansha Armor Kinetic Hardener
Shadow Serpentis Energized Adaptive Nano Membrane

10MN Afterburner II
Small Cap Battery II

Large Remote Armor Repairer II
Large Remote Armor Repairer II
Large Remote Armor Repairer II
Large Remote Armor Repairer II
Large 'Regard' Remote Capacitor Transmitter
Large 'Regard' Remote Capacitor Transmitter

Medium Processor Overclocking Unit II
Medium Anti-Thermal Pump II


Light Shield Maintenance Bot I x5


Medium Hull Repairer I x1
Nanite Repair Paste x500
Mobile Depot x1
ECCM Script x1
```

Fit that is projecting onto it:
```
[Guardian, vulfpeck doctrine L4]

Damage Control II
True Sansha Armor EM Hardener
True Sansha Armor Thermal Hardener
True Sansha Armor Kinetic Hardener
Shadow Serpentis Energized Adaptive Nano Membrane

10MN Afterburner II
Cap Recharger II

Large Remote Armor Repairer II
Large Remote Armor Repairer II
Large Remote Armor Repairer II
Large Remote Armor Repairer II
Large 'Regard' Remote Capacitor Transmitter
[Empty High slot]

Medium Remote Repair Augmentor I
Medium Processor Overclocking Unit II


Light Shield Maintenance Bot I x5


Medium Hull Repairer I x1
Nanite Repair Paste x500
```

**Comment by blitzmann** [comment]
https://github.com/pyfa-org/Pyfa/commit/627dac692c6ceaaab7138776b0b44c7ce71dba9c

Well fuck. It would seem that `addDrain` is also used for things like remote cap transfers, the cap need is just negative in that case. I totally thought cap transfers used a different mechanic to apply their cap.

This was a case of bad function naming and lack of documentation.

I think that this is a sufficient error to warrant a new release. I'll look into getting that sorted tomorrow.

**Comment by ZarosTenjin** [comment]
Glad i found it relatively fast and decided to make a github account to report it then. Thanks for looking into it so fast!
