### ISSUE TITLE
Citadels

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#540]
This ticket is to track feature progression of Citadels in pyfa.

The new Citadels will feature structure fitting much the same way ship fitting is done. While there are a lot of similarities, there is also some push back in that we currently assume everything is a ship, which may cause issues. A quick test (and small modification) shows us that we are able to load a Citadel into the Ship class and show it in the fitting window. There are a few problems right off the bat (for example, there's an error when trying to calculate warp speed... because it's a structure). But at least it loads:

![capture](https://cloud.githubusercontent.com/assets/3904767/13906718/ea12c5d6-eeb3-11e5-936c-09f79eef2ca2.PNG)

Going forward, some questions need answers:
- Stats. What kind of stats do Citadels have, and what kind of stats do players need. As mentioned above, there's currently the problem in the warp speed calculation because Citadels do not move. How should we handle the differences between ships and structures? This also brings up the problem of dynamically changing content in the stats area - it's something that can kinda sorta work (see mining stats), but it's clunky and not very good. This is something that will need some more thought.
- Additions. Cargo, Implants, Boosters, Projected effects (this may apply to structures, not sure), Fleet... I don't know how to handle these. It may be possible to simply remove them from the notebook if we are working with a structure...
- What roles do skills play in citadels and their stats?

This list will probably grow, especially once my shit finally anchors on SISI and I can test out the modules and stuff

**Comment by blitzmann** [comment]
Also with this release comes changes to fighters. I haven't been keeping up with it, but it looks like fighters will now be able to toggle between selected abilities? I have no idea how this would work in pyfa...

**Comment by narthollis** [comment]
Fighters now have activateable abilities - From what I have seen its 1 movement and 1 role (damage for light and heavy fighters and ewar for the the support fighters). I have no idea if these are affected by skills.

I am fairly sure the fighters still have standard damage output as well as the activateables. This should still be skill/module/etc effected.

**Comment by narthollis** [comment]
Also, regarding citadels themselves - I think that its worth considering how to handle other structures in future as well as CCP is has been talking about citadels being the first of this type

**Comment by Ligraph** [comment]
About Fighters:
I've been doing some testing of my own and it seems like they are treated more like a ship than a drone.  E.g. they have turrets, missiles, mwd (with a cooldown), etc.  Possibly model their dps just like a ship's that has weapons fit.  I'm not at my computer with pyfa on it so I have no idea how drones are handled, so this could already be what is happening.

**Comment by Ligraph** [comment]
Also, skills do not affect citadels.

> Unlike ships, these bonuses are fixed and not dependent on character skill level. In fact, no existing skill will affect any of the structure hulls, modules or rigs. That means Engineering will not increase powergrid on any of the new Citadels for instance, and that none of the missile support skills will function for the structure missile launchers.

From [here](https://community.eveonline.com/news/dev-blogs/structure-fitting-in-the-citadel-expansion/).

**Comment by blitzmann** [comment]
IIRC, there is tracking / missile calculations in pyfa for drones, used by fighters only. This may or may not be a big change. I need more information on how the "additional" modules work for them, and thoughts on how they might be able to be implemented. =)

**Comment by blitzmann** [comment]
Also, the fact that skills don't affect citadels may be become problematic. At the moment, the plan was to simply make Citadels "fits", but that would mean that Skills that apply to the ship and it's modules would also apply. There may be an easy way to block these based on the fits item, I'll have to check.

**Comment by Calavoow** [comment]
The problem with @Ligraph quote is that it says "no existing skill", the core being existing skills. They added various citadel skills, such as Structure Doomsday Operation, Structure Missile systems, etc. Those do effect citiadels afaik.

**Comment by blitzmann** [comment]
@Calavoow thanks for the clarification. I won't be working on the feature until at least the current release cools down with the bugs, and even then it may be a bit of time. But the more info I get now, the better we'll be once work starts on it =D

**Comment by blitzmann** [comment]
Had a bit of time tonight to work on adding Citadel features to pyfa. So far it's been pretty straight forward. I'm working on my own playground branch: https://github.com/blitzmann/Pyfa/tree/citadel

Fittings work, but no effects have been implemented. Not only that, but current character skills are being applied to the citadels - I am not sure quite yet how I'm going to restrict it to only apply to ships and yet be able to apply effects to the citadel itself.

**Comment by blitzmann** [comment]
Took a look at this a bit more after putting it aside, and was able to restrict the skills that are applied to the structure.

**Comment by blitzmann** [comment]
reminder to myself that this is a thing

```
Traceback (most recent call last):
  File "C:\Users\Ryan\Sync\Git\blitzmann\Pyfa\gui\droneView.py", line 165, in fitChanged
    self.Parent.Parent.DisablePage(self, not fit or fit.isStructure)
  File "C:\Users\Ryan\Sync\Git\blitzmann\Pyfa\gui\chromeTabs.py", line 235, in DisablePage
    self.SetSelection(next(i for i, _ in enumerate(self.pages) if not self.tabsContainer.tabs[i].disabled))
StopIteration
```

**Comment by Ebag333** [comment]
Some more to add to the list:

- Can't see ammunition item stats
- Missile low mods don't seem to affect the stats (hard to confirm)
- Missing standup rigs?

**Comment by blitzmann** [comment]
Missile low mods were fixed with recent commit.

Totally forgot about rigs. Added those and fixed a bug in the market search as well. c3983a26c5ba0c8d0d7409016dbd50838ca4e19d

**Comment by Braineh** [comment]
There is a calculation failure with rigs giving bonuses using % with citadels. e.g. the Point Defense Battery got a default area of effect of 2500m, rigged with Gen1 rig which applies 500% bonus it shouldn't be 1.250.000m (2500x500) but 12.500m (2500x500%). Same goes for Missiles and the rigs.

**Comment by blitzmann** [comment]
@Braineh thanks, I'll add a bug tag until I can take a further look

**Comment by blitzmann** [comment]
Closing this issue as the feature was implemented a couple releases ago. All feature requests / bug report involving it should be reported in a new issue. :)
