### ISSUE TITLE
Right-clicking on fitted shield boost amps causes hang+crash

### ISSUE THREAD

**Issue by kikjezrous** [pyfa-org/Pyfa#543]
Other modules seem fine; it's just fitted shield boost amps.  So far, noticed it with SBA I and SBA II modules, not sure about meta.  Running Win 8, pyfa build 1.20.0

**Comment by blitzmann** [comment]
I cannot reproduce. Right clicking a shield boost amp is fine for me. Can you post the EFT fit? Can you also check `%userprofile%/.pyfa/log.txt`

**Comment by kikjezrous** [comment]
Launching pyfa also takes an extremely long time (60s+), so maybe I just need to reinstall.  The last instance of pyfa, I launched the application, loaded the following fit, and right-clicked on the boost amp.  It hung, greyscreened, and eventually had to be forcibly closed, causing the OS to hang slightly in the process.  (This is all typical and reproducible).  

The last log entry was from 2015, so I didn't bother to attach it.  

FIT:
```
[Caracal, Gurista Hunt?]

Damage Control II
Ballistic Control System II
Ballistic Control System II
Co-Processor I

Adaptive Invulnerability Field II
Large Ancillary Shield Booster, Navy Cap Booster 150
Shield Boost Amplifier II
Large Ancillary Shield Booster, Navy Cap Booster 150
1MN Afterburner II

Rapid Light Missile Launcher II, Guristas Scourge Light Missile
Rapid Light Missile Launcher II, Guristas Scourge Light Missile
Rapid Light Missile Launcher II, Guristas Scourge Light Missile
Rapid Light Missile Launcher II, Guristas Scourge Light Missile
Rapid Light Missile Launcher II, Guristas Scourge Light Missile

Medium Anti-Thermal Screen Reinforcer I
Medium Anti-Thermal Screen Reinforcer I
Medium Bay Loading Accelerator I
```

**Comment by blitzmann** [comment]
Can you please email me sable.blitzmann@gmail.com and attach your `~/.pyfa/saveddata.db` file. I still cannot reproduce, so I'm wondering if it's an issue with the database (also, want to debug the long load times)

**Comment by blitzmann** [comment]
Received file. Nothing is popping out at me. I can open the aforementioned fit and right click the Amp no problem. I am also not getting any slowdown at all. Did you just install this version?

Some things to try: It doesn't pop up with menu at all? How about module immediately above and below? Try to change characters and see if it happens with both default and user characters. Try off lining module, then try right clicking. Remove module, then add again and test.

If all that fails, try completely removing the pyfa installation (1.20.1 is the latest version anyway), keeping your saveddata.db. If it still persists, remove pyfa agin and reinstall, along with removing `~/.pyfa` directory.

**Comment by kikjezrous** [comment]
No menu, it immediately hangs.  Other modules are fine.  Removing the module and replacing it (even with different types of boost amps) still exhibits the behavior.  It hung for a brief moment when it was offlined, and then recovered.  Upon right-click, it hung+crashed like before.  Hangs with all-5 character, hangs with user char.  

I'll probably just update and reinstall.

**Comment by blitzmann** [comment]
Fucking hell, I hope this isn't another phantom mystery that only happens on certain machines, a la #441. Let me know how that reinstall works out. 

If it doesn't, I'll get you a few old versions and have you test if you don't mind.

**Comment by kikjezrous** [comment]
Upon reinstall it's working again.  No harm, no foul?

**Comment by blitzmann** [comment]
Weird. Well, glad it's working again =D
