### ISSUE TITLE
Empty ECCM and Sensor Backup Arrays groups in item browser

### ISSUE THREAD

**Issue by MrNukealizer** [pyfa-org/Pyfa#546]
The categories for the various types of ECCM are still there even though there's only one module in any of them. It's probably a bug that the 'Shady' Sensor Booster is still listed under ECCM in game, so that will likely change soon and mean the end of the ECCM category..

**Comment by MrNukealizer** [comment]
Also the Sensor Backup Arrays categories are empty except for the 'Firewall' Signal Amplifier.

**Comment by MrNukealizer** [comment]
And Projected ECCM except for the 'Bootleg' Remote Sensor Booster...

**Comment by blitzmann** [comment]
That's all sourced from the EVE data. I can look into disabling them manually, but CCP will (hopefully) clean them up eventually

**Comment by blitzmann** [comment]
I just checked on SISI and these market groups dont show up. So I'm not sure if it's an issue in pyfa or if the data was patched with sisi. I can take a look at this more closely later

**Comment by MrNukealizer** [comment]
Someone probably noticed when adding the new capital and citadel stuff. It'll probably be fixed on TQ when the update comes out.

**Comment by MrNukealizer** [comment]
Well as of the current version the categories still show up but are empty.

**Comment by blitzmann** [comment]
I figured before it was just CCP forgetting to remove them, but actually looking into this: we are sourcing data from a resource that does not specify `hasTypes` for market groups, which would normally tell us if we have any items at all under that group. I don't know when this changed and how long pyfa has been improper due to it, but I will look into it soonish. AS of right now, it's not a major concern though.

**Comment by blitzmann** [comment]
I think I got it working by utilizing `marketProxy()_GetMarketGroups()` which is a cache of the market tree stored by the eve client. This has the values we need. I'll mark this fixed when I'm able to commit the fixes to the database. In the meantime, a fixed database:

[eve.zip](https://github.com/pyfa-org/Pyfa/files/243990/eve.zip)

**Comment by blitzmann** [comment]
I kinda of fixed this by using data from the cache that has the `hasType` properties. There's still a bug that causes ECCM to show up, but at least it no longer has any children.

**Comment by blitzmann** [comment]
Have to manually remove the ECCM market group.
