### ISSUE TITLE
Sensor Boosters loaded with ECCM Script don't display bonus

### ISSUE THREAD

**Issue by TheJokr** [pyfa-org/Pyfa#547]
When using a scripted Sensor Booster the Optimal/Falloff tab will display the bonus provided by the script, but if the Sensor Booster is loaded with an ECCM Script that information is missing.

Example:
![Example](https://cloud.githubusercontent.com/assets/7347535/14059971/b2563a38-f354-11e5-9f4d-0138909e5d6d.png)

**Comment by Ebag333** [comment]
#643
