### ISSUE TITLE
Use HTTPS for jQuery CSS and JS

### ISSUE THREAD

**Issue by richy58729** [pyfa-org/Pyfa#549]
I'm using the exported HTML page on a web site with HTTPS.

Because the included stylesheet and JavaScript files from jQuery are HTTP URLs, they get blocked by at least Mozilla Firefox and Google Chrome, as including non-SSL content from an SSL web page is considered to be insecure.

Because those files are also available via HTTPS ([http**s**://code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.min.css](https://code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.min.css), [http**s**://code.jquery.com/jquery-1.11.0.min.js](https://code.jquery.com/jquery-1.11.0.min.js) and [http**s**://code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.min.js](https://code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.min.js) are all reachable, I checked), I would like for you to consider changing that in the exported HTML.

In that case it would always work, regardless whether this HTML file is viewed on a website with or without SSL.

**Comment by blitzmann** [comment]
I don't see a problem with this, just need to test it out. The HTML page needs a little work as a whole to be honest, but I figured it's use has declined since the introduction of Copy from Clipboard in the EVE client.

**Comment by richy58729** [comment]
Much obliged.

At least I still use the HTML export functionality; in fact, I even wrote a small AutoIt script to do it automatically and send it to my web server...

Some arguments as to why I think you should take the time to implement this: the search function of the web page is pretty handy and yes, pyfa itself also has a search function, but for that, I need to click first and with the web page I can just start typing (I'm a lazy bastard, I know). Also, with the HTML export, I have this data available on whatever computer, as long as I have a web browser, which is just awesome IMHO.

So, I hope I have convinced you to implement it in your code, test it and have it ready in a future version of pyfa... By the way, I **love** pyfa; when pyfa became available, I stopped using EFT.

**Comment by blitzmann** [comment]
<3

Also, in case you didn't know, there is an option in the user preferences to automatically generate the HTML document whenever a change is made. Use with caution though - it's a threaded processes which doesn't block the GUI, but we've always and reports of it possibly causing crashes (most likely because it's accessing database at same time as main program). I've never had the motivation to look into it as it's fairly elusive to reproduce. I've used it without issue before, but others have a lot of problems with it. YMMV.

**Comment by narthollis** [comment]
Rather than switching to https links, It would be better to use protocol
relative links.

```
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="//code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.min.js
"></script>
```

**Comment by blitzmann** [comment]
@narthollis I don't think that would work when opening the file locally. The protocol would be `file://` in that case, and thus not load. Not tested >_>

**Comment by narthollis** [comment]
On 30 March 2016 at 09:11, Ryan Holmes <notifications@github.com> wrote:

> @narthollis <https://github.com/narthollis> I don't think that would work
> when opening the file locally. The protocol would be file:// in that
> case, and thus not load. Not tested >_>
>
>
Ah, yeah - good point. I hadn't thought about opening the file. In that
case using a hard https:// reference would be best.

**Comment by blitzmann** [comment]
Done. Also fixed an issue where it wasn't loading in Chrome - who knows for how longs it's been like that x_x

**Comment by richy58729** [comment]
Nice going, guys, thanks very much!
