### ISSUE TITLE
Non adaptive shield resist buffers don't register in the shield ehp/s recharge rate.

### ISSUE THREAD

**Issue by Ligraph** [pyfa-org/Pyfa#551]
The fit with the Adaptive shield resist buffer (fit 1) has much more EHP/s regen than the other fit (fit 2).  The problem is that the second fit has the same EHP/s as if it didn't have the EM Ward Amp.

Fit 1:
[Maelstrom, Maelstrom Wher]

Capacitor Flux Coil II
Capacitor Flux Coil II
Capacitor Flux Coil II
Gyrostabilizer II
Gyrostabilizer II

Adaptive Invulnerability Field II
Adaptive Invulnerability Field II
Shield Boost Amplifier II
Cap Recharger II
X-Large Shield Booster II
Large Micro Jump Drive

Dual 650mm Repeating Cannon II, Hail L
Dual 650mm Repeating Cannon II, Hail L
Dual 650mm Repeating Cannon II, Hail L
Dual 650mm Repeating Cannon II, Hail L
Dual 650mm Repeating Cannon II, Hail L
Dual 650mm Repeating Cannon II, Hail L
Dual 650mm Repeating Cannon II, Hail L
Salvager II

Large Capacitor Control Circuit II
Large Capacitor Control Circuit II
Large Capacitor Control Circuit I

Praetor II x3
Acolyte II x2
Acolyte II x3
Curator I x4
Hobgoblin I x5

Infiltrator II x5

859.8 EHP/s

Fit 2:
[Maelstrom, Maelstrom Wher]

Capacitor Flux Coil II
Capacitor Flux Coil II
Capacitor Flux Coil II
Gyrostabilizer II
Gyrostabilizer II

Adaptive Invulnerability Field II
EM Ward Amplifier II
Shield Boost Amplifier II
Cap Recharger II
X-Large Shield Booster II
Large Micro Jump Drive

Dual 650mm Repeating Cannon II, Hail L
Dual 650mm Repeating Cannon II, Hail L
Dual 650mm Repeating Cannon II, Hail L
Dual 650mm Repeating Cannon II, Hail L
Dual 650mm Repeating Cannon II, Hail L
Dual 650mm Repeating Cannon II, Hail L
Dual 650mm Repeating Cannon II, Hail L
Salvager II

Large Capacitor Control Circuit II
Large Capacitor Control Circuit II
Large Capacitor Control Circuit I

Praetor II x3
Acolyte II x2
Acolyte II x3
Curator I x4
Hobgoblin I x5

Infiltrator II x5
Adaptive Invulnerability Field II x1

**Comment by Ebag333** [comment]
This seems to work correctly in the current branch.

Fit 1 has 35.5 HP/s passive omni, 25.8 HP/s passive with a 100% EM damage profile.

Fit 2 has 30.7 HP/s passive omni, 32.8 HP/s passive with a 100% EM damage profile.

Fit 2 (with the EM ward amp offline) has 26.3 HP/s passive omni, 19 HP/s passive with a 100% EM damage profile.

As this all looks correct to me, recommend we close this.

**Comment by DarkFenX** [comment]
Agreed.
