### ISSUE TITLE
Propulsion Subsystems do not get accepted

### ISSUE THREAD

**Issue by Rick5000** [pyfa-org/Pyfa#553]
When trying to import this fit:

[Legion, Booster]

Caldari Navy Co-Processor
Caldari Navy Co-Processor
Caldari Navy Co-Processor
Caldari Navy Co-Processor

Command Processor I
Command Processor I
Command Processor I
Command Processor I

Skirmish Warfare Link - Interdiction Maneuvers II
Skirmish Warfare Link - Rapid Deployment II
Information Warfare Link - Electronic Superiority II
Armored Warfare Link - Damage Control II
Armored Warfare Link - Passive Defense II
Sisters Expanded Probe Launcher
Covert Ops Cloaking Device II

Medium Processor Overclocking Unit II
Medium Low Friction Nozzle Joints I
Medium Low Friction Nozzle Joints I

Legion Defensive - Warfare Processor
Legion Engineering - Capacitor Regeneration Matrix
Legion Offensive - Covert Reconfiguration
Legion Electronics - Emergent Locus Analyzer
Legion Propulsion - Interdiction Nullifier

EVE gives me the following error:
http://prntscr.com/aq1rqj 
"The fitting you are trying to save has corupted data. The flag information for item Legion Propulsion - Interdiction Nullfiier is invalid"

All my fittings with a T3 Cruiser do not get accepted by EVE - It denies all "Propulsion" subsystems for some reason.
I have the newest version.

Please help me!

EDIT: Importing via "clipboard" does work. Files do not.

**Comment by blitzmann** [comment]
I believe EVE requires them to be exported in a specific order. We had the same issue with HTML export/import and had to fix the order. Didn't know XML was affected as well. i'll look into it.

**Comment by blitzmann** [comment]
Fixed, will be available with the next release

**Comment by Rick5000** [comment]
Awesome, you rock!
