### ISSUE TITLE
Logi frigate skills not affecting shield booster cap usage

### ISSUE THREAD

**Issue by IslayTzash** [pyfa-org/Pyfa#555]
I'm playing with a logi frig fit.  I've only got the first remote shield booster marked active.   If I change the logi frigate skill from the shield booster > change module skills > logi frigates, the cap usage for the ship and that module always reads -5.8 GJ/s.   The module attributes (activation cost & duration) do change after adjusting the logi frigate skill, and I calculate a different GJ/s.  Is there something more complicated to this calculation.

logi frig skill                 |      1    |     4
-----------------------------|----------|---------
activation cost (GJ)   |   22  |   18.6
duration (s)                |   3.8  |  3.2
Expected GJ/s           |  5.74 | 5.62
Displayed GJ/s           |  5.8 | 5.8

pyfa 1.20.1, stable march 2015, 1.3, win 10

[Scalpel, Test]

Capacitor Power Relay II
Power Diagnostic System II
Damage Control II

5MN Quad LiF Restrained Microwarpdrive
Medium Azeotropic Restrained Shield Extender
Adaptive Invulnerability Field II
Small Capacitor Booster II, Cap Booster 200

Small S95a Scoped Remote Shield Booster
Small S95a Scoped Remote Shield Booster
Small S95a Scoped Remote Shield Booster

Small Core Defense Field Extender I
Small Core Defense Field Extender I

Warrior II x1

Nanite Repair Paste x100
Navy Cap Booster 200 x43

**Comment by blitzmann** [comment]
The math is as such:
```
    @property
    def capUse(self):
        capNeed = self.getModifiedItemAttr("capacitorNeed")
        if capNeed and self.state >= State.ACTIVE:
            cycleTime = self.cycleTime
            capUsed = capNeed / (cycleTime / 1000.0)
            return capUsed
        else:
            return 0
```

It isn't complicated at all, we basically take the cap use and divide by duration to get cap/s. I'm not sure I understand your issue though, as I believe you have some errors in your math.  For example, your expected GJ/s for level 1, based on your values, should be `5.7894`, not `5.74`, and for log 4 it should be `5.8125`, not `5.62`. Couple that with general rounding errors, and you should get something similar to the expected. Could you confirm or elaborate on your math for me?

If you are still concerned about the math being off, send me your `saveddata.db` file and point me to a fit that is displaying the issue and I can take a look at it. My email is listed on the pyfa README. =)

**Comment by IslayTzash** [comment]
**I think pyfa does get this right, no further action required.**  

I was originally trying to investigate if this combined bonus -- _**_5% reduction in remote shield booster activation cost & duration_**_ -- results in zero net change to capacitor cost?   It appears I screwed up the math while answering it and the answer should have been _mostly yes_, there is a tiny cost savings but it is below the number of significant digits presented by pyfa.

Ship stats:
  * logi frig: 5% reduction in remote shield booster activation cost & duration
  * minmatar frig: 10% bonus in activation cost
![image](https://cloud.githubusercontent.com/assets/18371221/14942300/690bae46-0f86-11e6-82e8-149680da47af.png)

0 Minmatar Frig / 0 Logi Frig == -34.8 GJ/s total / -11.6 per booster
![image](https://cloud.githubusercontent.com/assets/18371221/14942276/ccd67a6a-0f85-11e6-90a9-9e026a7be5a7.png)

5 Minmatar Frig / 0 Logi Frig == -17.4 GJ/s total / - 5.8 per booster [total really -17.437]
![image](https://cloud.githubusercontent.com/assets/18371221/14942280/f90877dc-0f85-11e6-82b8-f392a69ad219.png)

5 Minmatar Frig / 5 Logi Frig == -17.4 GJ/s total / - 5.8 per booster  [total really -17.368, display is same as 5/0]
![image](https://cloud.githubusercontent.com/assets/18371221/14942287/2ebe824a-0f86-11e6-91ba-ddb4decdc619.png)



[Scalpel, Deadshot's Healing]

Capacitor Power Relay II
Power Diagnostic System II
Damage Control II

5MN Quad LiF Restrained Microwarpdrive
Medium Azeotropic Restrained Shield Extender
Adaptive Invulnerability Field II
Small Capacitor Booster II, Cap Booster 200

Small S95a Scoped Remote Shield Booster
Small S95a Scoped Remote Shield Booster
Small S95a Scoped Remote Shield Booster

Small Core Defense Field Extender I
Small Core Defense Field Extender I


Warrior II x1


Nanite Repair Paste x100
Navy Cap Booster 200 x43

**Comment by blitzmann** [comment]
Glad you get it sorted out. =)
