### ISSUE TITLE
 Citadel Pre-Release: Siege/Triage/Bastion crash (singularity-1027729)

### ISSUE THREAD

**Issue by JoshuaNotowitz** [pyfa-org/Pyfa#558]
Siege and Triage mods appear to be broken and break fits when you attempt to fit them.

**Comment by blitzmann** [comment]
Hrm, yeah, I guess I should at least fit them next time to make sure they don't break.

Attached is a zip containing fixed effect files. Go ahead and copy these into the `pyfa/library.zip/eos/effects/` directory and allow it to overwrite the ones there. I'm going to leave this open so that others can find the fix.
[effect_files.zip](https://github.com/pyfa-org/Pyfa/files/218166/effect_files.zip)

**Comment by JoshuaNotowitz** [comment]
Siege isn't affecting phoenix range atm. it should be giving it a 150% bonus

**Comment by blitzmann** [comment]
Removing fixed label until I can take a look.

**Comment by blitzmann** [comment]
I can only confirm for Torps, not XL torps or cruise missiles. Is this the case ingame/sisi?

**Comment by Hoerks** [comment]
The networked sensor array also broke fits, I attempted to fix it.

Disclaimer: I have no actual idea how this code (or any other code, for that matter) works, but by replicating the changes you did to the bastion file I think I was able to unbreak it. Monkey see, monkey do. Use at your own discretion.

[networkedsensorarray.zip](https://github.com/pyfa-org/Pyfa/files/227866/networkedsensorarray.zip)

P.S. at least the Nidhoggur has the old, TQ base stats, not the new ones, that are on SiSi.

**Comment by blitzmann** [comment]
The SISI dump that the prerelease uses is not about a week old, so it's very possible some stats (such as cpu, etc) are incorrect to latest SISI.

I will take a look at the Network module and report back =)

**Comment by blitzmann** [comment]
Yep, that worked. Fixed on my branch =)

**Comment by hipplewm** [comment]
Where do you put this file on a Mac?

**Comment by JoshuaNotowitz** [comment]
hipplewm show package contents on pyfa, then 
<img width="1011" alt="screen shot 2016-04-22 at 10 51 48 am" src="https://cloud.githubusercontent.com/assets/8390690/14750213/76581694-0878-11e6-96ab-452cf649f99b.png"> is the path

**Comment by hipplewm** [comment]
I don't seem to have as many folders as you do.......I have show invisible files on

<img width="806" alt="screen shot 2016-04-22 at 5 03 06 pm" src="https://cloud.githubusercontent.com/assets/18379777/14754872/3d388306-08ac-11e6-9139-eeec657b6121.png">

**Comment by blitzmann** [comment]
@hipplewm the mac is a bit different. The source files are included with other python packages instead of separated as they wre in the windows build. So the path you are looking for is:

`pyfa.app\Contents\Resources\lib\python2.7\site-packages.zip\eos\effects`

I believe that you can't natively copy a file into a zip on OSX, so you'll have to extract `site-packages.zip`, moke the modifications, and zip it back up. =)

**Comment by hipplewm** [comment]
Hmm, well, I did what you said, worked fine, but now the program won't even start...Grrr

I'll just wait for the patch....

**Comment by blitzmann** [comment]
What do you get when you run `pyfa.app/MacOS/pyfa` directly from the terminal?

**Comment by hipplewm** [comment]
I get no such file or directory
i changed the directory to applications and still get the same thing, do I have to change the "MacOS" to my drive name? - edit, that didn't seem to work either

**Comment by hipplewm** [comment]
Hmm, ok, may have a bigger problem, even if i swap back to original sitepackages.zip, won't work, but I updated java after i ran it last.......wonder if that messed with something.  I running 8.91 now i think

**Comment by hipplewm** [comment]
OK, it didn't revert correctly, when I deleted the new zip and replaced with the old zip, it runs fine now

**Comment by blitzmann** [comment]
You may even be able to just unzip it and keep it unzipped as long as you get rid of the previous zip file. Also, make sure it's named `site-packages` and not `sitepackages` like your comment implies. =) If you can't get it to work, jut wait for the release next week

**Comment by hipplewm** [comment]
OK, unzipped the file, left it unzipped, swapped out the 3 files you made and the one file for the networksensor array and all works good, just left it unzipped.  Thanks

**Comment by JoshuaNotowitz** [comment]
@blitzmann i still use the deprecated version because I've had a couple problems with the new one, nothing major, just a little bit of overall performance but enough to make a difference

**Comment by blitzmann** [comment]
@JoshuaNotowitz what kind of performance issues? Also, are you using 10.11? Because I know theres a few graphical bugs with wx3 and 10.11 due to wxpython/wxwidgets itself... =(

**Comment by hipplewm** [comment]
10.10.5 here on a 2011 MBP

Runs just fine, no issues, but not a heavy user

**Comment by JoshuaNotowitz** [comment]
yea I'm on 10.11 Everything just seems to run slower, searching for fits, for mods, putting mods on, than on the deprecated version.

**Comment by blitzmann** [comment]
Marking this as fixed again as all items in here should have been addressed
