### ISSUE TITLE
Citadel Pre-Release: Character import not working (singularity-1027729)

### ISSUE THREAD

**Issue by master3553** [pyfa-org/Pyfa#559]
When putting in the KeyID and the vCode and press "Get Characters" I get "Error: 'CharacterEditor' object has no attribute 'getActiveCharater'".

**Comment by blitzmann** [comment]
This is with the pre release, correct? It's a known issue. This issue came up with another issue.

> In the meantime, you could potentially work around this by importing character to EVEMon, making a blank skillplan, and exporting that (which you then import to pyfa).

Try that, let me know if it works for you (worked for the other guy =)). It's not optimal, but this is something that will be fixed soon =)

**Comment by master3553** [comment]
This workaround is fine! Thanks!

**Comment by blitzmann** [comment]
Here's a proper fix:

Replace `pyfa/library.zip/gui/characterEditor.py` with this file: http://pastebin.com/xejewB4F
