### ISSUE TITLE
Citadel Pre-Release: Leviathan - adding charges issue (singularity-1027729)

### ISSUE THREAD

**Issue by RemovalTool** [pyfa-org/Pyfa#561]
I can add missile launchers to the Leviathan but it does not allow me to add charges as either a group or individually.  tested this with Rapid torps, XL torps and Xl cruise.

**Comment by blitzmann** [comment]
Thanks!

It seems that SISI data is incorrect, and that the leviathan effect for exp/therm/em bonus was actually pointing to non-existing dreadnaught attributes. I've fixed it. Please repalce `pyfa/library.zip/eos/effects/shipbonustitanc5alldamagebonus.py` with this file: http://pastebin.com/uhpHEL4x
