### ISSUE TITLE
Importing a skill plan from EveMon gives me better stats than All 5.

### ISSUE THREAD

**Issue by Ligraph** [pyfa-org/Pyfa#563]
I don't think this is intended.  Difference is ~100 dps and ~200 tank.

Skill plan is (should be) attached.

Fit:
[Svipul, Svipul PvP Shield MAIN]

Damage Control II
Gyrostabilizer II
Gyrostabilizer II
Micro Auxiliary Power Core I

J5b Enduring Warp Scrambler
5MN Y-T8 Compact Microwarpdrive
Medium F-S9 Regolith Compact Shield Extender
Medium F-S9 Regolith Compact Shield Extender

200mm AutoCannon II, Hail S
Small Gremlin Compact Energy Neutralizer
200mm AutoCannon II, Hail S
200mm AutoCannon II, Hail S
Small Gremlin Compact Energy Neutralizer
200mm AutoCannon II, Hail S

Small Core Defense Field Extender I
Small Core Defense Field Extender I
Small Core Defense Field Extender I

**Comment by blitzmann** [comment]
Skill plan was not attached. Please attach it or post it somewhere =)

**Comment by Ligraph** [comment]
[Skill plan](http://pastebin.com/rSjsDpYm)

**Comment by blitzmann** [comment]
![untitled](https://cloud.githubusercontent.com/assets/3904767/14593477/ccca4c78-04f8-11e6-9c53-830bafc37f5c.png)

Well this looks like it could be the reason... I'll look into it =)

**Comment by blitzmann** [comment]
Should be fixed. I overlooked the fact that the exported character can contain multiple entries of the same skill, so pyfa happily added these.
