### ISSUE TITLE
Warhead upgrades not listed in change module/charge skill menu

### ISSUE THREAD

**Issue by IslayTzash** [pyfa-org/Pyfa#565]
I don't see Warhead Upgrades listed in either menu.   It's listed in charge stats > affected by.

[Jackdaw, Jackdaw]

Damage Control II
Ballistic Control System II

Faint Epsilon Scoped Warp Scrambler
Medium Azeotropic Restrained Shield Extender
5MN Y-T8 Compact Microwarpdrive
Medium Ancillary Shield Booster
Medium Ancillary Shield Booster
Fleeting Compact Stasis Webifier

Rocket Launcher II, Mjolnir Rage Rocket
Rocket Launcher II, Mjolnir Rage Rocket
Rocket Launcher II, Mjolnir Rage Rocket
Rocket Launcher II, Mjolnir Rage Rocket
Rocket Launcher II, Mjolnir Rage Rocket
[Empty High slot]

Small Ancillary Current Router II
Small Anti-EM Screen Reinforcer II
Small Core Defense Field Extender II

Mjolnir Rage Rocket x1200
Scourge Rage Rocket x1785
Nova Rage Rocket x3000
Scourge Javelin Rocket x1475
Inferno Javelin Rocket x3000
Nanite Repair Paste x164
Navy Cap Booster 50 x42

**Comment by IslayTzash** [comment]
most likely related to #535

**Comment by blitzmann** [comment]
Yes, this should be a duplicate to #535. If you're interested in a fix, see #541 and apply those changes to your local files (source files are in `pyfa/library.zip/`). =)

**Comment by varrwillis** [comment]
Have the changes from #541 / #535 been pushed into a recent build? I have the latest release (pyfa 1.23.0 Stable - YC 118.7 1.4) and Warhead Upgrades is still missing from the Change Module Skills drop down for T2 Rocket Launchers.

**Comment by blitzmann** [comment]
@varrwillis yeah, this fix should have been brought into master branch months ago. If you're still experiencing issues, go ahead and open a new issue with details
