### ISSUE TITLE
Character Editor - API codes not working in charc creation

### ISSUE THREAD

**Issue by PallaraHazeMacLeod** [pyfa-org/Pyfa#566]
hi,  Iwas trying to get my character skills into pyfa, generated a key and no expiry.

Once I enter the key and VCode that has been generated for the API and press "Get Characters", the area below simply states "
- 'CharacterEditor' object has no attribute 'getActiveCharacter'

seems to not be able to pull the data through?

thanks! Pallara

**Comment by blitzmann** [comment]
duplicate #564
