### ISSUE TITLE
CREST Login breaks on idle

### ISSUE THREAD

**Issue by mkaito** [pyfa-org/Pyfa#567]
After logging into CREST and having the app idle for a while, it'll log itself out. Upon trying to log in again, I get this backtrace in the console:

```
Traceback (most recent call last):
  File "/usr/share/pyfa/gui/crestFittings.py", line 233, in ssoLogin
    self.updateCharList()
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 16707, in __getattr__
    raise PyDeadObjectError(self.attrStr % self._name)
wx._core.PyDeadObjectError: The C++ part of the ExportToEve object has been deleted, attribute access no longer allowed.
```

The same thing happens if I manually log out and try to log in again.

**Comment by blitzmann** [comment]
Sorry I never got around to troubleshooting and fixing this. Must have slipped through the cracks. It seems like it was a simple GUI issue. That being said, pyfa 2.x series removed CREST support and introduces ESI, so this issue is moot now. Thanks!
