### ISSUE TITLE
Charges doesn't get saved to fit when exporting with CREST

### ISSUE THREAD

**Issue by Nahaz** [pyfa-org/Pyfa#569]
Ammo & Charges are not being saved to fits when exporting via CREST, it seems to be working fine otherwise.

Pyfa 1.20.1

**Comment by blitzmann** [comment]
I think this is one of the things I meant to do, and put it off, and totally forgot about. =3

Cargo should export, correct? You're talking about currently loaded charges?

**Comment by Nahaz** [comment]
Yes, exactly

**Comment by blitzmann** [comment]
k, I'll look into it. Can't promise it comes with the next release though. =)

**Comment by blitzmann** [comment]
Should be done, however I tested it once. It may very well break. <_<
