### ISSUE TITLE
Can pyfa generate in-game links?

### ISSUE THREAD

**Issue by mkaito** [pyfa-org/Pyfa#575]
There are times I'd like to share one of my fits with someone, without first importing it to the fitting manager. I'm a pyfa warrior and have hundreds of fits, but try to keep the in-game manager as lean as I can, because otherwise I can never find anything. So copying a link from pyfa and pasting it in game would be awfully convenient, if that was somehow possible.

**Comment by MrNukealizer** [comment]
Well, you'd have to paste it in a note or mail then drag it to chat. You can't paste links directly to chat. That said, the ingame links are basically a little bit of extra text around what you get if you copy in DNA format. For example, an ingame link for a random Nidhoggur fit would look like this:`<url=fitting:24483:2048;1:4405;3:33983;1:2281;2:35662;1:40354;2:24417;1:12271;3:41411;1:24283;1:31163;3::>Awesome Name</url>`

Copying as DNA gives `24483:2048;1:4405;3:33983;1:2281;2:35662;1:40354;2:24417;1:12271;3:41411;1:24283;1:31163;3::` so it would be trivial to add the url tags and name.

**Comment by mkaito** [comment]
That's pretty interesting; I didn't know that. If you can't paste links straight into chat, that defeats the purpose (maybe?) of my suggestion. Please reopen if you find the notepad-workaround a good idea.
