### ISSUE TITLE
Omnidirectional Tracking Links show as passive modules

### ISSUE THREAD

**Issue by MrNukealizer** [pyfa-org/Pyfa#579]
Easy fix: Change type to "active" in https://github.com/pyfa-org/Pyfa/blob/master/eos/effects/modulebonusomnidirectionaltrackinglink.py

**Comment by blitzmann** [comment]
I really should write some basic tests to cover stupid, simple shit like this. =/

Those who have this issue and need a fix, the file is located in `pyfa/library.zip//eos/effects/modulebonusomnidirectionaltrackinglink.py`.
