### ISSUE TITLE
Small Ancillary Shield Booster - can't load charges

### ISSUE THREAD

**Issue by bran2k7** [pyfa-org/Pyfa#581]
The Small Ancillary Shield Booster does not have an option when right clicking to add charges. Also can't add charges by dragging a charge from the market to the module.
![image](https://cloud.githubusercontent.com/assets/18815608/14940294/296f3698-0f2e-11e6-870e-1b16a8cc7c3b.png)

**Comment by blitzmann** [comment]
Hi,

CCP changed the item group these things belonged to, so it's most likely the cause of it and was simply overlooked. I will look into it. =)

**Comment by blitzmann** [comment]
This seems to be due to CCP removing the charge size value for the ancillary shield booster, and so it can't match to the correct charges. 

Confirmed via CREST: https://crest-tq.eveonline.com/types/32774/

I'll get in touch with CCP and file a bug report.

**Comment by blitzmann** [comment]
Okay, so after speaking with CCP Larrikin, it seems that the mechanic has changed. `chargeSize = 0` is now a default which basically mean to only take the capacity into consideration.  Will be tweaking this shortly.
