### ISSUE TITLE
Hurricane and Hurricane Fleet Damage bonuses

### ISSUE THREAD

**Issue by Calavoow** [pyfa-org/Pyfa#584]
There is something strange going on with Hurricane and HFI hull bonuses. In the following two minimal fits, the hurricane actually has the higher amount of dps. I would expect the HFI to have the higher DPS.

```
[Hurricane Fleet Issue, Minimal]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

425mm AutoCannon II, Hail M
425mm AutoCannon II, Hail M
425mm AutoCannon II, Hail M
425mm AutoCannon II, Hail M
425mm AutoCannon II, Hail M
425mm AutoCannon II, Hail M
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]
```

```
[Hurricane, Minimal]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

425mm AutoCannon II, Hail M
425mm AutoCannon II, Hail M
425mm AutoCannon II, Hail M
425mm AutoCannon II, Hail M
425mm AutoCannon II, Hail M
425mm AutoCannon II, Hail M
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]
```

**Comment by blitzmann** [comment]
Hi. First off, thanks for supplying a minimal test to work off of. More people need to do that ;)

Secondly, the calcs are applying correctly from what I can see. I believe you are forgetting that the hurricane not only includes a damage bonus, but also a RoF bonus, which the HFI lacks. This increases the overall DPS applied. You can also see that the HFI has a higher volley than the Hurricane, which is to be expected as it gains 5% more damage per level.

Hope this clears it up for you. =)

**Comment by Calavoow** [comment]
Ah sorry, I did not notice the difference in bonuses. Thanks!
