### ISSUE TITLE
Capacitor Transfer amount for remote cap transfers borked when projecting on other ships

### ISSUE THREAD

**Issue by ZarosTenjin** [pyfa-org/Pyfa#585]
Heya,

i just updated to 1.21.0 and noticed a little different behavior on the amount of cap thats is projected on a fit by remote rep transfers
![pyfa 1 21 0 - python fitting assistant_002](https://cloud.githubusercontent.com/assets/17838944/14942651/6bb3d1ae-0fc3-11e6-967c-525e7a980979.png)

Disabling one transfer halves the 30k GJ ..

Example is an augoror projecting onto itself but also confirmed it with projecting onto other fits as well.

It seems to be a problem with the calculation instead of the module since with other module its also inflated but also reduced to reflect the meta tier of the module...
![pyfa 1 21 0 - python fitting assistant_003](https://cloud.githubusercontent.com/assets/17838944/14942663/05590a4a-0fc4-11e6-9ac8-a448c1fe395e.png)

Cheers 
Zaros

**Comment by blitzmann** [comment]
Oh look, I'm setting the amount to the modules max range. 

```
def handler(fit, module, context):
    if "projected" in context:
        amount = module.getModifiedItemAttr("maxRange")
        duration = module.getModifiedItemAttr("duration")
        fit.addDrain(duration, -amount, 0)
```
Fail (and fixed)
