### ISSUE TITLE
unresponsive+crash when showing modules

### ISSUE THREAD

**Issue by locten** [pyfa-org/Pyfa#590]
hi every time i launch pyfa it seems to work fine until there is a module shown on screen as well as a ship eather by importing a fit or browsing market tab users/me/.pyfa/log remains empty.
i am on windows 7 64bit and have tryed laters and the previous version of pyfa.
![crash](https://cloud.githubusercontent.com/assets/19159045/14971776/6b3c03ee-10cd-11e6-8d8b-ede0d97e9710.png)
![fine 1](https://cloud.githubusercontent.com/assets/19159045/14971778/6b40161e-10cd-11e6-9b4a-e21f41c67249.png)
![fine 2](https://cloud.githubusercontent.com/assets/19159045/14971777/6b3ec94e-10cd-11e6-9fcc-75c7b58fc519.png)

**Comment by blitzmann** [comment]
Hi,

There are other folks reporting issues with crashing that may be related. I am not sure I understand your situation though. pyfa works fine up until a ship is loaded, or it works fine up until you add / remove a module?  What if you load a blank fit, or add a new fit? What about if you add drones, and not modules?

Let me know these things, and also anything else you notice. Thanks!

**Comment by locten** [comment]
Ok after some further testing it seems to be a random crash whenever i have a empty ship loaded and start looking through the market tab (including implants and drones) also loading an all ready fitted ship crashes it to. it may be related to the other issue but not sure.

**Comment by locten** [comment]
clarification i don't have to actually add anything to the fit just get to the point where it shows the modules in the bottom left or on a ship.

**Comment by blitzmann** [comment]
Does this happen with every fit?

**Comment by locten** [comment]
yes have tried it with at least 5 different ships

**Comment by blitzmann** [comment]
Okay. I'm fairly certain that this is related to #598. I'm going to close this issue, can you please post / subscribe to that thread? Thanks!
