### ISSUE TITLE
Lif, Ninazu cycle time bonus

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#591]
Can't determine if this is a bug on CCPs side, or simply a new way they are doing things. I am not able to test in game at the moment.

The Lif Remote Rep cycle bonus effect has the following modifiers:

```
shipBonusForceAuxiliaryM1RemoteCycleTime

Modifier 1:
   state: offline
   scope: local
   srcattr: shipBonusForceAuxiliaryM1 2317
   operator: post_percent 8
   tgtattr: duration (not penalized) 73
   location: ship
   filter type: skill
   filter value: Capital Remote Armor Repair Systems
Modifier 2:
   state: offline
   scope: local
   srcattr: shipBonusForceAuxiliaryM1 2317
   operator: post_percent 8
   tgtattr: duration (not penalized) 73
   location: ship
   filter type: skill
   filter value: Remote Armor Repair Systems
Modifier 3:
   state: offline
   scope: local
   srcattr: shipBonusForceAuxiliaryM1 2317
   operator: post_percent 8
   tgtattr: duration (not penalized) 73
   location: ship
   filter type: skill
   filter value: Shield Emission Systems
Modifier 4:
   state: offline
   scope: local
   srcattr: shipBonusForceAuxiliaryM1 2317
   operator: post_percent 8
   tgtattr: duration (not penalized) 73
   location: ship
   filter type: skill
   filter value: Capital Shield Emission Systems
```
We utilize this effect on all modues that require Remote Armor Repair Systems, Capital Remote Armor Repair Systems, Shield Emission Systems, or Capital Shield Emission Systems. The problem is that Capital remote reps utilize both the capital skill and sub cap skill (eg, Capital Armor Remote Rep requires both `Remote Armor Repair Systems` and `Capital Remote Armor Repair Systems`).

This makes it so that the effect is run twice as each Capital Remote Rep module matches on two of the modifiers. 

here's effect code for pyfa:

```
# shipBonusForceAuxiliaryM1RemoteCycleTime
#
# Used by:
# Ship: Lif
type = "passive"
def handler(fit, src, context):
    fit.modules.filteredItemBoost(lambda mod: mod.item.requiresSkill("Shield Emission Systems"), "duration", src.getModifiedItemAttr("shipBonusForceAuxiliaryM1"), skill="Minmatar Carrier")
    fit.modules.filteredItemBoost(lambda mod: mod.item.requiresSkill("Capital Shield Emission Systems"), "duration", src.getModifiedItemAttr("shipBonusForceAuxiliaryM1"), skill="Minmatar Carrier")
    fit.modules.filteredItemBoost(lambda mod: mod.item.requiresSkill("Remote Armor Repair Systems"), "duration", src.getModifiedItemAttr("shipBonusForceAuxiliaryM1"), skill="Minmatar Carrier")
    fit.modules.filteredItemBoost(lambda mod: mod.item.requiresSkill("Capital Remote Armor Repair Systems"), "duration", src.getModifiedItemAttr("shipBonusForceAuxiliaryM1"), skill="Minmatar Carrier")

```

**Comment by lunedis** [comment]
I tested it on sisi and the bonus is indeed applied there twice as well.

A Lif with Triage and one Remote Shield Booster has 2.25s cycle time on Sisi.

**Comment by jyxu2015** [comment]
But these skills do not have a bonus in cycle times...they only make a reduction in the capacitor amount used.

**Comment by blitzmann** [comment]
@jyxu2015 not sure what you mean. This issue is about the cycle time bonus attached to the Lif and Ninazu.

**Comment by blitzmann** [comment]
This looks like it's still an issue on CCPs side as of Citadel 1.11

**Comment by blitzmann** [comment]
> CCP Larrikin [5:25 AM] 
> Hey mate. Hrm, so `shipBonusForceAuxiliaryM1RemoteCycleTime` now only effects the cycle time of modules that require `Shield Emission Systems` and `Remote Armor Repair Systems`
> IDK why the API is still showing capital skills

So... yeah. I'll be able to fix these effects for the next point release. I'll also try to go through other cap effects / modules and double check them...
