### ISSUE TITLE
remote shield boosters not working with links correctly

### ISSUE THREAD

**Issue by teenkertoy** [pyfa-org/Pyfa#592]
Just downloaded PYFA for the first time, trying to get the numbers to match what I'm used to seeing in EFT.

Built a Nighthawk with three shield links and the implant
Built a Kirin with remote shield transporters
Built a combat assault frigate

Opened assault frigate, selected Nighthawk as squad booster.  Shield resistances of the assault frigate match EFT.  Added Kirin as projected effect, numbers match EFT.

The problem is when I add the Nighthawk to the Kirin as a squad booster, the remote shield transporters on the Kirin are enhanced but the amount of remote repairs going to the assault frigate do not change.

Am I doing something wrong?

**Comment by blitzmann** [comment]
It's seems to be a bug, related to #582. It seems I did not get all the runtimes I needed. Will fix and post results here so that you can apply them you your pyfa install
