### ISSUE TITLE
Remote repair cycle time bonuses on ninazu and lif do not work correctly

### ISSUE THREAD

**Issue by jyxu2015** [pyfa-org/Pyfa#593]
A capital remote armor repairer has a cycle time of 12 seconds without any fleet effect.
A triage module reduce the cycle time by 75%
So a capital remote armor repairer on Apostle has a cycle time of 3 seconds in triage.
...
Gallente Carrier bonuses on Ninazu (per skill level):
5% bonus to Remote Armor Repairer and Remote Shield Booster cycle time.
...
However, a capital remote armor repairer on Ninazu has a cycle time of 1.69 seconds in triage. (1.69=3\*0.75\*0.75)  [http://i.imgur.com/ImuHgyK.jpg](url)
It seems the bonuses are calculated twice.

Similar issue happens on Lif as well.

**Comment by lunedis** [comment]
Partly duplicate with #591

**Comment by blitzmann** [comment]
Can confirm, this is the same as #591 - they dont share the same effect, but both effects are similar and have the same cause. Closing.
