### ISSUE TITLE
Strategic cruisers show still no slots in version1.21.1

### ISSUE THREAD

**Issue by mydogspies** [pyfa-org/Pyfa#594]
Any ship I add, including Tactical Destroyers, shows low/med/high but nothing except for rig slots show when adding a fresh Strategic Cruiser fit. Import for T3 cruisers still does not work either. Any ideas?

![bug_legion_example](https://cloud.githubusercontent.com/assets/18701250/14978559/e433a6ea-111c-11e6-810b-2e721221ee3c.jpg)

**Comment by bran2k7** [comment]
I think I've read that it has to do with how CCP puts the subsystems first or something which for the fitting tools throws it off since they read looking for the slots in a certain order and the reach subsystems and stops looking for the h/m/l slots. But either way I've got the same issue

**Comment by blitzmann** [comment]
Yeah, slots are determined by the subsystems you have installed. So go ahead and add those and you should be good to go ;)
