### ISSUE TITLE
Module stats window formatting

### ISSUE THREAD

**Issue by bran2k7** [pyfa-org/Pyfa#596]
Noticed this subsystem and others seem to not have consistent line spacing between flavor text and bonus
![image](https://cloud.githubusercontent.com/assets/18815608/14993467/20eb753a-1128-11e6-988f-dc294317d741.png)

**Comment by blitzmann** [comment]
I believe this is more of an issue with the data that we get back from the EVE client. I'll take a look and see if there is something we can do about this.
