### ISSUE TITLE
EWAR Resists

### ISSUE THREAD

**Issue by Raikia517** [pyfa-org/Pyfa#597]
The titan stasis web resist of 80% is not properly calculated.  It shows as being webbed with no resists

**Comment by blitzmann** [comment]
This is mentioned in the release notes

> Unfortunately, time did not allow to implement some of the more intricate details of this release, such as EWAR resistance for certain ship hulls, or taking into account fighter refueling in the DPS. I am open to suggestions on how to best implement some of those features, and if you notice anything missing that should be part of future releases, let us know on out Issues page. =)

It's something I will definitely be doing in the coming weeks though, once things die down a bit.

**Comment by blitzmann** [comment]
I worked on this a bit last night. It's kinda hackish, not as smooth as I'd like it, but it works. It requires a new parameter for remote effects to tell the effect modifier code to check for ewar resistances on the target fit. I'll get this implemented and rolled out hopefully by the next point release (aiming for later this week)

**Comment by blitzmann** [comment]
Tested:

* [ ] Tracking Disruptors
* [ ] Missile Disruptors
* [ ] Target Painting
* [ ] Stasis Web
* [ ] Stasis Grappler
* [ ] Remote Reppers
