### ISSUE TITLE
Fighter stats NA?

### ISSUE THREAD

**Issue by PixelatedFitz** [pyfa-org/Pyfa#599]
I just downloaded 1.21.1 Citadel, I was attempting to test out a fit in a carrier but none of the drone stats show. DPS is not calculated, HP, speed and tracking stats of fighters are also not shown either.

http://prntscr.com/b07f1b

**Comment by blitzmann** [comment]
Right click on the fighters and select the abilities you want. The DPS is tried to their abilities, which are toggled by the user. Without active abilities, they just sort of buzz around.

**Comment by blitzmann** [comment]
Speed is already shown (it's between the fighter name and fighter abilities). Tracking and HP are planned, just haven't gotten around to implementing them yet =/
