### ISSUE TITLE
Capital Flex Hardeners cap use does not get adjusted by skill "Resistance Phasing"

### ISSUE THREAD

**Issue by Grookshank** [pyfa-org/Pyfa#601]
The capital flex shield hardener gets 10% reduced cycle time and 15% reduced cap usage per level of "Resistance Phasing". Pyfa does not seem to take the skill into account atm (Version 1.21.1).

The module has a base cap usage of 3.600 and a base cycle time of 60s, so base cap usage is 60/s.

When I adjust the level of the skill "Resistance Phasing", the cap usage stays 60/s, while it should go down.

**Comment by blitzmann** [comment]
Thanks, I'll take a look at it this weekend.

**Comment by Helothane** [comment]
The code added looks like it only addressed the Reactive Armor Hardener and the Capital Flex Armor Hardener, not the Capital Flex Shield Hardener.

**Comment by blitzmann** [comment]
This is the relevant code:

`lambda mod: mod.item.requiresSkill("Resistance Phasing")`

it basically says that the effect applies to all modules that requires that skill, which covers both armor and shield flex. It's confusing as the effect name itself has `ArmorHardener` in it, but it's just the way CCP did it =)
