### ISSUE TITLE
Siege/Triage Module EWAR Resistances not working

### ISSUE THREAD

**Issue by sHaanQ** [pyfa-org/Pyfa#602]
Since the Citadel expansion the Siege and Triage Modules apply an EWAR resistance on the FAX/Dread. I just applied a Tracking Disrupter(Optimal Range Script) to a HAW Moros and it reduced the Optimal Range + Falloff by the normal TD amount, not the 80% reduced.

Thanks ;)

**Comment by blitzmann** [comment]
Duplicate #597. It's also mentioned in the release notes that it's planned, just didn't get around to it. =)
