### ISSUE TITLE
Not importing module

### ISSUE THREAD

**Issue by robmburke** [pyfa-org/Pyfa#607]
Small Compact Pb-Acid Cap Battery will not import from EFT layout in clipboard

**Comment by blitzmann** [comment]
can you please post the eft format of the fit that your trying to import?

**Comment by blitzmann** [comment]
Not going to label this a a bug since it's really CCPs issue: the module in question has trailing whitespace in the database, which is from CCP. This means that we aren't able to find this module. I've fixed it by modifying our json2sql script to account for it.

**Comment by robmburke** [comment]
Sorry. Forgot about this. I saw that as well. I removed the trailing whitespace and it still wasn't working. I understand why now. Thanks.
