### ISSUE TITLE
Middle click to close fitting windows

### ISSUE THREAD

**Issue by vectorman1** [pyfa-org/Pyfa#608]
I would very much like to see this feature to get implemented. I am very used to closing Chrome tabs with middle click and tbh the X on the fitting windows are too goddamn small + the windows resize depending how many there are, therefore making it hard to close all of them at once.

Thanks!

**Comment by blitzmann** [comment]
This used to work IIRC, I'll take a look at it.

**Comment by blitzmann** [comment]
Hrm, maybe this wasn't ta hing before. Looking into it now.

**Comment by blitzmann** [comment]
That was pretty easy. =)

**Comment by vectorman1** [comment]
good thing it was an enhancement and not a bug because working out what exactly breaks a middle mouse click i suppose would've been a nightmare
