### ISSUE TITLE
cx_Freeze: Python error in main script

### ISSUE THREAD

**Issue by vahaul** [pyfa-org/Pyfa#609]
Hello. When i starting Pyfa those message appears and program doesnt runs. Reinstalling Python doesnt helps.
![snap 2016-05-08 at 19 12 18](https://cloud.githubusercontent.com/assets/19253020/15098892/f1cb9834-1550-11e6-8201-1fc1218ba69a.png)

**Comment by blitzmann** [comment]
Are you upgrading from a relatively old version? The directory structure changed last year and this looks like an error that stems from that. Can you post the contents of `%userprofile%\.pyfa\log.txt`?

After you post the contents of the log (if anything), try to completely delete the pyfa directory, and reinstall. Might be a good idea to delete `%userprofile%\.pyfa` as well (backup `saveddata.db` if you want to keep your fits)

**Comment by vahaul** [comment]
[log.txt](https://github.com/pyfa-org/Pyfa/files/253997/log.txt)
There is my .log

**Comment by blitzmann** [comment]
Whelp, the log doesn't show much. Go ahead and delete the pyfa directory and reinstall, let me knoe what happens.

**Comment by vahaul** [comment]
Delete pyfa and reinstall it and reboot pc, nothing changed...

**Comment by vahaul** [comment]
Those error 1st time appear when i delete "avast" antivirus program.

**Comment by blitzmann** [comment]
Can you please zip the pyfa directory (right click -> send to -> compressed file) and upload it to evefiles here: http://www.eve-files.com/upload.aspx. I want to see what the directory structure looks like

Then post the link here.

What version did you upgrade from? When was the last time it worked? Try to disable antivirus, and run as admin.

**Comment by vahaul** [comment]
Now i using "Zillya!" antivirus program becouse "Avast" makes too much load on cpu thats why i stop to use it. 
Tryed to diasable antivirus and run as administrator but still same resoult - nothing.
There is url - http://dl.eve-files.com/media/1605/pyfa.7z

**Comment by blitzmann** [comment]
Also, are you just extracting the zip file or using the .exe installer?

The link you sent does not exist. Instead of 7z (which I don't know if eve files supports), do a `.zip`

Did this only happen when you switched antivirus?

**Comment by vahaul** [comment]
I used .exe installer.
Don't sure that it is connected just this error make his place after removing avast, while avast was "on board" it works, when avast was delete and few days have pass i try to run Pyfa and find those error.
http://dl.eve-files.com/media/1605/pyfa.zip

**Comment by blitzmann** [comment]
Youre missing a file in your root pyfa directory. My guess is that the antivirus is deleting it when its installed. Try disabling all antivirus, deleting pyfa, and reinstalling

**Comment by vahaul** [comment]
Its helps. Add pyfa's folder to antivirus exceptions folder. Thankyou very much for helping. Is there anything i need to do?

**Comment by blitzmann** [comment]
Did you get it working after adding it to the antivirus exceptions? If it's still not working, download this file and put it in your pyfa root (alongside pyfa.exe), and it (hopefully) will work:

https://github.com/pyfa-org/Pyfa-skel/raw/master/win/wx._gizmos.pyd

**Comment by vahaul** [comment]
Adding pyfa's folder to antivirus exceptions helps.

**Comment by blitzmann** [comment]
Excellent. In that case, I'm going to close this issue. Glad you got it working =)
