### ISSUE TITLE
Modules from a stack vanish after fitting them from the cargohold

### ISSUE THREAD

**Issue by ZarosTenjin** [pyfa-org/Pyfa#610]
Hey, was messing around with refitting and with following situation arose (Version 1.21.1):

![selection_006](https://cloud.githubusercontent.com/assets/17838944/15100613/f95dfd82-1576-11e6-8f67-90b269dfb41a.png)

I have 2 Remote Sensor Boosters II in my cargo and two free med slots now if i drag and drop the stack onto a free medslot i would expect it to take a single of the remote sensor boosters and fit it onto the dragged on med slot. But the following behavior is observed:

![selection_007](https://cloud.githubusercontent.com/assets/17838944/15100622/4a170a7a-1577-11e6-8dd1-cd6aa6ac0868.png)

After dragging the stack the whole stack is removed from the cargohold and a single remote sensor booster II is equipped in the med slot effectively deleting the spare remote sensor booster from the cargohold.

If this is is expected behavior i'm sorry but it seems curious to me.

Cheers
Zaros

**Comment by blitzmann** [comment]
Hmm, yeah I'll look at it. That'd not expected behavior

**Comment by blitzmann** [comment]
I fixed this, as well as incremented items that were already in the cargo (for example, if you're swapping a sensor booster from cargo for a web, and you already have a web in your cargo, it'll increment the web rather than add another web)
