### ISSUE TITLE
Add an option that allows to export a minimal HTML version of the Fittings

### ISSUE THREAD

**Issue by Timmeey** [pyfa-org/Pyfa#612]
I ran into the problem, where i could not add the HTML generated by the Export option, to a website, because the Editor is stripping almost all tags (`<style><script>`....) and to get the generated html code to work, was a LOT of effort, because i had to manually remove this/that add this/that.

It would be nice if there was an option, that tells pyfa to export a minimal version, without any styling/lists/javascript etc.

So i went ahead and added this option to pyfa. it works great and produces really simple html output that works in game and oog. #611

**Comment by blitzmann** [comment]
I'll look into this for the next major release, thanks!

**Comment by blitzmann** [comment]
It's been merged, thanks for the contribution!
