### ISSUE TITLE
Incorrect calculation for ancillary remote armor repairer when projecting more than 1

### ISSUE THREAD

**Issue by Will-W** [pyfa-org/Pyfa#618]
The following is in Raw HP, because it's easier to check it against the numbers in 'Attributes':

Get any ship.
Fit a Medium Ancillary Remote Armor Repairer. Load it with Nanite Paste
Drag same fit into 'projected', so that one instance of that fit is projecting on.
Set HP to 'Raw' and observe 72.5 HP/s as expected (145 * 3 / 6 from the attributes).
Do 'change quantity' on the projection and set it to 2. 

Expected:
Repair rate becomes 145 HP/s

Actual:
Repair rate becomes 290 HP/s (i.e. 4x rather than 2x)

Setting it to 3 gets 942.5, to 4 gets 2900.

**Comment by blitzmann** [comment]
Oh, this looks fun.

I'll take a look tonightish. Thanks!

**Comment by blitzmann** [comment]
![capture](https://cloud.githubusercontent.com/assets/3904767/15347231/a54aaa56-1c8d-11e6-951e-da7fc9310c01.PNG)

It's multiplying the amount by three each time. It almost certainly has to do with the fact that the nanite repair paste multiplies the repair amount by three. We are probably not being careful with where / how we apply that. I'll look into it some more tomorrow.
.
