### ISSUE TITLE
EV series drones project incorrect amount

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#619]
To replicate:

Use this fit:

[Taipan, EV Drones]

Acolyte EV-300 x5
Infiltrator EV-600 x5
Praetor EV-900 x5

Project the ship back on itself.

Projected amount (based on maths and drone bay side, which is correct) should be:
5 lights -4.165 GJ/s, 5 mediums -8.35 GJ/s, and 5 heavies -20.8 GJ/s

Actual amounts projected:
5 lights give -20 GJ/s, 5 mediums give -41.7 GJ/s, and 5 heavies gives -104 GJ/s

Example:
http://puu.sh/p0Cq9/de0ef76fc1.png

It's 5 times the amount is should be.  Removing 1 drone (so projecting 4) projects at about 4 times the amount.  So it seems that somewhere the number of drones is getting multiplied twice.

I can't find the EV drones listed in the affected by tab, so not sure where that's happening at....

**Comment by blitzmann** [comment]
I wonder how long this has been broken for... >_>

Commit above fixes it though. =)
