### ISSUE TITLE
Max attribute value

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#620]
Something seems to be wrong with at least the max targeting range. We seem to still be checking on `maxAttributeID`, which for targeting range is set to 300KM. This might not be a thing anymore, and might be due to data that we are pulling from the client but which isn't used any longer. Need to look into this.

https://forums.eveonline.com/default.aspx?g=posts&m=6498948#post6498948

**Comment by blitzmann** [comment]
At this time, I think I am going to hardcode it to simply ignore the max targeting range cap until I can figure out the root of the problem.

**Comment by JoshuaNotowitz** [comment]
I just checked ingame and the max target range for subcaps is 300.

**Comment by MrNukealizer** [comment]
Yes, the targeting range cap is 300km for everything except carriers and super carriers, so that seems accurate.

**Comment by blitzmann** [comment]
I'm going to reopen this until I can figure out how to best deal with this. CCP may have it hardcoded because I don't see an attribute about ignoring certain attributes...

**Comment by blitzmann** [comment]
e70ea67 fixed
