### ISSUE TITLE
Speed Value missing

### ISSUE THREAD

**Issue by Titus142** [pyfa-org/Pyfa#624]
The speed value under Targeting & MIsc is always at 0 now. Seems to be across all fits. 

http://puu.sh/p2Lgh/a720a0ccda.png

Hope this helps. Love the software!

**Comment by blitzmann** [comment]
Please post fit. Also, are you using the latest version, a git commit, etc?

My fits look fine. Double check your projections and skills.

**Comment by Titus142** [comment]
Ugh Im dumb. It was just the Phoenix, and with the siege on the speed is
zero. Pyfa is smarter then me. Thanks! Sorry for the trouble.

**Comment by blitzmann** [comment]
No worries. =)
