### ISSUE TITLE
Fighter DPS: reload time

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#627]
Ignore travel time and simply add in reload time for fighters

**Comment by blitzmann** [comment]
This is going to be put on hold for now because I cannot for the life of me find here the number of charges is defined, which is going to be needed if we want accurate reload times. It shows up in EVE, but not in the data that I can see 

![capture](https://cloud.githubusercontent.com/assets/3904767/15653048/85eb242c-2658-11e6-984a-38229ff1dbde.PNG)

**Comment by blitzmann** [comment]
After discussions on Slack, apparently I have implemented this slightly incorrect. Need to look into it a bit more.

**Comment by blitzmann** [comment]
Thankfully CCP finally added these to the client as FSD data. Phobos was able to dump them:

https://gist.github.com/blitzmann/935c2d5b178d62205ba88a30463e8eda

Not sure how I'm going to proceed with these atm. Usually these would be given their own table in the database, but that seems excessive. I'll take a deeper look into them later.

**Comment by DarkFenX** [comment]
This is in pyfa for quite a few years already.
