### ISSUE TITLE
Cataclysmic Variable has no effect on any Anchillary Armor Repairer

### ISSUE THREAD

**Issue by neutronst4r** [pyfa-org/Pyfa#628]
The title says it all.

**Comment by blitzmann** [comment]
Is it the same in game? I remember checking this in the data files and noticed that ancillary modules were not included with the wormhole effects.

**Comment by neutronst4r** [comment]
I just tested it on Sisi. The Shield Modules are affected, the Armor Modules are not... weird. I guess Pyfa is correct then. Does anyone know if this is a confirmed bug?

**Comment by blitzmann** [comment]
> CCP Larrikin:
> This should be fixed in 118.6

Once the June update deploys, I'll double check these effects and update accordingly.
