### ISSUE TITLE
CPU miscalculation

### ISSUE THREAD

**Issue by rlex** [pyfa-org/Pyfa#632]
Hello. This fit
```
[Drake Navy Issue, Drake N TRB]

Ballistic Control System II
Ballistic Control System II
Shield Power Relay II
Shield Power Relay II

Adaptive Invulnerability Field II
Adaptive Invulnerability Field II
EM Ward Field II
Large Shield Extender II
Large Shield Extender II
10MN Afterburner II

Heavy Missile Launcher II, Scourge Fury Heavy Missile
Heavy Missile Launcher II, Scourge Fury Heavy Missile
Heavy Missile Launcher II, Scourge Fury Heavy Missile
Heavy Missile Launcher II, Scourge Fury Heavy Missile
Heavy Missile Launcher II, Scourge Fury Heavy Missile
Heavy Missile Launcher II, Scourge Fury Heavy Missile
Heavy Missile Launcher II, Scourge Fury Heavy Missile
Heavy Missile Launcher II, Scourge Fury Heavy Missile

Medium Core Defense Field Purger II
Medium Core Defense Field Purger II
Medium Core Defense Field Purger II


Hobgoblin II x5
Hammerhead II x5
```

Shows in pyfa as valid.

However in game and in EFT this will show 2% CPU overusage.

Looks like HML II have wrong CPU usage data.
With all-v as example:
Pyfa: 40 tf
EFT: 41.8 tf 

In-game 41.25 tf (with my skills)

**Comment by blitzmann** [comment]
I am not sure of the problem as you describe it. With an all 5 character, pyfa calculates the HML IIs as having 41.3 (rounded from 41.25) CPU usage.

![capture](https://cloud.githubusercontent.com/assets/3904767/15831112/ea94e124-2be9-11e6-99b5-54dfc5519a01.PNG)

Not only that, but pyfa calculates that fit as over CPU by 1.02%.

Please double check your fit for implants / boosts / other artifacts that may affect fitting calculations. If you are still having issues, please elaborate a little more, and possibly send me you `%userprofile%/.pyfa/saveddata.db` file via email (in README).

**Comment by blitzmann** [comment]
Closing this as invalid due to no response. Feel free to reopen and elaborate on issue if needed

**Comment by rlex** [comment]
missed it in my mail..
Cannot reproduce anymore with latest version, anyway

**Comment by blitzmann** [comment]
k, if you ever stumble upon it again, reopen this thing =)
