### ISSUE TITLE
Feature Request:  Ability to offline active modules

### ISSUE THREAD

**Issue by IslayTzash** [pyfa-org/Pyfa#635]
I'd like to be able to keep modules in a fit, but have them offline.   I know I'm over cpu/powergrid with that module active, but I'd like to see what else I can fit when it's offline -- i.e. an offline cyno in the high slot.

Maybe clicking on modules that can be activated could cycle through three states: online (o), active (check), offline (x).

**Comment by blitzmann** [comment]
You can already offline modules. Ctrl+clicking the state should offline it. If this is not what you are looking for, please elaborate. =)

**Comment by blitzmann** [comment]
Closing this issue as invalid, feel free to reopen if you need to with more details.

**Comment by wffurr** [comment]
This was completely impossible to figure out how to do in the client.  I had to search and the top result was this issue.

I'd prefer if single-clicking cycled through all states: active, overheat, offline, inactive.  Left click cycles forward, right click cycles backwards.

**Comment by blitzmann** [comment]
> I'd prefer if single-clicking cycled through all states: active, overheat, offline, inactive. Left click cycles forward, right click cycles backwards. I would find this much more intuitive.

pyfa has a large user base, changing the mechanisms of how to offline/overheat modules would confuse and aggravate quite a few folks. There's two reasons why it is the way it is currently:

1) Precedent. EFT used to be the only real fitting tool around, and it was that one that came up with the concept of modifiers for offline / overheat. pyfa adopted that convention early in it's development, and it has remained that convention for both programs (and I believe a few other fitting programs do similar shortcuts)
2) Active / Inactive is a much more popular state to toggle between than the other two, hence why it's a simple click toggle, whereas overheat / offline is more for specific use-cases. The way it's set up right now is also more efficient - I can always give the module a certain state without clicking through to try to find the state (recalculating the fit each time, which decreases responsiveness).

There's the possibility of adding this add an option, but that just feels like overdoing it for something like this. Every program has a learning curve as to how to use it, what it's shortcuts are, etc. Once you know them though, it's fairly straightforward. I do heartily agree that the various shortcuts and modifiers should be at least better documented somewhere. :)

For now I'll leave it as-is. If there's more demand for adding an option to support it another way, I'll take another peak. :)

**Comment by Asday** [comment]
For anyone somehow landing here from google, you can middle click to offline nowadays.
