### ISSUE TITLE
Ion Siege Blaster I powergrid usage wrong

### ISSUE THREAD

**Issue by robbiewalker** [pyfa-org/Pyfa#637]
Pyfa 1.21.3 Stable - Citadel 1.11
Ion Siege Blaster I powergrid is listed as 89100 powergrid

in game info lists it as 99000 which is larger than the CONCORD faction guns (98000) which makes sense

**Comment by blitzmann** [comment]
pyfa has the correct value with the latest version

![capture](https://cloud.githubusercontent.com/assets/3904767/15917439/bb864ad4-2dca-11e6-8cd6-89c21f67717a.PNG)

Double check your skills which may be affecting it. Closing as invalid - if you feel this is in error, feel free to reopen or create a new issue with more details. =)

**Comment by robbiewalker** [comment]
That was me just being stupid. Sorry

**Comment by blitzmann** [comment]
No worries, glad it's sorted ;)
