### ISSUE TITLE
Target Resists Profile does not handle values greater than 100

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#638]
Target resists does not seem to do the maths to dynamically calculate the resists.

Steps to reproduce:
1) Enter resist profiles with very large numbers
2) Set the profile

Bonus bug: It's often difficult/impossible to open the menu to set the target resist profile.  Right click doesn't seem to open it.  This is the only right click menu I've seen with this issue.

**Comment by blitzmann** [comment]
Discussed with Ebag on slack, Target Resists are working as intended and it is not feasible to change at this time. =)
