### ISSUE TITLE
Add tabbed views for products in market? (Similar if not identical to EFT)

### ISSUE THREAD

**Issue by vectorman1** [pyfa-org/Pyfa#640]
I would like to see something like it implemented, however I do realize not a whole lot of people would like it as they're used to the current one.

I find the current sorted by (say microwarpdrives) sizes and tiers and whatnot a little bit too .. let's say crowded.

Thoughts?

**Comment by blitzmann** [comment]
I am not sure what you are asking. The market browser is essentially the same between the two programs as is relates to modules. There are some differences (such as the aforementioned MWD sizes), but AFAIK EFT does some custom modifications to the market browser to support those changes, while we use data straight from the client (and doing custom bits of code for the market will become a nightmare to maintain).
