### ISSUE TITLE
Selectable Booster Negatives

### ISSUE THREAD

**Issue by Natheniel** [pyfa-org/Pyfa#642]
So I was thinking that you could have a right click menu on each booster to select what negatives would effect your ship, also with a selectable skill level effect since skills do effect them.

**Comment by blitzmann** [comment]
Yeah, it's something that has been looked at off/on throughout the years. It would be tricky to not only store the information, but also display it on the GUI.

**Comment by Ebag333** [comment]
This isn't a true side effect implementation, but you can take a look at #804

**Comment by blitzmann** [comment]
This feature was added long ago, this issue seemed to miss the memo :D

Closing \o/
