### ISSUE TITLE
Ancillary armor repairer not displaying EHP restored by charges properly

### ISSUE THREAD

**Issue by LeeChurch** [pyfa-org/Pyfa#648]
This is for all 3 sizes. The HP/s when loaded is correct, But it looks like the calculation for the amount of armor repaired with charges isn't applying the loaded bonus, as it is consistently 1/3 of what it should be.

**Comment by blitzmann** [comment]
This should be fixed internally a few weeks ago with #629. We just haven't released it yet. Next version comes out at the end of June, but if you need this functionality now: replace `pyfa\library.zip\gui\builtinViewColumns\misc.py` (in windows you don't need to unzip it, you can just edit the file directly) with the contents found here:

https://raw.githubusercontent.com/wolfwood/Pyfa/1cd7b9a25027a2ae60d1eb267840c51f06d49499/gui/builtinViewColumns/misc.py
