### ISSUE TITLE
Missing Market Prices

### ISSUE THREAD

**Issue by FireCulex** [pyfa-org/Pyfa#652]
After upgrading to the latest 1.21.3 all market pricing has disappeared. All ships/fittings/total now read 0.0 ISK

**Comment by blitzmann** [comment]
This is an EVE Central issue. All market data that I checked seems to be down. https://eve-central.com/home/quicklook.html?typeid=12044

CCP changed CREST endpooints yesterday/today, so EVE Central probably has not been updated to reflect those changes.

Marking as invalid, but leaving issue up in case anyone else comes looking for it.

**Comment by blitzmann** [comment]
Issue has been resolved on eve centrals end, closing.
