### ISSUE TITLE
Rof bonus from siege module and ballistic control system are incorrectly penalized on phoneix

### ISSUE THREAD

**Issue by jyxu2015** [pyfa-org/Pyfa#653]
http://i.imgur.com/egGChR6.jpg

**Comment by blitzmann** [comment]
Are they not supposed to be penalized? The BCS is definitely supposed to be penalized, not sure on triage since it's a special snowflake. If you can provide screenshot comparison to in-game values that would be helpful, as well as the actual fit (post eft here).

**Comment by jyxu2015** [comment]
Hi, Blitzmann

Since my tranquility and SISI accounts could not fly a phoneix now, I will use the screenshots from my serenity account with some brief translation. And I assume that all the mechanism are the same.

The BCS and the Siege module are both T2 version.
Here is the screenshot in game:
[http://i.imgur.com/54NjIDa.jpg](url)
When there is no BCS online and not in siege, the rof is 93.19 seconds/round.
When there is 1 BCS online and not in siege, the rof is 83.41 seconds/round.
93.19*(1-10.5%)=83.405 (T2 BCS reduces 10.5% rof)
When there is 1 BCS and in siege, the rof is 16.68 seconds/round.
93.19*(1-80%)*(1-10.5%)=16.681 

If the BCS and siege are penalized, the rof should be 93.19*(1-80%)*(1-10.5%*0.87)=16.93

So I think there is no penalization between BCS and siege. 

The account i used is all V in ROF related skills with a rapid launcher 1005 implant.
And here is the monitoring from pyfa and eft.
[http://i.imgur.com/fO7hyo9.jpg](url)

Thank you.

**Comment by jyxu2015** [comment]
If there are some confusion cased by the client language, please let me know and i would make some more translations if necessary. 
Sorry for the inconvenience.

**Comment by blitzmann** [comment]
Confirmed with SISI data. The fix will be out with the next release at the end of the month.
