### ISSUE TITLE
Projected effects lost when fit set as booster

### ISSUE THREAD

**Issue by Nahaz** [pyfa-org/Pyfa#654]
I believe there's a bug where projected effects are lost when assigning the same ships as fleet booster. Might be an edge case but this is my setup:

2 Command ships, same fits, different links

When I assign the ship as projected effects I see the effect of the cap chain (cap time doubles) but when I add either of the ships as booster, the projected effects are lost (cap time halved).

Just poke me if you need pictures to understand more, but I think it's fairly clear

**Comment by blitzmann** [comment]
Can you post the fit of these ships, along with their projections,

**Comment by blitzmann** [comment]
@Nahaz still need the fits :)

**Comment by Nahaz** [comment]
Sorry, been away, you will get them when I'm back

**Comment by blitzmann** [comment]
I'll have to double check how the new command boosters work with projected fits. They should be calculated correctly, just need to verify

**Comment by blitzmann** [comment]
Closing this due to new command burst mechanics
