### ISSUE TITLE
Export fit to EVE - Error 415: UNSUPPORTED

### ISSUE THREAD

**Issue by rawrgit** [pyfa-org/Pyfa#655]
Can't Export fit to eve error 415: UNSUPPORTED

This happened to me right after i followed [this](https://github.com/pyfa-org/Pyfa/wiki/CREST#user-defined-mode) wiki for the "User-defined Mode". I can browse my fits and import crest fits to pyfa, but not from pyfa to crest. When i try this i get a 415-error. 
I'm not sure if changing to "User-definded Mode" has anything to do with this, but I'll add it for troubleshooting.

I also tried to go back to "Implicit mode" and i still get the same error.

Adding [image](https://i.imgur.com/tRABj5e.jpg) of the error with description on imgur.

Using version 1.21.3.

**Comment by blitzmann** [comment]
Thanks. CCP changed a few things recently IIRC, I thought it was mostly market stuff, but I'll have to take a look.

**Comment by rawrgit** [comment]
Awesome responsetime!
Appreciate your tool! *thumbs up*

**Comment by Dubbly1** [comment]
Still having this issue

**Comment by blitzmann** [comment]
Because I haven't made a new release yet. The fix will come at the end of the month when the new EVE patch comes out.
