### ISSUE TITLE
June Release Progress and notes

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#657]
- [ ] `ECMResistance` attribute: if item has this set to 0, then they are immune to ECM. This can probably be implemented at the GUI level: if ship has this attribute, show "Immune" or something rather than jam chance.
- [x] Missiles have slight change to calcs.
- [ ] `remoteResistanceID` does not currently work for ECM due to the fact that ECM effects bypass the effect modification stuff and applied directly to a property on the ship object. Need to fix this. With this release, ECM drones now have this property.
- [x] Look into Asklepian implant set and their bonuses.
- [x] New attribute `energyNeutralizerSignatureResolution` seems to replace `signatureRadius` for neuts. I am not sure if we use this an any calculations (probably not), need to check. DONE: Not used anywhere to my knowledge
- [x] Neut drones have had a lot of their standard attirbutes converted to energy attributes. Need to make sure the cap drain code understands this if needed. See:

```
[*] Acolyte EV-300
  [-] duration: 6000.0
  [-] incapacitationRatio: 0.75
  [-] maxRange: 5000.0
  [+] energyNeutralizerDuration: 6000.0
  [+] energyNeutralizerEntityChance: 1.0
  [+] energyNeutralizerRangeOptimal: 5000.0
  [+] fighterAbilityAntiFighterMissileResistance: 1.0
```

**Comment by blitzmann** [comment]
The remaining items on the list aren't important enough to warrant a hold up on release. I will go through and make a new issue for each one and assign it as a todo to keep track.

**Comment by Ebag333** [comment]
> Missiles have slight change to calcs.

What were the changes?

>New attribute energyNeutralizerSignatureResolution seems to replace signatureRadius for neuts

This is probably for the new cap sized neuts.  A carrier running neuts basically has zero affect (effect?) on a frigate. Minimal on a cruiser.  Fairly decent on a BS (but heavy neut is better). Full effect on another cap.

**Comment by blitzmann** [comment]
Can you look into figuring out the neut calculations? Its probably the same calc used to determine the percentage of dps applied vs sig rdius

 Also the missile change was that they simply precaluclate something and store it in an attribute  that was originally calculated by pyfa. On mobile right now, cant get specifics

**Comment by Ebag333** [comment]
#684 should cover the neut stuff.

**Comment by DarkFenX** [comment]
Should be not actual anymore.
