### ISSUE TITLE
SAAR has reduced cap usage when loaded with paste

### ISSUE THREAD

**Issue by graywolf** [pyfa-org/Pyfa#658]
No implants, All V skills, the following fit 

    [Astero, Exploration]
    
    Small Ancillary Armor Repairer
    [Empty Low slot]
    [Empty Low slot]
    [Empty Low slot]
    
    [Empty Med slot]
    [Empty Med slot]
    [Empty Med slot]
    [Empty Med slot]
    
    [Empty High slot]
    [Empty High slot]
    
    [Empty Rig slot]
    [Empty Rig slot]
    [Empty Rig slot]
    
    
    Hobgoblin II x5
    Acolyte II x5
    Hornet EC-300 x5

has cap usage -8.89 on the SAAR. When you load paste into it, it goes down to -3.33. I'm pretty sure that should not happen. At least the in-game fitting shows same cap stability with&without paste.

**Comment by blitzmann** [comment]
You are factoring in the reload time. That will affect the cap usage.

You can see [here](https://github.com/pyfa-org/Pyfa/blob/3e1c561752b09a915459778c7fbd4a2aeae97a96/eos/saveddata/module.py#L613) that if there is a charge set on the module in question, it will include the time to reload into the cycle time calculation if factor reload is `True`. And the cap is calculated as activation cost / cycle time.

It doesn't really make sense for this particular module, but it is technically correct - with the 60 second reload introduced, it will take 96 seconds to completely deplete the charges and reload. The average cap use during that time will be -3.33 / sec.

**Comment by graywolf** [comment]
I guess there isn't gui switch to turn this on/off? In frigate fights you don't usually stop it to reload since you will be dead long before the 60 sec passes.

**Comment by blitzmann** [comment]
Right click firepower area -> factor in reload. There may also be a global option enabled in the preferences.
