### ISSUE TITLE
Mac issue

### ISSUE THREAD

**Issue by gscottnelson** [pyfa-org/Pyfa#659]
Good afternoon - Great product - Thanks so much for a wonderful tool and using a Mac - 

One item I am noticing, is that I am also getting the 415 Export Error..see attached screenshot.    However, When I quit the application, it seems to hang and I have to force quit it.   Not sure why.   

![screen shot 35](https://cloud.githubusercontent.com/assets/10010885/16315831/7d9c38fc-3949-11e6-81a5-bc632e07bd3f.png)

**Comment by blitzmann** [comment]
The error should be fixed with #655. It's very possible that the error causes the process to hang, I'd have to test it out.

Why the fuck does it look like that? Did you resize the window?

**Comment by gscottnelson** [comment]
Yes – I did resize the window, because I for me to see the whole message to take the screenshot

**Comment by blitzmann** [comment]
okay, just checking. I might need to tweak the gui to not look so ugly in that case. Actually, the whole things needs a bit of reworking haha.

I've verified that with the current master branch, it works as expected, and doesn't hang. The previously mentioned fix should be available with the new release next week. =)

**Comment by gscottnelson** [comment]
Thanks Ryan,  great!!


On Jun 23, 2016, at 8:19 PM, Ryan Holmes <notifications@github.com<mailto:notifications@github.com>> wrote:


okay, just checking. I might need to tweak the gui to not look so ugly in that case. Actually, the whole things needs a bit of reworking haha.

I've verified that with the current master branch, it works as expected, and doesn't hang. The previously mentioned fix should be available with the new release next week. =)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/pyfa-org/Pyfa/issues/659#issuecomment-228232061>, or mute the thread<https://github.com/notifications/unsubscribe/AJjBBVOcADH_uHdfOkxk-9IuYBjMHqzgks5qOzCZgaJpZM4I9H3x>.

________________________________

This message is intended only for the use of the individual(s) or entity to which it is addressed and may contain information that is privileged, confidential, and/or proprietary to RealPage and its affiliated companies. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, forwarding or copying of this communication is prohibited without the express permission of the sender. If you have received this communication in error, please notify the sender immediately and delete the original message.
