### ISSUE TITLE
Undo & Redo fit/skills changes shortcut

### ISSUE THREAD

**Issue by simonlinj** [pyfa-org/Pyfa#663]
Sometimes I need to compare modes between T2, Factions and Deadspace  and looking for Stats Changes.  

I wish to see a Gree/Red flashing highlight on the specific stat change. Green for positive changes, and Red for negative changes. 

And easily UNDO and REDO shortcut to switch between lastest mod changes..

**Comment by Ebag333** [comment]
While not exactly what you're asking for, this is rather close.

http://puu.sh/q5fB2/de95a8c8e7.png

Kudos to @blitzmann for adding this just recently.

Doing dynamic/color coded stats changes is quite a bit more complex, and you'll start to get into other areas, like user usability.  You mentioned green for positive, red for negative, but what if I'm red/green color blind?

Anyway, this gets you most of the way there.  There may be room to add a custom compare window in the future, but this can probably be closed.

**Comment by blitzmann** [comment]
I'm actually going to leave this open and assign it as an enhancement. An undo/redo feature has been a long requested item (and I don't), but it's one that would take a lot of time and testing, probably a fair bit of refactoring as well. That being said, there is absolutely no ETA on something like this, and color changes as described won't be part of that. We might have a 'flash" that shows which module was changed :)

**Comment by blitzmann** [comment]
closing in favor of #1524
