### ISSUE TITLE
"Resistances" Section Blank

### ISSUE THREAD

**Issue by stevehinesley** [pyfa-org/Pyfa#664]
As you can see in the first image, the resistances shown are correct. In the second image, the resistances are blank. The only difference is the weapons and ammo, everything else is identical.

I can't remember for sure, but I think I remember seeing this with a different ship as well.

Image 1
![1](https://cloud.githubusercontent.com/assets/20214126/16470305/3c1b096a-3e0a-11e6-997d-ee93117502e8.png)

Image 2
![2](https://cloud.githubusercontent.com/assets/20214126/16470262/12ffc322-3e0a-11e6-9e2e-e35105927cdb.png)

Running on Linux Mint 17.3 with Python 2.7.6

**Comment by stevehinesley** [comment]
In case it matters....
EVE Data: 	1042384
Python: 		2.7.6
wxPython: 	2.8.12.1
SQLAlchemy: 	0.8.4

**Comment by OISumeko** [comment]
That is working as intended. Polarized weapons will [zero out your resistances](https://forums.eveonline.com/default.aspx?g=posts&t=380904).

**Comment by blitzmann** [comment]
As stated, this is due to the weapons. Should say so in their descriptions. =)
