### ISSUE TITLE
Asklepian implants having zero effect

### ISSUE THREAD

**Issue by Triksterism** [pyfa-org/Pyfa#670]
The newest implants (Asklepian) do not show any effect on armor repairing ships. I've tried with all three grades (low, mid, high) to no avail. I was really hoping today's hotfix would remedy this.

Hopefully this is fixed soon, I'm itching to see what these implants can do!

**Comment by blitzmann** [comment]
I didn't have time to implement these effect unfortunately. They are next on the agenda though :)

**Comment by blitzmann** [comment]
I don't know when I'll make a new release that includes these implants. Unless there's something critically broken, I usually like to give versions a few days to marinate -- that way other issues that people have can filter in and I can fix them with a larger point release. That being said, you can implement the fix yourself buy adding these two files to `pyfa/library.zip/eos/effects/`:

**armorrepairamountbonussubcap.py**
https://github.com/pyfa-org/Pyfa/blob/2212311a4491e2818c8aa9f7214218262d84bbe7/eos/effects/armorrepairamountbonussubcap.py

**setbonusasklepian.py**
https://github.com/pyfa-org/Pyfa/blob/2212311a4491e2818c8aa9f7214218262d84bbe7/eos/effects/setbonusasklepian.py

Please note that file name is very important, make sure it's correct.

**Comment by Triksterism** [comment]
I copied the files into the zip file under eos/effects, however when I add the implants (or even just one of them) to a ship all the ship's resists get knocked down super low and the CPU/PG gets absolutely wrecked.

Here's an example:

Normal: http://i.imgur.com/hbvg54K.png
Asklepian: http://i.imgur.com/4lrb4bB.png

**Comment by Triksterism** [comment]
One thing is that the omega doesnt seem to have any effect.

**Comment by blitzmann** [comment]
Good catch. 

**setbonusasklepian.py**
https://github.com/pyfa-org/Pyfa/blob/92b2a35888ec4fce3e567ae68f9dc594ac606ebd/eos/effects/setbonusasklepian.py

**Comment by Triksterism** [comment]
Alright, next up it seems the set bonuses arent as strong as they should be.

According to this: https://community.eveonline.com/news/dev-blogs/sarpatis-army-the-new-serpentis-capital-ships/

For instance, on this Kronos, overheated it gets 5663.8 DPS tank. When I add a HG Asklepian set (all 6 implants) it only goes up to 6100.9 which is only about 7.7% increase.

**Comment by blitzmann** [comment]
Mind posting the fit you're referring to?

**Comment by Triksterism** [comment]
[Kronos, Test]

Syndicate Damage Control
Corpum C-Type Energized Adaptive Nano Membrane
Corpum C-Type Energized Adaptive Nano Membrane
Centus X-Type Large Armor Repairer
Federation Navy Magnetic Field Stabilizer
Federation Navy Magnetic Field Stabilizer
Federation Navy Magnetic Field Stabilizer

Domination Warp Scrambler
Gist X-Type 500MN Microwarpdrive
Shadow Serpentis Heavy Stasis Grappler
True Sansha Heavy Capacitor Booster, Navy Cap Booster 800

Bastion Module I
Imperial Navy Large EMP Smartbomb
True Sansha Heavy Energy Neutralizer
Corpum C-Type Medium Energy Neutralizer
Neutron Blaster Cannon II, Federation Navy Antimatter Charge L
Neutron Blaster Cannon II, Federation Navy Antimatter Charge L
Neutron Blaster Cannon II, Federation Navy Antimatter Charge L
Neutron Blaster Cannon II, Federation Navy Antimatter Charge L

Large Auxiliary Nano Pump II
Large Hybrid Metastasis Adjuster II


Acolyte II x5
Hornet EC-300 x5
Hobgoblin II x5
Valkyrie II x5

**Comment by blitzmann** [comment]
Try this:

**armorrepairamountbonussubcap.py**
https://github.com/pyfa-org/Pyfa/blob/f396077cd6ff68d529e546fa0ddf1c042700ead4/eos/effects/armorrepairamountbonussubcap.py

I had the implants stacking penalized with each other. I'm bad at testing shit like this - I basically implement it and see if it changes the value, but rarely do I actually check the value. Unit testing would be nice for these situations. :)

Anyway, I have hand-checked the calculations, which should be correct. For a full set I get a 53.63% increase in repping power.

Also, I have no idea where you got `5663.8 hp/s` armor reps for this fit. I'm getting `2213.5 hp/s` without heat / implants. =/

**Comment by Triksterism** [comment]
Awesome, looks like it's working perfectly. Thanks!
