### ISSUE TITLE
Show market prices on the compare window

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#673]
As an enhancement, would be nice to show the market prices for the items on the item compare tab. (As a new column on far right.)

This would let you quickly see which ones are even worth looking at, instead of having to load each one onto the fit individually.

**Comment by blitzmann** [comment]
![capture](https://cloud.githubusercontent.com/assets/3904767/16640785/04e578d0-43c9-11e6-9039-b6f0973bcd58.PNG)
