### ISSUE TITLE
Ancillary Remote Reps, Range problem.

### ISSUE THREAD

**Issue by AdamGRocco** [pyfa-org/Pyfa#677]
When fitted to a T1 logi, Hull bonuses for range are not being applied.

Osprey - T1 rep, Range 35.5+53km falloff.
               Anc rep, Range 6.7+10km falloff.

This seems to be an issue on all t1 logi hulls (frig and cruiser + Shield and armor)

**Comment by AdamGRocco** [comment]
I just noticed that they do not show a "shield transferred per second" figure either.

**Comment by blitzmann** [comment]
I checked the Osprey, and everything is correct. Confirmed on SISI as well. This is not to say that this should be the case -- when CCP released remote ancillary reppers, they forgot to update many of the effects that delt with remote reps to account for them. I think this may be one of those cases. I did not check the other logis, but I assume it's the same. As such, I'll file a bug report with CCP and block this issue for now until I get more information on it.

Also, I know that the ancil remote shield booster doesn't ahve anything in the misc column. There was a reason for it, but I don't remember why. >_>

**Comment by blitzmann** [comment]
Just pings @ccplarrikin again about this issue. I also got a report that this happens in pyfa for t2 frig logis, Dunno if the client has the same issue or if THAT is pyfa-specific

**Comment by svaraeir** [comment]
As pointed out by @Ebag333 in another medium, T2 logistics cruisers (which apply the remote ancil rep range bonus correctly) use a different Effect property than T1 logistics cruisers, and T1/T2 logistics frigates (which do not correctly apply that bonus for ancils).

The correctly functioning Effects are shipShieldTransferFalloffCC1, shipShieldTransferRangeCC1, shipRemoteArmorFalloffAC2, shipRemoteArmorRangeAC2 (these apply to T2C logi). 

The problematic (and perhaps "unlinked") Effects are armorRepairProjectorFalloffBonus, armorRepairProjectorMaxRangeBonus, shieldTransporterFalloffBonus, and shieldTransporterMaxRangeBonus (these apply to T1C and T1F/T2F logi).

N.B. "Range" and "MaxRange" refer to what is termed in-game as "Optimal Range".

**Comment by ccplarrikin** [comment]
Hey guys,

Known issue. Will be getting fixed soon :)

Cheers mates,
CCP Larrikin

**Comment by blitzmann** [comment]
@ccplarrikin, going through this issue again, it seems that this was not fixed with the release earlier this month (Aug 9th). In game, it still shows as Ancil Remote Reps not being bonused to non-t2 cruiser logi. Can you confirm status of the fix?

**Comment by Ebag333** [comment]
https://community.eveonline.com/news/patch-notes/patch-notes-for-yc118.8-release/

> Ancillary repairers and boosters now received the correct falloff bonuses from appropriate ships.
