### ISSUE TITLE
NAT port forwarding

### ISSUE THREAD

**Issue by StinGer-ShoGuN** [pyfa-org/Pyfa#679]
Hello guys.

It's been a long time since I last used PyFa as my EvE accounts are off for now due to busy real life. 

Lately, I've had some spare time and used it to have a look at the new CREST functionalities (yeah, I've been out for a while...) and I've seen with pleasure that PyFa supports CREST. However, I've found that end users must setup the NAT forwarding rule on their router manually. I've not seen any UPnP or NAT-PMP or PCP support. Would be cool if PyFa could set this up automatically.

I could help in doing so, using [miniupnpc](https://github.com/miniupnp/miniupnp/tree/master/miniupnpc) from [miniupnp](https://github.com/miniupnp/miniupnp).

Let me know.

**Comment by blitzmann** [comment]
Hey, 

This is the first I've heard of this issue. I am able to log in and use the CREST functionality behind my router at home (which does not have any specific port forwarding instructions for pyfa) as well as from my work computer. What specifically is the issue? I assume it's the opening the server's port to listen for the call back, considering that all other CREST functionality runs over HTTPS and thus shouldn't be blocked.

I would like to learn more about the issue. If you can provide detailed reproduction steps as well as error logs (if any), that would be great.

Going forward, however, I would like to set up the call back to a hosted page that will make the call to `localhost:6461`, and if it can't make the connection, to display the information for the user to copy/paste. That would be a solution for all use cases and failures. But literally 0 work has been done towards that at the moment. =/

**Comment by StinGer-ShoGuN** [comment]
There is no bug. It's just what I inferred from reading codes and docs.

But I was completely wrong: I don't know why I misunderstood the SSO server would make the call himself to the callback URL, hence needing NAT traversal techniques when redirecting to localhost...
The callback URL is called by the client with extra arguments added by the SSO server so it just works out of the box !

I still need some sleep...
