### ISSUE TITLE
Fleet Boosts calculation

### ISSUE THREAD

**Issue by FireCulex** [pyfa-org/Pyfa#682]
A large shield booster on a scimitar with claymore as fleet booster s/s, has a cycle time of 5.9s according to the game, not 6.34

**Comment by blitzmann** [comment]
Please post exact fitting(s). Also, is this on the all 5 character, or your character? Double check boosters, system effects, fittings, skills, etc to make sure you're not missing something. Once I get those fittings, I can take a deeper look into this.

**Comment by blitzmann** [comment]
Any progress on getting those fittings to me? :)

**Comment by jasonb4610** [comment]
Just took a look at this to see if its a possible issue. Fits linked below but it sounds like the Claymore fit was missing a Mindlink. Including that drops the Scimi's cycle time down to 5.93 seconds. Excuse the goofy booster fit, it just makes the point =P

[Claymore, Shield Boost]

Co-Processor II
Co-Processor II
[Empty Low slot]
[Empty Low slot]

Command Processor I
Command Processor I
Command Processor I
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Siege Warfare Link - Active Shielding II
Siege Warfare Link - Shield Efficiency II
Siege Warfare Link - Shield Harmonizing II
Skirmish Warfare Link - Rapid Deployment II
Skirmish Warfare Link - Interdiction Maneuvers II
Skirmish Warfare Link - Evasive Maneuvers II
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]


Republic Fleet Warfare Mindlink


[Scimitar, Scimi]

Dark Blood Capacitor Power Relay
Dark Blood Capacitor Power Relay
Dark Blood Capacitor Power Relay
Damage Control II

Shadow Serpentis Remote Tracking Computer
Shadow Serpentis Remote Tracking Computer
Shadow Serpentis Remote Tracking Computer
Shadow Serpentis Remote Tracking Computer
Corelum A-Type 10MN Afterburner

Large Remote Shield Booster II
Large Remote Shield Booster II
Large Remote Shield Booster II
Large Remote Shield Booster II

Medium Capacitor Control Circuit II
Medium Ancillary Current Router II

[Image Capture of Large Remote Shield Booster II on the Scimi](http://imgur.com/a/SZI7M)

**Comment by blitzmann** [comment]
So there doesn't seem to be a problem? In that case I'm going to close the issue - if the OP still has issue, feel free to reopen with additional details. =)
