### ISSUE TITLE
Feature request: create new racial character with pre-populated skill levels

### ISSUE THREAD

**Issue by RealRalph** [pyfa-org/Pyfa#687]
I would like to be able to create a new character in pyfa's Character Editor by clicking "New Amarr/Caldari/Gallente/Minmatar pilot" with the skill levels automatically set to the proper values as currently supplied by CCP. EVEMon has a similar feature (create blank character) which I find quite helpful.

**Comment by blitzmann** [comment]
I am not sure this is something we want in pyfa. I'm not saying no to this feature, as I don't think it would be particularly difficult, but pyfa isn't focused on being a character editor, and this is somewhat infringing on EVEMons specialty. I'll keep this open for now, but it's not something I'm going to commit to atm.

In the meantime, if you want to help, go ahead and post what skills the racial characters start with, or a link to where this is documented. =)

**Comment by RealRalph** [comment]
Unfortunately, CCP Rise presented the new skill sets introduced with Vanguard in form of an Imgur album, which no longer exists (forum thread reference: https://forums.eveonline.com/default.aspx?g=posts&m=6058364#post6058364).

The EVE University Wiki, which is usually pretty spot-on, offers the following: http://wiki.eveuniversity.org/Starting_Skills . Looks reasonable, but I don't have four empty character slots which I could use to create new characters to verify this information.

I've submitted a support request to CCP, asking for an official statement. Let's see how that goes. ;-)

**Comment by Ebag333** [comment]
The primary concern for me is that CCP tweaks these. And may or may not mention anything about it. 

Now if someone wanted to go through the effort to create some base files that someone could import, and we maintained those separately (not part of the database) that might be a different scenario. 

I actually have a Gallente starting char that I could export the skillset for.

Oh, and you don't need slots on your main. Just start a trial account.

**Comment by RealRalph** [comment]
Using a trial account is a good idea, I did not think of that (at least I did not consider the possibility to create more than one character on a trial account).

Regarding base files: I can look into creating one file for each of the four races, but I want to wait for CCP to process my support ticket before I mess with new characters.

Re CCP possibly tweaking skills: that's no different to CCP tweaking everything else, is it? Stats and attributes in EVE are prone to change with every release, or even patch.

**Comment by blitzmann** [comment]
>Re CCP possibly tweaking skills: that's no different to CCP tweaking everything else, is it? Stats and attributes in EVE are prone to change with every release, or even patch.

That's true, but we have ways at automatically getting at that data so that we don't have to go looking for it. With these skills we would have to be aware that they changed, and then manually go about fixing it. Unless this stuff is hidden in he SDE or CREST...

This is one of the reasons why I am reluctant to move forward with this because it's not exposed information AFAIK. How difficult is it to create a character in EVEMon and then import it into pyfa?

**Comment by RealRalph** [comment]
As I work on my Mac right now, I don't currently have access to EVEMon. I'll try to export blank characters when I get the chance. I seem to remember that EVEMon varied a little from the EVE University skill list, so I'd have to compare that as well. Maybe the only way to be sure is to create four new characters and manually make note of the skills.

**Comment by RealRalph** [comment]
> How difficult is it to create a character in EVEMon and then import it into pyfa?

**Comment by RealRalph** [comment]
Clicked the wrong button, did no mean to close this issue.

**Comment by RealRalph** [comment]
I have created blank characters with EVEMon version 3.0.2. I was able to import these files into Pyfa 1.22.2 Stable - YC 118.6 1.0 running on Windows 10.

[EVEMon_blank_characters.zip](https://github.com/pyfa-org/Pyfa/files/405103/EVEMon_blank_characters.zip)

**Comment by RealRalph** [comment]
Turns out that CCP customer support does not have a list of skills that is maintained by CCP. They agree that EVE University probably is the most reliable source of information. :stuck_out_tongue:

**Comment by RealRalph** [comment]
Damn, this "close and comment" button is really annoying...

**Comment by blitzmann** [comment]
I took a look around the SDE and stuff, and unfortunately I'm not seeing a way to fetch and maintain starting skills automatically. In order to do something like this we would be required to follow these things and maintain them ourselves - CCP just doesn't provide that resource for us. Sorry bud L(

I think having a collection of starting skills that you can import into pyfa is a good workaround, and thanks to you folks who google this issue can get those files from here :)
