### ISSUE TITLE
Split Drone Stack UI Glitch

### ISSUE THREAD

**Issue by Robbilie** [pyfa-org/Pyfa#692]
The split drone stack window is not high enough to display all gui elements properly.

Debian Stretch
Gnome 3.20
http://i.imgur.com/SX3w3Ap.png

**Comment by blitzmann** [comment]
@Robbilie I made a change in v1.29.0 that may fix this (i wasn't able to reproduce, but then again I didn't have Gnome 3). Can you test it out and let me know? I'll close this issue in the meantime :)

**Comment by Robbilie** [comment]
nope not fixed

**Comment by blitzmann** [comment]
*le sigh*

**Comment by blitzmann** [comment]
@Robbilie Can you check the amount dialog? add cargo to a fit, right click -> change cargo quantity (or whatever it's called). Does it exhibit the same issue?

**Comment by Robbilie** [comment]
yes

**Comment by blitzmann** [comment]
ಠ_ಠ

Okay, how about the sec status editor for characters (it's new; found on the character editor below the skill tree)? Does that display funky spacing?

**Comment by Robbilie** [comment]
no
looks good

**Comment by blitzmann** [comment]
sweet. I will implement that for the amount changes then. it's a bit more bulky, but at least you'll be able to actually see the text boxes lol. Thanks for checking :)

**Comment by blitzmann** [comment]
I think this was fixed with v1.35.2. please make a new issue if you're still experiencing this issue :)

Thanks!
