### ISSUE TITLE
Burst Jammer range not displayed with Recon Operation infolink bonus in place

### ISSUE THREAD

**Issue by zhabry** [pyfa-org/Pyfa#693]
As shown here
![ss 2016-08-07 at 12 24 27](https://cloud.githubusercontent.com/assets/20880053/17459420/0176e4f0-5c37-11e6-8a25-5fc33f1d5400.png)

This happens if the Burst Jammer-fitted ship is boosting itself, or it's another ship receiving boosts.

In addition, playing with pilot skills presets in case of self-boosting Burst Jamming ship looks funny. Switching between All 0 and All 5 pilots in fitting screen causes range to switch between 12 km (All 0) and 18 km (All 5). However, switching between All 0 and All 5 pilot presets in Fleet effects window makes it either 12 km (All 0) or nothing, as shown in the screenshot.

**Comment by blitzmann** [comment]
Very strange. The value must be getting overridden by null or something... Also of note that it only happens if Recon Operation II is on the fit (T1 doesn't show the symptoms)

I'l definitely take a look into this soon. Thanks!

**Comment by Ebag333** [comment]
@blitzmann this can probably be closed since links are going away: #738

**Comment by blitzmann** [comment]
Closing as this is no longer valid due to restructuring of fleet boosts into command boosts
