### ISSUE TITLE
Overrides window does not work

### ISSUE THREAD

**Issue by lunedis** [pyfa-org/Pyfa#694]
I open the overrides window, type into the search bar, press [Enter], press the search icon, but nothing happens.

I don't have a git version I can start to see the log atm.

**Comment by Ebag333** [comment]
It's happening in Master.

So far I've traced it down to where `scheduleSearch` hands off the search to `sMkt.searchItems`, but it never seems to come back.

The market service has changed quite a bit for fighters and a bunch of other things.

It was working though when I submitted the change to move the override toggle on the menu....

**Comment by Ebag333** [comment]
Okay, it's the filter being off that's the problem. Turn on the filter (default), and it works.

Hmm, wonder if it's something in the database....

**Comment by blitzmann** [comment]
Fixed 5a5ab84
