### ISSUE TITLE
Antipharmakon Toxot booster incorrectly stacking penalized

### ISSUE THREAD

**Issue by Cribbit** [pyfa-org/Pyfa#695]
I did not extensively test the other boosters, only Kosybo (armor rep amt) vs aux nano pump and Thureo (shield rep amt) vs boost amps. Those two are correctly not stacking penalized. 

However, Toxot (missile flight time) appears to be hitting stacking penalties with missile guidance computers, which I believe is incorrect.

**Comment by blitzmann** [comment]
Could you please post fit, and tell me if this is under your character or under all 5? Also, post the expected vs actual values and boosts please. :)

**Comment by Cribbit** [comment]
[Tengu, blood raider]

Ballistic Control System II
Ballistic Control System II
Ballistic Control System II
Ballistic Control System II

10MN Afterburner II
Pithum A-Type Medium Shield Booster
Pithum A-Type EM Ward Amplifier
Pithum A-Type EM Ward Amplifier
Missile Guidance Computer II, Missile Range Script
Missile Guidance Computer II, Missile Range Script

Heavy Assault Missile Launcher II, Mjolnir Rage Heavy Assault Missile
Heavy Assault Missile Launcher II, Mjolnir Rage Heavy Assault Missile
Heavy Assault Missile Launcher II, Mjolnir Rage Heavy Assault Missile
Heavy Assault Missile Launcher II, Mjolnir Rage Heavy Assault Missile
Heavy Assault Missile Launcher II, Mjolnir Rage Heavy Assault Missile
Heavy Assault Missile Launcher II, Mjolnir Rage Heavy Assault Missile

Medium Capacitor Control Circuit II
Medium Capacitor Control Circuit I
Medium Rocket Fuel Cache Partition II

Tengu Defensive - Amplification Node
Tengu Propulsion - Fuel Catalyst
Tengu Offensive - Accelerated Ejection Bay
Tengu Engineering - Augmented Capacitor Reservoir
Tengu Electronics - CPU Efficiency Gate


Zainou 'Deadeye' Missile Bombardment MB-705
Zainou 'Deadeye' Guided Missile Precision GP-803
Zainou 'Deadeye' Target Navigation Prediction TN-903
Zainou 'Deadeye' Rapid Launch RL-1003

Using all V profile for stats below, but the issue is present in all profiles. 

Flight times, 'guidance computer' indicates on range script which is 11% flight time, rig is 20%, booster is 8%:

Without rig, implant, booster or guidance computers: 6s
With rig, gcs: 8.38s (as expected 6 * 1.2 * (1 + .87 * .11) * (1 + .57 * .11) = 8.38)
With rig, gcs, booster: 8.57s (too low - should be 9.05s but is using the 8% at 27% effectiveness, 6 * 1.2 * (1 + .87 * .11) * (1 + .57 * .11) * (1 + .28 * .08) = 8.57
With rig, gcs, booster, implant: 9s (expected given the booster issue - 8.57 * 1.05 = 9s)

And as a side note, when I get time I'll work in a feature to make it clearer how flight time works at the end of missile range (see https://www.reddit.com/r/Eve/comments/4v3l4y/will_missile_range_ever_get_fixed/)

**Comment by blitzmann** [comment]
Excellent bug reporting, thank you! Seems you're right, I've made a quick fix for it. ;)
