### ISSUE TITLE
Activating space superiority fighters into the fighter bay first results in a 0 DPS readout

### ISSUE THREAD

**Issue by MythicalDreams** [pyfa-org/Pyfa#699]
I was crafting a thanatos fit and noticed this, if I activated the ability of the space superiority fighters first (I tested with Gram Is) before standard light fighter abilities the DPS readout remains at 0 until the space superiority fighters ability is deactivated.
It is the same if I activate 1 flight of light fighters and then activate the Gram Is and then activate the other set of light fighters, the DPS registers the first set of fighters, then doesn't register the other set of light fighters until the Gram Is are deactivated.
Unsure if working as intended or if it is a bug.

**Comment by DarkFenX** [comment]
Works for me in all combinations. Might've been fixed. If still an issue - reopen.
