### ISSUE TITLE
newest update from Pyfa disables Features of windows 10 completely

### ISSUE THREAD

**Issue by malleusmintaka** [pyfa-org/Pyfa#708]
O.o
so, I updated pyfa today, after that, I could not use the windows 10 win-s search for programs function, same for start menu-all apps. they just didnt show up. uninstalling pyfa did fix it. 

Could this be on your side?

**Comment by blitzmann** [comment]
Doubtful it's on pyfas side. I can't imagine programs would have the ability to disable features of the operating system. The only thing that I can thing might cause this is if we used Win-S as a shortcut for out own use, but we don't. 

This latest release is actually one of the least-changed releases, so there aren't any major changes from previous releases. It might be an isolated issue with your specific installation for whatever reason, perhaps something in the install went bad? What was your previous version? Try reinstalling the latest, and if it still happens, try installing a previous version to see if it works,

Regardless, I'm going to close this issue as this is almost certainly not a pyfa-related issue.
