### ISSUE TITLE
Citadel fitting view crashes when slot colors are enabled

### ISSUE THREAD

**Issue by gscottnelson** [pyfa-org/Pyfa#711]
Good morning.

When trying to create a citadel fitting, by clicking on any of them.   The app gets extremely slow and seems to hang for several seconds.    Once the fitting screen opens after click on any Citadel, Moving to the market section or anywhere doesn't seem to work and the application seems to hang.    When I resize the window, the window goes black like it can't redraw as if its waiting for some other process to complete.  

This on an iMac 27" with core i7 running @3.50 Ghz -  Mac OS X 10.11.6

**Comment by ppfeufer** [comment]
Similar issue on linux, but it just stops working at all.

> Traceback (most recent call last):
>   File "/home/ppfeufer/applications/pyfa/gui/builtinViews/fittingView.py", line 463, in fitChanged
>     self.refresh(self.mods)
>   File "/home/ppfeufer/applications/pyfa/gui/builtinViews/fittingView.py", line 590, in refresh
>     self.SetItemBackgroundColour(i, self.slotColour(mod.slot))
>   File "/home/ppfeufer/applications/pyfa/gui/builtinViews/fittingView.py", line 560, in slotColour
>     return self.slotColourMap[slot] or self.GetBackgroundColour()
> KeyError: 8

**Comment by blitzmann** [comment]
@gscottnelson I will check, but I don't have easy access to OS X anymore. =/

@ppfeufer I am hoping it is as simple as this, however someone included a fix for exactly this issue: https://github.com/pyfa-org/Pyfa/pull/700 Weird

**Comment by blitzmann** [comment]
Oh motherfucker... that fix went into the citadel branch and was never merged back into master. x_x Will fix and test tonight

**Comment by gscottnelson** [comment]
Thank Ryan –

I appreciate all the work you put in.    When the pre-release gets available, I will download and see how it responds.

Thanks again
Scooter

**Comment by blitzmann** [comment]
The fix has been merged into master, and will be available in the next point release (soonish)
