### ISSUE TITLE
Omnidirectional Tracking Enhancers

### ISSUE THREAD

**Issue by snoesen** [pyfa-org/Pyfa#718]
There seems to be an issue with Omnidirectional Tracking Enhancers in 1.23.1

They can't be right-clicked in the market tab
When added to fits they will only show up after opening character editor and closing again.
Cannot import fits using them

**Comment by amkoc** [comment]
Additionally, any fit that you try to attach a drone tracking computer to will not load properly when you relaunch pyfa - everything goes blank, even slots are missing - and and won't let you remove it from the fitting browser.

**Comment by Bluekind** [comment]
> Additionally, any fit that you try to attach a drone tracking computer to will not load properly when you relaunch pyfa - everything goes blank, even slots are missing - and and won't let you remove it from the fitting browser.

Having the same issue. But when you export the fitting to clip board it still works and import into eve.

**Comment by blitzmann** [comment]
Seems I goofed with the effect. Changed it via github because I didn't have a way to get an IDE setup at the time, and apparently forgot to test it. 

There's a PR already for a fix, so hopefully that fixes that issue

**Comment by blitzmann** [comment]
Sorry it took a lot longer to fix than usual guys. been dealing with a gnarly cold over the weekend, so wasn't up for making a new release. New version should be up that fixes the issue ;)

**Comment by snoesen** [comment]
Sweet, thank you.
