### ISSUE TITLE
Cane DPS vs HFI DPS

### ISSUE THREAD

**Issue by ARobertHarrison** [pyfa-org/Pyfa#722]
Running 1.23.1, using all level 5 skills, no implants, no drones

A Hurricane (5% RoF + 5% DMG per lvl) with 6x 720mm Arty II's (w/ RF EMP) does 306 dps

A Hurricane Fleet Issue (10% RoF + 10% DMG per lvl) with 6x 720 Arty II's (w/ RF EMP) does 279 dps

Looking at the stats on the weapons, the issue seems to be an incorrect ROF bonus for the the normal Cane. The Hurricane's is much lower (by almost 4 seconds) than the HFI.

**Comment by blitzmann** [comment]
I believe your assumption of the bonuses is incorrect, unless I'm not understanding the issue. The HFI does not have a 10% RoF bonus, it has a 10% tracking speed bonus. This is why the Hurricane gets more DPS than the HFI.

Let me know if that solves the issue :)

**Comment by ARobertHarrison** [comment]
*le sigh* No... No... You got it... Apparently my reading comprehension was in the tank the other night. 

I'd been bouncing between them all night and must have started seeing things. I'll have to make sure to read more closely next time.

**Comment by blitzmann** [comment]
No worries, glad it's sorted out. ;)
