### ISSUE TITLE
New Installation, can't create character

### ISSUE THREAD

**Issue by recsa** [pyfa-org/Pyfa#723]
I have just installed Pyfa, was using EFT and wanted to give it a try, so ive never had Pyfa installed, the problem is when i go to Character Editor and Click on "New Character" [http://prntscr.com/cecdwv](http://prntscr.com/cecdwv) a new window to type the char name appears [http://prntscr.com/ceceu6](http://prntscr.com/ceceu6) and no matter what i type there the new character is never created [http://prntscr.com/cecfld](http://prntscr.com/cecfld). After that, if i close the Character Editor window, i cant bring it back again, neither CTRL+E or clicking Window --> Character Editor do nothing at all.

Any hint? might i be missing something?

Thx

**EDIT: PROBLEM SOLVED**, UNINSTALLED, MANUALLY REMOVED users\.Pyfa folder AND REINSTALLED, WORKING FINE NOW. THX

**Comment by blitzmann** [comment]
I am thinking you must have run pyfa a long time ago and had some very old data that it no longer supports. Anyway, glad that it's working for you now :)
