### ISSUE TITLE
Mining barge rework

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#727]
Not an issue, but just a heads up for @blitzmann in case something breaks.

https://community.eveonline.com/news/patch-notes/patch-notes-for-yc118.8-release/

>Mining Barges and Exhumers have received a balance touch-up pass. All the details can be found in this forum thread. https://forums.eveonline.com/default.aspx?g=posts&t=491069
>This set of changes includes:
>All mining barges and exhumers now use two strip miners or ice harvesters
>Adjustments to strip miner and ice harvester base stats, with corresponding changes to ship bonuses to compensate
>ORE Strip Miners and Ice Harvesters have received additional buffs above and beyond their non-faction counterparts

**Comment by amkoc** [comment]
This has dropped, mining barges are inaccurate in pyfa now.

**Comment by Ebag333** [comment]
Give it time for a build to happen. :)

**Comment by blitzmann** [comment]
I'm aware, but don't expect anything before the weekend unfortunately. 😆
