### ISSUE TITLE
Bug: Stacking active drones on inactive results in mixed stack

### ISSUE THREAD

**Issue by BartMassey** [pyfa-org/Pyfa#728]
If you grab a stack of inactive drones (in-bay, red x) and drag them on top of a stack of active drones (in-space, green check) of the same type, the resulting stack is inactive: this is ok, if not what I would have expected. However, if you grab a stack of active drones and drag them on top of a stack of inactive drones, the result is a stack which shows as active, but actually contains (as evidenced by the drone damage display) the mix of active and inactive drones. In this state, clicking to deactivate the stack actually activates the inactive drones and leaves the stack marked active.

Reproduce by:
1. Open a Federation Navy Comet.
2. Put a Hobgoblin I (we'll call it HA) in the drone bay.
3. Mark the drone active. Note the drone DPS.
4. Put another Hobgoblin I (we'll call it HB) in the drone bay, by double-clicking to create a new stack.
5. Drag HA atop HB. Note that the stack is marked active, but drone DPS doesn't change.
6. Click the HA+HB stack. Note that the drone DPS doubles, and the stack remains active.

**Comment by blitzmann** [comment]
Interesting... thanks for the bug report, will look into this. ;)

**Comment by Ebag333** [comment]
>If you grab a stack of inactive drones (in-bay, red x) and drag them on top of a stack of active drones (in-space, green check) of the same type, the resulting stack is inactive: this is ok, if not what I would have expected. However, if you grab a stack of active drones and drag them on top of a stack of inactive drones, the result is a stack which shows as active, but actually contains (as evidenced by the drone damage display) the mix of active and inactive drones. 

Good bug report. :)

We're handling this now (as of #992) by simply making all the drones in the entire stack active if either stack was active.  This means you can easily go over your active drone limit, but we can also remove the hard set to all active if we ever finish implementing allowing partial drone stacks to be active.  (Back end is there, no front end support for it.)

**Comment by BartMassey** [comment]
Sounds great! Thanks much.
