### ISSUE TITLE
Price sometimes doesn't show

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#729]
Noticed this happen from time to time, finally caught an error for what I suspect the issue might be.

```
    def change(self, event):
        sFit = service.Fit.getInstance()
        mainFrame = gui.mainFrame.MainFrame.getInstance()
        fitID = mainFrame.getActiveFit()

        if isinstance(self.thing, eos.types.Cargo):
            sFit.addCargo(fitID, self.thing.item.ID, int(self.input.GetLineText(0)), replace=True)
        elif isinstance(self.thing, eos.types.Fit):
            sFit.changeAmount(fitID, self.thing, int(self.input.GetLineText(0)))
        elif isinstance(self.thing, eos.types.Fighter):
            sFit.changeActiveFighters(fitID, self.thing, int(self.input.GetLineText(0)))

        wx.PostEvent(mainFrame, GE.FitChanged(fitID=fitID))

        event.Skip()
        self.Close()
```

```
Traceback (most recent call last):
  File ".\gui\builtinContextMenus\amount.py", line 54, in change
    sFit.addCargo(fitID, self.thing.item.ID, int(self.input.GetLineText(0)), replace=True)
ValueError: invalid literal for int() with base 10: 
''`
```

**Comment by Ebag333** [comment]
What's weird is that it doesn't always throw the traceback.

Symptom is ship price shows but not whole fit price.

**Comment by blitzmann** [comment]
I've push a fix that should ensure that `ValueError` doesn't happen.

That being said, I have no idea how the error happens, considering we only allow numerical text in the input. I also don't know what that has to do with prices (perhaps it reaches a None amount after failing there and doesn't know what to do). I'm closing this issue for now, if you notice it again reopen or create a new one with more details
