### ISSUE TITLE
Active Prop Mod + Active Cloaking Device behavior

### ISSUE THREAD

**Issue by BartMassey** [pyfa-org/Pyfa#731]
Currently, one can turn on a MWD and a T2 Cloak at the same time in Pyfa, at which point the ship speed shows as the MWD speed modified by the Cloak speed penalty. That speed is probably correct for the one MWD cycle allowed before the Cloak turns it off, so...yay. However, the speed display can be really misleading if you don't notice that both modules are on: either because you wonder how come the ship is so slow (or in the case of a Blops, so _fast_) or because you assume the ship can actually move faster than it can under cloak.

I'm not sure what the right thing is here. Probably highlighting the speed somehow and providing mouseover text when both things are on at once?

Not a big priority, but would have saved me some time tonight.

**Comment by blitzmann** [comment]
I'll have to confirm, but something probably mucked with that specific constraint. Thanks!

**Comment by blitzmann** [comment]
So I misunderstood what the problem was. We've never had this constraint in pyfa. 

A cloak turns off all active modules, correct? There isn't a single module that can be active with a cloak on? I can't recall any. We could loop through all modules and simply turn them off in the effect.

**Comment by BartMassey** [comment]
As far as I'm aware, one cannot have active modules while cloaked. Microwarpdrives can initiate a cycle within five seconds of cloaking for the cloak-MWD trick, and I suspect other modules with cycles have similar behavior. A started cycle will complete while cloaked.

I'm not sure we really want to turn everything else off when the cloak's on. For starters, it would be kind of annoying unless we remembered to turn things back on when cloak was turned off, especially since modules are installed activated by default. It also is actually nice to see how much prop you're gonna get from your prop mod cycle under cloak, if you know that's what you're looking at.

I'm not sure what the right answer is, really. I hadn't thought about anything but prop mods: for these turning the velocity indicator red and altering the tooltip should be sufficient. But thinking about doing this with things like AARs starts to be painful. 

I guess I don't have a good solution. If you think of something, great. Otherwise, it's fine to leave it alone for now. Is there at least an easy way to have cloaks off rather than on at install time?

**Comment by DarkFenX** [comment]
If cloak would instantly disable modules (like scram does for MWD) it would make sense. However, as cloak allows you to use modules for a limited time, i'd prefer to keep current behavior as-is. And if low speed is confusing, just check what affects it by looking at active modules of ship's affected by tab.
