### ISSUE TITLE
Pyfa doesn't seem to open previously loaded fits

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#739]
`self.LoadPreviousOpenFits()` (in `mainFrame.py`) implies that it will try and open previously loaded fits.

This doesn't seem to work, either in the .exe or raw version.

The preference file exists, but doesn't seem to be populated with anything.

**Comment by blitzmann** [comment]
Is this still a thing? Because it works for me.

**Comment by Ebag333** [comment]
Yes

**Comment by Ebag333** [comment]
Closing as I can't get this to replicate.
