### ISSUE TITLE
Exhumer fittings change

### ISSUE THREAD

**Issue by ProVersius** [pyfa-org/Pyfa#741]
Could you please update the fitting screens for the exhumers. I know right off the top of my head, the Skiff got a second high slot and the hulk lost a high but gained a low. Plus they changed the CPU and bonuses around.

**Comment by ChemicalRascal** [comment]
Link to the relevant thread:

https://forums.eveonline.com/default.aspx?g=posts&t=491069

**Comment by Ebag333** [comment]
Also, this one: #727

**Comment by blitzmann** [comment]
Duplicate #727.

I'm dealing with some family issues ATM which of course take priority. I hope to have the point release out sometime this week, but no promises,
