### ISSUE TITLE
Tagging modules

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#750]
Got this message on slack from @alkol.v:

> I just wanted to mention something that I'd love to see on pyfa and wasn't sure where to put it
> it'd be pretty neat if we could tag modules with an acronym
> http://i.imgur.com/6vq7ijs.png (16KB)
> like, i could select all the drone damage amplifiers, right click, and tag them as dda
> and they would then come up when i search dda

This is an interesting idea. 

There's two ways I can see this working: 
- The hard way. Save the "tag" definitions in the user database as a simple association. Two fields, `itemID` and `searchTag` or something. When we schedule a search, query against this table for every seartch token - if the tag is found, load all the itemIDs associated with that tag and use those IDs in the search filter to bring back items that match them. This seems like a lot of extra work for little gain in comparison to the other way described below, however it does allow a fairly seemless integration which I like and could be interesting to see. We would also have to develop a UI as well to show the user which items have which associations.
- The easy way. Allow user to save searches. This should be dead simple - have a table with the search name and the search string. User browses it, clicks it, and is able to run a search right from the browser. This will allow the user to save "Drone Damage Amp" as "DDA" or something. The downside to this is that it's not as seemless - instead of naturally searching for a popular acronym, they will have to remember they have a saved search for it. "Saved searches" also doesn't really make sense for a simple tokenized search (would if we had awesome search capabilities like :hasAttribute and crap like that, but we don't)
- Actually three ways, just thought of this one. Possibly support acronyms out of the box. For each keyword in search (and if number of characters is less than 6 or so), break up the letters and use them in a query like (for DDA): `LIKE D% D% A%`. This might be very possible (would have to look a bit more into sqlalchemy to figure out how to create a `LIKE` statement like this without resorting to direct sql. I  like this idea as it doesn't involve set up on the user's part, and might be fairly simple enough to do, however it will not support things that aren't acronyms such as `"sebo"`, a popular abbreviation for sensor boosters.

I'd like more discussion on this. I really like the idea of #3, even if it's ultimately paired with #1 and #2 - I think acronym searching would be an excellent search feature to include right out of the box.

**Comment by Kyria** [comment]
More than just tags, this could also be some "custom item groups" the user may create and add items in it though the use of pyfa. Then he may only find his groups through the search, or even better by adding the groups at then end in the item tree ? (Just like the quick search in the eve market, where you can have folder)
This way you can manually set what you want when you are looking for any acronym you may have set (or using some "premade" groups with well known tags, such as dda, sebo etc), but you are not limited to "LIKE" search, while you can do some groups of items you commonly use.

_as for the "like" with SqlAlchemy, you just have to ```Item.name.like('searchString')``` (or ilike for case insensitive)_

**Comment by Rylleyryelle** [comment]
i would do market metas, not itemid.. because searching for "dda" for drone amps would only then give you the like.. dda2 or dda1 you set it to, and when i search dda i want the option to fit t2 or faction, etc.

i personally would set up some kind of "common acronyms" table for like.. DCU. DDA, ENAM/EANM, etc..

also i love the idea of custom groups. i could set up like "brawler basics" or "carrier shee".. stuff i need on all ships, then just have to search for the specific weapons.

**Comment by blitzmann** [comment]
#1369 introduced a way to have custom search terms map to specific search terms. Going to close this out as I believe this is the route we will take further development, at least for now. :)
