### ISSUE TITLE
CREST Login to Eve broken

### ISSUE THREAD

**Issue by offtherails2010** [pyfa-org/Pyfa#752]
howdy & thx to all in advance & for PYFA, using it for 1st time for 2 weeks now and its Awesome !

sorry to the issue at hand;

This started about 3-4 days ago, i click Login to Eve in PYFA, it opens up in my google chrome browser and when i hit the authorise button, a window pops open with only this in the address bar:

http://localhost:6461/#access_token=PmMcwk6LYFCZXkw40bqdgI99-_alSieeWEtGX5h5KuolMOljiM8qq5QNtvrZeI-GIWQT8jkEFHzgJVV2tI-SNg2&token_type=Bearer&expires_in=1200&state=488e9293-3c73-43b4-b63b-ae200e50b2cc

and it just stays there, normally that page tells me that PYFA has logged me in successfully and i can close the page down, but im not logged into Eve in PYFA now, where once i was.

i have;
> cleared cache in google chrome
> installed latest PYFA version after uninstalling previous & restarting windows 7 
> verified files in my Eve Launcher & purged extra files (make any difference ?)

The link posted above makes no sense to me as im a humble gamer, not an awesome dev, lol

Apologies if this has been posted before, i did try to look if something similar has for this Link, is anyone able to help ?

thanks loads in advance & fly awesome yall :)

Rails :)

**Comment by blitzmann** [comment]
Hi there,

I cannot seem to reproduce this issue. My character logs in fine. Are you perhaps behind a firewall? You need to ensure that port 6461 is open or otherwise accessible from outside the network.

The pyfa server also does have a timeout. I don't remember what it is by default, but if you sit on the login page too long it will shut the server off, so the `localhost:6461` path won't actually go anywhere.

**Comment by blitzmann** [comment]
Additionally, can you check `%userprofile%\.pyfa\log.txt` and see if there are any messages there?

**Comment by offtherails2010** [comment]
howdy blitzmann & thx ever so much for helping, heres what i found in the txt file you pointed to;

2016-09-20 02:06:09,790 service.crest            WARNING  OAUTH state mismatch
2016-09-23 06:57:08,769 service.market           ERROR    Could not get item: ECM – Spatial Destabilizer II

Um, i havent changed any internet settings of late but where would i input that port number ? sorry im not the brightest knife in the drawer when it comes to networking side of computers lol

once again thx loads for the help, will try to find out how to get the computer to accept port 6461 too at same time

**Comment by blitzmann** [comment]
Well, if you were able to do it before and didn't change any network settings, it's probably not that. (fyi, if your interested in this stuff, portforwarding on your router is usually what you would look for, but I don't think that's the case here).

>service.crest WARNING OAUTH state mismatch

This is concerning. This has to do with securing the CREST login. What happens is that pyfa generates a state (see `state=488e9293-3c73-43b4-b63b-ae200e50b2cc` in your URL) that it sends to EVE. After you login, the EVE website redirects to a server that pyfa is running, and supplies that same state. If it's not the same state, it's assumed that it's another entity trying to access the server, and pyfa simply ignores it.

This could probably happen organically if you try to login twice in quick succession, though that would be fairly rare. That error also happened 7 days ago, so if you're still experiencing the issue, I don't think that has anything to do with it.

Do me a favor. Open up a command prompt (<kbd>Windows</kbd>+ <kbd>R</kbd>, type in `cmd`, hit <kbd>Enter</kbd>), and then run pyfa in debug mode (type in path to pyfa along with `-d`, eg: `C:\Users\Blitzmann\Desktop\pyfa\pyfa.exe -d`)

Then try to log in to CREST. Try a few times. Close pyfa. After that, the log file should show a lot more information. Please email it to me at sable.blitzmann@gmail.com (it may contain sensitive information, so try not to post it here)

**Comment by offtherails2010** [comment]
Good day to you blitzmann !

i found the culprit, there was a malware software that had somehow attatched itself to my browser, social2search, and it even prevented me from logging into my router, so went thru hurdles and hoops finding out now also why i couldnt login to my router !!

- as i had created an exception rule in windows firewall to allow your port number then went to do the same in my router hardware thru the login page on 192.168.0.1

cant believe it was something this stupidly simple all along, i went thru untold complicated stuffs lolz

thank you immensely for your help with this, tbh i dont think i would had gotten even close to finding the source of the problem without your help, i am in your debt, thank you !!!

PYFA IS AWESOME !
~ support is even better, lol :)

Once again, thanks so very much for everything :)

fly awesome :))

**Comment by blitzmann** [comment]
No problem, glad you found the fix. :)
