### ISSUE TITLE
Hard crash on launch - User permission related

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#754]
Windows (and presumably Linux, Mac) can create users with restricted permissions.  This is more commonly seen in a corporate environment, but some home users get setup by their local IT support (AKA brother/sister/dad) and lack things like local administrator rights.

Pyfa does not understand this.

@blitzmann will be annoyed that I'm drudging this back up, but having just walked a user through troubleshooting and solving this, it's a legitimate (and pretty serious) issue.

There's usually no transparency to the end user as to the reason. They see a black box pop up, then go away. No log (no perms to write one), no error message.  On more seriously locked down machines, it can cause Windows to become unresponsive or even crash Explorer as Pyfa tries to do things to files that don't exist (it doesn't understand it doesn't have permission there, so just soldiers on trying to create files).

If the user is very lucky, they'll get a crash popup window with a message about access being denied or the file not existing.  (More likely they'll just get nothing.)

This can be replicated (to a degree) by taking away rights from your user account to the `.pyfa` folder (disinherit permissions, remove rights, propagate to children).  When you launch Pyfa you will likely receive a permissions error.  If your account is part of the Administrators group, you can right click the exe and `Run as administrator`.  Pyfa will launch normally.

However, for some users, getting admin rights may not be a feasible solution (nor should we count on or need admin rights).

Unless a workstation is extremely locked down (in which case, we don't have _any_ good options and need to gracefully exit), the user should have full rights to `c:\Users\%USER%\AppData\Local\`. So move the default Pyfa location there for Windows.  (While we're at it--here's where @blitzmann will get annoyed again--we should rename the directory from `.pyfa` to `pyfa`.  While Linux supports folders that start with `.`, this means something _very special_ in Windows and should _never_ be used by users or applications.)

At a high level, we should do a few things:
1. See if the the command line to specify a directory is used. If they did, skip to 5
2. See if `%USERPROFILE%\AppData\Local\pyfa` exists.  If it does, skip to 5
3. See if `%USERPROFILE%\.pyfa` exists.  If it does, skip to 5
4. Nothing exists, so lets create `%USERPROFILE%\AppData\Local\pyfa` 
5. Check to see if we can access the folder (and have full permissions to it).

If at any point in time we fall through all our potential directories and don't have permissions, or can't create the default for some reason, we need to exit gracefully and notify the user what happened.

I'll be opening a PR soon to tackle this, I don't think it's terribly difficult and if we follow that order of operations above we don't need to touch existing setups at all.

Big thanks to Ry for taking the time to help me troubleshoot this.  (And glad you're finally off EFT. 👍 )

**Comment by OISumeko** [comment]
If storage locations are going to be fiddled with, can we update the linux and mac locations at the same time?

For linux and mac we currently dump everything in the ```~/.pyfa``` directory. More correctly on linux we should be using the [XDG base directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) paths ```$XDG_DATA_HOME/pyfa``` and ```$XDG_CONFIG_HOME/pyfa``` as appropriate (See #237). Mac should probably be in ```~/Library/Preferences``` and ```~/Library/pyfa/```, but someone who actually uses a mac should check those as I'm not 100% there.

If someone is taking the time to write in your suggested checklist, it shouldn't be too painful to add in cases for linux/mac detection also right?

**Comment by Ebag333** [comment]
@OISumeko absolutely.  I don't use Linux or Mac, so I wasn't exactly sure.

I can play around with it, but would need someone to test.  If you have Linux, can you run from source and test?

(I guess I could just install Linux, but....meh.)

**Comment by OISumeko** [comment]
I'm more than happy to run it up on a couple of different linux systems to see how it goes. No problem at all.

**Comment by blitzmann** [comment]
You know, I can get behind this. I did not know there were possible permission issues for `%userprofile%/.pyfa` - I was under the impression that anything under the user profile, the user has access to.

Lets start with just doing the checks and whatnot, but I am not adverse to moving data if necessary. So, the steps would be as follow:

1. See if the the command line to specify a directory is used. If they did, skip to 5
2. See if %USERPROFILE%\AppData\Local\pyfa exists. If it does, skip to 5
3. See if %USERPROFILE%\.pyfa exists. If it does, prompt user to move files. if they confirm, do step 4 and copy files into new directory
4. Nothing exists, so lets create %USERPROFILE%\AppData\Local\pyfa 
5. Check to see if we can access the folder (and have full permissions to it).

**Comment by blitzmann** [comment]
Also, we need to be careful not using additional external packages. Updating the os x build with new libraries is a bitch.

**Comment by minlexx** [comment]
@Ebag333 I have some questions.
:question: 1. Why exactly ```%USERPROFILE%\.pyfa``` is bad? A lot of (cross-platform) apps currently use this scheme *in user profile folder* with no problems - http://puu.sh/rquag/f79ddaee98.png . Among them are Gimp, Android Studio, JetBrains PyCharm, VirtualBox, ... Of course, *in AppData folder* we don't need ```.pyfa```, ```pyfa``` is fine there.
:question: 2. In all places where you use ```%USERPROFILE%\AppData\Local``` should you probably use env var```%LOCALAPPDATA%``` or maybe even ```%APPDATA%``` (the latter points at ```%USERPROFILE%\AppData\Roaming```) ? Which is more appropriate? Windows XP doesn't have AppData folder, it is called ```Application Data``` or ```Local Settings``` there AFAIK. That's why I think that %LOCALAPPDATA%  may be better than hardcoded ```%USERPROFILE%\AppData```. Does Pyfa support Windows XP?

**Comment by blitzmann** [comment]
> Does Pyfa support Windows XP?

Not sure. I'm sure it works, there isn't anything in there that is specific to newer versions of windows. That being said, I honestly don't care about XP. EVE min requirements are 7, so that should be the min req for pyfa as well

> Why exactly %USERPROFILE%\.pyfa is bad? 
I am also wondering about this. As stated before, the user should have nearly full access to their profile directory. I have not tried fiddling with my permissions (ofc, I'm sure if I restrict `.pyfa` explicitly then it's going to have problems). But is there any documentation on this from Microsoft or anything?

IIRC, I even set up a non-admin account on my PC to test pyfa once trying to diagnose an issue, and it worked fine as well. =/

**Comment by Ebag333** [comment]
>Why exactly %USERPROFILE%\.pyfa is bad? A lot of (cross-platform) apps currently use this scheme in user profile folder with no problems - http://puu.sh/rquag/f79ddaee98.png . Among them are Gimp, Android Studio, JetBrains PyCharm, VirtualBox, ... 

A lot of things going on here. 

First, the `.`.

>In Unix-like systems, DOS, and Windows, the filenames "." and ".." have special meanings (current and parent directory respectively). 

Once upon a time in Win7, for a while Windows saw `.name` as `.\name`. That got quickly fixed, but ever since then Microsoft has said not to start folders and files with a period. A _lot_ more apps used to, many have migrated to Windows friendly names. 

Win10 AE is also not allowing you to manually do folders with a period at the start. Before Anniversary Edition I renamed my .pyfa folders all the time (was working on DB changes), now I literally cannot. 

Secondly, why is %USERPROFILE% bad? Normally it's not. In fact, outside of enterprise environments, you can do whatever you want to it, for the most part. The problem is locked down environments. As part of my day to day job, I help companies deploy software to thousands (or tens of thousands) of users. I've packaged thousands of applications. The ones that write to %USERPROFILE% cause problems, because users have special access there, not full administrator access. 

>Among them are Gimp, Android Studio, JetBrains PyCharm, VirtualBox

And look at how many will work easily without Administrator rights. One (gimp). 

I've also packaged gimp. It was a PITA. 



>❓ 2. In all places where you use %USERPROFILE%\AppData\Local should you probably use env var%LOCALAPPDATA% or maybe even %APPDATA% (the latter points at %USERPROFILE%\AppData\Roaming) ? Which is more appropriate? Windows XP doesn't have AppData folder, it is called Application Data or Local Settings there AFAIK. That's why I think that %LOCALAPPDATA% may be better than hardcoded %USERPROFILE%\AppData. 

Local system variables are absolutely the best. I wasn't sure if they got translated properly of hand. If they do, we should absolutely use them.

>Does Pyfa support Windows XP?

_*Microsoft*_ doesn't support XP. Screw XP. 😊

**Comment by blitzmann** [comment]
Closing this in favor of discussion taking place in #237. XDG standards are something I want to look at moving pyfa towards in the coming months, and this issue is basically more information for that. :D
