### ISSUE TITLE
feature request: quicktabs

### ISSUE THREAD

**Issue by Rylleyryelle** [pyfa-org/Pyfa#757]
Pyfa really needs to auto open new tabs when you open fits and not overwrite the current tab.
I spent a good 20 minutes trying g to figure out why I could only have 1 fit open.

Some kind of side by side would be nice too. In eft I can have two fits next to each other and I can drag common modules from one to the other. There's no way to quick fit ships in pyfa like that, so comparing like ships is nearly impossible

**Comment by Ebag333** [comment]
>Pyfa really needs to auto open new tabs when you open fits and not overwrite the current tab.

A work around is to simply click the `+` before opening the next fit/ship.  But that would be a nice preference.

>Some kind of side by side would be nice too. 

Yeah, we have no good way to compare ships currently.

> In eft I can have two fits next to each other and I can drag common modules from one to the other. 

What'd be nice is when you click to duplicate a ship, you get an option to copy the existing fit onto a different hull.  There's lots of times when I want to take 50%+ of a fit and try it on another hull.  You can work around it by exporting the EFT, changing the ship type, and importing, but that's annoying.

**Comment by blitzmann** [comment]
>Pyfa really needs to auto open new tabs when you open fits and not overwrite the current tab.

I'm not sure this is what we want to do by default, although I don't know of a good reason not to atm. For now, <kbd>ctrl</kbd>+click will open them in a new tab (just like any web browser). ;) I'll consider changing the default open though.

> Some kind of side by side would be nice too.

What ebag said. This has been brought up many times before, and it's something we would ofc love to do. It just need to be built out.

**Comment by IndictionEve** [comment]
The tab behavior solved by #791 
There will be a checkbox in the preferences.
