### ISSUE TITLE
Mining Drones

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#762]
Couple issues with Mining drones
1. The mining drone rigs have a stacking penalty. They shouldn't.
2. Drones have an innate bonus on them of 150% (for T2 mining drones). This isn't calculated.

> Neugeniko (Jita Miners Indices)
> I took 1 drone and it mined 90m3 of veldspar in 1 cycle of 60 sec
> 90.0 m3 or 900 units
> Fit is orca with 2x Large Drone Mining Augmentor II, 1x Large Drone Mining Augmentor I
> T2 mining drone

Once the stacking penalty is removed off the rigs, T2 mining drones in Pyfa show as 60 m3 per cycle.  They should be 90, which seems to be where that 150% bonus comes into play.

**Comment by blitzmann** [comment]
Both items should be fixed

**Comment by blitzmann** [comment]
Reopening - I like to close these things once the stable release is out :)
