### ISSUE TITLE
Cannot edit or load damage patterns

### ISSUE THREAD

**Issue by Matrinn** [pyfa-org/Pyfa#766]
Nothing happens at all when clicking window > Damage Pattern Editor. Same with CTRL+D. Also no drop down when right clicking on resistances indicator. (incoming damage patterns)

**Comment by blitzmann** [comment]
It sounds like you have DB corruption and the items can't load. Can you please send me your `%userprofile%\.pyfa\saveddata.db` file to sable.blitzmann@gmail.com, and I can take a look at it. :)

**Comment by Cold-FuzZ** [comment]
Is there a solution for this ?

**Comment by blitzmann** [comment]
Not currently. We do have the ability now to run "cleanup" procedures that are a stop-gap for issues like this - We would have to write one specifically for damage patterns until we can determine what exactly is causing the database corruption. That should hopefully be out by the next stable release.

**Comment by Ebag333** [comment]
>We do have the ability now to run "cleanup" procedures that are a stop-gap for issues like this

This will run every startup, so we just have to have the user restart Pyfa. 

@blitzmann can you send me the DB when you get a chance? I don't think we covered this scenario.

**Comment by blitzmann** [comment]
I will have to check my email - I think I forgot about this issue, and now I have my sable.blitzmann account desynced from my mail due to a password change. I'll try to dig it out tonight and we can look at a decent solution for this.

**Comment by blitzmann** [comment]
@Matrinn @Cold-FuzZ Can you guys test the recent pre-release version and see if this is fixed for you? 

Also, I was not able to find any email with the database file from @Matrinn, so I'm not sure what exactly the problem is. But it's possible we just implemented a fix in the pre-release that might take care of it. :)

**Comment by blitzmann** [comment]
Gonna mark this as fixed as I believe the recent addition of integrity validation at startup will solve these issues
