### ISSUE TITLE
Ability to export attribute stats

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#768]
> CCP Larrikin has a feature request, for current and new version of pyfa if possible, he would like to be able to CTRL+A/CTRL+C or just in general export all the values from the stats screen

https://files.gitter.im/pyfa-org/Pyfa/9UFl/pyfa-1.png

> That stats screen

Easiest way to do this would be to give user an export button.

**Comment by Ebag333** [comment]
Sniped from @blitzmann in #779

**Comment by blitzmann** [comment]
done #779
