### ISSUE TITLE
3 MLU fitted Hulk display incorrect mining yield

### ISSUE THREAD

**Issue by vmech** [pyfa-org/Pyfa#773]
[Hulk, Miner]

Mining Laser Upgrade II
Mining Laser Upgrade II
Mining Laser Upgrade II /OFFLINE

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Modulated Strip Miner II, Omber Mining Crystal II
Modulated Strip Miner II, Omber Mining Crystal II

With 2 MLU onlined:
http://image.prntscr.com/image/bdd662e6573c40d89d0e1b2a1a537267.png

With 3 MLU onlined:
http://image.prntscr.com/image/18b477d7017a4d28abcf1cea687a946e.png

Rightside panel displays incorrect yield too with 3 MLU onlined.

All values calculated under perfect Orca boosting (with Mining Foreman Mindlink)

**Comment by Ebag333** [comment]
Does this happen without the booster?  Can you link the boosting fit as well?

Also, can you confirm the numbers match to what you expect in game?  There's some question as to the actual numbers for mining (I have an open PR on that and am working on it currently, actually).

**Comment by vmech** [comment]
Yes, this happen without booster. 3rd MLU have effect only on Mining amount parameter.
I dont check this in game. Only in PYFA.

Orca fit:
[Orca, Booster]

Damage Control II
Expanded Cargohold II

Adaptive Invulnerability Field II
Thermal Dissipation Amplifier II
EM Ward Field II
Gist B-Type 100MN Afterburner

Small Tractor Beam II
Mining Foreman Link - Laser Optimization II
Mining Foreman Link - Mining Laser Field Enhancement II

Large Ancillary Current Router I
Large Hyperspatial Velocity Optimizer II
Large Transverse Bulkhead II

Mining Foreman Mindlink

**Comment by Ebag333** [comment]
>I dont check this in game. In PYFA only.

The problem here is that we're not sure that the mining amounts given by Pyfa are accurate.  I've been collecting data on it so we can figure it out, but without actual in game numbers I have _no_ idea if the numbers given by Pyfa are correct or not.

You're absolutely right that something is off, but I don't have _any_ mining skills, so I can't go and check myself.  Until someone provides actual numbers, there's not much I can do about this.

**Comment by vmech** [comment]
I found this error in PYFA under All 5 profile.
Theoretically, I can check this in game, but some later :)

**Comment by vmech** [comment]
>

**Comment by vmech** [comment]
Now I check this through creation new blank Hulk fit... All values displays **correctly**.
It's a migration errors... Sorry :)

2 MLU
http://image.prntscr.com/image/aee095bfaa574dd7958a344d9d43449f.png

3 MLU
http://image.prntscr.com/image/9dc6e030de774364b9906cb096a3ea82.png

Well... I need recreate all fits... Again :(

**Comment by blitzmann** [comment]
Can you send me the `%userprofile%\.pyfa\saveddata.db` file at sable.blitzmann@gmail.com and let me know which fit looks "corrupted"? This doesn't look like database corruption to me, as the attributes should be contained in the read-only eve.db, not the user database.

I would like to look into it a bit further if you haven't already deleted the fit

**Comment by vmech** [comment]
Sended. Check your mail.
