### ISSUE TITLE
Database corruption issue

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#777]
As per #773 (and many others), users are getting corrupted databases, where either data is getting out of sync or there's actual corruption (missing/bad data).

Need to do some investigating on this, and see about doing some standard database repairs......

**Comment by Ebag333** [comment]
We started down this road with the implementation of the default profiles.

Can likely extend this methodology easily to other things (chars).

I have personally seen where you can end up with a "missing" damage profile, so you always show HP (even if EHP is toggled) until a new damage profile is selected.

**Comment by blitzmann** [comment]
Agreed, we can do more about database maintenance. At the very least, allow the user to run an integrity check manually.

I think we should look at the current constraints. Things like character skills being orphaned shouldn't happen as we cascade the delete within a transaction. I don't know why some things break like that.

As for #773, I don't think it's database corruption. Symptoms don't make sense to me.

**Comment by Ebag333** [comment]
>I think we should look at the current constraints. Things like character skills being orphaned shouldn't happen as we cascade the delete within a transaction. I don't know why some things break like that.

SQLite doesn't have proper DB constraints like MS SQL or MySQL would, so you are allowed to do things that full blown DBs would prevent you from doing.  (But hey, at least it's not Mongo.)

There _are_ a number of things we don't seem to take advantage of though.  Like flagging a column as being unique, limited amount of foreign keys set, and there _is_ a check constraint...but those can be dangerous.  I also have no idea how SQLAlchemy handles those (though it should handle at least two of those three just fine).

Foreign keys are particularly interesting because they're very hit and miss what's set and what's not.  Those can do a lot to help prevent bad data from sneaking in.

**Comment by Ebag333** [comment]
>I have personally seen where you can end up with a "missing" damage profile, so you always show HP (even if EHP is toggled) until a new damage profile is selected.

Well, figured this out.

We assume that `Uniform` will be damage pattern 1.  But what if it's recreated at some point in time?  (Or, for that matter, any damage pattern.)
https://puu.sh/rP8Fq/6c53fd18e7.png

We should do validation on launch, if the damage pattern ID is set but doesn't exist, we can handle it one of two different ways.

1) Change it to the (new/current) uniform damage pattern ID.
2) Nullify the field.

I vote for option 2, and then change the damage pattern code so that if the damage pattern lookup is null we set it to uniform.

**Comment by blitzmann** [comment]
>But what if it's recreated at some point in time?

Uniform damage pattern should not be able to be deleted / changed by the user, no questions. There is a lot of dependencies and assumptions regarding this. New fits automatically assign DP 1, which is assumed to be Uniform. We have some hardcoded things that use the name "Uniform" and expects it to be as such. It will be a task to change this, and I'd rather not worry about it. Right now, IIRC, the only checks on this is on the GUI, which is bad. If the UI glitches and allows the user to change the uniform damage pattern / delete it / etc, then there could be corruption. We should have some sort of check upon save of this object, and to ignore it if it's `ID == 1`. I believe SQLAlchemy allows for this?

> (Or, for that matter, any damage pattern.)

This is more serious. I thought we had a check in place where if a damage pattern is deleted, it automatically assigns Uniform... This should be fixed low level. When deleting a damage pattern, search for all fits with that and reassign before it's actually deleted. Again, I think SQLALchemy can help with this - we may be able to write a function in the DP class that is run when SQLAlchemy tries to commit the delete.

We should also have a NOT NULL constraint on that column in the fits` table. I don't remember if SQLAlchemy has this or not.

**Comment by Ebag333** [comment]
>Uniform damage pattern should not be able to be deleted / changed by the user, no questions.

`Should not` and `does not` are unfortunately two very different things separated by a moat filled with bugs, assumptions, and developer tears.

>It will be a task to change this, and I'd rather not worry about it. 

Changing it to handle null as Uniform should actually be pretty straight forward.

>We have some hardcoded things that use the name "Uniform" and expects it to be as such.

This is actually less of a problem, most of the code looks for "Uniform" not 1.  I don't like hard coding it, but it's not a problem or factor with this particular issue.

>We should have some sort of check upon save of this object, and to ignore it if it's ID == 1. I believe SQLAlchemy allows for this?

Yeah, my thought is we can handle this on start. I hate to make it take even _longer_ to run, but we can probably actually batch this up and run it as a job in the background.

Simple solution is do a search in the `Fits` table where `DamageProfileID` doesn't exist in the `DamageProfile` table, then get the current ID for `Uniform` and set it to that.  When the fit is loaded, make sure we're checking to apply the `Uniform` damage profile and not simply assuming that `1=Uniform`, then apply the damage profile.

Fixes broken Uniform profiles, as well as broken custom ones.  Should be minimal changes to existing code.

Could still break during use of the app, but at least a relaunch would fix it.

>We should also have a NOT NULL constraint on that column in the fits` table. I don't remember if SQLAlchemy has this or not.

We don't use `NOT NULL` _at all_ which is kinda a problem (not even on our ID columns!).  I'll look into seeing if SQLAlchemy has this or not, I'd be shocked if it didn't.

**Comment by blitzmann** [comment]
> Changing it to handle null as Uniform should actually be pretty straight forward.

I meant changing all the hardcoded assumptions about Uniform = ID 1 = read-only to something that is smarter. I know setting the damage pattern if null to uniform is pretty trivial.

> Yeah, my thought is we can handle this on start.

I don't want to checks like this when we start. it's unnecessary overhead, no matter how simple the query is. It's much better, IMO, to stick this in something that is triggered when the object is deleted from the database.

Now, once we have a fix for it to ensure integrity moving forward, then I'm totally okay with having a migration script that does a one-time fix for current databases. :)

**Comment by Ebag333** [comment]
>I meant changing all the hardcoded assumptions about Uniform = ID 1 = read-only to something that is smarter.

The problem is that some people are already broken. And because the ID column is autoincrement, it's really bad practice to inject the profile back at 1 (if SQLite will even allow you to do it, MS SQL and MySQL won't).

Pyfa for the most part handles `Uniform` being ID `85` just fine.  I don't think there's much that's hard tied to the ID of 1......

I'll poke around and see what there is. It will be easy to modify if there is.

>I don't want to checks like this when we start. 

Not even if it's batched up as a a job that runs in the background so there's no impact to the user? :)

We can tie it to the "Import Database Defaults" under the help menu, it was designed with this sort of thing in mind.  It'll mean that we'll have to tell the user to run it, and most won't even report the issue.  I'd rather handle it quietly and invisibly to the user, just fix the problem rather than making them search out the solution and then manually running it.

**Comment by blitzmann** [comment]
>  (if SQLite will even allow you to do it, MS SQL and MySQL won't)

SQLite actually reuses it's ID's if they are deleted. This is why we have some problems, for example, when a character is deleted but not all the skills are for whatever reason. Character 7 might delete, and character 7 may still have skills in the database, but when a new character is created, it will try to use 7 again, hence the issue (integrity exception when inserting the skills). If this wasn't a thing, a lot of corruption issues would be solved. There may be a SQLite option for this, not sure, but their auto increment fields are simply that. They aren't like an `IDENTITY (1,1)`. =/

>Not even if it's batched up as a a job that runs in the background so there's no impact to the user? :)

Nope. It should be a one-time fix during migration after we fix the core issue. The exception to this would be a triggered "DB Cleanup" which can scour the database and clean up any orphaned records after backing up the DB. But running something the could potentially modify the users DB every time it runs is not something I'm comfortable with, and it just seems like a hack.

**Comment by blitzmann** [comment]
Also, I'd rather have the Uniform ID remain at one as that's how it's always been, but I'm not adverse to making that a strict constraint.

**Comment by Ebag333** [comment]
>SQLite actually reuses it's ID's if they are deleted. 

I don't think SQLite does.....but however SQLAlchemy is doing it it seems to.  Or maybe an older version of SQLite.  Or <something>.  I've messed with damage profiles a lot, but there is still no number 1 (starts at 2).

But yeah. Ugh.

**Comment by blitzmann** [comment]
After this next release, I'll try to focus on way to handle integrity issues better. I'm not so concerned about orphaned records, but rather the reuse of IDs. If we can figure out a way to not reuse IDs, I think that would be a nice, quick solution (of course, we could still include a database clean up function).

**Comment by blitzmann** [comment]
Closing this as #920 was merged and I accidentally opened a new thread about this at #895
