### ISSUE TITLE
Notes on new command module

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#778]
Just leaving this here...

The new command module charges have 6 attributes of interest:

1) `warfareBuff1ID`
2) `warfareBuff1Value`
3) `warfareBuff2ID`
4) `warfareBuff2Value`
5) `warfareBuff3ID`
6) `warfareBuff3Value`
- It seems these are laid out in the same way as required skills, where `requiredSkill1` refers to the typeID of the skill, and `requiredSkill1Level` refers to the required level of the skill. In this situation, ID is the attribute that is modified, and values is by how much.
- These attributes exist for the charge even if there is no value.
- All charges seem to share the same effect: `chargeBonusWarfareCharge`

My first thought would be to just assign these bonuses in that effect and be done with it, however... we won't know where exactly to apply these bonuses. For example, a charge that boosts the resist of the target (`fit.ship`) should be applied differently than a boost that modifies scram range (`fit.modules (filtered)`), and from what I can see there is no way to tell how it works.

Here's the `modifierInfo` from `dgmEffects`. I haven't really looked at it any, so the answer may lie in here```

```
    - domain: otherID
              func: ItemModifier
              modifiedAttributeID: 2468
              modifyingAttributeID: 2468
              operator: 7
    - domain: otherID
          func: ItemModifier
          modifiedAttributeID: 2469
          modifyingAttributeID: 2469
          operator: 7
    - domain: otherID
          func: ItemModifier
          modifiedAttributeID: 2470
          modifyingAttributeID: 2470
          operator: 7
    - domain: otherID
          func: ItemModifier
          modifiedAttributeID: 2471
          modifyingAttributeID: 2471
          operator: 7
    - domain: otherID
          func: ItemModifier
          modifiedAttributeID: 2472
          modifyingAttributeID: 2472
          operator: 7
    - domain: otherID
          func: ItemModifier
          modifiedAttributeID: 2473
          modifyingAttributeID: 2473
          operator: 7
```

the boosting module itself also has a new effect, but no `modifierInfo`, and I haven't drilled down into the expression tree to figure it out. However, there isn't anything special in it's attributes...

**Comment by Ebag333** [comment]
>the boosting module itself also has a new effect, but no modifierInfo

AFAIK the effect is tied to the charge, at _most_ the module would be something like a remote sebo where a script picks one of `#` options.

Sounds like CCP's not going that route though and just has the effect purely on the charge itself.

We may simply have to wait until CCP releases the modules officially.  They may even change the charges between now and release date.  They're playing this one rather close to their chest.

**Comment by blitzmann** [comment]
> In this situation, ID is the attribute that is modified, and values is by how much.

Was totally off here. Seems to be a reference to a new lookup list that we don't currently have... trying to find data in client now...

**Comment by blitzmann** [comment]
New stuff from CCP:
https://gist.github.com/blitzmann/027e50b0356675e0c5db1aece8f0d186#file-dbuffcollections-json-L189

**Comment by ccplarrikin** [comment]
Hey guys,
I'm happy to help out here if you want. But it seams like your pretty much cracked it.

`warfareBuff1ID` refers to the buff ID in the file @blitzmann linked above (`dbuffcollections.jason`)
`warfareBuff1Value` refers to the value of the buff.

i.e.
`warfareBuff1ID` = `21` is `Skirmish Burst: Interdiction Maneuvers: Tackle Range`
`warfareBuff1Value` = `12` is a 12% `PostPercent` modifier, using locationRequiredSkill where the `skillID` is 3435 and the modified `dogmaAttributeID` is 54.

If you need any more details please just ask :)

**Comment by Ebag333** [comment]
Lots of ways to tackle this in Pyfa, but the TL;DR is that we can't do it in the effect itself (because it's a best one wins).

One possible solution, create a dict attached to `fit` and write the boost there (when in the effect), but only if it doesn't exist yet and is better than the current boost listed.

Just would need to store `attribute`, `value`, and `boost type` (filtered item vs hull boost).  Then have some code toward the end of `fit.py` to loop through the dict and apply it (basically same as we do inside an effect).
