### ISSUE TITLE
Conflagration crystals not applying optimal penalty

### ISSUE THREAD

**Issue by Triksterism** [pyfa-org/Pyfa#787]
Title! There is a 50% optimal range penalty that isn't being shown when swapping to Conflagration crystals. I've tested this on multiple ships with different weapon sizes.

**Comment by Ebag333** [comment]
Looks like it's applied to me.

https://puu.sh/rVnle/86721ecdd0.png

You can see that with Conflag the optimal range is 50% that of a laser without a crystal at all.  If you open up that particular laser and drill down, we can see that the optimal range has a 50% penalty being applied from conflag.

Can you provide a fit where this penalty isn't applying?

**Comment by Triksterism** [comment]
Here's a quick screenshot of what I'm seeing. I've tried this on the Revelation with T2 XL guns (anti-capital) and on something like the Harbinger with T2 medium pulses.

https://puu.sh/rVnzH/fbd079fc39.png

**Comment by Ebag333** [comment]
Multifrequency also has a 50% penalty to optimal range, so comparing MF and Conflag the optimal should be the same.

Conflag also has a penalty to tracking speed, which is why faction MF is so popular.

So far, looks right to me. :)

**Comment by Triksterism** [comment]
Here I thought I was crazy. Naturally it was something simple like this. Some guy from my alliance had me second guessing myself I guess. Anyways sorry for the bother.
