### ISSUE TITLE
ECM Burst Jammer on Scorpion hull not receiving strength bonus

### ISSUE THREAD

**Issue by jordillo** [pyfa-org/Pyfa#788]
ship description mentions bonus to ECM Burst Jammer strength and range.

range shows the bonus.

strength does not. 

ECM Burst Jammer module stats in the "Affected" tab under "Caldari Battleship" show range bonus but not the strength bonus.

thanks for fixing!  :-)

**Comment by Ebag333** [comment]
Fix submitted #789 

Poor burst jammers have been neglected.  Shows you how often they're used though, no one's noticed that they were mostly not implemented for a long time now.  (They didn't work at all for projection, I fixed that a while back.)

**Comment by jordillo** [comment]
Wow, that was quick. you rock!
