### ISSUE TITLE
HTML Export searching

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#79]
Improvement to HTML Export searching.

https://forums.eveonline.com/default.aspx?g=posts&m=4493849#post4493849

and 

https://forums.eveonline.com/default.aspx?g=posts&m=4494091#post4494091

**Comment by StinGer-ShoGuN** [comment]
I'm pulling this issue from the ashes but I think it can be closed and marked as deprecated now as there is no more in-game browser and the HTML export thingy served, to my mind, only one purpose: being open in the IG browser.

**Comment by blitzmann** [comment]
Agreed. The html export may still be used by a small amount of people, but let's be honest, I'm not going to put any time into it. If someone else wants to pick this up, that would be cool (hence help wanted label - apparently GitHub suggests these issues to new repo visitors), but I'm going to close it.
