### ISSUE TITLE
Issue with Damage editor / Changing damage types

### ISSUE THREAD

**Issue by ThisIsOneCrazyMOnkey** [pyfa-org/Pyfa#796]
I saw someone else posted about their damage editor playing up too, Mine also is exactly the same.

When I click Damage editor nothing happens. No popup nothing. When I click Char editor I get a pop up. When I try to change the damage type for the defence testing it also doesn't do anything.

**Comment by blitzmann** [comment]
Hi there,

This is usually due to an issue with your database. sometimes the database can get corrupted. Would you mind sending me an email with the database file attached? It can be found here: `%userprofile%\.pyfa\saveddata.db`

**Comment by blitzmann** [comment]
I'm going to close this as it is most likely resolved by recent commits and will be fixed with the next stable release in coming weeks. :)
