### ISSUE TITLE
Patch notes for EVE Online: Ascension

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#808]
Just a quick list of things we should check.

- [x] `Existing mining drones have been rebalanced.` We did something somewhat hacky with the effects to make the numbers work right.  After patch (and after Pyfa is rebuilt) need to validate the numbers in game match with Pyfa numbers.
- [ ] `The old Warfare Link and Foreman Link modules will be converted in to the new Command Burst modules. ` Lots of work to be done here.
- [ ] `Phenomena Generators have been introduced. Titans will be able to fit these new modules (one per race) that apply timed bonuses and penalties to ships over an extremely large area. Unlike Command Bursts, Effect Generators impact ALL ships within their defined area (friend or foe).` More complex command bursts (more like wormhole effects).
- [x] `The Porpoise is a new ship Industrial Command Ship` New ship (possibly in a new line/category).
- [x] `The Orca is receiving a massive overhaul` validate numbers/effects.
- [x] `The Rorqual is getting a revamp from the ground-up` validate numbers/effects.
- [ ] `Rorqual PANIC module` We can't really simulate the invuln, but it has other effects while active that we should simulate (shield regen, etc).
- [x] `Tactical Destroyers have been rebalanced.` Big change here is that the stances/modes changed quite a bit, as well as the base hull bonuses.  Validate those are correct as we handle effects manually.
- [x] `The new Sunesis destroyer has been introduced.` New ship
- [x] `Mining Drone Specialization: 2% bonus to the mining yield and max velocity of drones requiring Mining Drone Specialization per level.`
- [x] `Ice Harvester Drone Operation: 5% reduction in ice harvester drone cycle time per level.`
- [x] `Ice Harvester Drone Specialization: 2% reduction in cycle time and bonus to max velocity of drones requiring Ice Harvester Drone Specialization per level.`
- [x] `Added new skill Invulnerability Core Operation - requirement for Rorqual's new PANIC module.`
- [ ] `Added new skill Spatial Phenomena Generation - requirement for Titan's new Phenomena Generator modules.`
- [ ] `Engineering Complexes, Engineering Service modules, and Engineering rigs (for all structures) are now available.` Slew of new structures, service modules (which we still don't support) and rigs.
- [x] `small artillery PG dropped by 2` confirm that correct stats are shown.
- [ ] https://github.com/pyfa-org/Pyfa/issues/808#issuecomment-261761678
- [x] DEVELOP MIGRATIONS for new boost stuff. 

Nice short easy patch here. :D

**Comment by blitzmann** [comment]
When is this patch coming out?

**Comment by Ebag333** [comment]
Tuesday.

I'm simply preempting the "Ebag tell me what I need to care about in this patch notes" that happens every cycle.

**Comment by blitzmann** [comment]
Oh hey, so the patch released on the 8th wasn't this large command ship patch? :D

**Comment by Ebag333** [comment]
>The old Warfare Link and Foreman Link modules will be converted in to the new Command Burst modules

I still think that we should just handle this through projection.

CCP is adding new projected stuff fast and furious, and if we start adding things via another tab, we're going to end up with 30 of them.  To wit, this patch alone CCP added:

1) Command burst
2) Titan effects (very wspace like)
3) Rorq PANIC (yes this projects)

All these are very different from each other gameplay mechanic wise.  Do we add three new tabs for them?

We also have effects that are very burst like but implemented under the old system (lockbreaker and void bombs).

Plus, once we start implementing the actual "fight simulation" that I'm planning (and yes, this is a thing), scraping this information off multiple tabs will be _vastly_ more difficult than using a single tab/location.

**Comment by Ebag333** [comment]
>Oh hey, so the patch released on the 8th wasn't this large command ship patch? :D

I did mean to write up an issue regarding that.  That oversight has been corrected.

**Comment by MechaLynx** [comment]
For what little it's worth, the Porpoise is under the same line/category as the Orca (and in fact has the exact same requirements as the Orca), both according to sisi and the relevant [dev blog](https://community.eveonline.com/news/dev-blogs/mining-foreman-revolution/#PORP): "[...]it shares a group with the larger and more expensive Orca[...]".

**Comment by Ebag333** [comment]
Assuming that applies to the market group, and they don't go and create a new one, that means that we should pick it up no problem.

**Comment by blitzmann** [comment]
> I still think that we should just handle this through projection.

>CCP is adding new projected stuff fast and furious, and if we start adding things via another tab, we're going to end up with 30 of them.

Hyperbole much? They will continue to be separated into their own gang tab. They are fairly different from projections, using a warfareBuffID instead of simply running an effect that affects a remote fit rather than the local fit (which is a simple concept). This is how it will be done for now at least; I'm not going to try to devise a way to make projected and command stuff play well with one another before I even get the command effect working again.

**Comment by Ebag333** [comment]
'''
Orca
Industrial Command Ships IV
Mining Drone I

5145 units of Concentrated Veldspar
'''

Need to validate these numbers.

**Comment by Ebag333** [comment]
With the new database, Pyfa says the following for the Orca. (V skills)

5x T1 mining drones will give you 3.91 m3/s, which would be 234.6 m3/s for one cycle (60 seconds).  For concentrated Veld, which is .1 m3 per unit, that would give you 2346 units.

Since we haven't done the effects yet, the 100% hull bonus would put that into just about the right numbers as above.

**Comment by Ebag333** [comment]
New database has a bug where ABs and MWDs won't activate (can online/offline).  Need to figure out why.

**Comment by blitzmann** [comment]
Thanks for getting this list together and commenting on what you find. I'm hoping to have some time this week to really sit down and go over everything. Still need to get command bursts actually functional x_x

**Comment by resinneublem** [comment]
Here are the notes: https://community.eveonline.com/news/patch-notes/patch-notes-for-eve-online-ascension

Another fitting change is the small artillery PG dropped by 2:

> All small artillery weapons have had their powergrid requirements reduced by 2.

**Comment by Ebag333** [comment]
>Another fitting change is the small artillery PG dropped by 2:

That should be covered by the DB being updated, but I'll add it to the list.  Thanks for pointing that out.

**Comment by goney3** [comment]
Thank you guys for working on Pyfa, we're really excited to see your Ascension Pyfa release. :+1:

**Comment by Ebag333** [comment]
>New database has a bug where ABs and MWDs won't activate (can online/offline). Need to figure out why.

Can't replicate.  Filing this under `legacy code`.

**Comment by blitzmann** [comment]
Need to test these:

"maxGroupActive"
"maxGroupOnline"

In relation to the new command burst modules. maxGroupActive is already a thing, just need to test it's correct. maxGroupOnline is a new one that is not implemented. Should be the same thing, just checking for a different state.

**Comment by Ebag333** [comment]
Yup.  The rorq and orca (and probably other command ships) have this set so that you can fit 3 without having to do any rigs.  You just can't _activate_ them without the command processing rigs.

**Comment by blitzmann** [comment]
gonna close this as most on that list has been completed. I'm not going to worry about citadels at the moment, nor PANIC module
