### ISSUE TITLE
Remote impedance not implemented

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#809]
>`Ancillary Remote Repairers/Boosters can no longer be used on Heavy Interdictors with an active Warp Disruption Field Generator.`

We need to check to see if this is true in Pyfa.

Crap, do we allow projected stuff for WDFG HICs, bastioned Marauders, sieged dreads, core Rorqs, etc?

Also, I saw a reference to a FAUX fit with multiple ancil shield boosters on it.  Need to  double check if game play actualy allows it or not.

**Comment by Ebag333** [comment]
>We need to check to see if this is true in Pyfa.
>Crap, do we allow projected stuff for WDFG HICs, bastioned Marauders, sieged dreads, core Rorqs, etc?

Answer is: 
HICs: yes
Dreads: yes

I'm guessing the other two will be yes as well.

Okay, so now we need to figure out how CCP flags stuff for being blocked.

Dread siege module has various remote impedance "bonus".  Seems these are not implemented.

HICs WDFG module have a `Disallow Assistance`.

Marauders bastion module are similar to Dreads.

**Comment by Ebag333** [comment]
Rorq also has remote impedance while the industrial core is running.

**Comment by blitzmann** [comment]
When ewar resists came out, I started down that path here:
https://github.com/blitzmann/Pyfa/tree/ewar-resists (specifically this commit https://github.com/blitzmann/Pyfa/commit/6e90d29bd7811161b3fb77494501f718d5987bbf)

And then life happened. I'm not sure if this is the route to take, but I'm putting it here at least for documentation / idea gathering

**Comment by Ebag333** [comment]
yeah, I'm not quite sure how to go on this.

I tend to lean toward doing what we did for `addDrain` and when the effects are processed, look for any resists/reductions/immunity and apply those.

**Comment by blitzmann** [comment]
Done with v1.29.0
