### ISSUE TITLE
Can't launch: "cx_Freeze: Python error in main script"

### ISSUE THREAD

**Issue by Barrogh** [pyfa-org/Pyfa#814]
![pyfa](https://cloud.githubusercontent.com/assets/23470210/20295018/7229cbb0-ab13-11e6-9039-23b3a8fbf42c.jpg)

The program cannot work with non-English characters in directory path. Here's the example of what happens. Installing into a folder that doesn't contain non-English symbols solves the issue.

Not sure if it really counts as issue since the program doesn't need to install anything into system user folders (sidestepping the issue could be way harder otherwise), but there's that.

**Comment by minlexx** [comment]
Python 2 is bad at Unicode, russian letters in path ("Прочее") and all fails.
Try ot put Pyfa in directory, containing only English letters...

**Comment by Ebag333** [comment]
>Try ot put Pyfa in directory, containing only English letters...

Essentially this is the work around.

It's been reported multiple times in the past.  Now that we have more users moving over from EFT to Pyfa, it's probably something we should look into....

**Comment by blitzmann** [comment]
Duplicate #548
