### ISSUE TITLE
Add note pane

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#815]
Simple enhancement, tab to write notes on.  Maybe it's a recipe. Maybe it's your plan for world domination. Maybe it's where you left your car keys.

(Now what fit did I leave that note on....)

**Comment by blitzmann** [comment]
this is a duplicate another issue. Its been brought it before and I agree we should definitely do it and it's simple enough, just never have gotten around to it.

I can't easily find the duplicate right now due to being on mobile

**Comment by mkemnetz** [comment]
looks like a duplicate of #364

**Comment by resinneublem** [comment]
I'm working on a PR for #364. Though not sure when it'll be ready.

This is probably closable.

**Comment by Ebag333** [comment]
Closing as it's well covered. :)
