### ISSUE TITLE
Remembering filter choices

### ISSUE THREAD

**Issue by resinneublem** [pyfa-org/Pyfa#818]
I heard from a corpmate last night that one bummer about the search is:

* You search for a specific module
* You don't want officer modules so you deselect the filter at the bottom
* You find you item and then do another search
* The filters are reset

Keeping the filter choice at least for the duration of the app being open makes sense. (For example, if it was reset every time the app opened, but not every time a search occurred)

**Comment by Ebag333** [comment]
The other annoying thing to me is that the behavior for searching changes the default behavior.  That changed behavior then sticks when you go back to browsing.

**Comment by resinneublem** [comment]
> The other annoying thing to me is that the behavior for searching changes the default behavior.

Sorry, I'm not following. Do you have an example?

**Comment by Ebag333** [comment]
>Sorry, I'm not following. Do you have an example?

Search for an item.  It turns on all categories.
Click on a market group.  All categories will be turned on (default when clicking on groups is only `Normal`).
"Closing" the search reverts to the default behavior.

**Comment by resinneublem** [comment]
Ohh. I think I did run into that while testing. Pretty sure #829 fixes that too. But you might want to checkout the branch and verify.

It mainly retains the pushed state across searches. And continues to have all meta buttons pushed on startup.

**Comment by blitzmann** [comment]
Eh, this closed by mistake. Keeping it open until release
