### ISSUE TITLE
Should HTML export continue to be supported?

### ISSUE THREAD

**Issue by resinneublem** [pyfa-org/Pyfa#825]
Thinking out loud here. Is there a reason to continue supporting the HTML export now that the IGB is gone?

https://community.eveonline.com/news/patch-notes/patch-notes-for-yc118.9-release

> The in-game browser (IGB) has been removed. Please check the blog Bidding Farewell to the in-game brower for more info.

**Comment by blitzmann** [comment]
It still offers a way to browse fits outside of pyfa, however it uses nullsec as it's fitting website and that no longer exists.

**Comment by blitzmann** [comment]
#826 I think we should switch to Osmium for now. I don't know if it's worth keeping HTML export around though. I don't have usage metrics of it or anything.

**Comment by resinneublem** [comment]
I can put together a PR dropping null-sec.com and defaulting to osmium.

I could see certain alliances or groups like Warp to Me finding it useful for sharing sets of fits outside of the game. But I don't know if they're actively using it.

https://wl.warptome.net/fits/ is an example, but even that looks customized.

**Comment by blitzmann** [comment]
I'm going to say that, for now, we will continue supporting the html export. There's no reason at the moment to get rid of it, and it might prove useful for some folks. Gonna close this issue for now.
