### ISSUE TITLE
Command Burst Issue List

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#833]
Steps to reproduce:

Use this fit
```
[Rorqual, BattleRorq]

Damage Control II
Drone Damage Amplifier II
Drone Damage Amplifier II
Drone Damage Amplifier II

Adaptive Invulnerability Field II
Adaptive Invulnerability Field II
EM Ward Field II
Capital Shield Booster II
Capital Shield Extender II
Capital Shield Extender II
Heavy Electrochemical Capacitor Booster I, Navy Cap Booster 3200

Mining Foreman Burst II
Shield Command Burst II, Shield Harmonizing Charge
Large Remote Shield Booster II
Large Remote Shield Booster II
Capital Remote Shield Booster II
Capital Remote Shield Booster II
Pulse Activated Nexus Invulnerability Core
Industrial Core II

Capital Ancillary Current Router II
Capital Core Defense Field Extender II
Capital Core Defense Field Extender II

Gecko x2
'Augmented' Vespa x2
'Augmented' Hornet x1
```

Turn on shield burst. HP/s reps goes up.
Turn off shield burst.

Drag that fit to command burst.
Turn on command burst.

HP/s reps do not change.

https://puu.sh/sr3fg/f11805b156.gif

**Comment by blitzmann** [comment]
Yeah, I didn't get around to testing recursive stuff... Since the command effects are applied to the local fit anyway, I think it would be safe to check if `fit == targetFit` and not do the command bonuses if so

**Comment by Ebag333** [comment]
Problem is, somehow neither of them apply?

**Comment by blitzmann** [comment]
It's weird, but it's probably some sort of edge case condition. Don't have time to step through the code and figure out exactly why, but I've added a commit that does not run through the command bonuses if it's the same fit. Closing this, please open another issue if you find more bugs :D
