### ISSUE TITLE
Orca won't activate multiple Mining Foreman links at once

### ISSUE THREAD

**Issue by Kirby207** [pyfa-org/Pyfa#834]
But it really can.

With 3 fitted and a different script loaded in each one, Pyfa only allows one to be activated at a time, it'll turn the currently active one off when you try to activate another.

In game, Orca can run all 3 because of a role bonus.

**Comment by blitzmann** [comment]
Should be fixed. To apply to your local copy, open `pyfa/library.zip/eos/effects/commandshipmultirelayeffect.py` and replace with this file https://raw.githubusercontent.com/pyfa-org/Pyfa/abcce8879fe357cbda2ad0f21b49ee54d8ea1151/eos/effects/commandshipmultirelayeffect.py

**Comment by blitzmann** [comment]
Actually gonna keep this open so it's visible

**Comment by TAPEJIKO** [comment]
Mackinaw Mining drone II me ~80m3 x5drones, pufa ~30m3 x5drones. 
Orca Mining drone II me =252m3 x5drones, pufa ~83m3 x5drones.
