### ISSUE TITLE
T3D missing bonuses

### ISSUE THREAD

**Issue by Tyrowski** [pyfa-org/Pyfa#835]
The new bonuses for T3 Destroyers are not applying when you change modes. No change in DPS on the right hand panel. 

Tried changing ammo type to force recalc, no dice

**Comment by Phrynohyas** [comment]
Scan resolution and speed bonuses aren't applied as well

**Comment by Tyrowski** [comment]
@Phrynohyas There is no scan resolution bonus anymore. See patchnotes

**Comment by blitzmann** [comment]
Can you please provide a fit and explain what you expect it to show vs what it's actually showing? Thanks

**Comment by blitzmann** [comment]
Ah, nvm. Found the problem:

![image](https://cloud.githubusercontent.com/assets/3904767/20565879/2f932cfc-b161-11e6-8cad-02f149482fc5.png)


Looks like I forgot to add the new effects to these guys. how did I miss this?

**Comment by blitzmann** [comment]
Fixed. There's a few Fixed. There's a few files that were missing. If you want to test it, please add the files that were created in 7e98d29 to `pyfa/library.zip/eos/effects/`
