### ISSUE TITLE
Armor Burst > Rapid Repair Charge not improving hp/s rep

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#839]
from https://forums.eveonline.com/default.aspx?g=posts&m=6723229#post6723229

I have confirmed, although I'm not sure why this is. I have only tested with local Armor Repairers. They are getting the bonus, but the rep amount doesn't seem to change?

![image](https://cloud.githubusercontent.com/assets/3904767/20565582/1966cf66-b160-11e6-9f88-25066c211ca8.png)

**Comment by blitzmann** [comment]
Activation cost shouldn't come into effect here, the the duration should change the hp/s rep (unless I'm completely failing at basic logic)

**Comment by SeijiOeda** [comment]
Skirmish Burst > Rapid Deployment Charge is not also improving speed.
Is this from the same problem?

**Comment by Ebag333** [comment]
So testing an Eos projecting on a Vengeance....

Without Burst:
```
73,duration,Activation time / duration,3824.9999999999995,6000.0
6,capacitorNeed,Activation Cost,40.0,40.0
```

With burst
```
73,duration,Activation time / duration,3365.9999999999995,6000.0
6,capacitorNeed,Activation Cost,35.2,40.0
```

So the activation time and cap usage both drops 12%.  So the effective rep amount _should_ go up as well.

Could this be when these are executed?  We have various effects that modify the command bursts themselves (hull, skill, etc), then we have the command burst modifying the modules.

What's _really_ weird is that while the HP/s reps don't change, the _sustained_ HP/s reps do....they go _down_.  Which if you are using less cap, shouldn't happen.  But I don't really trust those calc numbers after poking around with them.

`RUN EFFECT:  Heavy Tackle (Vengeance)`

This comes very late in the whole process.  It wouldn't surprise me if the way that calcs are done if it's completing after the GUI is refreshed.

**Comment by Ebag333** [comment]
Okay, how's this for weird.

I get zero command effects when using the branch that moves the recalc to a threaded job.

```
Command: 
{}
```

The only thing that's different is `service.fit`.

**Comment by blitzmann** [comment]
So... there's a problem here. Command bursts are applied at the very end of a fit calculation. So what happens is that the fit goes through it's calculations (the afterburner has it's modification in place, and finally modifies the ship max velocity), but then the command burst modifies the afterburners `speedFactor` attribute after the afterburner has already modified the fit. Same goes for the reppers.

This might take some time to get right - we now have to possibly consider command burst effect runtimes into the equation (short-term we may be able to just run them before the fit starts on it's own local modules...)

I'll try to get something working in the next couple days. once this is fixed though, I believe we are ready for a stable release :D

**Comment by blitzmann** [comment]
So, a quick rundown and background: pyfa has this concept of run-times. There are certain effects that must be run before other effects in order to correctly apply. Afterburners come to mind: if the afterburner applies it's speed boost to the ship before the speed boost is increased via another effects, the max velocity won't show that boosted increase. So we have the afterburners affect to the ship run in the `late` runtime. 

This is what is happening with these command bursts. Command bursts are, by default, set in the `normal` runtime. When the fit reaches that runtime level, the boosts are set on the fit, however they aren't run yet (because we need to ensure we only apply 1 `warfareBuffID` per fit). The problem here stemmed from the fact that although the modifiers were set inside the runtime, they were applied outside the runtime loops and at the end of the fit, so they were not constrained by the runtimes.

As a fix, I've simply moved running the command bursts at the end of each runtime loop, and run those "effects" that need to be run at that runtime. They still all default to `normal`, but we have the ability to fiddle with it later if needed.

So I'm going to mark this as fixed. :)
