### ISSUE TITLE
'Excavator' Mining Drone missed bonus from Mining Drone Specialization 

### ISSUE THREAD

**Issue by Shegox** [pyfa-org/Pyfa#840]
The Excavator drones are affected by the new skill Mining Drone Specialization (2% to yield and max velocity), in pyfa the skill is not in the affected by category and is not calculated into the result.

With the Ice Excavator drones there are also some missmatches, but I don't have enogh knowledge for that.

**Comment by blitzmann** [comment]
Thanks! I've fixed some effects related to mining drones, should be good now. Take a look at 6500e6d4670053d9a97704e640d1bff8431dee3a
