### ISSUE TITLE
Pulse Activated Nexus Invulnerability Core does not exist

### ISSUE THREAD

**Issue by Helothane** [pyfa-org/Pyfa#842]
This is module for the Rorqual that gives it and the industrials within 200km of it in its fleet 100% resists on the shields for a period of time (5m + 30s/level of the skill Invulnerability Core Operation) .  It is technically categorized as a Superweapon.

**Comment by Ebag333** [comment]
Hmm.  You can search for it, but indeed it doesn't show up.

@blitzmann It should be under `Superweapons` -> `ORE`
