### ISSUE TITLE
Alpha Clones

### ISSUE THREAD

**Issue by 0Pinger** [pyfa-org/Pyfa#846]
Return player with a lot of skills above the alpha caps, I imported a fresh api for my main account and see that when making ship builds pyfa is not seeing it as an alpha but an omega, so its giving higher stats than it should be

e.g. cap amount and stable
in game 1.74k @ 37%
in pyfa 1.81k @ 57.2%

drone damage
ingame 223dps
pyfa 280dps

short term I can edit my char stats and remove those above the cap, but it needs a way to see its an alpha and not an omega account/character

**Comment by blitzmann** [comment]
Pyfa doesn't support alpha clones yet. It's planned, but its probably not going to be done before stable release for ascension.

**Comment by blitzmann** [comment]
I've created a separate issue here to track this feature progress: #863
