### ISSUE TITLE
[Suggestion] Command burst interface

### ISSUE THREAD

**Issue by Orlha** [pyfa-org/Pyfa#851]
Hello.
Command bursts are pretty standartized by themselves and by the hull they are fitted to. You can have them unbonused or 1%/2%/3% depending on the hull.

I suggest an ability to check ship stats with bursts without fitting them on some Command ship.
Like, you right click on "Projected" tab where you can add system effects, then you select something like this:
Add command burst > Skirmish > Rapid Deployment > Unbonused (0) / 1 / 2 / 3 (%) > Character name (for skills) or "All 5"

Would be much easier to use than the current system. Imagine if I have a Thorax and Boosting Magus.
I need to find a Thorax fit, open it, then I need to type "Magus" everytime when I want to check i with different ships and drag it onto "Projected" tab. Even I my Command Ship (Magus in this case) already opened in one of the tabs, I still need to use "Search Fitting" everytime. We could mark fitting as "Fleet Boosters" before Ascension update, but I think my idea is even better and easier to use - just have presets and use it.

**Comment by blitzmann** [comment]
It's an interesting idea, however this would require a hefty reworking of how pyfa does things. For one thing, we can't currently assign a character to just a module. We could probably run command stuff from the projected tab, where you simply project a command burst, but it won't have a character associated and, again, to support that would require a large change in how projected stuff works with command stuff (they are two separate things in the back end). Not only that, but it would require us keeping track of the different bonuses in the game to create that custom menu, which are subject to change.

> We could mark fitting as "Fleet Boosters" before Ascension update

This is still a thing in the backend, and will be coming back once we get all the command kinks worked out.

Thanks for the suggestion. Unfortunately, it's not something that is currently in scope and it would require a large effort for what i believe to be little gain, especially once the booster fit flagging is back. :)
