### ISSUE TITLE
Ice harvesting drones not reflecting bonuses from Porpoise/Orca

### ISSUE THREAD

**Issue by Helothane** [pyfa-org/Pyfa#852]
Ice harvesting drones (both t1 and t2) show an unmodified duration when put in the drone bay of either the Porpoise or the Orca.  Both hulls give a reduced duration bonus for ice harvesting drones.  In addition, the ice harvesting drones are not showing the reduction in duration due to the ice harvesting drone skill (5%/level) and the ice harvesting drone specialization skill (2%/level).

The bonus may be being applied as an increase in the yield, but that is not correct.

**Comment by blitzmann** [comment]
Duplicate #840. Thanks!

**Comment by Helothane** [comment]
That fixes the issue of the skills, but it doesn't appear to address the hull bonus from the Orca/Porpoise
