### ISSUE TITLE
Drone Mining Augmentor rigs impacting yield of Ice Harvesting Drones

### ISSUE THREAD

**Issue by Helothane** [pyfa-org/Pyfa#853]
The bonus from Drone Mining Augmentor rigs appears to be impacting the yield displayed from Ice Harvesting Drones.  These rigs only impact duration of the ice harvesting drones, not the yield.

**Comment by Ebag333** [comment]
Fixed #855

**Comment by blitzmann** [comment]
Thanks guys, fix for this has been merged to master. This is an example of new items using old effects which we're properly constructed in the first place. >.<
