### ISSUE TITLE
Structure Modifications Tree doesn't work

### ISSUE THREAD

**Issue by SacredPowers** [pyfa-org/Pyfa#862]
I don't know if you are aware of this issue yet or not but clicking the + button next to the structure modifications group in the market tab doesn't open up anything. The + button simply disappears and the tree is empty.

**Comment by blitzmann** [comment]
I believe this has been fixed with a recent commit that fixed other market groups. Can't test right now, but I'll check later

**Comment by blitzmann** [comment]
Confirmed this was fixed with a previous commit.
