### ISSUE TITLE
Porpoise can only activate one Mining Foreman Burst module at a time

### ISSUE THREAD

**Issue by MajkStone** [pyfa-org/Pyfa#870]
The Porpoise can use two Command Burst Modules at the same time.  In pyfa, when you enable one (green check mark), the other one is reverted to online.
![porpoise2](https://cloud.githubusercontent.com/assets/14260487/20845055/195144e2-b891-11e6-8690-2b1cde5e5db8.png)
![porpoise1](https://cloud.githubusercontent.com/assets/14260487/20845056/1953bc86-b891-11e6-8c0f-e2ba47a6435c.png)

**Comment by Ebag333** [comment]
This is fixed in code already, and there should be a release coming out shortly.

You can either wait for the release, or run from code yourself. :)

**Comment by MajkStone** [comment]
Thank you sir!
