### ISSUE TITLE
T3D damage still wrong

### ISSUE THREAD

**Issue by Orlha** [pyfa-org/Pyfa#871]
226 dps with this fit and defense mode.
229 in sharpshooter. I think there should be more than only 3 dps difference.
Defense: http://puu.sh/sCjvU/639a87e77d.png
Sharp: http://puu.sh/sCkmn/af51dd3a8a.png

**Comment by Ebag333** [comment]
you are probably right. CCP changed the effects, I had a line item for it but it got overlooked I think.

**Comment by blitzmann** [comment]
Fun fact, this has apparently been a bug for months (since the t3ds were release as far as I can tell). Nice catch!
