### ISSUE TITLE
Fighters added with no active abilities and user cannot manually add abilities

### ISSUE THREAD

**Issue by sophos9** [pyfa-org/Pyfa#872]
From 1.25.0, newly added fighters cannot have abilities activated manually and exisiting fighters with active abilities show no DPS

**Comment by IndictionEve** [comment]
do you have a example fit for me? unable to reproduce this issue.
adding fighter abilities can be added manually and dps are updated, too

**Comment by sophos9** [comment]
This is not fit specific. New Thanatos added in Pyfa with fighters loads in the fighters tab with 'None' under active abilities. Right click to the submenu 'Abilities' results in the 'Abilities' submenu not showing at all so no abilities can be selected

**Comment by blitzmann** [comment]
> This is not fit specific. New Thanatos added in Pyfa with fighters loads in the fighters tab with 'None' under active abilities. Right click to the submenu 'Abilities' results in the 'Abilities' submenu not showing at all so no abilities can be selected

I just created a new Thanatos and added an Einherji from the market, the default Turret Attack ability was activated and I'm able to activate more using the right click menu.

I'm also not able to reproduce. Please be as detailed as possible, lay out step-by-step to reproduce. Also, I am assuming this is on Windows?

**Comment by sophos9** [comment]
- Add new Thanatos
- Add fighters (any)
- In the fighter tab, I can see fighters. Added with default of 'None' for active abilities
- Right click on fighters, I can see 'Abilities' sub menu
- Click on 'Abilities', no submenu appears (I used to be able to select MWD etc)

This is on Windows. There really is not more detail I can add. Not had any problem until 1.25.0

**Comment by sophos9** [comment]
Just tested on an Astrahaus fit, same error condition

**Comment by IndictionEve** [comment]
ok, this is really strange. 
using the source-version i'm unable to produce the issue.
![IDEworks](http://i.imgur.com/wGowbQL.png)


using the release files without IDE, the bug is there.
![ReleaseFail](http://i.imgur.com/2ciG7RU.png)


looks like something is wrong with the ability listing.

**Comment by sophos9** [comment]
Thanks for confirmation but also thanks for such an amazing tool, really appreciate the effort!

**Comment by Ebag333** [comment]
Might be time to rebuild the skeleton....

**Comment by blitzmann** [comment]
Can confirm, release exes are bugged for some reason.

> Might be time to rebuild the skeleton....

Possibly. What concerns me is that nothing has significantly changed that I'm aware of. =/

**Comment by Ebag333** [comment]
We refactored pretty much all of Eos.  I didn't touch pyfa.py, but that doesn't mean something else didn't break due to the whole import mess.

There's 2-3 TODOs to move stuff there, so it's probably about time.  I know you hate it, and I actually have some thoughts on ways that we might be able to make it easier (at least for Windows, Mac/Linux I'm not as sure about).

**Comment by blitzmann** [comment]
> didn't touch pyfa.py, but that doesn't mean something else didn't break due to the whole import mess.

Dunno why you're concered about pyfa.py specifically.

I'll make a few personal builds to try to narrow it down to a commit. Also, just tried to re-generate the windows build, came back with an error. Can't be fucked to deal with it right now.

**Comment by blitzmann** [comment]
Bad commit  `b29fa2467a4ac0079`. Oops, seems I accidentally deleted the effects associated with the fighter abilities.

The reason i wasn't seeing this when running via source was because I had the `.pyc` files  assciated with those effect files (for some reason... I usually run python with `-B` so I shouldn't generate these, but whatever).

I'll be making a new release soon which fixes this. Sorry about that! :)

**Comment by Triksterism** [comment]
Would it be possible to make it so you can select multiple fighters and choose their weapons? What I mean by this is currently we have to do them one group at a time which is kind of a pain.

**Comment by blitzmann** [comment]
> Would it be possible to make it so you can select multiple fighters and choose their weapons? What I mean by this is currently we have to do them one group at a time which is kind of a pain.

It's certainly possible... how difficult it would be is a different question (probably not difficult though). Please open up a new ticket with this feature request. :)

**Comment by Eylandt** [comment]
I can confirm same issue here on MacOS. Added fighters and they show "None" under "Active abilities" by default. Right clicking on fighters and moving cursor onto "Abilities" doesn't open any submenu with fighters' abilities.
Firepower -> Drones show 0.0 DPS:
