### ISSUE TITLE
Boosting ship fitted and dragged into Command tab does not apply boosts

### ISSUE THREAD

**Issue by sophos9** [pyfa-org/Pyfa#873]
From 1.25.0 when dragging a command boosting ship into Command tab to show applied boosts on the current selected ship, no boosts are applied

**Comment by Orlha** [comment]
Can confirm, tried to apply bonuses from Magus with 2 armor links and 1 skirmish link. No bonuses are applied.

**Comment by blitzmann** [comment]
Need more information guys. Please post fits for both the boosting fit and the boosted fit. Tell me which bonuses are not being applied, or if they are just incorrect, how they are incorrect.

Also make sure there is a charge loaded in the command modules of the boosting ship and make sure the module is turned on and active.

**Comment by sophos9** [comment]
[Orca, Overwatch]

Reinforced Bulkheads II
Damage Control II

Adaptive Invulnerability Field II
Adaptive Invulnerability Field II
Large Shield Extender II
Large Shield Extender II
[Empty Med slot]

Mining Foreman Burst II, Mining Laser Field Enhancement Charge
Shield Command Burst I, Shield Harmonizing Charge
Mining Foreman Burst II, Mining Laser Optimization Charge
[Empty High slot]
[Empty High slot]
[Empty High slot]

Large Drone Mining Augmentor II
Large Drone Mining Augmentor II
Large Drone Mining Augmentor I


'Augmented' Mining Drone x5
Mining Drone II x5

That fit does not apply any boosts with burst modules fitted with charges and active.  Same can be replicated for other ships with burst modules with charges

**Comment by blitzmann** [comment]
Thanks, I will check this probably tomorrow. I did a somewhat last minute change to how command bursts worked to fix another bug noted in pre-release, this might be due to that...
