### ISSUE TITLE
Strength of command bursts wrong.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#876]
The burst shield hp bonus from for the following fit is 15% in pyfa, not 19.7% like in client.

[Orca, Caca - Solo - Neug]

Damage Control II
Reinforced Bulkheads II

Adaptive Invulnerability Field II
Adaptive Invulnerability Field II
Thermal Dissipation Field II
Kinetic Deflection Field II
500MN Y-T8 Compact Microwarpdrive

Auto Targeting System II
Small Tractor Beam II
Armor Command Burst I, Armor Energizing Charge
Shield Command Burst II, Shield Harmonizing Charge
Salvager II
Shield Command Burst II, Shield Extension Charge

Large Drone Mining Augmentor II
Large Drone Mining Augmentor II
Large Drone Mining Augmentor I

Hammerhead II x5
Hobgoblin II x5
Mining Drone II x5
Ice Harvesting Drone II x1

ORE Mining Director Mindlink

Shield Harmonizing Charge x300
Shield Extension Charge x300
Armor Energizing Charge x300

**Comment by Neugeniko** [comment]
The raw shield hp is 37500 hp before, 43125 after in pyfa. Shield resists are 54.7/80.7/85.5/77.4 before 58.6/81.5/86.1/79.3 after in pyfa.

**Comment by blitzmann** [comment]
I think this might be fixed, but I'll be double checking in game. :)
