### ISSUE TITLE
Magnetometric and Radar ECM modules have 'switched' shown effects

### ISSUE THREAD

**Issue by Cosmitz** [pyfa-org/Pyfa#879]
In the hover-over text.

**Comment by blitzmann** [comment]
Can you be a little more descriptive? I have no idea what this means ;)

**Comment by Cosmitz** [comment]
This should explain it. Check the tooltips for the effects. http://imgur.com/a/yg5Kr

**Comment by Ebag333** [comment]
Good catch. It is indeed swapped in the tool tip.

Submitted a fix.

**Comment by blitzmann** [comment]
Thanks to both of you. :)
