### ISSUE TITLE
Missing Fighter Abilities

### ISSUE THREAD

**Issue by IndictionEve** [pyfa-org/Pyfa#881]
Specific support fighter abilities (web, neut, etc) are missing, because their effect flagged  `isImplemented=false`

Example: `Dromi I`
> effect = {Effect} <eos.gamedata.Effect object at 0x0E670E50>
 ID = {int} 6435
 _Effect__activeByDefault = {bool} True
 _Effect__effectModule = {NoneType} None
 _Effect__generated = {bool} True
 _Effect__runTime = {str} 'normal'
 _Effect__type = {NoneType} None
 _sa_class_manager = {ClassManager} <ClassManager of <class 'eos.gamedata.Effect'> at 51ca918>
 _sa_instance_state = {InstanceState} <sqlalchemy.orm.state.InstanceState object at 0x0E670F70>
 activeByDefault = {bool} True
 description = {NoneType} None
 effectID = {int} 6435
 handlerName = {unicode} u'fighterabilitystasiswebifier'
 info = {EffectInfo} <eos.gamedata.EffectInfo object at 0x0E670ED0>
 isImplemented = {bool} False
 name = {unicode} u'fighterAbilityStasisWebifier'
 nameFilter = {SRE_Pattern} <_sre.SRE_Pattern object at 0x05045BF0>
 published = {bool} False
 runTime = {str} 'normal'
 type = {NoneType} None
 typeID = {int} 40347

may you have a look into eos? still look like voodoo to me

**Comment by Ebag333** [comment]
I believe @blitzmann fixed this already.

https://github.com/pyfa-org/Pyfa/commit/4a95156e353d5983d1f49bc55b3dedae7dfe550a

Can you make sure you have latest files, and try again?

**Comment by Ebag333** [comment]
Also, make sure you're running in debug mode.  `pyfa.py -debug`

Inside Pyfa, if you look at the item window, effects tab has some new features.

Active: Yes if online, no if offline (double click to toggle), blank if not implemented
Type; active, passive, projected, etc
Run time: What point in the engine it runs in
ID: internal ID of the effect

**Comment by IndictionEve** [comment]
you are right.
fix confirmed, sry :)
