### ISSUE TITLE
Porpoise is listed under Gallente instead of ORE

### ISSUE THREAD

**Issue by Pick107** [pyfa-org/Pyfa#882]
Not a huge thing, still a bug I think.

**Comment by blitzmann** [comment]
While it is supposed to be an ORE ship, technically CCP has it listed in their database as a Gallente race. pyfa uses this data directly from CCP sources, so we go with what the data says. Adding in custom conditionals for a small issue like this isn't something I'd want to do, but I'll definitley let some CCP folks know the race is not assigned correctly :)
