### ISSUE TITLE
Porpoise ice harvester drone duration still not quite right

### ISSUE THREAD

**Issue by Helothane** [pyfa-org/Pyfa#883]
Better than it used to be though :)

This might be an impact of #866, if that is still a live issue and if that impacts the Porpoise as well as the Orca.

On TQ my Porpoise pilot (Industrial Command Ship 5, Ice Harvester Drone 5, Ice Harvester Drone Specialization 4) with a Ice Harvester Drone II and in a Porpoise with a single Medium Drone Mining Augmentor II has a duration of 87.97s.  In Pyfa it is reported to be 111.435s.

**Comment by blitzmann** [comment]
Thanks for the bug report. it has been fixed and will be released tomorrow :)
