### ISSUE TITLE
Feature Request: Light fighter damage

### ISSUE THREAD

**Issue by Triksterism** [pyfa-org/Pyfa#885]
Would it be possible to enable light fighter damage abilities to check dps please?

I'm speaking of the anti-frigate/anti-drone fighters (Equite, Gram, etc...)

**Comment by Ebag333** [comment]
Works for me.  Have you tried right clicking and enabling abilities?

**Comment by Triksterism** [comment]
Regular and heavy fighters have always worked for me (barring the recent bug) but the anti-fighter fighters (Gram, Equite, etc...) do not. 

This is what I see: https://puu.sh/sHKA3/57765b8616.png

**Comment by Ebag333** [comment]
Probably fixed by https://github.com/pyfa-org/Pyfa/commit/4a95156e353d5983d1f49bc55b3dedae7dfe550a

Not sure when Blitzmann is going to do a new build.  You can run from source if you need it before then.

**Comment by blitzmann** [comment]
correct, this has already been fixed

**Comment by malleusmintaka** [comment]
it is fixed? not for the .exe file though, right? At least there the issue still exists

**Comment by Ebag333** [comment]
It's fixed in the source. No, a new build has not been released yet.  Soon `(tm)`
