### ISSUE TITLE
Paste from clipboard doesn't work when entering API for new character (OSX)

### ISSUE THREAD

**Issue by matthewpennell** [pyfa-org/Pyfa#887]
In the current OSX build, on adding a new character, paste (Cmd+V or Edit->Paste) does not work in the API key and verification code fields. This means that you cannot import a character's skills without retyping both strings manually.

**Comment by blitzmann** [comment]
Duplicate #490

Unfortunately it's difficult for me at this point to do anything or develop on OSX. I will try to make this a priority for the next big release though.
