### ISSUE TITLE
Citadel fittings broken still

### ISSUE THREAD

**Issue by tstivers1990** [pyfa-org/Pyfa#891]
Attempt to modify a citadel fitting and at some point the fitting window locks up, refusing to allow you to add/remove modules. I also ran into an issue where my old citadel fittings weren't able to load in 1.25.1. I've noticed this seems to be triggered by citadel energy neutralizers. As soon as I attempt to add one of them, I get the described results. Afterwards, if I close the fitting and try to re-open it, I'm presented with a blank fitting, the same as what happened when I tried to open my old fittings.

**Comment by blitzmann** [comment]
Fixed with #890
