### ISSUE TITLE
The Titan phenomenon generator not working?

### ISSUE THREAD

**Issue by jyxu2015** [pyfa-org/Pyfa#893]
http://i.imgur.com/YNmafS5.jpg
Erebus`s phenomenon generator should give a 30% armor hitpoint bonus..

Thank you

**Comment by Ebag333** [comment]
these haven't been implemented as far as I know. it's a little complicated because they're more like wormhole effects than proper bursts. 

It's probably something that will be looked at sooner rather than later, but we need to decide how and where we want to handle these.

**Comment by blitzmann** [comment]
> these haven't been implemented as far as I know. it's a little complicated because they're more like wormhole effects than proper bursts.

They shouldn't be any more complicated than the other bursts, as they are quite literally the same thing. The only difference is they affect everyone in their AoE rather than only fleet mates, but since we don't have that particular constraint in pyfa, they should act similar.

Could be completely wrong, who knows. Will have a peak :)

**Comment by Ebag333** [comment]
>The only difference is they affect everyone in their AoE rather than only fleet mates

Yeah, that's the complicated part, potentially. :)

**Comment by blitzmann** [comment]
> Yeah, that's the complicated part, potentially. :)

I don't see how that affects pyfa though

@jyxu2015 I've found the issue - it was a simple copy and paste error on my part, along with some incorrect effects. I will be dropping this into out into master shortly, and it'll be available with the next point release :)

**Comment by blitzmann** [comment]
Fixed with 7875c2aca

I will warn, however, that I'm not sure about the stacking penalties on these. If you ever notice values are off, let me know. :)

**Comment by Ebag333** [comment]
should not have stacking penalties. (99.99999999% sure)

**Comment by blitzmann** [comment]
@ebag Which effects?

**Comment by Ebag333** [comment]
All of them for the Titan effects. This is why wspace effects can literally break the game, because of lack of stacking penalties. We can double check with someone who knows, maybe. 

I hate stacking penalties. They are such a PITA.

**Comment by blitzmann** [comment]
I'll leave it as is for now. People will report it if there's a problem. You might be able to contact larrikin and determine which command effects are SP'd.
