### ISSUE TITLE
Ship skill bonuses on command burst strength do not work

### ISSUE THREAD

**Issue by jyxu2015** [pyfa-org/Pyfa#896]
http://i.imgur.com/Pa2wUHt.png

A damnation has 3% bonus on armored command burst strength and duration per command ship skill level
A drake has no bonus on that.

The modifier durations in the Module State windows are different. **←the duration bonus works**
The warfarebuff1values in the Module State windows are different (1.44 on Damnation vs 1.25 on Drake)
The warfarebuff1multipliers in the Charge State windows are the same (-18.8 on Damnation vs -18.8 on Drake)
According to the Devblog, on damnation warfarebuff1multipliers should be -21.56. (18.8*1.15=21.62)

==========================
http://i.imgur.com/kYDF69y.png

When applying them on a Erebus fit.

Erebus with no bonus: 50% EM resistance

Erebus with Drake  bonus: 59.4% EM resistance
(1-59.4%)/(1-50%)=81.2%
18.8% resistance bonus from Drake<-Correct.

Erebus with damnation bonus: 59.4% EM resistance
(1-59.4%)/(1-50%)=81.2%
18.8% resistance bonus from damnation <-**InCorrect, the commandship bonus on strength does not work**

Find the the same problem with command destroyers, carriers, supercarriers, T3s

**Comment by blitzmann** [comment]
Please post all relevant fittings in EFT format, makes it much easier to test out

**Comment by blitzmann** [comment]
nvm, noticed they were reeeealy simple fittings

**Comment by blitzmann** [comment]
This probably has to do with the timings of the effects. Still looking into it

**Comment by blitzmann** [comment]
The problem does indeed lie withing the effect runtimes. The ship hull modifier was applying after the command module did it's thing. This is going to require a bit of refactoring. Right now, the module modifies the charge, and the charge applies the effect. It really should be the other way around (charge modified module, which does effect).

I've got a rough draft of the refactor working. Gonna need to refine and test it.
