### ISSUE TITLE
Titan Phenomenon Generator Resistance Bonus problems.

### ISSUE THREAD

**Issue by jyxu2015** [pyfa-org/Pyfa#897]
According to https://forums.eveonline.com/default.aspx?g=posts&m=6686508#post6686508
http://i.imgur.com/sjiZRjK.png

================

After replacing the 4 changed files mentioned in https://github.com/pyfa-org/Pyfa/commit/7875c2acaa8770bfd9b5480b4bdd52759731f5a9
(I replaced them for multiple times and got the same result, not clear if there was anything wrong with my operation)

Test Results：http://i.imgur.com/2mq6RBU.png

Amarr Phenomenon Generator do not have the EM resistance nerf on armor and shield
Caldari Phenomenon Generator has an exceeded EM resistance bonus on armor and shield (19% vs should-be 10% )
And none of them affects the hull resistance.

**Comment by Ebag333** [comment]
>Whenever these bonuses apply to a stacking penalized attribute (such as resists) they are stacking penalized like a normal module. The resist ones are stacking penalized with hardeners/command bursts and stuff like that, rather than with DCUs and RAHs.

well that's.... somewhat helpful.

**Comment by blitzmann** [comment]
> Amarr Phenomenon Generator do not have the EM resistance nerf on armor and shield
I made an oops, corrected in the commit after this one: 0a28fb60df915

> Caldari Phenomenon Generator has an exceeded EM resistance bonus on armor and shield (19% vs should-be 10% )
Possibly due to penalties...?

> And none of them affects the hull resistance.
They should... I can't test right now though =(

@jyxu2015 do you have titans to test these things with?

**Comment by jyxu2015** [comment]
> Caldari  Phenomenon Generator has an exceeded EM resistance bonus on armor and shield (19% vs should-be 10% )
> Possibly due to penalties...?

Based on this: http://i.imgur.com/2mq6RBU.png

An erebus has a basic shield resistance 0/20/40/50, an armor resistance 50/35/25/10 and a Hull resistance 33/33/33/33

A naked erebus (no commander link, no equipment) under a gallente phenomenon generator which should give -15% resistance nerf on thermal damage and +10% resistance buff on explosive  damage: 
The shield thermal resistance should be 1-0.8*1.15=8% 
The armor thermal  resistance should be 1-0.65*1.15=25.25%
The shield explosive resistance should be 1-0.5*0.9=55%
The armor explosive resistance should be 1-0.9*0.9=19%
**The calculation result is the same as shown in PYFA**

And the calculation result of an erebus under minmatar phenomenon generator is also the same as shown in PYFA

a Caldari phenomenon generator which should give -15% resistance nerf on kinetic damage and +10% resistance buff on EM damage:
The shield EM resistance should be 1-1*0.9=10%, however, in the PYFA, it is shown to be 19%
The armor EM resistance should be 1-0.5*0.9=55%, in PYFA, it is 59.5%
Since 19%=1-1*0.9*0.9 and 59.5%=1-0.5*0.9*0.9....

I think the EM resistance bonus of a Caldari phenomenon generator may be used in the calculation for twice....which is different from all the other kinds of resistance bonus/nerf calculation ways.

Since there is no equipment and only one bonus(the generator), I think it may be a mistake or a typo in the code?

============


> They should... I can't test right now though =(
> 
> @jyxu2015 do you have titans to test these things with?

Sorry, my account in SISI and TQ could not fly a titan, but according to CCP Fozzie`s reply in the forum [here](https://forums.eveonline.com/default.aspx?g=posts&m=6686508#post6686508)

> MuraSaki Siki wrote:
> are the resist bonus and nerf affect shield/armor/hull all three?
> CCP fozzie: Yup, all three.

BTW, A friend told me just a moment ago that he asked some FCs of GSF and was told that the generator would affect the hull resistance. I then asked him for some screenshots or so but have not got any reply yet...I will update here as soon as I got response.
