### ISSUE TITLE
Dual propped ships with Projected effects from another ship allows the MWD and Afterburner to be enabled together.

### ISSUE THREAD

**Issue by GKFC** [pyfa-org/Pyfa#903]
For example:

- Start with this base fit:

[Dramiel, Dramiel_Fast]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

1MN Afterburner II
5MN Microwarpdrive II
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

Then create another ship with a Warp Scrambler on it, and add that to the Projected tab for the above ship.

If you enable the Afterburner and then the MWD, the Speed goes off the charts.  Obviously this won't work ingame, more of a cosmetic bug.

Cheers,

G.

**Comment by blitzmann** [comment]
I'll take a look at this as I have time, but it's not high priority. :)

**Comment by jtaylormayfield** [comment]
I cannot recreate this bug.

**Comment by DarkFenX** [comment]
Do not think so. Code related to these checks has been reworked in one of recent releases, most likely that's why.
