### ISSUE TITLE
Patch notes for YC118.10 release

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#904]
Two things to verify, one easy one more complicated.

- [ ] Reduced the mining yield of 'Excavator' Mining Drones by 32%.
- [ ] Changed the behavior of Defender Missiles, you can find out more here.
https://forums.eveonline.com/default.aspx?g=posts&t=501519

Defender missiles are changing a lot.  They also have unique fitting reqs, so we need to figure out how CCP is doing that.

**Comment by blitzmann** [comment]
There doesn't seem to be any mechanic changes. It's basically a missile that is targeted at bombs, but we don't handle that use case in pyfa, just like we don't handle the existing use case of shooting down missiles. Everything else (only attachable to ship groups, etc) should already be handled by the engine.

The most complicated thing (not really complicated at all) is converting existing missiles and launchers. So, should be an easy patch :D

**Comment by Ebag333** [comment]
Nope, pretty easy.  See #906
