### ISSUE TITLE
Another issue with Ice Harvester drones - yield displayed

### ISSUE THREAD

**Issue by Helothane** [pyfa-org/Pyfa#905]
I swear these things are going to be the death of you folks :)

It appears that the Drone Interfacing bonus of 10% bonus to ore mined for mining drones per level of the skill is being applied to the yield of these drones.  Unfortunately, that isn't the case since the unit size of ice is 1000m3.  Even at Drone Interfacing 5, which Pyfa is reporting 1500m3 mined, the end result will be 1000m3.

This goes for all versions of the Ice Harvester drones - t1, t2, augmented, excavator.

**Comment by blitzmann** [comment]
I think that fixed it... hopefully. Thanks for the report :)
