### ISSUE TITLE
Question: How do you package Pyfa for all environments?

### ISSUE THREAD

**Issue by resinneublem** [pyfa-org/Pyfa#911]
@blitzmann I'm just curious what your build process is when making the final releases. How do you package the app for each of the environments?

**Comment by Ebag333** [comment]
For Windows I _believe_ it's basically running the `setup.py` to generate an archive, then dropping it in here:
https://github.com/pyfa-org/Pyfa-skel

I'm not sure how much Mac/Linux differs.

**Comment by blitzmann** [comment]
I don't usually run setup.py.

The pyfa-skel repo houses the binary skeleton for windows and os x. What basically happens is that we copy the skeleton to a new directory, then copy the source files to that directory. Then we zip them up.

It's done via the dist.py script from the `scripts` directory: `python2 dist.py -s ../../pyfa-skel -b ../../pyfa-ro -d ../../ -z -w`

This allows us to avoid building on the platforms themselves every release, which is a pain in the ass.

**Comment by resinneublem** [comment]
Ah cool thanks. I don't need to make any changes, but I was just generally curious how that was done.

**Comment by blitzmann** [comment]
Also, @resinneublem, have you make a pyfa slack account yet? This types of questions can be discussed there instead of making issues about them here. I don't generally monitor most of the channels, but if you directly convo me I do get notifications about it. :)
