### ISSUE TITLE
Quitting pyfa after using CREST makes the app hang

### ISSUE THREAD

**Issue by ghost** [pyfa-org/Pyfa#925]
If I log in using CREST then quitting the app makes the app hang and I have to force quit it every time. If I don't log in then quitting the app doesn't hang it. Even if I log out before quitting the app it still hangs.

MacOS 10.12.2
pyfa 1.26.0

**Comment by Eylandt** [comment]
Didn't get any error output while running and quitting pyfa through terminal. Just a spinning beachball until I closed the app with ctrl+c.

PS: If I choose CREST->"Login to EVE" then every time this message pops up.
![screenshot 2017-01-01 12 39 55](https://cloud.githubusercontent.com/assets/7578126/21580893/f44d1396-d01f-11e6-9a27-cf22488c6fd6.png)
I've added pyfa to firewall settings already but it's still showing this message. Maybe those problems are somehow related but I'm not sure.

**Comment by resinneublem** [comment]
Yeah I can reproduce. I don't use the mac regularly anymore but I setup a macOS Sierra VM on non-mac hardware via http://www.wikigain.com/install-macos-sierra-10-12-virtualbox/

I also reproduced on linux though. So this isn't a mac-only issue.

I haven't dived into the CREST implementation but I wonder if the server code is actually shutting down.

After I click "Crest > Login to EVE":

> 2017-01-01 16:38:15,783 root                     DEBUG    Starting server
> 2017-01-01 16:38:15,783 service.server           DEBUG    Running server for 60 seconds
> Created new window in existing browser session.

And then when I finish the CREST login I see:

> ...
> 2017-01-01 16:34:19,727 root                     DEBUG    Stopping Server

Yet, if I run `netstat -a` I can still see a process is listening on port 6461.

This might be a problem on windows too, just less visible.

**Comment by resinneublem** [comment]
Also FWIW, if you click "Crest > Login to EVE" and DON'T login, the server will timeout after 60 seconds:

> 2017-01-01 16:39:15,862 service.server           DEBUG    Server timed out waiting for connection

And closing the app will close normally.

**Comment by blitzmann** [comment]
If it happens on Linux, then it just became a bit easier for me to debug and fix. No ETA on it ATM

**Comment by blitzmann** [comment]
97cdd751b8c11a7e1dd07175acb563a6c3bebddd should fix this. It was indeed a runaway thread. Hopefully this solves the issue across the various platforms. :)
