### ISSUE TITLE
GUI: User is able to spawn the rename dialog for All 5 character

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#930]
When the character editor first spawns, the user is able to click the rename button for All 5 and input text. Thanks to a recent PR by ebag, this text isn't saved, however this button should be disabled by default.

The issue likely lies in a logic error during initialization of the character editor window. We probably don't run the logic that determined whether the buttons should be disabled or not when the window spawns. Haven't checked. Low priority.

**Comment by Ebag333** [comment]
See #928 and #929 for some history.

**Comment by Ebag333** [comment]
>Thanks to a recent PR by ebag, this text isn't saved, however this button should be disabled by default.

The issue occurs after a specific series of steps.

1) Import a character file (used a EVEMon one that was causing problems, unknown if it's all imports or specific ones).
2) Open character editor window.
3) All 5 character is selected (as it should be).  Rename button is not grayed out (it should be).

This doesn't seem to happen with manually created chars, or if no other chars exist.  If you switch chars and then back to the All V char, the rename button grays out properly.

**Comment by blitzmann** [comment]
The import isn't necessary. This happens on even a fresh database.
