### ISSUE TITLE
Alliance tournament ships

### ISSUE THREAD

**Issue by AkiraWhitlock** [pyfa-org/Pyfa#935]
First time here.
I was curious about ships that have not yet been implemented  such as the Rabisu and Caedes if they were to be added to the database.

**Comment by blitzmann** [comment]
Oh shit, I totally forgot to assign them to a group. Will do that before the next release.

In the meantime, you can search for these ships in the fittings search. They should come up.

**Comment by blitzmann** [comment]
Ah, they are available in the ship browser, just under their actual groups: Caedes is under Covert Ops, and Rabisu is under Logistics.

They should be under Limited Edition, so I'll go ahead and make that change. :)

**Comment by AkiraWhitlock** [comment]
Ooh. did not see that since i never play with logistics/covert ops fittings. Thank you.

**Comment by blitzmann** [comment]
Gonna keep this open until that fix has been released with the next patch :)
