### ISSUE TITLE
Patch Notes 

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#936]
Just a reminder to check the effects for these. 

```
Standup Void Guided Bombs are now effected by Energy Warfare Resistance.
Super Weapons & Burst Projectors now respect Energy Warfare Resistance.
```

**Comment by blitzmann** [comment]
We don't deal with ewar resists yet, so this shouldn't be an issue. Everything else in the patch notes seem benign as well

**Comment by Ebag333** [comment]
These are all neut resists.

**Comment by blitzmann** [comment]
do we? I didn't think we did. ¯\_(ツ)_/¯

**Comment by Ebag333** [comment]
We do! We handle battery resist reductions, and capital neut sig radius reductions.  

We just need to make sure that these effects are being passed into `adddrain` properly, if they are then they're already handled.  But since burst projectors weren't working properly until a few days ago, I don't really trust it.

Plus CCP may change the effect/stats, so need to double check that.

**Comment by blitzmann** [comment]
@Ebag333 I've updated master to include the new database, however my diff is showing completely blank with respect to any attributes changing. If you can run a quick test on it when you get a chance, that'll be great. if you don't get to it I'll test before the next release.

**Comment by Ebag333** [comment]
They rolled the patch back, so there's no changes.....yet.

**Comment by blitzmann** [comment]
Ah, well that would be why. Thanks for the update :)

**Comment by Ebag333** [comment]
>there's no changes.....yet.

Rescheduled for the 12th.

**Comment by blitzmann** [comment]
Closing this as it's been merged to dev
