### ISSUE TITLE
Pyfa hangs up when EVE is opened

### ISSUE THREAD

**Issue by sport4Dev** [pyfa-org/Pyfa#937]
If pyfa is opened and nothing else is going on, it works fine. If I open pyfa when EVE is open, it gets all screwy. It gets hung up, acts all delayed, like takes 2 minutes for it it to obey a click.

I have tried everything I know, and cannot fix it. Of thats much, I have checked firewall, looked for any background stuff running, ...

I did not have this problem before the last update. 

Using Windows 10, AMD 8 core, 64-bit

Any suggestions?

**Comment by Ebag333** [comment]
what does your CPU, memory and disk look like while EVE is running? Can you get a screenshot of your stats?

**Comment by sport4Dev** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } When eve is running CPU is less than 2%, and other factors are low as well. It does not seem to be a hardware problem.This recently changed. Used to be able to run eve and pyfa at same time, no issues.
Now they are incompatible, it seems like software conflict. 
I can run eve and run YouTube, stream twitch browse websites whatever, but the second I run pyfa all goes to shit. Google web browser also gets affected.
I can run pyfa along side anything else, as mentioned above. But if I run out eve
Then all goes to shit.
I have to restart to get rid of the problem.
This problem only exists in conjunction with pyfa. 


Sent from Yahoo Mail for iPhone


On Saturday, January 7, 2017, 4:29 PM, Ebag333 <notifications@github.com> wrote:


what does your CPU, memory and disk look like while EVE is running? Can you get a screenshot of your stats?

**Comment by Ebag333** [comment]
>When eve is running CPU is less than 2%, and other factors are low as well. It does not seem to be a hardware problem.This recently changed. Used to be able to run eve and pyfa at same time, no issues.
>Now they are incompatible, it seems like software conflict. 
>I can run eve and run YouTube, stream twitch browse websites whatever, but the second I run pyfa all goes to shit. Google web browser also gets affected.
>I can run pyfa along side anything else, as mentioned above. But if I run out eve
>Then all goes to shit.
>I have to restart to get rid of the problem.
>This problem only exists in conjunction with pyfa. 

Tons of people (including myself) run Pyfa and EVE side by side.  If this were an issue with the application itself, we'd get *TONS* of reports.

You'll need to start troubleshooting and see what's causing the slow down.  Looking at Resource Explorer is a start, if you can identify what resource is being tapped out (CPU, Memory, or Hard Drive) then it can help isolate it.

Other common things to look for are antivirus, anti-malware, or any sort of special firewall software.  A lot of these are overly aggressive and can use up tons of resources.  Again, you should be able to get an idea of what's going on from using Resource Explorer.

It's very possible it's disk utilization. It doesn't take much to tap out that resource, and an aggressive AV can certainly trigger it.

**Comment by sport4Dev** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } So I figured I would try a reload, so I uninstalled and downloaded pyfa again.That did not fix it.Then I remembered I had recently changed to windowed mode.I changed Eve back to full screen mode, And that solved the problem.Things are back to normal...except I can not run in windowed mode.



Sent from Yahoo Mail for iPhone


On Saturday, January 7, 2017, 8:15 PM, Ebag333 <notifications@github.com> wrote:



When eve is running CPU is less than 2%, and other factors are low as well. It does not seem to be a hardware problem.This recently changed. Used to be able to run eve and pyfa at same time, no issues.
Now they are incompatible, it seems like software conflict.
I can run eve and run YouTube, stream twitch browse websites whatever, but the second I run pyfa all goes to shit. Google web browser also gets affected.
I can run pyfa along side anything else, as mentioned above. But if I run out eve
Then all goes to shit.
I have to restart to get rid of the problem.
This problem only exists in conjunction with pyfa.


Tons of people (including myself) run Pyfa and EVE side by side. If this were an issue with the application itself, we'd get TONS of reports.

You'll need to start troubleshooting and see what's causing the slow down. Looking at Resource Explorer is a start, if you can identify what resource is being tapped out (CPU, Memory, or Hard Drive) then it can help isolate it.

Other common things to look for are antivirus, anti-malware, or any sort of special firewall software. A lot of these are overly aggressive and can use up tons of resources. Again, you should be able to get an idea of what's going on from using Resource Explorer.

It's very possible it's disk utilization. It doesn't take much to tap out that resource, and an aggressive AV can certainly trigger it.

**Comment by Ebag333** [comment]
>Then I remembered I had recently changed to windowed mode.I changed Eve back to full screen mode, And that solved the problem.Things are back to normal...except I can not run in windowed mode.

Possibly a video card driver issue.

**Comment by sport4Dev** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Thanks, you may be on to something there. I reduced the graphic quality in game for eve.Once I optimized for performance, I was then able to run in windowed mode. But it looks like shit that way.
I will turn it up until it affects it again.Perhaps my graphics card is wearing out?
Thanks for the help



Sent from Yahoo Mail for iPhone


On Saturday, January 7, 2017, 9:14 PM, Ebag333 <notifications@github.com> wrote:



Then I remembered I had recently changed to windowed mode.I changed Eve back to full screen mode, And that solved the problem.Things are back to normal...except I can not run in windowed mode.


Possibly a video card driver issue.

**Comment by blitzmann** [comment]
This is very odd. I also have never had an issue running EVE and pyfa together. I run in in borderless windowed mode.

pyfa is not an efficient or fast program by any stretch of the imagination, but I have never heard of it interfering with other programs or causing acute system instability.

I agree with ebag - try to make sure all drivers are up to date for your system. AV also doesn't like pyfa sometimes, so there's that. I have no idea why pyfa would be the only program causing issue though.

Since it sounds like a localized issue regarding your environment, I'm gonna close this issue. Feel free to continue the conversation below. :)
