### ISSUE TITLE
If Pyfa install path changes, setting does not update

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#938]
Seems we don't actually update `settings.getPath` if it changes.  Found this trying to export a fit to HTML, when running from within pyCharm.  The original install directory where Pyfa was no longer exist, but the setting isn't updated.

https://puu.sh/thfQ2/1cb71d0b50.png

Should run a test when Pyfa launches and prompt the user to update it if the location is bad (or give them the option to cancel out if they *REALLY* want to keep the bad location).

**Comment by blitzmann** [comment]
This only affect the html export right?

**Comment by Ebag333** [comment]
I believe so.  Haven't done a deep dive yet to see what else might be using `settings.getPath`.

It also bugs me that we have 3 different places to do exports.

**Comment by blitzmann** [comment]
Looking at this again, this has nothing to do with the installed directory. The user themselves sets the path in preferences - if that path doesn't exist, they get this error which instructs them to verify the path. As this is working as intended, gonna close issue
