### ISSUE TITLE
[Suggestion] Colour code the ship fittings in the Graphs section as well.

### ISSUE THREAD

**Issue by GKFC** [pyfa-org/Pyfa#942]
Hi,

Really like using the Graphs feature, but sometimes with multiple fittings and changing variables frequently it can get a little confused as to which line represents which ship.

Having an easy visual way of showing that red = this fit, blue = this fit, green = this fit etc would be useful.

Cheers,

G.

**Comment by Ebag333** [comment]
Yes it does.

That's maybe/probably an easy feature, but I'm a bit hesitant to spend much time on graphs.  It's poorly implemented and has lots of issues, it really needs to be reworked from the ground up.

That being said, if you like graphs, hopefully we have more graphs on the way. :)

**Comment by GKFC** [comment]
Nice, looking forward to seeing them  :-)

They're useful to quickly compare damage application of similar fits when (e.g.) swapping webs / target painters / tracking computers etc.

What issues do they have currently though?

**Comment by Ebag333** [comment]
Slow, doesn't handle multiple graphs properly, boxes for values are hard coded (so can't remove/switch them...).

There is a long list.

**Comment by blitzmann** [comment]
Yeah... there's a lot we'd like to do with graphing, but it would be best to completely re-write it rather than tack on new shit on a broken codebase. However, this particular feature request may be easy to implement - next time I'm in the graph code I'll take a look at it :)

**Comment by Ebag333** [comment]
Fixed in  #974
https://puu.sh/tSa3l/85704bdbe9.png

Doesn't color code the ships in the pane on the bottom, but does give you a legend.

**Comment by blitzmann** [comment]
Looks good! Do you know which version we have currently loaded in our builds? (ie: can this thing run fine now, or does it require updates to builds?)

**Comment by blitzmann** [comment]
@GKFC I've merged in ebags changes to master, however it won't show with the current build of pyfa (we need to update a few libraries). But I wanted to get your feedback on the image he posted - is this what you had in mind?

**Comment by GKFC** [comment]
Thanks, yes this does help differentiate the multiple fits quite nicely.

My only feedback would be if (for example) there were multiple long range fits being shown?  Will the legend continue to mask the right hand side of the graph?  Or will it "fade out" until you mouseover the area or something?

Just thinking that if you're doing some comparisons of arty fits it might get awkward having the legend there constantly...

Or perhaps move it outside the graph area somewhere?  Just a thought.

Cheers,

G.

**Comment by Ebag333** [comment]
The window is resizable, so you should be able to move the window so it's not in the way. 

Unfortunately it has to stay on the graph, so our choices are limited to where it goes.

**Comment by GKFC** [comment]
Ah OK cool, interested to see it in action then  :-)

**Comment by DarkFenX** [comment]
Done in current master, you can pick colors as you want (just out of 8 though).
