### ISSUE TITLE
Some skills are not included in "Change Module Skills" tab

### ISSUE THREAD

**Issue by HurSungYun** [pyfa-org/Pyfa#944]
I think Surgical Strike affects DPS, but it does not appear on "Change Module Skills" tab when right-clicking hybrid turret.

As well as Trajectary Analysis.

**Comment by blitzmann** [comment]
![image](https://cloud.githubusercontent.com/assets/3904767/21933899/4dc8b0f2-d975-11e6-9ec6-b64dd3e95109.png)

Can you double check? It shows up fine for me. If it's still not showing up, please send me the `saveddata.db` file from your `%userprofile%/.pyfa/` directory to sable.blitzmann@gmail.com and direct me to which fit is having this issue. It might be an issue with how your character is saved in the DB, but I need the data to determine.

Thanks!

**Comment by HurSungYun** [comment]
@blitzmann I re-checked it and I found that it looks just like you.

I'm really sorry to give you wrong information and make you confused.

Thanks for answering me kindly. :)

**Comment by blitzmann** [comment]
No worries, glad it's working for you :)
