### ISSUE TITLE
Cap Booster timings, etc.

### ISSUE THREAD

**Issue by xoxfaby** [pyfa-org/Pyfa#959]
This is something I'm missing from EFT.

An estimate for how long X cap boosters will last you. It doesn't help me to know I can be cap stable using the boosters if I don't know how long they will last me. Should probably go off how many you have in your cargo.

Maybe you could also revisit this:

https://github.com/pyfa-org/Pyfa/issues/446

**Comment by xoxfaby** [comment]
Should work for everything used up by a module btw. how long certain ammo will last you, cap booster in shield boosters. etc.

**Comment by Ebag333** [comment]
Hmm. Interesting idea. 

Not sure where we'd put this info off hand, the misc columns are already quite cluttered. 

Oooooh, this could be implemented into Gnosis and shown on the graph. I like this idea....

**Comment by xoxfaby** [comment]
Maybe a colum in the cargo, for each item, showing how long it would take to be used up by the currently active modules.

**Comment by Ebag333** [comment]
I have to take a look at how cluttered the cargo is currently. 

The issue with showing it there is that we don't know which module it belongs to.   If I have two boosters, but one stack of charges, which booster do the charges belong to? 

We also do show you how much reps you get from one full cycle in the misc column, and over how long. So you get some of the info.... 

What I was thinking above, basically once you ran out of charges it'd be reflected here. 
https://puu.sh/shVqn/c2aa3d8b00.png

But again, we run into the issue of who owns what stacks.  That adds a ton of complexity.

**Comment by Ebag333** [comment]
I have an idea for implementing this, but it'll take a pretty big enhancement to Gnosis. It is something that I wanted to do anyway as I want to use it for a full simulation engine, but it'll take a bit of time to do.

**Comment by xoxfaby** [comment]
> The issue with showing it there is that we don't know which module it belongs to. If I have two boosters, but one stack of charges, which booster do the charges belong to?

Simple, all the modules specify which charges they are looking for. ( Cycle time * Number of charges + reload time ) let's you calculate the number of charges used per second. Add all of the modules up and you have an estimate of how long they will be able to run.

**Comment by Ebag333** [comment]
Sure, that's easy when you have  8 guns all using the same ammo. 

Now what do you do when you have 2-3 modules that all CAN use the same ammo, but may or may not be? Think having a cap booster and ASB with mixed cap charges in the hold.

**Comment by xoxfaby** [comment]
Dude, every fitting specifies which module is trying to use which charges.

**Comment by xoxfaby** [comment]
Module A: 
2s cycle  * 8 charges + 10s reload = 26 seconds for 8 charges, 8 / 26 = 0.30769 charges per second
M odule B:
5s cycle * 2 charges + 20s reload = 30 second for 2 charges, 2/30 = 0.066666 charges per second

With both modules active you use 0.374356 charges per second. 

100 charges will last you about 267 seconds

**Comment by xoxfaby** [comment]
I am not 100% sure if I did the math right there but even if I didn't you can just build the correct formula and use that

**Comment by xoxfaby** [comment]
> Now what do you do when you have 2-3 modules that all CAN use the same ammo, but may or may not be? Think having a cap booster and ASB with mixed cap charges in the hold.

And this is really no problem. You only have to calculate it for all the active modules that have this charge selected. If the ASB has cap booster 100 selected and the cap booster has navy cap booster 400's selected, you only calculate it for those in the cargo, where's the problem?

**Comment by Ebag333** [comment]
Right, so we know which one  to select at first. 

What happens when you run out of that type? Should the module poach ammo from another stack? 

Or what happens when modules run at different speeds? A cap booster and ASB use very different amounts of ammo.   Do you simply divide the cap charges in half, even though the ASB will use it much slower than the Booster? 

Thinking more about this, I think that the easiest solution is to provide this information in the popup. Something along the lines of if you hover over a stack of 100 cap charges, it says something like:
```
MASB: 10 minutes 
Cap Booster: 3 minutes
```

Then if you want to plan for your modules you can simply add different stacks sized appropriately. 

I'll have to see how feasible this is, and how much we can make it so we don't have to manually maintain a list.

**Comment by xoxfaby** [comment]
All of this was covered by my very simple formula. If you are constantly using both things, then your total cap chargers are being drained by both modules, just at a different total rate. I'm sure if you wanted to you could adjust the formula to only work in amounts of full reloads, but for most approximations my approach would be fine. 

And "what happens when you run out" isn't a consideration if you attach the calculation to the STACK of charges in the carge. If the stack ran out, that's it. If you wanna see how long you could last on both, you put both in your cargo and then look at each and see. "oh, 200's would last me 3 minutes, 100 would last me 1 minute, if I run out of 200's I can use 100's for a minute. my ASB runs out of 100's in 10 minutes so I'll have so and so many left. really not that hard once you have it calculating anything.

**Comment by Ebag333** [comment]
>And "what happens when you run out" isn't a consideration if you attach the calculation to the STACK of charges in the cargo

Cargo and modules have no knowledge of each other currently.

**Comment by xoxfaby** [comment]
All you have to do is call which modules are on the ship that use this type of charge and make the calculations, that should be a couple of function calls at the most, lol.

**Comment by Ebag333** [comment]
You  make it sound so easy. Why not give it a go? Pyfa is open source, and I'd love to learn how to do it with just a few function calls. 😊

**Comment by xoxfaby** [comment]
Because I'm not familiar with the code and it would take me much longer than someone who is?

**Comment by Ebag333** [comment]
Probably true, but I've got a few irons in the fire myself.
https://github.com/pyfa-org/Pyfa/pulls

And I'm probably keeping @blitzmann busy reviewing all those PRs. 😁

**Comment by xoxfaby** [comment]
Lol

anyways, the actual algoritms are really simple as I pointed out above. You just have to implement them into the program, which is the "hard" part, but even then it shouldn't be hard at all.

**Comment by Ebag333** [comment]
Not exactly what you want, but it sure is easy. :)

https://puu.sh/tEQIG/f0a4bec708.gif

**Comment by Ebag333** [comment]
It's been long bugging me that the Remote Ancil reppers didn't show the same stats (as well as cap boosters)....so...well...that's fixed now.

Slipped in what you asked for.  Not exactly, but should be close enough so you can get a good guesstimate as to how many charges to put in your cargo.

**Comment by blitzmann** [comment]
Merged PR from @Ebag333 addressing this feature
