### ISSUE TITLE
Windows line feed error in 1.26.1 on Ubuntu 16.10 x64 execution error

### ISSUE THREAD

**Issue by qnub** [pyfa-org/Pyfa#964]
Can't run https://github.com/pyfa-org/Pyfa/releases/download/preview_backend/pyfa-20170130-6049c9-linux.zip:
`/usr/bin/env: «python\r»:` file not found. 

When i've resave file with unix `\n` line feed it executes succefully.

**Comment by blitzmann** [comment]
@ebag333 does this have anything to do with line ending changes

@qnub is this only for pyfa.py, or another file?

**Comment by qnub** [comment]
Only pyfa.py raises error, as main script with shebang sequences. Think even if other files have `\r\n` line endings it's ok for python… At least i've not checked other files.

**Comment by Ebag333** [comment]
>does this have anything to do with line ending changes

It might, but we have other users on Linux and haven't heard this. 

It also seems weird that it'd be a issue for Pyfa.py and nothing else.

**Comment by blitzmann** [comment]
@qnub can you give us the command being used to run pyfa and the full error that prints out in terminal

**Comment by qnub** [comment]
```
$ /media/2TB/gamez/pyfa/pyfa.py
/usr/bin/env: «python\r»: Нет такого файла или каталога
```

**Comment by Ebag333** [comment]
>No such file or directory

I wonder if it's the environment. What path is Python installed into?

**Comment by qnub** [comment]
It's standard `apt` installation. But how change lineendings can affect on python path? When i change `\r\n` to `\n` it works without any system changes…

**Comment by Ebag333** [comment]
If universal line ending support was turned off, that would explain it.

https://www.python.org/dev/peps/pep-0278/

>```
Universal newline support can be disabled during configure because it does have a small performance penalty, and moreover the implementation has not been tested on all conceivable platforms yet. It might also be silly on some platforms (WinCE or Palm devices, for instance). If universal newline support is not enabled then file objects do not have the "newlines" attribute, so testing whether the current Python has it can be done with a simple:

if hasattr(open, 'newlines'):
   print 'We have universal newline support'
Note that this test uses the open() function rather than the file type so that it won't fail for versions of Python where the file type was not available (the file type was added to the built-in namespace in the same release as the universal newline feature was added).

Additionally, note that this test fails again on Python versions >= 2.5, when open() was made a function again and is not synonymous with the file type anymore.
```

Not sure off hand how you'd test it.

**Comment by blitzmann** [comment]
@DarkFenX you normally run linux IIRC, can you take a look at the pre-release and see if it runs for you / have any ideas on how to fix it? Is it as simple as saving with a certain line ending? It's odd that we've never run into this before.

I'll try on my linux VM tonight as well.

**Comment by Ebag333** [comment]
@qnub try this bit of python code:
```
if hasattr(file, 'newlines'):
   print 'We have universal newline support'
```

**Comment by qnub** [comment]
```
$ ./pyfa.py  
We have universal newline support
```

**Comment by qnub** [comment]
I think it's not about python, but about bash. Whe bash reab shebang it tryed to execute last part of script in target interptreter. And iterpreter here is `python\r`. Because newline for bash is `\n` not `\r\n`. Python itself can use any newline…

**Comment by qnub** [comment]
If i run `python pyfa.py` in execute flawless wit any wersion of newline. If i run `./pyfa.py` itself (because it have shebang and can be set as executable file) it raise error that `python\r not found`. Got it?

**Comment by blitzmann** [comment]
@qnub ... I kinda got it. Sorry, when I run pyfa in linux I run it via `python pyfa.py`, I never try to run the script itself. I am not too familiar with the nuances of linux scripting (such as the shebang to make the script itself executable)

I'm hopping on my VM right now to try to figure it out. One question: `python\r ` what does the `\r` signify?

**Comment by qnub** [comment]
Is invicible newline codes. OSes have dofferent newline codes. Here is detailed info https://en.wikipedia.org/wiki/Newline but in windows to mark end of line uses sequense of two symbols `CR` and `LF` or in different notation is `\r\n`. In *nix systems in only `LF` or `\n`.

As you can see bash think that `\r` form `\r\n` sequense in the end of line is meaning symbol of `python` word and `\n` is line ending mark… So you need to save `pyfa.py` file witn unix line nedings or remove this shebang comment (`#!/usr/bin/env python` 👈 this part) from the beginning of file because it's meant that script can be set as executeable in *nix, but it's not work…

**Comment by qnub** [comment]
More info about shebang https://en.wikipedia.org/wiki/Shebang_(Unix)

**Comment by blitzmann** [comment]
> As you can see bash think that \r form \r\n sequense in the end of line is meaning symbol of python word and \n is line ending mark… 

ohhhh, so it reads this line:

`#!/usr/bin/env python`

but with the return it looks like this:

`#!/usr/bin/env python\r\n`

And only the `\n` is interpreted leaving 

`#!/usr/bin/env python\r`

That makes a lot more sense now... Thank you!

**Comment by blitzmann** [comment]
I think this has been fixed in the latest master build. I added something to `.gitattributes` that will always save `pyfa.py` with LF line endings.
