### ISSUE TITLE
Make the Fittings search input box shown by default

### ISSUE THREAD

**Issue by Josemaloco** [pyfa-org/Pyfa#982]
Small feature (and silly, I know) request. I haven´t been using this app for too long, but is there any reason why you have to click the rather small magnifying glass in the fitting tab to show the search input?

![PYFA Fitting search](http://i.imgur.com/cuuFRCF.png)

Looks like it could work like in the market tab, and be shown by default to avoid the click every time you want to look for a fit (at least for us that use PYFA mostly to manage fittings)

It could also automatically put the cursor on the search box (on tab change between Market and Fittings). 
"Should" not affect normal operation, since all hotkeys work even with the inputbox focused.

I think it could improve usability a bit.

**Comment by Ebag333** [comment]
I'm not sure why we hide it.  It'd  make a lot more sense to leave it up, and have a X to the right to clear it.

I think the idea was to keep the interface from being cluttered, which has value, but having your UI as static as possible also has value.

>It could also automatically put the cursor on the search box (on tab change between Market and Fittings).

This in particular I disagree with.  We should never take control away from users.  Especially for users such as myself who rarely uses the search box, and flips between tabs often.

**Comment by blitzmann** [comment]
CTRL+F brings up the search box and focuses it for you so that you can immediately start typing. This should be pretty intuitive since most every program has a CTRL+F find feature.

Also: CTRL-F works on Market Browser as well. CTRL-SPACE switches between the two tabs.

Knowing these shortcuts, do you think that would be sufficient for your use cases (I could also put a note on search button tooltip to tell users the shortcut is possible)? Honestly, I don't want to muck with this 
and try to find another place for the button tooltips that currently show up in that space.

**Comment by Josemaloco** [comment]
>CTRL+F brings up the search box and focuses it for you so that you can immediately start typing. This should be pretty intuitive since most every program has a CTRL+F find feature.

Thats very useful. No idea why I though it wouldn´t work before trying first, thanks.


> This in particular I disagree with. We should never take control away from users. Especially for users such as myself who rarely uses the search box, and flips between tabs often.

I though so myself, too. Take this with a grain of salt because as I said, I havent used the program extensively, but right now typing has no function while in the Fittings tab, am I right? 
I would like to see some use of typing while in Fittings, but then again making the Fittings and Market tabs work differently would be counterintuitive, so maybe its better to leave it as it is and work with Ctrl + F.


On a semi related note, a small panel showing the last ships that the user used might be useful. It could fit below the Fitting ship list with the possibility of hiding it. 
Behold my paint skills:

![PYFA Last ships fitted](http://i.imgur.com/aUr5Ajt.png)
Clicking on any of them would open the relevant ship fittings in the upper panel, as usual.

All this would be quite a bit more work though.

**Comment by blitzmann** [comment]
> right now typing has no function while in the Fittings tab, am I right?
we don't capture all keyboard input and immediately start a search, no. But, as stated, CTRL+F does automatically put focus onto the search box, :) I think we're going to keep it the way it is (and I'll add a small bit of text to the tooltip)

>On a semi related note, a small panel showing the last ships that the user used might be useful. 
Now this is a feature request that I like, and I don't know why no one has ever brought it up before. It would be more difficult though as you said, and we would have to modify the database a bit (we don't currently store a timestamp when modifying fit). I'm going to close this issue and open up another one for this specifically. 

Thanks!
