### ISSUE TITLE
List of recently modified fits

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#983]
see https://github.com/pyfa-org/Pyfa/issues/982#issuecomment-279127262

I don't know if it's best to have a panel or button to toggle the view. The default ship Category listing is quite large to begin with and I think being able to hide this might be a good idea.

Additionally, we don't ahve any way of pulling back recently changed fits. We don't have a modified timestamp on fits, nor a last opened timestamp. We only have a created timestamp, which I don't believe works well with this.

**Comment by Ebag333** [comment]
I believe that a certain smart person recently suggested adding a modified column to tables. 😁
