### ISSUE TITLE
Do not recalculate fit when simply switching tabs

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#987]
Right now, if you have two fits open, switching between the two recalculates them every time. This was initially done intentionally to allow fits that were affected by other fits to update correctly (fit A is projecting onto fit B, fit A has a change, when we switch over to Fit B we recalc to ensure we always get that change)

However, most of the times fits don't have anything to do with one another. We should be smarter about this, as this can cause pyfa to be perceived as slow.

Plan:
1) When a fit is calculated, it sets a flag `__calculated = True`., 
2) When the fit is calculating, it goes through all fits that it affects (is the command booster or projected fit), and set those fits as `__calculated == False`. That way, when we switch back to the other fit, we can pick up that it's no longer calculated.

Seems easy, but the whole fit loading / switching / and calculation workflow is kind of a mess. It will require more work and research into what data is loaded at what time, what events are being used, etc, and extensive testing to make sure that calculations are being updated correctly and are sound.

**Comment by Ebag333** [comment]
>Seems easy

doesn't sound easy to me. lol

**Comment by blitzmann** [comment]
In the same light, I believe we currently calculate character every run as well, even if skills have been static. Should look at this as well, but lower priority to fit calc caching.
