### ISSUE TITLE
Change quantity window - Enter does not close window

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#991]
## Bug Report
When hitting enter on cargo change quantity popup, quantity changes but window doesn't close.

### Expected behavior:
Enter changes quantity and closes window

### Actual behavior:
Enter changes quantity, but does not close window.

### Detailed steps to reproduce:
Add item to cargo. Right click, change quantity. Enter amount. Hit enter.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
N/A

### Release or development git branch? Please note the release version or commit hash:
Development.

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
https://puu.sh/u3xQH/788cf05572.gif

**Comment by blitzmann** [comment]
Nice catch, thanks!
