### ISSUE TITLE
Launch error - Special characters in path

### ISSUE THREAD

**Issue by Eiden2004** [pyfa-org/Pyfa#997]
Update to new version, and catch this error.

![image](https://cloud.githubusercontent.com/assets/3904767/23068847/3390dfc2-f4f3-11e6-9fa9-75ee8a10696d.png)

blitzmann edit: updated image to SFW version >_>

**Comment by blitzmann** [comment]
This looks like an encoding issue. Can you paste here your user directory path?

@Ebag333 probably something happening with the new path definitions

**Comment by Ebag333** [comment]
Not an encoding issue. 

Using the new logging but pointing to log.txt?  I'm guessing bad merge.

**Comment by Ebag333** [comment]
@Eiden2004 what's the path that you're using?

I see it thinks it's `C:\Users\xc4\xe5\xed\.pyfa`.  Can you post your actual path here?

**Comment by GoshaEgorian** [comment]
The same error.
Actual path is "C:\Program Files (x86)\pyfa\pyfa.exe"
User path: "C:\Users\Гоша Егорян\.pyfa"
![default](https://cloud.githubusercontent.com/assets/8870929/23075502/c41f62ac-f54d-11e6-86de-e083952d54c1.png)

**Comment by Ebag333** [comment]
`C:\Users\Гоша Егорян.pyfa`
or
`C:\Users\Гоша Егорян\.pyfa`

I'm hoping you just forgot the slash, otherwise that's all sorts of weird. :)

**Comment by GoshaEgorian** [comment]
@Ebag333 it's github interface. Slash is there, I corrected it

**Comment by Ebag333** [comment]
Thanks.  I'll see if I can replicate this.

**Comment by blitzmann** [comment]
> Don't think it's an encoding issue. 

\xe3 and stuff like that is almost always encoding issue, for example can't find the correct encoding.

**Comment by blitzmann** [comment]
Also, what language is this? Hebrew?

**Comment by Ebag333** [comment]
Russian I believe (at least in the second example).

**Comment by Ebag333** [comment]
@GoshaEgorian @Eiden2004 

Can either of you screenshot this?

View the System Locale settings for Windows
1. Click Start, then Control Panel
2. Click Clock, Language and Region
3. Windows 10, Windows 8: Click Region 
Windows 7: Click Region and Language
Windows XP: Click Regional and Language Options 
4. The Region and Language options dialog appears.
5. Click the Administrative tab
On Windows XP, click the Advanced tab 

https://puu.sh/u7GtB/f9378efa24.png

**Comment by blitzmann** [comment]
@Eiden2004 @GoshaEgorian Did pyfa work for you guys previously?

**Comment by Eiden2004** [comment]
Pyfa118 works normally.

Path to pyfa119
https://gyazo.com/cc3f3d7371760db2b5def66803565c5e

Regional standarts are Russian ( but im from Ukraine )
https://gyazo.com/74258313efcdd7f71833515c6ee14ab4

**Comment by Ebag333** [comment]
I  submitted a PR that  I believe will fix this. #999 

Before we were only accounting for Unicode,  UTF-8, and cp1252 (Windows default).  We were missing cp1251, which is Russian on Windows.

Not sure how we weren't seeing issues previously with this.  Must have gotten lucky with the characters in your username, because we certainly weren't handling it (and it was a long known issue that certain characters would break it).

**Comment by blitzmann** [comment]
This is going to take some time to research. I don't particularly like ebags solution: it's brute forced, feels hacky, and I feel there should be a better, easier way, although what he is doing should work... pyfa can't be the only project to have this issue with special characters in path, and I want to see if there are any third party libraries we can utilize that help with this going forward. 

I'll make a build with the proposed solution from ebag for you guys to test as well, just to see if it performs the way it should.

**Comment by blitzmann** [comment]
I also want to see / research if there is a difference in results running via pyCharm vs binaries.

**Comment by Ebag333** [comment]
>I also want to see / research if there is a difference in results running via pyCharm vs binaries.

With my hacky brute forced terrible solution?  Or are you talking about rebuilding the skeleton.

Need me to build a package? I can do that now! (For Windows at least.)

**Comment by GoshaEgorian** [comment]
`pyfa 1.26.0 Stable - YC118.10 1.2` work normaly
Language is Russian. I already have got ploblems with rus letters in username when launch other programs.
![default](https://cloud.githubusercontent.com/assets/8870929/23092946/ec3d4cb0-f5e6-11e6-882b-e47569a1c053.png)

**Comment by blitzmann** [comment]
This is been fixed by reverting the path changes we put into place for 1.27. I'll make a release this weekend - if you guys still have issues after that, please report them again. :)
