### ISSUE TITLE
Bug: CREST Integration Fails

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#998]
In `crest.py`

```
    def handleLogin(self, message):
        if not message:
            raise Exception("Could not parse out querystring parameters.")
```

`message` always comes in as blank.  Tried reverting `crest.py`, no change to behavior.  Believe issue lies in `server.py` changes to threading, but haven't confirmed.  Possibly due to server stopping to quickly.

This is happening in Master and most recent build.

**Comment by blitzmann** [comment]
Confirmed, though it only seems to happen with implicit mode, which unfortunately is the more popular of the two

**Comment by Lozzyg** [comment]
I now have this issue since upgrading to 1.27

**Comment by MHacker9404** [comment]
I now have this issue since upgrading to 1.27

**Comment by blitzmann** [comment]
Yep, a new release will be coming this weekend to address this issue as well as the other fixed issues on the issue page :)
